function [plan, count] = attributionApplyEvidencePlan(conn, plan, transaction)
%ATTRIBUTIONAPPLYEVIDENCEPLAN Atomically append long-form evidence rows.
%
% TRANSACTION "own" (default) commits here; "caller" joins the caller's open
% transaction and leaves commit and rollback to the caller.

if nargin < 3
    transaction = "own";
end
if plan.has_conflicts
    error("vawlume:attribution:PlanConflict", ...
        "An evidence plan with conflicts cannot be applied.");
end
count = height(plan.evidence);
if transaction == "caller"
    attributionRequireCallerTransaction(conn, "Evidence apply");
    plan = writeEvidence(conn, plan);
    return
end
oldAutoCommit = string(conn.AutoCommit);
if oldAutoCommit ~= "on"
    error("vawlume:attribution:TransactionState", ...
        "Evidence apply requires a connection with AutoCommit enabled.");
end
conn.AutoCommit = "off";
try
    plan = writeEvidence(conn, plan);
    commit(conn);
catch exception
    try
        rollback(conn);
    catch
    end
    conn.AutoCommit = oldAutoCommit;
    rethrow(exception);
end
conn.AutoCommit = oldAutoCommit;
end

function plan = writeEvidence(conn, plan)
for index = 1:height(plan.evidence)
    row = plan.evidence(index, :);
    evidenceId = attributionInsertRow(conn, "attribution_evidence", ...
        struct(attribution_target_id=row.attribution_target_id, ...
        attribution_candidate_id=row.attribution_candidate_id, ...
        evidence_dimension=row.evidence_dimension, ...
        evidence_kind=row.evidence_kind, value_real=row.value_real, ...
        value_text=row.value_text, value_units=row.value_units, ...
        value_semantics=row.value_semantics, ...
        identity_statement_kind=row.identity_statement_kind, ...
        tracking_identity_association_id= ...
            row.tracking_identity_association_id, ...
        external_event_id=row.external_event_id, ...
        alignment_run_id=row.alignment_run_id, ...
        source_file_id=row.source_file_id, ...
        mapping_profile_version_id=row.mapping_profile_version_id, ...
        source_locator=row.source_locator, notes=row.notes, ...
        attribution_localization_estimate_id= ...
            row.attribution_localization_estimate_id, ...
        recording_channel_id=row.recording_channel_id, ...
        derived_measurement_id=row.derived_measurement_id), ...
        "attribution_evidence_id");
    plan.evidence.attribution_evidence_id(index) = evidenceId;
end
end
