function plan = attributionBuildPlan(conn, recordingRef, runSpec)
%ATTRIBUTIONBUILDPLAN Resolve one immutable run, its sources, subjects, targets.

plan = struct();
plan.context = validateRunSpec(runSpec);
plan.recording = attributionResolveRecording(conn, recordingRef);
plan.settings_profile = resolveSettingsProfile(conn, plan.recording, ...
    plan.context.settings_profile_version_id);
plan.target_set = attributionResolveTargetSet(conn, plan.recording, ...
    plan.context.target_set);
[plan.participating_entity_ids, plan.participating_entities, ...
    plan.participating_links] = attributionResolveParticipants( ...
    conn, plan.recording, runSpec);
plan.input_sources = attributionResolveSources(conn, plan.recording, runSpec);
[plan.parent_attribution_run_id, plan.parent_analysis_run_id] = ...
    resolveParent(conn, plan.recording, plan.context.parent_attribution_run_id);
plan.analysis_extraction_inputs = extractionInputs(plan.target_set.event_set);
plan.analysis_sources = analysisSources(plan.target_set.event_set, ...
    plan.input_sources.analysis_run_ids);
plan.provenance = provenanceSnapshot(plan);
plan.provenance_json = string(jsonencode(plan.provenance));
[plan.analysis, plan.run, storedTargets] = resolveExisting(conn, plan);
if plan.run.action == "reuse"
    plan.target_set.targets = storedTargets;
end
plan.conflicts = strings(0, 1);
plan = appendConflict(plan, plan.analysis.conflict_message);
plan = appendConflict(plan, plan.run.conflict_message);
plan.has_conflicts = ~isempty(plan.conflicts);
end

function context = validateRunSpec(runSpec)
required = ["run_key", "attribution_path", "method", ...
    "settings_profile_version_id", "target_set", "sources"];
for name = required
    if ~isfield(runSpec, name)
        error("vawlume:attribution:RunSpecInvalid", ...
            "runSpec.%s is required.", name);
    end
end
path = scalarText(runSpec.attribution_path, "runSpec.attribution_path");
if path ~= "imported"
    error("vawlume:attribution:RunSpecInvalid", ...
        "Phase 4 creates imported attribution runs only; '%s' belongs to a later path.", path);
end
if ~isstruct(runSpec.target_set) || ~isscalar(runSpec.target_set)
    error("vawlume:attribution:RunSpecInvalid", ...
        "runSpec.target_set must be a scalar struct.");
end
context = struct( ...
    run_key=scalarText(runSpec.run_key, "runSpec.run_key"), ...
    attribution_path=path, ...
    method=scalarText(runSpec.method, "runSpec.method"), ...
    settings_profile_version_id=positiveInteger( ...
        runSpec.settings_profile_version_id, ...
        "runSpec.settings_profile_version_id"), ...
    target_set=runSpec.target_set, ...
    parent_attribution_run_id=optionalIdentifier(runSpec, ...
        "parent_attribution_run_id"), ...
    run_label=optionalText(runSpec, "run_label"), ...
    vawlume_version=optionalText(runSpec, "vawlume_version"), ...
    source_commit=optionalText(runSpec, "source_commit"), ...
    notes=optionalText(runSpec, "notes"));
end

function profile = resolveSettingsProfile(conn, recording, profileVersionId)
rows = fetch(conn, "SELECT cpv.profile_version_id, cpv.profile_id, " + ...
    "cp.profile_key, cp.profile_kind, IFNULL(cp.project_id,-1) AS project_id, " + ...
    "cpv.version_label, cpv.content_uri, " + ...
    "IFNULL(cpv.checksum_sha256,'') AS checksum_sha256, cpv.is_snapshot " + ...
    "FROM config_profile_versions cpv JOIN config_profiles cp " + ...
    "ON cp.profile_id=cpv.profile_id WHERE cpv.profile_version_id=" + ...
    string(profileVersionId));
if isempty(rows) || height(rows) == 0
    error("vawlume:attribution:SettingsProfileNotFound", ...
        "settings_profile_version_id %d does not exist.", profileVersionId);
end
projectId = double(rows.project_id(1));
checksum = presentText(rows.checksum_sha256(1));
checksumCharacters = char(checksum);
checksumOkay = strlength(checksum) == 64 && ...
    all(ismember(checksumCharacters, ['0':'9' 'A':'F' 'a':'f']));
if (projectId >= 0 && projectId ~= recording.project_id) || ...
        double(rows.is_snapshot(1)) ~= 1 || ~checksumOkay
    error("vawlume:attribution:SettingsProfileInvalid", ...
        "The settings profile must be a checksum-bearing snapshot in this project or built in.");
end
profile = struct(profile_version_id=double(rows.profile_version_id(1)), ...
    profile_id=double(rows.profile_id(1)), ...
    profile_key=presentText(rows.profile_key(1)), ...
    profile_kind=presentText(rows.profile_kind(1)), ...
    version_label=presentText(rows.version_label(1)), ...
    content_uri=presentText(rows.content_uri(1)), checksum_sha256=checksum);
end

function [parentAttributionId, parentAnalysisId] = resolveParent( ...
        conn, recording, requestedId)
parentAttributionId = NaN;
parentAnalysisId = NaN;
if isnan(requestedId)
    return
end
rows = fetch(conn, "SELECT atr.attribution_run_id, atr.analysis_run_id, " + ...
    "ar.project_id FROM attribution_runs atr JOIN analysis_runs ar " + ...
    "ON ar.analysis_run_id=atr.analysis_run_id WHERE atr.attribution_run_id=" + ...
    string(requestedId));
if isempty(rows) || height(rows) == 0 || ...
        double(rows.project_id(1)) ~= recording.project_id
    error("vawlume:attribution:ParentRunInvalid", ...
        "The parent attribution run must exist in the same project.");
end
parentAttributionId = double(rows.attribution_run_id(1));
parentAnalysisId = double(rows.analysis_run_id(1));
end

function rows = extractionInputs(eventSet)
if eventSet.source_kind == "extraction_run"
    rows = table(eventSet.source_id, "target_event_set", ...
        VariableNames=["extraction_run_id", "input_role"]);
else
    rows = table(zeros(0, 1), strings(0, 1), ...
        VariableNames=["extraction_run_id", "input_role"]);
end
end

function rows = analysisSources(eventSet, directIds)
targetIds = zeros(0, 1);
if eventSet.source_kind == "analysis_run"
    targetIds = eventSet.source_id;
end
ids = unique([double(directIds(:)); double(targetIds(:))]);
roles = strings(numel(ids), 1);
for index = 1:numel(ids)
    isDirect = ismember(ids(index), directIds);
    isTarget = ismember(ids(index), targetIds);
    if isDirect && isTarget
        roles(index) = "target_event_set_and_attribution_input";
    elseif isTarget
        roles(index) = "target_event_set";
    else
        roles(index) = "attribution_input";
    end
end
rows = table(ids, roles, VariableNames=["source_analysis_run_id", ...
    "dependency_role"]);
end

function value = provenanceSnapshot(plan)
value = struct( ...
    schema="vawlume.attribution.run_provenance.v1", ...
    source_file_ids=rowVector(plan.input_sources.source_file_ids), ...
    artifact_ids=rowVector(plan.input_sources.artifact_ids), ...
    external_stream_ids=rowVector(plan.input_sources.external_stream_ids), ...
    source_analysis_run_ids=rowVector(plan.input_sources.analysis_run_ids), ...
    participating_entity_ids=rowVector(plan.participating_entity_ids), ...
    recording_entity_link_ids=rowVector( ...
        plan.participating_links.recording_entity_link_id), ...
    target_kind=plan.target_set.event_set.kind, ...
    target_source_kind=plan.target_set.event_set.source_kind, ...
    target_source_id=plan.target_set.event_set.source_id, ...
    target_ids=rowVector(plan.target_set.event_set.target_ids), ...
    agreement_extent_method= ...
        plan.target_set.event_set.agreement_extent_method, ...
    user_notes=plan.context.notes);
end

function value = rowVector(raw)
value = reshape(double(raw), 1, []);
end

function [analysis, run, storedTargets] = resolveExisting(conn, plan)
analysis = struct(action="create", analysis_run_id=NaN, ...
    parent_analysis_run_id=plan.parent_analysis_run_id, ...
    run_type="caller_attribution", run_key=plan.context.run_key, ...
    conflict_message="");
run = struct(action="create", attribution_run_id=NaN, ...
    analysis_run_id=NaN, recording_id=plan.recording.recording_id, ...
    parent_attribution_run_id=plan.parent_attribution_run_id, ...
    settings_profile_version_id=plan.settings_profile.profile_version_id, ...
    run_key=plan.context.run_key, attribution_path=plan.context.attribution_path, ...
    method=plan.context.method, status="planned", conflict_message="");
storedTargets = plan.target_set.targets;
rows = fetch(conn, "SELECT analysis_run_id, run_type, status, " + ...
    "IFNULL(parent_analysis_run_id,-1) AS parent_analysis_run_id " + ...
    "FROM analysis_runs WHERE project_id=" + string(plan.recording.project_id) + ...
    " AND run_key=" + sqlText(plan.context.run_key));
if isempty(rows) || height(rows) == 0
    return
end
analysis.analysis_run_id = double(rows.analysis_run_id(1));
analysis.action = "reuse";
storedParent = double(rows.parent_analysis_run_id(1));
expectedParent = plan.parent_analysis_run_id;
if isnan(expectedParent), expectedParent = -1; end
if presentText(rows.run_type(1)) ~= "caller_attribution" || ...
        ~ismember(presentText(rows.status(1)), ["started", "completed"]) || ...
        storedParent ~= expectedParent
    analysis.action = "conflict";
    analysis.conflict_message = "Analysis run_key '" + ...
        plan.context.run_key + "' exists with incompatible type, status, or parent.";
end

attribution = fetch(conn, "SELECT attribution_run_id, recording_id, " + ...
    "IFNULL(parent_attribution_run_id,-1) AS parent_attribution_run_id, " + ...
    "run_key, attribution_path, method, " + ...
    "IFNULL(settings_profile_version_id,-1) AS settings_profile_version_id, " + ...
    "status, IFNULL(notes,'') AS notes FROM attribution_runs " + ...
    "WHERE analysis_run_id=" + string(analysis.analysis_run_id));
if isempty(attribution) || height(attribution) ~= 1
    run.action = "conflict";
    run.conflict_message = "Analysis run_key '" + plan.context.run_key + ...
        "' has no single compatible attribution run.";
    return
end
run.attribution_run_id = double(attribution.attribution_run_id(1));
run.analysis_run_id = analysis.analysis_run_id;
run.action = "reuse";
expectedAttributionParent = plan.parent_attribution_run_id;
if isnan(expectedAttributionParent), expectedAttributionParent = -1; end
identityOkay = double(attribution.recording_id(1)) == ...
    plan.recording.recording_id && ...
    double(attribution.parent_attribution_run_id(1)) == expectedAttributionParent && ...
    presentText(attribution.run_key(1)) == plan.context.run_key && ...
    presentText(attribution.attribution_path(1)) == plan.context.attribution_path && ...
    presentText(attribution.method(1)) == plan.context.method && ...
    double(attribution.settings_profile_version_id(1)) == ...
        plan.settings_profile.profile_version_id && ...
    ismember(presentText(attribution.status(1)), ["planned", "complete"]) && ...
    presentText(attribution.notes(1)) == plan.provenance_json;
profileOkay = profileLinkMatches(conn, analysis.analysis_run_id, ...
    plan.settings_profile.profile_version_id);
extractionOkay = extractionInputsMatch(conn, analysis.analysis_run_id, ...
    plan.analysis_extraction_inputs);
sourcesOkay = analysisSourcesMatch(conn, analysis.analysis_run_id, ...
    plan.analysis_sources);
storedTargets = attributionReadTargets(conn, run.attribution_run_id);
targetsOkay = attributionTargetsEqual(storedTargets, plan.target_set.targets);
if ~(identityOkay && profileOkay && extractionOkay && sourcesOkay && targetsOkay)
    run.action = "conflict";
    run.conflict_message = "Attribution run_key '" + plan.context.run_key + ...
        "' exists with different settings, sources, participants, or targets.";
end
end

function okay = profileLinkMatches(conn, analysisId, profileVersionId)
rows = fetch(conn, "SELECT profile_version_id, assignment_role " + ...
    "FROM analysis_run_profiles WHERE analysis_run_id=" + string(analysisId));
okay = height(rows) == 1 && ...
    double(rows.profile_version_id(1)) == profileVersionId && ...
    presentText(rows.assignment_role(1)) == "attribution_settings";
end

function okay = extractionInputsMatch(conn, analysisId, expected)
rows = fetch(conn, "SELECT extraction_run_id, input_role " + ...
    "FROM analysis_run_extraction_inputs WHERE analysis_run_id=" + ...
    string(analysisId) + " ORDER BY extraction_run_id");
okay = height(rows) == height(expected);
if okay && height(expected) > 0
    okay = all(double(rows.extraction_run_id) == expected.extraction_run_id) && ...
        all(presentText(rows.input_role) == expected.input_role);
end
end

function okay = analysisSourcesMatch(conn, analysisId, expected)
rows = fetch(conn, "SELECT source_analysis_run_id, dependency_role " + ...
    "FROM analysis_run_sources WHERE analysis_run_id=" + string(analysisId) + ...
    " ORDER BY source_analysis_run_id");
okay = height(rows) == height(expected);
if okay && height(expected) > 0
    okay = all(double(rows.source_analysis_run_id) == ...
        expected.source_analysis_run_id) && ...
        all(presentText(rows.dependency_role) == expected.dependency_role);
end
end

function plan = appendConflict(plan, message)
if strlength(message) > 0
    plan.conflicts(end + 1, 1) = message;
end
end

function value = optionalIdentifier(container, field)
value = NaN;
if isfield(container, field)
    value = positiveInteger(container.(field), "runSpec." + field);
end
end

function value = optionalText(container, field)
value = "";
if isfield(container, field)
    value = scalarText(container.(field), "runSpec." + field, true);
end
end

function value = scalarText(raw, label, allowEmpty)
if nargin < 3, allowEmpty = false; end
try
    value = strtrim(string(raw));
catch
    error("vawlume:attribution:RunSpecInvalid", "%s must be scalar text.", label);
end
if ~isscalar(value) || ismissing(value) || (~allowEmpty && strlength(value) == 0)
    error("vawlume:attribution:RunSpecInvalid", ...
        "%s must be %sscalar text.", label, conditional(~allowEmpty, "nonempty ", ""));
end
end

function value = conditional(condition, whenTrue, whenFalse)
if condition, value = whenTrue; else, value = whenFalse; end
end

function value = positiveInteger(raw, label)
if ~isnumeric(raw) || ~isscalar(raw) || ~isfinite(raw) || ...
        raw < 1 || fix(raw) ~= raw
    error("vawlume:attribution:RunSpecInvalid", ...
        "%s must be a positive integer.", label);
end
value = double(raw);
end

function value = presentText(raw)
value = string(raw);
value(ismissing(value)) = "";
end

function value = sqlText(raw)
value = "'" + replace(string(raw), "'", "''") + "'";
end
