function [plan, counts] = attributionApplyPlan(conn, plan)
%ATTRIBUTIONAPPLYPLAN Atomically persist a run, provenance, and all targets.

if plan.has_conflicts
    error("vawlume:attribution:PlanConflict", ...
        "An attribution plan with identity conflicts cannot be applied.");
end
counts = emptyCounts();
if plan.run.action == "reuse"
    counts = reuseCounts(plan, counts);
    return
end
oldAutoCommit = string(conn.AutoCommit);
if oldAutoCommit ~= "on"
    error("vawlume:attribution:TransactionState", ...
        "Attribution apply requires a connection with AutoCommit enabled.");
end
conn.AutoCommit = "off";
try
    plan.analysis.analysis_run_id = attributionInsertRow(conn, ...
        "analysis_runs", struct(project_id=plan.recording.project_id, ...
        parent_analysis_run_id=plan.parent_analysis_run_id, ...
        run_type="caller_attribution", run_key=plan.context.run_key, ...
        run_label=plan.context.run_label, ...
        vawlume_version=plan.context.vawlume_version, ...
        source_commit=plan.context.source_commit, status="started", ...
        notes="Caller-attribution run; target set " + ...
            plan.target_set.event_set.kind + "."), "analysis_run_id");
    counts.analysis_runs = 1;
    plan.run.analysis_run_id = plan.analysis.analysis_run_id;
    attributionInsertRow(conn, "analysis_run_profiles", struct( ...
        analysis_run_id=plan.analysis.analysis_run_id, ...
        profile_version_id=plan.settings_profile.profile_version_id, ...
        assignment_role="attribution_settings"));
    counts.analysis_run_profiles = 1;
    for index = 1:height(plan.analysis_extraction_inputs)
        row = plan.analysis_extraction_inputs(index, :);
        attributionInsertRow(conn, "analysis_run_extraction_inputs", struct( ...
            analysis_run_id=plan.analysis.analysis_run_id, ...
            extraction_run_id=row.extraction_run_id, input_role=row.input_role));
    end
    counts.analysis_run_extraction_inputs = ...
        height(plan.analysis_extraction_inputs);
    for index = 1:height(plan.analysis_sources)
        row = plan.analysis_sources(index, :);
        attributionInsertRow(conn, "analysis_run_sources", struct( ...
            analysis_run_id=plan.analysis.analysis_run_id, ...
            source_analysis_run_id=row.source_analysis_run_id, ...
            dependency_role=row.dependency_role));
    end
    counts.analysis_run_sources = height(plan.analysis_sources);
    plan.run.attribution_run_id = attributionInsertRow(conn, ...
        "attribution_runs", struct( ...
        analysis_run_id=plan.analysis.analysis_run_id, ...
        recording_id=plan.recording.recording_id, ...
        parent_attribution_run_id=plan.parent_attribution_run_id, ...
        run_key=plan.context.run_key, ...
        attribution_path=plan.context.attribution_path, ...
        method=plan.context.method, ...
        settings_profile_version_id= ...
            plan.settings_profile.profile_version_id, ...
        status="planned", notes=plan.provenance_json), "attribution_run_id");
    counts.attribution_runs = 1;
    for index = 1:height(plan.target_set.targets)
        row = plan.target_set.targets(index, :);
        targetId = attributionInsertRow(conn, "attribution_targets", struct( ...
            attribution_run_id=plan.run.attribution_run_id, ...
            detection_id=row.detection_id, ...
            consensus_event_id=row.consensus_event_id, ...
            agreement_group_id=row.agreement_group_id, ...
            agreement_extent_method=row.agreement_extent_method, ...
            notes=row.notes), "attribution_target_id");
        plan.target_set.targets.attribution_target_id(index) = targetId;
        plan.target_set.targets.attribution_run_id(index) = ...
            plan.run.attribution_run_id;
        plan.target_set.targets.action(index) = "create";
    end
    counts.attribution_targets = height(plan.target_set.targets);
    commit(conn);
catch exception
    try
        rollback(conn);
    catch
    end
    conn.AutoCommit = oldAutoCommit;
    rethrow(exception);
end
conn.AutoCommit = oldAutoCommit;
end

function counts = reuseCounts(plan, counts)
counts.reused_analysis_runs = 1;
counts.reused_analysis_run_profiles = 1;
counts.reused_analysis_run_extraction_inputs = ...
    height(plan.analysis_extraction_inputs);
counts.reused_analysis_run_sources = height(plan.analysis_sources);
counts.reused_attribution_runs = 1;
counts.reused_attribution_targets = height(plan.target_set.targets);
end

function counts = emptyCounts()
counts = struct(analysis_runs=0, analysis_run_profiles=0, ...
    analysis_run_extraction_inputs=0, analysis_run_sources=0, ...
    attribution_runs=0, attribution_targets=0, ...
    reused_analysis_runs=0, reused_analysis_run_profiles=0, ...
    reused_analysis_run_extraction_inputs=0, ...
    reused_analysis_run_sources=0, reused_attribution_runs=0, ...
    reused_attribution_targets=0);
end
