function result = attributionPlanResult(plan)
%ATTRIBUTIONPLANRESULT Project internal run planning state to the public result.

if plan.has_conflicts
    status = "conflict";
else
    status = "planned";
end
result = struct(status=status, committed=false, ...
    has_conflicts=plan.has_conflicts, conflicts=plan.conflicts, ...
    recording=plan.recording, analysis=plan.analysis, run=plan.run, ...
    settings_profile=plan.settings_profile, input_sources=plan.input_sources, ...
    event_set=plan.target_set.event_set, ...
    target_count=height(plan.target_set.targets), ...
    targets=plan.target_set.targets, ...
    participating_entity_ids=plan.participating_entity_ids, ...
    participating_entities=plan.participating_entities, ...
    participating_links=plan.participating_links, ...
    provenance_snapshot=plan.provenance);
% A native run states which upstream inputs it consumed (contract 06 D16). Added
% for that path only, so imported and backend results keep their exact shape.
if plan.context.attribution_path == "native_estimate"
    result.declared_inputs = plan.declared_inputs;
end
end
