function run = attributionResolveRun(conn, runRef)
%ATTRIBUTIONRESOLVERUN Resolve an existing attribution run reference.

hasId = isfield(runRef, "attribution_run_id");
hasPortable = isfield(runRef, "project_key") && isfield(runRef, "run_key");
if hasId == hasPortable
    error("vawlume:attribution:RunRefInvalid", ...
        "runRef must contain attribution_run_id, or project_key plus run_key.");
end
if hasId
    id = positiveInteger(runRef.attribution_run_id, ...
        "runRef.attribution_run_id");
    predicate = "atr.attribution_run_id=" + string(id);
else
    projectKey = scalarText(runRef.project_key, "runRef.project_key");
    runKey = scalarText(runRef.run_key, "runRef.run_key");
    predicate = "p.project_key=" + sqlText(projectKey) + ...
        " AND atr.run_key=" + sqlText(runKey);
end
rows = fetch(conn, "SELECT atr.attribution_run_id, atr.analysis_run_id, " + ...
    "atr.recording_id, atr.run_key, atr.attribution_path, atr.method, " + ...
    "IFNULL(atr.settings_profile_version_id,-1) AS settings_profile_version_id, " + ...
    "atr.status, IFNULL(atr.notes,'') AS provenance_json, " + ...
    "ar.status AS analysis_status, ar.project_id, p.project_key, " + ...
    "IFNULL(r.native_recording_id,'') AS native_recording_id, " + ...
    "IFNULL(sf.relative_path,'') AS source_relative_path " + ...
    "FROM attribution_runs atr JOIN analysis_runs ar " + ...
    "ON ar.analysis_run_id=atr.analysis_run_id " + ...
    "JOIN projects p ON p.project_id=ar.project_id " + ...
    "JOIN recordings r ON r.recording_id=atr.recording_id " + ...
    "JOIN source_files sf ON sf.source_file_id=r.source_file_id " + ...
    "WHERE " + predicate);
if isempty(rows) || height(rows) == 0
    error("vawlume:attribution:RunNotFound", ...
        "No attribution run matches runRef.");
end
if height(rows) ~= 1
    error("vawlume:attribution:RunAmbiguous", ...
        "runRef matched %d attribution runs.", height(rows));
end
provenanceJson = presentText(rows.provenance_json(1));
try
    provenance = jsondecode(provenanceJson);
catch
    error("vawlume:attribution:RunProvenanceInvalid", ...
        "Attribution run provenance is not valid JSON.");
end
if ~isfield(provenance, "schema") || ...
        string(provenance.schema) ~= "vawlume.attribution.run_provenance.v1"
    error("vawlume:attribution:RunProvenanceInvalid", ...
        "Attribution run provenance does not use the supported v1 envelope.");
end
run = struct(attribution_run_id=double(rows.attribution_run_id(1)), ...
    analysis_run_id=double(rows.analysis_run_id(1)), ...
    recording_id=double(rows.recording_id(1)), ...
    project_id=double(rows.project_id(1)), ...
    project_key=presentText(rows.project_key(1)), ...
    native_recording_id=presentText(rows.native_recording_id(1)), ...
    source_relative_path=presentText(rows.source_relative_path(1)), ...
    run_key=presentText(rows.run_key(1)), ...
    attribution_path=presentText(rows.attribution_path(1)), ...
    method=presentText(rows.method(1)), ...
    settings_profile_version_id=double(rows.settings_profile_version_id(1)), ...
    status=presentText(rows.status(1)), ...
    analysis_status=presentText(rows.analysis_status(1)), ...
    participating_entity_ids=double(provenance.participating_entity_ids(:)), ...
    provenance_json=provenanceJson, provenance=provenance);
end

function value = positiveInteger(raw, label)
if ~isnumeric(raw) || ~isscalar(raw) || ~isfinite(raw) || ...
        raw < 1 || fix(raw) ~= raw
    error("vawlume:attribution:RunRefInvalid", ...
        "%s must be a positive integer.", label);
end
value = double(raw);
end

function value = scalarText(raw, label)
try
    value = strtrim(string(raw));
catch
    error("vawlume:attribution:RunRefInvalid", "%s must be scalar text.", label);
end
if ~isscalar(value) || ismissing(value) || strlength(value) == 0
    error("vawlume:attribution:RunRefInvalid", ...
        "%s must be nonempty scalar text.", label);
end
end

function value = presentText(raw)
value = string(raw);
value(ismissing(value)) = "";
end

function value = sqlText(raw)
value = "'" + replace(string(raw), "'", "''") + "'";
end
