function [plan, count] = attributionApplyEvidencePlan(conn, plan)
%ATTRIBUTIONAPPLYEVIDENCEPLAN Atomically append long-form evidence rows.

if plan.has_conflicts
    error("vawlume:attribution:PlanConflict", ...
        "An evidence plan with conflicts cannot be applied.");
end
count = height(plan.evidence);
oldAutoCommit = string(conn.AutoCommit);
if oldAutoCommit ~= "on"
    error("vawlume:attribution:TransactionState", ...
        "Evidence apply requires a connection with AutoCommit enabled.");
end
conn.AutoCommit = "off";
try
    for index = 1:height(plan.evidence)
        row = plan.evidence(index, :);
        evidenceId = attributionInsertRow(conn, "attribution_evidence", ...
            struct(attribution_target_id=row.attribution_target_id, ...
            attribution_candidate_id=row.attribution_candidate_id, ...
            evidence_dimension=row.evidence_dimension, ...
            evidence_kind=row.evidence_kind, value_real=row.value_real, ...
            value_text=row.value_text, value_units=row.value_units, ...
            value_semantics=row.value_semantics, ...
            identity_statement_kind=row.identity_statement_kind, ...
            tracking_identity_association_id= ...
                row.tracking_identity_association_id, ...
            external_event_id=row.external_event_id, ...
            alignment_run_id=row.alignment_run_id, ...
            source_file_id=row.source_file_id, ...
            mapping_profile_version_id=row.mapping_profile_version_id, ...
            source_locator=row.source_locator, notes=row.notes), ...
            "attribution_evidence_id");
        plan.evidence.attribution_evidence_id(index) = evidenceId;
    end
    commit(conn);
catch exception
    try
        rollback(conn);
    catch
    end
    conn.AutoCommit = oldAutoCommit;
    rethrow(exception);
end
conn.AutoCommit = oldAutoCommit;
end
