function candidates = attributionReadCandidates(conn, attributionTargetId)
%ATTRIBUTIONREADCANDIDATES Read every candidate for one target without judging it.

rows = fetch(conn, "SELECT attribution_candidate_id, attribution_target_id, " + ...
    "entity_id, candidate_status, " + ...
    "CASE WHEN candidate_rank IS NULL THEN 1 ELSE 0 END AS rank_missing, " + ...
    "IFNULL(candidate_rank,-1) AS candidate_rank, " + ...
    "CASE WHEN score IS NULL THEN 1 ELSE 0 END AS score_missing, " + ...
    "IFNULL(score,0.0) AS score, IFNULL(score_semantics,'') AS score_semantics, " + ...
    "CASE WHEN probability IS NULL THEN 1 ELSE 0 END AS probability_missing, " + ...
    "IFNULL(probability,0.0) AS probability, " + ...
    "IFNULL(probability_semantics,'') AS probability_semantics, " + ...
    "IFNULL(source_label,'') AS source_label, IFNULL(notes,'') AS notes " + ...
    "FROM attribution_candidates WHERE attribution_target_id=" + ...
    string(attributionTargetId) + " ORDER BY " + ...
    "CASE WHEN candidate_rank IS NULL THEN 1 ELSE 0 END, candidate_rank, entity_id");
count = height(rows);
candidates = table(NaN(count, 1), NaN(count, 1), (1:count)', ...
    NaN(count, 1), strings(count, 1), NaN(count, 1), NaN(count, 1), ...
    strings(count, 1), NaN(count, 1), strings(count, 1), ...
    strings(count, 1), strings(count, 1), repmat("reuse", count, 1), ...
    VariableNames=["attribution_candidate_id", "attribution_target_id", ...
    "candidate_ordinal", "entity_id", "candidate_status", ...
    "candidate_rank", "score", "score_semantics", "probability", ...
    "probability_semantics", "source_label", "notes", "action"]);
if count == 0
    return
end
candidates.attribution_candidate_id = double(rows.attribution_candidate_id);
candidates.attribution_target_id = double(rows.attribution_target_id);
candidates.entity_id = double(rows.entity_id);
candidates.candidate_status = presentText(rows.candidate_status);
candidates.candidate_rank = nullableNumber(rows.candidate_rank, rows.rank_missing);
candidates.score = nullableNumber(rows.score, rows.score_missing);
candidates.score_semantics = presentText(rows.score_semantics);
candidates.probability = nullableNumber(rows.probability, rows.probability_missing);
candidates.probability_semantics = presentText(rows.probability_semantics);
candidates.source_label = presentText(rows.source_label);
candidates.notes = presentText(rows.notes);
end

function value = nullableNumber(raw, missing)
value = double(raw);
value(logical(double(missing))) = NaN;
end

function value = presentText(raw)
value = string(raw);
value(ismissing(value)) = "";
end
