function targets = attributionReadTargets(conn, attributionRunId)
%ATTRIBUTIONREADTARGETS Read targets in their stored insertion order.

rows = fetch(conn, "SELECT attribution_target_id, attribution_run_id, " + ...
    "IFNULL(detection_id,-1) AS detection_id, " + ...
    "IFNULL(consensus_event_id,-1) AS consensus_event_id, " + ...
    "IFNULL(agreement_group_id,-1) AS agreement_group_id, " + ...
    "IFNULL(agreement_extent_method,'') AS agreement_extent_method, " + ...
    "IFNULL(notes,'') AS notes FROM attribution_targets " + ...
    "WHERE attribution_run_id=" + string(attributionRunId) + ...
    " ORDER BY attribution_target_id");
count = height(rows);
targets = table(NaN(count, 1), NaN(count, 1), (1:count)', NaN(count, 1), ...
    NaN(count, 1), NaN(count, 1), strings(count, 1), strings(count, 1), ...
    repmat("reuse", count, 1), ...
    VariableNames=["attribution_target_id", "attribution_run_id", ...
    "target_ordinal", ...
    "detection_id", "consensus_event_id", "agreement_group_id", ...
    "agreement_extent_method", "notes", "action"]);
if count == 0
    return
end
targets.attribution_target_id = double(rows.attribution_target_id);
targets.attribution_run_id = double(rows.attribution_run_id);
targets.detection_id = absentIdToNaN(rows.detection_id);
targets.consensus_event_id = absentIdToNaN(rows.consensus_event_id);
targets.agreement_group_id = absentIdToNaN(rows.agreement_group_id);
targets.agreement_extent_method = presentText(rows.agreement_extent_method);
targets.notes = presentText(rows.notes);
end

function value = absentIdToNaN(raw)
value = double(raw);
value(value < 0) = NaN;
end

function value = presentText(raw)
value = string(raw);
value(ismissing(value)) = "";
end
