function result = measureReferenceResponse(conn, referenceRef, channelIndex, options)
%MEASUREREFERENCERESPONSE Measure one reference on one explicit channel.
%
%   result = VAWLUME.ACOUSTIC.MEASUREREFERENCERESPONSE(conn, ...
%       struct(acoustic_reference_id=ID), channelIndex, SourceRoot=root)
%   result = VAWLUME.ACOUSTIC.MEASUREREFERENCERESPONSE(..., ...
%       Apply=true, RunKey="stable-run-key")
%
% RMS and peak absolute amplitude are computed from the bounded native sample
% window. Band power is added only when the reference declares both bounds as
% a positive-width band at or below Nyquist. Units are normalized full-scale
% ratios from AUDIOREAD, not volts or dB. No normalization is applied to calls
% and no caller or preferred-channel claim is made.
%
% Apply=false (default) is read-only. Apply=true creates or exactly reuses one
% analysis run and provenance-bearing derived_measurements rows.

arguments
    conn
    referenceRef (1,1) struct
    channelIndex (1,1) double
    options.SourceRoot (1,1) string = ""
    options.Apply (1,1) logical = false
    options.RunKey (1,1) string = ""
    options.RunLabel (1,1) string = ""
    options.VawlumeVersion (1,1) string = ""
    options.SourceCommit (1,1) string = ""
    options.Notes (1,1) string = ""
end

reference = resolveReference(conn, referenceRef);
if ~isnan(reference.reference_channel_index) && ...
        reference.reference_channel_index ~= channelIndex
    error("vawlume:acoustic:ReferenceChannelMismatch", ...
        "Reference %d is scoped to channel %d, not requested channel %d.", ...
        reference.acoustic_reference_id, reference.reference_channel_index, channelIndex);
end

window = vawlume.acoustic.readAudioWindow(conn, ...
    struct(recording_id=reference.recording_id), channelIndex, ...
    reference.start_time_s, reference.end_time_s, ...
    SourceRoot=options.SourceRoot);
[metrics, metricQc] = calculateMetrics(window.samples, window.sample_rate_hz, ...
    reference.frequency_min_hz, reference.frequency_max_hz);
qcFlags = unique([window.qc_flags; metricQc], "stable");

if window.sample_count == 0
    status = "failed";
elseif isempty(qcFlags)
    status = "completed";
else
    status = "completed_with_warnings";
end
details = derivationDetails(reference, window, qcFlags);

analysisRunId = NaN;
measurementIds = zeros(0, 1);
action = "planned";
if options.Apply
    if ismissing(options.RunKey) || strlength(options.RunKey) == 0
        error("vawlume:acoustic:RunKeyRequired", ...
            "RunKey is required when Apply=true.");
    end
    [analysisRunId, measurementIds, action] = persistMeasurements( ...
        conn, reference, window, metrics, details, status, options);
end

result = struct( ...
    acoustic_reference_id=reference.acoustic_reference_id, ...
    reference_key=reference.reference_key, ...
    recording_id=reference.recording_id, ...
    recording_channel_id=window.recording_channel_id, ...
    channel_index=window.channel_index, ...
    status=status, ...
    qc_flags=qcFlags, ...
    metrics=metrics, ...
    audio_window=window, ...
    method_key="vawlume.acoustic.reference_response", ...
    method_version="1.0.0", ...
    analysis_run_id=analysisRunId, ...
    derived_measurement_ids=measurementIds, ...
    action=action);
end

function reference = resolveReference(conn, ref)
if ~isfield(ref, "acoustic_reference_id") || numel(fieldnames(ref)) ~= 1
    error("vawlume:acoustic:ReferenceRefInvalid", ...
        "referenceRef must contain only acoustic_reference_id.");
end
id = double(ref.acoustic_reference_id);
if ~isscalar(id) || ~isfinite(id) || id < 1 || id ~= floor(id)
    error("vawlume:acoustic:ReferenceRefInvalid", ...
        "referenceRef.acoustic_reference_id must be a positive integer.");
end
rows = fetch(conn, "SELECT ar.acoustic_reference_id, ar.recording_id, " + ...
    "r.project_id, ar.reference_key, ar.reference_type, ar.start_time_s, ar.end_time_s, " + ...
    "IFNULL(ar.frequency_min_hz,-1) AS frequency_min_hz, " + ...
    "IFNULL(ar.frequency_max_hz,-1) AS frequency_max_hz, " + ...
    "IFNULL(ar.recording_channel_id,-1) AS reference_channel_id, " + ...
    "IFNULL(rc.channel_index,-1) AS reference_channel_index " + ...
    "FROM acoustic_references ar JOIN recordings r ON r.recording_id=ar.recording_id " + ...
    "LEFT JOIN recording_channels rc ON rc.recording_channel_id=ar.recording_channel_id " + ...
    "WHERE ar.acoustic_reference_id=" + string(id));
if isempty(rows) || height(rows) == 0
    error("vawlume:acoustic:ReferenceNotFound", ...
        "No acoustic reference %d exists.", id);
end
reference = struct( ...
    acoustic_reference_id=double(rows.acoustic_reference_id(1)), ...
    recording_id=double(rows.recording_id(1)), ...
    project_id=double(rows.project_id(1)), ...
    reference_key=acousticPresentText(rows.reference_key(1)), ...
    reference_type=acousticPresentText(rows.reference_type(1)), ...
    start_time_s=double(rows.start_time_s(1)), ...
    end_time_s=double(rows.end_time_s(1)), ...
    frequency_min_hz=nullable(rows.frequency_min_hz(1)), ...
    frequency_max_hz=nullable(rows.frequency_max_hz(1)), ...
    reference_channel_id=nullable(rows.reference_channel_id(1)), ...
    reference_channel_index=nullable(rows.reference_channel_index(1)));
end

function [metrics, qcFlags] = calculateMetrics(samples, sampleRate, bandMin, bandMax)
metrics = table(Size=[0 3], VariableTypes=["string", "double", "string"], ...
    VariableNames=["metric_key", "value", "unit"]);
qcFlags = strings(0, 1);
if isempty(samples)
    return
end
metrics = [metrics; {"acoustic_rms_amplitude", ...
    sqrt(mean(samples .^ 2)), "full_scale_ratio"}];
metrics = [metrics; {"acoustic_peak_abs_amplitude", ...
    max(abs(samples)), "full_scale_ratio"}];

hasMin = ~isnan(bandMin);
hasMax = ~isnan(bandMax);
if ~hasMin && ~hasMax
    return
end
if hasMin ~= hasMax
    qcFlags(end + 1, 1) = "incomplete_reference_band";
    return
end
if bandMax <= bandMin
    qcFlags(end + 1, 1) = "invalid_reference_band";
    return
end
if bandMax > sampleRate / 2
    qcFlags(end + 1, 1) = "reference_band_above_nyquist";
    return
end

n = numel(samples);
spectrum = fft(samples);
frequency = (0:n-1)' * (sampleRate / n);
foldedFrequency = min(frequency, sampleRate - frequency);
selected = foldedFrequency >= bandMin & foldedFrequency <= bandMax;
bandPower = sum(abs(spectrum(selected)) .^ 2) / (n ^ 2);
metrics = [metrics; {"acoustic_band_power", bandPower, ...
    "full_scale_ratio_squared"}];
end

function details = derivationDetails(reference, window, qcFlags)
details = struct( ...
    method_key="vawlume.acoustic.reference_response", ...
    method_version="1.0.0", ...
    sample_semantics="MATLAB audioread normalized full-scale ratio", ...
    interval_semantics="half-open [start,end) in native audio seconds", ...
    band_power_method="two-sided rectangular-bin DFT power folded by absolute frequency; no detrending or window", ...
    acoustic_reference_id=reference.acoustic_reference_id, ...
    reference_key=reference.reference_key, ...
    recording_id=window.recording_id, ...
    recording_channel_id=window.recording_channel_id, ...
    channel_index=window.channel_index, ...
    source_file_id=window.source_file_id, ...
    source_path_or_uri=window.source_path_or_uri, ...
    source_relative_path=window.source_relative_path, ...
    resolved_source_path=window.resolved_source_path, ...
    source_checksum_sha256=window.source_checksum_sha256, ...
    requested_interval_s=window.requested_interval_s, ...
    covered_interval_s=window.covered_interval_s, ...
    read_interval_s=window.read_interval_s, ...
    first_sample=window.first_sample, ...
    last_sample=window.last_sample, ...
    sample_count=window.sample_count, ...
    sample_rate_hz=window.sample_rate_hz, ...
    frequency_band_hz=[reference.frequency_min_hz reference.frequency_max_hz], ...
    qc_flags=qcFlags(:)');
end

function [runId, measurementIds, action] = persistMeasurements(conn, reference, ...
        window, metrics, details, status, options)
metricRows = resolveMetricDefinitions(conn, metrics.metric_key);
detailsJson = string(jsonencode(details));
oldAutoCommit = conn.AutoCommit;
conn.AutoCommit = "off";
try
    existing = fetch(conn, "SELECT analysis_run_id, run_type, status, " + ...
        "IFNULL(run_label,'') AS run_label, IFNULL(vawlume_version,'') AS vawlume_version, " + ...
        "IFNULL(source_commit,'') AS source_commit, IFNULL(notes,'') AS notes " + ...
        "FROM analysis_runs WHERE project_id=" + string(reference.project_id) + ...
        " AND run_key=" + acousticSqlText(options.RunKey));
    if isempty(existing) || height(existing) == 0
        values = struct(project_id=reference.project_id, ...
            run_type="acoustic_reference_response", run_key=options.RunKey, ...
            run_label=options.RunLabel, vawlume_version=options.VawlumeVersion, ...
            source_commit=options.SourceCommit, status=status, ...
            completed_at_utc=currentTimestamp(), notes=options.Notes);
        runId = acousticInsertRow(conn, "analysis_runs", values, "analysis_run_id");
        measurementIds = insertMeasurements(conn, runId, reference, window, ...
            metrics, metricRows, detailsJson);
        action = "created";
        commit(conn);
    else
        runId = double(existing.analysis_run_id(1));
        assertRunCompatible(existing(1, :), status, options);
        measurementIds = assertMeasurementsCompatible(conn, runId, reference, ...
            window, metrics, detailsJson);
        action = "reused";
    end
catch exception
    try
        rollback(conn);
    catch
    end
    conn.AutoCommit = oldAutoCommit;
    rethrow(exception);
end
conn.AutoCommit = oldAutoCommit;
end

function rows = resolveMetricDefinitions(conn, keys)
if isempty(keys)
    rows = table(Size=[0 2], VariableTypes=["double","string"], ...
        VariableNames=["metric_definition_id","metric_key"]);
    return
end
quoted = arrayfun(@acousticSqlText, keys);
rows = fetch(conn, "SELECT metric_definition_id, metric_key FROM metric_definitions " + ...
    "WHERE metric_key IN (" + strjoin(quoted, ",") + ")");
if height(rows) ~= numel(keys)
    error("vawlume:acoustic:MetricDefinitionsMissing", ...
        "Built-in acoustic metric definitions are missing; run vawlume.db.registerBuiltinSemantics first.");
end
rows.metric_definition_id = double(rows.metric_definition_id);
rows.metric_key = string(rows.metric_key);
end

function ids = insertMeasurements(conn, runId, reference, window, metrics, definitions, detailsJson)
ids = zeros(height(metrics), 1);
for index = 1:height(metrics)
    definitionId = definitions.metric_definition_id( ...
        definitions.metric_key == metrics.metric_key(index));
    ids(index) = acousticInsertRow(conn, "derived_measurements", struct( ...
        analysis_run_id=runId, metric_definition_id=definitionId, ...
        acoustic_reference_id=reference.acoustic_reference_id, ...
        recording_channel_id=window.recording_channel_id, ...
        value_real=metrics.value(index), unit=metrics.unit(index), ...
        derivation_details_json=detailsJson), "derived_measurement_id");
end
end

function assertRunCompatible(row, status, options)
actual = [acousticPresentText(row.run_type(1)), acousticPresentText(row.status(1)), ...
    acousticPresentText(row.run_label(1)), acousticPresentText(row.vawlume_version(1)), ...
    acousticPresentText(row.source_commit(1)), acousticPresentText(row.notes(1))];
expected = ["acoustic_reference_response", status, options.RunLabel, ...
    options.VawlumeVersion, options.SourceCommit, options.Notes];
if ~isequal(actual, expected)
    error("vawlume:acoustic:MeasurementRunConflict", ...
        "RunKey '%s' already identifies an analysis run with different provenance or status.", ...
        options.RunKey);
end
end

function ids = assertMeasurementsCompatible(conn, runId, reference, window, metrics, detailsJson)
rows = fetch(conn, "SELECT dm.derived_measurement_id, md.metric_key, dm.value_real, " + ...
    "IFNULL(dm.unit,'') AS unit, IFNULL(dm.derivation_details_json,'') AS details " + ...
    "FROM derived_measurements dm JOIN metric_definitions md " + ...
    "ON md.metric_definition_id=dm.metric_definition_id " + ...
    "WHERE dm.analysis_run_id=" + string(runId) + ...
    " AND dm.acoustic_reference_id=" + string(reference.acoustic_reference_id) + ...
    " AND dm.recording_channel_id=" + string(window.recording_channel_id) + ...
    " ORDER BY md.metric_key");
if height(rows) ~= height(metrics)
    conflict();
end
if isempty(rows)
    ids = zeros(0, 1);
    return
end
rows.metric_key = string(rows.metric_key);
rows.unit = string(rows.unit);
rows.details = string(rows.details);
[expectedKeys, order] = sort(metrics.metric_key);
expectedValues = metrics.value(order);
expectedUnits = metrics.unit(order);
if ~isequal(rows.metric_key, expectedKeys) || ...
        ~isequal(double(rows.value_real), expectedValues) || ...
        ~isequal(rows.unit, expectedUnits) || any(rows.details ~= detailsJson)
    conflict();
end
ids = double(rows.derived_measurement_id);
end

function conflict()
error("vawlume:acoustic:MeasurementRunConflict", ...
    "The existing analysis run does not contain exactly the requested deterministic measurements.");
end

function value = currentTimestamp()
value = string(char(datetime("now", "TimeZone", "UTC", ...
    "Format", "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'")));
end

function value = nullable(raw)
value = double(raw);
if value < 0
    value = NaN;
end
end
