function references = readReferences(conn, recordingRef, options)
%READREFERENCES Read declared acoustic references and their provenance.
%
%   references = VAWLUME.ACOUSTIC.READREFERENCES(conn, recordingRef)
%   references = VAWLUME.ACOUSTIC.READREFERENCES(..., ChannelIndex=2)
%   references = VAWLUME.ACOUSTIC.READREFERENCES(..., StartTimeS=5, EndTimeS=10)
%
% With no filters, returns every reference for the recording. ChannelIndex=N
% returns declarations applying to channel N: both recording-wide rows and rows
% explicitly narrowed to that channel. Time bounds use interval overlap and may
% be supplied independently.
%
% Times are always in the recording's native audio clock and seconds. When the
% recording also has a declared is_recording_native timebase, its identity and
% vocabulary are returned; absence remains NaN/empty rather than being invented.
% A linked external event's own stream/timebase fields are returned separately,
% because event provenance is not timing authority for the acoustic reference.
%
% Read-only. No alignment anchor or measured response is inferred.
%
% See also VAWLUME.ACOUSTIC.REGISTERREFERENCE

arguments
    conn
    recordingRef (1,1) struct
    options.ChannelIndex (1,1) double = NaN
    options.StartTimeS (1,1) double = NaN
    options.EndTimeS (1,1) double = NaN
end

recording = acousticResolveRecording(conn, recordingRef);
channelId = NaN;
if ~isnan(options.ChannelIndex)
    channelId = resolveChannelId(conn, recording, options.ChannelIndex);
end
validateBound(options.StartTimeS, "StartTimeS");
validateBound(options.EndTimeS, "EndTimeS");
if ~isnan(options.StartTimeS) && ~isnan(options.EndTimeS) && ...
        options.EndTimeS < options.StartTimeS
    error("vawlume:acoustic:ReadWindowInvalid", ...
        "EndTimeS must be greater than or equal to StartTimeS.");
end

where = "ar.recording_id=" + string(recording.recording_id);
if ~isnan(channelId)
    where = where + " AND (ar.recording_channel_id IS NULL OR " + ...
        "ar.recording_channel_id=" + string(channelId) + ")";
end
if ~isnan(options.StartTimeS)
    where = where + " AND ar.end_time_s >= " + compose("%.17g", options.StartTimeS);
end
if ~isnan(options.EndTimeS)
    where = where + " AND ar.start_time_s <= " + compose("%.17g", options.EndTimeS);
end

rows = fetch(conn, "SELECT ar.acoustic_reference_id, ar.recording_id, " + ...
    "ar.reference_key, ar.reference_type, IFNULL(ar.native_label,'') AS native_label, " + ...
    "ar.start_time_s, ar.end_time_s, " + ...
    "IFNULL(ar.frequency_min_hz,-1) AS frequency_min_hz, " + ...
    "IFNULL(ar.frequency_max_hz,-1) AS frequency_max_hz, " + ...
    "IFNULL(ar.recording_channel_id,-1) AS recording_channel_id, " + ...
    "IFNULL(rc.channel_index,-1) AS channel_index, " + ...
    "IFNULL(rc.channel_label,'') AS channel_label, " + ...
    "CASE WHEN ar.recording_channel_id IS NULL THEN 1 ELSE 0 END AS applies_to_all_channels, " + ...
    "IFNULL(nt.timebase_id,-1) AS native_timebase_id, " + ...
    "IFNULL(nt.timebase_name,'') AS native_timebase_name, " + ...
    "IFNULL(nt.timebase_kind,'') AS native_timebase_kind, " + ...
    "IFNULL(nt.native_unit,'') AS native_time_unit, " + ...
    "IFNULL(ar.external_event_id,-1) AS external_event_id, " + ...
    "IFNULL(ee.event_type,'') AS external_event_type, " + ...
    "IFNULL(ee.native_event_label,'') AS external_native_label, " + ...
    "IFNULL(es.external_stream_id,-1) AS external_stream_id, " + ...
    "IFNULL(es.stream_name,'') AS external_stream_name, " + ...
    "IFNULL(et.timebase_id,-1) AS external_timebase_id, " + ...
    "IFNULL(et.timebase_name,'') AS external_timebase_name, " + ...
    "IFNULL(et.native_unit,'') AS external_native_unit, " + ...
    "IFNULL(ar.source_file_id,-1) AS source_file_id, " + ...
    "IFNULL(sf.path_or_uri,'') AS source_path_or_uri, " + ...
    "IFNULL(ar.mapping_profile_version_id,-1) AS mapping_profile_version_id, " + ...
    "IFNULL(cp.profile_key,'') AS mapping_profile_key, " + ...
    "IFNULL(cpv.version_label,'') AS mapping_profile_version, " + ...
    "IFNULL(ar.source_locator,'') AS source_locator, IFNULL(ar.notes,'') AS notes " + ...
    "FROM acoustic_references ar " + ...
    "LEFT JOIN recording_channels rc ON rc.recording_channel_id=ar.recording_channel_id " + ...
    "LEFT JOIN timebases nt ON nt.recording_id=ar.recording_id AND nt.is_recording_native=1 " + ...
    "LEFT JOIN external_events ee ON ee.external_event_id=ar.external_event_id " + ...
    "LEFT JOIN external_streams es ON es.external_stream_id=ee.external_stream_id " + ...
    "LEFT JOIN timebases et ON et.timebase_id=es.timebase_id " + ...
    "LEFT JOIN source_files sf ON sf.source_file_id=ar.source_file_id " + ...
    "LEFT JOIN config_profile_versions cpv " + ...
    "ON cpv.profile_version_id=ar.mapping_profile_version_id " + ...
    "LEFT JOIN config_profiles cp ON cp.profile_id=cpv.profile_id " + ...
    "WHERE " + where + " ORDER BY ar.start_time_s, ar.end_time_s, ar.reference_key");

if isempty(rows) || height(rows) == 0
    references = emptyReferences();
    return
end

numericNames = ["acoustic_reference_id", "recording_id", "start_time_s", ...
    "end_time_s", "frequency_min_hz", "frequency_max_hz", ...
    "recording_channel_id", "channel_index", "native_timebase_id", ...
    "external_event_id", "external_stream_id", "external_timebase_id", ...
    "source_file_id", "mapping_profile_version_id"];
textNames = ["reference_key", "reference_type", "native_label", ...
    "channel_label", "native_timebase_name", "native_timebase_kind", ...
    "native_time_unit", "external_event_type", "external_native_label", ...
    "external_stream_name", "external_timebase_name", "external_native_unit", ...
    "source_path_or_uri", "mapping_profile_key", "mapping_profile_version", ...
    "source_locator", "notes"];
for name = numericNames
    rows.(name) = double(rows.(name));
end
for name = ["frequency_min_hz", "frequency_max_hz", "recording_channel_id", ...
        "channel_index", "native_timebase_id", "external_event_id", ...
        "external_stream_id", "external_timebase_id", "source_file_id", ...
        "mapping_profile_version_id"]
    rows.(name)(rows.(name) < 0) = NaN;
end
rows.applies_to_all_channels = logical(rows.applies_to_all_channels);
for name = textNames
    rows.(name) = acousticPresentText(rows.(name));
end
references = rows;
end

function channelId = resolveChannelId(conn, recording, channelIndex)
if ~isfinite(channelIndex) || channelIndex <= 0 || channelIndex ~= floor(channelIndex)
    error("vawlume:acoustic:ReadFilterInvalid", ...
        "ChannelIndex must be a positive integer when supplied.");
end
rows = fetch(conn, "SELECT recording_channel_id FROM recording_channels " + ...
    "WHERE recording_id=" + string(recording.recording_id) + ...
    " AND channel_index=" + string(channelIndex));
if isempty(rows) || height(rows) == 0
    error("vawlume:acoustic:ChannelNotFound", ...
        "Recording %d has no channel_index %d.", ...
        recording.recording_id, channelIndex);
end
channelId = double(rows.recording_channel_id(1));
end

function validateBound(value, name)
if isnan(value)
    return
end
if ~isfinite(value) || value < 0
    error("vawlume:acoustic:ReadFilterInvalid", ...
        "%s must be a finite nonnegative scalar when supplied.", name);
end
end

function value = emptyReferences()
names = ["acoustic_reference_id", "recording_id", "reference_key", ...
    "reference_type", "native_label", "start_time_s", "end_time_s", ...
    "frequency_min_hz", "frequency_max_hz", "recording_channel_id", ...
    "channel_index", "channel_label", "applies_to_all_channels", ...
    "native_timebase_id", "native_timebase_name", "native_timebase_kind", ...
    "native_time_unit", "external_event_id", "external_event_type", ...
    "external_native_label", "external_stream_id", "external_stream_name", ...
    "external_timebase_id", "external_timebase_name", "external_native_unit", ...
    "source_file_id", "source_path_or_uri", "mapping_profile_version_id", ...
    "mapping_profile_key", "mapping_profile_version", "source_locator", "notes"];
types = repmat("double", 1, numel(names));
types(ismember(names, ["reference_key", "reference_type", "native_label", ...
    "channel_label", "native_timebase_name", "native_timebase_kind", ...
    "native_time_unit", "external_event_type", "external_native_label", ...
    "external_stream_name", "external_timebase_name", "external_native_unit", ...
    "source_path_or_uri", "mapping_profile_key", "mapping_profile_version", ...
    "source_locator", "notes"])) = "string";
types(names == "applies_to_all_channels") = "logical";
value = table(Size=[0, numel(names)], VariableTypes=cellstr(types), ...
    VariableNames=cellstr(names));
end
