function profile = readChannelResponse(conn, profileRef)
%READCHANNELRESPONSE Read a response/QC profile and exact source evidence.
%
%   profile = VAWLUME.ACOUSTIC.READCHANNELRESPONSE(conn, ...
%       struct(analysis_run_id=ID))
%   profile = VAWLUME.ACOUSTIC.READCHANNELRESPONSE(conn, ...
%       struct(project_key="project", run_key="response-profile"))
%
% The returned sources table contains every derived measurement cited by the
% restrictive lineage junction, together with reference and source-run context.
% This is a read-only evidence query, not a normalization operation.

arguments
    conn
    profileRef (1,1) struct
end

analysis = resolveProfile(conn, profileRef);
estimates = fetch(conn, "SELECT cre.channel_response_estimate_id, " + ...
    "cre.analysis_run_id, cre.recording_id, cre.recording_channel_id, " + ...
    "rc.channel_index, IFNULL(rc.channel_label,'') AS channel_label, " + ...
    "cre.metric_definition_id, md.metric_key, cre.estimate_key, " + ...
    "cre.reference_type, cre.aggregation_method, cre.aggregation_version, " + ...
    "IFNULL(cre.frequency_min_hz,-1) AS frequency_min_hz, " + ...
    "IFNULL(cre.frequency_max_hz,-1) AS frequency_max_hz, cre.qc_status, " + ...
    "IFNULL(cre.value_real,-1.7976931348623157e308) AS value_real, " + ...
    "IFNULL(cre.unit,'') AS unit, cre.details_json, IFNULL(cre.notes,'') AS notes " + ...
    "FROM channel_response_estimates cre " + ...
    "JOIN recording_channels rc ON rc.recording_channel_id=cre.recording_channel_id " + ...
    "JOIN metric_definitions md ON md.metric_definition_id=cre.metric_definition_id " + ...
    "WHERE cre.analysis_run_id=" + string(analysis.analysis_run_id) + ...
    " ORDER BY cre.estimate_key");
estimates = normalizeEstimates(estimates);

sources = fetch(conn, "SELECT cres.channel_response_estimate_id, " + ...
    "cres.derived_measurement_id, dm.analysis_run_id AS source_analysis_run_id, " + ...
    "sar.run_key AS source_run_key, sar.status AS source_run_status, " + ...
    "dm.metric_definition_id, md.metric_key, dm.value_real, dm.unit, " + ...
    "dm.derivation_details_json, dm.acoustic_reference_id, ar.reference_key, " + ...
    "ar.reference_type, ar.start_time_s, ar.end_time_s, " + ...
    "IFNULL(ar.frequency_min_hz,-1) AS frequency_min_hz, " + ...
    "IFNULL(ar.frequency_max_hz,-1) AS frequency_max_hz, " + ...
    "dm.recording_channel_id, rc.channel_index, " + ...
    "IFNULL(rc.channel_label,'') AS channel_label " + ...
    "FROM channel_response_estimate_sources cres " + ...
    "JOIN derived_measurements dm ON dm.derived_measurement_id=cres.derived_measurement_id " + ...
    "JOIN analysis_runs sar ON sar.analysis_run_id=dm.analysis_run_id " + ...
    "JOIN metric_definitions md ON md.metric_definition_id=dm.metric_definition_id " + ...
    "JOIN acoustic_references ar ON ar.acoustic_reference_id=dm.acoustic_reference_id " + ...
    "JOIN recording_channels rc ON rc.recording_channel_id=dm.recording_channel_id " + ...
    "JOIN channel_response_estimates cre " + ...
    "ON cre.channel_response_estimate_id=cres.channel_response_estimate_id " + ...
    "WHERE cre.analysis_run_id=" + string(analysis.analysis_run_id) + ...
    " ORDER BY cres.channel_response_estimate_id, cres.derived_measurement_id");
sources = normalizeSources(sources);

settingsProfiles = fetch(conn, "SELECT arp.profile_version_id, " + ...
    "arp.assignment_role, cp.profile_key, cp.profile_kind, cpv.version_label, " + ...
    "cpv.content_uri, IFNULL(cpv.checksum_sha256,'') AS checksum_sha256 " + ...
    "FROM analysis_run_profiles arp JOIN config_profile_versions cpv " + ...
    "ON cpv.profile_version_id=arp.profile_version_id JOIN config_profiles cp " + ...
    "ON cp.profile_id=cpv.profile_id WHERE arp.analysis_run_id=" + ...
    string(analysis.analysis_run_id) + " ORDER BY arp.assignment_role, cp.profile_key");
if ~isempty(settingsProfiles)
    settingsProfiles.profile_version_id = double(settingsProfiles.profile_version_id);
end
settingsProfiles = normalizeTextTable(settingsProfiles);

sourceAnalyses = fetch(conn, "SELECT ars.source_analysis_run_id, " + ...
    "ars.dependency_role, sar.run_key, sar.run_type, sar.status, " + ...
    "IFNULL(ars.notes,'') AS notes FROM analysis_run_sources ars " + ...
    "JOIN analysis_runs sar ON sar.analysis_run_id=ars.source_analysis_run_id " + ...
    "WHERE ars.analysis_run_id=" + string(analysis.analysis_run_id) + ...
    " ORDER BY ars.source_analysis_run_id");
if ~isempty(sourceAnalyses)
    sourceAnalyses.source_analysis_run_id = double(sourceAnalyses.source_analysis_run_id);
end
sourceAnalyses = normalizeTextTable(sourceAnalyses);

profile = struct(analysis=analysis, estimates=estimates, ...
    source_measurements=sources, source_analyses=sourceAnalyses, ...
    settings_profiles=settingsProfiles);
end

function analysis = resolveProfile(conn, ref)
hasId = isfield(ref, "analysis_run_id");
hasPortable = isfield(ref, "project_key") && isfield(ref, "run_key");
if hasId == hasPortable || (hasId && numel(fieldnames(ref)) ~= 1) || ...
        (hasPortable && numel(fieldnames(ref)) ~= 2)
    error("vawlume:acoustic:ResponseProfileRefInvalid", ...
        "profileRef must contain only analysis_run_id, or project_key plus run_key.");
end
base = "SELECT ar.analysis_run_id, ar.project_id, p.project_key, ar.run_key, " + ...
    "ar.run_type, IFNULL(ar.run_label,'') AS run_label, " + ...
    "IFNULL(ar.vawlume_version,'') AS vawlume_version, " + ...
    "IFNULL(ar.source_commit,'') AS source_commit, ar.status, " + ...
    "ar.started_at_utc, IFNULL(ar.completed_at_utc,'') AS completed_at_utc, " + ...
    "IFNULL(ar.notes,'') AS notes FROM analysis_runs ar " + ...
    "JOIN projects p ON p.project_id=ar.project_id WHERE ";
if hasId
    id = double(ref.analysis_run_id);
    if ~isscalar(id) || ~isfinite(id) || id < 1 || id ~= floor(id)
        error("vawlume:acoustic:ResponseProfileRefInvalid", ...
            "profileRef.analysis_run_id must be a positive integer.");
    end
    rows = fetch(conn, base + "ar.analysis_run_id=" + string(id));
else
    projectKey = requiredText(ref.project_key, "project_key");
    runKey = requiredText(ref.run_key, "run_key");
    rows = fetch(conn, base + "p.project_key=" + acousticSqlText(projectKey) + ...
        " AND ar.run_key=" + acousticSqlText(runKey));
end
if isempty(rows) || height(rows) == 0
    error("vawlume:acoustic:ResponseProfileNotFound", ...
        "No channel-response profile matches profileRef.");
end
if acousticPresentText(rows.run_type(1)) ~= "acoustic_channel_response_estimate"
    error("vawlume:acoustic:ResponseProfileKindInvalid", ...
        "Analysis run %d is '%s', not acoustic_channel_response_estimate.", ...
        rows.analysis_run_id(1), acousticPresentText(rows.run_type(1)));
end
analysis = struct( ...
    analysis_run_id=double(rows.analysis_run_id(1)), ...
    project_id=double(rows.project_id(1)), ...
    project_key=acousticPresentText(rows.project_key(1)), ...
    run_key=acousticPresentText(rows.run_key(1)), ...
    run_type=acousticPresentText(rows.run_type(1)), ...
    run_label=acousticPresentText(rows.run_label(1)), ...
    vawlume_version=acousticPresentText(rows.vawlume_version(1)), ...
    source_commit=acousticPresentText(rows.source_commit(1)), ...
    status=acousticPresentText(rows.status(1)), ...
    started_at_utc=acousticPresentText(rows.started_at_utc(1)), ...
    completed_at_utc=acousticPresentText(rows.completed_at_utc(1)), ...
    notes=acousticPresentText(rows.notes(1)));
end

function rows = normalizeEstimates(rows)
if isempty(rows)
    return
end
numeric = ["channel_response_estimate_id", "analysis_run_id", "recording_id", ...
    "recording_channel_id", "channel_index", "metric_definition_id", ...
    "frequency_min_hz", "frequency_max_hz", "value_real"];
for name = numeric
    rows.(name) = double(rows.(name));
end
rows.frequency_min_hz(rows.frequency_min_hz < 0) = NaN;
rows.frequency_max_hz(rows.frequency_max_hz < 0) = NaN;
rows.value_real(rows.value_real == -realmax) = NaN;
rows = normalizeTextTable(rows);
end

function rows = normalizeSources(rows)
if isempty(rows)
    return
end
numeric = ["channel_response_estimate_id", "derived_measurement_id", ...
    "source_analysis_run_id", "metric_definition_id", "value_real", ...
    "acoustic_reference_id", "start_time_s", "end_time_s", ...
    "frequency_min_hz", "frequency_max_hz", "recording_channel_id", ...
    "channel_index"];
for name = numeric
    rows.(name) = double(rows.(name));
end
rows.frequency_min_hz(rows.frequency_min_hz < 0) = NaN;
rows.frequency_max_hz(rows.frequency_max_hz < 0) = NaN;
rows = normalizeTextTable(rows);
end

function rows = normalizeTextTable(rows)
if isempty(rows)
    return
end
for index = 1:width(rows)
    name = rows.Properties.VariableNames{index};
    value = rows.(name);
    if iscellstr(value) || ischar(value) || isstring(value)
        rows.(name) = string(value);
    end
end
end

function value = requiredText(raw, label)
value = string(raw);
if ~isscalar(value) || ismissing(value) || strlength(value) == 0
    error("vawlume:acoustic:ResponseProfileRefInvalid", ...
        "profileRef.%s must be nonempty scalar text.", label);
end
end
