function stream = trackingResolveStream(conn, streamRef)
%TRACKINGRESOLVESTREAM Resolve one registered tracking stream and its context.
%
% Returns the stream with its clock and its declared spatial frame attached, so
% every caller sees which frame the coordinates it is about to read are stated
% in rather than assuming one.

hasId = isfield(streamRef, "external_stream_id");
hasPortable = isfield(streamRef, "project_key") && isfield(streamRef, "stream_name");
if hasId == hasPortable
    error("vawlume:tracking:StreamRefInvalid", ...
        "streamRef must contain exactly one selector: external_stream_id, or " + ...
        "project_key plus stream_name.");
end

columns = "SELECT es.external_stream_id, es.project_id, p.project_key, " + ...
    "IFNULL(es.recording_id, -1) AS recording_id, es.stream_name, " + ...
    "es.stream_kind, tb.timebase_id, tb.timebase_name, " + ...
    "ts.coordinate_system_id, cs.coordinate_system_key, cs.dimensionality, " + ...
    "cs.unit, ts.native_time_basis, " + ...
    "IFNULL(ts.nominal_frame_rate_hz, -1) AS nominal_frame_rate_hz, " + ...
    "ts.has_confidence, " + ...
    "IFNULL(ts.declared_sample_count, -1) AS declared_sample_count " + ...
    "FROM external_streams es " + ...
    "JOIN projects p ON p.project_id=es.project_id " + ...
    "JOIN timebases tb ON tb.timebase_id=es.timebase_id " + ...
    "JOIN tracking_streams ts ON ts.external_stream_id=es.external_stream_id " + ...
    "JOIN coordinate_systems cs ON cs.coordinate_system_id=ts.coordinate_system_id " + ...
    "WHERE ";

if hasId
    id = streamRef.external_stream_id;
    if ~isnumeric(id) || ~isscalar(id) || ~isfinite(id) || id <= 0 || id ~= floor(id)
        error("vawlume:tracking:StreamRefInvalid", ...
            "external_stream_id must be a positive integer.");
    end
    rows = fetch(conn, columns + "es.external_stream_id=" + string(double(id)));
else
    rows = fetch(conn, columns + "p.project_key=" + ...
        trackingSqlText(streamRef.project_key) + " AND es.stream_name=" + ...
        trackingSqlText(streamRef.stream_name));
end

if isempty(rows) || height(rows) == 0
    error("vawlume:tracking:StreamNotFound", ...
        "No registered tracking stream matches streamRef. A stream must be " + ...
        "registered before its samples can be read.");
end
if height(rows) ~= 1
    error("vawlume:tracking:StreamAmbiguous", ...
        "streamRef matched %d tracking streams; exactly one is required.", ...
        height(rows));
end

frameRate = double(rows.nominal_frame_rate_hz(1));
if frameRate < 0
    frameRate = NaN;
end
sampleCount = double(rows.declared_sample_count(1));
if sampleCount < 0
    sampleCount = NaN;
end

stream = struct( ...
    external_stream_id=double(rows.external_stream_id(1)), ...
    project_id=double(rows.project_id(1)), ...
    project_key=trackingPresentText(rows.project_key(1)), ...
    recording_id=double(rows.recording_id(1)), ...
    stream_name=trackingPresentText(rows.stream_name(1)), ...
    stream_kind=trackingPresentText(rows.stream_kind(1)), ...
    timebase_id=double(rows.timebase_id(1)), ...
    timebase_name=trackingPresentText(rows.timebase_name(1)), ...
    coordinate_system_id=double(rows.coordinate_system_id(1)), ...
    coordinate_system_key=trackingPresentText(rows.coordinate_system_key(1)), ...
    dimensionality=double(rows.dimensionality(1)), ...
    unit=trackingPresentText(rows.unit(1)), ...
    native_time_basis=trackingPresentText(rows.native_time_basis(1)), ...
    nominal_frame_rate_hz=frameRate, ...
    has_confidence=logical(double(rows.has_confidence(1))), ...
    declared_sample_count=sampleCount);
end
