function [plan, counts] = trackingApplyPlan(conn, plan)
%TRACKINGAPPLYPLAN Atomically register one tracking stream.
%
% The stream, its artifact provenance, its mapping profile version, its subtype
% facts, its traces, and its coverage commit together or not at all. A failure
% part way through must not leave an external stream claiming tracking exists
% while its frame, traces, or coverage do not, so the whole registration runs in
% one transaction and any exception rolls it back before rethrowing.
%
% No tracking sample is written. There is no table that could hold one.

if plan.has_conflicts
    error("vawlume:tracking:PlanConflict", ...
        "A tracking plan with identity conflicts cannot be applied.");
end

counts = emptyCounts();
if plan.stream.action == "reuse"
    counts.reused_external_streams = 1;
    plan.status = "reused";
    return
end

oldAutoCommit = string(conn.AutoCommit);
if oldAutoCommit ~= "on"
    error("vawlume:tracking:TransactionState", ...
        "Tracking apply requires a connection with AutoCommit enabled.");
end
conn.AutoCommit = "off";
try
    [plan, counts] = applySource(conn, plan, counts);
    [plan, counts] = applyProfile(conn, plan, counts);
    [plan, counts] = applyStream(conn, plan, counts);
    [plan, counts] = applySeries(conn, plan, counts);
    counts = applyCoverage(conn, plan, counts);
    commit(conn);
catch exception
    try
        rollback(conn);
    catch
    end
    conn.AutoCommit = oldAutoCommit;
    rethrow(exception);
end
conn.AutoCommit = oldAutoCommit;
plan.status = "committed";
end

function [plan, counts] = applySource(conn, plan, counts)
%APPLYSOURCE The dense artifact is registered as provenance, never as content.
artifact = plan.artifact;
rows = fetch(conn, "SELECT source_file_id FROM source_files " + ...
    "WHERE project_id=" + string(plan.recording.project_id) + ...
    " AND path_or_uri=" + trackingSqlText(artifact.path_or_uri));
if ~isempty(rows) && height(rows) > 0
    plan.artifact.source_file_id = double(rows.source_file_id(1));
    counts.reused_source_files = counts.reused_source_files + 1;
    return
end

plan.artifact.source_file_id = trackingInsertRow(conn, "source_files", struct( ...
    project_id=plan.recording.project_id, file_role="tracking_export", ...
    path_or_uri=artifact.path_or_uri, relative_path=artifact.relative_path, ...
    filename=artifact.filename, file_format=artifact.file_format, ...
    size_bytes=artifact.size_bytes, checksum_sha256=artifact.checksum_sha256), ...
    "source_file_id");
counts.source_files = counts.source_files + 1;
end

function [plan, counts] = applyProfile(conn, plan, counts)
profile = plan.profile;
rows = fetch(conn, "SELECT profile_id FROM config_profiles " + ...
    "WHERE project_id=" + string(plan.recording.project_id) + ...
    " AND profile_key=" + trackingSqlText(profile.profile_key));
if ~isempty(rows) && height(rows) > 0
    profileId = double(rows.profile_id(1));
    counts.reused_config_profiles = counts.reused_config_profiles + 1;
else
    profileId = trackingInsertRow(conn, "config_profiles", struct( ...
        project_id=plan.recording.project_id, profile_key=profile.profile_key, ...
        profile_name=profile.profile_name, profile_kind="tracking_input_mapping", ...
        is_builtin=0, ...
        description="Tracking mapping profile registered by tracking intake."), ...
        "profile_id");
    counts.config_profiles = counts.config_profiles + 1;
end

versions = fetch(conn, "SELECT profile_version_id, " + ...
    "IFNULL(checksum_sha256,'') AS checksum_sha256 FROM config_profile_versions " + ...
    "WHERE profile_id=" + string(profileId) + ...
    " AND version_label=" + trackingSqlText(profile.version_label));
if ~isempty(versions) && height(versions) > 0
    plan.profile.profile_version_id = double(versions.profile_version_id(1));
    counts.reused_config_profile_versions = counts.reused_config_profile_versions + 1;
else
    plan.profile.profile_version_id = trackingInsertRow(conn, ...
        "config_profile_versions", struct( ...
        profile_id=profileId, version_label=profile.version_label, ...
        profile_schema_version=profile.profile_schema_version, ...
        content_format="json", content_uri=profile.content_uri, ...
        checksum_sha256=profile.checksum_sha256, is_snapshot=1, ...
        notes="Exact tracking mapping profile used by one registration."), ...
        "profile_version_id");
    counts.config_profile_versions = counts.config_profile_versions + 1;
end
plan.profile.profile_id = profileId;
end

function [plan, counts] = applyStream(conn, plan, counts)
facts = plan.stream_facts;

streamId = trackingInsertRow(conn, "external_streams", struct( ...
    project_id=plan.recording.project_id, ...
    recording_id=plan.recording.recording_id, ...
    timebase_id=plan.timebase.timebase_id, ...
    stream_name=plan.stream.stream_name, ...
    stream_kind="tracking", ...
    modality="pose_tracking", ...
    notes=plan.spec.notes), "external_stream_id");
plan.stream.external_stream_id = streamId;
counts.external_streams = counts.external_streams + 1;

trackingInsertRow(conn, "external_stream_sources", struct( ...
    external_stream_id=streamId, ...
    source_file_id=plan.artifact.source_file_id, ...
    source_role="other", ...
    mapping_profile_version_id=plan.profile.profile_version_id, ...
    source_locator=plan.artifact.relative_path, ...
    notes="Dense tracking samples remain in this artifact and are read window-wise."));
counts.external_stream_sources = counts.external_stream_sources + 1;

values = struct( ...
    external_stream_id=streamId, ...
    coordinate_system_id=plan.coordinate_system.coordinate_system_id, ...
    native_time_basis=facts.native_time_basis, ...
    has_confidence=double(facts.has_confidence), ...
    declared_sample_count=facts.declared_sample_count);
if ~isnan(facts.nominal_frame_rate_hz)
    values.nominal_frame_rate_hz = facts.nominal_frame_rate_hz;
end
trackingInsertRow(conn, "tracking_streams", values);
counts.tracking_streams = counts.tracking_streams + 1;
end

function [plan, counts] = applySeries(conn, plan, counts)
%APPLYSERIES One row per trace. Never one per sample.
series = plan.series;
for index = 1:height(series)
    row = table2struct(series(index, :));
    values = struct( ...
        external_stream_id=plan.stream.external_stream_id, ...
        native_track_id=row.native_track_id, ...
        native_bodypart_label=row.native_bodypart_label, ...
        canonical_bodypart_role=row.canonical_bodypart_role);
    trackingInsertRow(conn, "tracking_series", values);
    counts.tracking_series = counts.tracking_series + 1;
end
end

% NO ENTITY RESOLUTION HAPPENS HERE, DELIBERATELY.
%
% An earlier draft of this function looked up experimental_entities by
% native_id = native track label and wrote the match onto the series row. That
% is exactly the inference the architecture forbids: a tracker emitting
% 'mouse_a' is naming a trajectory, not asserting which animal that trajectory
% follows, and a string match on an animal-like name is not evidence. Worse, the
% stored result was indistinguishable from a verified assertion, and it forced
% one identity per trace for an entire session - so an identity swap mid-session
% could not be represented at all.
%
% Track-to-entity association is time-varying evidence with its own score
% semantics, calibration status, review state and provenance. It is a separate
% layer, and registration deliberately produces none of it.

function counts = applyCoverage(conn, plan, counts)
coverage = plan.coverage;
for index = 1:height(coverage)
    row = table2struct(coverage(index, :));
    trackingInsertRow(conn, "external_stream_coverage", struct( ...
        external_stream_id=plan.stream.external_stream_id, ...
        segment_index=row.segment_index, ...
        start_time_native=row.start_time_native, ...
        end_time_native=row.end_time_native, ...
        observation_status="observed", ...
        source_locator=row.source_locator, ...
        notes="Observed span derived from the artifact's own native time range."));
    counts.external_stream_coverage = counts.external_stream_coverage + 1;
end
end

function counts = emptyCounts()
counts = struct( ...
    source_files=0, reused_source_files=0, ...
    config_profiles=0, reused_config_profiles=0, ...
    config_profile_versions=0, reused_config_profile_versions=0, ...
    external_streams=0, reused_external_streams=0, ...
    external_stream_sources=0, ...
    tracking_streams=0, tracking_series=0, ...
    external_stream_coverage=0);
end
