function recording = trackingResolveRecording(conn, recordingRef)
%TRACKINGRESOLVERECORDING Resolve exactly one recording from a selector struct.
%
% Same selector vocabulary as matching, agreement and geometry: recording_id, or
% project_key plus source_relative_path, never both.

hasId = isfield(recordingRef, "recording_id");
hasPortable = isfield(recordingRef, "project_key") && ...
    isfield(recordingRef, "source_relative_path");
if hasId == hasPortable
    error("vawlume:tracking:RecordingRefInvalid", ...
        "recordingRef must contain exactly one selector: recording_id, or " + ...
        "project_key plus source_relative_path.");
end

columns = "SELECT r.recording_id, r.project_id, p.project_key, " + ...
    "IFNULL(sf.relative_path,'') AS source_relative_path " + ...
    "FROM recordings r JOIN projects p ON p.project_id=r.project_id " + ...
    "JOIN source_files sf ON sf.source_file_id=r.source_file_id WHERE ";
if hasId
    id = recordingRef.recording_id;
    if ~isnumeric(id) || ~isscalar(id) || ~isfinite(id) || id <= 0 || id ~= floor(id)
        error("vawlume:tracking:RecordingRefInvalid", ...
            "recording_id must be a positive integer.");
    end
    rows = fetch(conn, columns + "r.recording_id=" + string(double(id)));
else
    rows = fetch(conn, columns + "p.project_key=" + ...
        trackingSqlText(recordingRef.project_key) + ...
        " AND sf.relative_path=" + trackingSqlText(recordingRef.source_relative_path));
end

if isempty(rows) || height(rows) == 0
    error("vawlume:tracking:RecordingNotFound", ...
        "No established recording matches recordingRef.");
end
if height(rows) ~= 1
    error("vawlume:tracking:RecordingAmbiguous", ...
        "recordingRef matched %d recordings; exactly one is required.", height(rows));
end

recording = struct( ...
    recording_id=double(rows.recording_id(1)), ...
    project_id=double(rows.project_id(1)), ...
    project_key=trackingPresentText(rows.project_key(1)), ...
    source_relative_path=trackingPresentText(rows.source_relative_path(1)));
end
