function result = trackingPlanResult(plan)
%TRACKINGPLANRESULT The caller-facing view of a tracking registration.
%
% Deliberately summary-shaped. It reports the stream, its frame, its clock, its
% traces and its span - never samples - so a dry run reads as "here is what would
% be registered" rather than as a data dump.

facts = plan.stream_facts;

result = struct();
result.status = plan.status;
result.committed = false;
result.has_conflicts = plan.has_conflicts;
result.conflicts = plan.conflicts;

result.recording = struct( ...
    recording_id=plan.recording.recording_id, ...
    project_key=plan.recording.project_key);

result.stream = struct( ...
    stream_name=plan.stream.stream_name, ...
    stream_key=string(facts.stream_key), ...
    action=plan.stream.action, ...
    external_stream_id=plan.stream.external_stream_id, ...
    stream_kind="tracking", ...
    native_time_basis=string(facts.native_time_basis), ...
    nominal_frame_rate_hz=facts.nominal_frame_rate_hz, ...
    has_confidence=logical(facts.has_confidence), ...
    declared_sample_count=facts.declared_sample_count);

result.coordinate_system = plan.coordinate_system;
result.timebase = plan.timebase;

result.artifact = struct( ...
    relative_path=plan.artifact.relative_path, ...
    filename=plan.artifact.filename, ...
    checksum_sha256=plan.artifact.checksum_sha256, ...
    size_bytes=plan.artifact.size_bytes);

result.profile = struct( ...
    profile_key=plan.profile.profile_key, ...
    version_label=plan.profile.version_label, ...
    checksum_sha256=plan.profile.checksum_sha256);

result.series = plan.series(:, ["native_track_id", "native_bodypart_label", ...
    "canonical_bodypart_role", "sample_count", "status"]);
result.column_contract = plan.ir.tracking_columns(:, ["role", "source_field", ...
    "actual_source_field", "column_resolution", "is_required", "status"]);
result.coverage = plan.coverage(:, ["segment_index", "start_time_native", ...
    "end_time_native", "start_time_s", "end_time_s", "observation_status"]);

result.issues = plan.ir.issues;
result.valid_for_ingest = plan.ir.valid_for_ingest;
result.applied_counts = struct();

% The one claim this layer makes about itself, stated where a caller reading the
% result will see it.
result.dense_samples_stored = 0;
result.dense_sample_policy = "Positions, frames and confidences remain in the " + ...
    "registered artifact and are read window-wise on demand. No tracking " + ...
    "sample is written to SQLite.";
end
