function recording = geometryResolveRecording(conn, recordingRef)
%GEOMETRYRESOLVERECORDING Resolve exactly one recording from a selector struct.
%
% The selector vocabulary matches the matching and agreement layers so a caller
% who can address a recording for one of those can address it here unchanged:
% recording_id, or project_key plus source_relative_path, never both.

hasId = isfield(recordingRef, "recording_id");
hasPortable = isfield(recordingRef, "project_key") && ...
    isfield(recordingRef, "source_relative_path");
if hasId == hasPortable
    error("vawlume:geometry:RecordingRefInvalid", ...
        "recordingRef must contain exactly one selector: recording_id, or " + ...
        "project_key plus source_relative_path.");
end

columns = "SELECT r.recording_id, r.project_id, p.project_key, " + ...
    "IFNULL(sf.relative_path,'') AS source_relative_path " + ...
    "FROM recordings r JOIN projects p ON p.project_id=r.project_id " + ...
    "JOIN source_files sf ON sf.source_file_id=r.source_file_id WHERE ";
if hasId
    id = geometryPositiveInteger(recordingRef.recording_id, "recording_id");
    rows = fetch(conn, columns + "r.recording_id=" + string(id));
else
    projectKey = geometryScalarText(recordingRef.project_key, "project_key");
    relativePath = geometryScalarText(recordingRef.source_relative_path, ...
        "source_relative_path");
    rows = fetch(conn, columns + "p.project_key=" + geometrySqlText(projectKey) + ...
        " AND sf.relative_path=" + geometrySqlText(relativePath));
end

if isempty(rows) || height(rows) == 0
    error("vawlume:geometry:RecordingNotFound", ...
        "No established recording matches recordingRef.");
end
if height(rows) ~= 1
    error("vawlume:geometry:RecordingAmbiguous", ...
        "recordingRef matched %d recordings; exactly one is required.", ...
        height(rows));
end

recording = struct( ...
    recording_id=double(rows.recording_id(1)), ...
    project_id=double(rows.project_id(1)), ...
    project_key=geometryPresentText(rows.project_key(1)), ...
    source_relative_path=geometryPresentText(rows.source_relative_path(1)));
end
