function channel = geometryResolveChannel(conn, recording, placementSpec)
%GEOMETRYRESOLVECHANNEL Resolve one established recording channel by index.
%
% A channel is never created here. Channels are established when a recording is
% registered, and inventing one during placement registration would let a
% placement assert geometry for a channel that carries no audio.

if ~isfield(placementSpec, "channel_index")
    error("vawlume:geometry:PlacementInvalid", ...
        "placementSpec.channel_index is required and must identify an " + ...
        "established recording channel.");
end
index = geometryPositiveInteger(placementSpec.channel_index, "channel_index");

rows = fetch(conn, "SELECT recording_channel_id, channel_index, " + ...
    "IFNULL(channel_label,'') AS channel_label, " + ...
    "IFNULL(channel_role,'') AS channel_role FROM recording_channels " + ...
    "WHERE recording_id=" + string(recording.recording_id) + ...
    " AND channel_index=" + string(index));

if isempty(rows) || height(rows) == 0
    error("vawlume:geometry:RecordingChannelNotFound", ...
        "Recording %d has no channel %d. Placement locates an established " + ...
        "channel; it never creates one.", recording.recording_id, index);
end

channel = struct( ...
    recording_channel_id=double(rows.recording_channel_id(1)), ...
    channel_index=double(rows.channel_index(1)), ...
    channel_label=geometryPresentText(rows.channel_label(1)), ...
    channel_role=geometryPresentText(rows.channel_role(1)));
end
