function result = crossPatternComparison(profile, equivalenceClass)
%CROSSPATTERNCOMPARISON One feature across every support pattern, or a refusal.
%
% RESULT = vawlume.eda.CROSSPATTERNCOMPARISON(PROFILE, EQUIVALENCECLASS) returns
% the per-pattern distribution rows for one feature, for a caller that intends to
% put support pattern on an axis and that feature on the other. Called with no
% class it returns every class that may legitimately be used that way.
%
% IT REFUSES AN EXTRACTOR-RESTRICTED FEATURE. This is the whole reason the
% function exists. Contract §K's rule - only classes comparable across the entire
% participating extractor set may go on a cross-pattern axis - could have been a
% flag on the profile's feature rows, and a flag is a thing a caller reads when
% they remember to. A support pattern's members come from specific extractors by
% definition, so `vocalization_frequency_bandwidth` exists for a DeepSqueak-MUPET
% group and cannot exist for any pattern containing USVSEG. Plotting it by
% pattern compares populations that differ in whether the measurement exists at
% all: the apparent difference is the extractor composition, not the calls, and
% the plot looks entirely reasonable. A refusal at the point of use is the only
% version of this rule that cannot be skipped by not noticing.
%
% The refusal names the patterns the feature IS reportable in, because the caller
% usually has a real question and the answer is a within-pattern summary rather
% than nothing.
%
% Duration and centre frequency pass, which is the other half of the rule: the
% guard must not be so broad that it leaves nothing comparable. Contract §K
% readmits duration explicitly, even though the matching specification reserves
% it as primary evidence for classifying correspondence - a different question
% from describing what occupies a pattern.
%
% This function selects rows from a profile. It computes no statistic, opens no
% connection, and never re-derives a distribution: every number it returns was
% produced by vawlume.eda.supportPatternProfile.

arguments
    profile (1,1) struct
    equivalenceClass string = string.empty
end

requireFields(profile, ["features", "feature_eligibility", "patterns"]);
eligibility = profile.feature_eligibility;
comparable = eligibility.equivalence_class( ...
    eligibility.is_cross_pattern_comparable);

if isempty(equivalenceClass)
    result = struct( ...
        status="listed", ...
        cross_pattern_comparable=sort(comparable)', ...
        extractor_restricted=sort(eligibility.equivalence_class( ...
            ~eligibility.is_cross_pattern_comparable))', ...
        rule=ruleText(), ...
        reference_configuration=profile.reference_configuration, ...
        caution=profile.caution);
    return
end

name = string(equivalenceClass);
if ~isscalar(name)
    error("vawlume:eda:CrossPatternRequestInvalid", ...
        "Request one equivalence class at a time.");
end

known = eligibility.equivalence_class == name;
if ~any(known)
    error("vawlume:eda:FeatureNotRegistered", ...
        "'%s' is not a registered comparable feature class for these " + ...
        "extractors. Registered class(es): %s. Comparability is read from " + ...
        "feature_relationships and is never inferred from a feature name.", ...
        name, listOrNone(eligibility.equivalence_class));
end

selected = eligibility(known, :);
if ~selected.is_cross_pattern_comparable(1)
    error("vawlume:eda:FeatureNotCrossPatternComparable", ...
        "'%s' is registered as comparable only among %s, so it cannot be " + ...
        "placed on a cross-pattern axis: a support pattern's members come " + ...
        "from specific extractors by definition, and patterns outside that " + ...
        "set have no such measurement at all. The apparent difference would " + ...
        "be the extractor composition, not the calls. It IS reportable " + ...
        "within pattern(s) %s - read those rows from the profile's " + ...
        "`features` table instead.", ...
        name, selected.comparable_extractor_key(1), ...
        listOrNone(string(selected.eligible_patterns{1}(:))));
end

rows = profile.features(profile.features.equivalence_class == name, :);
result = struct( ...
    status="comparable", ...
    equivalence_class=name, ...
    canonical_unit=selected.canonical_unit(1), ...
    comparable_extractors=string(selected.comparable_extractors{1}(:))', ...
    is_readmitted_timing_class=selected.is_readmitted_timing_class(1), ...
    rows=rows, ...
    pattern_count=height(rows), ...
    low_coverage_patterns=rows.extractor_set_key(rows.is_low_coverage)', ...
    coverage_warning=coverageWarning(rows), ...
    rule=ruleText(), ...
    reference_configuration=profile.reference_configuration, ...
    interpretation_note=profile.interpretation_note, ...
    caution=profile.caution);
end

% -------------------------------------------------------------- plumbing ---

function value = ruleText()
value = "Only a feature class registered as comparable across the ENTIRE " + ...
    "participating extractor set may be placed on a cross-pattern axis. An " + ...
    "extractor-restricted class is reportable within the patterns whose " + ...
    "contributing extractors all register it, labelled as such, and never " + ...
    "across patterns.";
end

function value = coverageWarning(rows)
%COVERAGEWARNING Said in words beside the rows, not only as a column.
%
% A cross-pattern comparison is exactly the shape that gets plotted, and a
% pattern summarized from nine detections next to one summarized from four
% thousand looks identical on that plot. The warning travels with the result so
% it can reach a caption.
% EMPTY PATTERNS ARE NAMED SEPARATELY, not as low coverage. A pattern with no
% members is not a thinly measured one, and saying "0% of 0" would tell a reader
% the feature is poorly measured there when nothing is there to measure.
value = "";
if height(rows) == 0
    return
end
empty = rows(rows.pattern_population == 0, :);
thin = rows(rows.is_low_coverage, :);

parts = strings(0, 1);
if height(thin) > 0
    named = thin.extractor_set_label + " (" + ...
        compose("%.0f%%", 100 * thin.coverage_fraction) + " of " + ...
        string(thin.pattern_population) + ")";
    parts(end + 1) = "LOW COVERAGE in " + string(height(thin)) + ...
        " pattern(s): " + strjoin(named', "; ") + ". These summaries are " + ...
        "reported rather than filtered, because a low-coverage feature is a " + ...
        "finding about the extractor set - but they are not comparable " + ...
        "evidence to a well-covered pattern and must not be read as though " + ...
        "they were.";
end
if height(empty) > 0
    parts(end + 1) = string(height(empty)) + " pattern(s) hold no " + ...
        "detection at all and are reported with undefined statistics: " + ...
        strjoin(empty.extractor_set_label', "; ") + ". That is an absence of " + ...
        "members, not a thinly measured feature.";
end
if isempty(parts)
    value = "Every pattern's summary meets the coverage threshold.";
    return
end
value = strjoin(parts, " ");
end

function value = listOrNone(names)
if isempty(names)
    value = "none";
    return
end
value = strjoin(sort(unique(names))', ", ");
end

function requireFields(value, names)
missingNames = names(~isfield(value, names));
if ~isempty(missingNames)
    error("vawlume:eda:ProfileInputInvalid", ...
        "The profile is missing field(s): %s. Pass a " + ...
        "vawlume.eda.supportPatternProfile result.", ...
        strjoin(missingNames, ", "));
end
end
