function plan = exampleDisplayPlan(prepared, options)
%EXAMPLEDISPLAYPLAN Pure, assertable drawing instructions for one example.
%
% The plan contains every coordinate and label consumed by renderExample. It
% does not create graphics. Event geometry is copied from Part 12; the only
% coordinate conversion adds the recorded snippet start to the spectrogram's
% recorded snippet-relative frame centres.

arguments
    prepared (1,1) struct
    options.Styles table = table()
    options.ReferenceConfigurationId (1,1) string = ""
end

required = ["example_id", "recording", "extractor_set_key", "window", ...
    "frequency_bounds", ...
    "annotations", "spectrogram", "supported_extractor_pair_pattern", ...
    "reference_configuration", "approximate_extent_note", "caution"];
missingNames = required(~isfield(prepared, required));
if ~isempty(missingNames)
    error("vawlume:eda:ExampleRenderInputIncomplete", ...
        "The prepared example is missing field(s): %s.", ...
        strjoin(missingNames, ", "));
end
if string(prepared.spectrogram.status) ~= "computed"
    error("vawlume:eda:ExampleSpectrogramUnavailable", ...
        "Example '%s' has spectrogram status '%s', not 'computed'.", ...
        string(prepared.example_id), string(prepared.spectrogram.status));
end

annotations = prepared.annotations;
keys = sort(unique(string(annotations.extractor_key)));
styles = options.Styles;
if isempty(styles)
    styles = vawlume.eda.exampleStyles(keys);
end
validateStyles(styles, keys);

markerFrequencies = cell(height(annotations), 1);
annotations.color_r = zeros(height(annotations), 1);
annotations.color_g = zeros(height(annotations), 1);
annotations.color_b = zeros(height(annotations), 1);
annotations.line_style = strings(height(annotations), 1);
annotations.rectangle_x = nan(height(annotations), 1);
annotations.rectangle_y = nan(height(annotations), 1);
annotations.rectangle_width = nan(height(annotations), 1);
annotations.rectangle_height = nan(height(annotations), 1);
for index = 1:height(annotations)
    match = styles(styles.extractor_key == annotations.extractor_key(index), :);
    annotations.color_r(index) = match.color_r(1);
    annotations.color_g(index) = match.color_g(1);
    annotations.color_b(index) = match.color_b(1);
    annotations.line_style(index) = match.line_style(1);
    if ~annotations.has_measured_band(index)
        values = [annotations.frequency_min_hz(index), ...
            annotations.frequency_max_hz(index), ...
            annotations.frequency_center_hz(index), ...
            annotations.frequency_peak_hz(index)];
        markerFrequencies{index} = unique(values(isfinite(values)), "stable");
    else
        markerFrequencies{index} = zeros(1, 0);
        annotations.rectangle_x(index) = annotations.start_time_s(index);
        annotations.rectangle_y(index) = annotations.frequency_min_hz(index);
        annotations.rectangle_width(index) = annotations.end_time_s(index) - ...
            annotations.start_time_s(index);
        annotations.rectangle_height(index) = ...
            annotations.frequency_max_hz(index) - ...
            annotations.frequency_min_hz(index);
    end
end
annotations.marker_frequencies_hz = markerFrequencies;

referenceId = options.ReferenceConfigurationId;
if strlength(referenceId) == 0
    referenceId = string(prepared.reference_configuration.profile_key) + ...
        "@" + string(prepared.reference_configuration.version_label);
end

plan = struct( ...
    status="planned", ...
    example_id=string(prepared.example_id), ...
    recording_id=double(prepared.recording.recording_id), ...
    native_recording_id=string(prepared.recording.native_recording_id), ...
    extractor_set_key=string(prepared.extractor_set_key), ...
    supported_extractor_pair_pattern=string( ...
        prepared.supported_extractor_pair_pattern), ...
    reference_configuration_id=referenceId, ...
    x_limits_s=[prepared.window.actual_start_s, prepared.window.actual_end_s], ...
    y_limits_hz=[prepared.frequency_bounds.low_hz, ...
        prepared.frequency_bounds.high_hz], ...
    spectrogram_time_s=prepared.window.actual_start_s + ...
        double(prepared.spectrogram.time_s), ...
    spectrogram_frequency_hz=double(prepared.spectrogram.frequency_hz), ...
    spectrogram_matrix=double(prepared.spectrogram.matrix), ...
    annotations=annotations, ...
    styles=styles, ...
    legend=legendPlan(annotations, styles), ...
    identity_text=identityText(prepared, referenceId), ...
    approximate_extent_note=string(prepared.approximate_extent_note), ...
    caution=string(prepared.caution), ...
    style_ordering_note="styles are ordered lexically by extractor_key; " + ...
        "ordering carries no detection-count, support, or scientific meaning", ...
    coordinate_rule="spectrogram frame centres are snippet-relative; the " + ...
        "recorded actual snippet start is added exactly once", ...
    geometry_rule="annotation coordinates are copied from Part 12; a " + ...
        "rectangle is permitted only when has_measured_band is true");
end

function validateStyles(styles, keys)
required = ["extractor_key", "color_r", "color_g", "color_b", "line_style"];
if ~all(ismember(required, string(styles.Properties.VariableNames)))
    error("vawlume:eda:ExampleStylesInvalid", ...
        "Styles must contain: %s.", strjoin(required, ", "));
end
for key = keys'
    if sum(styles.extractor_key == key) ~= 1
        error("vawlume:eda:ExampleStylesInvalid", ...
            "Styles must contain exactly one row for extractor '%s'.", key);
    end
end
end

function value = legendPlan(annotations, styles)
keys = sort(unique(annotations.extractor_key));
labels = strings(numel(keys), 1);
for index = 1:numel(keys)
    rows = annotations(annotations.extractor_key == keys(index), :);
    hasBand = rows.has_measured_band;
    if all(hasBand)
        description = "measured band edges";
    elseif any(hasBand)
        description = "mixed measured bands and no-band time extents";
    else
        sources = strjoin(unique(rows.frequency_extent_source, "stable")', ", ");
        description = "no measured band; " + sources;
    end
    labels(index) = keys(index) + " — " + description;
end
value = styles(ismember(styles.extractor_key, keys), :);
[~, order] = ismember(keys, value.extractor_key);
value = value(order, :);
value.legend_label = labels;
end

function value = identityText(prepared, referenceId)
annotations = prepared.annotations;
native = annotations.extractor_key + ":" + annotations.native_event_id;
pairPattern = string(prepared.supported_extractor_pair_pattern);
if strlength(pairPattern) == 0
    pairPattern = "(no supported extractor pair)";
end
value = "Example " + string(prepared.example_id) + ...
    " | recording " + string(prepared.recording.recording_id) + ...
    " (" + string(prepared.recording.native_recording_id) + ")" + newline + ...
    "Extractor-set gallery category: " + string(prepared.extractor_set_key) + ...
    newline + ...
    "Exact supported-pair pattern: " + pairPattern + newline + ...
    "Native calls: " + strjoin(native', " | ") + newline + ...
    "Reference configuration: " + referenceId + newline + ...
    compose("Window requested %.6f–%.6f s; actual %.6f–%.6f s; " + ...
        "clamped start=%s, end=%s", prepared.window.requested_start_s, ...
        prepared.window.requested_end_s, prepared.window.actual_start_s, ...
        prepared.window.actual_end_s, string(prepared.window.is_clamped_at_start), ...
        string(prepared.window.is_clamped_at_end));
end
