function result = prepareExample(conn, example, options)
%PREPAREEXAMPLE Everything one picture needs, without drawing the picture.
%
% RESULT = vawlume.eda.PREPAREEXAMPLE(CONN, EXAMPLE) turns one row of a
% vawlume.eda.sampleExamples result into the audio window, the channel, the
% frequency bounds, the spectrogram matrix and its settings record, and one
% annotation specification per member detection.
%
% EXAMPLE is a one-row table or a struct carrying at least `agreement_group_id`;
% `example_id` and the reference identity are carried through when present.
%
% Name-value options:
%   PaddingPreS / PaddingPostS   seconds around the group extent, default 0.05
%   ChannelIndex                 explicit channel; default the recording's only
%                                channel, and required when it has several
%   SourceRoot                   root for relative audio paths
%   FrequencyMarginHz            widening of measured bounds, default 10000
%   DefaultFrequencyLimitsHz     used when no member measured a band edge
%   FrequencyFloorHz             lower clamp, default 0
%   IncludeAudio                 read audio and compute the spectrogram,
%                                default true
%   Spectrogram*                 forwarded to vawlume.eda.spectrogramMatrix
%
% THIS FUNCTION DRAWS NOTHING. No figure, no axes, no image file. Every return is
% a value a test can assert on, which is what lets Part 13 inherit a settled
% shape rather than negotiating geometry and rendering at once.
%
% CLAMPING IS NEVER SILENT. A call near the start or end of a recording yields an
% asymmetric window, and a reader looking at an off-centre call has to be able to
% tell that from a call that was genuinely off-centre in its window. Requested and
% actual bounds are both recorded, following `readAudioWindow`'s own
% requested-versus-covered pattern rather than inventing a second convention.
%
% THE CHANNEL IS NEVER CHOSEN BY SIGNAL CONTENT. Picking the loudest channel
% would make the image depend on the signal being illustrated, so two runs over
% one example could show different pictures and neither would be wrong. A
% recording with one channel uses it; a recording with several requires the
% caller to say which.
%
% FREQUENCY BOUNDS SAY WHETHER THEY WERE DERIVED OR DEFAULTED. When no member
% measured a band edge - the all-USVSEG case, which is not hypothetical - the
% bounds come from a configured default and `frequency_bounds.source` says so. A
% viewer must be able to tell a frequency axis chosen by the data from one chosen
% by a constant, because the two look identical.
%
% NOTHING IS SYNTHESIZED IN AN ANNOTATION. See edaMemberAnnotations: a detection
% with a centre frequency and no band edges produces no rectangle, by any route.

arguments
    conn
    example
    options.PaddingPreS (1,1) double {mustBeNonnegative} = 0.05
    options.PaddingPostS (1,1) double {mustBeNonnegative} = 0.05
    options.ChannelIndex double = []
    options.SourceRoot (1,1) string = ""
    options.FrequencyMarginHz (1,1) double {mustBeNonnegative} = 10000
    options.DefaultFrequencyLimitsHz (1,2) double = [20000, 120000]
    options.FrequencyFloorHz (1,1) double {mustBeNonnegative} = 0
    options.IncludeAudio (1,1) logical = true
    options.SpectrogramWindowLengthSamples double = []
    options.SpectrogramHopSamples double = []
    options.SpectrogramFftLength double = []
    options.SpectrogramScaling (1,1) string = "power_db"
end

identity = exampleIdentity(example);
[group, members] = readGroup(conn, identity.agreement_group_id);
recording = readRecording(conn, group.recording_id);
extent = readExtent(conn, identity.agreement_group_id);

window = snippetWindow(extent, recording, options);
channel = resolveChannel(conn, recording, options);
annotations = edaMemberAnnotations(conn, members, ...
    [window.actual_start_s, window.actual_end_s]);
bounds = frequencyBounds(annotations, recording, options);

audio = struct(status="not_requested");
spectrogram = struct(status="not_requested");
if options.IncludeAudio
    audio = readAudio(conn, recording, channel, window, options);
    spectrogram = computeSpectrogram(audio, bounds, window, channel, options);
end

result = struct( ...
    status="prepared", ...
    example_id=identity.example_id, ...
    agreement_group_id=identity.agreement_group_id, ...
    group_key=string(group.group_key), ...
    extractor_set_key=memberSetKey(members), ...
    supported_extractor_pair_pattern=string( ...
        group.supported_extractor_pair_pattern), ...
    reference_configuration=identity.reference, ...
    recording=recording, ...
    group_extent=extent, ...
    window=window, ...
    channel=channel, ...
    frequency_bounds=bounds, ...
    annotations=annotations, ...
    member_count=height(members), ...
    audio=audio, ...
    spectrogram=spectrogram, ...
    extent_vocabulary=edaFrequencyExtentSources()', ...
    approximate_extent_note=approximateExtentNote(), ...
    draws_nothing="this function returns values only; no figure, axes or " + ...
        "image file is created anywhere in Part 12", ...
    caution=edaCautionNote());
end

% ------------------------------------------------------------- the group ---

function [group, members] = readGroup(conn, groupId)
rows = fetch(conn, "SELECT agreement_group_id, recording_id, " + ...
    "IFNULL(group_key,'') AS group_key, " + ...
    "IFNULL(supported_extractor_pair_pattern,'') AS " + ...
    "supported_extractor_pair_pattern " + ...
    "FROM v_agreement_group_summary WHERE agreement_group_id=" + ...
    string(groupId));
if isempty(rows) || height(rows) == 0
    error("vawlume:eda:ExampleGroupNotFound", ...
        "Agreement group %d does not exist.", groupId);
end
group = struct( ...
    agreement_group_id=double(rows.agreement_group_id(1)), ...
    recording_id=double(rows.recording_id(1)), ...
    group_key=edaPresentText(rows.group_key(1)), ...
    supported_extractor_pair_pattern=edaPresentText( ...
        rows.supported_extractor_pair_pattern(1)));

memberRows = fetch(conn, "SELECT m.agreement_group_id, m.detection_id, " + ...
    "IFNULL(m.extractor_key,'') AS extractor_key, " + ...
    "IFNULL(m.extractor_name,'') AS extractor_name, " + ...
    "IFNULL(m.native_event_id,'') AS native_event_id, " + ...
    "m.start_time_s, m.end_time_s " + ...
    "FROM v_agreement_group_members m WHERE m.agreement_group_id=" + ...
    string(groupId) + " ORDER BY m.extractor_key, m.detection_id");
if isempty(memberRows) || height(memberRows) == 0
    error("vawlume:eda:ExampleGroupEmpty", ...
        "Agreement group %d holds no member detection.", groupId);
end
members = table(double(memberRows.agreement_group_id), ...
    double(memberRows.detection_id), ...
    edaPresentText(memberRows.extractor_key), ...
    edaPresentText(memberRows.extractor_name), ...
    edaPresentText(memberRows.native_event_id), ...
    double(memberRows.start_time_s), double(memberRows.end_time_s), ...
    VariableNames=["agreement_group_id", "detection_id", "extractor_key", ...
    "extractor_name", "native_event_id", "start_time_s", "end_time_s"]);
end

function value = readExtent(conn, groupId)
%READEXTENT The union extent, from the view rather than recomputed.
%
% `v_agreement_group_extent` already reports union, intersection, mean and the
% longest and shortest member boundaries with their counts. Recomputing a union
% from members here would be a second definition of a quantity the schema
% already names.
rows = fetch(conn, "SELECT start_time_s, end_time_s, member_count, " + ...
    "extractor_count, onset_spread_s, offset_spread_s " + ...
    "FROM v_agreement_group_extent WHERE agreement_group_id=" + ...
    string(groupId) + " AND extent_method='union_boundary_of_members'");
if isempty(rows) || height(rows) == 0
    error("vawlume:eda:ExampleExtentUnavailable", ...
        "Agreement group %d has no union extent.", groupId);
end
value = struct( ...
    extent_method="union_boundary_of_members", ...
    start_time_s=double(rows.start_time_s(1)), ...
    end_time_s=double(rows.end_time_s(1)), ...
    duration_s=double(rows.end_time_s(1)) - double(rows.start_time_s(1)), ...
    member_count=double(rows.member_count(1)), ...
    extractor_count=double(rows.extractor_count(1)), ...
    onset_spread_s=double(rows.onset_spread_s(1)), ...
    offset_spread_s=double(rows.offset_spread_s(1)), ...
    source="v_agreement_group_extent");
end

function value = readRecording(conn, recordingId)
rows = fetch(conn, "SELECT recording_id, " + ...
    "IFNULL(native_recording_id,'') AS native_recording_id, " + ...
    "IFNULL(sample_rate_hz,-1) AS sample_rate_hz, " + ...
    "IFNULL(channel_count,-1) AS channel_count, " + ...
    "IFNULL(duration_s,-1) AS duration_s " + ...
    "FROM recordings WHERE recording_id=" + string(recordingId));
if isempty(rows) || height(rows) == 0
    error("vawlume:eda:ExampleRecordingNotFound", ...
        "Recording %d does not exist.", recordingId);
end
value = struct( ...
    recording_id=double(rows.recording_id(1)), ...
    native_recording_id=edaPresentText(rows.native_recording_id(1)), ...
    sample_rate_hz=presentNumber(rows.sample_rate_hz(1)), ...
    channel_count=presentNumber(rows.channel_count(1)), ...
    duration_s=presentNumber(rows.duration_s(1)));
end

% ------------------------------------------------------------- the window ---

function value = snippetWindow(extent, recording, options)
%SNIPPETWINDOW The group extent plus padding, clamped to the recording.
%
% Requested and actual are both recorded. A call 20 ms from the start of a
% recording cannot have 50 ms of leading padding, so its window is asymmetric -
% and the picture shows a call sitting off to the left, which is
% indistinguishable from a call that was simply late in its window unless the
% clamping is stated.
requestedStart = extent.start_time_s - options.PaddingPreS;
requestedEnd = extent.end_time_s + options.PaddingPostS;

limit = recording.duration_s;
if ~isfinite(limit) || limit <= 0
    limit = Inf;
end
actualStart = min(max(requestedStart, 0), limit);
actualEnd = min(max(requestedEnd, actualStart), limit);

value = struct( ...
    requested_start_s=requestedStart, ...
    requested_end_s=requestedEnd, ...
    requested_duration_s=requestedEnd - requestedStart, ...
    actual_start_s=actualStart, ...
    actual_end_s=actualEnd, ...
    actual_duration_s=actualEnd - actualStart, ...
    padding_pre_s=options.PaddingPreS, ...
    padding_post_s=options.PaddingPostS, ...
    realized_padding_pre_s=max(extent.start_time_s - actualStart, 0), ...
    realized_padding_post_s=max(actualEnd - extent.end_time_s, 0), ...
    is_clamped_at_start=actualStart > requestedStart + 1e-12, ...
    is_clamped_at_end=actualEnd < requestedEnd - 1e-12, ...
    is_symmetric=abs((extent.start_time_s - actualStart) - ...
        (actualEnd - extent.end_time_s)) <= 1e-12, ...
    recording_duration_s=recording.duration_s, ...
    clamp_note="requested and actual bounds are both recorded; an " + ...
        "asymmetric window means the recording boundary clamped the " + ...
        "padding, not that the call sits off-centre");
end

% ------------------------------------------------------------ the channel ---

function value = resolveChannel(conn, recording, options)
%RESOLVECHANNEL Explicit, or the only one there is - never by signal content.
%
% Choosing the loudest channel would make the image a function of the signal it
% illustrates: the same example could render differently on two runs and neither
% would be detectably wrong. So: one channel means that channel; several means
% the caller says which.
rows = fetch(conn, "SELECT channel_index, " + ...
    "IFNULL(channel_label,'') AS channel_label, " + ...
    "IFNULL(channel_role,'') AS channel_role " + ...
    "FROM recording_channels WHERE recording_id=" + ...
    string(recording.recording_id) + " ORDER BY channel_index");
available = double.empty(0, 1);
if ~isempty(rows) && height(rows) > 0
    available = double(rows.channel_index);
end

if ~isempty(options.ChannelIndex)
    index = double(options.ChannelIndex);
    source = "caller_supplied";
elseif isscalar(available)
    index = available(1);
    source = "only_channel";
elseif isempty(available) && recording.channel_count == 1
    index = 1;
    source = "only_channel";
else
    error("vawlume:eda:ExampleChannelAmbiguous", ...
        "Recording %d has %d channels, so the channel cannot be chosen " + ...
        "without a caller decision. Pass ChannelIndex. It is never chosen " + ...
        "by signal content: that would make the image depend on the signal " + ...
        "being illustrated.", recording.recording_id, numel(available));
end

label = "";
role = "";
matched = available == index;
if any(matched) && ~isempty(rows)
    label = edaPresentText(rows.channel_label(find(matched, 1)));
    role = edaPresentText(rows.channel_role(find(matched, 1)));
end

value = struct( ...
    channel_index=index, ...
    channel_label=label, ...
    channel_role=role, ...
    selection_source=source, ...
    available_channel_indices=available', ...
    selection_rule="explicit caller choice, or the recording's single " + ...
        "channel; never chosen by signal energy or any other property of " + ...
        "the content");
end

% --------------------------------------------------- the frequency bounds ---

function value = frequencyBounds(annotations, recording, options)
%FREQUENCYBOUNDS Derived from what was measured, or defaulted and said so.
%
% Derived bounds come from the MEASURED frequency values of the members - band
% edges where they exist, and the centre and peak markers otherwise, because a
% marker outside the axis is as useless as a rectangle outside it. When no member
% measured any frequency at all the bounds are a configured default, and
% `source` says `defaulted`: a frequency axis chosen by a constant looks exactly
% like one chosen by the data.
nyquist = Inf;
if isfinite(recording.sample_rate_hz) && recording.sample_rate_hz > 0
    nyquist = recording.sample_rate_hz / 2;
end

measured = [];
if height(annotations) > 0
    measured = [annotations.frequency_min_hz; annotations.frequency_max_hz; ...
        annotations.frequency_center_hz; annotations.frequency_peak_hz];
    measured = measured(isfinite(measured));
end

if isempty(measured)
    low = options.DefaultFrequencyLimitsHz(1);
    high = options.DefaultFrequencyLimitsHz(2);
    source = "defaulted";
    detail = "no member detection reported any frequency measurement, so " + ...
        "the axis comes from the configured default and not from the data";
else
    low = min(measured) - options.FrequencyMarginHz;
    high = max(measured) + options.FrequencyMarginHz;
    source = "derived";
    detail = "bounds are the measured frequency extremes of the members " + ...
        "widened by the configured margin";
end

low = max(low, options.FrequencyFloorHz);
high = min(high, nyquist);
clampedAtNyquist = isfinite(nyquist) && high >= nyquist - 1e-9;
if high <= low
    low = max(options.FrequencyFloorHz, 0);
    high = min(options.DefaultFrequencyLimitsHz(2), nyquist);
    detail = detail + "; the derived band collapsed and was replaced by the " + ...
        "default range";
    source = "defaulted";
end

value = struct( ...
    low_hz=low, ...
    high_hz=high, ...
    source=source, ...
    detail=detail, ...
    margin_hz=options.FrequencyMarginHz, ...
    floor_hz=options.FrequencyFloorHz, ...
    default_limits_hz=options.DefaultFrequencyLimitsHz, ...
    nyquist_hz=nyquist, ...
    is_clamped_at_nyquist=clampedAtNyquist, ...
    measured_value_count=numel(measured), ...
    contributing_extent_sources=sourcesOf(annotations));
end

function value = sourcesOf(annotations)
value = strings(1, 0);
if height(annotations) > 0
    value = unique(annotations.frequency_extent_source)';
end
end

% ------------------------------------------------------------ audio ---

function value = readAudio(conn, recording, channel, window, options)
%READAUDIO Through readAudioWindow, unchanged, with its errors left alone.
%
% `readAudioWindow` already raises for an invalid channel layout, a missing file,
% a URI source and inconsistent metadata, each with a specific identifier.
% Wrapping those in a vaguer exploration-level error would lose the diagnosis, so
% they are allowed through.
value = vawlume.acoustic.readAudioWindow(conn, ...
    struct(recording_id=recording.recording_id), channel.channel_index, ...
    window.actual_start_s, window.actual_end_s, ...
    SourceRoot=options.SourceRoot);
end

function value = computeSpectrogram(audio, bounds, window, channel, options)
if audio.sample_count == 0
    value = struct(status="no_samples", matrix=zeros(0, 0), ...
        time_s=zeros(1, 0), frequency_hz=zeros(0, 1), ...
        note="the audio window returned no samples, so no spectrogram was " + ...
        "computed; audio.qc_flags says why");
    return
end
value = vawlume.eda.spectrogramMatrix(audio.samples, audio.sample_rate_hz, ...
    WindowLengthSamples=options.SpectrogramWindowLengthSamples, ...
    HopSamples=options.SpectrogramHopSamples, ...
    FftLength=options.SpectrogramFftLength, ...
    Scaling=options.SpectrogramScaling, ...
    FrequencyLimitsHz=[bounds.low_hz, bounds.high_hz], ...
    PaddingPreS=window.padding_pre_s, ...
    PaddingPostS=window.padding_post_s, ...
    ChannelIndex=channel.channel_index);
end

% -------------------------------------------------------------- plumbing ---

function value = approximateExtentNote()
%APPROXIMATEEXTENTNOTE Conceptual spec §10.9, carried in the structure.
%
% Carried rather than left to documentation because the annotation will be drawn
% and the drawing will be looked at without the code. A rectangle looks like a
% segmentation; it is not one.
value = "An annotation rectangle is an APPROXIMATE EXTENT derived from the " + ...
    "extractor's reported summary values. It is not the extractor's native " + ...
    "segmentation contour or mask, and its edges should not be read as the " + ...
    "boundary the extractor's algorithm actually traced.";
end

function value = memberSetKey(members)
value = strjoin(sort(unique(members.extractor_key))', "|");
end

function value = exampleIdentity(example)
row = example;
if istable(row)
    if height(row) ~= 1
        error("vawlume:eda:ExampleNotScalar", ...
            "Pass exactly one example row; %d were supplied.", height(row));
    end
    row = table2struct(row);
end
if ~isstruct(row) || ~isfield(row, "agreement_group_id")
    error("vawlume:eda:ExampleInvalid", ...
        "An example must carry agreement_group_id. Pass one row of a " + ...
        "vawlume.eda.sampleExamples result.");
end
value = struct( ...
    example_id=fieldOr(row, "example_id", ""), ...
    agreement_group_id=double(row.agreement_group_id), ...
    reference=struct( ...
        profile_key=fieldOr(row, "reference_profile_key", ""), ...
        version_label=fieldOr(row, "reference_version_label", ""), ...
        checksum_sha256=fieldOr(row, "reference_checksum_sha256", "")));
end

function value = fieldOr(source, name, fallback)
value = string(fallback);
if isfield(source, name)
    value = string(source.(name));
end
end

function value = presentNumber(raw)
value = double(raw);
if value < 0
    value = NaN;
end
end
