function design = referenceDesign(reference, options)
%REFERENCEDESIGN A one-configuration design that IS the reference configuration.
%
% DESIGN = vawlume.eda.REFERENCEDESIGN(REFERENCE) returns a design struct shaped
% exactly like a vawlume.eda.screeningDesign result, holding one configuration
% and no screened factors, so the reference configuration can be applied through
% Part 7's runner like any other configuration:
%
%   reference = vawlume.eda.referenceConfiguration();
%   design    = vawlume.eda.referenceDesign(reference);
%   material  = vawlume.eda.materializeConfigurations(design, BaseSpecPath=...);
%   run       = vawlume.eda.runScreen(conn, dataset, material, Apply=true, ...
%                   ProbeRole="reference");
%
% NO FACTORS IS THE POINT. `materializeConfigurations` overrides exactly the
% factors a design names and copies every other field from the base
% specification, so a design that names none produces the base specification
% unchanged. That is what makes this the reference configuration rather than
% something resembling it - contract §J forbids silently reusing a probe
% configuration that merely looks like the reference, and the way to obey that is
% to derive the run from the reference file itself with no overrides at all.
%
% THE GENERATED SPECIFICATION'S `profile_version` GAINS THE CONFIGURATION ID, as
% every materialized configuration's does, so a stored analysis can be traced
% back without recomputing a checksum. The identity that appears in Part 11's
% outputs is the TRACKED FILE's - key, version and checksum from
% vawlume.eda.referenceConfiguration - not this derived label. The two are
% different on purpose: one says what was run, the other says what it was a copy
% of.
%
% THE CONFIGURATION ID IS DERIVED FROM THE REFERENCE CHECKSUM rather than from
% parameter values, because there are no varied parameter values to hash. Two
% runs of the same reference file therefore produce the same id and the runner
% reuses the analyses instead of duplicating them; a different reference file
% produces a different id and cannot be confused with the first.
%
% This function is pure. It opens no connection and writes no file.

arguments
    reference (1,1) struct
    options.ConfigurationId (1,1) string = ""
end

requireFields(reference, ["profile_key", "version_label", "checksum_sha256"]);
configurationId = resolveId(reference, options);

configurations = table(configurationId, ...
    string(reference.profile_key), string(reference.version_label), ...
    string(reference.checksum_sha256), ...
    VariableNames=["configuration_id", "reference_profile_key", ...
    "reference_version_label", "reference_checksum_sha256"]);

design = struct( ...
    status="constructed", ...
    design_type="reference_configuration", ...
    probe_role="reference", ...
    factor_count=0, ...
    fraction_exponent=0, ...
    configuration_count=1, ...
    full_factorial_size=1, ...
    factors=emptyFactors(), ...
    coding=zeros(1, 0), ...
    coding_convention="no factor is screened, so there is no coding", ...
    row_order="a single row", ...
    configurations=configurations, ...
    alias=referenceAlias(), ...
    generator_source="not applicable: no fraction is generated", ...
    decision_path="the reference configuration is applied as itself, with " + ...
        "no parameter overridden", ...
    budget=struct( ...
        warn_at_configurations=NaN, ...
        maximum_configurations=NaN, ...
        exceeded_maximum_by_opt_in=false, ...
        binds=false), ...
    analysis_cost_rule="1 configuration x recordings x (N(N-1)/2 matching " + ...
        "+ 1 agreement) analyses, for N extractors", ...
    probe_resolution=struct(status="not_applicable", ...
        factors=emptyProbeFactors(), ...
        note="no factor is screened at the reference configuration, so no " + ...
            "probe value was resolved"), ...
    randomization="none; nothing is varied and nothing is drawn", ...
    warnings=strings(0, 1), ...
    reference=reference, ...
    overrides_note="this design overrides NO parameter, so the generated " + ...
        "specification is the reference specification with only its " + ...
        "profile_version relabelled to carry the configuration id", ...
    caution=edaCautionNote());
end

% -------------------------------------------------------------- plumbing ---

function value = resolveId(reference, options)
if strlength(options.ConfigurationId) > 0
    value = options.ConfigurationId;
    return
end
checksum = string(reference.checksum_sha256);
if strlength(checksum) < 10
    error("vawlume:eda:ReferenceChecksumInvalid", ...
        "The reference configuration carries no usable checksum, so a " + ...
        "stable configuration id cannot be derived from it.");
end
value = "ref-" + extractBefore(checksum, 11);
end

function value = referenceAlias()
%REFERENCEALIAS A design of one point confounds nothing and estimates nothing.
%
% The fields are those Part 10's leverage categoriser reads, so a caller that
% hands this design to it gets an honest answer rather than a missing-field
% error: nothing is aliased, and with one configuration there is no contrast to
% estimate any effect from.
value = struct( ...
    generators=strings(1, 0), ...
    defining_relation="I", ...
    defining_relation_word_count=1, ...
    resolution=Inf, ...
    resolution_label="not applicable", ...
    alias_table=emptyAliasTable(), ...
    main_effects_clear_of_two_factor_interactions=true, ...
    two_factor_interactions_uniquely_attributable=true, ...
    note="A single configuration confounds nothing because it contrasts " + ...
        "nothing. No effect is estimable from this design, and none should " + ...
        "be reported from it.");
end

function value = emptyProbeFactors()
%EMPTYPROBEFACTORS The probeParameters factor shape, empty.
%
% Carried so a consumer that reads design.probe_resolution.factors finds a table
% of the expected width rather than a missing field. Nothing was resolved,
% because nothing was varied.
value = table(strings(0, 1), strings(0, 1), false(0, 1), strings(0, 1), ...
    zeros(0, 1), zeros(0, 1), strings(0, 1), false(0, 1), ...
    VariableNames=["factor_name", "metric_name", "is_active", ...
    "inactive_reason", "low_value", "high_value", "strictness_direction", ...
    "flagged_redundant"]);
end

function value = emptyFactors()
value = table(strings(0, 1), strings(0, 1), strings(0, 1), zeros(0, 1), ...
    zeros(0, 1), strings(0, 1), strings(0, 1), strings(0, 1), ...
    VariableNames=["design_letter", "factor_name", "metric_name", ...
    "low_value", "high_value", "strictness_direction", "unit", ...
    "value_source"]);
end

function value = emptyAliasTable()
value = table(strings(0, 1), strings(0, 1), zeros(0, 1), false(0, 1), ...
    VariableNames=["effect", "aliased_with", "effect_order", ...
    "is_uniquely_attributable"]);
end

function requireFields(value, names)
missingNames = names(~isfield(value, names));
if ~isempty(missingNames)
    error("vawlume:eda:ReferenceIdentityMissing", ...
        "The reference record is missing field(s): %s. Pass a " + ...
        "vawlume.eda.referenceConfiguration result.", ...
        strjoin(missingNames, ", "));
end
end
