function recording = acousticResolveRecording(conn, recordingRef)
%ACOUSTICRESOLVERECORDING Resolve exactly one established recording.

hasId = isfield(recordingRef, "recording_id");
hasPortable = isfield(recordingRef, "project_key") && ...
    isfield(recordingRef, "source_relative_path");
if hasId == hasPortable
    error("vawlume:acoustic:RecordingRefInvalid", ...
        "recordingRef must contain exactly one selector: recording_id, or " + ...
        "project_key plus source_relative_path.");
end

columns = "SELECT r.recording_id, r.project_id, p.project_key, " + ...
    "IFNULL(r.native_recording_id,'') AS native_recording_id, " + ...
    "IFNULL(sf.relative_path,'') AS source_relative_path " + ...
    "FROM recordings r JOIN projects p ON p.project_id=r.project_id " + ...
    "JOIN source_files sf ON sf.source_file_id=r.source_file_id WHERE ";
if hasId
    id = positiveInteger(recordingRef.recording_id, "recording_id");
    rows = fetch(conn, columns + "r.recording_id=" + string(id));
else
    projectKey = scalarText(recordingRef.project_key, "project_key");
    relativePath = scalarText(recordingRef.source_relative_path, ...
        "source_relative_path");
    rows = fetch(conn, columns + "p.project_key=" + acousticSqlText(projectKey) + ...
        " AND sf.relative_path=" + acousticSqlText(relativePath));
end

if isempty(rows) || height(rows) == 0
    error("vawlume:acoustic:RecordingNotFound", ...
        "No established recording matches recordingRef.");
end
if height(rows) ~= 1
    error("vawlume:acoustic:RecordingAmbiguous", ...
        "recordingRef matched %d recordings; exactly one is required.", ...
        height(rows));
end

recording = struct( ...
    recording_id=double(rows.recording_id(1)), ...
    project_id=double(rows.project_id(1)), ...
    project_key=acousticPresentText(rows.project_key(1)), ...
    native_recording_id=acousticPresentText(rows.native_recording_id(1)), ...
    source_relative_path=acousticPresentText(rows.source_relative_path(1)));
end

function value = positiveInteger(raw, label)
if ~isnumeric(raw) || ~isscalar(raw) || ~isfinite(raw) || raw <= 0 || ...
        raw ~= floor(raw)
    error("vawlume:acoustic:RecordingRefInvalid", ...
        "recordingRef.%s must be a positive integer.", label);
end
value = double(raw);
end

function value = scalarText(raw, label)
value = string(raw);
if ~isscalar(value) || ismissing(value) || strlength(value) == 0
    error("vawlume:acoustic:RecordingRefInvalid", ...
        "recordingRef.%s must be nonempty scalar text.", label);
end
end
