function result = alignmentPlanResult(plan)
%ALIGNMENTPLANRESULT Project internal planning state into the public read-back.
%
% The caller should never have to query raw surrogate IDs to understand what was
% registered, so logical keys and database identities are reported side by side.
% No fitted transform value appears anywhere, because none exists yet.

if plan.has_conflicts
    status = "conflict";
else
    status = "planned";
end

result = struct( ...
    status=status, ...
    committed=false, ...
    has_conflicts=plan.has_conflicts, ...
    conflicts=plan.conflicts, ...
    valid_for_ingest=plan.bundle.valid_for_ingest, ...
    manifest=manifestSummary(plan), ...
    project=plan.project, ...
    recording=plan.recording, ...
    analysis=plan.analysis, ...
    reference_timebase=referenceSummary(plan), ...
    timebases=timebaseTable(plan), ...
    streams=streamTable(plan), ...
    sources=sourceTable(plan), ...
    profiles=profileTable(plan), ...
    anchor_summary=anchorSummary(plan), ...
    observations_by_timebase=plan.anchors.observations_by_timebase, ...
    fit_ready_anchors=fitReadyTable(plan), ...
    transform_runs=transformTable(plan), ...
    issues=plan.bundle.issues, ...
    transforms_fitted=false, ...
    applied_counts=struct());
end

function value = manifestSummary(plan)
manifest = plan.bundle.manifest;
value = struct( ...
    alignment_key=manifest.alignment_key, ...
    manifest_schema_version=manifest.manifest_schema_version, ...
    manifest_version=manifest.manifest_version, ...
    content_uri=manifest.content_uri, ...
    checksum_sha256=manifest.checksum_sha256, ...
    declared_method=manifest.method, ...
    reference_timebase_key=manifest.reference_timebase_key);
end

function value = referenceSummary(plan)
index = find([plan.timebases.timebase_key] == ...
    plan.bundle.manifest.reference_timebase_key, 1);
value = struct( ...
    timebase_key=plan.timebases(index).timebase_key, ...
    timebase_id=plan.timebases(index).timebase_id, ...
    timebase_kind=plan.timebases(index).timebase_kind, ...
    action=plan.timebases(index).action);
end

function value = timebaseTable(plan)
value = table(strings(0, 1), strings(0, 1), false(0, 1), zeros(0, 1), ...
    zeros(0, 1), strings(0, 1), ...
    VariableNames=["timebase_key", "timebase_kind", "recording_native", ...
    "timebase_id", "nominal_rate_hz", "action"]);
for index = 1:numel(plan.timebases)
    row = plan.timebases(index);
    value(end + 1, :) = {row.timebase_key, row.timebase_kind, ...
        row.recording_native, row.timebase_id, row.nominal_rate_hz, ...
        row.action}; %#ok<AGROW>
end
end

function value = streamTable(plan)
value = table(strings(0, 1), strings(0, 1), zeros(0, 1), strings(0, 1), ...
    zeros(0, 1), zeros(0, 1), zeros(0, 1), strings(0, 1), ...
    VariableNames=["stream_key", "timebase_key", "external_stream_id", ...
    "stream_kind", "event_count", "attribute_count", "coverage_segment_count", ...
    "action"]);
for index = 1:numel(plan.streams)
    row = plan.streams(index);
    value(end + 1, :) = {row.stream_key, row.timebase_key, ...
        row.external_stream_id, row.stream_kind, row.event_count, ...
        row.attribute_count, row.coverage_count, row.action}; %#ok<AGROW>
end
end

function value = sourceTable(plan)
value = table(strings(0, 1), strings(0, 1), strings(0, 1), strings(0, 1), ...
    zeros(0, 1), strings(0, 1), ...
    VariableNames=["role", "relative_path", "file_role", "checksum", ...
    "source_file_id", "action"]);
for index = 1:numel(plan.sources)
    row = plan.sources(index);
    value(end + 1, :) = {row.role, row.relative_path, row.file_role, ...
        shortChecksum(row.checksum_sha256), row.source_file_id, row.action}; %#ok<AGROW>
end
end

function value = profileTable(plan)
value = table(strings(0, 1), strings(0, 1), strings(0, 1), strings(0, 1), ...
    zeros(0, 1), strings(0, 1), ...
    VariableNames=["profile_key", "profile_kind", "version_label", "checksum", ...
    "profile_version_id", "version_action"]);
for index = 1:numel(plan.profiles)
    row = plan.profiles(index);
    value(end + 1, :) = {row.profile_key, row.profile_kind, row.version_label, ...
        shortChecksum(row.checksum_sha256), row.profile_version_id, ...
        row.version_action}; %#ok<AGROW>
end
end

function value = anchorSummary(plan)
value = struct( ...
    declared=plan.anchors.declared, ...
    anchor_count=plan.anchors.anchor_count, ...
    observation_count=plan.anchors.observation_count);
end

function value = fitReadyTable(plan)
value = plan.anchors.fit_pairs;
end

function value = transformTable(plan)
value = table(strings(0, 1), strings(0, 1), strings(0, 1), zeros(0, 1), ...
    zeros(0, 1), strings(0, 1), ...
    VariableNames=["source_timebase_key", "reference_timebase_key", "method", ...
    "fit_eligible_anchor_count", "alignment_run_id", "status"]);
for index = 1:numel(plan.transform_runs)
    row = plan.transform_runs(index);
    value(end + 1, :) = {row.source_timebase_key, row.reference_timebase_key, ...
        row.method, row.fit_eligible_anchor_count, row.alignment_run_id, ...
        "registered"}; %#ok<AGROW>
end
end

function value = shortChecksum(checksum)
value = string(checksum);
if strlength(value) >= 12
    value = extractBefore(value, 13);
end
end
