function [plan, counts] = applyEntityPlan(conn, plan)
%APPLYENTITYPLAN Atomically apply the complete provenance-bearing intake.

if plan.has_conflicts
    error("vawlume:ingest:PlanConflict", ...
        "An intake plan with conflicts cannot be applied.");
end
oldAutoCommit = string(conn.AutoCommit);
if oldAutoCommit ~= "on"
    error("vawlume:ingest:TransactionState", ...
        "Project graph apply requires a connection with AutoCommit enabled.");
end

counts = emptyCounts();
conn.AutoCommit = "off";
try
    [plan, counts] = applyMappingProfile(conn, plan, counts);
    [plan, counts] = applyLinkedProfiles(conn, plan, counts);
    [plan, counts] = applyProject(conn, plan, counts);
    [plan, counts] = applyProjectProfileAssignments(conn, plan, counts);
    [plan, counts] = applyIngestionRun(conn, plan, counts);
    [plan, counts] = applySources(conn, plan, counts);
    [plan, counts] = applyIngestionFiles(conn, plan, counts);
    [plan, counts] = applyEntityTypes(conn, plan, counts);
    [plan, counts] = applyEntities(conn, plan, counts);
    [plan, counts] = applyRelationships(conn, plan, counts);
    [plan, counts] = applyRecordings(conn, plan, counts);
    [plan, counts] = applyRecordingLinks(conn, plan, counts);
    [plan, counts] = applyRecordingProfileAssignments(conn, plan, counts);
    commit(conn);
catch exception
    try
        rollback(conn);
    catch
    end
    conn.AutoCommit = oldAutoCommit;
    rethrow(exception);
end
conn.AutoCommit = oldAutoCommit;
end

function [plan, counts] = applyMappingProfile(conn, plan, counts)
profile = plan.mapping_profile;
if profile.profile_action == "create"
    profileId = insertIntakeRow(conn, "config_profiles", struct( ...
        profile_key=profile.profile_key, ...
        profile_name=profile.profile_name, ...
        profile_kind=profile.profile_kind, ...
        is_builtin=profile.is_builtin), "profile_id");
    counts.config_profiles = counts.config_profiles + 1;
elseif profile.profile_action == "reuse"
    profileId = profile.existing_profile_id;
    counts.reused_config_profiles = counts.reused_config_profiles + 1;
else
    error("vawlume:ingest:PlanConflict", ...
        "Mapping-profile action '%s' cannot be applied.", ...
        profile.profile_action);
end
plan.mapping_profile.existing_profile_id = profileId;

if profile.version_action == "create"
    versionId = insertIntakeRow(conn, "config_profile_versions", struct( ...
        profile_id=profileId, ...
        version_label=profile.version_label, ...
        profile_schema_version=profile.profile_schema_version, ...
        content_format=profile.content_format, ...
        content_uri=profile.content_uri, ...
        checksum_sha256=profile.checksum_sha256, ...
        is_snapshot=true), "profile_version_id");
    counts.config_profile_versions = counts.config_profile_versions + 1;
elseif profile.version_action == "reuse"
    versionId = profile.existing_profile_version_id;
    counts.reused_config_profile_versions = ...
        counts.reused_config_profile_versions + 1;
else
    error("vawlume:ingest:PlanConflict", ...
        "Mapping-profile-version action '%s' cannot be applied.", ...
        profile.version_action);
end
plan.mapping_profile.existing_profile_version_id = versionId;
plan = propagateProfileVersionId(plan, profile.profile_key, versionId);
plan.ingestion_run.mapping_profile_version_id = versionId;
end

function [plan, counts] = applyLinkedProfiles(conn, plan, counts)
for index = 1:height(plan.profile_linkage.profiles)
    action = plan.profile_linkage.profiles.profile_action(index);
    if action == "create"
        profileId = insertIntakeRow(conn, "config_profiles", struct( ...
            profile_key=plan.profile_linkage.profiles.profile_key(index), ...
            profile_name=plan.profile_linkage.profiles.profile_name(index), ...
            profile_kind=plan.profile_linkage.profiles.profile_kind(index), ...
            is_builtin=true), "profile_id");
        counts.config_profiles = counts.config_profiles + 1;
    elseif action == "reuse"
        profileId = plan.profile_linkage.profiles.existing_profile_id(index);
        counts.reused_config_profiles = counts.reused_config_profiles + 1;
    else
        error("vawlume:ingest:PlanConflict", ...
            "Linked-profile action '%s' cannot be applied.", action);
    end
    plan.profile_linkage.profiles.existing_profile_id(index) = profileId;

    versionAction = plan.profile_linkage.profiles.version_action(index);
    if versionAction == "create"
        versionId = insertIntakeRow(conn, "config_profile_versions", struct( ...
            profile_id=profileId, ...
            version_label= ...
            plan.profile_linkage.profiles.version_label(index), ...
            profile_schema_version= ...
            plan.profile_linkage.profiles.profile_schema_version(index), ...
            content_format= ...
            plan.profile_linkage.profiles.content_format(index), ...
            content_uri=plan.profile_linkage.profiles.content_uri(index), ...
            checksum_sha256= ...
            plan.profile_linkage.profiles.checksum_sha256(index), ...
            is_snapshot=true), "profile_version_id");
        counts.config_profile_versions = counts.config_profile_versions + 1;
    elseif versionAction == "reuse"
        versionId = ...
            plan.profile_linkage.profiles.existing_profile_version_id(index);
        counts.reused_config_profile_versions = ...
            counts.reused_config_profile_versions + 1;
    else
        error("vawlume:ingest:PlanConflict", ...
            "Linked-profile-version action '%s' cannot be applied.", ...
            versionAction);
    end
    plan.profile_linkage.profiles.existing_profile_version_id(index) = ...
        versionId;
    plan = propagateProfileVersionId( ...
        plan, plan.profile_linkage.profiles.profile_key(index), versionId);
end
end

function plan = propagateProfileVersionId(plan, profileKey, versionId)
projectMatches = plan.project_profile_assignments.profile_key == profileKey;
plan.project_profile_assignments.profile_version_id(projectMatches) = versionId;
recordingMatches = ...
    plan.recording_profile_assignments.profile_key == profileKey;
plan.recording_profile_assignments.profile_version_id(recordingMatches) = ...
    versionId;
end

function [plan, counts] = applyProject(conn, plan, counts)
if plan.project.action == "create"
    projectId = insertIntakeRow(conn, "projects", struct( ...
        project_key=plan.project.project_key, ...
        project_name=plan.project.project_name, ...
        description=plan.project.description), "project_id");
    counts.projects = 1;
elseif plan.project.action == "reuse"
    projectId = plan.project.existing_project_id;
    counts.reused_projects = 1;
else
    error("vawlume:ingest:PlanConflict", ...
        "Project action '%s' cannot be applied.", plan.project.action);
end
plan.project.existing_project_id = projectId;
plan.sources.project_id(:) = projectId;
plan.entity_types.project_id(:) = projectId;
plan.entities.project_id(:) = projectId;
plan.relationships.project_id(:) = projectId;
plan.recordings.project_id(:) = projectId;
plan.recording_links.project_id(:) = projectId;
plan.project_profile_assignments.project_id(:) = projectId;
plan.recording_profile_assignments.project_id(:) = projectId;
plan.ingestion_run.project_id = projectId;
end

function [plan, counts] = applyProjectProfileAssignments(conn, plan, counts)
for index = 1:height(plan.project_profile_assignments)
    action = plan.project_profile_assignments.action(index);
    if action == "create"
        insertIntakeRow(conn, "project_profile_assignments", struct( ...
            project_id=plan.project.existing_project_id, ...
            profile_version_id= ...
            plan.project_profile_assignments.profile_version_id(index), ...
            assignment_role= ...
            plan.project_profile_assignments.assignment_role(index), ...
            is_default= ...
            plan.project_profile_assignments.is_default(index)));
        counts.project_profile_assignments = ...
            counts.project_profile_assignments + 1;
    elseif action == "reuse"
        counts.reused_project_profile_assignments = ...
            counts.reused_project_profile_assignments + 1;
    else
        error("vawlume:ingest:PlanConflict", ...
            "Project-profile-assignment action '%s' cannot be applied.", ...
            action);
    end
end
end

function [plan, counts] = applyIngestionRun(conn, plan, counts)
if plan.ingestion_run.action ~= "create"
    error("vawlume:ingest:PlanConflict", ...
        "Ingestion-run action '%s' cannot be applied.", ...
        plan.ingestion_run.action);
end
runId = insertIntakeRow(conn, "ingestion_runs", struct( ...
    project_id=plan.project.existing_project_id, ...
    mapping_profile_version_id= ...
    plan.mapping_profile.existing_profile_version_id, ...
    run_label=plan.ingestion_run.run_label, ...
    vawlume_version=plan.ingestion_run.vawlume_version, ...
    source_commit=plan.ingestion_run.source_commit, ...
    status=plan.ingestion_run.status, ...
    completed_at_utc=utcNowText(), ...
    notes=plan.ingestion_run.notes), "ingestion_run_id");
plan.ingestion_run.existing_ingestion_run_id = runId;
plan.ingestion_files.ingestion_run_id(:) = runId;
counts.ingestion_runs = counts.ingestion_runs + 1;
end

function [plan, counts] = applySources(conn, plan, counts)
for index = 1:height(plan.sources)
    action = plan.sources.action(index);
    if action == "create"
        id = insertIntakeRow(conn, "source_files", struct( ...
            project_id=plan.project.existing_project_id, ...
            file_role=plan.sources.file_role(index), ...
            path_or_uri=plan.sources.path_or_uri(index), ...
            relative_path=plan.sources.relative_path(index), ...
            filename=plan.sources.filename(index), ...
            file_format=plan.sources.file_format(index), ...
            checksum_sha256=plan.sources.checksum_sha256(index)), ...
            "source_file_id");
        counts.source_files = counts.source_files + 1;
    elseif action == "reuse"
        id = plan.sources.existing_source_file_id(index);
        counts.reused_source_files = counts.reused_source_files + 1;
    else
        error("vawlume:ingest:PlanConflict", ...
            "Source action '%s' cannot be applied.", action);
    end
    plan.sources.existing_source_file_id(index) = id;
    recordingMatches = plan.recordings.source_key == ...
        plan.sources.source_key(index);
    plan.recordings.source_file_id(recordingMatches) = id;
    ingestionMatches = plan.ingestion_files.source_key == ...
        plan.sources.source_key(index);
    plan.ingestion_files.source_file_id(ingestionMatches) = id;
end
end

function [plan, counts] = applyIngestionFiles(conn, plan, counts)
for index = 1:height(plan.ingestion_files)
    action = plan.ingestion_files.action(index);
    if action ~= "create"
        error("vawlume:ingest:PlanConflict", ...
            "Ingestion-file action '%s' cannot be applied.", action);
    end
    insertIntakeRow(conn, "ingestion_files", struct( ...
        ingestion_run_id= ...
        plan.ingestion_run.existing_ingestion_run_id, ...
        source_file_id=plan.ingestion_files.source_file_id(index), ...
        parse_status=plan.ingestion_files.parse_status(index), ...
        warning_count=plan.ingestion_files.warning_count(index), ...
        error_count=plan.ingestion_files.error_count(index), ...
        parser_message=plan.ingestion_files.parser_message(index)));
    counts.ingestion_files = counts.ingestion_files + 1;
end
end

function [plan, counts] = applyEntityTypes(conn, plan, counts)
for index = 1:height(plan.entity_types)
    action = plan.entity_types.action(index);
    if action == "create"
        id = insertIntakeRow(conn, "entity_types", struct( ...
            project_id=plan.project.existing_project_id, ...
            native_name=plan.entity_types.native_name(index), ...
            canonical_role=plan.entity_types.canonical_role(index), ...
            is_biological_unit=false, ...
            is_subject_like=false), "entity_type_id");
        counts.entity_types = counts.entity_types + 1;
    elseif action == "reuse"
        id = plan.entity_types.existing_entity_type_id(index);
        counts.reused_entity_types = counts.reused_entity_types + 1;
    else
        error("vawlume:ingest:PlanConflict", ...
            "Entity-type action '%s' cannot be applied.", action);
    end
    plan.entity_types.existing_entity_type_id(index) = id;
    matches = plan.entities.entity_type_key == ...
        plan.entity_types.entity_type_key(index);
    plan.entities.entity_type_id(matches) = id;
end
end

function [plan, counts] = applyEntities(conn, plan, counts)
for index = 1:height(plan.entities)
    action = plan.entities.action(index);
    if action == "create"
        id = insertIntakeRow(conn, "experimental_entities", struct( ...
            project_id=plan.project.existing_project_id, ...
            entity_type_id=plan.entities.entity_type_id(index), ...
            native_id=plan.entities.native_id(index), ...
            ingestion_run_id= ...
            plan.ingestion_run.existing_ingestion_run_id), "entity_id");
        counts.entities = counts.entities + 1;
    elseif action == "reuse"
        id = plan.entities.existing_entity_id(index);
        counts.reused_entities = counts.reused_entities + 1;
    else
        error("vawlume:ingest:PlanConflict", ...
            "Entity action '%s' cannot be applied.", action);
    end
    plan.entities.existing_entity_id(index) = id;
    matches = plan.entity_records.entity_key == plan.entities.entity_key(index);
    plan.entity_records.existing_entity_id(matches) = id;
    parentMatches = plan.relationships.parent_entity_key == ...
        plan.entities.entity_key(index);
    childMatches = plan.relationships.child_entity_key == ...
        plan.entities.entity_key(index);
    plan.relationships.parent_entity_id(parentMatches) = id;
    plan.relationships.child_entity_id(childMatches) = id;
    linkMatches = plan.recording_links.entity_key == ...
        plan.entities.entity_key(index);
    plan.recording_links.entity_id(linkMatches) = id;
end
end

function [plan, counts] = applyRelationships(conn, plan, counts)
for index = 1:height(plan.relationships)
    action = plan.relationships.action(index);
    if action == "create"
        values = struct( ...
            project_id=plan.project.existing_project_id, ...
            parent_entity_id=plan.relationships.parent_entity_id(index), ...
            child_entity_id=plan.relationships.child_entity_id(index), ...
            relationship_type=plan.relationships.relationship_type(index), ...
            role_label=plan.relationships.role_label(index), ...
            ingestion_run_id= ...
            plan.ingestion_run.existing_ingestion_run_id, ...
            source_locator=plan.relationships.source_locator(index), ...
            mapping_rule_key=plan.relationships.mapping_rule_key(index));
        sourceId = relationshipSourceId(plan, index);
        if ~isnan(sourceId)
            values.source_file_id = sourceId;
        end
        id = insertIntakeRow(conn, "entity_relationships", values, ...
            "entity_relationship_id");
        counts.entity_relationships = counts.entity_relationships + 1;
    elseif action == "reuse"
        id = plan.relationships.existing_entity_relationship_id(index);
        counts.reused_entity_relationships = ...
            counts.reused_entity_relationships + 1;
    else
        error("vawlume:ingest:PlanConflict", ...
            "Entity-relationship action '%s' cannot be applied.", action);
    end
    plan.relationships.existing_entity_relationship_id(index) = id;
end
end

function [plan, counts] = applyRecordings(conn, plan, counts)
for index = 1:height(plan.recordings)
    action = plan.recordings.action(index);
    if action == "create"
        id = insertIntakeRow(conn, "recordings", struct( ...
            project_id=plan.project.existing_project_id, ...
            source_file_id=plan.recordings.source_file_id(index), ...
            native_recording_id=plan.recordings.native_recording_id(index), ...
            checksum_sha256=plan.recordings.checksum_sha256(index)), ...
            "recording_id");
        counts.recordings = counts.recordings + 1;
    elseif action == "reuse"
        id = plan.recordings.existing_recording_id(index);
        counts.reused_recordings = counts.reused_recordings + 1;
    else
        error("vawlume:ingest:PlanConflict", ...
            "Recording action '%s' cannot be applied.", action);
    end
    plan.recordings.existing_recording_id(index) = id;
    matches = plan.recording_links.recording_key == ...
        plan.recordings.record_key(index);
    plan.recording_links.recording_id(matches) = id;
    assignmentMatches = plan.recording_profile_assignments.recording_key == ...
        plan.recordings.record_key(index);
    plan.recording_profile_assignments.recording_id(assignmentMatches) = id;
end
end

function [plan, counts] = applyRecordingLinks(conn, plan, counts)
for index = 1:height(plan.recording_links)
    action = plan.recording_links.action(index);
    if action == "create"
        id = insertIntakeRow(conn, "recording_entity_links", struct( ...
            recording_id=plan.recording_links.recording_id(index), ...
            entity_id=plan.recording_links.entity_id(index), ...
            link_type=plan.recording_links.link_type(index), ...
            role_label=plan.recording_links.role_label(index), ...
            ingestion_run_id= ...
            plan.ingestion_run.existing_ingestion_run_id), ...
            "recording_entity_link_id");
        counts.recording_entity_links = counts.recording_entity_links + 1;
    elseif action == "reuse"
        id = plan.recording_links.existing_recording_entity_link_id(index);
        counts.reused_recording_entity_links = ...
            counts.reused_recording_entity_links + 1;
    else
        error("vawlume:ingest:PlanConflict", ...
            "Recording-link action '%s' cannot be applied.", action);
    end
    plan.recording_links.existing_recording_entity_link_id(index) = id;
end
end

function [plan, counts] = applyRecordingProfileAssignments(conn, plan, counts)
for index = 1:height(plan.recording_profile_assignments)
    action = plan.recording_profile_assignments.action(index);
    if action == "create"
        insertIntakeRow(conn, "recording_profile_assignments", struct( ...
            recording_id= ...
            plan.recording_profile_assignments.recording_id(index), ...
            profile_version_id= ...
            plan.recording_profile_assignments.profile_version_id(index), ...
            assignment_role= ...
            plan.recording_profile_assignments.assignment_role(index), ...
            inheritance_source= ...
            plan.recording_profile_assignments.inheritance_source(index)));
        counts.recording_profile_assignments = ...
            counts.recording_profile_assignments + 1;
    elseif action == "reuse"
        counts.reused_recording_profile_assignments = ...
            counts.reused_recording_profile_assignments + 1;
    else
        error("vawlume:ingest:PlanConflict", ...
            "Recording-profile-assignment action '%s' cannot be applied.", ...
            action);
    end
end
end

function sourceId = relationshipSourceId(plan, relationshipIndex)
sourceId = NaN;
sourceKey = plan.relationships.source_locator(relationshipIndex);
if strlength(sourceKey) == 0
    return
end
sourceIndex = find(plan.sources.source_key == sourceKey, 1);
if ~isempty(sourceIndex)
    sourceId = plan.sources.existing_source_file_id(sourceIndex);
end
end

function value = emptyCounts()
value = struct( ...
    projects=0, config_profiles=0, config_profile_versions=0, ...
    project_profile_assignments=0, ingestion_runs=0, ingestion_files=0, ...
    source_files=0, entity_types=0, entities=0, entity_relationships=0, ...
    recordings=0, recording_entity_links=0, ...
    recording_profile_assignments=0, reused_projects=0, ...
    reused_config_profiles=0, reused_config_profile_versions=0, ...
    reused_project_profile_assignments=0, reused_source_files=0, ...
    reused_entity_types=0, reused_entities=0, ...
    reused_entity_relationships=0, reused_recordings=0, ...
    reused_recording_entity_links=0, ...
    reused_recording_profile_assignments=0);
end

function value = utcNowText()
value = string(datetime("now", "TimeZone", "UTC", ...
    "Format", "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'"));
end
