function [sourceFileId, created] = attributionIntakeRegisterSourceFile(conn, projectId, source, fileRole)
%ATTRIBUTIONINTAKEREGISTERSOURCEFILE Reuse or register the source_files row for an intake.
%
% Reused by project and portable path; otherwise inserted with its checksum.
% Called inside the caller's open transaction and opens none of its own.
created = false;
existing = fetch(conn, "SELECT source_file_id FROM source_files " + ...
    "WHERE project_id=" + string(projectId) + ...
    " AND path_or_uri=" + sqlText(source.relative_path));
if ~isempty(existing) && height(existing) > 0
    sourceFileId = double(existing.source_file_id(1));
    return
end
sourceFileId = attributionImportInsertRow(conn, "source_files", struct( ...
    project_id=projectId, ...
    file_role=fileRole, ...
    path_or_uri=source.relative_path, ...
    relative_path=source.relative_path, ...
    filename=source.filename, ...
    file_format="delimited_text", ...
    checksum_sha256=source.checksum_sha256), "source_file_id");
created = true;
end

function value = sqlText(text)
value = "'" + replace(string(text), "'", "''") + "'";
end
