function [versionId, createdProfile, createdVersion] = attributionIntakeRegisterProfile(conn, projectId, profile, profileKind)
%ATTRIBUTIONINTAKEREGISTERPROFILE Reuse or register the mapping-profile version an intake used.
%
% An identical version is reused. The same version_label over a different
% checksum is refused rather than rewritten: windows already cite that version by
% ID, and changing what it denotes underneath them would silently re-point
% evidence. Called inside the caller's open transaction and opens none of its own.
createdProfile = false;
createdVersion = false;
existing = fetch(conn, "SELECT p.profile_id AS profile_id, " + ...
    "IFNULL(v.profile_version_id,-1) AS version_id, " + ...
    "IFNULL(v.checksum_sha256,'') AS checksum " + ...
    "FROM config_profiles p LEFT JOIN config_profile_versions v " + ...
    "  ON v.profile_id = p.profile_id AND v.version_label=" + ...
    sqlText(profile.version_label) + ...
    " WHERE p.profile_key=" + sqlText(profile.profile_key));
if ~isempty(existing) && height(existing) > 0
    profileId = double(existing.profile_id(1));
    versionId = double(existing.version_id(1));
    if versionId > 0
        stored = string(existing.checksum(1));
        if stored ~= "" && stored ~= profile.checksum_sha256
            error("vawlume:attribution:ProfileVersionConflict", ...
                "Mapping profile %s version %s is registered with a different " + ...
                "checksum. Publish a new profile_version rather than editing one.", ...
                profile.profile_key, profile.version_label);
        end
        return
    end
else
    profileId = attributionImportInsertRow(conn, "config_profiles", struct( ...
        project_id=projectId, ...
        profile_key=profile.profile_key, ...
        profile_name=profile.profile_name, ...
        profile_kind=profileKind), "profile_id");
    createdProfile = true;
end
versionId = attributionImportInsertRow(conn, "config_profile_versions", struct( ...
    profile_id=profileId, ...
    version_label=profile.version_label, ...
    profile_schema_version=profile.profile_schema_version, ...
    content_format="json", ...
    content_uri=profile.content_uri, ...
    checksum_sha256=profile.checksum_sha256, ...
    is_snapshot=1), "profile_version_id");
createdVersion = true;
end

function value = sqlText(text)
value = "'" + replace(string(text), "'", "''") + "'";
end
