function run = attributionImportResolveRun(conn, runRef)
%ATTRIBUTIONIMPORTRESOLVERUN Read one attribution run for the import path.
%
% A deliberate, narrow duplicate. `attributionResolveRun` lives in
% `+attribution/private/` and MATLAB makes a private function visible only to its
% own package, so the ingest package cannot call it. This reads the same rows and
% applies no rule of its own: every judgement about whether a run may be imported
% into lives in attributionImportBuildPlan, not here.
%
% The duplication is recorded as a finding rather than hidden. The fix is to move
% the shared reader to a `+vawlume/+internal/` subpackage, as Phase 3 did with
% the alignment segment primitives, and that is a refactor with its own blast
% radius rather than something to do inside an import itinerary.

hasId = isfield(runRef, "attribution_run_id");
hasPortable = isfield(runRef, "project_key") && isfield(runRef, "run_key");
if hasId == hasPortable
    error("vawlume:attribution:RunRefInvalid", ...
        "runRef must contain attribution_run_id, or project_key and run_key.");
end

if hasId
    predicate = "r.attribution_run_id=" + string(double(runRef.attribution_run_id));
else
    predicate = "p.project_key=" + sqlText(runRef.project_key) + ...
        " AND r.run_key=" + sqlText(runRef.run_key);
end

rows = fetch(conn, "SELECT r.attribution_run_id, r.analysis_run_id, " + ...
    "r.recording_id, p.project_id, p.project_key, r.run_key, " + ...
    "r.attribution_path, r.method, r.status, a.status AS analysis_status, " + ...
    "IFNULL(r.notes,'') AS notes " + ...
    "FROM attribution_runs r " + ...
    "JOIN analysis_runs a ON a.analysis_run_id = r.analysis_run_id " + ...
    "JOIN projects p ON p.project_id = a.project_id " + ...
    "WHERE " + predicate);
if isempty(rows) || height(rows) == 0
    error("vawlume:attribution:RunNotFound", ...
        "No attribution run matches the supplied reference.");
end

run = struct( ...
    attribution_run_id=double(rows.attribution_run_id(1)), ...
    analysis_run_id=double(rows.analysis_run_id(1)), ...
    recording_id=double(rows.recording_id(1)), ...
    project_id=double(rows.project_id(1)), ...
    project_key=string(rows.project_key(1)), ...
    run_key=string(rows.run_key(1)), ...
    attribution_path=string(rows.attribution_path(1)), ...
    method=string(rows.method(1)), ...
    status=string(rows.status(1)), ...
    analysis_status=string(rows.analysis_status(1)));

% The participant set is the run's own snapshot, not the recording's current
% links: a candidate universe that moved when links changed would make an old
% import unreadable.
participants = fetch(conn, "SELECT entity_id FROM recording_entity_links " + ...
    "WHERE recording_id=" + string(run.recording_id) + " ORDER BY entity_id");
run.participating_entity_ids = double(participants.entity_id)';
snapshot = fetch(conn, "SELECT IFNULL(notes,'') AS notes FROM attribution_runs " + ...
    "WHERE attribution_run_id=" + string(run.attribution_run_id));
run.notes = string(snapshot.notes(1));
end

function value = sqlText(text)
value = "'" + replace(string(text), "'", "''") + "'";
end
