function [plan, counts] = attributionBackendApplyPlan(conn, plan)
%ATTRIBUTIONBACKENDAPPLYPLAN Persist one localization-backend export atomically.
%
% One transaction covers the source file, the mapping-profile version, the
% windows, the claims, the localization estimates, the preserved native fields
% and the declared inputs. A failure anywhere rolls all of it back.
%
% Transaction shape, as the imported path: sqlwrite OPENS a transaction when
% AutoCommit is off; execute and sqlupdate JOIN one already open.
%
% NO CANDIDATE, EVIDENCE OR CORRESPONDENCE ROW IS WRITTEN HERE. A claim belongs
% to (window, entity) and an estimate to a window; promoting either onto a
% VAWLUME target is an explicit, later act, because deciding which window refers
% to which event is correspondence and has not happened.

counts = struct(source_files=0, config_profiles=0, config_profile_versions=0, ...
    imported_attribution_windows=0, imported_attribution_claims=0, ...
    attribution_localization_estimates=0, attribution_native_attributes=0, ...
    attribution_run_declared_inputs=0);

previousAutoCommit = conn.AutoCommit;
conn.AutoCommit = "off";
restore = onCleanup(@() restoreAutoCommit(conn, previousAutoCommit));

try
    [sourceFileId, created] = attributionIntakeRegisterSourceFile(conn, ...
        plan.run.project_id, plan.source, "backend_attribution_output");
    counts.source_files = double(created);
    [profileVersionId, createdProfile, createdVersion] = attributionIntakeRegisterProfile( ...
        conn, plan.run.project_id, plan.profile, "attribution_backend_mapping");
    counts.config_profiles = double(createdProfile);
    counts.config_profile_versions = double(createdVersion);
    plan.source_file_id = sourceFileId;
    plan.profile_version_id = profileVersionId;

    windowIds = containers.Map("KeyType", "char", "ValueType", "double");
    for index = 1:height(plan.windows)
        row = plan.windows(index, :);
        windowIds(char(row.window_key)) = attributionImportInsertRow(conn, ...
            "imported_attribution_windows", struct( ...
            attribution_run_id=plan.run.attribution_run_id, ...
            recording_id=plan.run.recording_id, ...
            native_window_id=string(row.native_window_id), ...
            start_time_native=double(row.start_time_native), ...
            end_time_native=double(row.end_time_native), ...
            source_file_id=sourceFileId, ...
            mapping_profile_version_id=profileVersionId, ...
            source_locator=string(row.source_locator)), ...
            "imported_attribution_window_id");
        counts.imported_attribution_windows = counts.imported_attribution_windows + 1;
    end

    claimIds = containers.Map("KeyType", "char", "ValueType", "double");
    ordinals = containers.Map("KeyType", "char", "ValueType", "double");
    for index = 1:height(plan.claims)
        claim = plan.claims(index, :);
        windowKey = char(claim.window_key);
        if isKey(ordinals, windowKey)
            ordinals(windowKey) = ordinals(windowKey) + 1;
        else
            ordinals(windowKey) = 1;
        end
        % NaN numbers and empty semantics are dropped by the insert helper, so a
        % scoreless claim stores SQL NULL rather than a substitute.
        claimIds(char(claim.claim_key)) = attributionImportInsertRow(conn, ...
            "imported_attribution_claims", struct( ...
            imported_attribution_window_id=windowIds(windowKey), ...
            claim_ordinal=ordinals(windowKey), ...
            source_caller_label=string(claim.caller_label), ...
            entity_id=double(claim.entity_id), ...
            score=double(claim.score), ...
            score_semantics=string(claim.score_semantics), ...
            probability=double(claim.probability), ...
            probability_semantics=string(claim.probability_semantics), ...
            source_locator=string(claim.source_locator)), ...
            "imported_attribution_claim_id");
        counts.imported_attribution_claims = counts.imported_attribution_claims + 1;
    end

    estimateIds = containers.Map("KeyType", "char", "ValueType", "double");
    for index = 1:height(plan.estimates)
        estimate = plan.estimates(index, :);
        claimId = NaN;
        if strlength(estimate.claim_key) > 0
            claimId = claimIds(char(estimate.claim_key));
        end
        % position_z and confidence are NaN when the backend reported none; the
        % insert helper drops them, so they are stored as NULL, never 0.
        estimateIds(char(estimate.estimate_key)) = attributionImportInsertRow(conn, ...
            "attribution_localization_estimates", struct( ...
            imported_attribution_window_id=windowIds(char(estimate.window_key)), ...
            imported_attribution_claim_id=claimId, ...
            estimate_ordinal=double(estimate.estimate_ordinal), ...
            native_estimate_id=string(estimate.native_estimate_id), ...
            coordinate_system_id=double(estimate.coordinate_system_id), ...
            position_x=double(estimate.position_x), ...
            position_y=double(estimate.position_y), ...
            position_z=double(estimate.position_z), ...
            position_semantics=string(estimate.position_semantics), ...
            confidence=double(estimate.confidence), ...
            confidence_semantics=string(estimate.confidence_semantics), ...
            source_file_id=sourceFileId, ...
            mapping_profile_version_id=profileVersionId, ...
            source_locator=string(estimate.source_locator)), ...
            "attribution_localization_estimate_id");
        counts.attribution_localization_estimates = ...
            counts.attribution_localization_estimates + 1;
    end

    for index = 1:height(plan.native_attributes)
        attribute = plan.native_attributes(index, :);
        owner = struct();
        switch attribute.owner_kind
            case "window"
                owner.imported_attribution_window_id = windowIds(char(attribute.owner_key));
            case "claim"
                owner.imported_attribution_claim_id = claimIds(char(attribute.owner_key));
            otherwise
                owner.attribution_localization_estimate_id = ...
                    estimateIds(char(attribute.owner_key));
        end
        values = struct( ...
            attribute_name=string(attribute.attribute_name), ...
            native_field_name=string(attribute.native_field_name), ...
            value_type=string(attribute.value_type), ...
            value_text=string(attribute.value_text), ...
            value_real=double(attribute.value_real), ...
            value_integer=double(attribute.value_integer), ...
            value_boolean=double(attribute.value_boolean), ...
            native_raw_token=string(attribute.native_raw_token), ...
            unit=string(attribute.unit), ...
            source_locator=string(attribute.source_locator), ...
            mapping_rule_key=string(attribute.mapping_rule_key));
        ownerField = string(fieldnames(owner));
        values.(ownerField) = owner.(ownerField);
        attributionImportInsertRow(conn, "attribution_native_attributes", values, "");
        counts.attribution_native_attributes = counts.attribution_native_attributes + 1;
    end

    for index = 1:height(plan.declared_inputs)
        declaration = plan.declared_inputs(index, :);
        attributionImportInsertRow(conn, "attribution_run_declared_inputs", struct( ...
            attribution_run_id=plan.run.attribution_run_id, ...
            input_dimension=string(declaration.input_dimension), ...
            declaration=string(declaration.declaration), ...
            declared_by_profile_version_id=profileVersionId), "");
        counts.attribution_run_declared_inputs = counts.attribution_run_declared_inputs + 1;
    end

    commit(conn);
catch exception
    try
        rollback(conn);
    catch
    end
    rethrow(exception);
end
clear restore

plan.window_ids = windowIds;
plan.claim_ids = claimIds;
plan.estimate_ids = estimateIds;
end

function restoreAutoCommit(conn, previous)
try
    conn.AutoCommit = previous;
catch
end
end
