function result = deepsqueakPlanResult(plan)
%DEEPSQUEAKPLANRESULT Build the inspectable DeepSqueak import manifest.
%
% Every disposition is readable from the returned value, so a caller can tell
% what will be created, reused, or refused without reading console output.

arguments
    plan (1,1) struct
end

result = struct();
if plan.has_conflicts
    result.status = "conflict";
else
    result.status = "planned";
end
result.committed = false;

result.recording = struct( ...
    recording_id=plan.recording.recording_id, ...
    project_id=plan.recording.project_id, ...
    project_key=plan.recording.project_key, ...
    source_file_id=plan.recording.source_file_id, ...
    source_relative_path=plan.recording.source_relative_path, ...
    resolution_mode=plan.recording.resolution_mode);

result.extractor = struct( ...
    extractor_id=plan.extractor.extractor_id, ...
    extractor_name=plan.extractor.extractor_name, ...
    declared_version=plan.extractor.run_version_label, ...
    run_extractor_version_id=plan.extractor.run_version_id, ...
    feature_extractor_version_id=plan.extractor.feature_version_id, ...
    feature_scope_version_label=plan.extractor.scope_version_label, ...
    version_action=plan.extractor.version_action, ...
    version_matches_feature_scope=plan.extractor.version_matches_feature_scope);

result.output_profile = struct( ...
    profile_key=plan.output_profile.profile_key, ...
    version_label=plan.output_profile.version_label, ...
    profile_schema_version=plan.output_profile.profile_schema_version, ...
    profile_version_id=plan.output_profile.profile_version_id, ...
    checksum_sha256=plan.output_profile.checksum_sha256, ...
    content_uri=plan.output_profile.content_uri, ...
    action=plan.output_profile.action);

result.settings = struct( ...
    status=plan.settings_status, ...
    mode=plan.settings_profile.mode, ...
    profile_key=plan.settings_profile.profile_key, ...
    version_label=plan.settings_profile.version_label, ...
    profile_version_id=plan.settings_profile.profile_version_id, ...
    checksum_sha256=plan.settings_profile.checksum_sha256, ...
    profile_action=plan.settings_profile.profile_action, ...
    version_action=plan.settings_profile.version_action);

result.model = struct( ...
    status=plan.model_status, ...
    mode=plan.context.model.mode, ...
    model_label=plan.context.model.model_label, ...
    evidence_source=plan.context.model.evidence_source);

result.extraction_run = struct( ...
    run_key=plan.run.run_key, ...
    run_label=plan.run.run_label, ...
    status=plan.run.status, ...
    action=plan.run.action, ...
    extraction_run_id=plan.run.existing_extraction_run_id, ...
    input_action=plan.run.input_action);

result.artifacts = plan.artifacts(:, ["role", "artifact_type", "path_or_uri", ...
    "checksum_sha256", "checksum_status", "action", "existing_artifact_id"]);
result.artifacts.Properties.VariableNames{end} = 'artifact_id';
result.run_artifacts = plan.run_artifacts;

result.events = eventSummary(plan);
result.detections = plan.events.counts;
result.detections.planned = numel(plan.events.detections);
result.classification = struct( ...
    present=plan.events.classification.present, ...
    method=plan.events.classification.method, ...
    action=plan.events.classification.action, ...
    classification_run_id=plan.events.classification.classification_run_id, ...
    native_labels=plan.events.classification.classes, ...
    canonical_interpretation="none");
result.validation = struct( ...
    is_valid=plan.validation.is_valid, ...
    evaluated_checks=plan.validation.evaluated_checks, ...
    unevaluated_checks=plan.validation.unevaluated_checks, ...
    warnings=plan.validation.warnings);

result.warnings = plan.warnings;
result.conflicts = plan.conflicts;
result.has_conflicts = plan.has_conflicts;
result.export = struct( ...
    source_key=plan.export.source_key, ...
    row_count=plan.export.artifact.row_count, ...
    sheet_name=plan.export.artifact.sheet_name, ...
    relative_path=plan.export.artifact.relative_path, ...
    relative_path_source=plan.export.artifact.relative_path_source, ...
    runtime_path=plan.export.artifact.runtime_path);
result.plan = plan;
end

function summary = eventSummary(plan)
%EVENTSUMMARY One row per planned detection, inspectable before commit.
%
% Measurement counts come from the routed evidence rather than from
% height(ir.values): identity, review, and label evidence are not measurements,
% so counting IR values would overstate them.
count = numel(plan.events.detections);
sourceRow = NaN(count, 1);
nativeEventId = strings(count, 1);
startTime = NaN(count, 1);
endTime = NaN(count, 1);
measurementCount = NaN(count, 1);
action = strings(count, 1);
detectionId = NaN(count, 1);

for index = 1:count
    detection = plan.events.detections{index};
    sourceRow(index) = detection.source_row;
    nativeEventId(index) = detection.native_event_id;
    startTime(index) = detection.start_time_s;
    endTime(index) = detection.end_time_s;
    measurementCount(index) = height(detection.measurements);
    action(index) = detection.action;
    detectionId(index) = detection.detection_id;
end

summary = table(sourceRow, nativeEventId, startTime, endTime, ...
    measurementCount, action, detectionId, ...
    VariableNames=["source_row", "native_event_id", "start_time_s", ...
    "end_time_s", "measurement_count", "action", "detection_id"]);
end
