function [plan, counts] = deepsqueakApplyPlan(conn, plan)
%DEEPSQUEAKAPPLYPLAN Atomically apply the DeepSqueak scientific graph.
%
% One function owns one transaction for the whole import, so a failure while
% inserting detections can never leave an orphaned extraction run behind.
% Helpers called from here perform inserts only; none starts, commits, or rolls
% back a transaction of its own, and semantic seed registration is never invoked
% from inside it.
%
% The provenance rows and the event population are written by the shared
% extractor core, which both importers use. What remains here is the evidence
% only DeepSqueak exports: the run-scoped label context, the review state that
% becomes curation evidence, and the class assignments.
%
% Dependency order is fixed by the schema: extraction_run_inputs must exist
% before any detection, because trg_detection_requires_run_input rejects a
% detection whose recording is not a registered input to its run.

if plan.has_conflicts
    error("vawlume:ingest:DeepSqueakPlanConflict", ...
        "A DeepSqueak import plan with conflicts cannot be applied.");
end

oldAutoCommit = string(conn.AutoCommit);
if oldAutoCommit ~= "on"
    error("vawlume:ingest:TransactionState", ...
        "DeepSqueak import requires a connection with AutoCommit enabled.");
end

counts = emptyCounts();
conn.AutoCommit = "off";
try
    [plan, counts] = extractorApplyProvenance(conn, plan, counts, ...
        SettingsDescription="DeepSqueak extractor settings profile.", ...
        SettingsVersionNote="Extractor settings profile supplied with a DeepSqueak import.", ...
        ExtractorVersionNote="Exact extractor version declared for a DeepSqueak import.", ...
        RunNotes=runNotes(plan));
    [plan, counts] = applyClassificationRun(conn, plan, counts);
    [plan, counts] = applyEventPopulation(conn, plan, counts);
    if insertedRowCount(counts) > 0
        commit(conn);
    end
catch exception
    try
        rollback(conn);
    catch
    end
    conn.AutoCommit = oldAutoCommit;
    rethrow(exception);
end
conn.AutoCommit = oldAutoCommit;
end


function notes = runNotes(plan)
% Absent settings and model rows are indistinguishable from "never asked" unless
% the run says so, so the run records what was and was not recoverable.
statements = "settings=" + plan.settings_status + "; model=" + plan.model_status;
if strlength(plan.run.notes) > 0
    notes = plan.run.notes + " [" + statements + "]";
else
    notes = statements;
end
end

function [plan, counts] = applyClassificationRun(conn, plan, counts)
%APPLYCLASSIFICATIONRUN Create the run-scoped label context before assignments.
%
% classification_* is the only schema surface that can preserve an extractor's
% label evidence, so the run is recorded, but its method states that the label's
% provenance is unspecified unless the caller supplied a real one. No class is
% given a canonical biological meaning and no model is claimed.
classification = plan.events.classification;
if ~classification.present
    return
end

existing = fetch(conn, ...
    "SELECT classification_run_id FROM classification_runs " + ...
    "WHERE parent_extraction_run_id = " + string(plan.run.existing_extraction_run_id) + ...
    " AND method = '" + replace(classification.method, "'", "''") + "'");
if ~isempty(existing) && height(existing) > 0
    classification.classification_run_id = double(existing.classification_run_id(1));
    classification.action = "reuse";
    counts.reused_classification_runs = counts.reused_classification_runs + 1;
else
    classification.classification_run_id = insertIntakeRow(conn, "classification_runs", struct( ...
        project_id=plan.recording.project_id, ...
        parent_extraction_run_id=plan.run.existing_extraction_run_id, ...
        method=classification.method, ...
        run_label=classification.run_label, ...
        number_of_classes=numel(classification.classes), ...
        notes="Extractor-native labels imported from a DeepSqueak call-statistics export."), ...
        "classification_run_id");
    classification.action = "create";
    counts.classification_runs = counts.classification_runs + 1;
end

for index = 1:numel(classification.classes)
    nativeLabel = classification.classes(index);
    stored = fetch(conn, ...
        "SELECT classification_class_id FROM classification_classes " + ...
        "WHERE classification_run_id = " + string(classification.classification_run_id) + ...
        " AND native_class_id = '" + replace(nativeLabel, "'", "''") + "'");
    if ~isempty(stored) && height(stored) > 0
        classification.class_ids(index) = double(stored.classification_class_id(1));
        classification.class_actions(index) = "reuse";
        counts.reused_classification_classes = counts.reused_classification_classes + 1;
        continue
    end
    classification.class_ids(index) = insertIntakeRow(conn, "classification_classes", struct( ...
        classification_run_id=classification.classification_run_id, ...
        native_class_id=nativeLabel, ...
        native_class_label=nativeLabel, ...
        description="Extractor-native label preserved without canonical interpretation."), ...
        "classification_class_id");
    classification.class_actions(index) = "create";
    counts.classification_classes = counts.classification_classes + 1;
end

plan.events.classification = classification;
end

function [plan, counts] = applyEventPopulation(conn, plan, counts)
% The export artifact's row id is read again here rather than taken from the
% plan. When the artifact is created by this same apply, the plan recorded it as
% unresolved, and writing that into detections would leave source_artifact_id
% NULL. Detection identity is UNIQUE(run, recording, source_artifact_id,
% native_event_id), and SQLite treats NULLs as distinct, so a NULL there would
% silently let every rerun insert a second copy of the whole population.
%
% Detections and measurements are written by the shared extractor core inside
% this same transaction. Review and label evidence follow here, because they are
% DeepSqueak's own exported evidence rather than a universal event property.
scope = struct( ...
    extraction_run_id=plan.run.existing_extraction_run_id, ...
    recording_id=plan.recording.recording_id, ...
    source_artifact_id=appliedExportArtifactId(plan), ...
    event_subtype="vocalization_detection", ...
    timing_basis="profile_selected_event_geometry");
[plan.events.detections, counts] = extractorApplyEvents(conn, scope, ...
    plan.events.detections, counts);

for index = 1:numel(plan.events.detections)
    detection = plan.events.detections{index};
    counts = applyCuration(conn, detection, counts);
    counts = applyAssignment(conn, plan, detection, counts);
end
end

function id = appliedExportArtifactId(plan)
rows = plan.artifacts(plan.artifacts.role == "event_measurement_export", :);
id = double(rows.existing_artifact_id(1));
if isnan(id)
    error("vawlume:ingest:DeepSqueakArtifactUnresolved", ...
        "The export artifact was not resolved before the event population.");
end
end

function counts = applyCuration(conn, detection, counts)
if detection.curation.action == "skip"
    return
end
if detection.curation.action == "reuse"
    counts.reused_curation_events = counts.reused_curation_events + 1;
    return
end

insertIntakeRow(conn, "curation_events", struct( ...
    detection_id=detection.detection_id, ...
    source_artifact_id=detection.source_artifact_id, ...
    action_type=detection.curation.action_type, ...
    status_after=detection.curation.status_after, ...
    actor_type="extractor", ...
    actor_label="DeepSqueak " + detection.curation.native_field + " column", ...
    details_json=jsonencode(struct( ...
        native_field=detection.curation.native_field, ...
        native_raw_token=detection.curation.raw_token, ...
        canonical_status=detection.curation.status_after)), ...
    notes="Extractor review state, not a biological ground-truth claim."));
counts.curation_events = counts.curation_events + 1;
end

function counts = applyAssignment(conn, plan, detection, counts)
if detection.classification.action == "skip"
    return
end
if detection.classification.action == "reuse"
    counts.reused_classification_assignments = ...
        counts.reused_classification_assignments + 1;
    return
end

classification = plan.events.classification;
classIndex = find(classification.classes == detection.classification.native_label, 1);
if isempty(classIndex)
    return
end

insertIntakeRow(conn, "classification_assignments", struct( ...
    detection_id=detection.detection_id, ...
    classification_run_id=classification.classification_run_id, ...
    classification_class_id=classification.class_ids(classIndex), ...
    assignment_source="extractor", ...
    notes="Extractor-native label; provenance of the labelling method is not stated by the export."));
counts.classification_assignments = counts.classification_assignments + 1;
end

function total = insertedRowCount(counts)
%INSERTEDROWCOUNT Number of rows this apply actually wrote.
%
% A fully compatible rerun reuses every row and therefore writes nothing, which
% leaves SQLite with no open transaction to commit. Unlike project intake, this
% importer records no per-attempt audit row, so the no-write case is normal
% rather than exceptional and must not be reported as a commit failure.
total = counts.config_profiles + counts.config_profile_versions + ...
    counts.extractor_versions + counts.artifacts + counts.extraction_runs + ...
    counts.extraction_run_inputs + counts.extraction_run_artifacts + ...
    counts.classification_runs + counts.classification_classes + ...
    counts.detections + counts.event_measurements + counts.curation_events + ...
    counts.classification_assignments;
end

function counts = emptyCounts()
counts = struct( ...
    config_profiles=0, ...
    config_profile_versions=0, ...
    extractor_versions=0, ...
    artifacts=0, ...
    extraction_runs=0, ...
    extraction_run_inputs=0, ...
    extraction_run_artifacts=0, ...
    classification_runs=0, ...
    classification_classes=0, ...
    detections=0, ...
    event_measurements=0, ...
    curation_events=0, ...
    classification_assignments=0, ...
    reused_config_profiles=0, ...
    reused_config_profile_versions=0, ...
    reused_extractor_versions=0, ...
    reused_artifacts=0, ...
    reused_extraction_runs=0, ...
    reused_extraction_run_inputs=0, ...
    reused_extraction_run_artifacts=0, ...
    reused_classification_runs=0, ...
    reused_classification_classes=0, ...
    reused_detections=0, ...
    reused_event_measurements=0, ...
    reused_curation_events=0, ...
    reused_classification_assignments=0);
end
