function result = deepsqueakPlanResult(plan)
%DEEPSQUEAKPLANRESULT Build the inspectable DeepSqueak import manifest.
%
% Every disposition is readable from the returned value, so a caller can tell
% what will be created, reused, or refused without reading console output.

arguments
    plan (1,1) struct
end

result = struct();
if plan.has_conflicts
    result.status = "conflict";
else
    result.status = "planned";
end
result.committed = false;

result.recording = struct( ...
    recording_id=plan.recording.recording_id, ...
    project_id=plan.recording.project_id, ...
    project_key=plan.recording.project_key, ...
    source_file_id=plan.recording.source_file_id, ...
    source_relative_path=plan.recording.source_relative_path, ...
    resolution_mode=plan.recording.resolution_mode);

result.extractor = struct( ...
    extractor_id=plan.extractor.extractor_id, ...
    extractor_name=plan.extractor.extractor_name, ...
    declared_version=plan.extractor.run_version_label, ...
    run_extractor_version_id=plan.extractor.run_version_id, ...
    feature_extractor_version_id=plan.extractor.feature_version_id, ...
    feature_scope_version_label=plan.extractor.scope_version_label, ...
    version_action=plan.extractor.version_action, ...
    version_matches_feature_scope=plan.extractor.version_matches_feature_scope);

result.output_profile = struct( ...
    profile_key=plan.output_profile.profile_key, ...
    version_label=plan.output_profile.version_label, ...
    profile_schema_version=plan.output_profile.profile_schema_version, ...
    profile_version_id=plan.output_profile.profile_version_id, ...
    checksum_sha256=plan.output_profile.checksum_sha256, ...
    content_uri=plan.output_profile.content_uri, ...
    action=plan.output_profile.action);

result.settings = struct( ...
    status=plan.settings_status, ...
    mode=plan.settings_profile.mode, ...
    profile_key=plan.settings_profile.profile_key, ...
    version_label=plan.settings_profile.version_label, ...
    profile_version_id=plan.settings_profile.profile_version_id, ...
    checksum_sha256=plan.settings_profile.checksum_sha256, ...
    profile_action=plan.settings_profile.profile_action, ...
    version_action=plan.settings_profile.version_action);

result.model = struct( ...
    status=plan.model_status, ...
    mode=plan.context.model.mode, ...
    model_label=plan.context.model.model_label, ...
    evidence_source=plan.context.model.evidence_source);

result.extraction_run = struct( ...
    run_key=plan.run.run_key, ...
    run_label=plan.run.run_label, ...
    status=plan.run.status, ...
    action=plan.run.action, ...
    extraction_run_id=plan.run.existing_extraction_run_id, ...
    input_action=plan.run.input_action);

result.artifacts = plan.artifacts(:, ["role", "artifact_type", "path_or_uri", ...
    "checksum_sha256", "checksum_status", "action", "existing_artifact_id"]);
result.artifacts.Properties.VariableNames{end} = 'artifact_id';
result.run_artifacts = plan.run_artifacts;

result.detections = struct( ...
    planned=0, ...
    applied=0, ...
    note="Event population is inserted by a later pass inside this same transaction.");

result.warnings = plan.warnings;
result.conflicts = plan.conflicts;
result.has_conflicts = plan.has_conflicts;
result.export = struct( ...
    source_key=plan.export.source_key, ...
    row_count=plan.export.artifact.row_count, ...
    sheet_name=plan.export.artifact.sheet_name, ...
    relative_path=plan.export.artifact.relative_path, ...
    relative_path_source=plan.export.artifact.relative_path_source, ...
    runtime_path=plan.export.artifact.runtime_path);
result.plan = plan;
end
