function artifacts = deepsqueakResolveArtifacts(conn, projectId, export, context, roots)
%DEEPSQUEAKRESOLVEARTIFACTS Classify every artifact this import registers.
%
% Artifact identity follows the schema's UNIQUE(project_id, path_or_uri) with a
% portable path in path_or_uri. Relocating unchanged content therefore reuses the
% existing row instead of creating a second one, while the same portable path
% carrying different content is an explicit conflict rather than a silent
% overwrite.
%
% The recording's raw audio keeps the Phase 3 source_files identity and is never
% re-registered here as though it were extractor output.

arguments
    conn
    projectId (1,1) double
    export (1,1) struct
    context (1,1) struct
    roots (1,:) string
end
candidates = {};
candidates{end + 1} = exportCandidate(export);

if context.native_artifact.mode == "artifact"
    candidates{end + 1} = optionalCandidate(context.native_artifact, roots, ...
        "native_detection_container", "native_detection_container", true, ...
        "DeepSqueak native detection container");
end
if context.settings.mode == "artifact"
    candidates{end + 1} = optionalCandidate(context.settings, roots, ...
        "extractor_settings", "extractor_settings", false, ...
        "External DeepSqueak settings artifact; not a validated VAWLUME settings profile");
end
if context.model.mode == "artifact"
    candidates{end + 1} = optionalCandidate(context.model, roots, ...
        "detector_model", "detector_network", true, ...
        modelDescription(context.model));
end

artifacts = extractorClassifyArtifacts(conn, projectId, candidates);
end

function candidate = exportCandidate(export)
provenance = export.artifact;
assertPortable(provenance.relative_path, provenance.runtime_path, ...
    "the DeepSqueak call-statistics export", ...
    "Supply ArtifactRoot, RepoRoot, or RelativePath.");

candidate = struct( ...
    role="event_measurement_export", ...
    artifact_type="extractor_event_export", ...
    native_artifact_type=provenance.native_artifact_type, ...
    file_format=provenance.file_format, ...
    is_native=false, ...
    path_or_uri=provenance.relative_path, ...
    runtime_path=provenance.runtime_path, ...
    checksum_sha256=provenance.checksum_sha256, ...
    checksum_status="computed", ...
    description="DeepSqueak call-statistics export imported by VAWLUME");
end

function candidate = optionalCandidate(declared, roots, artifactType, role, isNative, description)
artifactPath = declared.artifact_path;
if ~isfile(artifactPath)
    error("vawlume:ingest:DeepSqueakArtifactNotFound", ...
        "Declared %s artifact does not exist: %s", role, artifactPath);
end

location = deepsqueakPortableLocation(artifactPath, declared.relative_path, roots);
assertPortable(location.relative_path, location.runtime_path, ...
    "the declared " + role + " artifact", ...
    "Supply ArtifactRoot, RepoRoot, or a relative_path in runSpec.");

[checksum, checksumStatus] = optionalChecksum(artifactPath);
candidate = struct( ...
    role=role, ...
    artifact_type=artifactType, ...
    native_artifact_type=declared.native_type, ...
    file_format=location.extension, ...
    is_native=isNative, ...
    path_or_uri=location.relative_path, ...
    runtime_path=location.runtime_path, ...
    checksum_sha256=checksum, ...
    checksum_status=checksumStatus, ...
    description=description);
end

function description = modelDescription(model)
description = "DeepSqueak detector model (" + model.evidence_source + ")";
if strlength(model.model_label) > 0
    description = description + ": " + model.model_label;
end
end

function [checksum, status] = optionalChecksum(artifactPath)
% Stream the digest so even large native containers and detector networks keep
% content identity without loading the whole artifact into memory.
checksum = sha256OfFile(artifactPath);
status = "computed";
end

function assertPortable(relativePath, runtimePath, subject, remedy)
if strlength(relativePath) > 0
    return
end
error("vawlume:ingest:DeepSqueakArtifactNotPortable", ...
    ['No portable path could be derived for %s (%s). An absolute runtime path ' ...
    'is not durable artifact identity, because relocating the same content ' ...
    'would create a duplicate artifact. %s'], subject, runtimePath, remedy);
end
