function profile = extractorResolveOutputProfile(conn, irProfile, errorToken)
%EXTRACTORRESOLVEOUTPUTPROFILE Resolve the registered mapping profile version.

arguments
    conn
    irProfile (1,1) struct
    errorToken (1,1) string
end

profile = struct(profile_key=string(irProfile.profile_key), ...
    profile_kind=string(irProfile.profile_kind), ...
    version_label=string(irProfile.profile_version), ...
    profile_schema_version=string(irProfile.profile_schema_version), ...
    content_format=string(irProfile.profile_content_format), ...
    content_uri=string(irProfile.profile_path), ...
    checksum_sha256=string(irProfile.profile_checksum), action="reuse", ...
    conflict_message="", profile_id=NaN, profile_version_id=NaN);
if profile.profile_kind ~= "extractor_output"
    error(errorId(errorToken, "ProfileUnsupported"), ...
        "Expected an extractor_output mapping profile, found '%s'.", profile.profile_kind);
end

rows = fetch(conn, "SELECT profile_id, profile_kind FROM config_profiles " + ...
    "WHERE profile_key = " + sqlText(profile.profile_key) + " AND project_id IS NULL");
if isempty(rows) || height(rows) == 0
    error(errorId(errorToken, "ProfileUnregistered"), ...
        "Output mapping profile '%s' is not registered. Run vawlume.db.registerBuiltinSemantics first.", ...
        profile.profile_key);
end
profile.profile_id = double(rows.profile_id(1));
storedKind = string(rows.profile_kind(1));
if storedKind ~= profile.profile_kind
    profile.action = "conflict";
    profile.conflict_message = "Registered profile kind '" + storedKind + ...
        "' does not match the IR profile kind '" + profile.profile_kind + "'.";
    return
end

versions = fetch(conn, "SELECT profile_version_id, version_label, " + ...
    "IFNULL(profile_schema_version, '') AS profile_schema_version, " + ...
    "IFNULL(content_format, '') AS content_format, " + ...
    "IFNULL(content_uri, '') AS content_uri, IFNULL(checksum_sha256, '') AS checksum_sha256 " + ...
    "FROM config_profile_versions WHERE profile_id = " + string(profile.profile_id) + ...
    " AND version_label = " + sqlText(profile.version_label));
if isempty(versions) || height(versions) == 0
    error(errorId(errorToken, "ProfileUnregistered"), ...
        "Output mapping profile '%s' has no registered version '%s'.", ...
        profile.profile_key, profile.version_label);
end
profile.profile_version_id = double(versions.profile_version_id(1));
storedChecksum = string(versions.checksum_sha256(1));
storedUri = string(versions.content_uri(1));
storedSchema = string(versions.profile_schema_version(1));
if strlength(storedChecksum) > 0 && strlength(profile.checksum_sha256) > 0 && ...
        storedChecksum ~= profile.checksum_sha256
    profile.action = "conflict";
    profile.conflict_message = "Registered profile version '" + profile.version_label + ...
        "' has checksum " + storedChecksum + " but the loaded profile has checksum " + ...
        profile.checksum_sha256 + ".";
    return
end
if strlength(storedSchema) > 0 && strlength(profile.profile_schema_version) > 0 && ...
        storedSchema ~= profile.profile_schema_version
    profile.action = "conflict";
    profile.conflict_message = "Registered profile version '" + profile.version_label + ...
        "' declares profile-language version " + storedSchema + ...
        " but the loaded profile declares " + profile.profile_schema_version + ".";
    return
end
profile.registered_content_uri = storedUri;
profile.registered_checksum_sha256 = storedChecksum;
end

function value = errorId(token, suffix), value = "vawlume:ingest:" + token + suffix; end
function value = sqlText(text), value = "'" + replace(string(text), "'", "''") + "'"; end
