function recording = extractorResolveRecording(conn, recordingRef, errorToken)
%EXTRACTORRESOLVERECORDING Resolve one recording established by project intake.

arguments
    conn
    recordingRef (1,1) struct
    errorToken (1,1) string
end

switch recordingRef.mode
    case "recording_id"
        rows = fetch(conn, "SELECT r.recording_id, r.project_id, p.project_key, " + ...
            "IFNULL(r.native_recording_id, '') AS native_recording_id, " + ...
            "r.source_file_id, IFNULL(sf.relative_path, '') AS relative_path " + ...
            "FROM recordings r JOIN projects p ON p.project_id = r.project_id " + ...
            "JOIN source_files sf ON sf.source_file_id = r.source_file_id " + ...
            "WHERE r.recording_id = " + string(recordingRef.recording_id));
        describe = "recording_id " + string(recordingRef.recording_id);
    case "portable_source"
        rows = fetch(conn, "SELECT r.recording_id, r.project_id, p.project_key, " + ...
            "IFNULL(r.native_recording_id, '') AS native_recording_id, " + ...
            "r.source_file_id, IFNULL(sf.relative_path, '') AS relative_path " + ...
            "FROM recordings r JOIN projects p ON p.project_id = r.project_id " + ...
            "JOIN source_files sf ON sf.source_file_id = r.source_file_id " + ...
            "WHERE p.project_key = " + sqlText(recordingRef.project_key) + ...
            " AND sf.relative_path = " + sqlText(recordingRef.source_relative_path));
        describe = "project_key " + recordingRef.project_key + ...
            " with source_relative_path " + recordingRef.source_relative_path;
    otherwise
        error(errorId(errorToken, "RecordingRefInvalid"), ...
            "Unsupported recordingRef mode '%s'.", recordingRef.mode);
end

if isempty(rows) || height(rows) == 0
    error(errorId(errorToken, "RecordingNotFound"), ...
        "No established recording matches %s. Run project intake for this source before importing extractor output.", ...
        describe);
end
if height(rows) > 1
    error(errorId(errorToken, "RecordingAmbiguous"), ...
        "Reference %s matched %d recordings; exactly one is required.", describe, height(rows));
end

recording = struct(recording_id=double(rows.recording_id(1)), ...
    project_id=double(rows.project_id(1)), project_key=string(rows.project_key(1)), ...
    native_recording_id=string(rows.native_recording_id(1)), ...
    source_file_id=double(rows.source_file_id(1)), ...
    source_relative_path=string(rows.relative_path(1)), ...
    resolution_mode=recordingRef.mode);
end

function value = errorId(token, suffix)
value = "vawlume:ingest:" + token + suffix;
end

function value = sqlText(text)
value = "'" + replace(string(text), "'", "''") + "'";
end
