function result = mupetPlanResult(plan)
%MUPETPLANRESULT Build an inspectable MUPET provenance manifest.

if plan.has_conflicts, status = "conflict"; else, status = "planned"; end
result = struct(status=status, committed=false, ...
    ready_for_event_apply=plan.ready_for_event_apply, ...
    recording=struct(recording_id=plan.recording.recording_id, ...
        project_id=plan.recording.project_id, project_key=plan.recording.project_key, ...
        source_file_id=plan.recording.source_file_id, ...
        source_relative_path=plan.recording.source_relative_path, ...
        resolution_mode=plan.recording.resolution_mode), ...
    extractor=struct(extractor_id=plan.extractor.extractor_id, ...
        extractor_name=plan.extractor.extractor_name, ...
        declared_version=plan.extractor.run_version_label, ...
        run_extractor_version_id=plan.extractor.run_version_id, ...
        feature_extractor_version_id=plan.extractor.feature_version_id, ...
        feature_scope_version_label=plan.extractor.scope_version_label, ...
        version_action=plan.extractor.version_action), ...
    output_profile=struct(profile_key=plan.output_profile.profile_key, ...
        version_label=plan.output_profile.version_label, ...
        profile_version_id=plan.output_profile.profile_version_id, ...
        checksum_sha256=plan.output_profile.checksum_sha256, ...
        action=plan.output_profile.action), ...
    settings=struct(status=plan.settings_status, mode=plan.context.settings.mode, ...
        structured_capture_checksum_sha256=string(plan.export.settings.structured_capture_checksum_sha256), ...
        profile_key=plan.settings_profile.profile_key, ...
        version_label=plan.settings_profile.version_label, ...
        profile_version_id=plan.settings_profile.profile_version_id, ...
        checksum_sha256=plan.settings_profile.checksum_sha256, ...
        profile_action=plan.settings_profile.profile_action, ...
        version_action=plan.settings_profile.version_action), ...
    extraction_run=struct(run_key=plan.run.run_key, run_label=plan.run.run_label, ...
        status=plan.run.status, action=plan.run.action, ...
        extraction_run_id=plan.run.existing_extraction_run_id, ...
        input_action=plan.run.input_action), ...
    dataset=plan.context.dataset, extractor_objects=plan.extractor_objects, ...
    event_population=struct(status="deferred_to_phase_5_pass_4", ...
        source_row_count=plan.export.artifact.row_count, planned_detection_count=0), ...
    warnings=plan.warnings, conflicts=plan.conflicts, has_conflicts=plan.has_conflicts, ...
    export=struct(source_key=plan.export.source_key, row_count=plan.export.artifact.row_count, ...
        relative_path=plan.export.artifact.relative_path, ...
        relative_path_source=plan.export.artifact.relative_path_source, ...
        runtime_path=plan.export.artifact.runtime_path));
result.artifacts = plan.artifacts(:, ["role", "artifact_type", "native_artifact_type", ...
    "is_native", "path_or_uri", "checksum_sha256", "checksum_status", ...
    "action", "existing_artifact_id", "metadata_json"]);
result.artifacts.Properties.VariableNames{9} = 'artifact_id';
result.run_artifacts = plan.run_artifacts;
result.plan = plan;
end
