function artifacts = mupetResolveArtifacts(conn, projectId, export, context, roots)
%MUPETRESOLVEARTIFACTS Build MUPET candidates, then use shared classification.

candidates = {exportCandidate(export, context.dataset)};
if context.settings.mode == "config_csv"
    candidates{end+1} = configCandidate(export.settings, context.dataset);
end
if context.native_artifact.mode == "artifact"
    [~,~,extension] = fileparts(context.native_artifact.artifact_path);
    if lower(string(extension)) ~= ".mat"
        error("vawlume:ingest:MupetNativeArtifactUnsupported", ...
            "MUPET native processed recording evidence must be a .mat artifact.");
    end
    candidates{end+1} = fileCandidate(context.native_artifact.artifact_path, ...
        context.native_artifact.relative_path, roots, "native_processed_recording", ...
        "native_processed_recording", true, context.native_artifact.native_type, ...
        "MUPET native processed recording; hashed and registered without parsing", ...
        datasetMetadata(context.dataset));
end
artifacts = extractorClassifyArtifacts(conn, projectId, candidates);
end

function candidate = exportCandidate(export, dataset)
value = export.artifact;
assertPortable(value.relative_path, value.runtime_path, "event CSV");
candidate = struct(role="event_measurement_export", ...
    artifact_type="extractor_event_export", ...
    native_artifact_type=value.native_artifact_type, file_format=value.file_format, ...
    is_native=false, path_or_uri=value.relative_path, runtime_path=value.runtime_path, ...
    checksum_sha256=value.checksum_sha256, checksum_status="computed", ...
    description="MUPET per-syllable event export imported by VAWLUME", ...
    metadata_json=datasetMetadata(dataset));
end

function candidate = configCandidate(settings, dataset)
value = settings.source_artifact;
assertPortable(value.relative_path, value.runtime_path, "settings config.csv");
capture = struct(status=settings.status, complete=settings.complete, ...
    extractor_name=settings.extractor_name, extractor_version=settings.extractor_version, ...
    source_checksum_sha256=settings.source_checksum_sha256, ...
    structured_capture_checksum_sha256=settings.structured_capture_checksum_sha256, ...
    missing_required_keys=settings.missing_required_keys, ...
    entries=table2struct(settings.entries), lineage=settings.lineage, dataset=dataset);
candidate = struct(role="extractor_settings", artifact_type="extractor_settings", ...
    native_artifact_type=value.native_artifact_type, file_format=value.file_format, ...
    is_native=false, path_or_uri=value.relative_path, runtime_path=value.runtime_path, ...
    checksum_sha256=value.checksum_sha256, checksum_status="computed", ...
    description="Native MUPET config.csv with structured faithful capture in artifact metadata", ...
    metadata_json=string(jsonencode(capture)));
end

function candidate = fileCandidate(path, relativePath, roots, type, role, native, nativeType, description, metadata)
if ~isfile(path)
    error("vawlume:ingest:MupetArtifactNotFound", "Declared %s artifact does not exist: %s", role, path);
end
location = extractorPortableLocation(path, relativePath, roots, "Mupet");
assertPortable(location.relative_path, location.runtime_path, role);
candidate = struct(role=role, artifact_type=type, native_artifact_type=nativeType, ...
    file_format=location.extension, is_native=native, path_or_uri=location.relative_path, ...
    runtime_path=location.runtime_path, checksum_sha256=sha256OfFile(path), ...
    checksum_status="computed", description=description, metadata_json=metadata);
end

function text = datasetMetadata(dataset)
text = "";
if dataset.status ~= "not_supplied"
    text = string(jsonencode(struct(mupet_dataset=dataset, ...
        hierarchy_policy="extractor_provenance_only_no_experimental_entities")));
end
end

function assertPortable(relativePath, runtimePath, subject)
if strlength(relativePath) == 0
    error("vawlume:ingest:MupetArtifactNotPortable", ...
        "No portable path could be derived for the MUPET %s (%s). Supply ArtifactRoot, RepoRoot, or relative_path.", ...
        subject, runtimePath);
end
end
