function result = projectPlanResult(plan)
%PROJECTPLANRESULT Build the stable developer-facing planning manifest.

result = struct();
if plan.has_conflicts
    result.status = "conflict";
else
    result.status = "planned";
end
result.committed = false;
result.project_id = resolvedId(plan.project.action, ...
    plan.project.existing_project_id);
result.ingestion_run_id = resolvedId( ...
    plan.ingestion_run.action, ...
    plan.ingestion_run.existing_ingestion_run_id);
result.mapping_profile_version_id = resolvedId( ...
    plan.mapping_profile.version_action, ...
    plan.mapping_profile.existing_profile_version_id);
result.source_ids = plan.sources(:, ...
    ["source_key", "existing_source_file_id", "action"]);
result.source_ids.Properties.VariableNames{2} = 'source_file_id';
result.entity_type_ids = plan.entity_types(:, ...
    ["entity_type_key", "existing_entity_type_id", "action"]);
result.entity_type_ids.Properties.VariableNames{2} = 'entity_type_id';
result.entity_ids = plan.entity_records(:, ...
    ["record_key", "existing_entity_id", "action"]);
result.entity_ids.Properties.VariableNames{2} = 'entity_id';
result.relationship_summary = struct( ...
    created=sum(plan.relationships.action == "create"), ...
    reused=sum(plan.relationships.action == "reuse"), ...
    conflicts=sum(plan.relationships.action == "conflict"), ...
    deferred=height(plan.deferred_relationships));
result.recording_ids = plan.recordings(:, ...
    ["record_key", "existing_recording_id", "action"]);
result.recording_ids.Properties.VariableNames{2} = 'recording_id';
result.recording_link_summary = struct( ...
    created=sum(plan.recording_links.action == "create"), ...
    reused=sum(plan.recording_links.action == "reuse"), ...
    conflicts=sum(plan.recording_links.action == "conflict"));
result.ingestion_file_summary = struct( ...
    created=sum(plan.ingestion_files.action == "create"), ...
    skipped=sum(plan.ingestion_files.action == "skip"), ...
    parsed=sum(plan.ingestion_files.parse_status == "parsed"), ...
    parsed_with_warnings=sum( ...
    plan.ingestion_files.parse_status == "parsed_with_warnings"));
result.profile_version_ids = profileVersionMap(plan);
result.project_profile_assignments = plan.project_profile_assignments(:, ...
    ["assignment_key", "profile_key", "profile_version_id", ...
    "assignment_role", "is_default", "action"]);
result.recording_profile_assignments = ...
    plan.recording_profile_assignments(:, ...
    ["assignment_key", "recording_key", "profile_key", ...
    "profile_version_id", "assignment_role", ...
    "inheritance_source", "action"]);
allAssignmentActions = [ ...
    plan.project_profile_assignments.action; ...
    plan.recording_profile_assignments.action];
result.profile_assignment_summary = struct( ...
    created=sum(allAssignmentActions == "create"), ...
    reused=sum(allAssignmentActions == "reuse"), ...
    conflicts=sum(allAssignmentActions == "conflict"));
result.created_counts = actionCounts(plan, "create");
result.reused_counts = actionCounts(plan, "reuse");
result.conflict_counts = actionCounts(plan, "conflict");
result.applied_counts = zeroAppliedCounts();
result.issues = plan.issues;
result.warnings = plan.issues(plan.issues.severity == "warning", :);
result.plan = plan;
end

function value = resolvedId(action, id)
if action == "reuse" || (action == "create" && ~isnan(id))
    value = id;
else
    value = NaN;
end
end

function value = actionCounts(plan, action)
value = struct( ...
    projects=double(plan.project.action == action), ...
    config_profiles=double(plan.mapping_profile.profile_action == action) + ...
    sum(plan.profile_linkage.profiles.profile_action == action), ...
    config_profile_versions= ...
    double(plan.mapping_profile.version_action == action) + ...
    sum(plan.profile_linkage.profiles.version_action == action), ...
    project_profile_assignments=sum( ...
    plan.project_profile_assignments.action == action), ...
    ingestion_runs=double(plan.ingestion_run.action == action), ...
    ingestion_files=sum(plan.ingestion_files.action == action), ...
    source_files=sum(plan.sources.action == action), ...
    entity_types=sum(plan.entity_types.action == action), ...
    entities=sum(plan.entities.action == action), ...
    entity_relationships=sum(plan.relationships.action == action), ...
    recordings=sum(plan.recordings.action == action), ...
    recording_entity_links=sum(plan.recording_links.action == action), ...
    recording_profile_assignments=sum( ...
    plan.recording_profile_assignments.action == action));
end

function value = zeroAppliedCounts()
value = struct( ...
    projects=0, config_profiles=0, config_profile_versions=0, ...
    project_profile_assignments=0, ingestion_runs=0, ingestion_files=0, ...
    source_files=0, entity_types=0, entities=0, entity_relationships=0, ...
    recordings=0, recording_entity_links=0, ...
    recording_profile_assignments=0, reused_projects=0, ...
    reused_config_profiles=0, reused_config_profile_versions=0, ...
    reused_project_profile_assignments=0, reused_source_files=0, ...
    reused_entity_types=0, reused_entities=0, ...
    reused_entity_relationships=0, reused_recordings=0, ...
    reused_recording_entity_links=0, ...
    reused_recording_profile_assignments=0);
end

function value = profileVersionMap(plan)
mapping = table( ...
    plan.mapping_profile.profile_key, ...
    plan.mapping_profile.version_label, ...
    plan.mapping_profile.existing_profile_version_id, ...
    plan.mapping_profile.version_action, ...
    VariableNames=["profile_key", "version_label", ...
    "profile_version_id", "action"]);
linked = plan.profile_linkage.profiles(:, ...
    ["profile_key", "version_label", ...
    "existing_profile_version_id", "version_action"]);
linked.Properties.VariableNames = ...
    ["profile_key", "version_label", "profile_version_id", "action"];
value = [mapping; linked];
value = sortrows(value, ["profile_key", "version_label"]);
end
