function [links, evidence] = resolveRecordingLinks( ...
        conn, irRelationships, project, recordings, entities, entityRecords)
%RESOLVERECORDINGLINKS Derive minimal recording context from explicit IR edges.
%
% Canonical subject ancestors and members of a recording ancestor become
% participants. The immediate entity that contains a recording becomes one
% context link unless that entity is already a participant. No filesystem
% depth or project-native hierarchy name is interpreted here.

candidates = recordingLinkCandidates( ...
    irRelationships, recordings, entityRecords);
evidence = candidateEvidence(candidates);
links = candidateLinks(candidates, project, recordings, entities);
if isempty(links) || project.action ~= "reuse"
    if project.action == "conflict"
        links.action(links.action ~= "conflict") = "skip";
    end
    return
end

rows = fetch(conn, ...
    "SELECT rel.recording_entity_link_id, r.project_id, " + ...
    "rel.recording_id, rel.entity_id, rel.link_type, " + ...
    "CASE WHEN rel.role_label IS NULL OR length(rel.role_label) = 0 " + ...
    "THEN '<empty-role>' ELSE rel.role_label END AS role_label, " + ...
    "rel.role_label IS NULL OR length(rel.role_label) = 0 AS role_is_empty, " + ...
    "rel.start_time_s IS NULL AS start_is_null, " + ...
    "rel.end_time_s IS NULL AS end_is_null " + ...
    "FROM recording_entity_links rel " + ...
    "JOIN recordings r ON r.recording_id = rel.recording_id");
if isempty(rows)
    return
end
rows.role_label(double(rows.role_is_empty) == 1) = "";
rows = rows(double(rows.project_id) == project.existing_project_id, :);
for index = 1:height(links)
    if links.action(index) ~= "create" || ...
            isnan(links.recording_id(index)) || isnan(links.entity_id(index))
        continue
    end
    endpointRows = rows( ...
        double(rows.recording_id) == links.recording_id(index) & ...
        double(rows.entity_id) == links.entity_id(index), :);
    if isempty(endpointRows)
        continue
    end
    exact = endpointRows( ...
        string(endpointRows.link_type) == links.link_type(index) & ...
        string(endpointRows.role_label) == links.role_label(index) & ...
        double(endpointRows.start_is_null) == 1 & ...
        double(endpointRows.end_is_null) == 1, :);
    if ~isempty(exact)
        links.action(index) = "reuse";
        links.existing_recording_entity_link_id(index) = ...
            double(exact.recording_entity_link_id(1));
    else
        links.action(index) = "conflict";
        links.conflict_message(index) = ...
            "Existing recording/entity pair has incompatible link semantics.";
    end
end
end

function candidates = recordingLinkCandidates( ...
        irRelationships, recordings, entityRecords)
candidates = emptyCandidates();
entityRecordKeys = string(entityRecords.record_key);
for recordingIndex = 1:height(recordings)
    recordingKey = recordings.record_key(recordingIndex);
    sourceKey = recordings.source_key(recordingIndex);
    relationships = irRelationships( ...
        string(irRelationships.source_key) == sourceKey, :);
    ancestors = recordingAncestors(recordingKey, relationships);
    local = emptyCandidates();

    subjectIndexes = find( ...
        ismember(entityRecordKeys, ancestors) & ...
        string(entityRecords.canonical_level) == "subject" & ...
        string(entityRecords.record_scope) == "entity");
    for subjectIndex = subjectIndexes'
        [relationshipKey, mappingRule] = ancestorEvidence( ...
            entityRecords.record_key(subjectIndex), relationships, ancestors);
        local(end + 1, :) = candidateRow( ...
            recordingKey, sourceKey, entityRecords.entity_key(subjectIndex), ...
            "participant", entityRecords.role_label(subjectIndex), ...
            relationshipKey, mappingRule, "ancestor_subject"); %#ok<AGROW>
    end

    memberRows = relationships( ...
        string(relationships.canonical_relationship) == "has_member" & ...
        ismember(string(relationships.from_record_key), ancestors) & ...
        ismember(string(relationships.to_record_key), entityRecordKeys), :);
    for memberIndex = 1:height(memberRows)
        entityIndex = find(entityRecordKeys == ...
            string(memberRows.to_record_key(memberIndex)), 1);
        role = string(memberRows.role_label(memberIndex));
        if strlength(role) == 0
            role = entityRecords.role_label(entityIndex);
        end
        local(end + 1, :) = candidateRow( ...
            recordingKey, sourceKey, entityRecords.entity_key(entityIndex), ...
            "participant", role, ...
            string(memberRows.relationship_key(memberIndex)), ...
            string(memberRows.mapping_rule(memberIndex)), ...
            "ancestor_membership"); %#ok<AGROW>
    end

    participantEntityKeys = unique(local.entity_key( ...
        local.link_type == "participant"));
    directRows = relationships( ...
        string(relationships.to_record_key) == recordingKey & ...
        string(relationships.canonical_relationship) == "contains" & ...
        ismember(string(relationships.from_record_key), entityRecordKeys), :);
    for directIndex = 1:height(directRows)
        entityIndex = find(entityRecordKeys == ...
            string(directRows.from_record_key(directIndex)), 1);
        entityKey = entityRecords.entity_key(entityIndex);
        if ismember(entityKey, participantEntityKeys)
            continue
        end
        local(end + 1, :) = candidateRow( ...
            recordingKey, sourceKey, entityKey, "context", ...
            string(directRows.role_label(directIndex)), ...
            string(directRows.relationship_key(directIndex)), ...
            string(directRows.mapping_rule(directIndex)), ...
            "direct_context"); %#ok<AGROW>
    end
    candidates = [candidates; local]; %#ok<AGROW>
end
if ~isempty(candidates)
    candidates = sortrows(candidates, ...
        ["recording_link_key", "relationship_key", "evidence_kind"]);
end
end

function ancestors = recordingAncestors(recordingKey, relationships)
ancestors = string(recordingKey);
ancestors = ancestors(:);
frontier = ancestors;
while ~isempty(frontier)
    incoming = relationships( ...
        string(relationships.canonical_relationship) == "contains" & ...
        ismember(string(relationships.to_record_key), frontier), :);
    parents = unique(string(incoming.from_record_key), "stable");
    parents = parents(~ismember(parents, ancestors));
    if isempty(parents)
        break
    end
    ancestors = [ancestors; parents]; %#ok<AGROW>
    frontier = parents;
end
end

function [relationshipKey, mappingRule] = ancestorEvidence( ...
        recordKey, relationships, ancestors)
rows = relationships( ...
    string(relationships.from_record_key) == recordKey & ...
    string(relationships.canonical_relationship) == "contains" & ...
    ismember(string(relationships.to_record_key), ancestors), :);
if isempty(rows)
    relationshipKey = "";
    mappingRule = "";
else
    relationshipKey = string(rows.relationship_key(1));
    mappingRule = string(rows.mapping_rule(1));
end
end

function row = candidateRow(recordingKey, sourceKey, entityKey, ...
        linkType, roleLabel, relationshipKey, mappingRule, evidenceKind)
linkKey = recordingLinkKey(recordingKey, entityKey, linkType, roleLabel);
pairKey = string(recordingKey) + "|entity:" + string(entityKey);
row = {linkKey, pairKey, string(recordingKey), string(sourceKey), ...
    string(entityKey), string(linkType), string(roleLabel), ...
    string(relationshipKey), string(mappingRule), string(evidenceKind)};
end

function evidence = candidateEvidence(candidates)
evidence = emptyEvidence();
if isempty(candidates)
    return
end
evidence = candidates(:, ["recording_link_key", "source_key", ...
    "relationship_key", "mapping_rule", "evidence_kind"]);
evidence = unique(evidence, "rows", "stable");
evidence = sortrows(evidence, ...
    ["recording_link_key", "relationship_key", "evidence_kind"]);
end

function links = candidateLinks(candidates, project, recordings, entities)
links = emptyLinks();
if isempty(candidates)
    return
end
keys = unique(candidates.recording_link_key);
for index = 1:numel(keys)
    rows = candidates(candidates.recording_link_key == keys(index), :);
    recordingIndex = find(recordings.record_key == rows.recording_key(1), 1);
    entityIndex = find(entities.entity_key == rows.entity_key(1), 1);
    action = "create";
    if ismember(recordings.action(recordingIndex), ["conflict", "skip"]) || ...
            ismember(entities.action(entityIndex), ["conflict", "skip"]) || ...
            project.action == "conflict"
        action = "skip";
    end
    links(end + 1, :) = { ...
        keys(index), rows.pair_key(1), action, NaN, ...
        project.existing_project_id, rows.recording_key(1), ...
        recordings.existing_recording_id(recordingIndex), ...
        rows.entity_key(1), entities.existing_entity_id(entityIndex), ...
        rows.link_type(1), rows.role_label(1), height(rows), ""}; %#ok<AGROW>
end

pairs = unique(links.pair_key);
for pair = pairs'
    pairRows = links.pair_key == pair;
    if sum(pairRows) > 1
        links.action(pairRows) = "conflict";
        links.conflict_message(pairRows) = ...
            "The IR implies incompatible roles or link types for one recording/entity pair.";
    end
end
links = sortrows(links, "recording_link_key");
end

function key = recordingLinkKey(recordingKey, entityKey, linkType, roleLabel)
key = "recording_link:" + string(recordingKey) + "|entity:" + ...
    string(entityKey) + "|type:" + string(linkType) + "|role:" + ...
    string(roleLabel);
end

function value = emptyCandidates()
value = table( ...
    strings(0, 1), strings(0, 1), strings(0, 1), strings(0, 1), ...
    strings(0, 1), strings(0, 1), strings(0, 1), strings(0, 1), ...
    strings(0, 1), strings(0, 1), ...
    VariableNames=["recording_link_key", "pair_key", "recording_key", ...
    "source_key", "entity_key", "link_type", "role_label", ...
    "relationship_key", "mapping_rule", "evidence_kind"]);
end

function value = emptyEvidence()
value = table( ...
    strings(0, 1), strings(0, 1), strings(0, 1), strings(0, 1), ...
    strings(0, 1), ...
    VariableNames=["recording_link_key", "source_key", ...
    "relationship_key", "mapping_rule", "evidence_kind"]);
end

function value = emptyLinks()
value = table( ...
    strings(0, 1), strings(0, 1), strings(0, 1), NaN(0, 1), ...
    NaN(0, 1), strings(0, 1), NaN(0, 1), strings(0, 1), ...
    NaN(0, 1), strings(0, 1), strings(0, 1), NaN(0, 1), ...
    strings(0, 1), ...
    VariableNames=["recording_link_key", "pair_key", "action", ...
    "existing_recording_entity_link_id", "project_id", "recording_key", ...
    "recording_id", "entity_key", "entity_id", "link_type", "role_label", ...
    "evidence_count", "conflict_message"]);
end
