function [projectAssignments, recordingAssignments] = ...
        resolveProfileAssignments( ...
        conn, project, mappingProfile, linkage, recordings)
%RESOLVEPROFILEASSIGNMENTS Resolve the supported profile attachment rules.

projectAssignments = projectProposals(project, mappingProfile, linkage);
projectAssignments = resolveProjectAssignments( ...
    conn, projectAssignments, project, mappingProfile, linkage.profiles);
recordingAssignments = recordingProposals( ...
    project, linkage, recordings);
recordingAssignments = resolveRecordingAssignments( ...
    conn, recordingAssignments, project, recordings, linkage.profiles);
end

function assignments = projectProposals(project, mappingProfile, linkage)
assignments = emptyProjectAssignments();
assignments(end + 1, :) = { ...
    assignmentKey("project", project.project_key, ...
    "source_mapping_profile", mappingProfile.profile_key, ...
    mappingProfile.version_label), ...
    "create", project.existing_project_id, mappingProfile.profile_key, ...
    mappingProfile.version_label, ...
    mappingProfile.existing_profile_version_id, ...
    "source_mapping_profile", false, false, ""};

for index = 1:height(linkage.defaults)
    profileIndex = find(linkage.profiles.profile_key == ...
        linkage.defaults.profile_key(index), 1);
    assignments(end + 1, :) = { ...
        assignmentKey("project", project.project_key, ...
        linkage.defaults.project_assignment_role(index), ...
        linkage.defaults.profile_key(index), ...
        linkage.profiles.version_label(profileIndex)), ...
        "create", project.existing_project_id, ...
        linkage.defaults.profile_key(index), ...
        linkage.profiles.version_label(profileIndex), ...
        linkage.profiles.existing_profile_version_id(profileIndex), ...
        linkage.defaults.project_assignment_role(index), true, true, ""}; %#ok<AGROW>
end
assignments = sortrows(assignments, "assignment_key");
end

function assignments = recordingProposals(project, linkage, recordings)
assignments = emptyRecordingAssignments();
for recordingIndex = 1:height(recordings)
    for defaultIndex = 1:height(linkage.defaults)
        profileIndex = find(linkage.profiles.profile_key == ...
            linkage.defaults.profile_key(defaultIndex), 1);
        assignments(end + 1, :) = { ...
            assignmentKey("recording", recordings.record_key(recordingIndex), ...
            linkage.defaults.recording_assignment_role(defaultIndex), ...
            linkage.defaults.profile_key(defaultIndex), ...
            linkage.profiles.version_label(profileIndex)), ...
            "create", project.existing_project_id, ...
            recordings.record_key(recordingIndex), ...
            recordings.existing_recording_id(recordingIndex), ...
            linkage.defaults.profile_key(defaultIndex), ...
            linkage.profiles.version_label(profileIndex), ...
            linkage.profiles.existing_profile_version_id(profileIndex), ...
            linkage.defaults.recording_assignment_role(defaultIndex), ...
            linkage.defaults.inheritance_source(defaultIndex), true, ""}; %#ok<AGROW>
    end
end
if ~isempty(assignments)
    assignments = sortrows(assignments, "assignment_key");
end
end

function assignments = resolveProjectAssignments( ...
        conn, assignments, project, mappingProfile, linkedProfiles)
rows = table();
if project.action == "reuse"
    rows = fetch(conn, ...
        "SELECT project_id, profile_version_id, assignment_role, is_default " + ...
        "FROM project_profile_assignments");
end
for index = 1:height(assignments)
    versionAction = profileVersionAction( ...
        assignments.profile_key(index), mappingProfile, linkedProfiles);
    if project.action == "conflict" || ...
            ismember(versionAction, ["conflict", "skip"])
        assignments.action(index) = "skip";
        continue
    end
    if project.action ~= "reuse" || isempty(rows)
        continue
    end
    roleRows = rows( ...
        double(rows.project_id) == project.existing_project_id & ...
        string(rows.assignment_role) == assignments.assignment_role(index), :);
    assignments = classifyProjectAssignment( ...
        assignments, index, roleRows);
end
end

function assignments = classifyProjectAssignment(assignments, index, roleRows)
versionId = assignments.profile_version_id(index);
if isnan(versionId)
    if assignments.is_singular(index) && ~isempty(roleRows)
        assignments.action(index) = "conflict";
        assignments.conflict_message(index) = ...
            "Existing project default uses an incompatible profile version.";
    end
    return
end
exact = roleRows(double(roleRows.profile_version_id) == versionId, :);
if ~isempty(exact)
    compatible = height(exact) == 1 && ...
        double(exact.is_default(1)) == double(assignments.is_default(index));
    if assignments.is_singular(index)
        compatible = compatible && height(roleRows) == 1;
    end
    if compatible
        assignments.action(index) = "reuse";
    else
        assignments.action(index) = "conflict";
        assignments.conflict_message(index) = ...
            "Existing project profile assignment has incompatible default semantics.";
    end
elseif assignments.is_singular(index) && ~isempty(roleRows)
    assignments.action(index) = "conflict";
    assignments.conflict_message(index) = ...
        "Existing project default uses an incompatible profile version.";
end
end

function assignments = resolveRecordingAssignments( ...
        conn, assignments, project, recordings, linkedProfiles)
rows = table();
if project.action == "reuse" && ~isempty(assignments)
    rows = fetch(conn, ...
        "SELECT r.project_id, rpa.recording_id, rpa.profile_version_id, " + ...
        "rpa.assignment_role, rpa.inheritance_source " + ...
        "FROM recording_profile_assignments rpa " + ...
        "JOIN recordings r ON r.recording_id = rpa.recording_id");
end
for index = 1:height(assignments)
    recordingIndex = find(recordings.record_key == ...
        assignments.recording_key(index), 1);
    profileIndex = find(linkedProfiles.profile_key == ...
        assignments.profile_key(index), 1);
    recordingAction = recordings.action(recordingIndex);
    versionAction = linkedProfiles.version_action(profileIndex);
    if project.action == "conflict" || ...
            ismember(recordingAction, ["conflict", "skip"]) || ...
            ismember(versionAction, ["conflict", "skip"])
        assignments.action(index) = "skip";
        continue
    end
    if recordingAction ~= "reuse" || isempty(rows)
        continue
    end
    roleRows = rows( ...
        double(rows.project_id) == project.existing_project_id & ...
        double(rows.recording_id) == assignments.recording_id(index) & ...
        string(rows.assignment_role) == assignments.assignment_role(index), :);
    assignments = classifyRecordingAssignment(assignments, index, roleRows);
end
end

function assignments = classifyRecordingAssignment(assignments, index, roleRows)
versionId = assignments.profile_version_id(index);
if isnan(versionId)
    if assignments.is_singular(index) && ~isempty(roleRows)
        assignments.action(index) = "conflict";
        assignments.conflict_message(index) = ...
            "Existing recording role uses an incompatible profile version.";
    end
    return
end
exact = roleRows(double(roleRows.profile_version_id) == versionId, :);
if ~isempty(exact)
    compatible = height(exact) == 1 && ...
        string(exact.inheritance_source(1)) == ...
        assignments.inheritance_source(index);
    if assignments.is_singular(index)
        compatible = compatible && height(roleRows) == 1;
    end
    if compatible
        assignments.action(index) = "reuse";
    else
        assignments.action(index) = "conflict";
        assignments.conflict_message(index) = ...
            "Existing recording profile assignment has incompatible inheritance.";
    end
elseif assignments.is_singular(index) && ~isempty(roleRows)
    assignments.action(index) = "conflict";
    assignments.conflict_message(index) = ...
        "Existing recording role uses an incompatible profile version.";
end
end

function action = profileVersionAction(profileKey, mappingProfile, linkedProfiles)
if profileKey == mappingProfile.profile_key
    action = mappingProfile.version_action;
    return
end
index = find(linkedProfiles.profile_key == profileKey, 1);
action = linkedProfiles.version_action(index);
end

function key = assignmentKey(scope, ownerKey, role, profileKey, version)
key = scope + "_profile_assignment:" + string(ownerKey) + ...
    "|role:" + string(role) + "|profile:" + string(profileKey) + ...
    "@" + string(version);
end

function value = emptyProjectAssignments()
value = table( ...
    strings(0, 1), strings(0, 1), NaN(0, 1), strings(0, 1), ...
    strings(0, 1), NaN(0, 1), strings(0, 1), false(0, 1), ...
    false(0, 1), strings(0, 1), ...
    VariableNames=["assignment_key", "action", "project_id", ...
    "profile_key", "version_label", "profile_version_id", ...
    "assignment_role", "is_default", "is_singular", "conflict_message"]);
end

function value = emptyRecordingAssignments()
value = table( ...
    strings(0, 1), strings(0, 1), NaN(0, 1), strings(0, 1), ...
    NaN(0, 1), strings(0, 1), strings(0, 1), NaN(0, 1), ...
    strings(0, 1), strings(0, 1), false(0, 1), strings(0, 1), ...
    VariableNames=["assignment_key", "action", "project_id", ...
    "recording_key", "recording_id", "profile_key", "version_label", ...
    "profile_version_id", "assignment_role", "inheritance_source", ...
    "is_singular", "conflict_message"]);
end
