function [relationships, evidence, deferred] = resolveEntityRelationships( ...
        conn, irRelationships, project, entities, entityRecords)
%RESOLVEENTITYRELATIONSHIPS Resolve only edges whose endpoints are entities.

[evidence, deferred] = partitionRelationshipEvidence( ...
    irRelationships, entityRecords);
relationships = relationshipRows(evidence, project, entities);
if isempty(relationships) || project.action ~= "reuse"
    if project.action == "conflict"
        relationships.action(relationships.action ~= "conflict") = "skip";
    end
    return
end

rows = fetch(conn, "SELECT entity_relationship_id, project_id, " + ...
    "parent_entity_id, child_entity_id, relationship_type, " + ...
    "CASE WHEN role_label IS NULL OR length(role_label) = 0 " + ...
    "THEN '<empty-role>' ELSE role_label END AS role_label, " + ...
    "role_label IS NULL OR length(role_label) = 0 AS role_label_is_empty " + ...
    "FROM entity_relationships");
if isempty(rows)
    return
end
rows.role_label(double(rows.role_label_is_empty) == 1) = "";
rows = rows(double(rows.project_id) == project.existing_project_id, :);
for index = 1:height(relationships)
    if relationships.action(index) ~= "create" || ...
            isnan(relationships.parent_entity_id(index)) || ...
            isnan(relationships.child_entity_id(index))
        continue
    end
    endpointRows = rows( ...
        double(rows.parent_entity_id) == relationships.parent_entity_id(index) & ...
        double(rows.child_entity_id) == relationships.child_entity_id(index), :);
    if isempty(endpointRows)
        continue
    end
    exact = endpointRows( ...
        string(endpointRows.relationship_type) == ...
        relationships.relationship_type(index) & ...
        string(endpointRows.role_label) == relationships.role_label(index), :);
    if ~isempty(exact)
        relationships.action(index) = "reuse";
        relationships.existing_entity_relationship_id(index) = ...
            double(exact.entity_relationship_id(1));
    else
        relationships.action(index) = "conflict";
        relationships.conflict_message(index) = ...
            "Existing entity pair has incompatible relationship semantics.";
    end
end
end

function [evidence, deferred] = partitionRelationshipEvidence( ...
        irRelationships, entityRecords)
evidence = emptyEvidence();
deferred = emptyDeferred();
entityRecordKeys = string(entityRecords.record_key);
for index = 1:height(irRelationships)
    row = irRelationships(index, :);
    fromIndex = find(entityRecordKeys == string(row.from_record_key), 1);
    toIndex = find(entityRecordKeys == string(row.to_record_key), 1);
    if isempty(fromIndex) || isempty(toIndex)
        deferred(end + 1, :) = { ...
            string(row.relationship_key), string(row.source_key), ...
            string(row.from_record_key), string(row.to_record_key), ...
            string(row.native_relationship), ...
            string(row.canonical_relationship), string(row.role_label), ...
            string(row.mapping_rule), "non_entity_endpoint"}; %#ok<AGROW>
        continue
    end

    parentKey = entityRecords.entity_key(fromIndex);
    childKey = entityRecords.entity_key(toIndex);
    relationshipType = string(row.canonical_relationship);
    roleLabel = string(row.role_label);
    relationalKey = relationshipKey( ...
        parentKey, childKey, relationshipType, roleLabel);
    pairKey = parentKey + "|to:" + childKey;
    evidence(end + 1, :) = { ...
        string(row.relationship_key), relationalKey, pairKey, ...
        string(row.source_key), parentKey, childKey, ...
        string(row.native_relationship), relationshipType, roleLabel, ...
        string(row.mapping_rule)}; %#ok<AGROW>
end
if ~isempty(evidence)
    evidence = sortrows(evidence, "relationship_key");
end
if ~isempty(deferred)
    deferred = sortrows(deferred, "relationship_key");
end
end

function relationships = relationshipRows(evidence, project, entities)
relationships = emptyRelationships();
if isempty(evidence)
    return
end

keys = unique(evidence.entity_relationship_key);
for index = 1:numel(keys)
    rows = evidence(evidence.entity_relationship_key == keys(index), :);
    parentKey = rows.parent_entity_key(1);
    childKey = rows.child_entity_key(1);
    parentIndex = find(entities.entity_key == parentKey, 1);
    childIndex = find(entities.entity_key == childKey, 1);
    action = "create";
    conflictMessage = "";
    if parentKey == childKey
        action = "conflict";
        conflictMessage = "Entity relationship resolves to the same parent and child.";
    elseif entities.action(parentIndex) == "conflict" || ...
            entities.action(childIndex) == "conflict" || ...
            entities.action(parentIndex) == "skip" || ...
            entities.action(childIndex) == "skip"
        action = "skip";
    end

    pairRows = evidence(evidence.entity_pair_key == rows.entity_pair_key(1), :);
    if numel(unique(pairRows.entity_relationship_key)) > 1
        action = "conflict";
        conflictMessage = ...
            "The IR declares incompatible semantics for one entity pair.";
    end

    sourceLocator = "";
    mappingRule = "";
    if height(rows) == 1
        sourceLocator = rows.source_key(1);
        mappingRule = rows.mapping_rule(1);
    end
    relationships(end + 1, :) = { ...
        keys(index), action, NaN, project.existing_project_id, ...
        parentKey, entities.existing_entity_id(parentIndex), ...
        childKey, entities.existing_entity_id(childIndex), ...
        rows.relationship_type(1), rows.role_label(1), sourceLocator, ...
        mappingRule, height(rows), conflictMessage}; %#ok<AGROW>
end
relationships = sortrows(relationships, "relationship_key");
end

function key = relationshipKey(parentKey, childKey, type, role)
key = "entity_relationship:" + parentKey + "|to:" + childKey + ...
    "|type:" + type + "|role:" + role;
end

function value = emptyEvidence()
value = table( ...
    strings(0, 1), strings(0, 1), strings(0, 1), strings(0, 1), ...
    strings(0, 1), strings(0, 1), strings(0, 1), strings(0, 1), ...
    strings(0, 1), strings(0, 1), ...
    VariableNames=["relationship_key", "entity_relationship_key", ...
    "entity_pair_key", "source_key", "parent_entity_key", ...
    "child_entity_key", "native_relationship", "relationship_type", ...
    "role_label", "mapping_rule"]);
end

function value = emptyDeferred()
value = table( ...
    strings(0, 1), strings(0, 1), strings(0, 1), strings(0, 1), ...
    strings(0, 1), strings(0, 1), strings(0, 1), strings(0, 1), ...
    strings(0, 1), ...
    VariableNames=["relationship_key", "source_key", "from_record_key", ...
    "to_record_key", "native_relationship", "canonical_relationship", ...
    "role_label", "mapping_rule", "defer_reason"]);
end

function value = emptyRelationships()
value = table( ...
    strings(0, 1), strings(0, 1), NaN(0, 1), NaN(0, 1), ...
    strings(0, 1), NaN(0, 1), strings(0, 1), NaN(0, 1), ...
    strings(0, 1), strings(0, 1), strings(0, 1), strings(0, 1), ...
    NaN(0, 1), strings(0, 1), ...
    VariableNames=["relationship_key", "action", ...
    "existing_entity_relationship_id", "project_id", ...
    "parent_entity_key", "parent_entity_id", "child_entity_key", ...
    "child_entity_id", "relationship_type", "role_label", ...
    "source_locator", "mapping_rule_key", "evidence_count", ...
    "conflict_message"]);
end
