function mappingProfile = resolveMappingProfile(conn, profile)
%RESOLVEMAPPINGPROFILE Classify inherited built-in profile provenance.

mappingProfile = struct( ...
    profile_action="create", ...
    version_action="create", ...
    existing_profile_id=NaN, ...
    existing_profile_version_id=NaN, ...
    profile_key=string(profile.profile_key), ...
    profile_name=string(profile.profile_name), ...
    profile_kind="project_input", ...
    is_builtin=true, ...
    version_label=string(profile.profile_version), ...
    profile_schema_version=string(profile.profile_schema_version), ...
    content_format=string(profile.profile_content_format), ...
    content_uri=string(profile.profile_path), ...
    checksum_sha256=lower(string(profile.profile_checksum)), ...
    profile_conflict_message="", ...
    version_conflict_message="");

profileRows = fetch(conn, ...
    "SELECT profile_id, profile_key, profile_name, profile_kind, is_builtin " + ...
    "FROM config_profiles WHERE project_id IS NULL");
if isempty(profileRows)
    return
end
match = profileRows(string(profileRows.profile_key) == mappingProfile.profile_key, :);
if isempty(match)
    return
end

mappingProfile.existing_profile_id = double(match.profile_id(1));
if string(match.profile_name(1)) ~= mappingProfile.profile_name || ...
        string(match.profile_kind(1)) ~= mappingProfile.profile_kind || ...
        double(match.is_builtin(1)) ~= 1
    mappingProfile.profile_action = "conflict";
    mappingProfile.version_action = "skip";
    mappingProfile.profile_conflict_message = ...
        "Existing built-in profile identity has incompatible name, kind, or scope.";
    return
end
mappingProfile.profile_action = "reuse";

versionRows = fetch(conn, ...
    "SELECT profile_version_id, profile_id, version_label, " + ...
    "IFNULL(profile_schema_version, '') AS profile_schema_version, " + ...
    "content_format, content_uri, IFNULL(checksum_sha256, '') AS checksum_sha256, " + ...
    "is_snapshot FROM config_profile_versions");
if isempty(versionRows)
    return
end
versionMatch = versionRows( ...
    double(versionRows.profile_id) == mappingProfile.existing_profile_id & ...
    string(versionRows.version_label) == mappingProfile.version_label, :);
if isempty(versionMatch)
    return
end

mappingProfile.existing_profile_version_id = ...
    double(versionMatch.profile_version_id(1));
compatible = ...
    string(versionMatch.profile_schema_version(1)) == mappingProfile.profile_schema_version && ...
    string(versionMatch.content_format(1)) == mappingProfile.content_format && ...
    string(versionMatch.content_uri(1)) == mappingProfile.content_uri && ...
    lower(string(versionMatch.checksum_sha256(1))) == mappingProfile.checksum_sha256 && ...
    double(versionMatch.is_snapshot(1)) == 1;
if compatible
    mappingProfile.version_action = "reuse";
else
    mappingProfile.version_action = "conflict";
    mappingProfile.version_conflict_message = ...
        "Existing profile identity/version has incompatible provenance or checksum.";
end
end
