function [entities, entityRecords] = resolveEntities( ...
        conn, irRecords, project, entityTypes)
%RESOLVEENTITIES Deduplicate source-scoped records by type and native ID.

records = irRecords(ismember(string(irRecords.record_scope), ...
    ["entity", "membership"]), :);
records = sortrows(records, ["native_level", "native_identifier", "record_key"]);
identities = unique(records(:, ["native_level", "native_identifier"]), "rows");
identities = sortrows(identities, ["native_level", "native_identifier"]);
count = height(identities);
entityTypeKeys = "entity_type:" + string(identities.native_level);
entityKeys = entityTypeKeys + "|native_id:" + string(identities.native_identifier);
entities = table( ...
    entityKeys, repmat("create", count, 1), NaN(count, 1), ...
    repmat(project.existing_project_id, count, 1), entityTypeKeys, ...
    NaN(count, 1), string(identities.native_identifier), ...
    strings(count, 1), strings(count, 1), ...
    VariableNames=["entity_key", "action", "existing_entity_id", ...
    "project_id", "entity_type_key", "entity_type_id", "native_id", ...
    "display_label", "conflict_message"]);

existingRows = table();
if project.action == "reuse"
    existingRows = fetch(conn, "SELECT entity_id, project_id, entity_type_id, " + ...
        "native_id, IFNULL(display_label, '') AS display_label " + ...
        "FROM experimental_entities");
end
for index = 1:height(entities)
    typeIndex = find(entityTypes.entity_type_key == ...
        entities.entity_type_key(index), 1);
    typeAction = entityTypes.action(typeIndex);
    entities.entity_type_id(index) = ...
        entityTypes.existing_entity_type_id(typeIndex);
    if typeAction == "conflict" || typeAction == "skip" || ...
            project.action == "conflict"
        entities.action(index) = "skip";
        continue
    elseif typeAction ~= "reuse" || isempty(existingRows)
        continue
    end

    match = existingRows( ...
        double(existingRows.entity_type_id) == entities.entity_type_id(index) & ...
        string(existingRows.native_id) == entities.native_id(index), :);
    if isempty(match)
        continue
    end
    entities.existing_entity_id(index) = double(match.entity_id(1));
    if double(match.project_id(1)) == project.existing_project_id
        entities.action(index) = "reuse";
    else
        entities.action(index) = "conflict";
        entities.conflict_message(index) = ...
            "Existing entity natural identity belongs to a different project.";
    end
end

recordCount = height(records);
entityRecords = table( ...
    string(records.record_key), string(records.source_key), ...
    strings(recordCount, 1), string(records.native_level), ...
    string(records.canonical_level), string(records.native_identifier), ...
    NaN(recordCount, 1), ...
    strings(recordCount, 1), string(records.record_scope), ...
    string(records.role_label), string(records.mapping_rule), ...
    VariableNames=["record_key", "source_key", "entity_key", ...
    "native_level", "canonical_level", "native_identifier", ...
    "existing_entity_id", "action", "record_scope", "role_label", ...
    "mapping_rule"]);
for index = 1:recordCount
    entityKey = "entity_type:" + string(records.native_level(index)) + ...
        "|native_id:" + string(records.native_identifier(index));
    entityIndex = find(entities.entity_key == entityKey, 1);
    entityRecords.entity_key(index) = entityKey;
    entityRecords.existing_entity_id(index) = ...
        entities.existing_entity_id(entityIndex);
    entityRecords.action(index) = entities.action(entityIndex);
end
entityRecords = sortrows(entityRecords, "record_key");
end
