function result = usvsegPlanResult(plan)
%USVSEGPLANRESULT Build the inspectable USVSEG import manifest.
if plan.has_conflicts, status="conflict"; else, status="planned"; end
result=struct(status=status,committed=false, ...
    recording=struct(recording_id=plan.recording.recording_id,project_id=plan.recording.project_id, ...
        project_key=plan.recording.project_key,source_file_id=plan.recording.source_file_id, ...
        source_relative_path=plan.recording.source_relative_path,resolution_mode=plan.recording.resolution_mode), ...
    extractor=struct(extractor_id=plan.extractor.extractor_id,extractor_name=plan.extractor.extractor_name, ...
        declared_version=plan.extractor.run_version_label,run_extractor_version_id=plan.extractor.run_version_id, ...
        feature_extractor_version_id=plan.extractor.feature_version_id, ...
        feature_scope_version_label=plan.extractor.scope_version_label,version_action=plan.extractor.version_action), ...
    output_profile=struct(profile_key=plan.output_profile.profile_key,version_label=plan.output_profile.version_label, ...
        profile_version_id=plan.output_profile.profile_version_id,checksum_sha256=plan.output_profile.checksum_sha256, ...
        action=plan.output_profile.action), ...
    settings=struct(status=plan.settings_status,mode=plan.context.settings.mode, ...
        evidence_strength=plan.context.settings.evidence_strength,verified_run_configuration=false), ...
    extraction_run=struct(run_key=plan.run.run_key,run_label=plan.run.run_label,status=plan.run.status, ...
        action=plan.run.action,extraction_run_id=plan.run.existing_extraction_run_id,input_action=plan.run.input_action), ...
    event_population=struct(status="planned",source_row_count=plan.export.artifact.row_count, ...
        planned_detection_count=numel(plan.events.detections)), ...
    warnings=plan.warnings,conflicts=plan.conflicts,has_conflicts=plan.has_conflicts, ...
    curation=plan.events.curation,classification=plan.events.classification,validation=plan.validation);
result.artifacts=plan.artifacts(:,["role","artifact_type","native_artifact_type","is_native", ...
    "path_or_uri","checksum_sha256","checksum_status","action","existing_artifact_id","metadata_json"]);
result.artifacts.Properties.VariableNames{9}='artifact_id'; result.run_artifacts=plan.run_artifacts;
result.events=eventSummary(plan.events.detections); result.detections=plan.events.counts;
result.detections.planned=numel(plan.events.detections);
result.export=struct(source_key=plan.export.source_key,row_count=plan.export.artifact.row_count, ...
    relative_path=plan.export.artifact.relative_path,runtime_path=plan.export.artifact.runtime_path);
result.plan=plan;
end
function value=eventSummary(detections)
n=numel(detections); sourceRow=NaN(n,1); nativeEventId=strings(n,1); startTime=NaN(n,1); ...
    endTime=NaN(n,1); exportedDuration=NaN(n,1); measurementCount=NaN(n,1); ...
    unmappedValueCount=NaN(n,1); action=strings(n,1); detectionId=NaN(n,1);
for i=1:n
    d=detections{i}; sourceRow(i)=d.source_row; nativeEventId(i)=d.native_event_id; ...
        startTime(i)=d.start_time_s; endTime(i)=d.end_time_s; exportedDuration(i)=d.duration_s; ...
        measurementCount(i)=height(d.measurements); unmappedValueCount(i)=height(d.unmapped_values); ...
        action(i)=d.action; detectionId(i)=d.detection_id;
end
value=table(sourceRow,nativeEventId,startTime,endTime,exportedDuration,measurementCount, ...
    unmappedValueCount,action,detectionId,VariableNames=["source_row","native_event_id", ...
    "start_time_s","end_time_s","exported_duration_s","measurement_count", ...
    "unmapped_value_count","action","detection_id"]);
end
