function tests = test_attribution_candidates_evidence
%TEST_ATTRIBUTION_CANDIDATES_EVIDENCE Phase 4.5 multi-candidate evidence path.
tests = functiontests(localfunctions);
end

function setupOnce(testCase)
repoRoot = fileparts(fileparts(fileparts(mfilename("fullpath"))));
addpath(fullfile(repoRoot, "src"));
testCase.TestData.repoRoot = repoRoot;
end

function setup(testCase)
file = string(tempname) + ".sqlite";
conn = sqlite(char(file), "create");
vawlume.db.applySchema(conn, fullfile(testCase.TestData.repoRoot, ...
    "schema", "schema.sql"));
seedFixture(conn);
run = vawlume.attribution.createRun(conn, struct(recording_id=1), ...
    nominalRunSpec(), Apply=true);
testCase.TestData.conn = conn;
testCase.TestData.file = file;
testCase.TestData.run = run;
testCase.TestData.targetId = run.targets.attribution_target_id(1);
end

function teardown(testCase)
if isfield(testCase.TestData, "conn")
    close(testCase.TestData.conn);
end
if isfield(testCase.TestData, "file") && isfile(testCase.TestData.file)
    delete(testCase.TestData.file);
end
end

function testThreeCandidatesPersistAndNoneIsPrivileged(testCase)
conn = testCase.TestData.conn;
targetRef = struct(attribution_target_id=testCase.TestData.targetId);
candidates = nominalCandidates();

preview = vawlume.attribution.addCandidates(conn, targetRef, candidates);
verifyEqual(testCase, preview.status, "planned");
verifyFalse(testCase, preview.committed);
verifyEqual(testCase, countOf(conn, "attribution_candidates"), 0);

created = vawlume.attribution.addCandidates(conn, targetRef, ...
    candidates, Apply=true);
verifyEqual(testCase, created.status, "created");
verifyTrue(testCase, created.committed);
verifyEqual(testCase, created.applied_count, 3);
verifyFalse(testCase, isfield(created, "winner"));
verifyFalse(testCase, isfield(created, "best_caller"));

rows = fetch(conn, "SELECT entity_id, candidate_status, candidate_rank, " + ...
    "score, score_semantics, probability, probability_semantics, source_label " + ...
    "FROM attribution_candidates WHERE attribution_target_id=" + ...
    string(testCase.TestData.targetId) + " ORDER BY entity_id");
% Read all three rows and their values. A count would not prove that all are
% reachable through the public representation.
verifyEqual(testCase, double(rows.entity_id), [1; 2; 3]);
verifyEqual(testCase, string(rows.candidate_status), ...
    repmat("candidate", 3, 1));
verifyEqual(testCase, double(rows.candidate_rank), [1; 2; 2]);
verifyEqual(testCase, double(rows.score), [42.7; 10.0; 10.0], ...
    AbsTol=1e-12);
verifyEqual(testCase, string(rows.score_semantics), ...
    repmat(scoreSemantics(), 3, 1));
verifyEqual(testCase, double(rows.probability), [0.81; 0.12; 0.07], ...
    AbsTol=1e-12);
verifyEqual(testCase, string(rows.probability_semantics), ...
    repmat(probabilitySemantics(), 3, 1));
verifyEqual(testCase, string(rows.source_label), [" native A "; "B"; "C"]);
verifyEqual(testCase, countOf(conn, "attribution_decisions"), 0);
verifyEqual(testCase, countOf(conn, "attribution_decision_candidates"), 0);

runRows = fetch(conn, "SELECT atr.status AS attribution_status, " + ...
    "ar.status AS analysis_status FROM attribution_runs atr " + ...
    "JOIN analysis_runs ar ON ar.analysis_run_id=atr.analysis_run_id " + ...
    "WHERE atr.attribution_run_id=" + ...
    string(testCase.TestData.run.run.attribution_run_id));
verifyEqual(testCase, string(runRows.attribution_status), "planned");
verifyEqual(testCase, string(runRows.analysis_status), "started");
end

function testIdenticalCandidateBatchReusesWithoutWriting(testCase)
conn = testCase.TestData.conn;
ref = struct(attribution_target_id=testCase.TestData.targetId);
first = vawlume.attribution.addCandidates(conn, ref, ...
    nominalCandidates(), Apply=true);
before = candidateFingerprint(conn);
again = vawlume.attribution.addCandidates(conn, ref, ...
    nominalCandidates(), Apply=true);

verifyEqual(testCase, again.status, "reused");
verifyEqual(testCase, again.applied_count, 0);
verifyEqual(testCase, again.candidates.attribution_candidate_id, ...
    first.candidates.attribution_candidate_id);
verifyEqual(testCase, candidateFingerprint(conn), before);
end

function testPortableTargetReferenceResolvesOneEvent(testCase)
ref = struct(project_key="p1", run_key="phase45-run", detection_id=1);
candidate = table(1, VariableNames="entity_id");
result = vawlume.attribution.addCandidates( ...
    testCase.TestData.conn, ref, candidate);
verifyEqual(testCase, result.target.attribution_target_id, ...
    testCase.TestData.targetId);
verifyEqual(testCase, result.candidates.entity_id, 1);
verifyEqual(testCase, countOf(testCase.TestData.conn, ...
    "attribution_candidates"), 0);
end

function testChangedCandidateContentConflictsWithoutRewrite(testCase)
conn = testCase.TestData.conn;
vawlume.attribution.addCandidates(conn, targetRef(testCase), ...
    nominalCandidates(), Apply=true);
before = candidateFingerprint(conn);
changed = nominalCandidates();
changed.score(1) = 41.0;
result = vawlume.attribution.addCandidates(conn, targetRef(testCase), ...
    changed, Apply=true);
verifyEqual(testCase, result.status, "conflict");
verifyFalse(testCase, result.committed);
verifyTrue(testCase, result.has_conflicts);
verifyEqual(testCase, candidateFingerprint(conn), before);
end

function testScoreWithoutSemanticsIsRefusedForThatReason(testCase)
candidate = table(1, 0.5, VariableNames=["entity_id", "score"]);
verifyNamedError(testCase, @() vawlume.attribution.addCandidates( ...
    testCase.TestData.conn, targetRef(testCase), candidate), ...
    "vawlume:attribution:ScoreSemanticsRequired");
end

function testProbabilityWithoutSemanticsIsRefusedForThatReason(testCase)
candidate = table(1, 0.5, ...
    VariableNames=["entity_id", "probability"]);
verifyNamedError(testCase, @() vawlume.attribution.addCandidates( ...
    testCase.TestData.conn, targetRef(testCase), candidate), ...
    "vawlume:attribution:ProbabilitySemanticsRequired");
end

function testProbabilityOutsideUnitIntervalIsRefusedForThatReason(testCase)
candidate = table(1, 1.01, probabilitySemantics(), ...
    VariableNames=["entity_id", "probability", "probability_semantics"]);
verifyNamedError(testCase, @() vawlume.attribution.addCandidates( ...
    testCase.TestData.conn, targetRef(testCase), candidate), ...
    "vawlume:attribution:ProbabilityOutOfRange");
end

function testScoreAndProbabilityAreStoredWithoutConversion(testCase)
candidate = table(1, 42.7, scoreSemantics(), 0.23, ...
    probabilitySemantics(), VariableNames=["entity_id", "score", ...
    "score_semantics", "probability", "probability_semantics"]);
vawlume.attribution.addCandidates(testCase.TestData.conn, ...
    targetRef(testCase), candidate, Apply=true);
row = fetch(testCase.TestData.conn, ...
    "SELECT score, probability FROM attribution_candidates");
verifyEqual(testCase, double(row.score), 42.7, AbsTol=1e-12);
verifyEqual(testCase, double(row.probability), 0.23, AbsTol=1e-12);
verifyNotEqual(testCase, double(row.score), double(row.probability));
end

function testEqualScoresCannotReceiveAHiddenTiebreak(testCase)
candidates = nominalCandidates();
candidates.candidate_rank = [1; 2; 3];
verifyNamedError(testCase, @() vawlume.attribution.addCandidates( ...
    testCase.TestData.conn, targetRef(testCase), candidates), ...
    "vawlume:attribution:CandidateRankConflict");
end

function testCandidateOutsideSnapshottedParticipantsIsRefused(testCase)
candidate = table(4, VariableNames="entity_id");
verifyNamedError(testCase, @() vawlume.attribution.addCandidates( ...
    testCase.TestData.conn, targetRef(testCase), candidate), ...
    "vawlume:attribution:CandidateNotInRun");
end

function testCandidateBatchRollsBackAtomically(testCase)
conn = testCase.TestData.conn;
execute(conn, "CREATE TRIGGER trg_induced_candidate_failure " + ...
    "BEFORE INSERT ON attribution_candidates FOR EACH ROW " + ...
    "WHEN NEW.entity_id=3 BEGIN " + ...
    "SELECT RAISE(ABORT,'induced candidate failure'); END");

failedForReason = false;
try
    vawlume.attribution.addCandidates(conn, targetRef(testCase), ...
        nominalCandidates(), Apply=true);
catch exception
    failedForReason = contains(string(exception.message), ...
        "induced candidate failure");
end
verifyTrue(testCase, failedForReason);
verifyEqual(testCase, countOf(conn, "attribution_candidates"), 0);
verifyEqual(testCase, string(conn.AutoCommit), "on");
end

function testAllFourEvidenceDimensionsRemainSeparatelyReadable(testCase)
conn = testCase.TestData.conn;
created = vawlume.attribution.addCandidates(conn, targetRef(testCase), ...
    nominalCandidates(), Apply=true);
candidateId = created.candidates.attribution_candidate_id(1);
evidence = fourDimensions();

preview = vawlume.attribution.addEvidence(conn, ...
    struct(attribution_candidate_id=candidateId), evidence);
verifyEqual(testCase, preview.status, "planned");
verifyFalse(testCase, preview.committed);
verifyEqual(testCase, countOf(conn, "attribution_evidence"), 0);

stored = vawlume.attribution.addEvidence(conn, ...
    struct(attribution_candidate_id=candidateId), evidence, Apply=true);
verifyEqual(testCase, stored.status, "created");
verifyEqual(testCase, stored.applied_count, 4);

rows = fetch(conn, "SELECT evidence_dimension, evidence_kind, value_real, " + ...
    "value_units, value_semantics, IFNULL(alignment_run_id,-1) AS alignment_run_id, " + ...
    "IFNULL(source_file_id,-1) AS source_file_id, " + ...
    "IFNULL(mapping_profile_version_id,-1) AS mapping_profile_version_id, " + ...
    "source_locator FROM attribution_evidence ORDER BY attribution_evidence_id");
verifyEqual(testCase, string(rows.evidence_dimension), ...
    evidence.evidence_dimension);
verifyEqual(testCase, string(rows.evidence_kind), evidence.evidence_kind);
verifyEqual(testCase, double(rows.value_real), evidence.value_real, AbsTol=1e-12);
verifyEqual(testCase, string(rows.value_units), evidence.value_units);
verifyEqual(testCase, string(rows.value_semantics), evidence.value_semantics);
verifyEqual(testCase, double(rows.alignment_run_id), [1; -1; -1; -1]);
verifyEqual(testCase, double(rows.source_file_id), [-1; 3; -1; 1]);
verifyEqual(testCase, double(rows.mapping_profile_version_id), [-1; -1; 1; -1]);
verifyEqual(testCase, string(rows.source_locator), evidence.source_locator);
verifyEqual(testCase, unique(string(rows.evidence_dimension), "stable"), ...
    ["temporal_alignment"; "pose_localization"; ...
    "visual_identity"; "acoustic"]);
end

function testImportedCompositeIsStoredAsExternalEvidence(testCase)
row = table("imported_composite", "exported_joint_score", 0.73, ...
    "upstream_score", ...
    "External Caller 2.0 combined acoustic and pose inputs; uncalibrated; not a probability; VAWLUME did not recompute it", ...
    "caller.csv#row=8", VariableNames=["evidence_dimension", ...
    "evidence_kind", "value_real", "value_units", "value_semantics", ...
    "source_locator"]);
result = vawlume.attribution.addEvidence(testCase.TestData.conn, ...
    targetRef(testCase), row, Apply=true);
verifyTrue(testCase, isnan(result.evidence.attribution_candidate_id));
stored = fetch(testCase.TestData.conn, ...
    "SELECT evidence_dimension, value_real, value_semantics, " + ...
    "CASE WHEN attribution_candidate_id IS NULL THEN 1 ELSE 0 END AS target_level " + ...
    "FROM attribution_evidence");
verifyEqual(testCase, string(stored.evidence_dimension), "imported_composite");
verifyEqual(testCase, double(stored.value_real), 0.73, AbsTol=1e-12);
verifyTrue(testCase, contains(string(stored.value_semantics), ...
    "VAWLUME did not recompute"));
verifyEqual(testCase, double(stored.target_level), 1);
end

function testEvidenceWithoutSemanticsIsRefused(testCase)
row = table("acoustic", "channel_ratio", 0.42, "ratio", ...
    "audio.wav#channel=1", VariableNames=["evidence_dimension", ...
    "evidence_kind", "value_real", "value_units", "source_locator"]);
verifyNamedError(testCase, @() vawlume.attribution.addEvidence( ...
    testCase.TestData.conn, targetRef(testCase), row), ...
    "vawlume:attribution:EvidenceSemanticsRequired");
end

function testEvidenceBatchRollsBackAtomically(testCase)
conn = testCase.TestData.conn;
created = vawlume.attribution.addCandidates(conn, targetRef(testCase), ...
    nominalCandidates(), Apply=true);
candidateId = created.candidates.attribution_candidate_id(1);
execute(conn, "CREATE TRIGGER trg_induced_evidence_failure " + ...
    "BEFORE INSERT ON attribution_evidence FOR EACH ROW " + ...
    "WHEN NEW.evidence_dimension='acoustic' BEGIN " + ...
    "SELECT RAISE(ABORT,'induced evidence failure'); END");

failedForReason = false;
try
    vawlume.attribution.addEvidence(conn, ...
        struct(attribution_candidate_id=candidateId), ...
        fourDimensions(), Apply=true);
catch exception
    failedForReason = contains(string(exception.message), ...
        "induced evidence failure");
end
verifyTrue(testCase, failedForReason);
verifyEqual(testCase, countOf(conn, "attribution_evidence"), 0);
verifyEqual(testCase, string(conn.AutoCommit), "on");
end

function testNoAttributionFunctionCombinesEvidenceDimensions(testCase)
source = attributionSourceText(testCase.TestData.repoRoot);
verifyEmpty(testCase, combinedDimensionArithmetic(source));

% Negative control: exercise the same scanner against a temporary in-memory
% mutation. If this assertion fails, the real-tree guard matched nothing only
% because the scanner itself is inert.
mutated = source + newline + ...
    "combined_value = temporal_alignment + pose_localization;";
verifyNotEmpty(testCase, combinedDimensionArithmetic(mutated));
end

% ---------------------------------------------------------------- helpers ---

function ref = targetRef(testCase)
ref = struct(attribution_target_id=testCase.TestData.targetId);
end

function candidates = nominalCandidates()
candidates = table([1; 2; 3], [1; 2; 2], [42.7; 10.0; 10.0], ...
    repmat(scoreSemantics(), 3, 1), [0.81; 0.12; 0.07], ...
    repmat(probabilitySemantics(), 3, 1), [" native A "; "B"; "C"], ...
    VariableNames=["entity_id", "candidate_rank", "score", ...
    "score_semantics", "probability", "probability_semantics", ...
    "source_label"]);
end

function value = scoreSemantics()
value = "External Caller 2.0 raw margin; producer=External Caller 2.0; " + ...
    "range=unbounded; uncalibrated; higher is better; not a probability";
end

function value = probabilitySemantics()
value = "Exporter-labelled caller probability; producer=External Caller 2.0; " + ...
    "range=[0,1]; calibration=exporter-claimed and not validated by VAWLUME";
end

function evidence = fourDimensions()
evidence = table( ...
    ["temporal_alignment"; "pose_localization"; ...
     "visual_identity"; "acoustic"], ...
    ["propagated_bound"; "keypoint_confidence"; ...
     "reidentification_similarity"; "channel_rms_ratio"], ...
    [0.002; 0.73; 0.55; 0.42], ...
    ["s"; "upstream_score"; "cosine_similarity"; "ratio"], ...
    ["Largest contributing anchor uncertainty on the reference clock; uncalibrated; not a confidence interval, standard error, or probability"; ...
     "Tracker-exported keypoint localization confidence; producer=Tracker X; range=[0,1]; uncalibrated; not caller probability"; ...
     "Appearance-embedding cosine similarity; producer=ReID X; range=[-1,1]; uncalibrated; not caller probability"; ...
     "Native channel 1 to channel 2 RMS ratio; producer=measurement export; range=nonnegative; uncalibrated; not caller probability"], ...
    [1; NaN; NaN; NaN], [-1; 3; -1; 1], [-1; -1; 1; -1], ...
    ["alignment_run:1"; "tracking.csv#frame=120"; ...
     "reid.json#track=A"; "audio.wav#samples=1000:2000"], ...
    VariableNames=["evidence_dimension", "evidence_kind", "value_real", ...
    "value_units", "value_semantics", "alignment_run_id", ...
    "source_file_id", "mapping_profile_version_id", "source_locator"]);
evidence.source_file_id(evidence.source_file_id < 0) = NaN;
evidence.mapping_profile_version_id( ...
    evidence.mapping_profile_version_id < 0) = NaN;
end

function verifyNamedError(testCase, operation, identifier)
try
    operation();
    verifyFail(testCase, "Expected refusal " + identifier + ".");
catch exception
    verifyEqual(testCase, string(exception.identifier), identifier, ...
        "Refused, but not for its own reason: " + string(exception.message));
end
end

function value = countOf(conn, tableName)
row = fetch(conn, "SELECT COUNT(*) AS n FROM " + tableName);
value = double(row.n(1));
end

function value = candidateFingerprint(conn)
rows = fetch(conn, "SELECT attribution_candidate_id, entity_id, " + ...
    "candidate_rank, score, probability FROM attribution_candidates " + ...
    "ORDER BY attribution_candidate_id");
value = strjoin(compose("%d|%d|%d|%.17g|%.17g", ...
    double(rows.attribution_candidate_id), double(rows.entity_id), ...
    double(rows.candidate_rank), double(rows.score), ...
    double(rows.probability)), ";");
end

function text = attributionSourceText(repoRoot)
files = dir(fullfile(repoRoot, "src", "+vawlume", "+attribution", ...
    "**", "*.m"));
text = "";
for index = 1:numel(files)
    text = text + newline + ...
        string(fileread(fullfile(files(index).folder, files(index).name)));
end
end

function offenders = combinedDimensionArithmetic(text)
dimensions = ["temporal_alignment", "pose_localization", ...
    "visual_identity", "acoustic"];
lines = splitlines(text);
offenders = strings(0, 1);
for index = 1:numel(lines)
    code = regexprep(lines(index), "%.*$", "");
    named = dimensions(arrayfun(@(dimension) ...
        contains(code, dimension), dimensions));
    hasArithmetic = ~isempty(regexp(char(code), ...
        '[A-Za-z0-9_)]\s*[+*/-]\s*[A-Za-z_(]', 'once'));
    if numel(named) >= 2 && hasArithmetic
        offenders(end + 1, 1) = strtrim(code); %#ok<AGROW>
    end
end
end

function spec = nominalRunSpec()
spec = struct(run_key="phase45-run", attribution_path="imported", ...
    method="External Caller 2.0", settings_profile_version_id=1, ...
    target_set=struct(detection_ids=1), ...
    participating_entity_ids=[1 2 3], ...
    sources=struct(source_file_ids=2), ...
    notes="Synthetic Phase 4.5 fixture.");
end

function seedFixture(conn)
execute(conn, "INSERT INTO projects(project_id,project_key,project_name) " + ...
    "VALUES(1,'p1','Project 1')");
execute(conn, "INSERT INTO source_files(source_file_id,project_id,file_role," + ...
    "path_or_uri,relative_path) VALUES" + ...
    "(1,1,'recording_audio','audio.wav','audio.wav')," + ...
    "(2,1,'attribution_output','caller.csv','caller.csv')," + ...
    "(3,1,'tracking_output','tracking.csv','tracking.csv')");
execute(conn, "INSERT INTO recordings(recording_id,project_id,source_file_id," + ...
    "native_recording_id) VALUES(1,1,1,'R1')");
execute(conn, "INSERT INTO entity_types(entity_type_id,project_id,native_name," + ...
    "is_subject_like) VALUES(1,1,'subject',1)");
execute(conn, "INSERT INTO experimental_entities(entity_id,project_id," + ...
    "entity_type_id,native_id) VALUES" + ...
    "(1,1,1,'A'),(2,1,1,'B'),(3,1,1,'C'),(4,1,1,'D')");
execute(conn, "INSERT INTO recording_entity_links(recording_entity_link_id," + ...
    "recording_id,entity_id,link_type) VALUES" + ...
    "(1,1,1,'participant'),(2,1,2,'participant'),(3,1,3,'participant')");
execute(conn, "INSERT INTO config_profiles(profile_id,project_id,profile_key," + ...
    "profile_name,profile_kind) VALUES" + ...
    "(1,1,'caller-input','Caller input mapping','attribution_input_mapping')");
execute(conn, "INSERT INTO config_profile_versions(profile_version_id,profile_id," + ...
    "version_label,content_format,content_uri,checksum_sha256,is_snapshot) VALUES" + ...
    "(1,1,'1.0.0','json','config/caller.json'," + ...
    "'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',1)");
execute(conn, "INSERT INTO extractors(extractor_id,extractor_key,extractor_name) " + ...
    "VALUES(1,'ds','DeepSqueak')");
execute(conn, "INSERT INTO extractor_versions(extractor_version_id,extractor_id," + ...
    "version_label) VALUES(1,1,'v1')");
execute(conn, "INSERT INTO extraction_runs(extraction_run_id,project_id," + ...
    "extractor_version_id,run_key) VALUES(1,1,1,'det-r1')");
execute(conn, "INSERT INTO extraction_run_inputs(extraction_run_id,recording_id) " + ...
    "VALUES(1,1)");
execute(conn, "INSERT INTO detections(detection_id,extraction_run_id,recording_id," + ...
    "start_time_s,end_time_s) VALUES(1,1,1,1.0,1.1)");

execute(conn, "INSERT INTO timebases(timebase_id,project_id,recording_id," + ...
    "timebase_name,timebase_kind,is_recording_native,native_unit) VALUES" + ...
    "(1,1,1,'audio','recording_audio',1,'s')," + ...
    "(2,1,1,'video','external_clock',0,'s')");
execute(conn, "INSERT INTO analysis_runs(analysis_run_id,project_id,run_type," + ...
    "run_key,status) VALUES(10,1,'temporal_alignment','alignment-r1','completed')");
execute(conn, "INSERT INTO alignment_sets(alignment_set_id,analysis_run_id," + ...
    "recording_id,reference_timebase_id,alignment_set_key,status) " + ...
    "VALUES(1,10,1,1,'align-r1','fitted')");
execute(conn, "INSERT INTO time_alignment_runs(alignment_run_id,alignment_set_id," + ...
    "source_timebase_id,target_timebase_id,method,status) " + ...
    "VALUES(1,1,2,1,'affine','estimated')");
end
