function tests = test_project_intake_transactions
tests = functiontests({ ...
    @testLateProfileAssignmentFailureRollsBackWholeIntake, ...
    @testWarningsCommitWithAuditStatus, ...
    @testDyadicRecordingProvenanceReadBack, ...
    @testTrackedDeviceSetupProvenanceReadBack});
end

function testLateProfileAssignmentFailureRollsBackWholeIntake(testCase)
[conn, dbFile, repoRoot] = createDisposableDatabase();
cleanupDb = onCleanup(@() cleanupDatabase(conn, dbFile));
[ir, sourceRoot] = parsedIR(repoRoot, ...
    "example.project.mouse_courtship.folder_driven", ...
    fullfile("control", "mouse_001", "baseline", ...
    "001_baseline_1.wav"));
cleanupRoot = onCleanup(@() removeTree(sourceRoot));
execute(conn, "CREATE TRIGGER force_profile_assignment_failure " + ...
    "BEFORE INSERT ON recording_profile_assignments BEGIN " + ...
    "SELECT RAISE(ABORT, 'forced profile assignment failure'); END");

didThrow = false;
try
    vawlume.ingest.project(conn, ir, projectSpec("rollback"), ...
        Apply=true, ProfileLinkagePath=linkagePath(repoRoot), ...
        RepoRoot=repoRoot);
catch exception
    didThrow = true;
    verifyTrue(testCase, contains(string(exception.message), ...
        "forced profile assignment failure"));
end

verifyTrue(testCase, didThrow);
verifyEqual(testCase, string(conn.AutoCommit), "on");
verifyEqual(testCase, targetCounts(conn), zeroTargetCounts());
verifyEqual(testCase, height(fetch(conn, "PRAGMA foreign_key_check")), 0);

clear cleanupRoot cleanupDb
rmpath(fullfile(repoRoot, "src"));
end

function testWarningsCommitWithAuditStatus(testCase)
[conn, dbFile, repoRoot] = createDisposableDatabase();
cleanupDb = onCleanup(@() cleanupDatabase(conn, dbFile));
[ir, sourceRoot] = parsedIR(repoRoot, ...
    "example.project.rat_self_admin.filename_driven", ...
    "OXY_PR_R03_SA07_001.wav");
cleanupRoot = onCleanup(@() removeTree(sourceRoot));

result = vawlume.ingest.project(conn, ir, projectSpec("warnings"), ...
    Apply=true);
run = fetch(conn, ...
    "SELECT status FROM ingestion_runs WHERE ingestion_run_id = " + ...
    string(result.ingestion_run_id));
file = fetch(conn, ...
    "SELECT parse_status, warning_count, error_count, parser_message " + ...
    "FROM ingestion_files WHERE ingestion_run_id = " + ...
    string(result.ingestion_run_id));

verifyEqual(testCase, result.status, "completed_with_warnings");
verifyTrue(testCase, result.committed);
verifyGreaterThanOrEqual(testCase, height(result.warnings), 1);
verifyEqual(testCase, string(run.status), "completed_with_warnings");
verifyEqual(testCase, string(file.parse_status), "parsed_with_warnings");
verifyGreaterThanOrEqual(testCase, double(file.warning_count), 1);
verifyEqual(testCase, double(file.error_count), 0);
verifyGreaterThan(testCase, strlength(string(file.parser_message)), 0);
verifyEqual(testCase, height(fetch(conn, "PRAGMA foreign_key_check")), 0);

clear cleanupRoot cleanupDb
rmpath(fullfile(repoRoot, "src"));
end

function testDyadicRecordingProvenanceReadBack(testCase)
[conn, dbFile, repoRoot] = createDisposableDatabase();
cleanupDb = onCleanup(@() cleanupDatabase(conn, dbFile));
relativeNative = fullfile("cohort_01", "dyad_004", ...
    "D004_M012_F031_courtship.wav");
relativePath = replace(string(relativeNative), string(filesep), "/");
[ir, sourceRoot] = parsedIR(repoRoot, ...
    "example.project.social_dyad.multi_subject", relativeNative);
cleanupRoot = onCleanup(@() removeTree(sourceRoot));

result = vawlume.ingest.project(conn, ir, projectSpec("dyadic"), ...
    Apply=true);
trace = fetch(conn, ...
    "SELECT r.recording_id, sf.relative_path, p.project_key, " + ...
    "cp.profile_key AS mapping_profile_key, " + ...
    "cpv.version_label AS mapping_version, " + ...
    "cpv.checksum_sha256 AS mapping_checksum, " + ...
    "ir.ingestion_run_id, ir.status AS ingestion_status, " + ...
    "rel.link_type, CASE WHEN rel.role_label IS NULL THEN '<empty>' " + ...
    "ELSE rel.role_label END AS role_label, et.native_name AS entity_type, " + ...
    "ee.native_id AS entity_native_id " + ...
    "FROM recordings r " + ...
    "JOIN source_files sf ON sf.source_file_id = r.source_file_id " + ...
    "JOIN projects p ON p.project_id = r.project_id " + ...
    "JOIN recording_entity_links rel ON rel.recording_id = r.recording_id " + ...
    "JOIN experimental_entities ee ON ee.entity_id = rel.entity_id " + ...
    "JOIN entity_types et ON et.entity_type_id = ee.entity_type_id " + ...
    "JOIN ingestion_files inf ON inf.source_file_id = sf.source_file_id " + ...
    "JOIN ingestion_runs ir ON ir.ingestion_run_id = inf.ingestion_run_id " + ...
    "JOIN config_profile_versions cpv ON cpv.profile_version_id = " + ...
    "ir.mapping_profile_version_id " + ...
    "JOIN config_profiles cp ON cp.profile_id = cpv.profile_id " + ...
    "WHERE ir.ingestion_run_id = " + string(result.ingestion_run_id) + ...
    " ORDER BY rel.link_type, role_label, ee.native_id");

verifyEqual(testCase, height(trace), 3);
verifyEqual(testCase, unique(string(trace.relative_path)), relativePath);
verifyEqual(testCase, unique(string(trace.project_key)), ...
    projectSpec("dyadic").project_key);
verifyEqual(testCase, unique(string(trace.mapping_profile_key)), ...
    "example.project.social_dyad.multi_subject");
verifyEqual(testCase, unique(string(trace.mapping_version)), "0.1.0");
verifyEqual(testCase, unique(string(trace.mapping_checksum)), ...
    "2a89d9de5e2e2d0da9d4c1f02dd487875c93aa989fd26cac2c2b72063165aa43");
verifyEqual(testCase, unique(double(trace.ingestion_run_id)), ...
    result.ingestion_run_id);
verifyEqual(testCase, unique(string(trace.ingestion_status)), "completed");
verifyEqual(testCase, string(trace.link_type), ...
    ["context"; "participant"; "participant"]);
verifyEqual(testCase, string(trace.role_label), ...
    ["<empty>"; "female_partner"; "male_partner"]);
verifyEqual(testCase, string(trace.entity_type), ...
    ["session"; "animal"; "animal"]);
verifyEqual(testCase, string(trace.entity_native_id), ...
    ["courtship"; "F031"; "M012"]);

memberships = fetch(conn, ...
    "SELECT er.role_label, child.native_id " + ...
    "FROM entity_relationships er " + ...
    "JOIN experimental_entities child ON child.entity_id = " + ...
    "er.child_entity_id " + ...
    "WHERE er.relationship_type = 'has_member' ORDER BY er.role_label");
verifyEqual(testCase, string(memberships.role_label), ...
    ["female_partner"; "male_partner"]);
verifyEqual(testCase, string(memberships.native_id), ["F031"; "M012"]);
verifyEqual(testCase, scalar(conn, ...
    "SELECT COUNT(*) AS n FROM entity_relationships WHERE ingestion_run_id = " + ...
    string(result.ingestion_run_id)), 5);
verifyEqual(testCase, height(fetch(conn, "PRAGMA foreign_key_check")), 0);

clear cleanupRoot cleanupDb
rmpath(fullfile(repoRoot, "src"));
end

function testTrackedDeviceSetupProvenanceReadBack(testCase)
[conn, dbFile, repoRoot] = createDisposableDatabase();
cleanupDb = onCleanup(@() cleanupDatabase(conn, dbFile));
[ir, sourceRoot] = parsedIR(repoRoot, ...
    "example.project.mouse_courtship.folder_driven", ...
    fullfile("control", "mouse_001", "baseline", ...
    "001_baseline_1.wav"));
cleanupRoot = onCleanup(@() removeTree(sourceRoot));

result = vawlume.ingest.project(conn, ir, projectSpec("linked"), ...
    Apply=true, ProfileLinkagePath=linkagePath(repoRoot), ...
    RepoRoot=repoRoot);
linked = fetch(conn, ...
    "SELECT cp.profile_key, cp.profile_kind, cpv.version_label, " + ...
    "cpv.profile_schema_version, cpv.content_uri, cpv.checksum_sha256, " + ...
    "ppa.assignment_role AS project_role, " + ...
    "rpa.assignment_role AS recording_role, rpa.inheritance_source " + ...
    "FROM recordings r " + ...
    "JOIN recording_profile_assignments rpa ON rpa.recording_id = " + ...
    "r.recording_id " + ...
    "JOIN config_profile_versions cpv ON cpv.profile_version_id = " + ...
    "rpa.profile_version_id " + ...
    "JOIN config_profiles cp ON cp.profile_id = cpv.profile_id " + ...
    "JOIN project_profile_assignments ppa ON ppa.project_id = r.project_id " + ...
    "AND ppa.profile_version_id = cpv.profile_version_id " + ...
    "ORDER BY cp.profile_key");
mapping = fetch(conn, ...
    "SELECT cp.profile_key, cpv.version_label, cpv.checksum_sha256, " + ...
    "ppa.assignment_role " + ...
    "FROM projects p " + ...
    "JOIN project_profile_assignments ppa ON ppa.project_id = p.project_id " + ...
    "JOIN config_profile_versions cpv ON cpv.profile_version_id = " + ...
    "ppa.profile_version_id " + ...
    "JOIN config_profiles cp ON cp.profile_id = cpv.profile_id " + ...
    "WHERE p.project_id = " + string(result.project_id) + ...
    " AND ppa.assignment_role = 'source_mapping_profile'");

verifyEqual(testCase, string(linked.profile_key), [ ...
    "example.device.ultrasonic_usb_primary"; ...
    "example.setup.mouse_courtship_chamber"]);
verifyEqual(testCase, string(linked.profile_kind), ...
    ["recording_device"; "experimental_setup"]);
verifyEqual(testCase, string(linked.version_label), ["1"; "1"]);
verifyEqual(testCase, string(linked.project_role), ...
    ["default_recording_device"; "default_experimental_setup"]);
verifyEqual(testCase, string(linked.recording_role), ...
    ["recording_device"; "experimental_setup"]);
verifyEqual(testCase, string(linked.inheritance_source), ...
    ["project_default"; "project_default"]);
verifyEqual(testCase, string(linked.checksum_sha256), [ ...
    "6bcb1ca9c07596619b56ee50fdce1ed6349100327a53622e7322c01d3c009ede"; ...
    "21b0b0a915078e437998232dda9683784744876632bedbb4b499bc3359adcd8e"]);
verifyEqual(testCase, string(mapping.profile_key), ...
    "example.project.mouse_courtship.folder_driven");
verifyEqual(testCase, string(mapping.version_label), "0.1.0");
verifyEqual(testCase, string(mapping.checksum_sha256), ...
    "2a89d9de5e2e2d0da9d4c1f02dd487875c93aa989fd26cac2c2b72063165aa43");
verifyEqual(testCase, string(mapping.assignment_role), ...
    "source_mapping_profile");
verifyEqual(testCase, height(fetch(conn, "PRAGMA foreign_key_check")), 0);

clear cleanupRoot cleanupDb
rmpath(fullfile(repoRoot, "src"));
end

function [ir, root] = parsedIR(repoRoot, profileId, relativePath)
root = string(tempname);
mkdir(root);
touchFile(fullfile(root, relativePath));
ir = vawlume.source_mapping.parse(projectProfilePath(repoRoot), root, ...
    ProfileId=profileId, RepoRoot=repoRoot);
end

function value = projectSpec(suffix)
value = struct(project_key="transaction_test_" + string(suffix), ...
    project_name="Transaction test " + string(suffix), ...
    description="Pass 5 transaction/provenance integration case.");
end

function value = targetCounts(conn)
value = struct( ...
    projects=scalar(conn, "SELECT COUNT(*) AS n FROM projects"), ...
    config_profiles=scalar(conn, ...
    "SELECT COUNT(*) AS n FROM config_profiles"), ...
    config_profile_versions=scalar(conn, ...
    "SELECT COUNT(*) AS n FROM config_profile_versions"), ...
    project_profile_assignments=scalar(conn, ...
    "SELECT COUNT(*) AS n FROM project_profile_assignments"), ...
    ingestion_runs=scalar(conn, ...
    "SELECT COUNT(*) AS n FROM ingestion_runs"), ...
    ingestion_files=scalar(conn, ...
    "SELECT COUNT(*) AS n FROM ingestion_files"), ...
    source_files=scalar(conn, "SELECT COUNT(*) AS n FROM source_files"), ...
    entity_types=scalar(conn, "SELECT COUNT(*) AS n FROM entity_types"), ...
    entities=scalar(conn, ...
    "SELECT COUNT(*) AS n FROM experimental_entities"), ...
    entity_relationships=scalar(conn, ...
    "SELECT COUNT(*) AS n FROM entity_relationships"), ...
    recordings=scalar(conn, "SELECT COUNT(*) AS n FROM recordings"), ...
    recording_entity_links=scalar(conn, ...
    "SELECT COUNT(*) AS n FROM recording_entity_links"), ...
    recording_profile_assignments=scalar(conn, ...
    "SELECT COUNT(*) AS n FROM recording_profile_assignments"));
end

function value = zeroTargetCounts()
value = struct( ...
    projects=0, config_profiles=0, config_profile_versions=0, ...
    project_profile_assignments=0, ingestion_runs=0, ingestion_files=0, ...
    source_files=0, entity_types=0, entities=0, entity_relationships=0, ...
    recordings=0, recording_entity_links=0, ...
    recording_profile_assignments=0);
end

function [conn, dbFile, repoRoot] = createDisposableDatabase()
repoRoot = repoRootForTest();
addpath(fullfile(repoRoot, "src"));
dbFile = string(tempname) + ".sqlite";
conn = sqlite(char(dbFile), "create");
vawlume.db.applySchema(conn, fullfile(repoRoot, "schema", "schema.sql"));
end

function value = scalar(conn, sql)
rows = fetch(conn, sql);
value = double(rows.n(1));
end

function cleanupDatabase(conn, dbFile)
if isopen(conn)
    close(conn);
end
deleteIfExists(dbFile);
deleteIfExists(dbFile + "-journal");
deleteIfExists(dbFile + "-wal");
deleteIfExists(dbFile + "-shm");
end

function touchFile(path)
parent = string(fileparts(path));
if ~isfolder(parent)
    mkdir(parent);
end
fileId = fopen(path, "w");
assert(fileId ~= -1, "Test fixture file could not be created.");
cleanupFile = onCleanup(@() fclose(fileId));
fwrite(fileId, uint8([]));
clear cleanupFile
end

function removeTree(root)
if isfolder(root)
    rmdir(root, "s");
end
end

function deleteIfExists(path)
if isfile(path)
    delete(path);
end
end

function path = linkagePath(repoRoot)
path = fullfile(repoRoot, "config", "04_examples", ...
    "profile_linkage_example.json");
end

function path = projectProfilePath(repoRoot)
path = fullfile(repoRoot, "config", "01_mapping_profiles", ...
    "project_inputs", "project_input_source_mapping_examples.json");
end

function repoRoot = repoRootForTest()
repoRoot = fileparts(fileparts(fileparts(mfilename("fullpath"))));
end
