function tests = test_acoustic_reference_registration
tests = functiontests({ ...
    @testRegistersAndReadsToneNoiseAndUserDefinedReferences, ...
    @testChannelAndWindowFiltersReturnApplicableReferences, ...
    @testMappedEventTableFeedsRegistrationWithoutANewParser, ...
    @testRegistrationRejectsInvalidOrConflictingClaims, ...
    @testSchemaRejectsCrossRecordingScopeAndInvalidBands});
end

function testRegistersAndReadsToneNoiseAndUserDefinedReferences(testCase)
[fixture, cleanup] = setUpFixture(); %#ok<ASGLU>

tone = vawlume.acoustic.registerReference(fixture.conn, fixture.recording_ref, ...
    struct(reference_key="tone-low-01", reference_type="tone", ...
    native_label="LOW_TONE", start_time_s=1, end_time_s=2, ...
    channel_index=1, frequency_min_hz=18000, frequency_max_hz=22000, ...
    external_event_id=1, source_file_id=3, mapping_profile_version_id=1, ...
    source_locator="references.csv:row:1"));
noise = vawlume.acoustic.registerReference(fixture.conn, fixture.recording_ref, ...
    struct(reference_key="noise-01", reference_type="noise", ...
    native_label="WHITE_NOISE", start_time_s=4, end_time_s=6));
custom = vawlume.acoustic.registerReference(fixture.conn, fixture.recording_ref, ...
    struct(reference_key="custom-01", ...
    reference_type="colony-specific chirp train", ...
    start_time_s=7, end_time_s=7));

verifyEqual(testCase, tone.action, "created");
verifyEqual(testCase, noise.action, "created");
verifyEqual(testCase, custom.action, "created");
verifyTrue(testCase, isnan(noise.recording_channel_id));
verifyEqual(testCase, custom.interval_s, [7 7]);

reused = vawlume.acoustic.registerReference(fixture.conn, fixture.recording_ref, ...
    struct(reference_key="tone-low-01", reference_type="tone", ...
    native_label="LOW_TONE", start_time_s=1, end_time_s=2, ...
    channel_index=1, frequency_min_hz=18000, frequency_max_hz=22000, ...
    external_event_id=1, source_file_id=3, mapping_profile_version_id=1, ...
    source_locator="references.csv:row:1"));
verifyEqual(testCase, reused.action, "reused");
verifyEqual(testCase, reused.acoustic_reference_id, tone.acoustic_reference_id);

rows = vawlume.acoustic.readReferences(fixture.conn, fixture.recording_ref);
verifyEqual(testCase, height(rows), 3);
toneRow = rows(rows.reference_key == "tone-low-01", :);
verifyEqual(testCase, toneRow.frequency_min_hz, 18000);
verifyEqual(testCase, toneRow.frequency_max_hz, 22000);
verifyEqual(testCase, toneRow.channel_index, 1);
verifyFalse(testCase, toneRow.applies_to_all_channels);
verifyEqual(testCase, toneRow.native_timebase_name, "audio_native");
verifyEqual(testCase, toneRow.native_time_unit, "s");
verifyEqual(testCase, toneRow.external_event_type, "tone");
verifyEqual(testCase, toneRow.external_stream_name, "reference_annotations");
verifyEqual(testCase, toneRow.mapping_profile_key, "reference-events-v1");
verifyEqual(testCase, toneRow.source_path_or_uri, "reference-events.csv");

noiseRow = rows(rows.reference_key == "noise-01", :);
verifyTrue(testCase, noiseRow.applies_to_all_channels);
verifyTrue(testCase, isnan(noiseRow.frequency_min_hz));
verifyTrue(testCase, isnan(noiseRow.frequency_max_hz));
verifyTrue(testCase, isnan(noiseRow.external_event_id));

customRow = rows(rows.reference_key == "custom-01", :);
verifyEqual(testCase, customRow.reference_type, ...
    "colony-specific chirp train");

% A linked event remains provenance. Registration creates neither an anchor nor
% a measurement and does not require an analysis run.
verifyEqual(testCase, countRows(fixture.conn, "alignment_anchors"), 0);
verifyEqual(testCase, countRows(fixture.conn, "alignment_anchor_observations"), 0);
verifyEqual(testCase, countRows(fixture.conn, "derived_measurements"), 0);

clear cleanup
end

function testChannelAndWindowFiltersReturnApplicableReferences(testCase)
[fixture, cleanup] = setUpFixture(); %#ok<ASGLU>
registerSimple(fixture, "global", "noise", 0, 10, NaN);
registerSimple(fixture, "channel-1", "tone", 2, 3, 1);
registerSimple(fixture, "channel-2", "tone", 5, 6, 2);

channel1 = vawlume.acoustic.readReferences(fixture.conn, ...
    fixture.recording_ref, ChannelIndex=1);
verifyEqual(testCase, sort(channel1.reference_key), ["channel-1"; "global"]);

channel2 = vawlume.acoustic.readReferences(fixture.conn, ...
    fixture.recording_ref, ChannelIndex=2);
verifyEqual(testCase, sort(channel2.reference_key), ["channel-2"; "global"]);

window = vawlume.acoustic.readReferences(fixture.conn, fixture.recording_ref, ...
    ChannelIndex=1, StartTimeS=4, EndTimeS=4.5);
verifyEqual(testCase, window.reference_key, "global");

empty = vawlume.acoustic.readReferences(fixture.conn, fixture.recording_ref, ...
    StartTimeS=20);
verifyEqual(testCase, height(empty), 0);
verifyTrue(testCase, ismember("external_timebase_id", ...
    string(empty.Properties.VariableNames)));

clear cleanup
end

function testMappedEventTableFeedsRegistrationWithoutANewParser(testCase)
[fixture, cleanup] = setUpFixture(); %#ok<ASGLU>
profile = fullfile(fixture.repo_root, "config", "01_mapping_profiles", ...
    "external_streams", "acoustic_reference_event_mapping_profile.json");
tbl = table("mapped-01", "LOW_TONE", 11, 12, "30000", "35000", 2, ...
    VariableNames=["reference_id", "reference_label", "start_time_s", ...
    "end_time_s", "frequency_min_hz", "frequency_max_hz", "channel_index"]);
ir = vawlume.source_mapping.mapTableToIR(tbl, profile, ...
    RepoRoot=fixture.repo_root);
minimum = ir.event_attributes(ir.event_attributes.attribute_name == ...
    "frequency_min_hz", :);
maximum = ir.event_attributes(ir.event_attributes.attribute_name == ...
    "frequency_max_hz", :);

result = vawlume.acoustic.registerReference(fixture.conn, fixture.recording_ref, ...
    struct(reference_key=ir.events.native_event_id(1), ...
    reference_type=ir.events.normalized_event_key(1), ...
    native_label=ir.events.native_event_label(1), ...
    start_time_s=ir.events.start_time_s(1), ...
    end_time_s=ir.events.end_time_s(1), channel_index=2, ...
    frequency_min_hz=minimum.value_real(1), ...
    frequency_max_hz=maximum.value_real(1), ...
    source_file_id=3, mapping_profile_version_id=1, ...
    source_locator=ir.events.source_locator(1)));

verifyEqual(testCase, result.reference_type, "tone");
rows = vawlume.acoustic.readReferences(fixture.conn, fixture.recording_ref);
verifyEqual(testCase, rows.reference_key, "mapped-01");
verifyEqual(testCase, rows.frequency_min_hz, 30000);
verifyEqual(testCase, rows.frequency_max_hz, 35000);
verifyEqual(testCase, rows.channel_index, 2);

clear cleanup
end

function testRegistrationRejectsInvalidOrConflictingClaims(testCase)
[fixture, cleanup] = setUpFixture(); %#ok<ASGLU>

verifyError(testCase, @() vawlume.acoustic.registerReference( ...
    fixture.conn, fixture.recording_ref, struct(reference_key="backwards", ...
    reference_type="tone", start_time_s=2, end_time_s=1)), ...
    "vawlume:acoustic:ReferenceIntervalInvalid");
verifyError(testCase, @() vawlume.acoustic.registerReference( ...
    fixture.conn, fixture.recording_ref, struct(reference_key="bad-band", ...
    reference_type="tone", start_time_s=1, end_time_s=2, ...
    frequency_min_hz=30, frequency_max_hz=20)), ...
    "vawlume:acoustic:FrequencyBandInvalid");
verifyError(testCase, @() vawlume.acoustic.registerReference( ...
    fixture.conn, fixture.recording_ref, struct(reference_key="bad-channel", ...
    reference_type="noise", start_time_s=1, end_time_s=2, channel_index=9)), ...
    "vawlume:acoustic:ChannelNotFound");
verifyError(testCase, @() vawlume.acoustic.registerReference( ...
    fixture.conn, fixture.recording_ref, struct(reference_key="bad-event", ...
    reference_type="noise", start_time_s=1, end_time_s=2, ...
    external_event_id=2)), ...
    "vawlume:acoustic:ExternalEventScopeMismatch");

registerSimple(fixture, "stable", "noise", 1, 2, NaN);
verifyError(testCase, @() vawlume.acoustic.registerReference( ...
    fixture.conn, fixture.recording_ref, struct(reference_key="stable", ...
    reference_type="tone", start_time_s=1, end_time_s=2)), ...
    "vawlume:acoustic:ReferenceConflict");

verifyError(testCase, @() vawlume.acoustic.readReferences( ...
    fixture.conn, fixture.recording_ref, StartTimeS=5, EndTimeS=4), ...
    "vawlume:acoustic:ReadWindowInvalid");

clear cleanup
end

function testSchemaRejectsCrossRecordingScopeAndInvalidBands(testCase)
[fixture, cleanup] = setUpFixture(); %#ok<ASGLU>

verifySqlFails(testCase, fixture.conn, ...
    "INSERT INTO acoustic_references(recording_id, recording_channel_id, " + ...
    "reference_key, reference_type, start_time_s, end_time_s) " + ...
    "VALUES (1, 3, 'wrong-channel', 'tone', 1, 2)");
verifySqlFails(testCase, fixture.conn, ...
    "INSERT INTO acoustic_references(recording_id, external_event_id, " + ...
    "reference_key, reference_type, start_time_s, end_time_s) " + ...
    "VALUES (1, 2, 'wrong-event', 'tone', 1, 2)");
verifySqlFails(testCase, fixture.conn, ...
    "INSERT INTO acoustic_references(recording_id, reference_key, " + ...
    "reference_type, start_time_s, end_time_s, frequency_min_hz) " + ...
    "VALUES (1, 'negative-frequency', 'tone', 1, 2, -1)");

execute(fixture.conn, "INSERT INTO acoustic_references(recording_id, " + ...
    "recording_channel_id, reference_key, reference_type, start_time_s, end_time_s) " + ...
    "VALUES (1, 1, 'valid', 'tone', 1, 2)");
verifySqlFails(testCase, fixture.conn, ...
    "UPDATE acoustic_references SET recording_channel_id=3 " + ...
    "WHERE reference_key='valid'");
verifySqlFails(testCase, fixture.conn, ...
    "UPDATE acoustic_references SET external_event_id=2 " + ...
    "WHERE reference_key='valid'");
verifyEqual(testCase, height(fetch(fixture.conn, "PRAGMA foreign_key_check")), 0);

clear cleanup
end

function registerSimple(fixture, key, type, startTime, endTime, channelIndex)
spec = struct(reference_key=key, reference_type=type, ...
    start_time_s=startTime, end_time_s=endTime);
if ~isnan(channelIndex)
    spec.channel_index = channelIndex;
end
vawlume.acoustic.registerReference(fixture.conn, fixture.recording_ref, spec);
end

function [fixture, cleanup] = setUpFixture()
repoRoot = repoRootForTest();
addpath(fullfile(repoRoot, "src"));
dbFile = string(tempname) + ".sqlite";
conn = sqlite(char(dbFile), "create");
cleanup = onCleanup(@() cleanUpFixture(conn, dbFile, repoRoot));
vawlume.db.applySchema(conn, fullfile(repoRoot, "schema", "schema.sql"));

execute(conn, "INSERT INTO projects(project_id, project_key, project_name) " + ...
    "VALUES (1, 'acoustic-p1', 'Acoustic project'), " + ...
    "(2, 'acoustic-p2', 'Other project')");
execute(conn, "INSERT INTO source_files(source_file_id, project_id, file_role, " + ...
    "path_or_uri, relative_path) VALUES " + ...
    "(1, 1, 'recording_audio', 'audio/r1.wav', 'audio/r1.wav'), " + ...
    "(2, 2, 'recording_audio', 'audio/r2.wav', 'audio/r2.wav'), " + ...
    "(3, 1, 'external_event_table', 'reference-events.csv', 'reference-events.csv')");
execute(conn, "INSERT INTO recordings(recording_id, project_id, source_file_id, " + ...
    "native_recording_id, sample_rate_hz, channel_count, duration_s) VALUES " + ...
    "(1, 1, 1, 'r1', 250000, 2, 60), (2, 2, 2, 'r2', 250000, 1, 60)");
execute(conn, "INSERT INTO recording_channels(recording_channel_id, recording_id, " + ...
    "channel_index, channel_label) VALUES (1, 1, 1, 'left'), " + ...
    "(2, 1, 2, 'right'), (3, 2, 1, 'other')");
execute(conn, "INSERT INTO timebases(timebase_id, project_id, recording_id, " + ...
    "timebase_name, timebase_kind, is_recording_native, native_unit) VALUES " + ...
    "(1, 1, 1, 'audio_native', 'audio_sample_clock', 1, 's'), " + ...
    "(2, 2, 2, 'audio_native', 'audio_sample_clock', 1, 's')");
execute(conn, "INSERT INTO external_streams(external_stream_id, project_id, " + ...
    "recording_id, timebase_id, stream_name, stream_kind, modality) VALUES " + ...
    "(1, 1, 1, 1, 'reference_annotations', 'annotation', 'acoustic_reference'), " + ...
    "(2, 2, 2, 2, 'other_annotations', 'annotation', 'acoustic_reference')");
execute(conn, "INSERT INTO external_events(external_event_id, external_stream_id, " + ...
    "native_event_id, native_event_label, event_type, start_time_native, " + ...
    "end_time_native) VALUES (1, 1, 'tone-event', 'LOW_TONE', 'tone', 1, 2), " + ...
    "(2, 2, 'other-event', 'OTHER_TONE', 'tone', 1, 2)");
execute(conn, "INSERT INTO config_profiles(profile_id, project_id, profile_key, " + ...
    "profile_name, profile_kind) VALUES " + ...
    "(1, 1, 'reference-events-v1', 'Reference event mapping', " + ...
    "'external_stream_mapping')");
execute(conn, "INSERT INTO config_profile_versions(profile_version_id, profile_id, " + ...
    "version_label, profile_schema_version, content_format, content_uri) VALUES " + ...
    "(1, 1, '0.1.0', '0.3-draft', 'json', " + ...
    "'config/01_mapping_profiles/external_streams/acoustic_reference_event_mapping_profile.json')");

fixture = struct(conn=conn, db_file=dbFile, repo_root=repoRoot, ...
    recording_ref=struct(recording_id=1));
end

function value = countRows(conn, tableName)
rows = fetch(conn, "SELECT COUNT(*) AS n FROM " + tableName);
value = double(rows.n(1));
end

function verifySqlFails(testCase, conn, sql)
didFail = false;
try
    execute(conn, sql);
catch
    didFail = true;
end
verifyTrue(testCase, didFail, "Expected SQL statement to fail: " + sql);
end

function cleanUpFixture(conn, dbFile, repoRoot)
if isopen(conn)
    close(conn);
end
for suffix = ["", "-journal", "-wal", "-shm"]
    path = dbFile + suffix;
    if isfile(path)
        delete(path);
    end
end
rmpath(fullfile(repoRoot, "src"));
end

function repoRoot = repoRootForTest()
repoRoot = fileparts(fileparts(fileparts(mfilename("fullpath"))));
end
