function tests = test_common_time_projection
%TEST_COMMON_TIME_PROJECTION Derived event union and projected coverage.
tests = functiontests(localfunctions);
end

function testDetectionAndExternalEventsProjectWithoutMutation(testCase)
[fixture, cleanup] = setUpFixture(); %#ok<ASGLU>
before = nativeFingerprint(fixture.conn);
view = vawlume.alignment.commonTime(fixture.conn, alignmentRef(), ...
    VocalizationSource="detections", VocalizationRunId=1);

detection = view.events(view.events.event_source_kind == "detection", :);
verifyEqual(testCase, detection.native_start, [1; 2]);
verifyEqual(testCase, detection.aligned_start, [101.1; 102.2], AbsTol=1e-12);
verifyEqual(testCase, detection.alignment_kind, repmat("stored_transform", 2, 1));

video = view.events(view.events.source_stream_id == 1, :);
verifyEqual(testCase, video.aligned_start, [102; 140], AbsTol=1e-12);
verifyEqual(testCase, video.aligned_end(1), 104, AbsTol=1e-12);
verifyTrue(testCase, isnan(video.aligned_end(2)));

neural = view.events(view.events.source_stream_id == 2, :);
verifyEqual(testCase, neural.native_start, neural.aligned_start);
verifyEqual(testCase, neural.alignment_kind, "identity");
verifyTrue(testCase, isnan(neural.alignment_run_id));

videoCoverage = view.coverage(view.coverage.source_stream_id == 1, :);
verifyEqual(testCase, videoCoverage.aligned_start, [100; 140]);
verifyEqual(testCase, videoCoverage.aligned_end, [120; 160]);
verifyEqual(testCase, nativeFingerprint(fixture.conn), before);
verifyEqual(testCase, rowCount(fixture.conn, "aligned_external_events"), 0);
verifyEqual(testCase, rowCount(fixture.conn, "sequences"), 0);
verifyEqual(testCase, rowCount(fixture.conn, "sequence_members"), 0);
clear cleanup
end

function testConsensusIsAnExplicitIndependentSourceChoice(testCase)
[fixture, cleanup] = setUpFixture(); %#ok<ASGLU>
view = vawlume.alignment.commonTime(fixture.conn, alignmentRef(), ...
    VocalizationSource="consensus_events", VocalizationRunId=2, ...
    IncludeExternal=false);
verifyEqual(testCase, height(view.events), 1);
verifyEqual(testCase, view.events.event_source_kind, "consensus_event");
verifyEqual(testCase, view.events.native_start, 1.5);
verifyEqual(testCase, view.events.aligned_start, 101.65, AbsTol=1e-12);
verifyEqual(testCase, rowCount(fixture.conn, "detections"), 2);
clear cleanup
end

function testMixedTimelineUsesProjectedCoverage(testCase)
[fixture, cleanup] = setUpFixture(); %#ok<ASGLU>
view = vawlume.alignment.commonTime(fixture.conn, alignmentRef(), ...
    VocalizationSource="detections", VocalizationRunId=1);
channels = [struct(name="call_count", event_source_kind="detection", ...
    normalized_event_key="vocalization", coverage_key="recording:1", ...
    aggregation="onset_count"), ...
    struct(name="entry_present", event_source_kind="external_event", ...
    normalized_event_key="female_entry", coverage_key="external_stream:1", ...
    aggregation="any_overlap"), ...
    struct(name="ttl_count", event_source_kind="external_event", ...
    normalized_event_key="sync_marker", coverage_key="external_stream:2", ...
    aggregation="onset_count")];
result = vawlume.sequence.regularizeTimeline(view, channels, ...
    WindowStart=100, WindowEnd=162, BinWidth=2, BinOrigin=100);
verifyEqual(testCase, result.timeline.call_count(1:2), [1; 1]);
verifyEqual(testCase, result.timeline.entry_present(2), 1);
verifyEqual(testCase, result.timeline.entry_present(10), 0);
verifyTrue(testCase, isnan(result.timeline.entry_present(11)));
verifyFalse(testCase, result.timeline.entry_present_covered(11));
verifyEqual(testCase, result.timeline.ttl_count(6), 1);
clear cleanup
end

function testMissingTransformAndOutsideCoverageRaiseControlledErrors(testCase)
[fixture, cleanup] = setUpFixture(); %#ok<ASGLU>
execute(fixture.conn, "INSERT INTO external_events(external_stream_id, " + ...
    "native_event_id, event_type, start_time_native) " + ...
    "VALUES (1, 'outside', 'investigation', 15)");
verifyError(testCase, @() vawlume.alignment.commonTime( ...
    fixture.conn, alignmentRef()), ...
    "vawlume:alignment:EventOutsideCoverage");
execute(fixture.conn, "DELETE FROM external_events WHERE native_event_id='outside'");
execute(fixture.conn, "DELETE FROM alignment_segments WHERE alignment_run_id=2");
verifyError(testCase, @() vawlume.alignment.commonTime( ...
    fixture.conn, alignmentRef()), ...
    "vawlume:alignment:TransformSegmentMissing");
execute(fixture.conn, "INSERT INTO alignment_segments(alignment_run_id, " + ...
    "segment_index, scale, offset_s) VALUES (2,1,2,100)");
execute(fixture.conn, "UPDATE time_alignment_runs SET status='rejected' " + ...
    "WHERE alignment_run_id=2");
verifyError(testCase, @() vawlume.alignment.commonTime( ...
    fixture.conn, alignmentRef()), ...
    "vawlume:alignment:TransformNotUsable");
clear cleanup
end

function [fixture, cleanup] = setUpFixture()
repoRoot = string(fileparts(fileparts(fileparts(mfilename("fullpath")))));
sourcePath = fullfile(repoRoot, "src");
addpath(sourcePath);
workspace = fullfile(tempdir, "vawlume_common_time_" + ...
    string(java.util.UUID.randomUUID));
mkdir(workspace);
conn = sqlite(char(fullfile(workspace, "common_time.sqlite")), "create");
cleanup = onCleanup(@() tearDown(conn, workspace, sourcePath));
vawlume.db.applySchema(conn, fullfile(repoRoot, "schema", "schema.sql"));
seed(conn);
fixture = struct(conn=conn);
end

function seed(conn)
execute(conn, "INSERT INTO projects(project_id, project_key, project_name) " + ...
    "VALUES (1, 'common_time_fixture', 'Common time fixture')");
execute(conn, "INSERT INTO source_files(source_file_id, project_id, file_role, " + ...
    "path_or_uri) VALUES (1, 1, 'recording_audio', 'fixture.wav')");
execute(conn, "INSERT INTO recordings(recording_id, project_id, source_file_id, " + ...
    "native_recording_id, duration_s) VALUES (1, 1, 1, 'REC1', 10)");
execute(conn, "INSERT INTO timebases(timebase_id, project_id, recording_id, " + ...
    "timebase_name, timebase_kind, is_recording_native) VALUES " + ...
    "(1,1,1,'audio','audio_clock',1), " + ...
    "(2,1,1,'video','video_clock',0), " + ...
    "(3,1,1,'neural','neural_clock',0)");

execute(conn, "INSERT INTO extractors(extractor_id, extractor_key, extractor_name) " + ...
    "VALUES (1, 'fixture', 'Fixture extractor')");
execute(conn, "INSERT INTO extractor_versions(extractor_version_id, extractor_id, " + ...
    "version_label) VALUES (1, 1, '1')");
execute(conn, "INSERT INTO extraction_runs(extraction_run_id, project_id, " + ...
    "extractor_version_id, run_key) VALUES (1, 1, 1, 'calls')");
execute(conn, "INSERT INTO extraction_run_inputs(extraction_run_id, recording_id) " + ...
    "VALUES (1, 1)");
execute(conn, "INSERT INTO detections(detection_id, extraction_run_id, recording_id, " + ...
    "native_event_id, start_time_s, end_time_s) VALUES " + ...
    "(1,1,1,'d1',1,1.2), (2,1,1,'d2',2,2.1)");

execute(conn, "INSERT INTO analysis_runs(analysis_run_id, project_id, run_type, " + ...
    "run_key, status) VALUES (1,1,'temporal_alignment','align','completed'), " + ...
    "(2,1,'matching','consensus','completed')");
execute(conn, "INSERT INTO consensus_events(consensus_event_id, analysis_run_id, " + ...
    "recording_id, start_time_s, end_time_s, derivation_method) " + ...
    "VALUES (1,2,1,1.5,1.7,'union_boundary_of_members')");

execute(conn, "INSERT INTO external_streams(external_stream_id, project_id, " + ...
    "recording_id, timebase_id, stream_name, stream_kind) VALUES " + ...
    "(1,1,1,2,'behavior','annotation'), (2,1,1,3,'ttl','ttl')");
execute(conn, "INSERT INTO external_events(external_event_id, external_stream_id, " + ...
    "native_event_id, native_event_label, event_type, start_time_native, end_time_native) " + ...
    "VALUES (1,1,'b1','entry','female_entry',1,2), " + ...
    "(2,1,'b2','entry edge','female_entry',20,NULL), " + ...
    "(3,2,'n1','TTL','sync_marker',110,NULL)");
execute(conn, "INSERT INTO external_stream_coverage(external_stream_id, segment_index, " + ...
    "start_time_native, end_time_native) VALUES " + ...
    "(1,1,0,10), (1,2,20,30), (2,1,100,200)");

execute(conn, "INSERT INTO alignment_sets(alignment_set_id, analysis_run_id, " + ...
    "recording_id, reference_timebase_id, alignment_set_key, status) " + ...
    "VALUES (1,1,1,3,'fixture','fitted')");
execute(conn, "INSERT INTO time_alignment_runs(alignment_run_id, alignment_set_id, " + ...
    "source_timebase_id, target_timebase_id, method, status) VALUES " + ...
    "(1,1,1,3,'affine','estimated'), (2,1,2,3,'affine','estimated')");
execute(conn, "INSERT INTO alignment_segments(alignment_run_id, segment_index, " + ...
    "scale, offset_s) VALUES (1,1,1.1,100), (2,1,2,100)");
end

function value = alignmentRef()
value = struct(run_key="align", project_key="common_time_fixture");
end

function value = nativeFingerprint(conn)
value = struct(detections=fetch(conn, "SELECT detection_id,start_time_s,end_time_s " + ...
    "FROM detections ORDER BY detection_id"), ...
    consensus=fetch(conn, "SELECT consensus_event_id,start_time_s,end_time_s " + ...
    "FROM consensus_events ORDER BY consensus_event_id"), ...
    external=fetch(conn, "SELECT external_event_id,start_time_native," + ...
    "IFNULL(end_time_native,-1) AS end_time_native FROM external_events " + ...
    "ORDER BY external_event_id"), ...
    coverage=fetch(conn, "SELECT external_stream_coverage_id,start_time_native," + ...
    "end_time_native FROM external_stream_coverage ORDER BY external_stream_coverage_id"));
end

function value = rowCount(conn, tableName)
rows = fetch(conn, "SELECT COUNT(*) AS n FROM " + tableName);
value = double(rows.n(1));
end

function tearDown(conn, workspace, sourcePath)
if isopen(conn), close(conn); end
if isfolder(workspace), rmdir(workspace, "s"); end
rmpath(sourcePath);
end
