function tests = test_phase1_fixture
tests = functiontests({ ...
    @testCreatePhase1FixtureDatabasePopulatesRequiredShape, ...
    @testPhase1FixtureRebuildsStably, ...
    @testPhase1FixtureRejectsProtectedIntegrityViolations});
end

function testCreatePhase1FixtureDatabasePopulatesRequiredShape(testCase)
repoRoot = repoRootForTest();
addpath(fullfile(repoRoot, "src"));
cleanupPath = onCleanup(@() rmpath(fullfile(repoRoot, "src")));

[conn, dbFile, summary] = createFixtureDatabase(repoRoot);
cleanupDb = onCleanup(@() cleanupDatabase(conn, dbFile));

verifyEqual(testCase, summary.project_key, "phase1_synthetic_fixture");
verifyEqual(testCase, summary.foreign_key_violation_count, 0);
verifyEqual(testCase, height(fetch(conn, "PRAGMA foreign_key_check")), 0);
verifyCoreCounts(testCase, summary.counts);
verifyExperimentalShape(testCase, conn);
verifyProfilesAndRuns(testCase, conn);
verifyDetectionsAndMeasurements(testCase, conn);
verifyThreeExtractorPopulation(testCase, conn);
verifyReviewAndMatching(testCase, conn);
verifyExternalAlignment(testCase, conn);

clear cleanupPath cleanupDb summary
end

function testPhase1FixtureRebuildsStably(testCase)
repoRoot = repoRootForTest();
addpath(fullfile(repoRoot, "src"));
cleanupPath = onCleanup(@() rmpath(fullfile(repoRoot, "src")));

[connA, dbFileA, summaryA] = createFixtureDatabase(repoRoot);
cleanupDbA = onCleanup(@() cleanupDatabase(connA, dbFileA));

[connB, dbFileB, summaryB] = createFixtureDatabase(repoRoot);
cleanupDbB = onCleanup(@() cleanupDatabase(connB, dbFileB));

verifyEqual(testCase, summaryA.counts, summaryB.counts);
verifyEqual(testCase, summaryA.stability_signature, summaryB.stability_signature);

clear cleanupPath cleanupDbA cleanupDbB summaryA summaryB
end

function testPhase1FixtureRejectsProtectedIntegrityViolations(testCase)
repoRoot = repoRootForTest();
addpath(fullfile(repoRoot, "src"));
cleanupPath = onCleanup(@() rmpath(fullfile(repoRoot, "src")));

[conn, dbFile] = createFixtureDatabase(repoRoot);
cleanupDb = onCleanup(@() cleanupDatabase(conn, dbFile));
ids = fixtureIds(conn);
countsBefore = protectedCounts(conn);

verifySqlFails(testCase, conn, ...
    "INSERT INTO detections(extraction_run_id, recording_id, native_event_id, start_time_s, end_time_s) " + ...
    "VALUES (" + string(ids.dsSocialRun) + ", " + string(ids.socialRecording) + ", 'BAD_TIME', 1.000, 0.500)");

verifySqlFails(testCase, conn, ...
    "INSERT INTO detections(extraction_run_id, recording_id, native_event_id, start_time_s, end_time_s) " + ...
    "VALUES (" + string(ids.dsSocialRun) + ", " + string(ids.baselineRecording) + ", 'BAD_RUN_INPUT', 1.000, 1.100)");

[sameRunA, sameRunB] = orderedPair(ids.dsSocial1, ids.dsSocial2);
verifySqlFails(testCase, conn, candidateInsertSql(ids.matchingAnalysis, ids.socialRecording, sameRunA, sameRunB, "same_run"));

[crossRecordingA, crossRecordingB] = orderedPair(ids.dsSocial1, ids.dsBaseline1);
verifySqlFails(testCase, conn, candidateInsertSql(ids.matchingAnalysis, ids.socialRecording, crossRecordingA, crossRecordingB, "cross_recording"));

verifySqlFails(testCase, conn, ...
    "INSERT INTO feature_relationships(feature_a_id, feature_b_id, relationship_type) " + ...
    "VALUES (" + string(ids.maxFeature) + ", " + string(ids.minFeature) + ", 'comparable')");

existingRelationship = fetch(conn, ...
    "SELECT feature_a_id, feature_b_id FROM feature_relationships ORDER BY feature_relationship_id LIMIT 1");
verifySqlFails(testCase, conn, ...
    "INSERT INTO feature_relationships(feature_a_id, feature_b_id, relationship_type) " + ...
    "VALUES (" + string(existingRelationship.feature_a_id(1)) + ", " + ...
    string(existingRelationship.feature_b_id(1)) + ", 'comparable')");

verifyEqual(testCase, protectedCounts(conn), countsBefore);
verifyEqual(testCase, height(fetch(conn, "PRAGMA foreign_key_check")), 0);

clear cleanupPath cleanupDb
end

function verifyCoreCounts(testCase, counts)
verifyEqual(testCase, counts.projects, 1);
verifyEqual(testCase, counts.example_profile_versions, 2);
verifyEqual(testCase, counts.source_files, 3);
verifyEqual(testCase, counts.entity_types, 5);
verifyEqual(testCase, counts.experimental_entities, 8);
verifyEqual(testCase, counts.entity_relationships, 9);
verifyEqual(testCase, counts.recordings, 2);
verifyEqual(testCase, counts.recording_channels, 2);
verifyEqual(testCase, counts.recording_entity_links, 6);
verifyEqual(testCase, counts.recording_profile_assignments, 4);
verifyEqual(testCase, counts.recording_epochs, 2);
verifyEqual(testCase, counts.artifacts, 6);
verifyEqual(testCase, counts.extraction_runs, 4);
verifyEqual(testCase, counts.extraction_run_inputs, 4);
verifyEqual(testCase, counts.extraction_run_profiles, 8);
verifyEqual(testCase, counts.extraction_run_artifacts, 6);
verifyEqual(testCase, counts.extractor_objects, 10);
verifyEqual(testCase, counts.extractor_object_recordings, 10);
% 8 DeepSqueak/MUPET detections carrying 80 measurements, plus 6 USVSEG
% syllables carrying the 7 columns USVSEG actually exports.
verifyEqual(testCase, counts.detections, 14);
verifyEqual(testCase, counts.event_measurements, 122);
% USVSEG exports no curation state, so the curation rows stay DeepSqueak's.
verifyEqual(testCase, counts.curation_events, 4);
verifyEqual(testCase, counts.analysis_runs, 2);
verifyEqual(testCase, counts.candidate_pairs, 3);
verifyEqual(testCase, counts.match_groups, 4);
verifyEqual(testCase, counts.match_group_members, 7);
verifyEqual(testCase, counts.consensus_events, 2);
verifyEqual(testCase, counts.consensus_event_members, 5);
verifyEqual(testCase, counts.manual_reviews, 3);
verifyEqual(testCase, counts.consilience_assessments, 3);
verifyEqual(testCase, counts.timebases, 2);
verifyEqual(testCase, counts.external_streams, 1);
verifyEqual(testCase, counts.external_stream_sources, 1);
verifyEqual(testCase, counts.external_stream_coverage, 1);
verifyEqual(testCase, counts.external_events, 2);
verifyEqual(testCase, counts.alignment_sets, 1);
verifyEqual(testCase, counts.time_alignment_runs, 1);
verifyEqual(testCase, counts.alignment_anchors, 2);
% Each logical anchor is observed on both clocks, so two anchors give four rows.
verifyEqual(testCase, counts.alignment_anchor_observations, 4);
verifyEqual(testCase, counts.alignment_anchor_residuals, 2);
verifyEqual(testCase, counts.alignment_segments, 1);
verifyEqual(testCase, counts.aligned_external_events, 2);
end

function verifyExperimentalShape(testCase, conn)
project = sqlText("phase1_synthetic_fixture");
verifyEqual(testCase, scalar(conn, ...
    "SELECT COUNT(*) AS n FROM experimental_entities ee " + ...
    "JOIN entity_types et ON et.entity_type_id = ee.entity_type_id " + ...
    "JOIN projects p ON p.project_id = ee.project_id " + ...
    "WHERE p.project_key = " + project + " AND et.native_name = 'subject'"), 3);
verifyEqual(testCase, scalar(conn, ...
    "SELECT COUNT(DISTINCT er.role_label) AS n FROM entity_relationships er " + ...
    "JOIN experimental_entities parent ON parent.entity_id = er.parent_entity_id " + ...
    "WHERE parent.native_id = 'DYAD_01' AND er.relationship_type = 'member' " + ...
    "AND er.role_label IN ('male', 'female')"), 2);
verifyEqual(testCase, scalar(conn, ...
    "SELECT COUNT(*) AS n FROM v_recording_entity_context " + ...
    "WHERE project_key = " + project + " AND native_recording_id = 'REC_SOCIAL_DYAD_01' " + ...
    "AND entity_type = 'subject' AND role_label IN ('male', 'female')"), 2);
verifyEqual(testCase, scalar(conn, ...
    "SELECT COUNT(*) AS n FROM v_recording_entity_context " + ...
    "WHERE project_key = " + project + " AND native_recording_id = 'REC_BASELINE_M01' " + ...
    "AND entity_type = 'subject'"), 1);
end

function verifyProfilesAndRuns(testCase, conn)
project = sqlText("phase1_synthetic_fixture");
verifyEqual(testCase, scalar(conn, ...
    "SELECT COUNT(*) AS n FROM config_profile_versions cpv " + ...
    "JOIN config_profiles cp ON cp.profile_id = cpv.profile_id " + ...
    "WHERE cp.profile_key IN ('example.device.ultrasonic_usb_primary', 'example.setup.mouse_courtship_chamber') " + ...
    "AND LENGTH(IFNULL(cpv.checksum_sha256, '')) = 64"), 2);
verifyEqual(testCase, scalar(conn, ...
    "SELECT COUNT(DISTINCT extractor_name) AS n FROM v_detection_core " + ...
    "WHERE project_key = " + project + " AND native_recording_id = 'REC_SOCIAL_DYAD_01'"), 3);
verifyEqual(testCase, scalar(conn, ...
    "SELECT COUNT(DISTINCT extraction_run_key) AS n FROM v_detection_core " + ...
    "WHERE project_key = " + project + " AND native_recording_id = 'REC_BASELINE_M01'"), 1);
verifyEqual(testCase, scalar(conn, ...
    "SELECT COUNT(*) AS n FROM extraction_run_profiles erp " + ...
    "JOIN extraction_runs er ON er.extraction_run_id = erp.extraction_run_id " + ...
    "JOIN projects p ON p.project_id = er.project_id " + ...
    "WHERE p.project_key = " + project), 8);

% Every extraction run declares its own extractor version and output mapping
% profile. The USVSEG run is an ordinary peer here, not a special case.
runs = fetch(conn, ...
    "SELECT er.run_key, e.extractor_name, ev.version_label, cp.profile_key " + ...
    "FROM extraction_runs er " + ...
    "JOIN extractor_versions ev ON ev.extractor_version_id = er.extractor_version_id " + ...
    "JOIN extractors e ON e.extractor_id = ev.extractor_id " + ...
    "JOIN config_profile_versions cpv ON cpv.profile_version_id = er.output_mapping_profile_version_id " + ...
    "JOIN config_profiles cp ON cp.profile_id = cpv.profile_id " + ...
    "JOIN projects p ON p.project_id = er.project_id " + ...
    "WHERE p.project_key = " + project + " ORDER BY er.run_key");
verifyEqual(testCase, string(runs.run_key), [ ...
    "fixture_deepsqueak_baseline_v1"; "fixture_deepsqueak_social_v1"; ...
    "fixture_mupet_social_v1"; "fixture_usvseg_social_v1"]);
verifyEqual(testCase, string(runs.extractor_name), ...
    ["DeepSqueak"; "DeepSqueak"; "MUPET"; "USVSEG"]);
verifyEqual(testCase, string(runs.version_label), ...
    ["3.2.x"; "3.2.x"; "2.1"; "0.9r2"]);
verifyEqual(testCase, string(runs.profile_key), [ ...
    "vawlume.deepsqueak.output.v3_2"; "vawlume.deepsqueak.output.v3_2"; ...
    "vawlume.mupet.output.v2_1"; "vawlume.usvseg.output.v0_9r2"]);
end

function verifyDetectionsAndMeasurements(testCase, conn)
project = sqlText("phase1_synthetic_fixture");
% 3 DeepSqueak calls, 4 MUPET syllables, and 6 USVSEG syllables share the one
% social recording.
verifyEqual(testCase, scalar(conn, ...
    "SELECT COUNT(*) AS n FROM v_detection_core WHERE project_key = " + project + ...
    " AND native_recording_id = 'REC_SOCIAL_DYAD_01'"), 13);
% Native event id 1 is now legally repeated across four run/artifact scopes.
verifyEqual(testCase, scalar(conn, ...
    "SELECT COUNT(*) AS n FROM v_detection_core WHERE project_key = " + project + ...
    " AND native_event_id = '1'"), 4);
verifyEqual(testCase, scalar(conn, ...
    "SELECT COUNT(*) AS n FROM v_event_measurements_long vml " + ...
    "JOIN v_detection_core vc ON vc.detection_id = vml.detection_id " + ...
    "WHERE vc.project_key = " + project + " AND vml.transform_key = 'kHz_to_Hz' " + ...
    "AND vml.native_unit = 'kHz' AND vml.canonical_unit = 'Hz' " + ...
    "AND ABS(vml.canonical_value_real - (vml.native_value_real * 1000)) < 1e-9"), 44);
verifyEqual(testCase, scalar(conn, ...
    "SELECT COUNT(*) AS n FROM v_event_measurements_long vml " + ...
    "JOIN v_detection_core vc ON vc.detection_id = vml.detection_id " + ...
    "WHERE vc.project_key = " + project + " AND vml.transform_key = 'ms_to_s' " + ...
    "AND vml.native_unit = 'ms' AND vml.canonical_unit = 's' " + ...
    "AND ABS(vml.canonical_value_real - (vml.native_value_real / 1000)) < 1e-9"), 10);
verifyEqual(testCase, scalar(conn, ...
    "SELECT COUNT(*) AS n FROM event_measurements em " + ...
    "JOIN canonical_features cf ON cf.canonical_feature_id = em.canonical_feature_id " + ...
    "WHERE cf.canonical_name = 'inter_call_interval' AND em.native_value_type = 'missing' " + ...
    "AND em.native_raw_token = 'NA' AND em.canonical_value_real IS NULL"), 1);
verifyGreaterThanOrEqual(testCase, scalar(conn, ...
    "SELECT COUNT(*) AS n FROM v_event_measurements_long vml " + ...
    "JOIN v_detection_core vc ON vc.detection_id = vml.detection_id " + ...
    "WHERE vc.project_key = " + project + ...
    " AND vml.canonical_name IN ('native_detection_score', 'contour_sinuosity', 'tonality')"), 4);
end

function verifyThreeExtractorPopulation(testCase, conn)
project = sqlText("phase1_synthetic_fixture");
usvseg = "SELECT COUNT(*) AS n FROM v_detection_core WHERE project_key = " + project + ...
    " AND extraction_run_key = 'fixture_usvseg_social_v1'";
verifyEqual(testCase, scalar(conn, usvseg), 6);
verifyEqual(testCase, scalar(conn, usvseg + " AND native_recording_id <> 'REC_SOCIAL_DYAD_01'"), 0);

% The interpretable geometry the three pairwise analyses depend on. Native
% event id plus extraction run key is the stable selector; detection_id is a
% surrogate and is deliberately not asserted here.
geometry = fetch(conn, ...
    "SELECT native_event_id, start_time_s, end_time_s FROM v_detection_core " + ...
    "WHERE project_key = " + project + ...
    " AND extraction_run_key = 'fixture_usvseg_social_v1' " + ...
    "ORDER BY CAST(native_event_id AS INTEGER)");
verifyEqual(testCase, string(geometry.native_event_id), ["1"; "2"; "3"; "4"; "5"; "6"]);
verifyEqual(testCase, double(geometry.start_time_s), ...
    [10.0020; 20.0010; 30.0010; 40.0010; 40.0500; 50.0000], AbsTol=1e-12);
verifyEqual(testCase, double(geometry.end_time_s), ...
    [10.0490; 20.0410; 30.0360; 40.0430; 40.0990; 50.0600], AbsTol=1e-12);

% One extraction-run-scoped native id identifies exactly one detection, so
% later agreement work can select fixture events without surrogate ids.
verifyEqual(testCase, scalar(conn, ...
    "SELECT COUNT(*) AS n FROM (SELECT extraction_run_key, native_event_id " + ...
    "FROM v_detection_core WHERE project_key = " + project + ...
    " GROUP BY extraction_run_key, native_event_id HAVING COUNT(*) > 1)"), 0);

% USVSEG exports seven measurement columns per syllable, no detection score,
% and no curation state. None of the absent quantities may be synthesized.
verifyEqual(testCase, scalar(conn, ...
    "SELECT COUNT(*) AS n FROM v_event_measurements_long vml " + ...
    "JOIN v_detection_core vc ON vc.detection_id = vml.detection_id " + ...
    "WHERE vc.project_key = " + project + ...
    " AND vc.extraction_run_key = 'fixture_usvseg_social_v1'"), 42);
verifyEqual(testCase, scalar(conn, ...
    "SELECT COUNT(DISTINCT vml.native_name) AS n FROM v_event_measurements_long vml " + ...
    "JOIN v_detection_core vc ON vc.detection_id = vml.detection_id " + ...
    "WHERE vc.project_key = " + project + ...
    " AND vc.extraction_run_key = 'fixture_usvseg_social_v1'"), 7);
verifyEqual(testCase, scalar(conn, ...
    "SELECT COUNT(*) AS n FROM detections d " + ...
    "JOIN extraction_runs er ON er.extraction_run_id = d.extraction_run_id " + ...
    "WHERE er.run_key = 'fixture_usvseg_social_v1' AND d.detection_score IS NOT NULL"), 0);
verifyEqual(testCase, scalar(conn, ...
    "SELECT COUNT(*) AS n FROM curation_events ce " + ...
    "JOIN detections d ON d.detection_id = ce.detection_id " + ...
    "JOIN extraction_runs er ON er.extraction_run_id = d.extraction_run_id " + ...
    "WHERE er.run_key = 'fixture_usvseg_social_v1'"), 0);
verifyEqual(testCase, scalar(conn, ...
    "SELECT COUNT(*) AS n FROM v_event_measurements_long vml " + ...
    "JOIN v_detection_core vc ON vc.detection_id = vml.detection_id " + ...
    "WHERE vc.project_key = " + project + ...
    " AND vc.extraction_run_key = 'fixture_usvseg_social_v1' " + ...
    "AND vml.canonical_name IN ('frequency_min', 'frequency_max', " + ...
    "'frequency_bandwidth', 'native_detection_score', 'inter_call_interval')"), 0);

% USVSEG has no run-scoped settings artifact, so the run's settings profile
% stays NULL and its only artifact is the summary CSV.
verifyEqual(testCase, scalar(conn, ...
    "SELECT COUNT(*) AS n FROM extraction_runs " + ...
    "WHERE run_key = 'fixture_usvseg_social_v1' AND settings_profile_version_id IS NULL"), 1);
usvsegArtifacts = fetch(conn, ...
    "SELECT a.artifact_type, a.native_artifact_type, a.is_native, era.artifact_role " + ...
    "FROM extraction_run_artifacts era " + ...
    "JOIN extraction_runs er ON er.extraction_run_id = era.extraction_run_id " + ...
    "JOIN artifacts a ON a.artifact_id = era.artifact_id " + ...
    "WHERE er.run_key = 'fixture_usvseg_social_v1'");
verifyEqual(testCase, height(usvsegArtifacts), 1);
verifyEqual(testCase, string(usvsegArtifacts.native_artifact_type(1)), "usvseg_dat_csv");
verifyEqual(testCase, double(usvsegArtifacts.is_native(1)), 0);

% Native print precision is preserved as evidence rather than reformatted.
tokens = fetch(conn, ...
    "SELECT vml.native_name, vml.native_raw_token FROM v_event_measurements_long vml " + ...
    "JOIN v_detection_core vc ON vc.detection_id = vml.detection_id " + ...
    "WHERE vc.project_key = " + project + ...
    " AND vc.extraction_run_key = 'fixture_usvseg_social_v1' " + ...
    "AND vc.native_event_id = '1' ORDER BY vml.native_name");
verifyEqual(testCase, string(tokens.native_name), ...
    ["cvfreq"; "duration"; "end"; "maxamp"; "maxfreq"; "meanfreq"; "start"]);
verifyEqual(testCase, string(tokens.native_raw_token), ...
    ["0.0640"; "47.0"; "10.0490"; "-18.4"; "71.200"; "62.100"; "10.0020"]);

% The stored matching analysis stays the DeepSqueak/MUPET pair. Adding a third
% extractor to the fixture does not silently widen a pairwise analysis.
verifyEqual(testCase, scalar(conn, ...
    "SELECT COUNT(*) AS n FROM analysis_run_extraction_inputs arei " + ...
    "JOIN analysis_runs ar ON ar.analysis_run_id = arei.analysis_run_id " + ...
    "WHERE ar.run_key = 'fixture_cross_extractor_matching_v1'"), 2);
verifyEqual(testCase, scalar(conn, ...
    "SELECT COUNT(*) AS n FROM candidate_pairs cp " + ...
    "JOIN analysis_runs ar ON ar.analysis_run_id = cp.analysis_run_id " + ...
    "JOIN detections d ON d.detection_id IN (cp.detection_a_id, cp.detection_b_id) " + ...
    "JOIN extraction_runs er ON er.extraction_run_id = d.extraction_run_id " + ...
    "WHERE er.run_key = 'fixture_usvseg_social_v1'"), 0);
end

function verifyReviewAndMatching(testCase, conn)
project = sqlText("phase1_synthetic_fixture");
verifyEqual(testCase, scalar(conn, ...
    "SELECT COUNT(*) AS n FROM curation_events ce " + ...
    "JOIN manual_reviews mr ON mr.detection_id = ce.detection_id " + ...
    "JOIN detections d ON d.detection_id = ce.detection_id " + ...
    "JOIN recordings r ON r.recording_id = d.recording_id " + ...
    "JOIN projects p ON p.project_id = r.project_id " + ...
    "WHERE p.project_key = " + project + " AND ce.status_after = 'Accepted' " + ...
    "AND ce.actor_type = 'extractor' AND mr.review_status = 'adjudicated_false_positive'"), 1);
verifyEqual(testCase, scalar(conn, ...
    "SELECT COUNT(*) AS n FROM candidate_pairs cp " + ...
    "JOIN analysis_runs ar ON ar.analysis_run_id = cp.analysis_run_id " + ...
    "JOIN projects p ON p.project_id = ar.project_id WHERE p.project_key = " + project), 3);
verifyEqual(testCase, scalar(conn, ...
    "SELECT COUNT(*) AS n FROM match_groups mg " + ...
    "JOIN analysis_runs ar ON ar.analysis_run_id = mg.analysis_run_id " + ...
    "JOIN projects p ON p.project_id = ar.project_id WHERE p.project_key = " + project + ...
    " AND mg.match_type = 'unmatched'"), 2);
verifyEqual(testCase, scalar(conn, ...
    "SELECT COUNT(*) AS n FROM match_groups mg " + ...
    "JOIN match_group_members mgm ON mgm.match_group_id = mg.match_group_id " + ...
    "JOIN analysis_runs ar ON ar.analysis_run_id = mg.analysis_run_id " + ...
    "JOIN projects p ON p.project_id = ar.project_id WHERE p.project_key = " + project + ...
    " AND mg.match_type = 'one_to_many'"), 3);
verifyEqual(testCase, scalar(conn, ...
    "SELECT COUNT(*) AS n FROM consensus_events ce " + ...
    "JOIN consensus_event_members cem ON cem.consensus_event_id = ce.consensus_event_id " + ...
    "JOIN analysis_runs ar ON ar.analysis_run_id = ce.analysis_run_id " + ...
    "JOIN projects p ON p.project_id = ar.project_id WHERE p.project_key = " + project + ...
    " AND ce.derivation_method = 'union_boundary_split_merge'"), 3);
end

function verifyExternalAlignment(testCase, conn)
project = sqlText("phase1_synthetic_fixture");
verifyEqual(testCase, scalar(conn, ...
    "SELECT COUNT(*) AS n FROM v_external_events_aligned vea " + ...
    "JOIN recordings r ON r.recording_id = vea.recording_id " + ...
    "JOIN projects p ON p.project_id = r.project_id WHERE p.project_key = " + project + ...
    " AND vea.start_time_aligned_s IS NOT NULL"), 2);
verifyEqual(testCase, scalar(conn, ...
    "SELECT COUNT(*) AS n FROM v_external_events_aligned vea " + ...
    "JOIN recordings r ON r.recording_id = vea.recording_id " + ...
    "JOIN projects p ON p.project_id = r.project_id WHERE p.project_key = " + project + ...
    " AND ABS((vea.start_time_aligned_s - vea.start_time_native) - 0.55) < 1e-9"), 2);
end

function ids = fixtureIds(conn)
ids = struct();
ids.socialRecording = lookupId(conn, "SELECT recording_id AS id FROM recordings WHERE native_recording_id = 'REC_SOCIAL_DYAD_01'");
ids.baselineRecording = lookupId(conn, "SELECT recording_id AS id FROM recordings WHERE native_recording_id = 'REC_BASELINE_M01'");
ids.dsSocialRun = lookupId(conn, "SELECT extraction_run_id AS id FROM extraction_runs WHERE run_key = 'fixture_deepsqueak_social_v1'");
ids.matchingAnalysis = lookupId(conn, "SELECT analysis_run_id AS id FROM analysis_runs WHERE run_key = 'fixture_cross_extractor_matching_v1'");
ids.dsSocial1 = detectionId(conn, "fixture_deepsqueak_social_v1", "REC_SOCIAL_DYAD_01", "1");
ids.dsSocial2 = detectionId(conn, "fixture_deepsqueak_social_v1", "REC_SOCIAL_DYAD_01", "2");
ids.dsBaseline1 = detectionId(conn, "fixture_deepsqueak_baseline_v1", "REC_BASELINE_M01", "1");
ids.minFeature = lookupId(conn, "SELECT MIN(extractor_feature_id) AS id FROM extractor_features");
ids.maxFeature = lookupId(conn, "SELECT MAX(extractor_feature_id) AS id FROM extractor_features");
end

function id = detectionId(conn, runKey, recordingNativeId, nativeEventId)
id = lookupId(conn, ...
    "SELECT d.detection_id AS id FROM detections d " + ...
    "JOIN extraction_runs er ON er.extraction_run_id = d.extraction_run_id " + ...
    "JOIN recordings r ON r.recording_id = d.recording_id " + ...
    "WHERE er.run_key = " + sqlText(runKey) + ...
    " AND r.native_recording_id = " + sqlText(recordingNativeId) + ...
    " AND d.native_event_id = " + sqlText(nativeEventId));
end

function sql = candidateInsertSql(analysisRunId, recordingId, detectionAId, detectionBId, status)
sql = ...
    "INSERT INTO candidate_pairs(analysis_run_id, recording_id, detection_a_id, detection_b_id, candidate_status) " + ...
    "VALUES (" + string(analysisRunId) + ", " + string(recordingId) + ", " + ...
    string(detectionAId) + ", " + string(detectionBId) + ", " + sqlText(status) + ")";
end

function counts = protectedCounts(conn)
counts = struct();
counts.detections = scalar(conn, "SELECT COUNT(*) AS n FROM detections");
counts.candidate_pairs = scalar(conn, "SELECT COUNT(*) AS n FROM candidate_pairs");
counts.feature_relationships = scalar(conn, "SELECT COUNT(*) AS n FROM feature_relationships");
end

function [left, right] = orderedPair(a, b)
left = min(a, b);
right = max(a, b);
end

function [conn, dbFile, summary] = createFixtureDatabase(repoRoot)
dbFile = string(tempname) + ".sqlite";
[conn, databaseSummary] = vawlume.db.createPhase1FixtureDatabase(dbFile, repoRoot);
summary = databaseSummary.fixture;
end

function id = lookupId(conn, sql)
rows = fetch(conn, sql);
if height(rows) ~= 1
    error("vawlume:test:LookupFailed", "Expected one row for lookup, found %d. SQL: %s", height(rows), sql);
end
id = double(rows.id(1));
end

function value = scalar(conn, sql)
result = fetch(conn, sql);
value = double(result.n(1));
end

function verifySqlFails(testCase, conn, sql)
didFail = false;
try
    execute(conn, sql);
catch
    didFail = true;
end
verifyTrue(testCase, didFail, "Expected SQL statement to fail: " + sql);
end

function text = sqlText(value)
text = string(value);
text = "'" + replace(text, "'", "''") + "'";
end

function cleanupDatabase(conn, dbFile)
if isopen(conn)
    close(conn);
end
deleteIfExists(dbFile);
deleteIfExists(dbFile + "-journal");
deleteIfExists(dbFile + "-wal");
deleteIfExists(dbFile + "-shm");
end

function deleteIfExists(path)
if isfile(path)
    delete(path);
end
end

function repoRoot = repoRootForTest()
repoRoot = fileparts(fileparts(fileparts(mfilename("fullpath"))));
end
