function report = summarize(conn, analysisRef, options)
%SUMMARIZE Quantify detection- and feature-level agreement for one matching analysis.
%
% REPORT = vawlume.consilience.summarize(CONN, ANALYSISREF) reads a completed
% cross-extractor matching analysis and returns transparent agreement summaries.
% It is read-only by default and never writes, updates, or deletes any native
% extractor row.
%
% ANALYSISREF selects exactly one matching analysis:
%
%   struct(analysis_run_id=7)
%   struct(run_key="matching-v1")
%   struct(project_key="project-a", run_key="matching-v1")
%
% What the report contains:
%
%   detection_agreement   per-run counts with explicit denominators, run-specific
%                         proportions, and one pooled symmetric coverage whose
%                         definition is stated in the result itself
%   topology              group counts and participating detections per topology
%   temporal_agreement    onset, offset, duration, and IoU summaries over
%                         unambiguous one-to-one groups, read from the stored
%                         candidate evidence rather than recomputed
%   feature_pairs         registered cross-extractor comparability, discovered
%                         through equivalence_class and feature_relationships
%   feature_comparisons   one row per one-to-one group per eligible feature pair
%   feature_summary       per equivalence class aggregates where N permits
%   consilience           one automated status per match group, with the rule
%                         that assigned it and the evidence behind it
%   manual_qc             evaluation against an independent reviewer-authored
%                         reference set, plus an automated-versus-manual
%                         contingency table
%
% Two rules the report enforces rather than assumes. Feature pairs are discovered
% only through the registry: a shared canonical_name is neither necessary (the
% two central-frequency features do not share one) nor sufficient (sharing an
% equivalence class does not imply consilience eligibility). And quantitative
% comparison is restricted to unambiguous one_to_one groups; ambiguous groups are
% reported with reason not_computed_split_merge rather than averaged into a value.
%
% REPORT = vawlume.consilience.summarize(..., Apply=true) additionally persists
% the aggregate statistics under a child analysis run whose parent is the
% matching analysis. Per-pair comparison rows are returned but never persisted:
% the schema has no row that can hold a group, two detections, and two features
% with explicit lineage, and every value is exactly recomputable from the stored
% candidates, measurements, and registry.
%
% A consilience status is a categorical evidence summary under one versioned rule
% set, never a probability, so no score is stored. Manual adjudication is
% reported beside the automated status and never overwrites it: the automated
% status is what persists, the manual verdict lives in its own manual_reviews
% row, and the precedence-resolved effective status is computed for the reader.
%
% Nothing here treats either extractor as ground truth, and no manual label is
% ever derived from extractor curation, native labels, or detector scores.

arguments
    conn
    analysisRef (1,1) struct
    options.Apply (1,1) logical = false
    options.RepoRoot (1,1) string = ""
end

analysis = consilienceResolveAnalysis(conn, analysisRef);
specification = consilienceLoadSpec(conn, analysis, options.RepoRoot);
detection = consilienceDetectionAgreement(conn, analysis);
feature = consilienceFeatureAgreement(conn, analysis, specification);
classification = consilienceClassify(conn, analysis, specification, ...
    detection, feature);
manualQc = consilienceManualQc(conn, analysis, specification, classification);

report = struct( ...
    status="reported", ...
    committed=false, ...
    analysis=analysis, ...
    specification=struct( ...
        profile_key=specification.profile_key, ...
        version_label=specification.version_label, ...
        checksum_sha256=specification.checksum_sha256, ...
        content_uri=specification.content_uri, ...
        icc_enabled=specification.icc_enabled, ...
        icc_reason=specification.icc_reason, ...
        secondary_minimum_n=specification.secondary_minimum_n, ...
        min_temporal_iou=specification.min_temporal_iou, ...
        minimum_supporting_comparisons=specification.minimum_supporting_comparisons, ...
        missing_feature_policy=specification.missing_feature_policy, ...
        reference_set_key=specification.reference_set_key, ...
        reference_coverage=specification.reference_coverage, ...
        manual_min_temporal_iou=specification.manual_min_temporal_iou, ...
        sensitivity_configurations=specification.sensitivity_configurations), ...
    algorithm=struct(key=consilienceAlgorithm().key, ...
        version=consilienceAlgorithm().version), ...
    detection_agreement=detection.per_run, ...
    detection_denominators=detection.denominator_note, ...
    symmetric_coverage=detection.symmetric, ...
    topology=detection.topology, ...
    topology_participation=detection.participation, ...
    temporal_agreement=detection.temporal, ...
    feature_pairs=feature.pairs, ...
    feature_comparisons=feature.comparisons, ...
    feature_summary=feature.summary, ...
    excluded_groups=feature.excluded_groups, ...
    consilience=classification.assessments, ...
    consilience_status_counts=classification.status_counts, ...
    consilience_precedence=classification.precedence, ...
    consilience_vocabulary=classification.vocabulary, ...
    manual_qc=manualQc, ...
    terminology_note=terminologyNote(), ...
    applied_counts=struct());

if ~options.Apply
    return
end
[report.applied_counts, report.agreement_analysis] = ...
    consilienceApplyStatistics(conn, analysis, specification, detection, ...
    feature, classification, manualQc);
report.committed = true;
report.status = report.agreement_analysis.status;
end

function value = terminologyNote()
value = [ ...
    "Unmatched means no cross-extractor correspondence survived the matching " + ...
        "specification. It is not a false positive."; ...
    "A false positive or false negative requires an independent manual " + ...
        "reference, which Phase 6 does not yet have."; ...
    "A split or merge group is one correspondence component, never several " + ...
        "independent one-to-one matches."];
end
