function text = renderReadme(record)
%RENDERREADME The package README, rendered from the package record alone.
%
%   TEXT = vawlume.export.internal.renderReadme(RECORD)
%
%   Every fact in the README -- the mode, the counts, the source and version
%   facts, the exported objects, and the warnings -- is read from RECORD, the
%   same record the manifest and the metadata CSVs are rendered from (contract
%   §G.1). What is fixed text is the explanation: how to read the files and the
%   representation rules of contract §E, including the two consumer caveats of
%   §E.5.
%
%   It claims nothing the package does not do: no other format, no
%   denormalization, no type-preserving round trip, no embedded metadata
%   snapshot (contract §G.4).
%
%   PURE. It returns the text; the caller writes it.

arguments
    record (1,1) struct
end

normal = record.mode == "normal";
lines = strings(0, 1);
    function add(varargin)
        % Its own loop variable: a nested function shares the caller's
        % workspace, so reusing `k` would overwrite the caller's loop index.
        for item = 1:nargin
            lines(end + 1, 1) = string(varargin{item}); %#ok<AGROW>
        end
    end

if normal
    add("# VAWLUME CSV export", "", ...
        "This package is an export of one VAWLUME SQLite database as CSV files, " + ...
        "with metadata describing every table, view, column, and relationship of " + ...
        "the VAWLUME schema.", "");
else
    add("# VAWLUME schema reference (schema-only)", "", ...
        "This package describes the VAWLUME schema. **It contains no experimental " + ...
        "data: no database was read and no data files were written.** Every " + ...
        "object is listed with `exported` = `false`.", "");
end

% --- contents ----------------------------------------------------------------
add("## Contents", "", "```text", "README.md                this file", ...
    "meta/manifest.csv        facts about this package and how it was made", ...
    "meta/tables.csv          one row per table and view of the schema", ...
    "meta/columns.csv         one row per column of every table and view", ...
    "meta/relationships.csv   one row per foreign-key relationship");
if normal
    add(sprintf("csv/                     %d data file(s), one per exported object", ...
        record.data_file_count));
end
add("```", "");

% --- facts ---------------------------------------------------------------------
add("## This package", "", "| Fact | Value |", "|---|---|", ...
    "| Mode | `" + record.mode + "` |", ...
    "| Format | `" + record.format + "` |", ...
    "| Created (UTC) | " + record.exported_at_utc + " |");
if normal
    add("| Source database | " + cellText(record.source_identifier.value) + " |", ...
        "| Source size (bytes) | " + record.source.bytes + " |", ...
        "| Source schema version | `" + record.source.schema_version + "` |", ...
        "| Source `PRAGMA user_version` | " + record.source.user_version + " |");
end
add("| Repository schema version | `" + record.repository_schema_version + "` |", ...
    "| Metadata version | `" + record.metadata_version + "` (describes schema `" + ...
        record.metadata_schema_version + "`) |");
if record.vawlume_version == ""
    add("| VAWLUME version | not recorded (none was supplied) |");
else
    add("| VAWLUME version | `" + record.vawlume_version + "` (supplied by the caller) |");
end
add("| Objects in the schema | " + record.supported_object_count + " |", ...
    "| Objects selected | " + record.selected_object_count + " |", ...
    "| Objects exported | " + record.exported_object_count + " |", ...
    "| Rows exported, all objects | " + record.exported_row_total + " |", ...
    "| Data files | " + record.data_file_count + " |", "");

if normal
    add("### Exported objects", "", "| Object | Kind | Rows | File |", "|---|---|---:|---|");
    exported = record.objects(record.objects.exported, :);
    for k = 1:height(exported)
        add("| `" + exported.object_name(k) + "` | " + exported.object_kind(k) + ...
            " | " + exported.row_count(k) + " | `" + exported.filename(k) + "` |");
    end
    add("");
end

% --- warnings --------------------------------------------------------------------
add("## Warnings", "");
if height(record.warnings) == 0
    add("None.", "");
else
    for k = 1:height(record.warnings)
        add("- **" + record.warnings.code(k) + "**: " + record.warnings.message(k));
    end
    add("");
    if any(record.warnings.code == "source_structure_differs")
        add("An object with a `source_structure_differs` warning was exported with " + ...
            "the columns the source database actually has. Its header can therefore " + ...
            "differ from what `meta/columns.csv` describes, because that file " + ...
            "describes the repository's schema version.", "");
    end
end

% --- metadata files ----------------------------------------------------------------
add("## Reading the metadata", "", ...
    "The metadata files use the same CSV rules as the data files (below). " + ...
    "They describe the **whole** schema whatever was exported, so an " + ...
    "object this package does not contain is still described, and a relationship " + ...
    "whose other end was not exported still appears.", "", ...
    "- **`meta/tables.csv`**: `" + strjoin(string(record.tables_csv.Properties.VariableNames), "`, `") + ...
        "`. `object_kind` is `table` or `view`. A view is a query over tables and " + ...
        "owns no rows of its own. `exported` is `true` or `false`; `row_count` and " + ...
        "`filename` are blank for an object this package does not contain.", ...
    "- **`meta/columns.csv`**: `" + strjoin(string(record.columns_csv.Properties.VariableNames), "`, `") + ...
        "`. `column_position` is the column's 1-based declared position. " + ...
        "`description_source` is `authored`, or `inherited:<table>.<column>` when a " + ...
        "view column passes a base-table column through unchanged and borrows its " + ...
        "description.", ...
    "- **`meta/relationships.csv`**: `" + strjoin(string(record.relationships_csv.Properties.VariableNames), "`, `") + ...
        "`. Each row is a foreign key read from child (`source_*`, the table holding " + ...
        "the key) to parent (`target_*`). To see whether an endpoint was exported, " + ...
        "look it up in `meta/tables.csv`.", ...
    "- **`meta/manifest.csv`**: `key`, `value`, `detail`. One fact per row. A blank " + ...
        "value is explained in `detail` (`not_applicable`, `not_available`). Each " + ...
        "`warning` row gives a code in `value` and the explanation in `detail`. The " + ...
        "manifest is written last, so a directory that has one is a complete package.", "");

% --- representation ----------------------------------------------------------------
add("## Reading the CSV files", "", ...
    "Every file is UTF-8 without a byte-order mark. Records end in CRLF, and the " + ...
    "first record is the header of column names.", "", ...
    "| In the database | In the CSV |", "|---|---|", ...
    "| NULL | an **empty, unquoted** field |", ...
    "| empty text | `""""` (an empty, quoted field) |", ...
    "| text | the exact text, double-quoted, with inner `""` doubled; a newline inside a value is kept |", ...
    "| integer | its decimal digits, quoted |", ...
    "| real | 17 significant digits (`printf('%!.17g')`), quoted; parses back to the identical double |", ...
    "| BLOB | uppercase hexadecimal, quoted; an empty BLOB is `""""` |", "", ...
    "Every value is quoted, so a quoted empty field is always empty text and an " + ...
    "unquoted empty field is always NULL. The header row is quoted only where RFC " + ...
    "4180 requires it. A real `-0.0` is written as `0.0`. Row order carries no " + ...
    "meaning: sort by the key columns you need.", "", ...
    "**Values are exact text, not typed values.** What is preserved is each value's " + ...
    "text. `meta/columns.csv` gives each column's meaning, but the package does not " + ...
    "record SQLite column types, so this is not a type-preserving copy of the " + ...
    "database. The files are the database's own tables and views, not an " + ...
    "analysis-ready joined table.", "", ...
    "Two things a reader must know:", "", ...
    "1. **A default CSV reader guesses types and loses information.** It turns " + ...
    "identifiers and decimals such as `20.0` into numbers and can merge NULL with " + ...
    "empty text. Read every column as text, for example in MATLAB:", "", ...
    "   ```matlab", ...
    "   opts = detectImportOptions(file, Delimiter="","", TextType=""string"");", ...
    "   opts = setvartype(opts, ""string"");", ...
    "   data = readtable(file, opts);", ...
    "   ```", "", ...
    "2. **Text that looks numeric is still text.** A quoted `""10.05""` in a text " + ...
    "column is a string in the database; a type-guessing reader turns it into a " + ...
    "number despite the quotes.", "");

if normal
    add("## Consistency", "", ...
        "The database was opened read-only and was not changed. Its change counter " + ...
        "was read before the first object and after the last, and they agreed, so " + ...
        "every file comes from one database state. This detects a write made during " + ...
        "the export and refuses to produce a package; it does not lock other writers " + ...
        "out.", "");
end

text = strjoin(lines, newline) + newline;
end

function value = cellText(value)
if ismissing(value)
    value = "(not recorded)";
end
end
