function summary = buildPhase1Fixture(conn, repoRoot, options)
%BUILDPHASE1FIXTURE Populate a deterministic Phase 1 synthetic fixture.
%
% The fixture is source-controlled data for tests and examples. It assumes a
% schema has already been applied to conn, registers built-in semantic
% profiles by default, and then inserts synthetic instance data into a fresh
% project namespace.

arguments
    conn
    repoRoot (1,1) string = ""
    options.RegisterSemantics (1,1) logical = true
end

if strlength(repoRoot) == 0
    repoRoot = defaultRepoRoot();
else
    repoRoot = normalizePath(repoRoot);
end

if options.RegisterSemantics
    semanticSummary = vawlume.db.registerBuiltinSemantics(conn, repoRoot);
else
    semanticSummary = struct();
end

fixture = fixtureConstants(repoRoot);
assertFixtureProjectAbsent(conn, fixture.project_key);

oldAutoCommit = conn.AutoCommit;
conn.AutoCommit = "off";
try
    execute(conn, "PRAGMA foreign_keys = ON");

    profiles = registerExampleProfiles(conn, fixture);
    ids = struct();
    ids.project = insertProject(conn, fixture);
    insertProjectProfileAssignments(conn, ids.project, profiles, fixture);

    ids.entity_types = insertEntityTypes(conn, ids.project);
    ids.entities = insertEntities(conn, ids.project, ids.entity_types);
    insertEntityAttributes(conn, ids.entities, fixture);
    insertEntityRelationships(conn, ids.project, ids.entities);
    insertSessionProfileAssignments(conn, ids.entities, profiles, fixture);

    [ids.source_files, ids.recordings, ids.channels] = insertRecordings(conn, ids.project, ids.entities, fixture);
    insertRecordingLinks(conn, ids.recordings, ids.entities);
    insertRecordingProfileAssignments(conn, ids.recordings, profiles, fixture);
    ids.epochs = insertRecordingEpochs(conn, ids.recordings);

    ids.extractor_versions = lookupExtractorVersions(conn);
    ids.output_profiles = lookupOutputMappingProfiles(conn);
    ids.artifacts = insertArtifacts(conn, ids.project, fixture);
    ids.extraction_runs = insertExtractionRuns(conn, ids.project, ids.extractor_versions, ids.output_profiles, fixture);
    insertExtractionRunInputs(conn, ids.extraction_runs, ids.recordings, ids.channels);
    insertExtractionRunProfiles(conn, ids.extraction_runs, profiles);
    insertExtractionRunArtifacts(conn, ids.extraction_runs, ids.artifacts);
    ids.extractor_objects = insertExtractorObjects(conn, ids.extraction_runs, ids.artifacts, ids.recordings);

    ids.features = lookupMeasurementFeatures(conn, ids.extractor_versions);
    ids.detections = insertDetections(conn, ids.extraction_runs, ids.recordings, ids.artifacts, ids.extractor_objects);
    insertMeasurements(conn, ids.detections, ids.artifacts, ids.features);
    insertCurationEvents(conn, ids.detections, ids.artifacts, fixture);

    ids.analysis_runs = insertAnalysisRuns(conn, ids.project, fixture);
    insertAnalysisInputs(conn, ids.analysis_runs, ids.extraction_runs);
    [ids.match_groups, ids.consensus_events] = insertMatchingRows(conn, ids.analysis_runs.matching, ids.recordings.social, ids.detections);
    insertManualReviews(conn, ids.analysis_runs.matching, ids.detections, ids.match_groups, ids.consensus_events, fixture);

    [ids.timebases, ids.external_streams, ids.external_events, ids.alignment_run] = insertExternalAlignmentRows( ...
        conn, ids.project, ids.recordings.social, ids.source_files.behavior, ids.entities, ids.analysis_runs.alignment);

    commit(conn);
catch exception
    try
        rollback(conn);
    catch
    end
    conn.AutoCommit = oldAutoCommit;
    rethrow(exception);
end
conn.AutoCommit = oldAutoCommit;

summary = buildSummary(conn, ids.project, fixture, semanticSummary);
end

function fixture = fixtureConstants(repoRoot)
fixture = struct();
fixture.repo_root = repoRoot;
fixture.fixture_source = relativePath(fullfile(repoRoot, "schema", "fixtures", "phase1_synthetic_fixture.md"), repoRoot);
fixture.project_key = "phase1_synthetic_fixture";
fixture.project_name = "Phase 1 synthetic USV fixture";
fixture.timestamp_utc = "2026-08-25T00:00:00.000Z";
fixture.device_profile_path = fullfile(repoRoot, "config", "02_device_profiles", "recording_device_profile_examples.yaml");
fixture.setup_profile_path = fullfile(repoRoot, "config", "03_setup_profiles", "experimental_setup_profile_examples.yaml");
fixture.device_profile_key = "example.device.ultrasonic_usb_primary";
fixture.device_profile_name = "Primary ultrasonic USB microphone";
fixture.device_profile_version = "1";
fixture.setup_profile_key = "example.setup.mouse_courtship_chamber";
fixture.setup_profile_name = "Mouse courtship recording chamber";
fixture.setup_profile_version = "1";
fixture.profile_schema_version = "0.1-draft";
end

function projectId = insertProject(conn, fixture)
projectId = insertRow(conn, "projects", struct( ...
    project_key=fixture.project_key, ...
    project_name=fixture.project_name, ...
    description="Synthetic fixture for Phase 1 schema, semantic registration, matching, review, and alignment tests.", ...
    created_at_utc=fixture.timestamp_utc), "project_id");
end

function profiles = registerExampleProfiles(conn, fixture)
profiles = struct();
profiles.device = upsertBuiltInProfileVersion(conn, struct( ...
    profile_key=fixture.device_profile_key, ...
    profile_name=fixture.device_profile_name, ...
    profile_kind="recording_device", ...
    version_label=fixture.device_profile_version, ...
    profile_schema_version=fixture.profile_schema_version, ...
    content_format="yaml", ...
    content_uri=relativePath(fixture.device_profile_path, fixture.repo_root), ...
    checksum_sha256=sha256File(fixture.device_profile_path), ...
    description="Built-in example recording-device profile used by the Phase 1 fixture.", ...
    notes="Fixture references the selected profile entry within this multi-profile YAML artifact.", ...
    created_at_utc=fixture.timestamp_utc));

profiles.setup = upsertBuiltInProfileVersion(conn, struct( ...
    profile_key=fixture.setup_profile_key, ...
    profile_name=fixture.setup_profile_name, ...
    profile_kind="experimental_setup", ...
    version_label=fixture.setup_profile_version, ...
    profile_schema_version=fixture.profile_schema_version, ...
    content_format="yaml", ...
    content_uri=relativePath(fixture.setup_profile_path, fixture.repo_root), ...
    checksum_sha256=sha256File(fixture.setup_profile_path), ...
    description="Built-in example experimental-setup profile used by the Phase 1 fixture.", ...
    notes="Fixture references the selected profile entry within this multi-profile YAML artifact.", ...
    created_at_utc=fixture.timestamp_utc));
end

function profileVersionId = upsertBuiltInProfileVersion(conn, expected)
profileRows = fetch(conn, ...
    "SELECT profile_id, profile_name, profile_kind, is_builtin, IFNULL(description, '') AS description " + ...
    "FROM config_profiles WHERE project_id IS NULL AND profile_key = " + sqlText(expected.profile_key));
if height(profileRows) == 0
    profileId = insertRow(conn, "config_profiles", struct( ...
        profile_key=expected.profile_key, ...
        profile_name=expected.profile_name, ...
        profile_kind=expected.profile_kind, ...
        is_builtin=1, ...
        description=expected.description, ...
        created_at_utc=expected.created_at_utc), "profile_id");
else
    profileId = double(profileRows.profile_id(1));
    assertTextEquals(profileRows.profile_name(1), expected.profile_name, "config_profiles.profile_name");
    assertTextEquals(profileRows.profile_kind(1), expected.profile_kind, "config_profiles.profile_kind");
    assert(double(profileRows.is_builtin(1)) == 1, "Expected built-in profile to have is_builtin=1.");
end

versionRows = fetch(conn, ...
    "SELECT profile_version_id, IFNULL(profile_schema_version, '') AS profile_schema_version, " + ...
    "content_format, content_uri, IFNULL(checksum_sha256, '') AS checksum_sha256, is_snapshot, " + ...
    "IFNULL(notes, '') AS notes FROM config_profile_versions " + ...
    "WHERE profile_id = " + string(profileId) + " AND version_label = " + sqlText(expected.version_label));
if height(versionRows) == 0
    profileVersionId = insertRow(conn, "config_profile_versions", struct( ...
        profile_id=profileId, ...
        version_label=expected.version_label, ...
        profile_schema_version=expected.profile_schema_version, ...
        content_format=expected.content_format, ...
        content_uri=expected.content_uri, ...
        checksum_sha256=expected.checksum_sha256, ...
        is_snapshot=1, ...
        created_at_utc=expected.created_at_utc, ...
        notes=expected.notes), "profile_version_id");
else
    profileVersionId = double(versionRows.profile_version_id(1));
    assertTextEquals(versionRows.profile_schema_version(1), expected.profile_schema_version, "config_profile_versions.profile_schema_version");
    assertTextEquals(versionRows.content_format(1), expected.content_format, "config_profile_versions.content_format");
    assertTextEquals(versionRows.content_uri(1), expected.content_uri, "config_profile_versions.content_uri");
    assertTextEquals(versionRows.checksum_sha256(1), expected.checksum_sha256, "config_profile_versions.checksum_sha256");
end
end

function insertProjectProfileAssignments(conn, projectId, profiles, fixture)
insertRow(conn, "project_profile_assignments", struct( ...
    project_id=projectId, ...
    profile_version_id=profiles.device, ...
    assignment_role="default_recording_device", ...
    is_default=1, ...
    assigned_at_utc=fixture.timestamp_utc));
insertRow(conn, "project_profile_assignments", struct( ...
    project_id=projectId, ...
    profile_version_id=profiles.setup, ...
    assignment_role="default_experimental_setup", ...
    is_default=1, ...
    assigned_at_utc=fixture.timestamp_utc));
end

function ids = insertEntityTypes(conn, projectId)
ids = struct();
ids.study = insertEntityType(conn, projectId, "study", "study", 1, false, false, "Synthetic study-like root.");
ids.cohort = insertEntityType(conn, projectId, "cohort", "group", 2, false, false, "Synthetic cohort grouping.");
ids.dyad = insertEntityType(conn, projectId, "dyad", "interaction_unit", 3, false, false, "Role-labelled social interaction unit.");
ids.subject = insertEntityType(conn, projectId, "subject", "subject", 4, true, true, "Synthetic biological subject.");
ids.session = insertEntityType(conn, projectId, "session", "session", 5, false, false, "Synthetic recording session.");
end

function id = insertEntityType(conn, projectId, nativeName, canonicalRole, order, isBiological, isSubjectLike, description)
id = insertRow(conn, "entity_types", struct( ...
    project_id=projectId, ...
    native_name=nativeName, ...
    canonical_role=canonicalRole, ...
    hierarchy_order=order, ...
    is_biological_unit=isBiological, ...
    is_subject_like=isSubjectLike, ...
    description=description), "entity_type_id");
end

function ids = insertEntities(conn, projectId, entityTypes)
ids = struct();
ids.study = insertEntity(conn, projectId, entityTypes.study, "STUDY_SYNTH_USV", "Synthetic USV fixture study");
ids.cohort = insertEntity(conn, projectId, entityTypes.cohort, "COHORT_A", "Fixture cohort A");
ids.dyad = insertEntity(conn, projectId, entityTypes.dyad, "DYAD_01", "Fixture dyad 01");
ids.subject_male = insertEntity(conn, projectId, entityTypes.subject, "SUBJ_M01", "Male subject M01");
ids.subject_female = insertEntity(conn, projectId, entityTypes.subject, "SUBJ_F01", "Female subject F01");
ids.subject_observer = insertEntity(conn, projectId, entityTypes.subject, "SUBJ_OBS01", "Observer subject OBS01");
ids.session_baseline = insertEntity(conn, projectId, entityTypes.session, "SESSION_BASELINE", "Baseline session");
ids.session_social = insertEntity(conn, projectId, entityTypes.session, "SESSION_SOCIAL", "Social dyad session");
end

function id = insertEntity(conn, projectId, entityTypeId, nativeId, label)
id = insertRow(conn, "experimental_entities", struct( ...
    project_id=projectId, ...
    entity_type_id=entityTypeId, ...
    native_id=nativeId, ...
    display_label=label), "entity_id");
end

function insertEntityAttributes(conn, entities, fixture)
insertEntityTextAttribute(conn, entities.subject_male, "sex", "male", fixture.timestamp_utc);
insertEntityTextAttribute(conn, entities.subject_female, "sex", "female", fixture.timestamp_utc);
insertEntityTextAttribute(conn, entities.subject_observer, "role", "observer", fixture.timestamp_utc);
end

function insertEntityTextAttribute(conn, entityId, name, value, timestampUtc)
insertRow(conn, "entity_attributes", struct( ...
    entity_id=entityId, ...
    attribute_name=name, ...
    value_type="text", ...
    value_text=value, ...
    source_locator="phase1_synthetic_fixture.md", ...
    mapping_rule_key="fixture_entity_attribute:" + timestampUtc), "entity_attribute_id");
end

function insertEntityRelationships(conn, projectId, entities)
insertEntityRelationship(conn, projectId, entities.study, entities.cohort, "contains", "");
insertEntityRelationship(conn, projectId, entities.cohort, entities.dyad, "contains", "");
insertEntityRelationship(conn, projectId, entities.cohort, entities.subject_male, "contains", "");
insertEntityRelationship(conn, projectId, entities.cohort, entities.subject_female, "contains", "");
insertEntityRelationship(conn, projectId, entities.cohort, entities.subject_observer, "contains", "");
insertEntityRelationship(conn, projectId, entities.cohort, entities.session_baseline, "contains", "");
insertEntityRelationship(conn, projectId, entities.dyad, entities.subject_male, "member", "male");
insertEntityRelationship(conn, projectId, entities.dyad, entities.subject_female, "member", "female");
insertEntityRelationship(conn, projectId, entities.dyad, entities.session_social, "contains", "");
end

function insertEntityRelationship(conn, projectId, parentId, childId, type, role)
insertRow(conn, "entity_relationships", struct( ...
    project_id=projectId, ...
    parent_entity_id=parentId, ...
    child_entity_id=childId, ...
    relationship_type=type, ...
    role_label=role, ...
    source_locator="phase1_synthetic_fixture.md", ...
    mapping_rule_key="fixture_entity_relationship"), "entity_relationship_id");
end

function insertSessionProfileAssignments(conn, entities, profiles, fixture)
insertRow(conn, "entity_profile_assignments", struct( ...
    entity_id=entities.session_social, ...
    profile_version_id=profiles.setup, ...
    assignment_role="experimental_setup", ...
    assigned_at_utc=fixture.timestamp_utc));
insertRow(conn, "entity_profile_assignments", struct( ...
    entity_id=entities.session_baseline, ...
    profile_version_id=profiles.setup, ...
    assignment_role="experimental_setup", ...
    assigned_at_utc=fixture.timestamp_utc));
end

function [sourceFiles, recordings, channels] = insertRecordings(conn, projectId, entities, fixture)
sourceFiles = struct();
recordings = struct();
channels = struct();

sourceFiles.social_audio = insertSourceFile(conn, projectId, "recording_audio", ...
    "synthetic/recordings/session_social_dyad_01.wav", "session_social_dyad_01.wav", "wav", fixture);
sourceFiles.baseline_audio = insertSourceFile(conn, projectId, "recording_audio", ...
    "synthetic/recordings/session_baseline_m01.wav", "session_baseline_m01.wav", "wav", fixture);
sourceFiles.behavior = insertSourceFile(conn, projectId, "external_event_log", ...
    "synthetic/behavior/session_social_controller_events.csv", "session_social_controller_events.csv", "csv", fixture);

recordings.social = insertRecording(conn, projectId, sourceFiles.social_audio, "REC_SOCIAL_DYAD_01", 384000, 16, 1, 60, ...
    "2026-08-25T14:00:00.000Z", "Shared social fixture recording linked to both dyad members.", fixture);
recordings.baseline = insertRecording(conn, projectId, sourceFiles.baseline_audio, "REC_BASELINE_M01", 384000, 16, 1, 45, ...
    "2026-08-25T13:00:00.000Z", "Single-subject baseline fixture recording.", fixture);

channels.social = insertChannel(conn, recordings.social, 1, "ultrasonic_microphone_1", "ultrasonic_audio");
channels.baseline = insertChannel(conn, recordings.baseline, 1, "ultrasonic_microphone_1", "ultrasonic_audio");

insertRecordingAttribute(conn, recordings.social, "session_entity_native_id", "SESSION_SOCIAL", entities.session_social);
insertRecordingAttribute(conn, recordings.baseline, "session_entity_native_id", "SESSION_BASELINE", entities.session_baseline);
end

function sourceFileId = insertSourceFile(conn, projectId, role, relativePathValue, filename, format, fixture)
sourceFileId = insertRow(conn, "source_files", struct( ...
    project_id=projectId, ...
    file_role=role, ...
    path_or_uri=relativePathValue, ...
    relative_path=relativePathValue, ...
    filename=filename, ...
    file_format=format, ...
    discovered_at_utc=fixture.timestamp_utc), "source_file_id");
end

function recordingId = insertRecording(conn, projectId, sourceFileId, nativeId, sampleRateHz, bitDepth, channelCount, durationS, startUtc, notes, fixture)
recordingId = insertRow(conn, "recordings", struct( ...
    project_id=projectId, ...
    source_file_id=sourceFileId, ...
    native_recording_id=nativeId, ...
    sample_rate_hz=sampleRateHz, ...
    bit_depth=bitDepth, ...
    channel_count=channelCount, ...
    duration_s=durationS, ...
    recorded_start_utc=startUtc, ...
    created_at_utc=fixture.timestamp_utc, ...
    notes=notes), "recording_id");
end

function channelId = insertChannel(conn, recordingId, index, label, role)
channelId = insertRow(conn, "recording_channels", struct( ...
    recording_id=recordingId, ...
    channel_index=index, ...
    channel_label=label, ...
    channel_role=role), "recording_channel_id");
end

function insertRecordingAttribute(conn, recordingId, name, value, entityId)
insertRow(conn, "recording_attributes", struct( ...
    recording_id=recordingId, ...
    attribute_name=name, ...
    value_type="text", ...
    value_text=value, ...
    source_locator="experimental_entities.entity_id=" + string(entityId), ...
    mapping_rule_key="fixture_recording_attribute"), "recording_attribute_id");
end

function insertRecordingLinks(conn, recordings, entities)
insertRecordingLink(conn, recordings.social, entities.dyad, "interaction_context", "dyad", 0, 60);
insertRecordingLink(conn, recordings.social, entities.subject_male, "participant", "male", 0, 60);
insertRecordingLink(conn, recordings.social, entities.subject_female, "participant", "female", 0, 60);
insertRecordingLink(conn, recordings.social, entities.session_social, "session", "session", 0, 60);
insertRecordingLink(conn, recordings.baseline, entities.subject_male, "participant", "subject", 0, 45);
insertRecordingLink(conn, recordings.baseline, entities.session_baseline, "session", "session", 0, 45);
end

function insertRecordingLink(conn, recordingId, entityId, linkType, role, startTime, endTime)
insertRow(conn, "recording_entity_links", struct( ...
    recording_id=recordingId, ...
    entity_id=entityId, ...
    link_type=linkType, ...
    role_label=role, ...
    start_time_s=startTime, ...
    end_time_s=endTime), "recording_entity_link_id");
end

function insertRecordingProfileAssignments(conn, recordings, profiles, fixture)
for recordingId = [recordings.social, recordings.baseline]
    insertRow(conn, "recording_profile_assignments", struct( ...
        recording_id=recordingId, ...
        profile_version_id=profiles.device, ...
        assignment_role="recording_device", ...
        inheritance_source="direct", ...
        assigned_at_utc=fixture.timestamp_utc));
    insertRow(conn, "recording_profile_assignments", struct( ...
        recording_id=recordingId, ...
        profile_version_id=profiles.setup, ...
        assignment_role="experimental_setup", ...
        inheritance_source="session_like_entity", ...
        assigned_at_utc=fixture.timestamp_utc));
end
end

function ids = insertRecordingEpochs(conn, recordings)
ids = struct();
ids.social_interaction = insertRow(conn, "recording_epochs", struct( ...
    recording_id=recordings.social, ...
    epoch_name="social_interaction", ...
    epoch_type="interaction", ...
    start_time_s=0, ...
    end_time_s=60, ...
    source="fixture"), "epoch_id");
ids.baseline_window = insertRow(conn, "recording_epochs", struct( ...
    recording_id=recordings.baseline, ...
    epoch_name="baseline_window", ...
    epoch_type="baseline", ...
    start_time_s=0, ...
    end_time_s=45, ...
    source="fixture"), "epoch_id");
end

function versions = lookupExtractorVersions(conn)
versions = struct();
versions.deepsqueak = lookupSingleId(conn, ...
    "SELECT ev.extractor_version_id AS id FROM extractor_versions ev " + ...
    "JOIN extractors e ON e.extractor_id = ev.extractor_id " + ...
    "WHERE e.extractor_name = 'DeepSqueak' AND ev.version_label = '3.2.x'");
versions.mupet = lookupSingleId(conn, ...
    "SELECT ev.extractor_version_id AS id FROM extractor_versions ev " + ...
    "JOIN extractors e ON e.extractor_id = ev.extractor_id " + ...
    "WHERE e.extractor_name = 'MUPET' AND ev.version_label = '2.1'");
end

function profiles = lookupOutputMappingProfiles(conn)
profiles = struct();
profiles.deepsqueak = lookupConfigProfileVersion(conn, "vawlume.deepsqueak.output.v3_2", "3.2.x");
profiles.mupet = lookupConfigProfileVersion(conn, "vawlume.mupet.output.v2_1", "2.1");
end

function profileVersionId = lookupConfigProfileVersion(conn, profileKey, versionLabel)
profileVersionId = lookupSingleId(conn, ...
    "SELECT cpv.profile_version_id AS id FROM config_profile_versions cpv " + ...
    "JOIN config_profiles cp ON cp.profile_id = cpv.profile_id " + ...
    "WHERE cp.profile_key = " + sqlText(profileKey) + ...
    " AND cpv.version_label = " + sqlText(versionLabel));
end

function artifacts = insertArtifacts(conn, projectId, fixture)
artifacts = struct();
artifacts.ds_social_stats = insertArtifact(conn, projectId, "extractor_event_export", "event_stats_excel", ...
    "synthetic/extractor_outputs/deepsqueak/REC_SOCIAL_DYAD_01_Stats.xlsx", "xlsx", false, fixture);
artifacts.ds_social_native = insertArtifact(conn, projectId, "native_detection_container", "native_mat_call_table", ...
    "synthetic/extractor_outputs/deepsqueak/REC_SOCIAL_DYAD_01_deepsqueak.mat", "mat", true, fixture);
artifacts.ds_baseline_stats = insertArtifact(conn, projectId, "extractor_event_export", "event_stats_excel", ...
    "synthetic/extractor_outputs/deepsqueak/REC_BASELINE_M01_Stats.xlsx", "xlsx", false, fixture);
artifacts.mupet_social_csv = insertArtifact(conn, projectId, "extractor_event_export", "per_syllable_csv", ...
    "synthetic/extractor_outputs/mupet/REC_SOCIAL_DYAD_01_syllables.csv", "csv", false, fixture);
artifacts.mupet_social_native = insertArtifact(conn, projectId, "native_detection_container", "native_mupet_output", ...
    "synthetic/extractor_outputs/mupet/REC_SOCIAL_DYAD_01_mupet.mat", "mat", true, fixture);
end

function artifactId = insertArtifact(conn, projectId, artifactType, nativeType, path, format, isNative, fixture)
metadata = jsonencode(struct( ...
    fixture_source=fixture.fixture_source, ...
    synthetic=true, ...
    artifact_key=nativeType));
artifactId = insertRow(conn, "artifacts", struct( ...
    project_id=projectId, ...
    artifact_type=artifactType, ...
    native_artifact_type=nativeType, ...
    path_or_uri=path, ...
    file_format=format, ...
    is_native=isNative, ...
    imported_at_utc=fixture.timestamp_utc, ...
    metadata_json=metadata), "artifact_id");
end

function runs = insertExtractionRuns(conn, projectId, versions, outputProfiles, fixture)
runs = struct();
runs.ds_social = insertExtractionRun(conn, projectId, versions.deepsqueak, "fixture_deepsqueak_social_v1", ...
    "DeepSqueak social fixture import", outputProfiles.deepsqueak, fixture);
runs.mupet_social = insertExtractionRun(conn, projectId, versions.mupet, "fixture_mupet_social_v1", ...
    "MUPET social fixture import", outputProfiles.mupet, fixture);
runs.ds_baseline = insertExtractionRun(conn, projectId, versions.deepsqueak, "fixture_deepsqueak_baseline_v1", ...
    "DeepSqueak baseline fixture import", outputProfiles.deepsqueak, fixture);
end

function runId = insertExtractionRun(conn, projectId, versionId, runKey, runLabel, outputProfileVersionId, fixture)
runId = insertRow(conn, "extraction_runs", struct( ...
    project_id=projectId, ...
    extractor_version_id=versionId, ...
    run_key=runKey, ...
    run_label=runLabel, ...
    output_mapping_profile_version_id=outputProfileVersionId, ...
    started_at_utc=fixture.timestamp_utc, ...
    completed_at_utc=fixture.timestamp_utc, ...
    imported_at_utc=fixture.timestamp_utc, ...
    status="imported", ...
    notes="Synthetic fixture extraction run."), "extraction_run_id");
end

function insertExtractionRunInputs(conn, runs, recordings, channels)
insertExtractionRunInput(conn, runs.ds_social, recordings.social, channels.social);
insertExtractionRunInput(conn, runs.mupet_social, recordings.social, channels.social);
insertExtractionRunInput(conn, runs.ds_baseline, recordings.baseline, channels.baseline);
end

function insertExtractionRunInput(conn, runId, recordingId, channelId)
insertRow(conn, "extraction_run_inputs", struct( ...
    extraction_run_id=runId, ...
    recording_id=recordingId, ...
    recording_channel_id=channelId, ...
    input_role="source_audio"));
end

function insertExtractionRunProfiles(conn, runs, profiles)
runIds = [runs.ds_social, runs.mupet_social, runs.ds_baseline];
for runId = runIds
    insertRow(conn, "extraction_run_profiles", struct( ...
        extraction_run_id=runId, ...
        profile_version_id=profiles.device, ...
        assignment_role="recording_device", ...
        inheritance_source="recording"));
    insertRow(conn, "extraction_run_profiles", struct( ...
        extraction_run_id=runId, ...
        profile_version_id=profiles.setup, ...
        assignment_role="experimental_setup", ...
        inheritance_source="recording"));
end
end

function insertExtractionRunArtifacts(conn, runs, artifacts)
insertRunArtifact(conn, runs.ds_social, artifacts.ds_social_stats, "event_measurement_export");
insertRunArtifact(conn, runs.ds_social, artifacts.ds_social_native, "native_detection_container");
insertRunArtifact(conn, runs.mupet_social, artifacts.mupet_social_csv, "event_measurement_export");
insertRunArtifact(conn, runs.mupet_social, artifacts.mupet_social_native, "native_detection_container");
insertRunArtifact(conn, runs.ds_baseline, artifacts.ds_baseline_stats, "event_measurement_export");
end

function insertRunArtifact(conn, runId, artifactId, role)
insertRow(conn, "extraction_run_artifacts", struct( ...
    extraction_run_id=runId, ...
    artifact_id=artifactId, ...
    artifact_role=role));
end

function objects = insertExtractorObjects(conn, runs, artifacts, recordings)
objects = struct();
objects.ds_social_audio = insertExtractorObject(conn, runs.ds_social, NaN, artifacts.ds_social_native, ...
    "audio_file", "recording", "", "source_recording", "REC_SOCIAL_DYAD_01", "DeepSqueak social audio file");
objects.ds_social_calls = insertExtractorObject(conn, runs.ds_social, objects.ds_social_audio, artifacts.ds_social_stats, ...
    "Calls", "event", "vocalization_detection", "vocalization_event", "REC_SOCIAL_DYAD_01_Calls", "DeepSqueak Calls table");
objects.mupet_workspace = insertExtractorObject(conn, runs.mupet_social, NaN, artifacts.mupet_social_native, ...
    "workspace", "extractor_workspace", "", "extractor_workspace", "MUPET_WORKSPACE_SYNTH_A", "MUPET fixture workspace");
objects.mupet_dataset = insertExtractorObject(conn, runs.mupet_social, objects.mupet_workspace, artifacts.mupet_social_native, ...
    "data_set", "extractor_dataset", "", "extractor_dataset", "MUPET_DATASET_DYAD_A", "MUPET fixture data set");
objects.mupet_syllables = insertExtractorObject(conn, runs.mupet_social, objects.mupet_dataset, artifacts.mupet_social_csv, ...
    "syllable", "event", "vocalization_detection", "vocalization_event", "REC_SOCIAL_DYAD_01_syllables", "MUPET syllable CSV");
objects.ds_baseline_audio = insertExtractorObject(conn, runs.ds_baseline, NaN, artifacts.ds_baseline_stats, ...
    "audio_file", "recording", "", "source_recording", "REC_BASELINE_M01", "DeepSqueak baseline audio file");
objects.ds_baseline_calls = insertExtractorObject(conn, runs.ds_baseline, objects.ds_baseline_audio, artifacts.ds_baseline_stats, ...
    "Calls", "event", "vocalization_detection", "vocalization_event", "REC_BASELINE_M01_Calls", "DeepSqueak baseline Calls table");

insertExtractorObjectRecording(conn, objects.ds_social_audio, recordings.social);
insertExtractorObjectRecording(conn, objects.ds_social_calls, recordings.social);
insertExtractorObjectRecording(conn, objects.mupet_workspace, recordings.social);
insertExtractorObjectRecording(conn, objects.mupet_dataset, recordings.social);
insertExtractorObjectRecording(conn, objects.mupet_syllables, recordings.social);
insertExtractorObjectRecording(conn, objects.ds_baseline_audio, recordings.baseline);
insertExtractorObjectRecording(conn, objects.ds_baseline_calls, recordings.baseline);
end

function objectId = insertExtractorObject(conn, runId, parentId, artifactId, nativeLevel, canonicalLevel, subtype, equivalenceClass, nativeId, label)
values = struct( ...
    extraction_run_id=runId, ...
    source_artifact_id=artifactId, ...
    native_level=nativeLevel, ...
    canonical_level=canonicalLevel, ...
    canonical_subtype=subtype, ...
    equivalence_class=equivalenceClass, ...
    native_id=nativeId, ...
    native_label=label, ...
    mapping_strength="structural_semantic", ...
    lineage_note="Synthetic fixture object preserving extractor-native hierarchy.");
if ~isnan(parentId)
    values.parent_object_id = parentId;
end
objectId = insertRow(conn, "extractor_objects", values, "extractor_object_id");
end

function insertExtractorObjectRecording(conn, objectId, recordingId)
insertRow(conn, "extractor_object_recordings", struct( ...
    extractor_object_id=objectId, ...
    recording_id=recordingId, ...
    membership_role="member"));
end

function features = lookupMeasurementFeatures(conn, versions)
features = struct();
features.ds = struct();
features.ds.score = lookupFeatureRef(conn, versions.deepsqueak, "Score", "event_stats_excel", "", "", "native_detection_score");
features.ds.start = lookupFeatureRef(conn, versions.deepsqueak, "Begin Time (s)", "event_stats_excel", "contour_derived", "", "call_start_time");
features.ds.finish = lookupFeatureRef(conn, versions.deepsqueak, "End Time (s)", "event_stats_excel", "contour_derived", "", "call_end_time");
features.ds.duration = lookupFeatureRef(conn, versions.deepsqueak, "Call Length (s)", "event_stats_excel", "contour_derived", "", "call_duration");
features.ds.center = lookupFeatureRef(conn, versions.deepsqueak, "Principle Frequency (kHz)", "event_stats_excel", "contour_derived", "", "contour_median_frequency");
features.ds.min = lookupFeatureRef(conn, versions.deepsqueak, "Low Freq (kHz)", "event_stats_excel", "contour_derived", "", "frequency_min");
features.ds.max = lookupFeatureRef(conn, versions.deepsqueak, "High Freq (kHz)", "event_stats_excel", "contour_derived", "", "frequency_max");
features.ds.bandwidth = lookupFeatureRef(conn, versions.deepsqueak, "Delta Freq (kHz)", "event_stats_excel", "contour_derived", "", "frequency_bandwidth");
features.ds.sinuosity = lookupFeatureRef(conn, versions.deepsqueak, "Sinuosity", "event_stats_excel", "contour_derived", "", "contour_sinuosity");
features.ds.tonality = lookupFeatureRef(conn, versions.deepsqueak, "Tonality", "event_stats_excel", "contour_derived", "", "tonality");

features.mupet = struct();
features.mupet.start = lookupFeatureRef(conn, versions.mupet, "Syllable start time (sec)", "per_syllable_csv", "segmentation", "", "call_start_time");
features.mupet.finish = lookupFeatureRef(conn, versions.mupet, "Syllable end time (sec)", "per_syllable_csv", "segmentation", "", "call_end_time");
features.mupet.interval = lookupFeatureRef(conn, versions.mupet, "inter-syllable interval (sec)", "per_syllable_csv", "native_sequence_derived", "", "inter_call_interval");
features.mupet.duration = lookupFeatureRef(conn, versions.mupet, "syllable duration (msec)", "per_syllable_csv", "pre_noise_reduction_onset_offset", "pre_noise_reduction", "call_duration");
features.mupet.min = lookupFeatureRef(conn, versions.mupet, "minimum frequency (kHz)", "per_syllable_csv", "spectral_filterbank", "", "frequency_min");
features.mupet.max = lookupFeatureRef(conn, versions.mupet, "maximum frequency (kHz)", "per_syllable_csv", "spectral_filterbank", "", "frequency_max");
features.mupet.center = lookupFeatureRef(conn, versions.mupet, "mean frequency (kHz)", "per_syllable_csv", "spectral_filterbank", "", "frequency_center");
features.mupet.bandwidth = lookupFeatureRef(conn, versions.mupet, "frequency bandwidth (kHz)", "per_syllable_csv", "spectral_filterbank", "", "frequency_bandwidth");
features.mupet.energy = lookupFeatureRef(conn, versions.mupet, "total syllable energy (dB)", "per_syllable_csv", "spectral", "", "total_energy");
features.mupet.amplitude = lookupFeatureRef(conn, versions.mupet, "peak syllable amplitude (dB)", "per_syllable_csv", "spectral", "", "peak_amplitude");
end

function ref = lookupFeatureRef(conn, extractorVersionId, nativeName, sourceArtifactType, derivationStage, operationalVariant, canonicalName)
rows = fetch(conn, ...
    "SELECT xf.extractor_feature_id, cf.canonical_feature_id " + ...
    "FROM extractor_features xf " + ...
    "JOIN feature_mappings fm ON fm.extractor_feature_id = xf.extractor_feature_id " + ...
    "JOIN canonical_features cf ON cf.canonical_feature_id = fm.canonical_feature_id " + ...
    "WHERE xf.extractor_version_id = " + string(extractorVersionId) + ...
    " AND xf.native_name = " + sqlText(nativeName) + ...
    " AND IFNULL(xf.source_artifact_type, '') = " + sqlText(sourceArtifactType) + ...
    " AND IFNULL(xf.derivation_stage, '') = " + sqlText(derivationStage) + ...
    " AND IFNULL(xf.operational_variant, '') = " + sqlText(operationalVariant) + ...
    " AND cf.canonical_name = " + sqlText(canonicalName));
if height(rows) ~= 1
    error("vawlume:db:FixtureFeatureMissing", ...
        "Expected one feature mapping for %s -> %s, found %d.", nativeName, canonicalName, height(rows));
end
ref = struct( ...
    extractor_feature_id=double(rows.extractor_feature_id(1)), ...
    canonical_feature_id=double(rows.canonical_feature_id(1)), ...
    native_name=nativeName, ...
    canonical_name=canonicalName, ...
    operational_variant=operationalVariant);
end

function detections = insertDetections(conn, runs, recordings, artifacts, objects)
detections = struct();
detections.ds_match = insertDetection(conn, runs.ds_social, recordings.social, artifacts.ds_social_stats, objects.ds_social_calls, "1", 10.000, 10.050, 0.91, "DeepSqueak one-to-one match candidate.");
detections.ds_only = insertDetection(conn, runs.ds_social, recordings.social, artifacts.ds_social_stats, objects.ds_social_calls, "2", 20.000, 20.040, 0.82, "DeepSqueak-only unmatched fixture detection.");
detections.ds_long = insertDetection(conn, runs.ds_social, recordings.social, artifacts.ds_social_stats, objects.ds_social_calls, "3", 40.000, 40.100, 0.88, "Long DeepSqueak detection for split/merge fixture case.");
detections.mupet_match = insertDetection(conn, runs.mupet_social, recordings.social, artifacts.mupet_social_csv, objects.mupet_syllables, "1", 10.004, 10.052, 0.93, "MUPET one-to-one match candidate.");
detections.mupet_only = insertDetection(conn, runs.mupet_social, recordings.social, artifacts.mupet_social_csv, objects.mupet_syllables, "2", 30.000, 30.035, 0.74, "MUPET-only unmatched fixture detection.");
detections.mupet_split_a = insertDetection(conn, runs.mupet_social, recordings.social, artifacts.mupet_social_csv, objects.mupet_syllables, "3", 40.002, 40.045, 0.86, "First MUPET syllable in split/merge fixture case.");
detections.mupet_split_b = insertDetection(conn, runs.mupet_social, recordings.social, artifacts.mupet_social_csv, objects.mupet_syllables, "4", 40.052, 40.098, 0.84, "Second MUPET syllable in split/merge fixture case.");
detections.ds_baseline_repeat_id = insertDetection(conn, runs.ds_baseline, recordings.baseline, artifacts.ds_baseline_stats, objects.ds_baseline_calls, "1", 12.000, 12.040, 0.76, "Baseline detection repeats native event id 1 in a distinct run/artifact scope.");
end

function detectionId = insertDetection(conn, runId, recordingId, artifactId, objectId, nativeEventId, startS, endS, score, notes)
detectionId = insertRow(conn, "detections", struct( ...
    extraction_run_id=runId, ...
    recording_id=recordingId, ...
    source_artifact_id=artifactId, ...
    extractor_object_id=objectId, ...
    native_event_id=nativeEventId, ...
    event_subtype="vocalization_detection", ...
    start_time_s=startS, ...
    end_time_s=endS, ...
    timing_basis="profile_selected_event_geometry", ...
    detection_score=score, ...
    imported_at_utc="2026-08-25T00:00:00.000Z", ...
    notes=notes), "detection_id");
end

function insertMeasurements(conn, detections, artifacts, features)
insertDeepSqueakMeasurements(conn, detections.ds_match, artifacts.ds_social_stats, features.ds, 1, struct( ...
    score=0.91, start=10.000, finish=10.050, duration=0.050, min_khz=45.1, max_khz=80.2, ...
    bandwidth_khz=35.1, center_khz=62.4, sinuosity=1.12, tonality=0.78));
insertDeepSqueakMeasurements(conn, detections.ds_only, artifacts.ds_social_stats, features.ds, 2, struct( ...
    score=0.82, start=20.000, finish=20.040, duration=0.040, min_khz=50.0, max_khz=72.0, ...
    bandwidth_khz=22.0, center_khz=61.0, sinuosity=1.05, tonality=0.72));
insertDeepSqueakMeasurements(conn, detections.ds_long, artifacts.ds_social_stats, features.ds, 3, struct( ...
    score=0.88, start=40.000, finish=40.100, duration=0.100, min_khz=42.0, max_khz=84.0, ...
    bandwidth_khz=42.0, center_khz=63.5, sinuosity=1.40, tonality=0.69));
insertDeepSqueakMeasurements(conn, detections.ds_baseline_repeat_id, artifacts.ds_baseline_stats, features.ds, 1, struct( ...
    score=0.76, start=12.000, finish=12.040, duration=0.040, min_khz=46.0, max_khz=76.0, ...
    bandwidth_khz=30.0, center_khz=58.5, sinuosity=1.10, tonality=0.75));

insertMupetMeasurements(conn, detections.mupet_match, artifacts.mupet_social_csv, features.mupet, 1, struct( ...
    start=10.004, finish=10.052, interval=19.948, duration_ms=48, min_khz=44.8, max_khz=79.5, ...
    center_khz=61.9, bandwidth_khz=34.7, energy_db=12.5, amplitude_db=-34.2));
insertMupetMeasurements(conn, detections.mupet_only, artifacts.mupet_social_csv, features.mupet, 2, struct( ...
    start=30.000, finish=30.035, interval=10.002, duration_ms=35, min_khz=48.0, max_khz=70.0, ...
    center_khz=60.0, bandwidth_khz=22.0, energy_db=9.2, amplitude_db=-36.0));
insertMupetMeasurements(conn, detections.mupet_split_a, artifacts.mupet_social_csv, features.mupet, 3, struct( ...
    start=40.002, finish=40.045, interval=0.007, duration_ms=43, min_khz=43.0, max_khz=76.0, ...
    center_khz=59.0, bandwidth_khz=33.0, energy_db=11.1, amplitude_db=-35.0));
insertMupetMeasurements(conn, detections.mupet_split_b, artifacts.mupet_social_csv, features.mupet, 4, struct( ...
    start=40.052, finish=40.098, interval_missing=true, interval_raw="NA", duration_ms=46, min_khz=44.0, ...
    max_khz=83.0, center_khz=64.0, bandwidth_khz=39.0, energy_db=11.8, amplitude_db=-34.5));
end

function insertDeepSqueakMeasurements(conn, detectionId, artifactId, features, rowNumber, m)
locator = "row=" + string(rowNumber) + "; column=";
insertRealMeasurement(conn, detectionId, features.score, artifactId, m.score, "", m.score, "", "", locator + "Score", "");
insertRealMeasurement(conn, detectionId, features.start, artifactId, m.start, "s", m.start, "s", "identity", locator + "Begin Time (s)", "");
insertRealMeasurement(conn, detectionId, features.finish, artifactId, m.finish, "s", m.finish, "s", "identity", locator + "End Time (s)", "");
insertRealMeasurement(conn, detectionId, features.duration, artifactId, m.duration, "s", m.duration, "s", "identity", locator + "Call Length (s)", "");
insertKHzMeasurement(conn, detectionId, features.center, artifactId, m.center_khz, locator + "Principle Frequency (kHz)", "");
insertKHzMeasurement(conn, detectionId, features.min, artifactId, m.min_khz, locator + "Low Freq (kHz)", "");
insertKHzMeasurement(conn, detectionId, features.max, artifactId, m.max_khz, locator + "High Freq (kHz)", "");
insertKHzMeasurement(conn, detectionId, features.bandwidth, artifactId, m.bandwidth_khz, locator + "Delta Freq (kHz)", "");
insertRealMeasurement(conn, detectionId, features.sinuosity, artifactId, m.sinuosity, "ratio", m.sinuosity, "ratio", "identity", locator + "Sinuosity", "");
insertRealMeasurement(conn, detectionId, features.tonality, artifactId, m.tonality, "ratio", m.tonality, "ratio", "identity", locator + "Tonality", "");
end

function insertMupetMeasurements(conn, detectionId, artifactId, features, rowNumber, m)
locator = "row=" + string(rowNumber) + "; column=";
insertRealMeasurement(conn, detectionId, features.start, artifactId, m.start, "s", m.start, "s", "identity", locator + "Syllable start time (sec)", "");
insertRealMeasurement(conn, detectionId, features.finish, artifactId, m.finish, "s", m.finish, "s", "identity", locator + "Syllable end time (sec)", "");
if isfield(m, "interval_missing") && m.interval_missing
    insertMissingMeasurement(conn, detectionId, features.interval, artifactId, m.interval_raw, "s", "s", "identity", locator + "inter-syllable interval (sec)");
else
    insertRealMeasurement(conn, detectionId, features.interval, artifactId, m.interval, "s", m.interval, "s", "identity", locator + "inter-syllable interval (sec)", "");
end
insertRealMeasurement(conn, detectionId, features.duration, artifactId, m.duration_ms, "ms", m.duration_ms / 1000, "s", "ms_to_s", locator + "syllable duration (msec)", "pre_noise_reduction");
insertKHzMeasurement(conn, detectionId, features.min, artifactId, m.min_khz, locator + "minimum frequency (kHz)", "");
insertKHzMeasurement(conn, detectionId, features.max, artifactId, m.max_khz, locator + "maximum frequency (kHz)", "");
insertKHzMeasurement(conn, detectionId, features.center, artifactId, m.center_khz, locator + "mean frequency (kHz)", "");
insertKHzMeasurement(conn, detectionId, features.bandwidth, artifactId, m.bandwidth_khz, locator + "frequency bandwidth (kHz)", "");
insertRealMeasurement(conn, detectionId, features.energy, artifactId, m.energy_db, "dB", m.energy_db, "dB", "identity", locator + "total syllable energy (dB)", "");
insertRealMeasurement(conn, detectionId, features.amplitude, artifactId, m.amplitude_db, "dB", m.amplitude_db, "dB", "identity", locator + "peak syllable amplitude (dB)", "");
end

function insertKHzMeasurement(conn, detectionId, feature, artifactId, valueKHz, locator, operationalVariant)
insertRealMeasurement(conn, detectionId, feature, artifactId, valueKHz, "kHz", valueKHz * 1000, "Hz", "kHz_to_Hz", locator, operationalVariant);
end

function insertRealMeasurement(conn, detectionId, feature, artifactId, nativeValue, nativeUnit, canonicalValue, canonicalUnit, transformKey, locator, operationalVariant)
insertRow(conn, "event_measurements", struct( ...
    detection_id=detectionId, ...
    extractor_feature_id=feature.extractor_feature_id, ...
    canonical_feature_id=feature.canonical_feature_id, ...
    source_artifact_id=artifactId, ...
    native_value_type="real", ...
    native_raw_token=numericToken(nativeValue), ...
    native_value_real=nativeValue, ...
    native_unit=nativeUnit, ...
    canonical_value_real=canonicalValue, ...
    canonical_unit=canonicalUnit, ...
    transform_key=transformKey, ...
    operational_variant=operationalVariant, ...
    source_locator=locator), "event_measurement_id");
end

function insertMissingMeasurement(conn, detectionId, feature, artifactId, rawToken, nativeUnit, canonicalUnit, transformKey, locator)
insertRow(conn, "event_measurements", struct( ...
    detection_id=detectionId, ...
    extractor_feature_id=feature.extractor_feature_id, ...
    canonical_feature_id=feature.canonical_feature_id, ...
    source_artifact_id=artifactId, ...
    native_value_type="missing", ...
    native_raw_token=rawToken, ...
    native_unit=nativeUnit, ...
    canonical_unit=canonicalUnit, ...
    transform_key=transformKey, ...
    source_locator=locator, ...
    notes="Final MUPET syllable preserved native missing inter-syllable token."), "event_measurement_id");
end

function insertCurationEvents(conn, detections, artifacts, fixture)
insertCurationEvent(conn, detections.ds_match, artifacts.ds_social_stats, "Accepted", fixture);
insertCurationEvent(conn, detections.ds_only, artifacts.ds_social_stats, "Accepted", fixture);
insertCurationEvent(conn, detections.ds_long, artifacts.ds_social_stats, "Accepted", fixture);
insertCurationEvent(conn, detections.ds_baseline_repeat_id, artifacts.ds_baseline_stats, "Accepted", fixture);
end

function insertCurationEvent(conn, detectionId, artifactId, statusAfter, fixture)
insertRow(conn, "curation_events", struct( ...
    detection_id=detectionId, ...
    source_artifact_id=artifactId, ...
    action_type="native_deepsqueak_accepted_import", ...
    status_after=statusAfter, ...
    actor_type="extractor", ...
    actor_label="DeepSqueak Accepted column", ...
    event_time_utc=fixture.timestamp_utc, ...
    details_json=jsonencode(struct(native_Accepted=1)), ...
    notes="Native extractor curation state, not manual ground truth."), "curation_event_id");
end

function runs = insertAnalysisRuns(conn, projectId, fixture)
runs = struct();
runs.matching = insertAnalysisRun(conn, projectId, "cross_extractor_matching", "fixture_cross_extractor_matching_v1", ...
    "Fixture DeepSqueak-MUPET matching", fixture);
runs.alignment = insertAnalysisRun(conn, projectId, "external_time_alignment", "fixture_behavior_audio_alignment_v1", ...
    "Fixture behavior-to-audio alignment", fixture);
end

function analysisRunId = insertAnalysisRun(conn, projectId, runType, runKey, runLabel, fixture)
analysisRunId = insertRow(conn, "analysis_runs", struct( ...
    project_id=projectId, ...
    run_type=runType, ...
    run_key=runKey, ...
    run_label=runLabel, ...
    vawlume_version="phase1-fixture", ...
    status="completed", ...
    started_at_utc=fixture.timestamp_utc, ...
    completed_at_utc=fixture.timestamp_utc, ...
    notes="Synthetic fixture analysis run."), "analysis_run_id");
end

function insertAnalysisInputs(conn, analysisRuns, extractionRuns)
insertRow(conn, "analysis_run_extraction_inputs", struct( ...
    analysis_run_id=analysisRuns.matching, ...
    extraction_run_id=extractionRuns.ds_social, ...
    input_role="deepsqueak_input"));
insertRow(conn, "analysis_run_extraction_inputs", struct( ...
    analysis_run_id=analysisRuns.matching, ...
    extraction_run_id=extractionRuns.mupet_social, ...
    input_role="mupet_input"));
end

function [groups, consensus] = insertMatchingRows(conn, analysisRunId, recordingId, detections)
insertCandidatePair(conn, analysisRunId, recordingId, detections.ds_match, detections.mupet_match, 0.046, 0.884615, 0.004, 0.002, 0.002, 0.95, "accepted");
insertCandidatePair(conn, analysisRunId, recordingId, detections.ds_long, detections.mupet_split_a, 0.043, 0.430000, 0.002, -0.055, -0.057, 0.73, "candidate_split");
insertCandidatePair(conn, analysisRunId, recordingId, detections.ds_long, detections.mupet_split_b, 0.046, 0.460000, 0.052, -0.002, -0.054, 0.71, "candidate_split");

groups = struct();
groups.one_to_one = insertMatchGroup(conn, analysisRunId, recordingId, "one_to_one", "resolved", 0.95, "Clear DeepSqueak/MUPET one-to-one match.");
insertMatchMember(conn, groups.one_to_one, detections.ds_match, "deepsqueak_member");
insertMatchMember(conn, groups.one_to_one, detections.mupet_match, "mupet_member");

groups.ds_unmatched = insertMatchGroup(conn, analysisRunId, recordingId, "unmatched", "resolved", 0, "DeepSqueak-only event retained as unmatched.");
insertMatchMember(conn, groups.ds_unmatched, detections.ds_only, "unmatched_deepsqueak");

groups.mupet_unmatched = insertMatchGroup(conn, analysisRunId, recordingId, "unmatched", "resolved", 0, "MUPET-only event retained as unmatched.");
insertMatchMember(conn, groups.mupet_unmatched, detections.mupet_only, "unmatched_mupet");

groups.split_merge = insertMatchGroup(conn, analysisRunId, recordingId, "one_to_many", "split_merge_confirmed", 0.72, "One long DeepSqueak event corresponds to two adjacent MUPET syllables.");
insertMatchMember(conn, groups.split_merge, detections.ds_long, "source_long_detection");
insertMatchMember(conn, groups.split_merge, detections.mupet_split_a, "source_split_detection");
insertMatchMember(conn, groups.split_merge, detections.mupet_split_b, "source_split_detection");

consensus = struct();
consensus.one_to_one = insertConsensusEvent(conn, analysisRunId, groups.one_to_one, recordingId, 10.002, 10.051, "mean_boundary_consensus", "accepted", 0.94);
insertConsensusMember(conn, consensus.one_to_one, detections.ds_match, "deepsqueak_source");
insertConsensusMember(conn, consensus.one_to_one, detections.mupet_match, "mupet_source");

consensus.split_merge = insertConsensusEvent(conn, analysisRunId, groups.split_merge, recordingId, 40.001, 40.099, "union_boundary_split_merge", "accepted", 0.72);
insertConsensusMember(conn, consensus.split_merge, detections.ds_long, "long_source");
insertConsensusMember(conn, consensus.split_merge, detections.mupet_split_a, "split_source");
insertConsensusMember(conn, consensus.split_merge, detections.mupet_split_b, "split_source");

insertConsilienceAssessment(conn, analysisRunId, groups.one_to_one, NaN, "supported", 0.94, "one_to_one_temporal_overlap");
insertConsilienceAssessment(conn, analysisRunId, groups.split_merge, NaN, "split_merge_supported", 0.72, "split_merge_temporal_coverage");
insertConsilienceAssessment(conn, analysisRunId, NaN, consensus.one_to_one, "accepted_consensus", 0.94, "consensus_from_two_extractors");
end

function insertCandidatePair(conn, analysisRunId, recordingId, detectionAId, detectionBId, overlap, iou, onsetDiff, offsetDiff, durationDiff, score, status)
values = struct( ...
    analysis_run_id=analysisRunId, ...
    recording_id=recordingId, ...
    detection_a_id=detectionAId, ...
    detection_b_id=detectionBId, ...
    temporal_overlap_s=overlap, ...
    temporal_iou=iou, ...
    onset_difference_s=onsetDiff, ...
    offset_difference_s=offsetDiff, ...
    duration_difference_s=durationDiff, ...
    candidate_score=score, ...
    candidate_status=status, ...
    details_json=jsonencode(struct(fixture=true)));
if detectionAId > detectionBId
    values.detection_a_id = detectionBId;
    values.detection_b_id = detectionAId;
end
insertRow(conn, "candidate_pairs", values, "candidate_pair_id");
end

function groupId = insertMatchGroup(conn, analysisRunId, recordingId, matchType, ambiguityStatus, score, notes)
groupId = insertRow(conn, "match_groups", struct( ...
    analysis_run_id=analysisRunId, ...
    recording_id=recordingId, ...
    match_type=matchType, ...
    ambiguity_status=ambiguityStatus, ...
    match_score=score, ...
    notes=notes), "match_group_id");
end

function insertMatchMember(conn, groupId, detectionId, role)
insertRow(conn, "match_group_members", struct( ...
    match_group_id=groupId, ...
    detection_id=detectionId, ...
    member_role=role));
end

function consensusEventId = insertConsensusEvent(conn, analysisRunId, groupId, recordingId, startS, endS, method, status, score)
consensusEventId = insertRow(conn, "consensus_events", struct( ...
    analysis_run_id=analysisRunId, ...
    match_group_id=groupId, ...
    recording_id=recordingId, ...
    start_time_s=startS, ...
    end_time_s=endS, ...
    derivation_method=method, ...
    consensus_status=status, ...
    confidence_score=score, ...
    notes="Synthetic fixture consensus event retaining source detections."), "consensus_event_id");
end

function insertConsensusMember(conn, consensusEventId, detectionId, role)
insertRow(conn, "consensus_event_members", struct( ...
    consensus_event_id=consensusEventId, ...
    detection_id=detectionId, ...
    member_role=role));
end

function insertConsilienceAssessment(conn, analysisRunId, matchGroupId, consensusEventId, status, score, rationale)
values = struct( ...
    analysis_run_id=analysisRunId, ...
    status=status, ...
    score=score, ...
    rationale_json=jsonencode(struct(rule=rationale)));
if ~isnan(matchGroupId)
    values.match_group_id = matchGroupId;
end
if ~isnan(consensusEventId)
    values.consensus_event_id = consensusEventId;
end
insertRow(conn, "consilience_assessments", values, "consilience_assessment_id");
end

function insertManualReviews(conn, analysisRunId, detections, groups, consensus, fixture)
insertRow(conn, "manual_reviews", struct( ...
    analysis_run_id=analysisRunId, ...
    detection_id=detections.ds_only, ...
    reviewer_label="fixture_reviewer", ...
    review_status="adjudicated_false_positive", ...
    reviewed_at_utc=fixture.timestamp_utc, ...
    notes="Manual review intentionally differs from DeepSqueak Accepted curation state."), "manual_review_id");
insertRow(conn, "manual_reviews", struct( ...
    analysis_run_id=analysisRunId, ...
    match_group_id=groups.split_merge, ...
    reviewer_label="fixture_reviewer", ...
    review_status="split_merge_confirmed", ...
    reviewed_at_utc=fixture.timestamp_utc, ...
    notes="Manual adjudication confirms split/merge match group."), "manual_review_id");
insertRow(conn, "manual_reviews", struct( ...
    analysis_run_id=analysisRunId, ...
    consensus_event_id=consensus.one_to_one, ...
    reviewer_label="fixture_reviewer", ...
    review_status="accepted_consensus", ...
    corrected_start_time_s=10.002, ...
    corrected_end_time_s=10.051, ...
    reviewed_at_utc=fixture.timestamp_utc, ...
    notes="Consensus-level review remains separate from native extractor state."), "manual_review_id");
end

function [timebases, streams, events, alignmentRunId] = insertExternalAlignmentRows(conn, projectId, recordingId, behaviorSourceFileId, entities, analysisRunId)
timebases = struct();
timebases.recording = insertTimebase(conn, projectId, recordingId, "recording_elapsed_time", "audio_sample_clock", "s", 384000, "Audio file sample clock.", "REC_SOCIAL_DYAD_01");
timebases.behavior = insertTimebase(conn, projectId, recordingId, "behavior_controller_clock", "behavior_controller_clock", "s", 100, "Controller event-log clock.", "CTRL_A");

streams = struct();
streams.behavior = insertRow(conn, "external_streams", struct( ...
    project_id=projectId, ...
    recording_id=recordingId, ...
    source_file_id=behaviorSourceFileId, ...
    timebase_id=timebases.behavior, ...
    stream_name="fixture_social_behavior_events", ...
    stream_kind="event", ...
    modality="behavior", ...
    units="s", ...
    notes="Synthetic external event stream for alignment fixture."), "external_stream_id");

events = struct();
events.contact = insertExternalEvent(conn, streams.behavior, entities.dyad, "BEH_001", "social_contact", 9.450, 10.950, "contact");
events.approach = insertExternalEvent(conn, streams.behavior, entities.subject_male, "BEH_002", "male_approach", 39.450, 40.000, "approach");

alignmentRunId = insertRow(conn, "time_alignment_runs", struct( ...
    analysis_run_id=analysisRunId, ...
    source_timebase_id=timebases.behavior, ...
    target_timebase_id=timebases.recording, ...
    method="affine_offset_from_synthetic_anchors", ...
    fit_rmse_s=0.001, ...
    max_error_s=0.002, ...
    status="validated", ...
    notes="Fixture alignment uses target_time = source_time + 0.55."), "alignment_run_id");

insertAlignmentAnchor(conn, alignmentRunId, 0.000, 0.550, "synthetic_start_marker");
insertAlignmentAnchor(conn, alignmentRunId, 59.000, 59.550, "synthetic_end_marker");
insertRow(conn, "alignment_segments", struct( ...
    alignment_run_id=alignmentRunId, ...
    segment_index=1, ...
    source_start=0, ...
    source_end=60, ...
    scale=1, ...
    offset_s=0.55, ...
    rmse_s=0.001, ...
    uncertainty_s=0.002), "alignment_segment_id");

insertAlignedExternalEvent(conn, events.contact, alignmentRunId, timebases.recording, 10.000, 11.500);
insertAlignedExternalEvent(conn, events.approach, alignmentRunId, timebases.recording, 40.000, 40.550);
end

function timebaseId = insertTimebase(conn, projectId, recordingId, name, kind, unit, rateHz, origin, clockId)
timebaseId = insertRow(conn, "timebases", struct( ...
    project_id=projectId, ...
    recording_id=recordingId, ...
    timebase_name=name, ...
    timebase_kind=kind, ...
    native_unit=unit, ...
    nominal_rate_hz=rateHz, ...
    origin_description=origin, ...
    clock_identifier=clockId), "timebase_id");
end

function eventId = insertExternalEvent(conn, streamId, entityId, nativeEventId, eventType, startNative, endNative, label)
eventId = insertRow(conn, "external_events", struct( ...
    external_stream_id=streamId, ...
    entity_id=entityId, ...
    native_event_id=nativeEventId, ...
    event_type=eventType, ...
    start_time_native=startNative, ...
    end_time_native=endNative, ...
    value_text=label, ...
    unit="s", ...
    source_locator="phase1_synthetic_fixture.md"), "external_event_id");
end

function insertAlignmentAnchor(conn, alignmentRunId, sourceTime, targetTime, anchorType)
insertRow(conn, "alignment_anchors", struct( ...
    alignment_run_id=alignmentRunId, ...
    source_time=sourceTime, ...
    target_time=targetTime, ...
    anchor_type=anchorType, ...
    source_reference="synthetic behavior event log", ...
    target_reference="synthetic recording elapsed time", ...
    uncertainty_s=0.002), "alignment_anchor_id");
end

function insertAlignedExternalEvent(conn, externalEventId, alignmentRunId, targetTimebaseId, startS, endS)
insertRow(conn, "aligned_external_events", struct( ...
    external_event_id=externalEventId, ...
    alignment_run_id=alignmentRunId, ...
    target_timebase_id=targetTimebaseId, ...
    start_time_aligned_s=startS, ...
    end_time_aligned_s=endS, ...
    uncertainty_s=0.002), "aligned_external_event_id");
end

function summary = buildSummary(conn, projectId, fixture, semanticSummary)
summary = struct();
summary.repo_root = fixture.repo_root;
summary.fixture_source = fixture.fixture_source;
summary.project_key = fixture.project_key;
summary.project_id = projectId;
summary.semantic_registration = semanticSummary;
summary.counts = fixtureCounts(conn, projectId);
summary.foreign_key_violation_count = foreignKeyViolationCount(conn);
summary.stability_signature = fixtureSignature(conn, fixture.project_key);
summary.notes = [
    "Fixture intentionally repeats native event id 1 across extractor/run/artifact scopes."
    "DeepSqueak Accepted curation is stored separately from manual adjudication."
    "External alignment uses target_time = source_time + 0.55."
];
end

function counts = fixtureCounts(conn, projectId)
counts = struct();
counts.projects = countWhere(conn, "projects", "project_id = " + string(projectId));
counts.project_profile_assignments = countWhere(conn, "project_profile_assignments", "project_id = " + string(projectId));
counts.example_profile_versions = fetchScalarDouble(conn, ...
    "SELECT COUNT(*) AS n FROM config_profile_versions cpv JOIN config_profiles cp ON cp.profile_id = cpv.profile_id " + ...
    "WHERE cp.profile_key IN ('example.device.ultrasonic_usb_primary', 'example.setup.mouse_courtship_chamber')");
counts.source_files = countWhere(conn, "source_files", "project_id = " + string(projectId));
counts.entity_types = countWhere(conn, "entity_types", "project_id = " + string(projectId));
counts.experimental_entities = countWhere(conn, "experimental_entities", "project_id = " + string(projectId));
counts.entity_relationships = countWhere(conn, "entity_relationships", "project_id = " + string(projectId));
counts.entity_profile_assignments = fetchScalarDouble(conn, ...
    "SELECT COUNT(*) AS n FROM entity_profile_assignments epa JOIN experimental_entities ee ON ee.entity_id = epa.entity_id " + ...
    "WHERE ee.project_id = " + string(projectId));
counts.recordings = countWhere(conn, "recordings", "project_id = " + string(projectId));
counts.recording_channels = joinedProjectCount(conn, "recording_channels rc JOIN recordings r ON r.recording_id = rc.recording_id", projectId);
counts.recording_entity_links = joinedProjectCount(conn, "recording_entity_links rel JOIN recordings r ON r.recording_id = rel.recording_id", projectId);
counts.recording_attributes = joinedProjectCount(conn, "recording_attributes ra JOIN recordings r ON r.recording_id = ra.recording_id", projectId);
counts.recording_profile_assignments = joinedProjectCount(conn, "recording_profile_assignments rpa JOIN recordings r ON r.recording_id = rpa.recording_id", projectId);
counts.recording_epochs = joinedProjectCount(conn, "recording_epochs ep JOIN recordings r ON r.recording_id = ep.recording_id", projectId);
counts.artifacts = countWhere(conn, "artifacts", "project_id = " + string(projectId));
counts.extraction_runs = countWhere(conn, "extraction_runs", "project_id = " + string(projectId));
counts.extraction_run_inputs = fetchScalarDouble(conn, ...
    "SELECT COUNT(*) AS n FROM extraction_run_inputs eri JOIN extraction_runs er ON er.extraction_run_id = eri.extraction_run_id " + ...
    "WHERE er.project_id = " + string(projectId));
counts.extraction_run_profiles = fetchScalarDouble(conn, ...
    "SELECT COUNT(*) AS n FROM extraction_run_profiles erp JOIN extraction_runs er ON er.extraction_run_id = erp.extraction_run_id " + ...
    "WHERE er.project_id = " + string(projectId));
counts.extraction_run_artifacts = fetchScalarDouble(conn, ...
    "SELECT COUNT(*) AS n FROM extraction_run_artifacts era JOIN extraction_runs er ON er.extraction_run_id = era.extraction_run_id " + ...
    "WHERE er.project_id = " + string(projectId));
counts.extractor_objects = fetchScalarDouble(conn, ...
    "SELECT COUNT(*) AS n FROM extractor_objects xo JOIN extraction_runs er ON er.extraction_run_id = xo.extraction_run_id " + ...
    "WHERE er.project_id = " + string(projectId));
counts.extractor_object_recordings = fetchScalarDouble(conn, ...
    "SELECT COUNT(*) AS n FROM extractor_object_recordings xmap JOIN extractor_objects xo ON xo.extractor_object_id = xmap.extractor_object_id " + ...
    "JOIN extraction_runs er ON er.extraction_run_id = xo.extraction_run_id WHERE er.project_id = " + string(projectId));
counts.detections = joinedProjectCount(conn, "detections d JOIN recordings r ON r.recording_id = d.recording_id", projectId);
counts.event_measurements = fetchScalarDouble(conn, ...
    "SELECT COUNT(*) AS n FROM event_measurements em JOIN detections d ON d.detection_id = em.detection_id " + ...
    "JOIN recordings r ON r.recording_id = d.recording_id WHERE r.project_id = " + string(projectId));
counts.curation_events = fetchScalarDouble(conn, ...
    "SELECT COUNT(*) AS n FROM curation_events ce JOIN detections d ON d.detection_id = ce.detection_id " + ...
    "JOIN recordings r ON r.recording_id = d.recording_id WHERE r.project_id = " + string(projectId));
counts.analysis_runs = countWhere(conn, "analysis_runs", "project_id = " + string(projectId));
counts.candidate_pairs = analysisProjectCount(conn, "candidate_pairs cp JOIN analysis_runs ar ON ar.analysis_run_id = cp.analysis_run_id", projectId);
counts.match_groups = analysisProjectCount(conn, "match_groups mg JOIN analysis_runs ar ON ar.analysis_run_id = mg.analysis_run_id", projectId);
counts.match_group_members = fetchScalarDouble(conn, ...
    "SELECT COUNT(*) AS n FROM match_group_members mgm JOIN match_groups mg ON mg.match_group_id = mgm.match_group_id " + ...
    "JOIN analysis_runs ar ON ar.analysis_run_id = mg.analysis_run_id WHERE ar.project_id = " + string(projectId));
counts.consensus_events = analysisProjectCount(conn, "consensus_events ce JOIN analysis_runs ar ON ar.analysis_run_id = ce.analysis_run_id", projectId);
counts.consensus_event_members = fetchScalarDouble(conn, ...
    "SELECT COUNT(*) AS n FROM consensus_event_members cem JOIN consensus_events ce ON ce.consensus_event_id = cem.consensus_event_id " + ...
    "JOIN analysis_runs ar ON ar.analysis_run_id = ce.analysis_run_id WHERE ar.project_id = " + string(projectId));
counts.manual_reviews = analysisProjectCount(conn, "manual_reviews mr JOIN analysis_runs ar ON ar.analysis_run_id = mr.analysis_run_id", projectId);
counts.consilience_assessments = analysisProjectCount(conn, "consilience_assessments ca JOIN analysis_runs ar ON ar.analysis_run_id = ca.analysis_run_id", projectId);
counts.timebases = countWhere(conn, "timebases", "project_id = " + string(projectId));
counts.external_streams = countWhere(conn, "external_streams", "project_id = " + string(projectId));
counts.external_events = fetchScalarDouble(conn, ...
    "SELECT COUNT(*) AS n FROM external_events ee JOIN external_streams es ON es.external_stream_id = ee.external_stream_id " + ...
    "WHERE es.project_id = " + string(projectId));
counts.time_alignment_runs = analysisProjectCount(conn, "time_alignment_runs tar JOIN analysis_runs ar ON ar.analysis_run_id = tar.analysis_run_id", projectId);
counts.alignment_anchors = fetchScalarDouble(conn, ...
    "SELECT COUNT(*) AS n FROM alignment_anchors aa JOIN time_alignment_runs tar ON tar.alignment_run_id = aa.alignment_run_id " + ...
    "JOIN analysis_runs ar ON ar.analysis_run_id = tar.analysis_run_id WHERE ar.project_id = " + string(projectId));
counts.alignment_segments = fetchScalarDouble(conn, ...
    "SELECT COUNT(*) AS n FROM alignment_segments seg JOIN time_alignment_runs tar ON tar.alignment_run_id = seg.alignment_run_id " + ...
    "JOIN analysis_runs ar ON ar.analysis_run_id = tar.analysis_run_id WHERE ar.project_id = " + string(projectId));
counts.aligned_external_events = fetchScalarDouble(conn, ...
    "SELECT COUNT(*) AS n FROM aligned_external_events aee JOIN time_alignment_runs tar ON tar.alignment_run_id = aee.alignment_run_id " + ...
    "JOIN analysis_runs ar ON ar.analysis_run_id = tar.analysis_run_id WHERE ar.project_id = " + string(projectId));
end

function count = joinedProjectCount(conn, fromClause, projectId)
count = fetchScalarDouble(conn, "SELECT COUNT(*) AS n FROM " + fromClause + " WHERE r.project_id = " + string(projectId));
end

function count = analysisProjectCount(conn, fromClause, projectId)
count = fetchScalarDouble(conn, "SELECT COUNT(*) AS n FROM " + fromClause + " WHERE ar.project_id = " + string(projectId));
end

function count = countWhere(conn, tableName, whereClause)
count = fetchScalarDouble(conn, "SELECT COUNT(*) AS n FROM " + tableName + " WHERE " + whereClause);
end

function signature = fixtureSignature(conn, projectKey)
signature = struct();
signature.project_key = projectKey;
signature.entity_keys = queryKeyStrings(conn, ...
    "SELECT et.native_name, ee.native_id FROM experimental_entities ee " + ...
    "JOIN entity_types et ON et.entity_type_id = ee.entity_type_id " + ...
    "JOIN projects p ON p.project_id = ee.project_id WHERE p.project_key = " + sqlText(projectKey) + ...
    " ORDER BY et.native_name, ee.native_id");
signature.recordings = queryKeyStrings(conn, ...
    "SELECT native_recording_id, sample_rate_hz, duration_s FROM recordings r " + ...
    "JOIN projects p ON p.project_id = r.project_id WHERE p.project_key = " + sqlText(projectKey) + ...
    " ORDER BY native_recording_id");
signature.detections = queryKeyStrings(conn, ...
    "SELECT extractor_name, extraction_run_key, native_recording_id, native_event_id, start_time_s, end_time_s " + ...
    "FROM v_detection_core WHERE project_key = " + sqlText(projectKey) + ...
    " ORDER BY extractor_name, extraction_run_key, native_event_id, start_time_s");
signature.measurements = queryKeyStrings(conn, ...
    "SELECT vc.extractor_name, vc.extraction_run_key, vc.native_event_id, vml.native_name, IFNULL(vml.canonical_name, '') AS canonical_name, " + ...
    "IFNULL(vml.native_raw_token, '') AS native_raw_token, IFNULL(vml.native_value_real, -999999) AS native_value_real, " + ...
    "IFNULL(vml.canonical_value_real, -999999) AS canonical_value_real, IFNULL(vml.canonical_unit, '') AS canonical_unit " + ...
    "FROM v_event_measurements_long vml JOIN v_detection_core vc ON vc.detection_id = vml.detection_id " + ...
    "WHERE vc.project_key = " + sqlText(projectKey) + ...
    " ORDER BY vc.extractor_name, vc.extraction_run_key, vc.native_event_id, vml.native_name");
signature.matching = queryKeyStrings(conn, ...
    "SELECT mg.match_type, IFNULL(mg.ambiguity_status, '') AS ambiguity_status, COUNT(mgm.detection_id) AS member_count " + ...
    "FROM match_groups mg JOIN match_group_members mgm ON mgm.match_group_id = mg.match_group_id " + ...
    "JOIN analysis_runs ar ON ar.analysis_run_id = mg.analysis_run_id " + ...
    "JOIN projects p ON p.project_id = ar.project_id WHERE p.project_key = " + sqlText(projectKey) + ...
    " GROUP BY mg.match_group_id, mg.match_type, mg.ambiguity_status ORDER BY mg.match_type, ambiguity_status, member_count");
signature.alignment = queryKeyStrings(conn, ...
    "SELECT event_type, start_time_native, start_time_aligned_s, end_time_aligned_s " + ...
    "FROM v_external_events_aligned vea JOIN recordings r ON r.recording_id = vea.recording_id " + ...
    "JOIN projects p ON p.project_id = r.project_id WHERE p.project_key = " + sqlText(projectKey) + ...
    " ORDER BY event_type");
end

function count = foreignKeyViolationCount(conn)
violations = fetch(conn, "PRAGMA foreign_key_check");
count = height(violations);
end

function rows = queryKeyStrings(conn, sql)
tableData = fetch(conn, sql);
if height(tableData) == 0
    rows = strings(0, 1);
    return
end
values = strings(height(tableData), width(tableData));
names = tableData.Properties.VariableNames;
for col = 1:width(tableData)
    column = tableData.(names{col});
    values(:, col) = string(column);
end
rows = join(values, "|", 2);
end

function id = lookupSingleId(conn, sql)
rows = fetch(conn, sql);
if height(rows) ~= 1
    error("vawlume:db:FixtureLookupFailed", ...
        "Expected one row for lookup, found %d. SQL: %s", height(rows), sql);
end
id = double(rows.id(1));
end

function value = fetchScalarDouble(conn, sql)
rows = fetch(conn, sql);
value = double(rows.n(1));
end

function id = insertRow(conn, tableName, values, idColumn)
if nargin < 4
    idColumn = "";
end
idColumn = string(idColumn);
insertValues = stripEmptyOptionalFields(values);
names = fieldnames(insertValues);
rowStruct = struct();
for index = 1:numel(names)
    value = insertValues.(names{index});
    if isstring(value) || ischar(value) || iscellstr(value)
        rowStruct.(names{index}) = {char(normalizeText(value))};
    elseif islogical(value)
        value = value(:);
        rowStruct.(names{index}) = double(value(1));
    else
        value = value(:);
        rowStruct.(names{index}) = double(value(1));
    end
end
row = struct2table(rowStruct, "AsArray", true);
sqlwrite(conn, char(tableName), row);

id = NaN;
if strlength(idColumn) > 0
    result = fetch(conn, "SELECT last_insert_rowid() AS " + idColumn);
    id = double(result.(idColumn)(1));
end
end

function values = stripEmptyOptionalFields(values)
names = string(fieldnames(values));
for name = names'
    value = values.(name);
    if (isstring(value) || ischar(value)) && strlength(string(value)) == 0
        values = rmfield(values, char(name));
    end
end
end

function assertFixtureProjectAbsent(conn, projectKey)
count = fetchScalarDouble(conn, "SELECT COUNT(*) AS n FROM projects WHERE project_key = " + sqlText(projectKey));
if count > 0
    error("vawlume:db:FixtureAlreadyPresent", ...
        "Fixture project %s already exists. Build this fixture in a fresh temporary database.", projectKey);
end
end

function assertTextEquals(actual, expected, label)
actual = normalizeText(actual);
expected = normalizeText(expected);
if actual ~= expected
    error("vawlume:db:FixtureProfileConflict", ...
        "Conflicting %s. Existing value: %s. Expected value: %s.", label, actual, expected);
end
end

function text = normalizeText(raw)
text = string(raw);
if isempty(text) || ismissing(text)
    text = "";
else
    text = text(1);
end
end

function text = sqlText(value)
text = string(value);
text = "'" + replace(text, "'", "''") + "'";
end

function token = numericToken(value)
token = string(sprintf("%.12g", value));
end

function path = relativePath(path, repoRoot)
path = normalizePath(path);
repoRoot = normalizePath(repoRoot);
if strlength(repoRoot) == 0
    path = replace(path, filesep, "/");
    return
end
repoPrefix = repoRoot + string(filesep);
if startsWith(path, repoPrefix, "IgnoreCase", ispc)
    path = extractAfter(path, strlength(repoPrefix));
end
path = replace(path, filesep, "/");
end

function path = normalizePath(path)
path = string(path);
if strlength(path) == 0
    return
end
try
    path = string(java.io.File(char(path)).getCanonicalPath());
catch
    path = string(path);
end
end

function hash = sha256File(path)
if ~isfile(path)
    error("vawlume:db:FixtureProfileNotFound", ...
        "Fixture profile file does not exist: %s", path);
end
fileId = fopen(path, "r");
if fileId < 0
    error("vawlume:db:FixtureFileReadFailed", ...
        "Could not open file for hashing: %s", path);
end
cleaner = onCleanup(@() fclose(fileId));
bytes = fread(fileId, Inf, "*uint8")';

digest = java.security.MessageDigest.getInstance("SHA-256");
digest.update(typecast(bytes, "int8"));
hashBytes = typecast(digest.digest(), "uint8");
hash = lower(string(reshape(dec2hex(hashBytes, 2).', 1, [])));
delete(cleaner);
end

function repoRoot = defaultRepoRoot()
repoRoot = fileparts(fileparts(fileparts(fileparts(mfilename("fullpath")))));
repoRoot = string(repoRoot);
end
