function placements = readChannelPlacements(conn, recordingRef)
%READCHANNELPLACEMENTS Microphone placements of one recording's channels.
%
%   placements = VAWLUME.GEOMETRY.READCHANNELPLACEMENTS(conn, recordingRef)
%
% Returns one row per placed channel, ordered by channel index, carrying the
% channel identity, the cited frame's key, unit and dimensionality, and the
% coordinates. Channels with no placement are absent rather than returned with
% empty coordinates: no placement means nothing was declared, which is different
% from a declared position at the origin.
%
% position_z is NaN when the frame is 2-dimensional, and may also be NaN in a
% 3-dimensional frame when the height was not supplied.
%
% Read-only.
%
% See also VAWLUME.GEOMETRY.REGISTERCHANNELPLACEMENT,
% VAWLUME.GEOMETRY.ASSERTCOMPATIBLE

arguments
    conn
    recordingRef (1,1) struct
end

recording = geometryResolveRecording(conn, recordingRef);
rows = fetch(conn, "SELECT cp.channel_placement_id, cp.recording_channel_id, " + ...
    "rc.channel_index, IFNULL(rc.channel_label,'') AS channel_label, " + ...
    "cs.coordinate_system_id, cs.coordinate_system_key, cs.dimensionality, " + ...
    "cs.unit, cp.position_x, cp.position_y, " + ...
    "IFNULL(cp.position_z, 1e308) AS position_z, " + ...
    "IFNULL(cp.placement_role,'') AS placement_role, " + ...
    "IFNULL(cp.orientation_description,'') AS orientation_description, " + ...
    "IFNULL(cp.source_profile_version_id, -1) AS source_profile_version_id " + ...
    "FROM channel_placements cp " + ...
    "JOIN recording_channels rc ON rc.recording_channel_id=cp.recording_channel_id " + ...
    "JOIN coordinate_systems cs ON cs.coordinate_system_id=cp.coordinate_system_id " + ...
    "WHERE rc.recording_id=" + string(recording.recording_id) + ...
    " ORDER BY rc.channel_index");

if isempty(rows) || height(rows) == 0
    placements = emptyPlacements();
    return
end

positionZ = double(rows.position_z);
positionZ(positionZ == 1e308) = NaN;
profileVersion = double(rows.source_profile_version_id);
profileVersion(profileVersion < 0) = NaN;

placements = table(double(rows.channel_placement_id), ...
    double(rows.recording_channel_id), double(rows.channel_index), ...
    geometryPresentText(rows.channel_label), ...
    double(rows.coordinate_system_id), ...
    geometryPresentText(rows.coordinate_system_key), ...
    double(rows.dimensionality), geometryPresentText(rows.unit), ...
    double(rows.position_x), double(rows.position_y), positionZ, ...
    geometryPresentText(rows.placement_role), ...
    geometryPresentText(rows.orientation_description), profileVersion, ...
    VariableNames=placementVariableNames());
end

function value = emptyPlacements()
names = placementVariableNames();
types = repmat("double", 1, numel(names));
types(ismember(names, ["channel_label", "coordinate_system_key", "unit", ...
    "placement_role", "orientation_description"])) = "string";
value = table(Size=[0, numel(names)], VariableTypes=cellstr(types), ...
    VariableNames=cellstr(names));
end

function names = placementVariableNames()
names = ["channel_placement_id", "recording_channel_id", "channel_index", ...
    "channel_label", "coordinate_system_id", "coordinate_system_key", ...
    "dimensionality", "unit", "position_x", "position_y", "position_z", ...
    "placement_role", "orientation_description", "source_profile_version_id"];
end
