function demonstration = agreement_filter_demo(options)
%AGREEMENT_FILTER_DEMO Demonstrate analysis-ready agreement populations.
%
% DEMONSTRATION = AGREEMENT_FILTER_DEMO() creates the disposable Phase 1
% fixture, derives pairwise and arbitrary-N agreement analyses, selects exact
% and coarse agreement populations, and joins native member detections to
% time-bounded experimental context and long-form duration measurements.
%
% The early/late condition windows and all calls are synthetic. Summaries are
% descriptive only: no confidence score, biological truth label, inferential
% model, or consensus timing is created.
%
% Name-value options:
%   Print     print compact developer-facing read-backs (default true)
%   RepoRoot  repository root, inferred from this file by default

arguments
    options.Print (1,1) logical = true
    options.RepoRoot (1,1) string = ""
end

repoRoot = options.RepoRoot;
if strlength(repoRoot) == 0
    repoRoot = string(fileparts(fileparts(mfilename("fullpath"))));
end
sourcePath = fullfile(repoRoot, "src");
removePath = ~contains(path, sourcePath);
if removePath, addpath(sourcePath); end
cleanupPath = onCleanup(@() restorePath(sourcePath, removePath));

workspace = fullfile(tempdir, "VAWLUME agreement filter demo " + ...
    string(java.util.UUID.randomUUID));
mkdir(workspace);
cleanupWorkspace = onCleanup(@() removeTree(workspace));
databasePath = fullfile(workspace, "agreement_filter_demo.sqlite");
[conn, ~] = vawlume.db.createPhase1FixtureDatabase(databasePath, repoRoot);
cleanupConnection = onCleanup(@() closeConnection(conn));

seedDemoConditions(conn);
baselineSources = runBaselinePairwise(conn, repoRoot);
vawlume.agreement.compose(conn, socialRef(), baselineSources, ...
    struct(run_key="demo_agreement_baseline"), RepoRoot=repoRoot, Apply=true);
partialSources = runPartialShapePairwise(conn, repoRoot, workspace);
vawlume.agreement.compose(conn, socialRef(), partialSources, ...
    struct(run_key="demo_agreement_partial_shape"), ...
    RepoRoot=repoRoot, Apply=true);

baselineRef = struct(run_key="demo_agreement_baseline", ...
    project_key="phase1_synthetic_fixture");
partialRef = struct(run_key="demo_agreement_partial_shape", ...
    project_key="phase1_synthetic_fixture");
triple = "deepsqueak|mupet|usvseg";
allGroups = vawlume.agreement.selectPopulation(conn, baselineRef);
populations = struct( ...
    all_groups=allGroups, ...
    at_least_two_pairs=vawlume.agreement.selectPopulation(conn, baselineRef, ...
        MinSupportedPairCount=2), ...
    exact_all_three_pairs=vawlume.agreement.selectPopulation(conn, ...
        baselineRef, ExactSupportPattern=allPairPattern()), ...
    exact_ds_usvseg_and_mupet_usvseg=vawlume.agreement.selectPopulation(conn, ...
        partialRef, ExactSupportPattern=partialPairPattern()), ...
    clean_complete_triple=vawlume.agreement.selectPopulation(conn, ...
        baselineRef, ExtractorSetKey=triple, Completeness="complete", ...
        Cleanliness="clean", Multiplicity="one_per_extractor"), ...
    complete_ambiguous=vawlume.agreement.selectPopulation(conn, baselineRef, ...
        ExtractorSetKey=triple, Completeness="complete", ...
        Cleanliness="not_clean", Multiplicity="multiple_per_extractor"), ...
    extractor_unique=vawlume.agreement.selectPopulation(conn, baselineRef, ...
        Uniqueness="extractor_unique"));

memberContext = memberContextMeasurements(conn, allGroups);
demonstration = struct( ...
    populations=populations, ...
    population_summary=populationSummary(populations), ...
    member_context_measurements=memberContext, ...
    condition_counts=conditionCounts(memberContext), ...
    duration_summary=durationSummary(memberContext), ...
    foreign_key_check=fetch(conn, "PRAGMA foreign_key_check"), ...
    proves=[ ...
        "exact extractor-pair shapes remain distinct from coarse K-of-N filters"; ...
        "clean complete and complete ambiguous components remain separate"; ...
        "native group and member identities survive hierarchy and feature joins"; ...
        "descriptive counts and durations can be compared across context windows"], ...
    does_not_prove=[ ...
        "biological truth or caller attribution"; ...
        "empirical calibration of agreement strength or matching thresholds"; ...
        "inferential differences between experimental conditions"], ...
    temporary_artifacts_removed=false);

if options.Print, printDemo(demonstration); end
close(conn);
clear cleanupConnection
removeTree(workspace);
clear cleanupWorkspace
demonstration.temporary_artifacts_removed = ...
    ~isfolder(workspace) && ~isfile(databasePath);
clear cleanupPath
end

function keys = runBaselinePairwise(conn, repoRoot)
pairs = { ...
    {"demo_ds_mupet", "fixture_deepsqueak_social_v1", ...
        "fixture_mupet_social_v1"}, ...
    {"demo_ds_usvseg", "fixture_deepsqueak_social_v1", ...
        "fixture_usvseg_social_v1"}, ...
    {"demo_mupet_usvseg", "fixture_mupet_social_v1", ...
        "fixture_usvseg_social_v1"}};
keys = strings(numel(pairs), 1);
for index = 1:numel(pairs)
    pair = pairs{index};
    vawlume.matching.compare(conn, socialRef(), ...
        struct(run_a=pair{2}, run_b=pair{3}), ...
        struct(run_key=pair{1}), RepoRoot=repoRoot, Apply=true);
    keys(index) = pair{1};
end
end

function keys = runPartialShapePairwise(conn, repoRoot, workspace)
profilePath = writeStrictIouProfile(repoRoot, workspace);
pairs = { ...
    {"demo_strict_ds_mupet", "fixture_deepsqueak_social_v1", ...
        "fixture_mupet_social_v1"}, ...
    {"demo_strict_ds_usvseg", "fixture_deepsqueak_social_v1", ...
        "fixture_usvseg_social_v1"}, ...
    {"demo_strict_mupet_usvseg", "fixture_mupet_social_v1", ...
        "fixture_usvseg_social_v1"}};
keys = strings(numel(pairs), 1);
for index = 1:numel(pairs)
    pair = pairs{index};
    vawlume.matching.compare(conn, socialRef(), ...
        struct(run_a=pair{2}, run_b=pair{3}), ...
        struct(run_key=pair{1}, profile_path=profilePath), ...
        RepoRoot=repoRoot, Apply=true);
    keys(index) = pair{1};
end
end

function pathValue = writeStrictIouProfile(repoRoot, workspace)
source = fullfile(repoRoot, "config", "05_matching_profiles", ...
    "prototype_matching_consilience_spec.json");
text = string(fileread(source));
text = replace(text, """profile_version"": ""0.1.0""", ...
    """profile_version"": ""0.1.1""");
text = replace(text, """min_temporal_iou"": 0.10", ...
    """min_temporal_iou"": 0.47");
pathValue = fullfile(workspace, "strict_iou_matching_spec.json");
fileId = fopen(pathValue, "w");
assert(fileId >= 0, "Could not create the synthetic matching specification.");
closer = onCleanup(@() fclose(fileId));
fprintf(fileId, "%s", text);
clear closer
end

function seedDemoConditions(conn)
projectId = scalar(conn, "SELECT project_id AS n FROM projects " + ...
    "WHERE project_key='phase1_synthetic_fixture'");
recordingId = scalar(conn, "SELECT recording_id AS n FROM recordings " + ...
    "WHERE native_recording_id='REC_SOCIAL_DYAD_01'");
execute(conn, "INSERT INTO entity_types(project_id,native_name," + ...
    "canonical_role,hierarchy_order,is_biological_unit,is_subject_like," + ...
    "description) VALUES(" + string(projectId) + ...
    ",'demo_condition','experimental_condition',90,0,0," + ...
    "'Synthetic time-window context for the Phase 1.10 demonstration')");
typeId = scalar(conn, "SELECT entity_type_id AS n FROM entity_types " + ...
    "WHERE project_id=" + string(projectId) + ...
    " AND native_name='demo_condition'");
execute(conn, "INSERT INTO experimental_entities(project_id,entity_type_id," + ...
    "native_id,display_label) VALUES " + ...
    "(" + string(projectId) + "," + string(typeId) + ...
    ",'DEMO_EARLY','Synthetic early window')," + ...
    "(" + string(projectId) + "," + string(typeId) + ...
    ",'DEMO_LATE','Synthetic late window')");
execute(conn, "INSERT INTO recording_entity_links(recording_id,entity_id," + ...
    "link_type,role_label,start_time_s,end_time_s) SELECT " + ...
    string(recordingId) + ",entity_id,'experimental_condition'," + ...
    "CASE native_id WHEN 'DEMO_EARLY' THEN 'early' ELSE 'late' END," + ...
    "CASE native_id WHEN 'DEMO_EARLY' THEN 0 ELSE 35 END," + ...
    "CASE native_id WHEN 'DEMO_EARLY' THEN 35 ELSE 60 END " + ...
    "FROM experimental_entities WHERE entity_type_id=" + string(typeId));
end

function rows = memberContextMeasurements(conn, population)
ids = strjoin(string(population.detection_ids'), ",");
rows = fetch(conn, "SELECT m.agreement_group_id,m.group_key," + ...
    "m.detection_id,m.extractor_key,m.extractor_name,m.native_event_id," + ...
    "m.start_time_s,m.end_time_s,ctx.entity_id AS condition_entity_id," + ...
    "ctx.entity_native_id AS condition_key," + ...
    "IFNULL(ctx.role_label,'') AS condition_label," + ...
    "vm.canonical_value_real AS call_duration_s," + ...
    "IFNULL(vm.canonical_unit,'') AS duration_unit " + ...
    "FROM v_agreement_group_members m " + ...
    "JOIN v_recording_entity_context ctx ON ctx.recording_id=m.recording_id " + ...
    "AND ctx.entity_type='demo_condition' " + ...
    "AND (ctx.start_time_s IS NULL OR m.start_time_s>=ctx.start_time_s) " + ...
    "AND (ctx.end_time_s IS NULL OR m.start_time_s<ctx.end_time_s) " + ...
    "LEFT JOIN v_event_measurements_long vm ON vm.detection_id=m.detection_id " + ...
    "AND vm.canonical_name='call_duration' " + ...
    "WHERE m.analysis_run_id=" + string(population.analysis.analysis_run_id) + ...
    " AND m.detection_id IN (" + ids + ") " + ...
    "ORDER BY m.group_key,m.extractor_key,m.native_event_id,m.detection_id");
for name = ["group_key", "extractor_key", "extractor_name", ...
        "native_event_id", "condition_key", "condition_label", "duration_unit"]
    rows.(name) = presentText(rows.(name));
end
for name = ["agreement_group_id", "detection_id", "start_time_s", ...
        "end_time_s", "condition_entity_id", "call_duration_s"]
    rows.(name) = double(rows.(name));
end
end

function rows = populationSummary(populations)
fields = string(fieldnames(populations));
filterKey = strings(numel(fields), 1);
agreementRunKey = strings(numel(fields), 1);
groupCount = zeros(numel(fields), 1);
memberCount = zeros(numel(fields), 1);
for index = 1:numel(fields)
    population = populations.(fields(index));
    filterKey(index) = fields(index);
    agreementRunKey(index) = population.analysis.run_key;
    groupCount(index) = population.selected_group_count;
    memberCount(index) = population.selected_member_count;
end
rows = table(filterKey, agreementRunKey, groupCount, memberCount, ...
    VariableNames=["filter_key", "agreement_run_key", "group_count", ...
    "member_count"]);
end

function rows = conditionCounts(members)
contexts = unique(members(:, ["condition_key", "condition_label"]), ...
    "rows", "stable");
groupCount = zeros(height(contexts), 1);
memberCount = zeros(height(contexts), 1);
for index = 1:height(contexts)
    mask = members.condition_key == contexts.condition_key(index);
    groupCount(index) = numel(unique(members.agreement_group_id(mask)));
    memberCount(index) = nnz(mask);
end
rows = addvars(contexts, groupCount, memberCount);
end

function rows = durationSummary(members)
dimensions = unique(members(:, ["condition_key", "condition_label", ...
    "extractor_key", "extractor_name", "duration_unit"]), ...
    "rows", "stable");
memberCount = zeros(height(dimensions), 1);
meanDurationS = zeros(height(dimensions), 1);
minimumDurationS = zeros(height(dimensions), 1);
maximumDurationS = zeros(height(dimensions), 1);
for index = 1:height(dimensions)
    mask = members.condition_key == dimensions.condition_key(index) & ...
        members.extractor_key == dimensions.extractor_key(index);
    values = members.call_duration_s(mask);
    memberCount(index) = numel(values);
    meanDurationS(index) = mean(values);
    minimumDurationS(index) = min(values);
    maximumDurationS(index) = max(values);
end
rows = addvars(dimensions, memberCount, meanDurationS, ...
    minimumDurationS, maximumDurationS);
end

function printDemo(value)
fprintf('\nVAWLUME synthetic agreement-filter demonstration\n');
fprintf(['Agreement is methodological evidence, not a confidence probability ' ...
    'or biological truth label.\n']);
fprintf('Selected populations:\n');
disp(value.population_summary);
fprintf('Group and native-member counts by synthetic context window:\n');
disp(value.condition_counts);
fprintf('Native-member call durations by context window and extractor:\n');
disp(value.duration_summary);
fprintf('Proves:\n  %s\n', strjoin(value.proves, '\n  '));
fprintf('Does not prove:\n  %s\n', strjoin(value.does_not_prove, '\n  '));
end

function value = allPairPattern()
value = "deepsqueak--mupet|deepsqueak--usvseg|mupet--usvseg";
end

function value = partialPairPattern()
value = "deepsqueak--usvseg|mupet--usvseg";
end

function ref = socialRef()
ref = struct(project_key="phase1_synthetic_fixture", ...
    source_relative_path="synthetic/recordings/session_social_dyad_01.wav");
end

function value = scalar(conn, sql)
rows = fetch(conn, sql);
value = double(rows.(rows.Properties.VariableNames{1})(1));
end

function value = presentText(raw)
value = string(raw);
value(ismissing(value)) = "";
end

function restorePath(sourcePath, removePath)
if removePath && contains(path, sourcePath), rmpath(sourcePath); end
end

function closeConnection(conn)
if isopen(conn), close(conn); end
end

function removeTree(workspace)
if isfolder(workspace), rmdir(workspace, "s"); end
end
