function demonstration = backend_localization_demo(options)
%BACKEND_LOCALIZATION_DEMO Demonstrate the integrated Phase 5 backend/localization path.
%
% DEMONSTRATION = BACKEND_LOCALIZATION_DEMO() creates a disposable synthetic
% session and carries a localization backend's export through the whole
% attribution path: a recording with participating entities, two microphone
% channels, and a coordinate system shared with the tracking data; a backend
% export on the backend's own clock, previewed before it is imported; a fitted
% piecewise transform relating that clock to the recording's; correspondence
% across it; localization estimates with their frames; explicit promotion of the
% backend's caller scores into candidates and of its estimate, per-channel value
% and track reference into evidence; all five evidence dimensions side by side
% with no combined value; and a decision for every status the vocabulary has.
%
% A second, structurally different backend -- 3D, localization only, several
% ranked sources per window, covariance instead of a scalar confidence -- is
% imported over the same recording and read back through the same function, so
% optional z is visible both absent and present.
%
% The refusals are demonstrated beside the successes, in a harness that fails
% the example if a refusal stops refusing: an evidence row citing an estimate
% without declaring its frame, a backend export naming another project's frame,
% a caller label resolving outside the run's participants, a correspondence with
% no clock declaration, and a second apply.
%
% Nothing here is calibrated and nothing is validated. Every number is
% synthetic, both backends are invented, VAWLUME computes no distance and
% estimates no caller, and no result is evidence that any animal called. All
% inputs are created under the system temporary directory and removed before
% return.
%
% Name-value options:
%   Print     print compact developer-facing read-backs (default true)
%   RepoRoot  repository root, inferred from this file by default
%
% See also CALLER_ATTRIBUTION_DEMO, MULTIMODAL_INTEGRATION_DEMO

arguments
    options.Print (1,1) logical = true
    options.RepoRoot (1,1) string = ""
end

repoRoot = normalizedRepoRoot(options.RepoRoot);
sourcePath = fullfile(repoRoot, "src");
removeSourcePath = ~pathContains(sourcePath);
if removeSourcePath, addpath(sourcePath); end
cleanupPath = onCleanup(@() restoreSourcePath(sourcePath, removeSourcePath));

workspace = fullfile(tempdir, "VAWLUME phase 5 backend localization demo " + ...
    string(java.util.UUID.randomUUID));
mkdir(workspace);
cleanupWorkspace = onCleanup(@() removeTree(workspace));
databasePath = fullfile(workspace, "backend_localization_demo.sqlite");
conn = sqlite(char(databasePath), "create");
cleanupConnection = onCleanup(@() closeConnection(conn));

vawlume.db.applySchema(conn, fullfile(repoRoot, "schema", "schema.sql"));
vawlume.db.registerBuiltinSemantics(conn, repoRoot);

session = seedSession(conn, workspace);
geometry = declareGeometry(conn);
backendClock = establishBackendClock(conn, workspace, repoRoot);
tracking = registerTracking(conn, workspace, repoRoot);
profilePath = writeBackendProfile(workspace, repoRoot, "arena_2d", "demo");

refusals = emptyRefusals();

% --- Run 1: the caller-scoring backend, on its own clock ----------------------

mainRun = createRun(conn, session, "session01-backend", ...
    "Synthetic Localization Backend 1.0.0");

[refusals, ~] = recordRefusal(refusals, ...
    "a backend export whose positions name a frame declared only for another project", ...
    @() vawlume.ingest.backendAttribution(conn, runRef("session01-backend"), ...
        writeExport(workspace), RepoRoot=repoRoot, Apply=true, ...
        ProfilePath=writeBackendProfile(workspace, repoRoot, "other_lab_arena", ...
            "foreign-frame")));
[refusals, ~] = recordRefusal(refusals, ...
    "a backend caller label resolving to an animal outside the run's participants", ...
    @() vawlume.ingest.backendAttribution(conn, runRef("session01-backend"), ...
        writeOutsiderExport(workspace), ProfilePath=profilePath, ...
        RepoRoot=repoRoot, Apply=true));

exportPath = writeExport(workspace);
importPreview = vawlume.ingest.backendAttribution(conn, runRef("session01-backend"), ...
    exportPath, ProfilePath=profilePath, RepoRoot=repoRoot);
importResult = vawlume.ingest.backendAttribution(conn, runRef("session01-backend"), ...
    exportPath, ProfilePath=profilePath, RepoRoot=repoRoot, Apply=true);

[refusals, ~] = recordRefusal(refusals, ...
    "a second apply of the same backend export to the same run", ...
    @() vawlume.ingest.backendAttribution(conn, runRef("session01-backend"), ...
        exportPath, ProfilePath=profilePath, RepoRoot=repoRoot, Apply=true));
[refusals, ~] = recordRefusal(refusals, ...
    "a correspondence that did not say how the backend's clock relates to the recording's", ...
    @() vawlume.attribution.correspondWindows(conn, runRef("session01-backend")));

correspondence = vawlume.attribution.correspondWindows(conn, runRef("session01-backend"), ...
    AlignmentRun=backendClock.alignment_run_id, RepoRoot=repoRoot, Apply=true);

candidates = promoteClaimsToCandidates(conn, mainRun.target_ids);
anchorCandidate = candidateFor(conn, mainRun.target_ids(1), 1);
estimateId = estimateFor(conn, mainRun.attribution_run_id, "b1");

[refusals, ~] = recordRefusal(refusals, ...
    "a source-localization evidence row citing an estimate without declaring its frame", ...
    @() vawlume.attribution.addEvidence(conn, ...
        struct(attribution_candidate_id=anchorCandidate), ...
        struct(evidence_dimension="source_localization", ...
            evidence_kind="backend_source_location", ...
            attribution_localization_estimate_id=estimateId), Apply=true));

evidence = addFiveDimensionEvidence(conn, anchorCandidate, estimateId, ...
    mainRun, backendClock, tracking);

decision = vawlume.attribution.decide(conn, runRef("session01-backend"), struct(), ...
    RepoRoot=repoRoot, Apply=true, Targets=mainRun.target_ids(1:5));
mainReport = vawlume.attribution.report(conn, runRef("session01-backend"));

% --- Run 2: a structurally different backend over the same recording -----------

arrayRun = createRun(conn, session, "session01-array", "Synthetic Array Localizer 0.3");
arrayImport = vawlume.ingest.backendAttribution(conn, runRef("session01-array"), ...
    writeArrayExport(workspace), RepoRoot=repoRoot, Apply=true, ...
    ProfilePath=fullfile(repoRoot, "config", "01_mapping_profiles", "attribution", ...
        "generic_array_backend_attribution_profile.json"));
arrayCorrespondence = vawlume.attribution.correspondWindows(conn, ...
    runRef("session01-array"), SameClock=true, RepoRoot=repoRoot, Apply=true);
arrayReport = vawlume.attribution.report(conn, runRef("session01-array"));

% --- Read-back, QC and the boundaries -------------------------------------------

inventory = databaseInventory(conn);
foreignKeyCheck = fetch(conn, "PRAGMA foreign_key_check");

demonstration = struct( ...
    calibration_boundary="Every coordinate, confidence, score and threshold here " + ...
        "is a synthetic illustrative value from an invented backend. VAWLUME " + ...
        "computes no distance, transforms no frame, estimates no caller, and no " + ...
        "decision below means an animal called.", ...
    session=session, geometry=geometry, backend_clock=backendClock, ...
    tracking=tracking, ...
    main_run=struct(attribution_run_id=mainRun.attribution_run_id, ...
        target_count=numel(mainRun.target_ids)), ...
    import_preview=struct(status=importPreview.status, ...
        wrote_nothing=~importPreview.committed, ...
        window_count=height(importPreview.windows), ...
        claim_count=height(importPreview.claims), ...
        estimate_count=height(importPreview.estimates), ...
        unmapped_rows=importPreview.unmapped_rows, ...
        issues=importPreview.issues, ...
        resolutions=importPreview.resolutions), ...
    import=struct(status=importResult.status, ...
        applied_counts=importResult.applied_counts, ...
        exporting_system=importResult.exporting_system, ...
        profile=importResult.profile, ...
        source_checksum=importResult.source.checksum_sha256, ...
        not_written=importResult.not_written), ...
    correspondence=struct(iou_basis=correspondence.iou_basis, ...
        alignment_run_id=correspondence.alignment_run_id, ...
        rows=correspondence.correspondences(:, ["native_window_id", ...
            "attribution_target_id", "iou_basis", "aligned_start_s", ...
            "aligned_end_s", "temporal_iou"])), ...
    candidates=candidates, evidence=evidence, ...
    decisions=struct(rows=decision.decisions(:, ["attribution_target_id", ...
            "decision_status", "applied_threshold", "selected_count"]), ...
        run_completed=decision.run_completed), ...
    main_report=compactReport(mainReport), ...
    array_run=struct(attribution_run_id=arrayRun.attribution_run_id, ...
        import_status=arrayImport.status, ...
        applied_counts=arrayImport.applied_counts, ...
        correspondence_count=height(arrayCorrespondence.correspondences)), ...
    array_report=compactReport(arrayReport), ...
    same_read_surface=isequal(sort(string(fieldnames(mainReport))), ...
        sort(string(fieldnames(arrayReport)))), ...
    refusals=refusals, ...
    separation=struct(combined_value_computed=false, caller_estimated=false, ...
        distance_computed=false, ...
        evidence_dimensions_present=height(mainReport.qc.evidence_by_dimension), ...
        note="Five evidence dimensions -- temporal alignment, pose " + ...
            "localization, visual identity, acoustic and source localization -- " + ...
            "are stored, read and displayed side by side with their own units " + ...
            "and semantics. Nothing here combines them, and the decision policy " + ...
            "reads one candidate column and no evidence row."), ...
    database_inventory=inventory, foreign_key_check=foreignKeyCheck, ...
    proves=["a localization backend's export lands in the same canonical " + ...
        "attribution representation as an imported one, through one intake " + ...
        "function and one read surface"; ...
        "a localization estimate is stored once, in a declared frame, keyed " + ...
        "to the backend's own window, and reaches a target only by explicit " + ...
        "promotion"; ...
        "the backend's coordinates, confidences and scores keep their values, " + ...
        "their semantics and their producer"; ...
        "a backend window reaches a VAWLUME event only through a declared clock"; ...
        "five evidence dimensions sit on one candidate and nothing combines them"; ...
        "two structurally different backends read back through the same fields"; ...
        "the path refuses by name where guessing would look like success"], ...
    does_not_prove=["that any localized source was an animal, or the right one"; ...
        "that any backend's coordinates, confidences or scores are accurate or calibrated"; ...
        "that any real backend's export maps: both backends here are invented"; ...
        "that the backend and the tracker measured in the frame they both cite"; ...
        "that any caller was estimated: VAWLUME estimates none"; ...
        "that this representation is legible at realistic session scale"], ...
    temporary_artifacts_removed=false);

close(conn);
clear cleanupConnection
removeTree(workspace);
clear cleanupWorkspace
demonstration.temporary_artifacts_removed = ...
    ~isfolder(workspace) && ~isfile(databasePath);

if options.Print, printDemonstration(demonstration); end
clear cleanupPath
end

% ================================================================ session ===

function value = seedSession(conn, workspace)
%SEEDSESSION The upstream session, written directly where it has its own demo.
%
% Project intake and extractor import each have their own demonstration. What is
% seeded is what Phase 5 consumes: a recording, four entities of which three
% participate, six detections, and a second project that owns a frame this
% session must not use. The run's settings profile is registered through the
% public function, not by SQL.
execute(conn, "INSERT INTO projects(project_id,project_key,project_name) VALUES" + ...
    "(1,'backend_localization_demo','Backend localization demonstration')," + ...
    "(2,'other_lab','Another laboratory''s experiment')");
execute(conn, "INSERT INTO source_files(source_file_id,project_id,file_role," + ...
    "path_or_uri,relative_path) VALUES" + ...
    "(1,1,'recording_audio','synthetic/session01.wav','session01.wav')");
execute(conn, "INSERT INTO recordings(recording_id,project_id,source_file_id," + ...
    "native_recording_id,sample_rate_hz,channel_count,duration_s) " + ...
    "VALUES(1,1,1,'REC_BACKEND_01',250000,2,120)");
execute(conn, "INSERT INTO entity_types(entity_type_id,project_id,native_name," + ...
    "is_subject_like) VALUES(1,1,'mouse',1)");
execute(conn, "INSERT INTO experimental_entities(entity_id,project_id," + ...
    "entity_type_id,native_id) VALUES(1,1,1,'A'),(2,1,1,'B'),(3,1,1,'C'),(4,1,1,'D')");
% D exists in the project but was not in this recording.
execute(conn, "INSERT INTO recording_entity_links(recording_entity_link_id," + ...
    "recording_id,entity_id,link_type) VALUES" + ...
    "(1,1,1,'participant'),(2,1,2,'participant'),(3,1,3,'participant')");
execute(conn, "INSERT INTO extractors(extractor_id,extractor_key,extractor_name) " + ...
    "VALUES(90,'synthetic_primary','Synthetic primary extractor')");
execute(conn, "INSERT INTO extractor_versions(extractor_version_id,extractor_id," + ...
    "version_label) VALUES(90,90,'0.1-demo')");
execute(conn, "INSERT INTO extraction_runs(extraction_run_id,project_id," + ...
    "extractor_version_id,run_key) VALUES(1,1,90,'demo-primary')");
execute(conn, "INSERT INTO extraction_run_inputs(extraction_run_id,recording_id) VALUES(1,1)");
execute(conn, "INSERT INTO detections(detection_id,extraction_run_id,recording_id," + ...
    "native_event_id,start_time_s,end_time_s,timing_basis) VALUES" + ...
    "(1,1,1,'c01',10.00,10.30,'synthetic fixture')," + ...
    "(2,1,1,'c02',20.00,20.25,'synthetic fixture')," + ...
    "(3,1,1,'c03',30.00,30.20,'synthetic fixture')," + ...
    "(4,1,1,'c04',50.00,50.30,'synthetic fixture')," + ...
    "(5,1,1,'c05',60.00,60.20,'synthetic fixture')," + ...
    "(6,1,1,'c06',70.00,70.30,'synthetic fixture')");
settingsPath = fullfile(workspace, "backend_run_settings.json");
writeText(settingsPath, "{""note"": ""Synthetic backend attribution run settings.""}" + newline);
settings = vawlume.db.registerProfileVersion(conn, struct(project_id=1), struct( ...
    profile_key="demo-backend-settings", profile_name="Backend attribution run settings", ...
    version_label="1.0.0", content_path=settingsPath));
value = struct(project_key="backend_localization_demo", recording_id=1, ...
    native_recording_id="REC_BACKEND_01", participating_entities=["A"; "B"; "C"], ...
    non_participant="D", detection_count=6, ...
    settings_profile_version_id=settings.profile_version_id, ...
    seeded_directly=["two projects, the recording and its source file"; ...
        "four entities, three of them participants"; ...
        "one extraction run and its six detections"]);
end

function value = declareGeometry(conn)
%DECLAREGEOMETRY Frames and microphones, through the public functions that own them.
%
% arena_2d is the frame the tracker and the caller-scoring backend share.
% arena_3d is the array backend's. other_lab_arena belongs to another project:
% same dimensionality, same unit, and still not this experiment's frame.
for spec = [struct(key="arena_2d", name="Arena floor", dimensionality=2, unit="cm"), ...
        struct(key="arena_3d", name="Arena volume", dimensionality=3, unit="mm")]
    vawlume.geometry.registerCoordinateSystem(conn, ...
        struct(project_key="backend_localization_demo"), struct( ...
        coordinate_system_key=spec.key, coordinate_system_name=spec.name, ...
        dimensionality=spec.dimensionality, unit=spec.unit));
end
vawlume.geometry.registerCoordinateSystem(conn, struct(project_key="other_lab"), ...
    struct(coordinate_system_key="other_lab_arena", ...
    coordinate_system_name="Another laboratory's arena", dimensionality=2, unit="cm"));
left = vawlume.geometry.registerRecordingChannel(conn, struct(recording_id=1), ...
    struct(channel_index=1, channel_label="mic_left", channel_role="attribution_reference"));
right = vawlume.geometry.registerRecordingChannel(conn, struct(recording_id=1), ...
    struct(channel_index=2, channel_label="mic_right", channel_role="attribution_reference"));
value = struct(frames=["arena_2d (2D, cm; shared with tracking)"; ...
        "arena_3d (3D, mm)"; "other_lab_arena (another project)"], ...
    channel_ids=[left.recording_channel_id; right.recording_channel_id], ...
    channel_labels=["mic_left"; "mic_right"], ...
    note="A channel index is a caller assertion; nothing inspects the audio.");
end

% ============================================================ backend clock ===

function value = establishBackendClock(conn, workspace, repoRoot)
%ESTABLISHBACKENDCLOCK Relate the backend's clock to the recording's.
%
% The Phase 4 demonstration's recipe: synchronization anchors observed on both
% clocks, a manifest, intake, and a piecewise-affine fit through the public
% alignment layer. Attribution reaches the result only through that layer.
truth = backendClockTruth();
writeAnchorTable(fullfile(workspace, "sync_anchors.csv"), truth);
anchorProfilePath = writeAnchorProfile(workspace, repoRoot);
manifestPath = writeManifest(workspace, anchorProfilePath);
vawlume.ingest.alignment(conn, manifestPath, RepoRoot=repoRoot, ...
    SourceRoot=workspace, Apply=true);
fitResult = vawlume.alignment.fit(conn, alignmentRef(), ...
    SourceTimebase="backend_native", Breakpoints=truth.breakpoint, Apply=true);
qc = vawlume.alignment.report(conn, alignmentRef());
transform = qc.transforms(qc.transforms.source_timebase_key == "backend_native", :);
value = struct(source_timebase="backend_native", ...
    reference_timebase=string(qc.reference_timebase.timebase_key(1)), ...
    alignment_run_id=double(transform.alignment_run_id(1)), ...
    method=string(transform.method(1)), status=string(transform.status(1)), ...
    fit_status=string(fitResult.status), breakpoint=truth.breakpoint, ...
    note="A fitted transform is estimated, never validated.");
end

function truth = backendClockTruth()
truth = struct();
truth.breakpoint = 35;
truth.scale = [1.002; 0.998];
truth.offset_s = [5.00; (truth.scale(1) - truth.scale(2)) * truth.breakpoint + 5.00];
truth.source_times = [3; 15; 25; 35; 45; 60];
segment = 1 + double(truth.source_times >= truth.breakpoint);
truth.reference_times = truth.scale(segment) .* truth.source_times + truth.offset_s(segment);
truth.anchor_keys = "sync" + compose("%02d", (1:numel(truth.source_times))');
end

function writeAnchorTable(pathValue, truth)
count = numel(truth.anchor_keys);
markers = strings(2 * count, 1);
streams = strings(2 * count, 1);
timestamps = strings(2 * count, 1);
row = 0;
for index = 1:count
    row = row + 1;
    markers(row) = truth.anchor_keys(index);
    streams(row) = "backend";
    timestamps(row) = compose("%.9f", truth.source_times(index));
    row = row + 1;
    markers(row) = truth.anchor_keys(index);
    streams(row) = "audio";
    timestamps(row) = compose("%.9f", truth.reference_times(index));
end
writetable(table(markers, streams, timestamps, repmat("primary", 2 * count, 1), ...
    repmat("true", 2 * count, 1), repmat("device_level", 2 * count, 1), ...
    VariableNames=["marker", "stream", "timestamp_s", "role", "include", ...
    "evidence_class"]), pathValue, QuoteStrings="minimal");
end

function pathValue = writeAnchorProfile(workspace, repoRoot)
document = jsondecode(fileread(fullfile(repoRoot, "config", ...
    "01_mapping_profiles", "alignment_anchors", "long_anchor_mapping_profile.json")));
document.profile.id = "vawlume.alignment.anchor.long.phase5_demo.v1";
document.profile.name = "Synthetic backend-clock anchor profile";
document.context.declared_timebases = {'audio_native'; 'backend_native'};
audio = document.context.stream_timebases(1);
audio.native_value = "audio";
audio.stream_key = "audio_sync";
audio.timebase_key = "audio_native";
backend = audio;
backend.native_value = "backend";
backend.stream_key = "backend_sync";
backend.timebase_key = "backend_native";
document.context.stream_timebases = [audio; backend];
pair = document.context.fit_pairs(1);
pair.source_timebase_key = "backend_native";
pair.reference_timebase_key = "audio_native";
document.context.fit_pairs = pair;
pathValue = fullfile(workspace, "phase5_anchor_profile.json");
writeText(pathValue, string(jsonencode(document, PrettyPrint=true)) + newline);
end

function pathValue = writeManifest(workspace, anchorProfilePath)
document = struct();
document.manifest = struct(manifest_schema_version="0.1-draft", ...
    manifest_version="0.1.0", alignment_key="phase5_backend_clock", ...
    label="Backend clock against the recording clock", ...
    notes="Synthetic. No clock here is a real device.");
document.session = struct(project_key="backend_localization_demo", ...
    recording=struct(native_recording_id="REC_BACKEND_01"));
document.reference_timebase = "audio_native";
document.method = "piecewise_affine";
document.timebases = {struct(timebase_key="audio_native", ...
        timebase_kind="audio_sample_clock", recording_native=true, ...
        native_unit="s", origin_description="Recording file time zero."), ...
    struct(timebase_key="backend_native", timebase_kind="backend_system_clock", ...
        recording_native=false, native_unit="s", ...
        origin_description="The localization backend's own start.")};
document.anchors = struct(source="sync_anchors.csv", ...
    mapping_profile=char(anchorProfilePath), file_role="alignment_anchor_table");
pathValue = fullfile(workspace, "phase5_alignment_manifest.json");
writeText(pathValue, string(jsonencode(document, PrettyPrint=true)) + newline);
end

function value = alignmentRef()
value = struct(project_key="backend_localization_demo", run_key="phase5_backend_clock");
end

% ================================================================= tracking ===

function value = registerTracking(conn, workspace, repoRoot)
%REGISTERTRACKING The tracker the backend's video association refers to.
%
% The tracking stream shares arena_2d with the caller-scoring backend. The
% association says which entity track_a may denote; the backend names track_a,
% and intake checks the association exists rather than creating one.
artifactPath = fullfile(workspace, "tracking.csv");
writetable(table([0; 10; 20; 40; 60; 80], repmat("track_a", 6, 1), ...
    repmat("snout", 6, 1), [0; 1; 2; 3; 4; 5], repmat(10, 6, 1), ...
    repmat(0.73, 6, 1), VariableNames=["time_s", "track", "bodypart", ...
    "x", "y", "likelihood"]), artifactPath, QuoteStrings="minimal");
profile = jsondecode(fileread(fullfile(repoRoot, "config", "01_mapping_profiles", ...
    "tracking", "generic_tracking_mapping_profile.json")));
profile.profiles.columns.track_label.source_field = "track";
profile.profiles.context.coordinate_system_key = "arena_2d";
profilePath = fullfile(workspace, "tracking_profile.json");
writeText(profilePath, string(jsonencode(profile, PrettyPrint=true)) + newline);
registration = vawlume.tracking.register(conn, struct(recording_id=1), ...
    struct(artifact_path="tracking.csv", profile_path=profilePath, ...
    timebase_key="audio_native"), Apply=true, RepoRoot=repoRoot, SourceRoot=workspace);
association = vawlume.tracking.registerIdentityAssociation(conn, ...
    struct(project_key="backend_localization_demo", stream_name="tracking_primary"), ...
    struct(native_track_id="track_a", entity_native_id="A", start_time_native=0, ...
    end_time_native=80, assignment_state="candidate", ...
    evidence_kind="reidentification_score", identity_value=0.55, ...
    identity_value_semantics="cosine_similarity_of_appearance_embeddings", ...
    calibration_status="uncalibrated", review_state="unreviewed"));
value = struct(stream_name="tracking_primary", frame="arena_2d", ...
    association_id=double(association.tracking_identity_association_id), ...
    dense_samples_stored=registration.dense_samples_stored);
end

% ================================================================== backend ===

function pathValue = writeBackendProfile(workspace, repoRoot, frameKey, suffix)
%WRITEBACKENDPROFILE The shipped template, pointed at this session.
%
% The backend knows animals A, B and X; X is declared to be D, who was not in
% this recording. It declares that it consumed the acoustic and pose evidence
% and not the visual identity evidence; temporal alignment is left undeclared.
document = jsondecode(fileread(fullfile(repoRoot, "config", "01_mapping_profiles", ...
    "attribution", "generic_backend_attribution_profile.json")));
entry = document.profiles(1);
entry.profile.id = "vawlume.attribution.demo_backend." + suffix + ".v0_1";
entry.profile.name = "Synthetic localization-backend export";
entry.profile.profile_version = "0.1.0-demo";
entry.context.exporting_system = "Synthetic Localization Backend";
entry.context.exporting_system_version = "1.0.0";
entry.context.coordinate_system_key = frameKey;
entry.context.tracking_stream_key = "tracking_primary";
entry.context.window_timebase_key = "backend_native";
map = entry.caller_label_resolution.map;
map(end + 1) = struct(caller_label="X", entity_native_id="D");
entry.caller_label_resolution.map = map;
entry.declared_inputs.declarations = struct(acoustic="used", ...
    pose_localization="used", visual_identity="not_used");
document.profiles = entry;
pathValue = fullfile(workspace, "demo_backend_profile_" + suffix + ".json");
writeText(pathValue, string(jsonencode(document, PrettyPrint=true)) + newline);
end

function pathValue = writeExport(workspace)
% On the backend's clock: each window's times are the recording-clock event
% times expressed in backend seconds under the fitted clock. b1-b5 cover c01-c05;
% c06 has no backend window at all. b9 ends before it starts and is reported,
% not dropped.
pathValue = fullfile(workspace, "backend_export.csv");
writeText(pathValue, strjoin([ ...
    "segment_id,start_s,end_s,candidate,assignment_score,track,source_x,source_y,localization_confidence,mic1_power,mic2_power,err_major"
    "b1,4.99,5.29,A,0.95,track_a,10.5,20.25,0.9,-41.25,-45,3.5"
    "b1,4.99,5.29,B,0.10,,10.5,20.25,0.9,-41.25,-45,3.5"
    "b2,14.97,15.22,A,0.85,,30,40,0.7,-43,-44,"
    "b2,14.97,15.22,B,0.80,,30,40,0.7,-43,-44,"
    "b3,24.95,25.15,A,0.60,,50,60,,-45,-45.5,"
    "b3,24.95,25.15,B,0.55,,50,60,,,,"
    "b4,44.95,45.25,A,0.30,,70,10,0.4,,,"
    "b4,44.95,45.25,B,0.20,,70,10,0.4,,,"
    "b5,54.97,55.17,A,,,80,15,0.5,,,"
    "b9,90.00,89.50,A,0.30,,,,,,,"], newline) + newline);
end

function pathValue = writeOutsiderExport(workspace)
pathValue = fullfile(workspace, "backend_export_outsider.csv");
writeText(pathValue, strjoin([ ...
    "segment_id,start_s,end_s,candidate,assignment_score,track,source_x,source_y,localization_confidence,mic1_power,mic2_power,err_major"
    "b1,4.99,5.29,X,0.70,,10.5,20.25,0.9,,,"], newline) + newline);
end

function pathValue = writeArrayExport(workspace)
% The second backend: on the recording's clock, re-using the detection's id as
% its event reference, two ranked 3D sources and one channel level for c01.
pathValue = fullfile(workspace, "array_export.csv");
writeText(pathValue, strjoin([ ...
    "event_ref,t_on,t_off,source_id,source_rank,frame,x_mm,y_mm,z_mm,var_x,var_y,var_z,cov_xy,mic,level_db"
    "c01,10.00,10.30,src-a,1,arena_3d,105,202.5,15,4,4.5,9,0.5,,"
    "c01,10.00,10.30,src-b,2,arena_3d,300,95,12,16,16,25,-1.25,,"
    "c01,10.00,10.30,,,,,,,,,,,1,-41.5"], newline) + newline);
end

% ============================================================== attribution ===

function value = runRef(runKey)
value = struct(project_key="backend_localization_demo", run_key=runKey);
end

function value = createRun(conn, session, runKey, method)
created = vawlume.attribution.createRun(conn, struct(recording_id=1), struct( ...
    run_key=runKey, attribution_path="backend", method=method, ...
    settings_profile_version_id=session.settings_profile_version_id, ...
    target_set=struct(detection_ids=1:6), participating_entity_ids=[1 2 3], ...
    sources=struct(source_file_ids=1)), Apply=true);
value = struct(attribution_run_id=double(created.run.attribution_run_id), ...
    target_ids=double(created.targets.attribution_target_id)');
end

function value = promoteClaimsToCandidates(conn, targetIds)
%PROMOTECLAIMSTOCANDIDATES The explicit step from a backend claim to a candidate.
%
% A claim belongs to (backend window, entity); a candidate to (VAWLUME target,
% entity). Here every claim over a window that corresponds to a target becomes a
% candidate of that target, with the backend's number and semantics copied
% unchanged. That rule is THIS demonstration's choice -- a policy decision the
% caller makes -- which is why VAWLUME never makes it implicitly.
perTarget = table(zeros(0,1), zeros(0,1), VariableNames=["attribution_target_id", ...
    "candidate_count"]);
for target = targetIds
    claims = fetch(conn, "SELECT cl.entity_id AS entity_id, " + ...
        "IFNULL(cl.score,-999.0) AS score, IFNULL(cl.score_semantics,'') AS semantics, " + ...
        "cl.source_caller_label AS label FROM imported_attribution_claims cl " + ...
        "JOIN attribution_window_correspondences wc " + ...
        "ON wc.imported_attribution_window_id = cl.imported_attribution_window_id " + ...
        "WHERE wc.attribution_target_id=" + string(target) + " ORDER BY cl.entity_id");
    if height(claims) == 0
        perTarget(end + 1, :) = {target, 0}; %#ok<AGROW>
        continue
    end
    scored = double(claims.score) ~= -999.0;
    if all(scored)
        batch = table(double(claims.entity_id), double(claims.score), ...
            string(claims.semantics), string(claims.label), ...
            VariableNames=["entity_id", "score", "score_semantics", "source_label"]);
    else
        batch = table(double(claims.entity_id), string(claims.label), ...
            VariableNames=["entity_id", "source_label"]);
    end
    vawlume.attribution.addCandidates(conn, struct(attribution_target_id=target), ...
        batch, Apply=true);
    perTarget(end + 1, :) = {target, height(batch)}; %#ok<AGROW>
end
value = struct(per_target=perTarget, ...
    note="Candidates were promoted explicitly from the backend's claims; " + ...
        "neither intake nor correspondence created one.");
end

function value = candidateFor(conn, targetId, entityId)
rows = fetch(conn, "SELECT attribution_candidate_id AS id FROM attribution_candidates " + ...
    "WHERE attribution_target_id=" + string(targetId) + " AND entity_id=" + string(entityId));
value = double(rows.id(1));
end

function value = estimateFor(conn, runId, windowId)
rows = fetch(conn, "SELECT le.attribution_localization_estimate_id AS id " + ...
    "FROM attribution_localization_estimates le JOIN imported_attribution_windows w " + ...
    "ON w.imported_attribution_window_id = le.imported_attribution_window_id " + ...
    "WHERE w.attribution_run_id=" + string(runId) + " AND w.native_window_id='" + ...
    windowId + "'");
value = double(rows.id(1));
end

function value = addFiveDimensionEvidence(conn, candidateId, estimateId, run, clock, tracking)
%ADDFIVEDIMENSIONEVIDENCE Five dimensions, five rows, and no sixth combined row.
%
% Three rows promote backend material stored at intake: the source localization
% cites its estimate; the acoustic row is the backend's folded per-channel value,
% now naming its recording channel; the visual-identity row cites the association
% the backend's track reference was checked against. The temporal-alignment and
% pose rows come from VAWLUME's own upstream layers, as in Phase 4.
channel = fetch(conn, "SELECT a.value_real AS value, a.unit AS unit, " + ...
    "a.source_locator AS locator, s.value_text AS semantics " + ...
    "FROM attribution_native_attributes a JOIN attribution_native_attributes s " + ...
    "ON s.imported_attribution_window_id = a.imported_attribution_window_id " + ...
    "AND s.attribute_name = a.attribute_name || ':semantics' " + ...
    "JOIN imported_attribution_windows w ON w.imported_attribution_window_id = a.imported_attribution_window_id " + ...
    "WHERE w.attribution_run_id=" + string(run.attribution_run_id) + ...
    " AND w.native_window_id='b1' AND a.attribute_name='channel:1:backend_channel_power'");
channelId = fetch(conn, "SELECT recording_channel_id AS id FROM recording_channels " + ...
    "WHERE recording_id=1 AND channel_index=1");
ref = struct(attribution_candidate_id=candidateId);
rows = { ...
    struct(evidence_dimension="temporal_alignment", evidence_kind="propagated_bound", ...
        value_real=0.0020, value_units="s", ...
        value_semantics="Largest contributing anchor uncertainty on the reference clock; uncalibrated; not a confidence interval", ...
        alignment_run_id=clock.alignment_run_id)
    struct(evidence_dimension="pose_localization", evidence_kind="keypoint_confidence", ...
        value_real=0.7300, value_units="upstream_score", ...
        value_semantics="Tracker-exported snout keypoint localization confidence; producer=Tracker X; uncalibrated; where a bodypart is, not where a sound came from", ...
        source_locator="tracking.csv#time=10.0")
    struct(evidence_dimension="visual_identity", evidence_kind="reidentification_similarity", ...
        value_real=0.55, value_units="cosine_similarity", ...
        value_semantics="Appearance-embedding cosine similarity behind the backend's track_a reference; producer=ReID X; uncalibrated", ...
        identity_statement_kind="identity_association", ...
        tracking_identity_association_id=tracking.association_id)
    struct(evidence_dimension="acoustic", evidence_kind="backend_channel_power", ...
        value_real=double(channel.value(1)), value_units=string(channel.unit(1)), ...
        value_semantics=string(channel.semantics(1)), ...
        recording_channel_id=double(channelId.id(1)), ...
        source_locator=string(channel.locator(1)))
    struct(evidence_dimension="source_localization", evidence_kind="backend_source_location", ...
        attribution_localization_estimate_id=estimateId, coordinate_system_key="arena_2d")};
for index = 1:numel(rows)
    vawlume.attribution.addEvidence(conn, ref, rows{index}, Apply=true);
end
display = fetch(conn, "SELECT ev.evidence_dimension AS evidence_dimension, " + ...
    "ev.evidence_kind AS evidence_kind, " + ...
    "IFNULL(ev.value_real, -999.0) AS value_real, " + ...
    "IFNULL(ev.value_units, cs.unit) AS units, " + ...
    "IFNULL(rc.channel_label, '') AS channel, " + ...
    "IFNULL(cs.coordinate_system_key, '') AS frame, " + ...
    "IFNULL(le.position_x, -999.0) AS x, IFNULL(le.position_y, -999.0) AS y, " + ...
    "IFNULL(le.confidence, -999.0) AS confidence, " + ...
    "IFNULL(ev.value_semantics, le.position_semantics) AS semantics " + ...
    "FROM attribution_evidence ev " + ...
    "LEFT JOIN recording_channels rc ON rc.recording_channel_id = ev.recording_channel_id " + ...
    "LEFT JOIN attribution_localization_estimates le " + ...
    "ON le.attribution_localization_estimate_id = ev.attribution_localization_estimate_id " + ...
    "LEFT JOIN coordinate_systems cs ON cs.coordinate_system_id = le.coordinate_system_id " + ...
    "WHERE ev.attribution_candidate_id=" + string(candidateId) + ...
    " ORDER BY ev.attribution_evidence_id");
for name = ["value_real", "x", "y", "confidence"]
    values = double(display.(name));
    values(values == -999.0) = NaN;
    display.(name) = values;
end
for name = ["channel", "frame", "units", "semantics"]
    values = string(display.(name));
    values(ismissing(values)) = "";
    display.(name) = values;
end
confidenceSemantics = fetch(conn, "SELECT confidence_semantics AS s " + ...
    "FROM attribution_localization_estimates WHERE attribution_localization_estimate_id=" + ...
    string(estimateId));
value = struct(applied_count=numel(rows), ...
    display=display(:, ["evidence_dimension", "evidence_kind", "value_real", ...
        "units", "channel", "frame", "x", "y", "confidence"]), ...
    semantics=display(:, ["evidence_dimension", "semantics"]), ...
    confidence_semantics=string(confidenceSemantics.s(1)), ...
    combined_value_present=false, ...
    note="Five rows on five scales. The source-localization row carries no " + ...
        "value of its own; its position, frame and confidence are the estimate's.");
end

% ================================================================ refusals ===

function value = emptyRefusals()
value = table('Size', [0 3], 'VariableTypes', ["string", "string", "string"], ...
    'VariableNames', ["what_was_attempted", "identifier", "message"]);
end

function [refusals, captured] = recordRefusal(refusals, description, action)
%RECORDREFUSAL Exercise a path that must refuse, and keep what it said.
%
% If the action succeeds the example fails: a refusal that stopped refusing is a
% regression, and showing it as a success would teach the opposite lesson.
try
    action();
    error("vawlume:examples:RefusalNotRaised", "Expected a refusal for: %s", description);
catch exception
    if exception.identifier == "vawlume:examples:RefusalNotRaised"
        rethrow(exception);
    end
    captured = struct(raised=true, identifier=string(exception.identifier), ...
        message=string(exception.message));
end
refusals = [refusals; table(string(description), captured.identifier, ...
    firstSentence(captured.message), VariableNames=["what_was_attempted", ...
    "identifier", "message"])];
end

function value = firstSentence(message)
value = string(message);
stop = strfind(value, ". ");
if ~isempty(stop)
    value = extractBefore(value, stop(1) + 1);
end
end

% =============================================================== read-backs ===

function value = compactReport(report)
value = struct(run_key=report.run_key, attribution_path=report.attribution_path, ...
    status=report.status, grain=grainTable(report), ...
    localization_estimates=report.localization_estimates, ...
    native_attributes=report.native_attributes, ...
    declared_inputs=report.declared_inputs, evidence=report.evidence, ...
    decisions=report.decisions, qc=report.qc, qc_note=report.qc_note);
end

function value = grainTable(report)
%GRAINTABLE What each returned table counts, beside how many rows it has.
names = ["targets"; "candidates"; "evidence"; "imported_claims"; ...
    "localization_estimates"; "native_attributes"; "declared_inputs"; ...
    "correspondences"; "claim_correspondences"; "decisions"; "decision_selections"];
grains = ["attribution target"; "(target, candidate entity)"; ...
    "stored evidence record"; "(backend window, claimed caller)"; ...
    "localization estimate (backend-window grain)"; ...
    "(owner, native attribute name)"; "(run, declared upstream input)"; ...
    "stored correspondence"; "(claim, correspondence) - the joined story"; ...
    "(target, policy version)"; "candidate a decision selected"];
counts = zeros(numel(names), 1);
for index = 1:numel(names)
    counts(index) = height(report.(names(index)));
end
value = table(names, grains, counts, ...
    VariableNames=["table_name", "one_row_per", "row_count"]);
end

function value = databaseInventory(conn)
names = ["attribution_runs"; "attribution_targets"; "imported_attribution_windows"; ...
    "imported_attribution_claims"; "attribution_localization_estimates"; ...
    "attribution_native_attributes"; "attribution_run_declared_inputs"; ...
    "attribution_window_correspondences"; "attribution_candidates"; ...
    "attribution_evidence"; "attribution_decisions"; "attribution_decision_candidates"; ...
    "alignment_segments"; "tracking_identity_associations"];
counts = zeros(numel(names), 1);
for index = 1:numel(names)
    rows = fetch(conn, "SELECT COUNT(*) AS n FROM " + names(index));
    counts(index) = double(rows.n(1));
end
value = table(names, counts, VariableNames=["table_name", "row_count"]);
end

% =================================================================== print ===

function printDemonstration(value)
fprintf('\nVAWLUME synthetic Phase 5 backend/localization demonstration\n');
fprintf('%s\n', value.calibration_boundary);
fprintf('\nSession seeded directly (each has its own demonstration):\n  %s\n', ...
    strjoin(value.session.seeded_directly, '\n  '));
fprintf('Frames declared: %s\n', strjoin(value.geometry.frames, '; '));
fprintf('Channels registered: %s\n', strjoin(value.geometry.channel_labels, ', '));
fprintf('Backend clock -> recording clock: %s (%s), alignment run %d\n', ...
    value.backend_clock.method, value.backend_clock.status, value.backend_clock.alignment_run_id);
fprintf('Tracking stream %s in %s; dense samples stored: %d\n', ...
    value.tracking.stream_name, value.tracking.frame, value.tracking.dense_samples_stored);

fprintf('\nBackend import dry run wrote nothing (%d windows, %d claims, %d estimates, %d rows unmapped):\n', ...
    value.import_preview.window_count, value.import_preview.claim_count, ...
    value.import_preview.estimate_count, value.import_preview.unmapped_rows);
disp(value.import_preview.issues(:, ["severity", "code", "message"]));
fprintf('  frames it would resolve:\n');
disp(value.import_preview.resolutions.frames);
fprintf('Imported: %s; producer: %s %s; profile %s@%s\n', value.import.status, ...
    value.import.exporting_system.name, value.import.exporting_system.version, ...
    value.import.profile.profile_key, value.import.profile.version_label);
fprintf('  source SHA-256: %s\n', value.import.source_checksum);
fprintf('  intake wrote none of: %s\n', strjoin(value.import.not_written, ', '));

fprintf('\nLocalization estimates, each in its declared frame (backend-window grain):\n');
disp(value.main_report.localization_estimates(:, ["native_window_id", ...
    "coordinate_system_key", "coordinate_system_unit", "position_x", "position_y", ...
    "position_z", "confidence"]));
fprintf('  confidence semantics: %s\n', value.evidence.confidence_semantics);

fprintf('\nCorrespondence on the %s basis, through alignment run %d:\n', ...
    value.correspondence.iou_basis, value.correspondence.alignment_run_id);
disp(value.correspondence.rows);

fprintf('Candidates promoted explicitly from the backend''s claims, per target:\n');
disp(value.candidates.per_target);
fprintf('  targets with no candidate at all:\n');
disp(value.main_report.qc.targets_without_candidate(:, ["attribution_target_id", "target_kind"]));

fprintf('Five evidence dimensions on one candidate, never combined:\n');
disp(value.evidence.display);
fprintf('  and what each means where it came from:\n');
for index = 1:height(value.evidence.semantics)
    fprintf('    %-20s %s\n', value.evidence.semantics.evidence_dimension(index), ...
        value.evidence.semantics.semantics(index));
end

fprintf('\nDecisions under the shipped policy (ambiguous and simultaneous are opposite claims):\n');
disp(value.decisions.rows);

fprintf('Backend-native fields, preserved apart from every canonical column:\n');
disp(value.main_report.native_attributes(:, ["owner_kind", "attribute_namespace", ...
    "attribute_name", "native_field_name", "value_type", "value_real", "value_text", "unit"]));
fprintf('What the backend declared it consumed (undeclared = unknown, not "not used"):\n');
disp(value.main_report.declared_inputs(:, ["input_dimension", "declaration", "profile_key"]));

fprintf('\nRead-back grain, so nothing is counted from the wrong table:\n');
disp(value.main_report.grain);
fprintf('Evidence by dimension (no total, no coverage fraction):\n');
disp(value.main_report.qc.evidence_by_dimension);
fprintf('Localization per coordinate system (never pooled across frames):\n');
disp(value.main_report.qc.localization_by_coordinate_system(:, ["coordinate_system_key", ...
    "coordinate_system_dimensionality", "coordinate_system_unit", "estimate_count", ...
    "estimates_without_confidence", "position_z_min", "position_z_max"]));

fprintf('\nA second, structurally different backend over the same recording (%s):\n', ...
    value.array_report.attribution_path);
disp(value.array_report.localization_estimates(:, ["native_window_id", ...
    "native_estimate_id", "estimate_ordinal", "coordinate_system_key", ...
    "coordinate_system_unit", "position_x", "position_y", "position_z", "confidence"]));
fprintf('  its covariance, preserved as native attributes:\n');
disp(value.array_report.native_attributes(value.array_report.native_attributes.owner_kind == ...
    "estimate", ["attribute_name", "value_real", "unit"]));
fprintf('  same read-surface fields as the first backend: %d\n', value.same_read_surface);

fprintf('\nRefusals demonstrated beside the successes:\n');
disp(value.refusals);

fprintf('\nDatabase inventory:\n');
disp(value.database_inventory);
fprintf('Foreign-key violations: %d; temporary artifacts removed: %d\n', ...
    height(value.foreign_key_check), value.temporary_artifacts_removed);
fprintf('Proves:\n  %s\n', strjoin(value.proves, '\n  '));
fprintf('Does not prove:\n  %s\n', strjoin(value.does_not_prove, '\n  '));
end

% ================================================================= helpers ===

function writeText(pathValue, value)
fileId = fopen(pathValue, "w");
if fileId < 0
    error("vawlume:examples:FixtureCreationFailed", ...
        "Could not create demonstration input: %s", pathValue);
end
cleanupFile = onCleanup(@() fclose(fileId));
fprintf(fileId, "%s", value);
clear cleanupFile
end

function root = normalizedRepoRoot(root)
if strlength(root) == 0
    root = fileparts(fileparts(mfilename("fullpath")));
end
try
    root = string(java.io.File(char(root)).getCanonicalPath());
catch
    root = string(root);
end
end

function value = pathContains(target)
value = any(split(string(path), pathsep) == string(target));
end

function restoreSourcePath(sourcePath, shouldRemove)
if shouldRemove && pathContains(sourcePath), rmpath(sourcePath); end
end

function closeConnection(conn)
try
    if isopen(conn), close(conn); end
catch
end
end

function removeTree(root)
try
    if isfolder(root), rmdir(root, "s"); end
catch
end
end
