function demonstration = caller_attribution_demo(options)
%CALLER_ATTRIBUTION_DEMO Demonstrate the integrated Phase 4 attribution path.
%
% DEMONSTRATION = CALLER_ATTRIBUTION_DEMO() creates a disposable synthetic
% session and exercises the whole caller-attribution path on it: a recording with
% three participating entities and two channels, VAWLUME detections and derived
% consensus events as the two target kinds, an external attribution export on the
% exporting system's own clock, a piecewise-affine transform relating that clock
% to the recording's, correspondence across it, multi-candidate results, evidence
% in four dimensions that is never combined, and decisions under two policies.
%
% The refusals are demonstrated beside the successes, because a path that shows
% only what works teaches a reader that everything works. Four are exercised by
% name: an imported caller label that resolves to no participating entity, a
% correspondence with no clock declaration, a second correspondence apply, and a
% candidate appended to a completed run.
%
% Nothing here is calibrated and nothing is validated. Every threshold is an
% illustrative prototype value, every number is synthetic, and no result is
% evidence that any animal called. All inputs are created under the system
% temporary directory and removed before return.
%
% Name-value options:
%   Print     print compact developer-facing read-backs (default true)
%   RepoRoot  repository root, inferred from this file by default
%
% See also TEMPORAL_ALIGNMENT_DEMO, MULTIMODAL_INTEGRATION_DEMO

arguments
    options.Print (1,1) logical = true
    options.RepoRoot (1,1) string = ""
end

repoRoot = normalizedRepoRoot(options.RepoRoot);
sourcePath = fullfile(repoRoot, "src");
removeSourcePath = ~pathContains(sourcePath);
if removeSourcePath, addpath(sourcePath); end
cleanupPath = onCleanup(@() restoreSourcePath(sourcePath, removeSourcePath));

workspace = fullfile(tempdir, "VAWLUME phase 4 caller attribution demo " + ...
    string(java.util.UUID.randomUUID));
mkdir(workspace);
cleanupWorkspace = onCleanup(@() removeTree(workspace));
databasePath = fullfile(workspace, "caller_attribution_demo.sqlite");
conn = sqlite(char(databasePath), "create");
cleanupConnection = onCleanup(@() closeConnection(conn));

vawlume.db.applySchema(conn, fullfile(repoRoot, "schema", "schema.sql"));
vawlume.db.registerBuiltinSemantics(conn, repoRoot);

session = seedSession(conn);
channels = registerChannels(conn);
consensus = deriveConsensusEvents(conn, repoRoot);
exporterClock = establishExporterClock(conn, workspace, repoRoot);
identity = registerIdentityEvidence(conn, workspace, repoRoot);
profilePath = writeExporterProfile(workspace, repoRoot);

refusals = emptyRefusals();

% --- Run A: the imported path over extractor-native detections --------------

detectionRun = createDetectionRun(conn);
[refusals, rejectedImport] = recordRefusal(refusals, ...
    "an imported label naming an animal that was not in this recording", ...
    @() vawlume.ingest.attribution(conn, detectionRunRef(), ...
        writeRejectedExport(workspace), ProfilePath=profilePath, ...
        RepoRoot=repoRoot, Apply=true));

exportPath = writeExport(workspace);
importPreview = vawlume.ingest.attribution(conn, detectionRunRef(), ...
    exportPath, ProfilePath=profilePath, RepoRoot=repoRoot);
importResult = vawlume.ingest.attribution(conn, detectionRunRef(), ...
    exportPath, ProfilePath=profilePath, RepoRoot=repoRoot, Apply=true);

refusals = recordRefusal(refusals, ...
    "a correspondence that did not say how the two clocks relate", ...
    @() vawlume.attribution.correspondWindows(conn, detectionRunRef()));

correspondence = vawlume.attribution.correspondWindows(conn, detectionRunRef(), ...
    AlignmentRun=exporterClock.alignment_run_id, RepoRoot=repoRoot, Apply=true);

refusals = recordRefusal(refusals, ...
    "a second correspondence apply over the same run", ...
    @() vawlume.attribution.correspondWindows(conn, detectionRunRef(), ...
        AlignmentRun=exporterClock.alignment_run_id, RepoRoot=repoRoot, Apply=true));

crossing = vawlume.alignment.applyTransformInterval(conn, ...
    exporterClock.alignment_run_id, exporterClock.crossing_window(1), exporterClock.crossing_window(2));

candidates = addDetectionCandidates(conn, detectionRun.target_ids);
evidence = addFourDimensionEvidence(conn, ...
    candidates.four_dimension_candidate_id, identity);

decidedTargets = detectionRun.target_ids([1 3 4 5 6 7]);
shippedDecision = vawlume.attribution.decide(conn, detectionRunRef(), ...
    struct(), RepoRoot=repoRoot, Apply=true, Targets=decidedTargets, ...
    Exclusions=struct(attribution_target_id=detectionRun.target_ids(6), ...
        reason="channel 2 clipped through this call"));

candidatesBefore = candidateFingerprint(conn, detectionRun.attribution_run_id);
relaxedPolicyPath = writeRelaxedPolicy(workspace, repoRoot);
relaxedDecision = vawlume.attribution.decide(conn, detectionRunRef(), ...
    struct(profile_path=relaxedPolicyPath), RepoRoot=repoRoot, Apply=true, ...
    Targets=decidedTargets);
candidatesAfter = candidateFingerprint(conn, detectionRun.attribution_run_id);
policyComparison = comparePolicies(shippedDecision, relaxedDecision, ...
    candidatesBefore, candidatesAfter);

detectionReport = vawlume.attribution.report(conn, detectionRunRef());

% --- Run B: the same representation over VAWLUME consensus events ----------

consensusRun = createConsensusRun(conn, consensus);
consensusExport = writeConsensusExport(workspace, consensus);
consensusImport = vawlume.ingest.attribution(conn, consensusRunRef(), ...
    consensusExport, ProfilePath=profilePath, RepoRoot=repoRoot, Apply=true);
consensusCorrespondence = vawlume.attribution.correspondWindows(conn, ...
    consensusRunRef(), SameClock=true, RepoRoot=repoRoot, Apply=true);
addConsensusCandidates(conn, consensusRun.target_ids);
consensusDecision = vawlume.attribution.decide(conn, consensusRunRef(), ...
    struct(), RepoRoot=repoRoot, Apply=true);

refusals = recordRefusal(refusals, ...
    "a candidate appended after the run's evidence was frozen", ...
    @() vawlume.attribution.addCandidates(conn, ...
        struct(attribution_target_id=consensusRun.target_ids(1)), ...
        table(3, VariableNames="entity_id"), Apply=true));

consensusReport = vawlume.attribution.report(conn, consensusRunRef());

% --- Read-back, QC and the boundaries -------------------------------------

inventory = databaseInventory(conn);
foreignKeyCheck = fetch(conn, "PRAGMA foreign_key_check");

demonstration = struct( ...
    calibration_boundary="Every threshold, score and probability here is a " + ...
        "synthetic illustrative value. Attribution is estimated, never " + ...
        "validated, and no decision below means an animal called.", ...
    session=session, channels=channels, ...
    exporter_clock=exporterClock, identity_evidence=identity, ...
    detection_run=struct(preview_status=detectionRun.preview_status, ...
        status=detectionRun.status, ...
        attribution_run_id=detectionRun.attribution_run_id, ...
        target_count=height(detectionRun.targets), ...
        stored_target_set_matches=detectionRun.stored_target_set_matches), ...
    consensus=consensus, ...
    mapping_profile=importResult.profile, ...
    rejected_import=rejectedImport, ...
    import_preview=struct(status=importPreview.status, ...
        window_count=height(importPreview.windows), ...
        claim_count=height(importPreview.claims), ...
        unmapped_rows=importPreview.unmapped_rows, ...
        issues=importPreview.issues, wrote_nothing=~importPreview.committed), ...
    import=struct(status=importResult.status, ...
        applied_counts=importResult.applied_counts, ...
        exporting_system=importResult.exporting_system, ...
        source_checksum=importResult.source.checksum_sha256), ...
    correspondence=struct(status=correspondence.status, ...
        iou_basis=correspondence.iou_basis, ...
        alignment_run_id=correspondence.alignment_run_id, ...
        rule=correspondence.rule, ...
        rows=correspondenceReadback(correspondence.correspondences), ...
        windows_without_correspondence= ...
            correspondence.windows_without_correspondence, ...
        ambiguous_window_count=correspondence.ambiguous_window_count), ...
    breakpoint_crossing=crossing, ...
    candidates=candidates, evidence=evidence, ...
    decisions=struct(shipped=decisionReadback(shippedDecision), ...
        relaxed=decisionReadback(relaxedDecision), ...
        comparison=policyComparison), ...
    detection_report=compactReport(detectionReport), ...
    consensus_run=struct(target_kind="consensus_event", ...
        target_count=height(consensusRun.targets), ...
        import_status=consensusImport.status, ...
        iou_basis=consensusCorrespondence.iou_basis, ...
        correspondence_count=height(consensusCorrespondence.correspondences), ...
        decision_status_counts=consensusReport.qc.decision_status_counts, ...
        run_completed=consensusDecision.run_completed, ...
        run_status=consensusReport.status, ...
        analysis_status=consensusReport.analysis_status), ...
    consensus_report=compactReport(consensusReport), ...
    refusals=refusals, ...
    separation=struct(combined_value_computed=false, ...
        caller_estimated=false, ...
        evidence_dimensions_present=height(detectionReport.qc.evidence_by_dimension), ...
        note="The four dimensions are stored, read and displayed side by " + ...
            "side with their own units and semantics. Nothing here combines " + ...
            "them, and the decision policy reads one candidate column and no " + ...
            "evidence row."), ...
    database_inventory=inventory, foreign_key_check=foreignKeyCheck, ...
    proves=["one canonical representation carries several candidate callers " + ...
        "per event, over both VAWLUME target kinds"; ...
        "an imported number keeps its own value, its semantics and its producer"; ...
        "an imported window reaches a VAWLUME event only through a declared " + ...
        "clock and a declared eligibility rule"; ...
        "the four uncertainty dimensions are represented separately and " + ...
        "combined by nothing"; ...
        "a decision moves with its policy while the candidates it read do not"; ...
        "ambiguous and simultaneous are recorded as opposite claims"; ...
        "the path refuses by name where guessing would look like success"], ...
    does_not_prove=["that any claimed or selected entity called"; ...
        "that the exporting system's scores or probabilities are calibrated"; ...
        "that any threshold in the shipped policy or mapping profile is tuned"; ...
        "that a window corresponding to nothing refers to a call VAWLUME missed"; ...
        "that this representation is legible at realistic session scale"], ...
    temporary_artifacts_removed=false);

close(conn);
clear cleanupConnection
removeTree(workspace);
clear cleanupWorkspace
demonstration.temporary_artifacts_removed = ...
    ~isfolder(workspace) && ~isfile(databasePath);

if options.Print, printDemonstration(demonstration); end
clear cleanupPath
end

% ================================================================ session ===

function value = seedSession(conn)
%SEEDSESSION The upstream session, written directly.
%
% Project intake, extractor import and reviewer input each have their own
% demonstration; repeating them here would bury the attribution path this example
% exists to show. What is seeded is exactly the material Phase 4 consumes: a
% recording, three participating entities, two extraction runs and their
% detections, and one registered settings-profile version.
%
% The settings-profile rows are the one seeded item that is a real gap rather
% than a deliberate omission: `createRun` requires a checksum-bearing
% `config_profile_versions` row and no public function registers an
% analysis-settings profile.
execute(conn, "INSERT INTO projects(project_id,project_key,project_name) " + ...
    "VALUES(1,'caller_attribution_demo','Caller attribution demonstration')");
execute(conn, "INSERT INTO source_files(source_file_id,project_id,file_role," + ...
    "path_or_uri,relative_path) VALUES" + ...
    "(1,1,'recording_audio','synthetic/session01.wav','session01.wav')," + ...
    "(2,1,'attribution_table','synthetic/caller_export.csv','caller_export.csv')");
execute(conn, "INSERT INTO recordings(recording_id,project_id,source_file_id," + ...
    "native_recording_id,sample_rate_hz,channel_count,duration_s) " + ...
    "VALUES(1,1,1,'REC_ATTRIB_01',250000,2,120)");
execute(conn, "INSERT INTO entity_types(entity_type_id,project_id,native_name," + ...
    "is_subject_like) VALUES(1,1,'mouse',1)");
execute(conn, "INSERT INTO experimental_entities(entity_id,project_id," + ...
    "entity_type_id,native_id) VALUES(1,1,1,'A'),(2,1,1,'B'),(3,1,1,'C')");
execute(conn, "INSERT INTO recording_entity_links(recording_entity_link_id," + ...
    "recording_id,entity_id,link_type) VALUES" + ...
    "(1,1,1,'participant'),(2,1,2,'participant'),(3,1,3,'participant')");
% Identifiers above the seeded range: registerBuiltinSemantics already occupies
% the low extractor and profile IDs with the three shipped extractors.
execute(conn, "INSERT INTO extractors(extractor_id,extractor_key,extractor_name) " + ...
    "VALUES(90,'synthetic_primary','Synthetic primary extractor')," + ...
    "(91,'synthetic_secondary','Synthetic secondary extractor')");
execute(conn, "INSERT INTO extractor_versions(extractor_version_id,extractor_id," + ...
    "version_label) VALUES(90,90,'0.1-demo'),(91,91,'0.1-demo')");
execute(conn, "INSERT INTO extraction_runs(extraction_run_id,project_id," + ...
    "extractor_version_id,run_key) VALUES(1,1,90,'demo-primary'),(2,1,91,'demo-secondary')");
execute(conn, "INSERT INTO extraction_run_inputs(extraction_run_id,recording_id) " + ...
    "VALUES(1,1),(2,1)");
execute(conn, "INSERT INTO detections(detection_id,extraction_run_id,recording_id," + ...
    "native_event_id,start_time_s,end_time_s,timing_basis) VALUES" + ...
    "(1,1,1,'c01',10.00,10.30,'synthetic fixture')," + ...
    "(2,1,1,'c02',10.40,10.62,'synthetic fixture')," + ...
    "(3,1,1,'c03',20.00,20.25,'synthetic fixture')," + ...
    "(4,1,1,'c04',30.00,30.20,'synthetic fixture')," + ...
    "(5,1,1,'c05',40.00,40.35,'synthetic fixture')," + ...
    "(6,1,1,'c06',50.00,50.30,'synthetic fixture')," + ...
    "(7,1,1,'c07',60.00,60.20,'synthetic fixture')," + ...
    "(8,2,1,'s01',10.02,10.31,'synthetic fixture')," + ...
    "(9,2,1,'s02',20.01,20.26,'synthetic fixture')," + ...
    "(10,2,1,'s03',30.02,30.19,'synthetic fixture')");
execute(conn, "INSERT INTO config_profiles(profile_id,project_id,profile_key," + ...
    "profile_name,profile_kind) VALUES(90,1,'demo-attribution-settings'," + ...
    "'Imported attribution run settings','analysis_settings')");
execute(conn, "INSERT INTO config_profile_versions(profile_version_id,profile_id," + ...
    "version_label,content_format,content_uri,checksum_sha256,is_snapshot) " + ...
    "VALUES(90,90,'1.0.0','json','config/demo_attribution_settings.json'," + ...
    "'1f0d9c6b3a2e5d4c8b7a6f5e4d3c2b1a0f9e8d7c6b5a4938271605f4e3d2c1b0',1)");
value = struct(project_key="caller_attribution_demo", recording_id=1, ...
    native_recording_id="REC_ATTRIB_01", ...
    participating_entities=["A"; "B"; "C"], ...
    detection_count=7, secondary_detection_count=3, ...
    settings_profile_version_id=90, ...
    seeded_directly=["project, source files and the recording"; ...
        "three entities and their participant links"; ...
        "two extraction runs and their detections"; ...
        "one registered attribution settings-profile version"]);
end

function value = registerChannels(conn)
%REGISTERCHANNELS The microphones, through the public function that owns them.
first = vawlume.geometry.registerRecordingChannel(conn, ...
    struct(recording_id=1), struct(channel_index=1, ...
    channel_label="mic_left", channel_role="attribution_reference"));
second = vawlume.geometry.registerRecordingChannel(conn, ...
    struct(recording_id=1), struct(channel_index=2, ...
    channel_label="mic_right", channel_role="attribution_reference"));
value = struct(channel_ids=[first.recording_channel_id; ...
        second.recording_channel_id], ...
    labels=["mic_left"; "mic_right"], ...
    note="A channel count is a caller assertion; nothing inspects the audio.");
end

function value = deriveConsensusEvents(conn, repoRoot)
%DERIVECONSENSUSEVENTS The second target kind, derived rather than declared.
result = vawlume.matching.compare(conn, struct(recording_id=1), ...
    struct(run_a="demo-primary", run_b="demo-secondary"), ...
    struct(run_key="demo-attribution-match", ...
        run_label="Matching that supplies consensus targets"), ...
    RepoRoot=repoRoot, Apply=true);
rows = fetch(conn, "SELECT consensus_event_id, start_time_s, end_time_s, " + ...
    "derivation_method FROM consensus_events WHERE analysis_run_id=" + ...
    string(result.analysis.analysis_run_id) + ...
    " ORDER BY start_time_s LIMIT 2");
value = struct( ...
    matching_analysis_run_id=double(result.analysis.analysis_run_id), ...
    matching_status=string(result.status), ...
    consensus_event_ids=double(rows.consensus_event_id), ...
    intervals=[double(rows.start_time_s), double(rows.end_time_s)], ...
    derivation_method=unique(string(rows.derivation_method)), ...
    events=rows);
end

% ============================================================ exporter clock ===

function value = establishExporterClock(conn, workspace, repoRoot)
%ESTABLISHEXPORTERCLOCK Relate the exporting system's clock to the recording's.
%
% The transform is fitted through the public alignment layer rather than written
% by hand, because the claim this example makes about clocks is that attribution
% reaches them through one shared API and adds no correction of its own.
truth = exporterClockTruth();
writeAnchorTable(fullfile(workspace, "sync_anchors.csv"), truth);
anchorProfilePath = writeAnchorProfile(workspace, repoRoot);
manifestPath = writeManifest(workspace, anchorProfilePath);

intake = vawlume.ingest.alignment(conn, manifestPath, ...
    RepoRoot=repoRoot, SourceRoot=workspace, Apply=true);
fitResult = vawlume.alignment.fit(conn, alignmentRef(), ...
    SourceTimebase="attribution_native", Breakpoints=truth.breakpoint, Apply=true);
qc = vawlume.alignment.report(conn, alignmentRef());
transform = qc.transforms(qc.transforms.source_timebase_key == ...
    "attribution_native", :);
segments = qc.segments(qc.segments.source_timebase_key == ...
    "attribution_native", :);

value = struct( ...
    source_timebase="attribution_native", ...
    reference_timebase=string(qc.reference_timebase.timebase_key(1)), ...
    alignment_run_id=double(transform.alignment_run_id(1)), ...
    method=string(transform.method(1)), ...
    status=string(transform.status(1)), ...
    anchor_count=double(intake.anchor_summary.anchor_count), ...
    anchored_source_range=[min(truth.source_times), max(truth.source_times)], ...
    breakpoint=truth.breakpoint, ...
    recovered=table(segments.segment_index, segments.scale, truth.scale, ...
        segments.offset_s, truth.offset_s, ...
        abs(segments.scale - truth.scale), ...
        abs(segments.offset_s - truth.offset_s), ...
        VariableNames=["segment_index", "scale", "expected_scale", ...
        "offset_s", "expected_offset_s", "scale_absolute_error", ...
        "offset_absolute_error_s"]), ...
    crossing_window=[34.90, 35.30], ...
    fit_status=string(fitResult.status), ...
    note="A fitted transform is estimated, never validated.");
end

function truth = exporterClockTruth()
truth = struct();
truth.breakpoint = 35;
truth.scale = [1.002; 0.998];
truth.offset_s = [5.00; (truth.scale(1) - truth.scale(2)) * truth.breakpoint + 5.00];
truth.source_times = [5; 15; 25; 35; 45; 55];
segment = 1 + double(truth.source_times >= truth.breakpoint);
truth.reference_times = truth.scale(segment) .* truth.source_times + ...
    truth.offset_s(segment);
truth.anchor_keys = "sync" + compose("%02d", (1:numel(truth.source_times))');
end

function writeAnchorTable(pathValue, truth)
count = numel(truth.anchor_keys);
markers = strings(2 * count, 1);
streams = strings(2 * count, 1);
timestamps = strings(2 * count, 1);
roles = repmat("primary", 2 * count, 1);
included = repmat("true", 2 * count, 1);
classes = repmat("device_level", 2 * count, 1);
row = 0;
for index = 1:count
    row = row + 1;
    markers(row) = truth.anchor_keys(index);
    streams(row) = "attribution";
    timestamps(row) = compose("%.9f", truth.source_times(index));
    row = row + 1;
    markers(row) = truth.anchor_keys(index);
    streams(row) = "audio";
    timestamps(row) = compose("%.9f", truth.reference_times(index));
end
writetable(table(markers, streams, timestamps, roles, included, classes, ...
    VariableNames=["marker", "stream", "timestamp_s", "role", "include", ...
    "evidence_class"]), pathValue, QuoteStrings="minimal");
end

function pathValue = writeAnchorProfile(workspace, repoRoot)
document = jsondecode(fileread(fullfile(repoRoot, "config", ...
    "01_mapping_profiles", "alignment_anchors", ...
    "long_anchor_mapping_profile.json")));
document.profile.id = "vawlume.alignment.anchor.long.phase4_demo.v1";
document.profile.name = "Synthetic exporter-clock anchor profile";
document.context.declared_timebases = {'audio_native'; 'attribution_native'};
mapping = document.context.stream_timebases(1);
mapping.native_value = "audio";
mapping.stream_key = "audio_sync";
mapping.timebase_key = "audio_native";
exporter = mapping;
exporter.native_value = "attribution";
exporter.stream_key = "attribution_sync";
exporter.timebase_key = "attribution_native";
document.context.stream_timebases = [mapping; exporter];
pair = document.context.fit_pairs(1);
pair.source_timebase_key = "attribution_native";
pair.reference_timebase_key = "audio_native";
document.context.fit_pairs = pair;
pathValue = fullfile(workspace, "phase4_anchor_profile.json");
writeText(pathValue, string(jsonencode(document, PrettyPrint=true)) + newline);
end

function pathValue = writeManifest(workspace, anchorProfilePath)
document = struct();
document.manifest = struct(manifest_schema_version="0.1-draft", ...
    manifest_version="0.1.0", alignment_key="phase4_attribution_clock", ...
    label="Exporting system clock against the recording clock", ...
    notes="Synthetic. No clock here is a real device.");
document.session = struct(project_key="caller_attribution_demo", ...
    recording=struct(native_recording_id="REC_ATTRIB_01"));
document.reference_timebase = "audio_native";
document.method = "piecewise_affine";
document.timebases = {struct(timebase_key="audio_native", ...
        timebase_kind="audio_sample_clock", recording_native=true, ...
        native_unit="s", origin_description="Recording file time zero."), ...
    struct(timebase_key="attribution_native", ...
        timebase_kind="attribution_system_clock", recording_native=false, ...
        native_unit="s", ...
        origin_description="Exporting attribution system's own start.")};
document.anchors = struct(source="sync_anchors.csv", ...
    mapping_profile=char(anchorProfilePath), ...
    file_role="alignment_anchor_table");
pathValue = fullfile(workspace, "phase4_alignment_manifest.json");
writeText(pathValue, string(jsonencode(document, PrettyPrint=true)) + newline);
end

function value = alignmentRef()
value = struct(project_key="caller_attribution_demo", ...
    run_key="phase4_attribution_clock");
end

% ========================================================= identity evidence ===

function value = registerIdentityEvidence(conn, workspace, repoRoot)
%REGISTERIDENTITYEVIDENCE The statement the visual-identity evidence will cite.
%
% Registered through the Phase 2 tracking layer rather than asserted, because a
% candidate-level identity row must name the association it read. A native track
% label is not a canonical entity, and the association is where that distinction
% is recorded together with its uncertainty.
vawlume.geometry.registerCoordinateSystem(conn, ...
    struct(project_key="caller_attribution_demo"), struct( ...
    coordinate_system_key="arena_2d", coordinate_system_name="Synthetic arena", ...
    dimensionality=2, unit="cm"));

artifactPath = fullfile(workspace, "tracking.csv");
writetable(table([0; 10; 20; 40; 60; 80], repmat("track_a", 6, 1), ...
    repmat("snout", 6, 1), [0; 1; 2; 3; 4; 5], repmat(10, 6, 1), ...
    repmat(0.73, 6, 1), VariableNames=["time_s", "track", "bodypart", ...
    "x", "y", "likelihood"]), artifactPath, QuoteStrings="minimal");

profilePath = fullfile(workspace, "tracking_profile.json");
profile = jsondecode(fileread(fullfile(repoRoot, "config", ...
    "01_mapping_profiles", "tracking", "generic_tracking_mapping_profile.json")));
profile.profiles.columns.track_label.source_field = "track";
writeText(profilePath, string(jsonencode(profile, PrettyPrint=true)) + newline);

registration = vawlume.tracking.register(conn, struct(recording_id=1), ...
    struct(artifact_path="tracking.csv", profile_path=profilePath, ...
    timebase_key="audio_native"), Apply=true, RepoRoot=repoRoot, ...
    SourceRoot=workspace);
streamRef = struct(project_key="caller_attribution_demo", ...
    stream_name="tracking_primary");
association = vawlume.tracking.registerIdentityAssociation(conn, streamRef, ...
    struct(native_track_id="track_a", entity_native_id="A", ...
    start_time_native=0, end_time_native=80, ...
    assignment_state="candidate", evidence_kind="reidentification_score", ...
    identity_value=0.55, ...
    identity_value_semantics="cosine_similarity_of_appearance_embeddings", ...
    calibration_status="uncalibrated", review_state="unreviewed"));

alignmentRun = fetch(conn, "SELECT alignment_run_id FROM time_alignment_runs " + ...
    "ORDER BY alignment_run_id LIMIT 1");
value = struct( ...
    association_id=double(association.tracking_identity_association_id), ...
    identity_value=0.55, ...
    alignment_run_id=double(alignmentRun.alignment_run_id(1)), ...
    dense_samples_stored=registration.dense_samples_stored, ...
    boundary="track_a is a tracker label. The association says which canonical " + ...
        "entity it may denote, with an uncalibrated score and an unreviewed state.");
end

% ============================================================ imported path ===

function pathValue = writeExporterProfile(workspace, repoRoot)
%WRITEEXPORTERPROFILE The shipped template, pointed at this session's labels.
%
% The exporting system knows animals A, B and D. Only A, B and C were in this
% recording, which is what makes the D claim refusable by name rather than
% silently dropped.
document = jsondecode(fileread(fullfile(repoRoot, "config", ...
    "01_mapping_profiles", "attribution", ...
    "generic_imported_attribution_profile.json")));
entry = document.profiles(1);
entry.profile.id = "vawlume.attribution.demo_imported.v0_1";
entry.profile.name = "Synthetic caller-attribution export";
entry.profile.profile_version = "0.1.0-demo";
entry.context.exporting_system = "Synthetic Caller Attribution System";
entry.context.exporting_system_version = "2.0.0";
map = entry.caller_label_resolution.map;
map(end + 1) = struct(caller_label="D", entity_native_id="D");
entry.caller_label_resolution.map = map;
document.profiles = entry;
pathValue = fullfile(workspace, "demo_attribution_profile.json");
writeText(pathValue, string(jsonencode(document, PrettyPrint=true)) + newline);
end

function pathValue = writeExport(workspace)
% Ten source rows. Eight map into claims over seven windows; two are reported as
% issues rather than dropped quietly. w2 carries two callers, which is one window
% and two claims, not one claim with the labels run together.
pathValue = fullfile(workspace, "caller_export.csv");
writeText(pathValue, strjoin([ ...
    "window_id,start_s,end_s,caller,score,probability"
    "w1,5.01,5.60,A,0.91,0.87"
    "w2,14.98,15.23,A,0.55,0.50"
    "w2,14.98,15.23,B,0.52,0.48"
    "w3,24.95,25.15,B,0.73,0.70"
    "w4,34.90,35.30,A,0.31,0.28"
    "w5,44.95,45.25,A,,"
    "w6,54.90,55.15,B,0.66,0.61"
    "w7,80.00,80.40,A,0.44,0.40"
    "w8,72.00,71.00,B,0.20,0.18"
    "w9,90.00,90.50,Z,0.30,0.29"], newline) + newline);
end

function pathValue = writeRejectedExport(workspace)
pathValue = fullfile(workspace, "caller_export_rejected.csv");
writeText(pathValue, strjoin([ ...
    "window_id,start_s,end_s,caller,score,probability"
    "w1,5.01,5.60,A,0.91,0.87"
    "w3,24.95,25.15,D,0.73,0.70"], newline) + newline);
end

function pathValue = writeConsensusExport(workspace, consensus)
% Authored from the consensus intervals the matching layer actually derived, and
% declared to be on the recording's own clock.
lines = "window_id,start_s,end_s,caller,score,probability";
labels = ["A", "B"];
scores = [0.90, 0.35; 0.66, 0.62];
for index = 1:size(consensus.intervals, 1)
    for which = 1:2
        lines(end + 1, 1) = compose("k%02d,%.6f,%.6f,%s,%.2f,%.2f", index, ...
            consensus.intervals(index, 1) + 0.01, ...
            consensus.intervals(index, 2) - 0.01, labels(which), ...
            scores(index, which), scores(index, which)); %#ok<AGROW>
    end
end
pathValue = fullfile(workspace, "consensus_caller_export.csv");
writeText(pathValue, strjoin(lines, newline) + newline);
end

% =============================================================== attribution ===

function value = detectionRunRef()
value = struct(project_key="caller_attribution_demo", ...
    run_key="session01-imported-detections");
end

function value = consensusRunRef()
value = struct(project_key="caller_attribution_demo", ...
    run_key="session01-imported-consensus");
end

function value = createDetectionRun(conn)
preview = vawlume.attribution.createRun(conn, struct(recording_id=1), ...
    detectionRunSpec());
created = vawlume.attribution.createRun(conn, struct(recording_id=1), ...
    detectionRunSpec(), Apply=true);
resolved = vawlume.attribution.resolveTargets(conn, detectionRunRef(), ...
    struct(detection_ids=1:7));
value = struct(preview_status=string(preview.status), ...
    status=string(created.status), ...
    attribution_run_id=double(created.run.attribution_run_id), ...
    targets=created.targets, ...
    target_ids=double(created.targets.attribution_target_id), ...
    stored_target_set_matches=resolved.matches_stored);
end

function value = detectionRunSpec()
value = struct(run_key="session01-imported-detections", ...
    attribution_path="imported", ...
    method="Synthetic Caller Attribution System 2.0", ...
    settings_profile_version_id=90, ...
    target_set=struct(detection_ids=1:7), ...
    participating_entity_ids=[1 2 3], ...
    sources=struct(source_file_ids=[1 2]), ...
    run_label="Imported caller attribution over extractor-native detections");
end

function value = createConsensusRun(conn, consensus)
created = vawlume.attribution.createRun(conn, struct(recording_id=1), ...
    struct(run_key="session01-imported-consensus", ...
        attribution_path="imported", ...
        method="Synthetic Caller Attribution System 2.0", ...
        settings_profile_version_id=90, ...
        target_set=struct(consensus_event_ids=consensus.consensus_event_ids'), ...
        participating_entity_ids=[1 2 3], ...
        sources=struct(source_file_ids=[1 2]), ...
        run_label="The same representation over VAWLUME consensus events"), ...
    Apply=true);
value = struct(attribution_run_id=double(created.run.attribution_run_id), ...
    targets=created.targets, ...
    target_ids=double(created.targets.attribution_target_id));
end

function value = addDetectionCandidates(conn, targetIds)
%ADDDETECTIONCANDIDATES Several candidate callers per target is the normal shape.
%
% Candidates are entered here rather than promoted from the imported claims.
% Nothing in Phase 4 turns a claim into a candidate: which correspondence is good
% enough to carry a claim onto an event is a judgement, not a join.
specs = { ...
    targetIds(1), [1 2 3], [0.92 0.40 0.20], [1 2 3], [0.81 0.12 0.07]; ...
    targetIds(3), [1 2],   [0.88 0.82],      [1 2],   [NaN NaN]; ...
    targetIds(4), [1 2],   [0.62 0.58],      [1 2],   [NaN NaN]; ...
    targetIds(5), [1 2],   [0.31 0.22],      [1 2],   [NaN NaN]; ...
    targetIds(6), [1 2],   [0.77 0.30],      [1 2],   [NaN NaN]; ...
    targetIds(7), [2 1 3], [0.95 0.10 NaN],  [1 2 NaN], [NaN NaN NaN]};
firstCandidateId = NaN;
perTarget = table('Size', [size(specs, 1) 3], ...
    'VariableTypes', ["double", "double", "double"], ...
    'VariableNames', ["attribution_target_id", "candidate_count", "scored_count"]);
for index = 1:size(specs, 1)
    batch = candidateBatch(specs{index, 2}, specs{index, 3}, specs{index, 4}, ...
        specs{index, 5});
    result = vawlume.attribution.addCandidates(conn, ...
        struct(attribution_target_id=specs{index, 1}), batch, Apply=true);
    if isnan(firstCandidateId)
        firstCandidateId = double(result.candidates.attribution_candidate_id(1));
    end
    perTarget.attribution_target_id(index) = specs{index, 1};
    perTarget.candidate_count(index) = height(result.candidates);
    perTarget.scored_count(index) = nnz(~isnan(specs{index, 3}));
end
value = struct(per_target=perTarget, ...
    four_dimension_candidate_id=firstCandidateId, ...
    target_without_candidates=targetIds(2), ...
    unscored_candidate_note="One candidate on the last target carries a label " + ...
        "and no number. Both numeric columns stay absent; nothing writes 1.0.");
end

function value = addConsensusCandidates(conn, targetIds)
%ADDCONSENSUSCANDIDATES Enough candidates for every consensus target to decide.
specs = {[1 2], [0.90 0.35], [1 2]; [1 2], [0.66 0.62], [1 2]};
value = zeros(numel(targetIds), 1);
for index = 1:numel(targetIds)
    spec = specs{min(index, size(specs, 1)), 1};
    batch = candidateBatch(spec, specs{min(index, size(specs, 1)), 2}, ...
        specs{min(index, size(specs, 1)), 3}, NaN(1, numel(spec)));
    result = vawlume.attribution.addCandidates(conn, ...
        struct(attribution_target_id=targetIds(index)), batch, Apply=true);
    value(index) = height(result.candidates);
end
end

function value = candidateBatch(entityIds, scores, ranks, probabilities)
count = numel(entityIds);
scoreSemantics = repmat(scoreSemanticsText(), count, 1);
scoreSemantics(isnan(scores)) = "";
probabilitySemantics = repmat(probabilitySemanticsText(), count, 1);
probabilitySemantics(isnan(probabilities)) = "";
value = table(double(entityIds(:)), double(ranks(:)), double(scores(:)), ...
    scoreSemantics, double(probabilities(:)), probabilitySemantics, ...
    string(char(double('A') + double(entityIds(:)) - 1)), ...
    VariableNames=["entity_id", "candidate_rank", "score", "score_semantics", ...
    "probability", "probability_semantics", "source_label"]);
end

function value = scoreSemanticsText()
value = "Synthetic Caller Attribution System 2.0 caller score; " + ...
    "producer=Synthetic Caller Attribution System 2.0; range=[0,1]; " + ...
    "uncalibrated; higher is stronger; not a probability";
end

function value = probabilitySemanticsText()
value = "Exporter-labelled caller probability; producer=Synthetic Caller " + ...
    "Attribution System 2.0; range=[0,1]; calibration=exporter-claimed and " + ...
    "not validated by VAWLUME";
end

function value = addFourDimensionEvidence(conn, candidateId, identity)
%ADDFOURDIMENSIONEVIDENCE Four dimensions, four rows, and no fifth combined row.
%
% Each row points back at where its number came from, relationally where the
% schema has a link and through a locator string where it does not. Three of the
% four reach a real row: the alignment run that produced the bound, the audio
% source file the ratio was measured from, and the identity association the
% similarity rests on. Pose confidence has no relation to cite, because a
% tracking sample is not a row in this database -- it is a line in the artifact.
%
% The visual-identity row must also say WHICH KIND of statement it read. Identity
% evidence that cannot name its source is not identity evidence, and the storage
% layer refuses a bare number rather than accepting one.
rows = table( ...
    ["temporal_alignment"; "pose_localization"; "visual_identity"; "acoustic"], ...
    ["propagated_bound"; "keypoint_confidence"; ...
     "reidentification_similarity"; "channel_rms_ratio"], ...
    [0.0020; 0.7300; identity.identity_value; 0.4200], ...
    ["s"; "upstream_score"; "cosine_similarity"; "ratio"], ...
    ["Largest contributing anchor uncertainty on the reference clock; uncalibrated; not a confidence interval"; ...
     "Tracker-exported keypoint localization confidence; producer=Tracker X; range=[0,1]; uncalibrated; not caller probability"; ...
     "Appearance-embedding cosine similarity; producer=ReID X; range=[-1,1]; uncalibrated; not caller probability"; ...
     "Native channel 1 to channel 2 RMS ratio; producer=measurement export; range=nonnegative; uncalibrated; not caller probability"], ...
    [identity.alignment_run_id; NaN; NaN; NaN], ...
    [NaN; NaN; NaN; 1], ...
    ["" ; ""; "identity_association"; ""], ...
    [NaN; NaN; identity.association_id; NaN], ...
    ["" ; "tracking.csv#time=10.0"; ""; "session01.wav#samples=2500000:2575000"], ...
    VariableNames=["evidence_dimension", "evidence_kind", "value_real", ...
    "value_units", "value_semantics", "alignment_run_id", "source_file_id", ...
    "identity_statement_kind", "tracking_identity_association_id", ...
    "source_locator"]);
result = vawlume.attribution.addEvidence(conn, ...
    struct(attribution_candidate_id=candidateId), rows, Apply=true);
value = struct(applied_count=result.applied_count, ...
    display=rows(:, ["evidence_dimension", "evidence_kind", "value_real", ...
        "value_units"]), ...
    provenance=provenanceDisplay(rows), ...
    semantics=rows(:, ["evidence_dimension", "value_semantics"]), ...
    combined_value_present=false, ...
    note="Four numbers on four scales. No row spans two dimensions and no " + ...
        "field is a function of more than one of them.");
end

function value = provenanceDisplay(rows)
%PROVENANCEDISPLAY Where each evidence row says its number came from.
pointers = strings(height(rows), 1);
kinds = strings(height(rows), 1);
for index = 1:height(rows)
    if ~isnan(rows.alignment_run_id(index))
        kinds(index) = "relational";
        pointers(index) = "time_alignment_runs:" + ...
            string(rows.alignment_run_id(index));
    elseif ~isnan(rows.tracking_identity_association_id(index))
        kinds(index) = "relational";
        pointers(index) = "tracking_identity_associations:" + ...
            string(rows.tracking_identity_association_id(index));
    elseif ~isnan(rows.source_file_id(index))
        kinds(index) = "relational";
        pointers(index) = "source_files:" + string(rows.source_file_id(index));
    else
        kinds(index) = "locator";
        pointers(index) = rows.source_locator(index);
    end
end
value = table(rows.evidence_dimension, kinds, pointers, ...
    VariableNames=["evidence_dimension", "pointer_kind", "points_at"]);
end

% ============================================================== comparisons ===

function value = candidateFingerprint(conn, attributionRunId)
value = fetch(conn, "SELECT c.attribution_candidate_id, c.entity_id, " + ...
    "c.candidate_status, IFNULL(c.candidate_rank,-1) AS candidate_rank, " + ...
    "IFNULL(c.score,-1e308) AS score, IFNULL(c.probability,-1e308) AS probability " + ...
    "FROM attribution_candidates c JOIN attribution_targets t " + ...
    "ON t.attribution_target_id=c.attribution_target_id " + ...
    "WHERE t.attribution_run_id=" + string(attributionRunId) + ...
    " ORDER BY c.attribution_candidate_id");
end

function value = comparePolicies(shipped, relaxed, before, after)
merged = outerjoin(shipped.decisions(:, ["attribution_target_id", ...
    "decision_status", "applied_threshold"]), ...
    relaxed.decisions(:, ["attribution_target_id", "decision_status", ...
    "applied_threshold"]), Keys="attribution_target_id", MergeKeys=true, ...
    Type="left");
merged.Properties.VariableNames = ["attribution_target_id", ...
    "shipped_status", "shipped_threshold", "relaxed_status", "relaxed_threshold"];
merged.status_moved = merged.shipped_status ~= merged.relaxed_status;
value = struct(per_target=merged, ...
    statuses_moved=nnz(merged.status_moved), ...
    candidates_unchanged=isequal(before, after), ...
    shipped_policy=shipped.policy.profile_key + "@" + shipped.policy.version_label, ...
    relaxed_policy=relaxed.policy.profile_key + "@" + relaxed.policy.version_label, ...
    note="Both decisions remain readable. Comparing policies over one body " + ...
        "of evidence is the reason a decision is never rewritten in place.");
end

function pathValue = writeRelaxedPolicy(workspace, repoRoot)
document = jsondecode(fileread(fullfile(repoRoot, "config", ...
    "08_attribution_policies", "prototype_attribution_decision_policy.json")));
document.profile.id = "vawlume.attribution.decision.demo_relaxed.v1";
document.profile.name = "Demonstration policy with different thresholds";
document.profile.profile_version = "0.1.0-demo";
document.thresholds.selection_threshold = 0.25;
document.thresholds.separation_margin = 0.05;
document.thresholds.co_occurrence_threshold = 0.85;
pathValue = fullfile(workspace, "relaxed_attribution_policy.json");
writeText(pathValue, string(jsonencode(document, PrettyPrint=true)) + newline);
end

% ================================================================= refusals ===

function value = emptyRefusals()
value = table('Size', [0 3], 'VariableTypes', ["string", "string", "string"], ...
    'VariableNames', ["what_was_attempted", "identifier", "message"]);
end

function [refusals, captured] = recordRefusal(refusals, description, action)
%RECORDREFUSAL Exercise a path that must refuse, and keep what it said.
%
% The Phase 3 demonstration's most useful single element was a source clock that
% failed with a named reason beside two that succeeded. These are this phase's.
try
    action();
    error("vawlume:examples:RefusalNotRaised", ...
        "Expected a refusal for: %s", description);
catch exception
    if exception.identifier == "vawlume:examples:RefusalNotRaised"
        rethrow(exception);
    end
    captured = struct(raised=true, identifier=string(exception.identifier), ...
        message=string(exception.message));
end
refusals = [refusals; table(string(description), captured.identifier, ...
    firstSentence(captured.message), VariableNames=["what_was_attempted", ...
    "identifier", "message"])];
end

function value = firstSentence(message)
value = string(message);
stop = strfind(value, ". ");
if ~isempty(stop)
    value = extractBefore(value, stop(1) + 1);
end
end

% =============================================================== read-backs ===

function value = correspondenceReadback(rows)
value = rows(:, ["native_window_id", "target_kind", "attribution_target_id", ...
    "iou_basis", "aligned_start_s", "aligned_end_s", "temporal_iou", ...
    "start_extrapolated", "end_extrapolated"]);
end

function value = decisionReadback(result)
value = struct(policy=result.policy, ...
    decisions=result.decisions(:, ["attribution_target_id", ...
        "decision_status", "applied_threshold", "selected_count", ...
        "contender_count", "readable_count", "top_value"]), ...
    status_counts=groupcounts(result.decisions, "decision_status"), ...
    run_completed=result.run_completed);
end

function value = compactReport(report)
value = struct( ...
    run_key=report.run_key, ...
    status=report.status, ...
    analysis_status=report.analysis_status, ...
    grain=grainTable(report), ...
    targets=report.targets, ...
    candidates=report.candidates, ...
    evidence=report.evidence, ...
    imported_claims=report.imported_claims, ...
    claim_correspondences=report.claim_correspondences, ...
    decisions=report.decisions, ...
    qc=report.qc, ...
    qc_note=report.qc_note, ...
    basis_note=report.basis_note);
end

function value = grainTable(report)
%GRAINTABLE What each returned table counts, beside how many rows it has.
%
% Displayed this way deliberately. `claim_correspondences` is (claim,
% correspondence), so a window carrying two claims appears twice there and once
% in `correspondences`; a row count shown without its grain invites exactly that
% miscount.
names = ["targets"; "candidates"; "evidence"; "imported_claims"; ...
    "correspondences"; "claim_correspondences"; "decisions"; ...
    "decision_selections"];
grains = ["attribution target"; "(target, candidate entity)"; ...
    "stored evidence record"; "(imported window, claimed caller)"; ...
    "stored correspondence"; "(claim, correspondence) - the joined story"; ...
    "(target, policy version)"; "candidate a decision selected"];
counts = zeros(numel(names), 1);
for index = 1:numel(names)
    counts(index) = height(report.(names(index)));
end
value = table(names, grains, counts, ...
    VariableNames=["table_name", "one_row_per", "row_count"]);
end

function value = databaseInventory(conn)
names = ["detections"; "consensus_events"; "attribution_runs"; ...
    "attribution_targets"; "attribution_candidates"; "attribution_evidence"; ...
    "imported_attribution_windows"; "imported_attribution_claims"; ...
    "attribution_window_correspondences"; "attribution_decisions"; ...
    "attribution_decision_candidates"; "alignment_segments"];
counts = zeros(numel(names), 1);
for index = 1:numel(names)
    rows = fetch(conn, "SELECT COUNT(*) AS n FROM " + names(index));
    counts(index) = double(rows.n(1));
end
value = table(names, counts, VariableNames=["table_name", "row_count"]);
end

% =================================================================== print ===

function printDemonstration(value)
fprintf('\nVAWLUME synthetic Phase 4 caller-attribution demonstration\n');
fprintf('%s\n', value.calibration_boundary);

fprintf('\nSession seeded directly (each has its own demonstration):\n  %s\n', ...
    strjoin(value.session.seeded_directly, '\n  '));
fprintf('Channels registered through the public function: %s\n', ...
    strjoin(value.channels.labels, ', '));
fprintf('Consensus events derived by matching: %d (%s)\n', ...
    numel(value.consensus.consensus_event_ids), ...
    strjoin(value.consensus.derivation_method, ', '));

fprintf('\nExporting system clock -> recording clock (%s, %s):\n', ...
    value.exporter_clock.method, value.exporter_clock.status);
disp(value.exporter_clock.recovered);
fprintf('  anchored source range: [%g, %g] s; declared breakpoint: %g s\n', ...
    value.exporter_clock.anchored_source_range(1), ...
    value.exporter_clock.anchored_source_range(2), ...
    value.exporter_clock.breakpoint);

fprintf('\nImport dry run wrote nothing (%d windows, %d claims, %d rows unmapped):\n', ...
    value.import_preview.window_count, value.import_preview.claim_count, ...
    value.import_preview.unmapped_rows);
disp(value.import_preview.issues(:, ["severity", "code", "message"]));
fprintf('Imported: %s; exporting system: %s; profile %s@%s\n', ...
    value.import.status, value.import.exporting_system.name, ...
    value.mapping_profile.profile_key, value.mapping_profile.version_label);
fprintf('  source SHA-256: %s\n', value.import.source_checksum);
fprintf('Imported claims, exactly as the file carried them:\n');
disp(value.detection_report.imported_claims(:, ["native_window_id", ...
    "source_caller_label", "entity_native_id", "score", "probability"]));
fprintf('  claims the exporter supplied no score for: %d (NaN, never 0 and never 1.0)\n', ...
    value.detection_report.qc.claims_without_score);

fprintf('\nCorrespondence on the %s basis, through alignment run %d:\n', ...
    value.correspondence.iou_basis, value.correspondence.alignment_run_id);
disp(value.correspondence.rows);
fprintf('  eligibility rule: %s, min temporal IoU %g (%s)\n', ...
    value.correspondence.rule.eligibility_rule, ...
    value.correspondence.rule.min_temporal_iou, ...
    value.correspondence.rule.calibration_status);
fprintf(['  windows corresponding to nothing: %d; windows corresponding to ' ...
    'more than one event: %d\n'], ...
    value.correspondence.windows_without_correspondence, ...
    value.correspondence.ambiguous_window_count);
fprintf(['  the window spanning the declared breakpoint crosses %d segments: ' ...
    'native %.4f s becomes aligned %.4f s (%+.4f s)\n'], ...
    value.breakpoint_crossing.segments_crossed, ...
    value.breakpoint_crossing.native_duration_s, ...
    value.breakpoint_crossing.aligned_duration_s, ...
    value.breakpoint_crossing.duration_change_s);

fprintf('\nCandidates per target:\n');
disp(value.candidates.per_target);
fprintf('  targets with no candidate at all:\n');
disp(value.detection_report.qc.targets_without_candidate(:, ...
    ["attribution_target_id", "target_kind"]));
fprintf('Four evidence dimensions on one candidate, never combined:\n');
disp(value.evidence.display);
fprintf('  where each number came from (relational where the schema has a link):\n');
disp(value.evidence.provenance);
fprintf('  and what each number means where it came from:\n');
for index = 1:height(value.evidence.semantics)
    fprintf('    %-20s %s\n', value.evidence.semantics.evidence_dimension(index), ...
        value.evidence.semantics.value_semantics(index));
end

fprintf('\nDecisions under the shipped policy:\n');
disp(value.decisions.shipped.decisions);
fprintf('The same candidates under a policy with different thresholds:\n');
disp(value.decisions.comparison.per_target);
fprintf('  statuses that moved: %d; candidate rows unchanged: %d\n', ...
    value.decisions.comparison.statuses_moved, ...
    value.decisions.comparison.candidates_unchanged);

fprintf('\nRead-back grain, so nothing is counted from the wrong table:\n');
disp(value.detection_report.grain);
fprintf('Evidence by dimension (no total, no coverage fraction):\n');
disp(value.detection_report.qc.evidence_by_dimension);
fprintf('Correspondence scores per basis pair (never pooled):\n');
disp(value.detection_report.qc.correspondence_by_basis);
fprintf('Imported label resolution:\n');
disp(value.detection_report.qc.imported_label_resolution);

fprintf('\nThe same representation over consensus events (%s basis):\n', ...
    value.consensus_run.iou_basis);
disp(value.consensus_run.decision_status_counts);
fprintf('  run status: %s / %s; completed by the decision batch: %d\n', ...
    value.consensus_run.run_status, value.consensus_run.analysis_status, ...
    value.consensus_run.run_completed);

fprintf('\nRefusals demonstrated beside the successes:\n');
disp(value.refusals);

fprintf('\nDatabase inventory:\n');
disp(value.database_inventory);
fprintf('Foreign-key violations: %d; temporary artifacts removed: %d\n', ...
    height(value.foreign_key_check), value.temporary_artifacts_removed);
fprintf('Proves:\n  %s\n', strjoin(value.proves, '\n  '));
fprintf('Does not prove:\n  %s\n', strjoin(value.does_not_prove, '\n  '));
end

% ================================================================= helpers ===

function writeText(pathValue, value)
fileId = fopen(pathValue, "w");
if fileId < 0
    error("vawlume:examples:FixtureCreationFailed", ...
        "Could not create demonstration input: %s", pathValue);
end
cleanupFile = onCleanup(@() fclose(fileId));
fprintf(fileId, "%s", value);
clear cleanupFile
end

function root = normalizedRepoRoot(root)
if strlength(root) == 0
    root = fileparts(fileparts(mfilename("fullpath")));
end
try
    root = string(java.io.File(char(root)).getCanonicalPath());
catch
    root = string(root);
end
end

function value = pathContains(target)
value = any(split(string(path), pathsep) == string(target));
end

function restoreSourcePath(sourcePath, shouldRemove)
if shouldRemove && pathContains(sourcePath), rmpath(sourcePath); end
end

function closeConnection(conn)
try
    if isopen(conn), close(conn); end
catch
end
end

function removeTree(root)
% Tolerant because this also runs as an onCleanup destructor on an error path,
% where the database connection may still hold the file. The demonstration's
% `temporary_artifacts_removed` field is measured afterwards rather than assumed,
% so a swallowed failure here still shows up there.
try
    if isfolder(root), rmdir(root, "s"); end
catch
end
end
