function demonstration = consilience_exploration_demo(options)
%CONSILIENCE_EXPLORATION_DEMO Demonstrate the extractor-consilience exploration.
%
% DEMONSTRATION = CONSILIENCE_EXPLORATION_DEMO() runs the complete exploratory
% workflow over a disposable six-recording synthetic project:
%
%   1. resolve the dataset and apply the tracked reference configuration;
%   2. diagnose the candidate-metric space - distributions, Pearson, Spearman,
%      partial correlation, coverage and redundancy;
%   3. resolve which threshold dimensions to screen and at what values;
%   4. run a bounded interaction-aware screen over the whole dataset;
%   5. draw a seeded, metadata-stratified subset of recordings;
%   6. run a richer probe on it and compare the two probes;
%   7. characterize exact extractor-support patterns at the reference;
%   8. render a representative spectrogram gallery;
%   9. export tables, figures, the example index and provenance.
%
% It then runs the workflow again with Stages="diagnostics" to show that a stage
% can be run on its own without building a design or executing a probe.
%
% WHAT THE DEMONSTRATION IS FOR. It proves the path works on real public
% functions and that its automatic choices are reproducible. It proves nothing
% about vocalizations: the recordings are synthetic, the detections were written
% by hand to exercise the matcher, and every threshold in the tracked reference
% configuration is an illustrative demonstration value.
%
% IT DELIBERATELY SHOWS THIN DATA. The whole-dataset screen is capped at four
% configurations, which over three factors is a resolution-III fraction whose
% main effects are aliased with two-factor interactions - so the screen makes no
% leverage claim about any factor and says so, and the full-factorial subset
% probe de-aliases part of it. Several exact support patterns hold too few
% groups to sample the requested number of examples from, and the shortfall is
% reported rather than padded from a neighbouring pattern. A demonstration that
% only ever showed the happy path would teach users to be surprised by their own
% data.
%
% Name-value options:
%   Print     print compact developer-facing read-backs (default true)
%   RepoRoot  repository root, inferred from this file by default
%
% See also VAWLUME.EDA.RUNEXPLORATION, MULTI_EXTRACTOR_AGREEMENT_DEMO.

arguments
    options.Print (1,1) logical = true
    options.RepoRoot (1,1) string = ""
end

repoRoot = normalizedRepoRoot(options.RepoRoot);
sourcePath = fullfile(repoRoot, "src");
removeSourcePath = ~pathContains(sourcePath);
if removeSourcePath, addpath(sourcePath); end
cleanupPath = onCleanup(@() restoreSourcePath(sourcePath, removeSourcePath));

workspaceRoot = fullfile(tempdir, ...
    "VAWLUME consilience exploration demo " + string(java.util.UUID.randomUUID));
mkdir(workspaceRoot);
cleanupWorkspace = onCleanup(@() removeTree(workspaceRoot));
databasePath = fullfile(workspaceRoot, "consilience_exploration_demo.sqlite");

% 1. A disposable six-recording project. The tracked Phase 1 fixture supplies
%    one richly populated recording; the rest exist so a subset can be a subset
%    and a stratum can be a stratum.
[conn, ~] = vawlume.db.createPhase1FixtureDatabase(databasePath, repoRoot);
cleanupConnection = onCleanup(@() closeConnection(conn));
extendProject(conn);
sourceRoot = fullfile(workspaceRoot, "source");
audioPath = writeGalleryAudio(conn, sourceRoot);

% 2. The whole workflow, from one call. The user-facing configuration is the
%    light one: a seed, a subset size, and one factor switched off - the last
%    two only to keep the demonstration affordable enough to run as a test.
%    Everything else - which factors to screen, at what values, which metadata
%    field to stratify on, how the design is constructed - the workflow decides
%    and records.
explorationOptions = vawlume.eda.explorationOptions(struct( ...
    seed=20260918, ...
    subset_size=3, ...
    disabled_factors="max_abs_duration_difference_s"));
outputRoot = fullfile(workspaceRoot, "output");

exploration = vawlume.eda.runExploration(conn, ...
    struct(project_key="phase1_synthetic_fixture"), ...
    Options=explorationOptions, RepoRoot=repoRoot, OutputRoot=outputRoot, ...
    SourceRoot=sourceRoot, ...
    MaximumConfigurations=4, ...       % forces the fraction; see the note above
    ExamplesPerPattern=2, ExampleRecordingId=1, ...
    ResolutionDpi=96, Print=options.Print);

% 3. One stage on its own. The diagnostics need the reference run's candidate
%    pairs and nothing else, so no design is built and no probe is executed.
diagnosticsOnly = vawlume.eda.runExploration(conn, ...
    struct(project_key="phase1_synthetic_fixture"), ...
    Options=explorationOptions, RepoRoot=repoRoot, OutputRoot=outputRoot, ...
    Stages="diagnostics", Print=false);

% 4. Pricing a probe without running it. Apply=false builds both designs and
%    reports what executing them would cost, and writes no analysis, no export
%    and no provenance record. In practice a user does this BEFORE committing to
%    a probe; it comes last here only because the demonstration has one database
%    and the assertion worth making is that the estimate matches what step 2
%    actually executed. The diagnostics are pointed at the reference run's own
%    analyses so the probe values are the same ones step 2 resolved.
planned = vawlume.eda.runExploration(conn, ...
    struct(project_key="phase1_synthetic_fixture"), ...
    Options=explorationOptions, RepoRoot=repoRoot, OutputRoot=outputRoot, ...
    MaximumConfigurations=4, Apply=false, Print=false, ...
    DiagnosticAnalyses=exploration.reference.matching_run_keys);

demonstration = struct( ...
    architecture=["resolve dataset"; "apply reference configuration"; ...
        "full-dataset diagnostics"; "resolve probe values"; ...
        "bounded whole-dataset screen"; "stratified recording subset"; ...
        "richer subset probe"; "probe concordance"; ...
        "exact support-pattern characterization"; ...
        "representative spectrogram gallery"; ...
        "tables, figures, example index, provenance"], ...
    calibration_boundary="Illustrative synthetic prototype settings. No " + ...
        "configuration explored here is optimal, validated, recommended, or " + ...
        "calibrated, and agreement among extractors is methodological " + ...
        "evidence rather than ground truth.", ...
    exploration_run_key=exploration.exploration_run_key, ...
    status=exploration.status, ...
    stages=exploration.stages, ...
    dataset=datasetSummary(exploration), ...
    diagnostics=diagnosticsSummary(exploration), ...
    probe=probeSummary(exploration), ...
    screen=probeSummary2(exploration.screen), ...
    subset=subsetSummary(exploration), ...
    concordance=concordanceSummary(exploration), ...
    support_patterns=supportSummary(exploration), ...
    examples=exampleSummary(exploration), ...
    exports=exportSummary(exploration), ...
    stage_skipping=struct( ...
        requested="diagnostics", ...
        stages_run=diagnosticsOnly.stages.stage( ...
            diagnosticsOnly.stages.status == "completed")', ...
        design_built=isfield(diagnosticsOnly, "screen"), ...
        probe_executed=isfield(diagnosticsOnly, "subset"), ...
        status=diagnosticsOnly.status), ...
    planning=struct( ...
        status=planned.status, ...
        screen_design_type=planned.screen.design.design_type, ...
        screen_configuration_count=planned.screen.design.configuration_count, ...
        screen_predicted_analyses=planned.screen.cost.total_analyses, ...
        subset_predicted_analyses=planned.subset.cost.total_analyses, ...
        nothing_exported=~isfield(planned, "exports"), ...
        skipped_reasons=planned.stages.reason( ...
            planned.stages.status == "skipped")'), ...
    honest_degenerate_cases=degenerateCases(exploration), ...
    proves=[ ...
        "one call carries a dataset from diagnostics to an exported poster bundle"; ...
        "every automatic choice - factors, probe values, subset, seed, design - is recorded"; ...
        "the two sensitivity probes are compared as a table and never as a score"; ...
        "exact extractor-support patterns survive to the figures uncollapsed"; ...
        "USVSEG annotations carry a time extent and measured markers, never a synthesized band"; ...
        "a stage can be run on its own without executing a probe"], ...
    does_not_prove=[ ...
        "that any threshold is calibrated, recommended, or optimal"; ...
        "that agreement among extractors establishes that a detection is real"; ...
        "that an extractor-unique detection is false"; ...
        "that agreement between the two probes removes the need for calibration"; ...
        "anything about vocalizations: the fixture is synthetic"], ...
    caution=exploration.caution, ...
    workspace_root=workspaceRoot, database_path=databasePath, ...
    audio_path=audioPath, temporary_artifacts_removed=false);

close(conn);
clear cleanupConnection
removeTree(workspaceRoot);
clear cleanupWorkspace
demonstration.temporary_artifacts_removed = ...
    ~isfolder(workspaceRoot) && ~isfile(databasePath);

if options.Print, printDemonstration(demonstration); end
clear cleanupPath
end

% ------------------------------------------------------------- read-backs ---

function value = datasetSummary(exploration)
dataset = exploration.dataset;
value = struct( ...
    project_key=dataset.project_key, ...
    recording_count=dataset.recording_count, ...
    extractor_keys=string(dataset.extractor_keys(:))', ...
    pairs_per_recording=dataset.pairs_per_recording, ...
    excluded_recording_count=height(dataset.excluded_recordings));
end

function value = diagnosticsSummary(exploration)
diagnostics = exploration.diagnostics;
value = struct( ...
    candidate_count=diagnostics.surface.candidate_count, ...
    metric_count=numel(diagnostics.surface.metric_names), ...
    quantile_definition=diagnostics.distributions.quantile_definition, ...
    observation_policy=diagnostics.dependencies.observation_policy.mode, ...
    complete_case_n=diagnostics.dependencies.observation_policy.complete_case_n, ...
    redundant_pair_count=height(diagnostics.dependencies.redundancy), ...
    distributions=diagnostics.distributions.distributions(:, ...
        ["metric_name", "supported", "non_finite", "statistics_status"]));
end

function value = probeSummary(exploration)
resolution = exploration.probe.resolution;
value = struct( ...
    seed=resolution.seed, ...
    seed_source=resolution.seed_source, ...
    active_factor_names=string(resolution.active_factor_names(:))', ...
    inactive_factor_names=string(resolution.inactive_factor_names(:))', ...
    factors=resolution.factors(:, ["factor_name", "is_active", ...
        "inactive_reason", "low_value", "high_value", "value_source", ...
        "strictness_direction", "reference_comparison"]));
end

function value = probeSummary2(probe)
value = struct( ...
    design_type=probe.design.design_type, ...
    configuration_count=probe.design.configuration_count, ...
    configuration_ids=string(probe.design.configurations.configuration_id(:))', ...
    design_resolution=probe.design.alias.resolution, ...
    main_effects_clear_of_two_factor_interactions= ...
        probe.design.alias.main_effects_clear_of_two_factor_interactions, ...
    predicted_analyses=probe.cost.total_analyses, ...
    executed_units=height(probe.run.manifest), ...
    leverage_counts=probe.leverage.category_counts);
end

function value = subsetSummary(exploration)
subset = exploration.subset.subset;
value = struct( ...
    is_stratified=subset.is_stratified, ...
    stratum_field=subset.stratum_field, ...
    fallback_reason=subset.fallback_reason, ...
    requested_size=subset.requested_size, ...
    realized_size=subset.realized_size, ...
    selected_recording_ids=subset.selected_recording_ids(:)', ...
    allocation=subset.allocation, ...
    probe=probeSummary2(exploration.subset), ...
    de_aliased_count=exploration.subset.design.screen_comparison.de_aliased_count);
end

function value = concordanceSummary(exploration)
concordance = exploration.concordance;
value = struct( ...
    comparison_row_count=height(concordance.comparison), ...
    contingency=concordance.category_contingency, ...
    factor_summary=concordance.factor_summary, ...
    calibration_note=concordance.calibration_note, ...
    composite_score_returned=false);
end

function value = supportSummary(exploration)
support = exploration.support_patterns;
patterns = support.primary.patterns;
value = struct( ...
    profiled_recording_count=numel(support.recording_ids), ...
    primary_recording_id=support.primary_recording_id, ...
    pattern_count=height(patterns), ...
    absent_pattern_count=sum(patterns.is_absent), ...
    patterns=patterns(:, ["extractor_set_label", "group_count", ...
        "group_proportion", "detection_count"]), ...
    cross_pattern_comparable=string( ...
        support.comparable_features.cross_pattern_comparable(:))', ...
    extractor_restricted=string( ...
        support.comparable_features.extractor_restricted(:))', ...
    pair_pattern_row_count=height(support.primary.pair_patterns));
end

function value = exampleSummary(exploration)
examples = exploration.examples;
value = struct( ...
    recording_id=examples.recording_id, ...
    target_per_pattern=examples.sample.target_per_pattern, ...
    example_count=examples.gallery.example_count, ...
    success_count=examples.gallery.success_count, ...
    failure_count=examples.gallery.failure_count, ...
    index_row_count=height(examples.gallery.index), ...
    index_column_count=width(examples.gallery.index), ...
    example_ids=string(examples.gallery.index.example_id(:))', ...
    image_paths=string(examples.gallery.index.image_path(:))', ...
    image_count=numel(dir(fullfile(examples.gallery.images_directory, "*.png"))), ...
    short_patterns=examples.sample.short_patterns, ...
    empty_patterns=examples.sample.empty_patterns, ...
    frequency_extent_sources=unique(splitJoined( ...
        examples.gallery.index.frequency_extent_sources))');
end

function value = exportSummary(exploration)
exports = exploration.exports;
value = struct( ...
    table_count=height(exports.tables), ...
    table_names=exports.tables.name', ...
    figure_count=sum(~startsWith(exports.figures.path, "not drawn")), ...
    figures=exports.figures, ...
    figures_not_drawn=exports.figures(startsWith(exports.figures.path, ...
        "not drawn"), :), ...
    provenance_written=isfile(exports.provenance_path), ...
    provenance_bytes=fileBytes(exports.provenance_path));
end

function value = degenerateCases(exploration)
%DEGENERATECASES The places this dataset is too thin, stated positively.
screen = exploration.screen;
patterns = exploration.support_patterns.primary.patterns;
value = struct( ...
    screen_makes_no_leverage_claim= ...
        ~any(ismember(screen.leverage.categories.category, ...
        ["high_leverage", "moderate_leverage", "low_leverage"])), ...
    screen_main_effects_are_aliased=screen.leverage.main_effects_are_aliased, ...
    empty_support_patterns=patterns.extractor_set_label(patterns.is_absent)', ...
    example_shortfall_pattern_count= ...
        height(exploration.examples.sample.short_patterns));
end

% ---------------------------------------------------------------- fixture ---
%
% Six recordings, each carrying one extraction run per extractor, plus a
% recording-level genotype attribute over five of them. The sizes differ on
% purpose: equal recordings would let a pooled fraction and an averaged one agree
% exactly, and the response layer's pooling rule would go untested here too. The
% sixth recording carries no genotype, so the stratified sample has to represent
% "(missing)" rather than drop it.

function extendProject(conn)
execute(conn, "INSERT INTO extraction_runs(extraction_run_id,project_id," + ...
    "extractor_version_id,run_key,status) VALUES" + ...
    "(80,1,2,'demo_mupet_baseline_v1','imported')," + ...
    "(81,1,3,'demo_usvseg_baseline_v1','imported')");
execute(conn, "INSERT INTO extraction_run_inputs(extraction_run_id," + ...
    "recording_id,input_role) VALUES(80,2,'source_audio'),(81,2,'source_audio')");
insertDetection(conn, 3, 2, "demo-ds-baseline-2", 20.000, 20.060);
insertDetection(conn, 80, 2, "demo-mupet-baseline-1", 20.004, 20.052);
insertDetection(conn, 81, 2, "demo-usvseg-baseline-1", 20.002, 20.049);
insertDetection(conn, 81, 2, "demo-usvseg-baseline-3", 30.000, 30.040);

sourceFileId = nextId(conn, "source_files", "source_file_id");
runId = 90;
for recordingId = 3:6
    native = sprintf("REC_DEMO_%02d", recordingId);
    execute(conn, "INSERT INTO source_files(source_file_id,project_id," + ...
        "file_role,path_or_uri,relative_path,filename) VALUES(" + ...
        string(sourceFileId) + ",1,'recording_audio','audio/" + native + ...
        ".wav','audio/" + native + ".wav','" + native + ".wav')");
    execute(conn, "INSERT INTO recordings(recording_id,project_id," + ...
        "source_file_id,native_recording_id) VALUES(" + string(recordingId) + ...
        ",1," + string(sourceFileId) + ",'" + native + "')");
    sourceFileId = sourceFileId + 1;
    for versionId = 1:3
        execute(conn, "INSERT INTO extraction_runs(extraction_run_id," + ...
            "project_id,extractor_version_id,run_key,status) VALUES(" + ...
            string(runId) + ",1," + string(versionId) + ",'demo_extra_r" + ...
            string(recordingId) + "_v" + string(versionId) + "','imported')");
        execute(conn, "INSERT INTO extraction_run_inputs(extraction_run_id," + ...
            "recording_id,input_role) VALUES(" + string(runId) + "," + ...
            string(recordingId) + ",'source_audio')");
        callCount = 2 + mod(recordingId + versionId, 3);
        for call = 1:callCount
            base = 5 * call + 0.01 * versionId;
            insertDetection(conn, runId, recordingId, ...
                sprintf("demo-r%d-v%d-%d", recordingId, versionId, call), ...
                base, base + 0.05 + 0.005 * versionId);
        end
        runId = runId + 1;
    end
end

genotype = ["WT", "KO", "WT", "KO", "WT"];
for recordingId = 1:numel(genotype)
    execute(conn, "INSERT INTO recording_attributes(recording_id," + ...
        "attribute_name,value_type,value_text) VALUES(" + ...
        string(recordingId) + ",'genotype','text','" + ...
        genotype(recordingId) + "')");
end
end

function path = writeGalleryAudio(conn, sourceRoot)
%WRITEGALLERYAUDIO A real WAV for the one recording the gallery draws from.
%
% The spectrogram is computed from the original audio, never from an
% extractor-rendered image, so the gallery needs a readable file. The recording's
% declared sample rate is lowered to match the file it is given, and the tone
% bursts sit where the fixture's detections are so the images show something.
sampleRate = 192000;
execute(conn, "UPDATE recordings SET sample_rate_hz=" + string(sampleRate) + ...
    " WHERE recording_id=1");
relative = string(fetch(conn, "SELECT sf.relative_path FROM recordings r " + ...
    "JOIN source_files sf ON sf.source_file_id=r.source_file_id " + ...
    "WHERE r.recording_id=1").relative_path(1));
path = fullfile(sourceRoot, replace(relative, "/", filesep));
if ~isfolder(fileparts(path)), mkdir(fileparts(path)); end

bursts = fetch(conn, "SELECT MIN(start_time_s) AS t0, MAX(end_time_s) AS t1 " + ...
    "FROM detections WHERE recording_id=1 GROUP BY " + ...
    "CAST(start_time_s AS INTEGER) / 5");
durationS = max(double(bursts.t1)) + 1;
n = round(durationS * sampleRate);
t = (0:(n - 1))' / sampleRate;
samples = zeros(n, 1);
for index = 1:height(bursts)
    window = t >= (double(bursts.t0(index)) - 0.01) & ...
        t <= (double(bursts.t1(index)) + 0.01);
    local = t(window) - t(find(window, 1));
    span = max(local(end) - local(1), eps);
    taper = sin(pi * local / span) .^ 2;
    samples(window) = 0.7 * taper .* sin(2 * pi * 62000 * t(window));
end
audiowrite(char(path), samples, sampleRate, BitsPerSample=16);
end

function value = nextId(conn, tableName, column)
rows = fetch(conn, "SELECT IFNULL(MAX(" + column + "),0) + 1 AS n FROM " + ...
    tableName);
value = double(rows.n(1));
end

function insertDetection(conn, runId, recordingId, nativeId, startS, endS)
execute(conn, "INSERT INTO detections(extraction_run_id,recording_id," + ...
    "native_event_id,start_time_s,end_time_s,timing_basis) VALUES(" + ...
    string(runId) + "," + string(recordingId) + ",'" + nativeId + "'," + ...
    sprintf("%.17g", startS) + "," + sprintf("%.17g", endS) + ...
    ",'profile_selected_event_geometry')");
end

% -------------------------------------------------------------- utilities ---

function value = splitJoined(values)
value = strings(0, 1);
for entry = string(values(:))'
    parts = split(entry, "|");
    value = [value; parts(strlength(parts) > 0)]; %#ok<AGROW>
end
value = unique(value);
end

function value = fileBytes(path)
value = 0;
listing = dir(path);
if ~isempty(listing)
    value = listing(1).bytes;
end
end

function root = normalizedRepoRoot(root)
if strlength(root) == 0, root = fileparts(fileparts(mfilename("fullpath"))); end
try
    root = string(java.io.File(char(root)).getCanonicalPath());
catch
end
end

function value = pathContains(target)
value = any(split(string(path), pathsep) == string(target));
end

function restoreSourcePath(sourcePath, shouldRemove)
if shouldRemove && pathContains(sourcePath), rmpath(sourcePath); end
end

function closeConnection(conn)
try
    if isopen(conn), close(conn); end
catch
end
end

function removeTree(root)
if isfolder(root), rmdir(root, "s"); end
end

function printDemonstration(value)
disp("VAWLUME EXTRACTOR-CONSILIENCE EXPLORATION DEMONSTRATION")
disp(value.calibration_boundary)
fprintf("Exploration run '%s': %s\n", value.exploration_run_key, value.status);
disp("Dataset:")
disp(value.dataset)
disp("Probe factors (the workflow chose these; none is optimal):")
disp(value.probe.factors)
fprintf(['Whole-dataset screen: %s, %d configurations, resolution %d, main ' ...
    'effects clear of two-factor interactions: %d\n'], ...
    value.screen.design_type, value.screen.configuration_count, ...
    value.screen.design_resolution, ...
    value.screen.main_effects_clear_of_two_factor_interactions);
fprintf("Subset: stratified=%d on '%s', %d of a requested %d recording(s)\n", ...
    value.subset.is_stratified, value.subset.stratum_field, ...
    value.subset.realized_size, value.subset.requested_size);
fprintf(['Subset probe: %s, %d configurations; %d effect(s) de-aliased by ' ...
    'the subset\n'], value.subset.probe.design_type, ...
    value.subset.probe.configuration_count, value.subset.de_aliased_count);
disp("Leverage categories, whole-dataset screen:")
disp(value.screen.leverage_counts)
disp("Leverage categories, subset probe:")
disp(value.subset.probe.leverage_counts)
fprintf("Probe concordance: %d factor-response rows, no composite score\n", ...
    value.concordance.comparison_row_count);
disp("Exact support patterns at the reference configuration:")
disp(value.support_patterns.patterns)
fprintf("Comparable across every pattern: %s\n", ...
    strjoin(value.support_patterns.cross_pattern_comparable, ", "));
fprintf("Extractor-restricted, within eligible patterns only: %s\n", ...
    strjoin(value.support_patterns.extractor_restricted, ", "));
fprintf(['Gallery: %d example(s), %d rendered, %d image(s), %d index ' ...
    'column(s); frequency extents: %s\n'], ...
    value.examples.example_count, value.examples.success_count, ...
    value.examples.image_count, value.examples.index_column_count, ...
    strjoin(value.examples.frequency_extent_sources, ", "));
if height(value.examples.short_patterns) > 0
    disp("Patterns with fewer examples than requested (reported, not padded):")
    disp(value.examples.short_patterns)
end
if height(value.examples.empty_patterns) > 0
    disp("Patterns with no members at all:")
    disp(value.examples.empty_patterns)
end
fprintf("Exports: %d table(s), %d figure(s), provenance written: %d\n", ...
    value.exports.table_count, value.exports.figure_count, ...
    value.exports.provenance_written);
if height(value.exports.figures_not_drawn) > 0
    disp("Figures not drawn (a vawlume:eda: identifier is a refusal on thin " + ...
        "data; anything else is a defect worth reporting):")
    disp(value.exports.figures_not_drawn)
end
fprintf("Stage skipping: requested '%s'; ran %s; probe executed: %d\n", ...
    value.stage_skipping.requested, ...
    strjoin(value.stage_skipping.stages_run, ", "), ...
    value.stage_skipping.probe_executed);
fprintf(['Pricing without running: %s; screen %s/%d cfg = %d analyses, ' ...
    'subset = %d analyses; nothing exported: %d\n'], ...
    value.planning.status, value.planning.screen_design_type, ...
    value.planning.screen_configuration_count, ...
    value.planning.screen_predicted_analyses, ...
    value.planning.subset_predicted_analyses, ...
    value.planning.nothing_exported);
fprintf("Temporary artifacts removed: %d\n", value.temporary_artifacts_removed);
fprintf("Proves:\n  %s\n", strjoin(value.proves, newline + "  "));
fprintf("Does not prove:\n  %s\n", ...
    strjoin(value.does_not_prove, newline + "  "));
fprintf("%s\n", strjoin(string(value.caution), newline));
end
