function demonstration = deepsqueak_import_demo(options)
%DEEPSQUEAK_IMPORT_DEMO Demonstrate the DeepSqueak import path end to end.
%
% DEMONSTRATION = DEEPSQUEAK_IMPORT_DEMO() establishes one project recording
% through the real project-intake path, generates a small DeepSqueak-style call
% statistics workbook, imports it with the public DeepSqueak importer, and
% returns relational read-back tables covering run provenance, artifacts,
% detections, native and canonical measurements, and review and label evidence.
% It then reruns the identical import and relocates the workbook to show that
% neither creates a second scientific population.
%
% Every input is generated under the system temporary directory and removed
% before this function returns. No private data is involved and no database edit
% is made by hand.
%
% The flow is:
%
%   synthetic source tree
%       -> project-input JSON profile
%       -> source_mapping.parse + preview
%       -> vawlume.ingest.project(..., Apply=true)
%       -> synthetic DeepSqueak call-statistics .xlsx
%       -> vawlume.ingest.deepsqueak (plan)
%       -> vawlume.ingest.deepsqueak (Apply=true)
%       -> relational read-back
%       -> unchanged rerun and artifact relocation
%
% Name-value options:
%   Print     print a concise developer-facing summary (default true)
%   RepoRoot  repository root; inferred from this file's location by default
%
% What this demonstrates is bounded. It covers the DeepSqueak Excel
% call-statistics export for the tracked v3.2 output mapping profile, and
% nothing else: not every DeepSqueak version, not arbitrary workbook shapes, not
% native .mat parsing, not DeepSqueak classifier or clustering workflows, not
% MUPET, and not cross-extractor matching. The imported review state and labels
% are extractor evidence, not biological truth.
%
% From the repository root:
%
%   addpath("examples")
%   deepsqueak_import_demo
%
% See also VAWLUME.INGEST.DEEPSQUEAK, PROJECT_INTAKE_DEMO.

arguments
    options.Print (1,1) logical = true
    options.RepoRoot (1,1) string = ""
end

repoRoot = normalizedRepoRoot(options.RepoRoot);
sourcePath = fullfile(repoRoot, "src");
removeSourcePath = ~pathContains(sourcePath);
if removeSourcePath
    addpath(sourcePath);
end
cleanupPath = onCleanup(@() restoreSourcePath(sourcePath, removeSourcePath));

workspaceRoot = fullfile(tempdir, ...
    "VAWLUME deepsqueak import demo " + string(java.util.UUID.randomUUID));
mkdir(workspaceRoot);
cleanupWorkspace = onCleanup(@() removeTree(workspaceRoot));
databasePath = fullfile(workspaceRoot, "deepsqueak_import_demo.sqlite");
conn = sqlite(char(databasePath), "create");
cleanupConnection = onCleanup(@() closeConnection(conn));

vawlume.db.applySchema(conn, fullfile(repoRoot, "schema", "schema.sql"));
vawlume.db.registerBuiltinSemantics(conn, repoRoot);

% --- Phase 3: establish one project recording through the public path --------
projectProfilePath = fullfile(repoRoot, "config", "01_mapping_profiles", ...
    "project_inputs", "project_input_source_mapping_examples.json");
sourceRoot = fullfile(workspaceRoot, "project");
audioPath = fullfile(sourceRoot, "control", "mouse_001", "baseline", ...
    "001_baseline_1.wav");
makeParentFolder(audioPath);
writeText(audioPath, "synthetic audio stand-in; no recorded sound is involved");

projectIR = vawlume.source_mapping.parse(projectProfilePath, sourceRoot, ...
    ProfileId="example.project.mouse_courtship.folder_driven", RepoRoot=repoRoot);
projectPreview = vawlume.source_mapping.preview(projectIR);
intake = vawlume.ingest.project(conn, projectIR, struct( ...
    project_key="demo_deepsqueak_import", ...
    project_name="DeepSqueak import demonstration", ...
    description="Disposable Phase 4 demonstration project."), Apply=true, ...
    ProfileLinkagePath=fullfile(repoRoot, "config", "04_examples", ...
    "profile_linkage_example.json"), RepoRoot=repoRoot);

recording = fetch(conn, ...
    "SELECT r.recording_id, IFNULL(r.native_recording_id,'') AS native_recording_id, " + ...
    "IFNULL(sf.relative_path,'') AS source_relative_path " + ...
    "FROM recordings r JOIN source_files sf ON sf.source_file_id = r.source_file_id");
recordingId = double(recording.recording_id(1));

% --- Phase 4: generate a small, deterministic call-statistics workbook -------
artifactRoot = fullfile(workspaceRoot, "deepsqueak");
exportPath = fullfile(artifactRoot, "exports", "MOUSE001_BASELINE_Stats.xlsx");
makeParentFolder(exportPath);
writecell(demonstrationExport(), exportPath);

settingsPath = fullfile(artifactRoot, "deepsqueak_detection_settings.json");
writeText(settingsPath, jsonencode(struct( ...
    profile=struct(id="demo.deepsqueak.settings.v1", ...
    name="Demonstration DeepSqueak detection settings", ...
    kind="extractor_settings", profile_version="1.0.0"), ...
    detection=struct(score_threshold=0.15, frequency_range_khz=[15, 115]))));

runSpec = struct( ...
    run_key="demo_deepsqueak_run_1", ...
    extractor_version="3.2.1", ...
    run_label="Demonstration DeepSqueak detection run", ...
    settings=struct(profile_path=settingsPath));

% Settings provenance is supplied because it is genuinely available here. No
% detector model is declared, because none is known: the demonstration shows
% that absence explicitly rather than inventing a model identity.
recordingRef = struct(recording_id=recordingId);
plan = vawlume.ingest.deepsqueak(conn, exportPath, recordingRef, runSpec, ...
    RepoRoot=repoRoot, ArtifactRoot=artifactRoot);
imported = vawlume.ingest.deepsqueak(conn, exportPath, recordingRef, runSpec, ...
    RepoRoot=repoRoot, ArtifactRoot=artifactRoot, Apply=true);

% --- Rerun and relocation ---------------------------------------------------
beforeRerun = scientificInventory(conn);
rerun = vawlume.ingest.deepsqueak(conn, exportPath, recordingRef, runSpec, ...
    RepoRoot=repoRoot, ArtifactRoot=artifactRoot, Apply=true);
rerunSummary = struct( ...
    committed=rerun.committed, ...
    extraction_run_action=rerun.extraction_run.action, ...
    extraction_run_id_stable=rerun.extraction_run.extraction_run_id == ...
        imported.extraction_run.extraction_run_id, ...
    detections_created=rerun.applied_counts.detections, ...
    detections_reused=rerun.detections.detections_reuse, ...
    measurements_created=rerun.applied_counts.event_measurements, ...
    measurements_reused=rerun.detections.measurements_reuse, ...
    scientific_rows_unchanged=isequal(scientificInventory(conn), beforeRerun));

relocatedRoot = fullfile(workspaceRoot, "relocated");
relocatedPath = fullfile(relocatedRoot, "exports", "MOUSE001_BASELINE_Stats.xlsx");
makeParentFolder(relocatedPath);
copyfile(exportPath, relocatedPath);
relocated = vawlume.ingest.deepsqueak(conn, relocatedPath, recordingRef, ...
    runSpec, RepoRoot=repoRoot, ArtifactRoot=relocatedRoot, Apply=true);
storedArtifactPath = scalarText(conn, ...
    "SELECT path_or_uri FROM artifacts WHERE artifact_type = 'extractor_event_export'");
relocationSummary = struct( ...
    committed=relocated.committed, ...
    extraction_run_action=relocated.extraction_run.action, ...
    artifact_action=string(relocated.artifacts.action(1)), ...
    runtime_path_changed=relocated.export.runtime_path ~= imported.export.runtime_path, ...
    stored_portable_path=storedArtifactPath, ...
    scientific_rows_unchanged=isequal(scientificInventory(conn), beforeRerun));

inventory = scientificInventory(conn);
foreignKeyViolations = fetch(conn, "PRAGMA foreign_key_check");

demonstration = struct( ...
    architecture=[ ...
        "synthetic project source tree"; ...
        "project intake with tracked device/setup linkage"; ...
        "synthetic DeepSqueak call-statistics workbook"; ...
        "adapter read + source_mapping IR"; ...
        "extraction run/artifact provenance"; ...
        "detections, measurements, review, labels"; ...
        "idempotent relational read-back"], ...
    boundaries=prototypeBoundaries(), ...
    project_intake=struct( ...
        status=intake.status, committed=intake.committed, ...
        project_id=intake.project_id, ...
        preview_verdict=projectPreview.verdict, ...
        recording_id=recordingId, ...
        native_recording_id=string(recording.native_recording_id(1)), ...
        source_relative_path=string(recording.source_relative_path(1))), ...
    recording_context=recordingContextRows(conn, recordingId), ...
    import_summary=struct( ...
        ir_valid=imported.plan.export.ir.valid_for_ingest, ...
        ir_source_rows=imported.export.row_count, ...
        ir_value_count=height(imported.plan.export.ir.values), ...
        plan_status=plan.status, ...
        plan_conflicts=numel(plan.conflicts), ...
        planned_detections=plan.detections.planned, ...
        planned_measurements=plan.detections.measurements_create, ...
        apply_status=imported.status, ...
        committed=imported.committed, ...
        settings_status=imported.settings.status, ...
        model_status=imported.model.status), ...
    diagnostics=imported.diagnostics, ...
    extraction_run_provenance=extractionRunRows(conn), ...
    artifact_provenance=artifactRows(conn), ...
    detections=detectionRows(conn), ...
    measurements=measurementRows(conn), ...
    review_and_labels=reviewLabelRows(conn), ...
    rerun=rerunSummary, ...
    relocation=relocationSummary, ...
    database_inventory=inventory, ...
    foreign_key_violations=foreignKeyViolations, ...
    workspace_root=workspaceRoot, database_path=databasePath, ...
    temporary_artifacts_removed=false);

close(conn);
clear cleanupConnection
removeTree(workspaceRoot);
clear cleanupWorkspace
demonstration.temporary_artifacts_removed = ...
    ~isfolder(workspaceRoot) && ~isfile(databasePath);

if options.Print
    printDemonstration(demonstration);
end
clear cleanupPath
end

% ------------------------------------------------------- synthetic input ---

function cells = demonstrationExport()
%DEMONSTRATIONEXPORT Five deterministic calls in the tracked v3.2 export shape.
%
% Labels are opaque extractor tokens. No biological narrative is attached to
% them, and none should be read into them.
headers = {'File', 'ID', 'Label', 'Accepted', 'Score', 'Begin Time (s)', ...
    'End Time (s)', 'Call Length (s)', 'Principle Frequency (kHz)', ...
    'Low Freq (kHz)', 'High Freq (kHz)', 'Delta Freq (kHz)', ...
    'Frequency Standard Deviation (kHz)', 'Slope (kHz/s)', 'Sinuosity', ...
    'Mean Power (dB/Hz)', 'Tonality', 'Peak Freq (kHz)'};
detectionFile = 'synthetic/deepsqueak/MOUSE001_BASELINE_detections.mat';
cells = [
    headers
    {detectionFile, 1, 'class_a', 1, 0.9134, 10.000, 10.050, 0.050, ...
        62.4, 45.1, 80.2, 35.1, 3.2, -120.5, 1.12, -71.4, 0.78, 63.0}
    {detectionFile, 2, 'class_a', 1, 0.8021, 20.000, 20.044, 0.044, ...
        61.0, 50.0, 72.0, 22.0, 2.1, 15.0, 1.05, -70.1, [], 61.5}
    {detectionFile, 3, 'class_b', 1, 0.6440, 31.250, 31.362, 0.112, ...
        58.2, 40.6, 76.9, 36.3, 4.0, -44.8, 1.31, -68.7, 0.66, 59.4}
    {detectionFile, 4, 'class_b', 0, 0.2107, 40.000, 40.100, 0.100, ...
        63.5, 42.0, 84.0, 42.0, 4.4, -8.25, 1.40, -69.3, 0.69, 64.2}
    {detectionFile, 5, 'class_c', 0, 0.1802, 52.500, 52.530, 0.030, ...
        55.8, 48.3, 68.1, 19.8, 1.6, 92.4, 1.02, -73.6, 0.58, 56.1}
];
end

function value = prototypeBoundaries()
value = [ ...
    "Supported: the DeepSqueak Excel call-statistics export for the tracked v3.2 output mapping profile."; ...
    "Not supported: arbitrary workbook shapes or every DeepSqueak version."; ...
    "Not supported: native .mat parsing, classifier and clustering workflows."; ...
    "Not supported: MUPET import or any cross-extractor matching or consensus."; ...
    "Accepted state and labels are extractor evidence, not biological truth."];
end

% -------------------------------------------------------- read-back rows ---

function rows = recordingContextRows(conn, recordingId)
rows = fetch(conn, ...
    "SELECT project_key, entity_type, IFNULL(canonical_role,'') AS canonical_role, " + ...
    "entity_native_id, link_type, " + ...
    "CASE WHEN role_label IS NULL OR role_label = '' THEN '-' ELSE role_label END AS role_label " + ...
    "FROM v_recording_entity_context WHERE recording_id = " + ...
    string(recordingId) + " ORDER BY entity_type, entity_native_id, link_type");
end

function rows = extractionRunRows(conn)
rows = fetch(conn, ...
    "SELECT er.run_key, sf.filename AS recording_source, e.extractor_name, " + ...
    "ev.version_label AS extractor_version, " + ...
    "ocp.profile_key AS output_mapping_profile, " + ...
    "ocv.version_label AS profile_version, " + ...
    "substr(ocv.checksum_sha256, 1, 12) AS profile_checksum, " + ...
    "IFNULL(scp.profile_key, '<not recoverable>') AS settings_profile " + ...
    "FROM extraction_runs er " + ...
    "JOIN extraction_run_inputs eri ON eri.extraction_run_id = er.extraction_run_id " + ...
    "JOIN recordings r ON r.recording_id = eri.recording_id " + ...
    "JOIN source_files sf ON sf.source_file_id = r.source_file_id " + ...
    "JOIN extractor_versions ev ON ev.extractor_version_id = er.extractor_version_id " + ...
    "JOIN extractors e ON e.extractor_id = ev.extractor_id " + ...
    "JOIN config_profile_versions ocv ON ocv.profile_version_id = er.output_mapping_profile_version_id " + ...
    "JOIN config_profiles ocp ON ocp.profile_id = ocv.profile_id " + ...
    "LEFT JOIN config_profile_versions scv ON scv.profile_version_id = er.settings_profile_version_id " + ...
    "LEFT JOIN config_profiles scp ON scp.profile_id = scv.profile_id " + ...
    "ORDER BY er.run_key");
end

function rows = artifactRows(conn)
rows = fetch(conn, ...
    "SELECT ra.artifact_role, a.artifact_type, a.path_or_uri, " + ...
    "IFNULL(a.file_format,'') AS file_format, " + ...
    "substr(IFNULL(a.checksum_sha256,''), 1, 12) AS checksum " + ...
    "FROM extraction_run_artifacts ra " + ...
    "JOIN artifacts a ON a.artifact_id = ra.artifact_id " + ...
    "ORDER BY ra.artifact_role");
end

function rows = detectionRows(conn)
rows = fetch(conn, ...
    "SELECT c.native_event_id, c.start_time_s, c.end_time_s, c.duration_s, " + ...
    "c.detection_score, ce.status_after AS review_state, " + ...
    "cc.native_class_label AS native_label " + ...
    "FROM v_detection_core c " + ...
    "JOIN detections d ON d.detection_id = c.detection_id " + ...
    "LEFT JOIN curation_events ce ON ce.detection_id = d.detection_id " + ...
    "LEFT JOIN classification_assignments ca ON ca.detection_id = d.detection_id " + ...
    "LEFT JOIN classification_classes cc " + ...
    "ON cc.classification_class_id = ca.classification_class_id " + ...
    "ORDER BY CAST(c.native_event_id AS INTEGER)");
end

function rows = measurementRows(conn)
% A representative subset rather than every column: one identity transform, two
% unit transforms, and the explicitly missing optional measurement.
% Missing values are rendered as missing. Substituting a numeric zero here would
% display exactly the fabricated value the storage contract exists to prevent.
rows = fetch(conn, ...
    "SELECT d.native_event_id, xf.native_name, em.native_value_type, " + ...
    "CASE WHEN em.native_value_real IS NULL THEN '<missing>' " + ...
    "ELSE CAST(em.native_value_real AS TEXT) END AS native_value, " + ...
    "IFNULL(em.native_unit,'') AS native_unit, " + ...
    "IFNULL(cf.canonical_name,'') AS canonical_feature, " + ...
    "CASE WHEN em.canonical_value_real IS NULL THEN '<missing>' " + ...
    "ELSE CAST(em.canonical_value_real AS TEXT) END AS canonical_value, " + ...
    "IFNULL(em.canonical_unit,'') AS canonical_unit, " + ...
    "IFNULL(em.transform_key,'') AS transform_key, " + ...
    "IFNULL(xf.derivation_stage,'') AS derivation_stage " + ...
    "FROM event_measurements em " + ...
    "JOIN detections d ON d.detection_id = em.detection_id " + ...
    "JOIN extractor_features xf ON xf.extractor_feature_id = em.extractor_feature_id " + ...
    "LEFT JOIN canonical_features cf ON cf.canonical_feature_id = em.canonical_feature_id " + ...
    "WHERE xf.native_name IN ('Begin Time (s)', 'Principle Frequency (kHz)', " + ...
    "'Slope (kHz/s)', 'Tonality') " + ...
    "AND d.native_event_id IN ('1', '2') " + ...
    "ORDER BY CAST(d.native_event_id AS INTEGER), xf.native_name");
end

function rows = reviewLabelRows(conn)
rows = fetch(conn, ...
    "SELECT d.native_event_id, ce.action_type, ce.status_after, ce.actor_type, " + ...
    "cr.method AS classification_method, cc.native_class_label, " + ...
    "IFNULL(cc.canonical_class_label, '<no canonical interpretation>') AS canonical_class " + ...
    "FROM detections d " + ...
    "JOIN curation_events ce ON ce.detection_id = d.detection_id " + ...
    "LEFT JOIN classification_assignments ca ON ca.detection_id = d.detection_id " + ...
    "LEFT JOIN classification_runs cr ON cr.classification_run_id = ca.classification_run_id " + ...
    "LEFT JOIN classification_classes cc " + ...
    "ON cc.classification_class_id = ca.classification_class_id " + ...
    "ORDER BY CAST(d.native_event_id AS INTEGER)");
end

function value = scientificInventory(conn)
tables = ["extraction_runs", "extraction_run_inputs", "extraction_run_artifacts", ...
    "artifacts", "detections", "event_measurements", "curation_events", ...
    "classification_runs", "classification_classes", "classification_assignments"];
value = struct();
for name = tables
    value.(name) = scalar(conn, "SELECT COUNT(*) AS n FROM " + name);
end
end

% -------------------------------------------------------------- plumbing ---

function value = scalar(conn, sql)
rows = fetch(conn, sql);
value = double(rows.n(1));
end

function value = scalarText(conn, sql)
rows = fetch(conn, sql);
value = string(rows{1, 1});
end

function printDemonstration(value)
disp("VAWLUME DEEPSQUEAK IMPORT DEMONSTRATION")
disp(strjoin(value.architecture, " -> "))
fprintf("\nProject intake: %s (project %d, recording %d), preview %s\n", ...
    value.project_intake.status, value.project_intake.project_id, ...
    value.project_intake.recording_id, value.project_intake.preview_verdict);
disp("Recording context:")
disp(value.recording_context)
fprintf("Import: IR valid %d over %d source rows; plan %s with %d conflict(s); " + ...
    "apply %s; settings %s; model %s\n", ...
    value.import_summary.ir_valid, value.import_summary.ir_source_rows, ...
    value.import_summary.plan_status, value.import_summary.plan_conflicts, ...
    value.import_summary.apply_status, value.import_summary.settings_status, ...
    value.import_summary.model_status);
disp("Extraction-run provenance:")
disp(value.extraction_run_provenance)
disp("Artifact provenance:")
disp(value.artifact_provenance)
disp("Detections:")
disp(value.detections)
disp("Selected measurements (native evidence beside canonical form):")
disp(value.measurements)
disp("Review and label evidence:")
disp(value.review_and_labels)
fprintf("Rerun: %d created, %d reused detections; scientific rows unchanged: %d\n", ...
    value.rerun.detections_created, value.rerun.detections_reused, ...
    value.rerun.scientific_rows_unchanged);
fprintf("Relocation: run %s, artifact %s, stored portable path %s; unchanged: %d\n", ...
    value.relocation.extraction_run_action, value.relocation.artifact_action, ...
    value.relocation.stored_portable_path, ...
    value.relocation.scientific_rows_unchanged);
fprintf("Foreign-key violations: %d; temporary artifacts removed: %d\n", ...
    height(value.foreign_key_violations), value.temporary_artifacts_removed);
disp("Scope:")
disp(value.boundaries)
end

function makeParentFolder(path)
parent = fileparts(path);
if ~isfolder(parent)
    mkdir(parent);
end
end

function writeText(path, text)
makeParentFolder(path);
fileId = fopen(path, "w");
if fileId < 0
    error("vawlume:examples:FileWriteFailed", ...
        "Could not open %s for writing.", path);
end
cleaner = onCleanup(@() fclose(fileId));
fprintf(fileId, "%s", text);
delete(cleaner);
end

function root = normalizedRepoRoot(root)
if strlength(root) > 0
    root = string(root);
    return
end
root = string(fileparts(fileparts(mfilename("fullpath"))));
end

function value = pathContains(target)
value = any(strcmp(strsplit(string(path), pathsep), target));
end

function restoreSourcePath(sourcePath, shouldRemove)
if shouldRemove && pathContains(sourcePath)
    rmpath(sourcePath);
end
end

function closeConnection(conn)
try
    close(conn);
catch
end
end

function removeTree(root)
%REMOVETREE Best-effort workspace removal.
%
% This also runs while an exception is unwinding, when the SQLite file may still
% be held briefly. Failing loudly here would bury the real error, so removal is
% retried and then reported through the returned struct rather than thrown.
for attempt = 1:5
    if ~isfolder(root)
        return
    end
    try
        rmdir(root, "s");
        return
    catch
        pause(0.2);
    end
end
end
