function demonstration = matching_consensus_demo(options)
%MATCHING_CONSENSUS_DEMO Demonstrate matching and consilience end to end.
%
% DEMONSTRATION = MATCHING_CONSENSUS_DEMO() creates a disposable project and
% recording through public project intake, imports synthetic DeepSqueak and
% MUPET exports through their public importers, and proceeds through matching,
% ambiguity-preserving groups, consensus, agreement, feature comparison,
% consilience, independent manual QC, and three-configuration sensitivity.
%
% All artifacts and the SQLite database live under the system temporary
% directory and are removed before return. The data and thresholds are
% illustrative prototype fixtures, not empirical performance evidence.
%
% Name-value options:
%   Print     print compact developer-facing read-backs (default true)
%   RepoRoot  repository root, inferred from this file by default

arguments
    options.Print (1,1) logical = true
    options.RepoRoot (1,1) string = ""
end

repoRoot = normalizedRepoRoot(options.RepoRoot);
sourcePath = fullfile(repoRoot, "src");
removeSourcePath = ~pathContains(sourcePath);
if removeSourcePath, addpath(sourcePath); end
cleanupPath = onCleanup(@() restoreSourcePath(sourcePath, removeSourcePath));

workspaceRoot = fullfile(tempdir, ...
    "VAWLUME matching consensus demo " + string(java.util.UUID.randomUUID));
mkdir(workspaceRoot);
cleanupWorkspace = onCleanup(@() removeTree(workspaceRoot));
databasePath = fullfile(workspaceRoot, "matching_consensus_demo.sqlite");
conn = sqlite(char(databasePath), "create");
cleanupConnection = onCleanup(@() closeConnection(conn));

vawlume.db.applySchema(conn, fullfile(repoRoot, "schema", "schema.sql"));
vawlume.db.registerBuiltinSemantics(conn, repoRoot);

% Establish the recording through the real source-mapping/intake path.
[project, recordingRef] = establishProject(conn, workspaceRoot, repoRoot);

% Create and import both extractor outputs. These files are purpose-built
% demonstration inputs; no private recording or extractor artifact is used.
[deepSqueak, mupet] = importExtractors( ...
    conn, workspaceRoot, repoRoot, recordingRef);
preMatching = derivedInventory(conn);
upstreamBefore = upstreamFingerprint(conn);

% Reviewer-authored fixture input is deliberately independent of extractor
% curation. There is not yet a reviewer-file ingest API, so this reproducible
% example authors the four reference rows explicitly rather than asking the
% developer to edit the disposable database by hand.
authorReferenceEvents(conn, project.recording_id);

profilePath = fullfile(repoRoot, "config", "05_matching_profiles", ...
    "prototype_matching_consilience_spec.json");
runPair = struct(run_a="demo-ds", run_b="demo-mupet");
matchingContext = struct(run_key="demo-match-illustrative", ...
    profile_path=profilePath, run_label="Illustrative matching configuration");

candidatePlan = vawlume.matching.compare(conn, recordingRef, runPair, ...
    matchingContext, RepoRoot=repoRoot);
illustrative = vawlume.matching.compare(conn, recordingRef, runPair, ...
    matchingContext, RepoRoot=repoRoot, Apply=true);
assert(illustrative.committed, "Illustrative matching did not commit.");
authorAdjudications(conn, illustrative.analysis.analysis_run_id);

candidateEvidence = compactCandidates(conn, illustrative);
groupReadback = compactGroups(conn, illustrative);
consensusReadback = compactConsensus(conn, illustrative);

% An unchanged apply must reuse every derived identity and add no row.
beforeRerun = derivedInventory(conn);
groupIdsBefore = sort(illustrative.groups.match_group_id);
rerun = vawlume.matching.compare(conn, recordingRef, runPair, ...
    matchingContext, RepoRoot=repoRoot, Apply=true);
afterRerun = derivedInventory(conn);
rerunReadback = struct(status=rerun.status, ...
    analysis_id_stable=rerun.analysis.analysis_run_id == ...
        illustrative.analysis.analysis_run_id, ...
    group_ids_stable=isequal(groupIdsBefore, sort(rerun.groups.match_group_id)), ...
    scientific_rows_unchanged=isequal(beforeRerun, afterRerun), ...
    applied_counts=rerun.applied_counts);

% Agreement/consilience aggregates and assessments persist under their child
% analysis in one transaction. Per-pair feature rows remain reproducible output.
agreement = vawlume.consilience.summarize(conn, ...
    struct(run_key="demo-match-illustrative"), RepoRoot=repoRoot, Apply=true);

% Sensitivity configurations vary only the illustrative temporal-IoU threshold.
strictPath = writeSpecVariant(profilePath, workspaceRoot, "strict", 0.50);
permissivePath = writeSpecVariant(profilePath, workspaceRoot, "permissive", 0.05);
strict = applyMatching(conn, recordingRef, runPair, repoRoot, ...
    "demo-match-strict", strictPath);
permissive = applyMatching(conn, recordingRef, runPair, repoRoot, ...
    "demo-match-permissive", permissivePath);
sensitivity = vawlume.consilience.sensitivity(conn, ...
    ["demo-match-strict", "demo-match-illustrative", ...
    "demo-match-permissive"], RepoRoot=repoRoot);

specificationDocument = jsondecode(fileread(profilePath));
matchingSpec = specificationReadback( ...
    illustrative, agreement, specificationDocument);
centralFrequency = centralFrequencyReadback(agreement);
ineligibleFeatures = ineligibleFeatureReadback(agreement);
provenance = provenanceReadback(conn, agreement, centralFrequency, ...
    project.recording_id);
inventory = databaseInventory(conn);
foreignKeyViolations = fetch(conn, "PRAGMA foreign_key_check");
upstreamAfter = upstreamFingerprint(conn);

demonstration = struct( ...
    architecture=["public project intake"; "public DeepSqueak import"; ...
        "public MUPET import"; "candidate plan"; ...
        "candidate/group/consensus apply"; "agreement and feature comparison"; ...
        "consilience plus independent manual QC"; ...
        "three-configuration threshold sensitivity"; ...
        "relational provenance read-back"], ...
    calibration_boundary="Illustrative synthetic prototype settings; not " + ...
        "empirically calibrated or validated performance.", ...
    project=project, deep_squeak=deepSqueak, mupet=mupet, ...
    pre_matching_inventory=preMatching, ...
    matching_spec=matchingSpec, candidate_plan=candidatePlan, ...
    candidate_evidence=candidateEvidence, match_groups=groupReadback, ...
    consensus_events=consensusReadback, ...
    detection_agreement=agreement.detection_agreement, ...
    detection_denominators=agreement.detection_denominators, ...
    topology=agreement.topology, temporal_agreement=agreement.temporal_agreement, ...
    feature_pairs=agreement.feature_pairs, ...
    central_frequency=centralFrequency, ...
    ineligible_features=ineligibleFeatures, ...
    feature_agreement=struct(comparisons=agreement.feature_comparisons, ...
        summary=agreement.feature_summary, ...
        excluded_groups=agreement.excluded_groups), ...
    consilience=struct(assessments=agreement.consilience, ...
        status_counts=agreement.consilience_status_counts, ...
        precedence=agreement.consilience_precedence), ...
    manual_qc=agreement.manual_qc, sensitivity=sensitivity, ...
    rerun=rerunReadback, ...
    coexisting_matching_analyses=struct( ...
        illustrative_analysis_id=illustrative.analysis.analysis_run_id, ...
        strict_analysis_id=strict.analysis.analysis_run_id, ...
        permissive_analysis_id=permissive.analysis.analysis_run_id, ...
        distinct_analysis_ids=numel(unique([illustrative.analysis.analysis_run_id, ...
        strict.analysis.analysis_run_id, permissive.analysis.analysis_run_id])) == 3), ...
    provenance=provenance, database_inventory=inventory, ...
    native_detections_unchanged=isequal(upstreamBefore, upstreamAfter), ...
    foreign_key_check=foreignKeyViolations, workspace_root=workspaceRoot, ...
    database_path=databasePath, temporary_artifacts_removed=false);

close(conn);
clear cleanupConnection
removeTree(workspaceRoot);
clear cleanupWorkspace
demonstration.temporary_artifacts_removed = ...
    ~isfolder(workspaceRoot) && ~isfile(databasePath);

if options.Print, printDemonstration(demonstration); end
clear cleanupPath
end

% -------------------------------------------------------------- workflow ---

function [project, recordingRef] = establishProject(conn, workspaceRoot, repoRoot)
profilePath = fullfile(repoRoot, "config", "01_mapping_profiles", ...
    "project_inputs", "project_input_source_mapping_examples.json");
sourceRoot = fullfile(workspaceRoot, "project");
audioPath = fullfile(sourceRoot, "control", "mouse_001", "baseline", ...
    "001_baseline_1.wav");
writeText(audioPath, "synthetic audio stand-in; no recorded sound is involved");
ir = vawlume.source_mapping.parse(profilePath, sourceRoot, ...
    ProfileId="example.project.mouse_courtship.folder_driven", RepoRoot=repoRoot);
preview = vawlume.source_mapping.preview(ir);
intake = vawlume.ingest.project(conn, ir, struct( ...
    project_key="demo_matching_consensus", ...
    project_name="Matching and consensus demonstration", ...
    description="Disposable Phase 6 end-to-end demonstration."), ...
    Apply=true, ProfileLinkagePath=fullfile(repoRoot, "config", ...
    "04_examples", "profile_linkage_example.json"), RepoRoot=repoRoot);
recording = fetch(conn, "SELECT r.recording_id, p.project_id, p.project_key, " + ...
    "IFNULL(r.native_recording_id,'') AS native_recording_id, " + ...
    "sf.relative_path FROM recordings r JOIN projects p ON p.project_id=r.project_id " + ...
    "JOIN source_files sf ON sf.source_file_id=r.source_file_id");
recordingId = double(recording.recording_id(1));
recordingRef = struct(recording_id=recordingId);
project = struct(status=intake.status, committed=intake.committed, ...
    project_id=double(recording.project_id(1)), ...
    project_key=string(recording.project_key(1)), recording_id=recordingId, ...
    native_recording_id=string(recording.native_recording_id(1)), ...
    source_relative_path=string(recording.relative_path(1)), ...
    preview_verdict=preview.verdict, ...
    context=recordingContext(conn, recordingId));
end

function [deepSqueak, mupet] = importExtractors( ...
        conn, workspaceRoot, repoRoot, recordingRef)
dsRoot = fullfile(workspaceRoot, "deepsqueak");
dsPath = fullfile(dsRoot, "exports", "REC_A_Stats.xlsx");
writeCells(dsPath, deepSqueakCells());
dsPlan = vawlume.ingest.deepsqueak(conn, dsPath, recordingRef, ...
    struct(run_key="demo-ds", extractor_version="3.2.1"), ...
    RepoRoot=repoRoot, ArtifactRoot=dsRoot);
dsResult = vawlume.ingest.deepsqueak(conn, dsPath, recordingRef, ...
    struct(run_key="demo-ds", extractor_version="3.2.1"), ...
    RepoRoot=repoRoot, ArtifactRoot=dsRoot, Apply=true);

mupetRoot = fullfile(workspaceRoot, "mupet");
mupetPath = fullfile(mupetRoot, "CSV", "REC_A.csv");
configPath = fullfile(mupetRoot, "config.csv");
writeCells(mupetPath, mupetCells());
writeText(configPath, strjoin(mupetConfigLines(), newline) + newline);
mupetPlan = vawlume.ingest.mupet(conn, mupetPath, recordingRef, ...
    struct(run_key="demo-mupet", extractor_version="2.1", ...
    settings=struct(config_path=configPath)), ...
    RepoRoot=repoRoot, ArtifactRoot=mupetRoot);
mupetResult = vawlume.ingest.mupet(conn, mupetPath, recordingRef, ...
    struct(run_key="demo-mupet", extractor_version="2.1", ...
    settings=struct(config_path=configPath)), ...
    RepoRoot=repoRoot, ArtifactRoot=mupetRoot, Apply=true);

deepSqueak = struct(plan_status=dsPlan.status, import_status=dsResult.status, ...
    committed=dsResult.committed, extraction_run_id= ...
    dsResult.extraction_run.extraction_run_id, ...
    detection_count=dsResult.detections.planned, ...
    artifact_count=height(dsResult.artifacts));
mupet = struct(plan_status=mupetPlan.status, import_status=mupetResult.status, ...
    committed=mupetResult.committed, extraction_run_id= ...
    mupetResult.extraction_run.extraction_run_id, ...
    detection_count=mupetResult.detections.planned, ...
    artifact_count=height(mupetResult.artifacts), ...
    curation_rows_expected=mupetResult.detections.curation_rows_expected, ...
    classification_rows_expected= ...
    mupetResult.detections.classification_rows_expected);
end

function result = applyMatching(conn, recordingRef, runPair, repoRoot, runKey, path)
result = vawlume.matching.compare(conn, recordingRef, runPair, ...
    struct(run_key=runKey, profile_path=path), RepoRoot=repoRoot, Apply=true);
assert(result.committed, "Matching '%s' did not commit: %s", runKey, result.status);
end

% ------------------------------------------------------------ read-backs ---

function value = compactCandidates(conn, result)
n = height(result.candidates);
value = table(strings(n, 1), strings(n, 1), zeros(n, 1), zeros(n, 1), ...
    zeros(n, 1), zeros(n, 1), false(n, 1), ...
    VariableNames=["deep_squeak_native_id", "mupet_native_id", ...
    "temporal_iou", "onset_delta_s", "offset_delta_s", ...
    "duration_delta_s", "eligible"]);
for index = 1:n
    row = result.candidates(index, :);
    value.deep_squeak_native_id(index) = nativeId(conn, row.run_a_detection_id);
    value.mupet_native_id(index) = nativeId(conn, row.run_b_detection_id);
    value.temporal_iou(index) = row.temporal_iou;
    value.onset_delta_s(index) = row.onset_difference_s;
    value.offset_delta_s(index) = row.offset_difference_s;
    value.duration_delta_s(index) = row.duration_difference_s;
    value.eligible(index) = row.candidate_status == "eligible";
end
end

function value = compactGroups(conn, result)
n = height(result.groups);
value = table(zeros(n, 1), strings(n, 1), zeros(n, 1), zeros(n, 1), ...
    strings(n, 1), strings(n, 1), strings(n, 1), zeros(n, 1), ...
    zeros(n, 1), strings(n, 1), ...
    VariableNames=["group_id", "topology", "deep_squeak_member_count", ...
    "mupet_member_count", "deep_squeak_native_ids", "mupet_native_ids", ...
    "consensus_status", "consensus_start_s", "consensus_end_s", ...
    "consensus_method"]);
value.consensus_start_s(:) = NaN;
value.consensus_end_s(:) = NaN;
for index = 1:n
    group = result.groups(index, :);
    members = result.group_members( ...
        result.group_members.component_ordinal == group.component_ordinal, :);
    value.group_id(index) = group.match_group_id;
    value.topology(index) = group.match_type;
    value.deep_squeak_member_count(index) = group.run_a_member_count;
    value.mupet_member_count(index) = group.run_b_member_count;
    value.deep_squeak_native_ids(index) = joinNativeIds(conn, ...
        members.detection_id(members.member_role == "run_a"));
    value.mupet_native_ids(index) = joinNativeIds(conn, ...
        members.detection_id(members.member_role == "run_b"));
    selected = result.consensus_events.component_ordinal == group.component_ordinal;
    if any(selected)
        event = result.consensus_events(find(selected, 1), :);
        value.consensus_status(index) = event.consensus_status;
        value.consensus_start_s(index) = event.start_time_s;
        value.consensus_end_s(index) = event.end_time_s;
        value.consensus_method(index) = event.derivation_method;
    else
        value.consensus_status(index) = "not_emitted";
        value.consensus_method(index) = "not_applicable";
    end
end
end

function value = compactConsensus(conn, result)
n = height(result.consensus_events);
value = table(zeros(n, 1), zeros(n, 1), strings(n, 1), zeros(n, 1), ...
    zeros(n, 1), strings(n, 1), strings(n, 1), ...
    VariableNames=["consensus_event_id", "group_id", "topology", ...
    "start_time_s", "end_time_s", "derivation_method", "member_native_ids"]);
for index = 1:n
    event = result.consensus_events(index, :);
    value.consensus_event_id(index) = event.consensus_event_id;
    value.group_id(index) = event.match_group_id;
    value.topology(index) = result.groups.match_type( ...
        result.groups.component_ordinal == event.component_ordinal);
    value.start_time_s(index) = event.start_time_s;
    value.end_time_s(index) = event.end_time_s;
    value.derivation_method(index) = event.derivation_method;
    members = result.consensus_event_members( ...
        result.consensus_event_members.consensus_ordinal == ...
        event.consensus_ordinal, :);
    value.member_native_ids(index) = joinNativeIds(conn, members.detection_id);
end
end

function value = specificationReadback(matching, agreement, document)
value = struct(analysis_key=matching.analysis.run_key, ...
    profile_id=matching.configuration.profile_key, ...
    profile_version=matching.configuration.version_label, ...
    checksum_sha256=matching.configuration.checksum_sha256, ...
    matching_algorithm=matching.algorithm, agreement_algorithm=agreement.algorithm, ...
    min_temporal_iou=matching.min_temporal_iou, ...
    assignment_model=string(document.assignment.model), ...
    one_to_one_consensus_method=string( ...
    document.consensus.by_topology.one_to_one.derivation_method), ...
    ambiguous_consensus_method=string( ...
    document.consensus.by_topology.one_to_many.derivation_method), ...
    minimum_supporting_comparisons= ...
    agreement.specification.minimum_supporting_comparisons, ...
    missing_feature_policy=agreement.specification.missing_feature_policy, ...
    calibration_status=string(document.calibration_status.state));
end

function value = centralFrequencyReadback(report)
selected = string(report.feature_pairs.equivalence_class) == ...
    "vocalization_frequency_center";
pair = report.feature_pairs(selected, :);
comparison = report.feature_comparisons( ...
    string(report.feature_comparisons.equivalence_class) == ...
    "vocalization_frequency_center", :);
value = struct(deep_squeak_canonical_name= ...
    string(pair.feature_a_canonical_name(1)), ...
    mupet_canonical_name=string(pair.feature_b_canonical_name(1)), ...
    shared_equivalence_class=string(pair.equivalence_class(1)), ...
    relationship_type=string(pair.relationship_type(1)), ...
    consilience_eligible=logical(pair.consilience_eligible(1)), ...
    deep_squeak_method=string(pair.feature_a_derivation_stage(1)), ...
    mupet_method=string(pair.feature_b_derivation_stage(1)), ...
    comparison=comparison);
end

function value = ineligibleFeatureReadback(report)
pairs = report.feature_pairs(~report.feature_pairs.consilience_eligible, :);
value = pairs(:, ["feature_a_canonical_name", "feature_b_canonical_name", ...
    "relationship_type", "consilience_eligible", "unit_status"]);
value.not_scored = true(height(value), 1);
end

function value = provenanceReadback(conn, report, centralFrequency, recordingId)
assessment = report.consilience( ...
    report.consilience.automated_status == "matched_feature_supported", :);
groupId = assessment.match_group_id(1);
members = fetch(conn, "SELECT ca.status AS automated_status, " + ...
    "agreement.run_key AS agreement_run_key, matching.run_key AS matching_run_key, " + ...
    "cp.profile_key AS matching_profile_key, cpv.version_label, cpv.checksum_sha256, " + ...
    "mg.match_group_id, mg.match_type, mgm.member_role, d.detection_id, " + ...
    "d.native_event_id, er.run_key AS extraction_run_key, e.extractor_name, " + ...
    "r.recording_id, sf.relative_path AS recording_source, p.project_key " + ...
    "FROM consilience_assessments ca " + ...
    "JOIN analysis_runs agreement ON agreement.analysis_run_id=ca.analysis_run_id " + ...
    "JOIN analysis_runs matching ON matching.analysis_run_id=agreement.parent_analysis_run_id " + ...
    "JOIN analysis_run_profiles arp ON arp.analysis_run_id=matching.analysis_run_id " + ...
    "JOIN config_profile_versions cpv ON cpv.profile_version_id=arp.profile_version_id " + ...
    "JOIN config_profiles cp ON cp.profile_id=cpv.profile_id " + ...
    "JOIN match_groups mg ON mg.match_group_id=ca.match_group_id " + ...
    "JOIN match_group_members mgm ON mgm.match_group_id=mg.match_group_id " + ...
    "JOIN detections d ON d.detection_id=mgm.detection_id " + ...
    "JOIN extraction_runs er ON er.extraction_run_id=d.extraction_run_id " + ...
    "JOIN extractor_versions ev ON ev.extractor_version_id=er.extractor_version_id " + ...
    "JOIN extractors e ON e.extractor_id=ev.extractor_id " + ...
    "JOIN recordings r ON r.recording_id=d.recording_id " + ...
    "JOIN source_files sf ON sf.source_file_id=r.source_file_id " + ...
    "JOIN projects p ON p.project_id=r.project_id WHERE ca.match_group_id=" + ...
    string(groupId) + " ORDER BY mgm.member_role");
candidate = fetch(conn, "SELECT cp.temporal_iou,cp.onset_difference_s," + ...
    "cp.offset_difference_s,cp.duration_difference_s FROM candidate_pairs cp " + ...
    "JOIN match_group_members a ON a.detection_id=cp.detection_a_id " + ...
    "JOIN match_group_members b ON b.detection_id=cp.detection_b_id " + ...
    "WHERE a.match_group_id=" + string(groupId) + ...
    " AND b.match_group_id=a.match_group_id AND cp.analysis_run_id=" + ...
    "(SELECT analysis_run_id FROM match_groups WHERE match_group_id=" + ...
    string(groupId) + ")");
artifacts = fetch(conn, "SELECT er.run_key,e.extractor_name,era.artifact_role," + ...
    "a.artifact_type,a.path_or_uri,IFNULL(a.checksum_sha256,'') AS checksum_sha256 " + ...
    "FROM extraction_run_artifacts era " + ...
    "JOIN extraction_runs er ON er.extraction_run_id=era.extraction_run_id " + ...
    "JOIN extractor_versions ev ON ev.extractor_version_id=er.extractor_version_id " + ...
    "JOIN extractors e ON e.extractor_id=ev.extractor_id " + ...
    "JOIN artifacts a ON a.artifact_id=era.artifact_id " + ...
    "WHERE er.run_key IN ('demo-ds','demo-mupet') ORDER BY er.run_key,era.artifact_role");
value = struct(assessment_members=members, candidate_evidence=candidate, ...
    run_artifacts=artifacts, project_context=recordingContext(conn, recordingId), ...
    feature_relationship=centralFrequency);
end

function value = recordingContext(conn, recordingId)
value = fetch(conn, "SELECT p.project_key,r.recording_id,sf.relative_path," + ...
    "et.native_name AS entity_type,ee.native_id AS entity_native_id," + ...
    "rel.link_type,IFNULL(rel.role_label,'') AS role_label " + ...
    "FROM recordings r JOIN projects p ON p.project_id=r.project_id " + ...
    "JOIN source_files sf ON sf.source_file_id=r.source_file_id " + ...
    "JOIN recording_entity_links rel ON rel.recording_id=r.recording_id " + ...
    "JOIN experimental_entities ee ON ee.entity_id=rel.entity_id " + ...
    "JOIN entity_types et ON et.entity_type_id=ee.entity_type_id " + ...
    "WHERE r.recording_id=" + string(recordingId) + ...
    " ORDER BY rel.link_type,ee.native_id");
end

% --------------------------------------------------------- reviewer input ---

function authorReferenceEvents(conn, recordingId)
events = {"r1", 10.002, 10.051; "r2", 20.001, 20.041; ...
    "r3", 40.001, 40.099; "r4", 60.000, 60.050};
for index = 1:size(events, 1)
    execute(conn, "INSERT INTO manual_reference_events(recording_id," + ...
        "reference_set_key,native_reference_id,reviewer_label," + ...
        "start_time_s,end_time_s) VALUES(" + string(recordingId) + ...
        ",'prototype_manual_reference_v1','" + events{index, 1} + ...
        "','synthetic_reviewer'," + string(events{index, 2}) + ...
        "," + string(events{index, 3}) + ")");
end
end

function authorAdjudications(conn, analysisId)
supported = fetch(conn, "SELECT mg.match_group_id FROM match_groups mg " + ...
    "JOIN match_group_members mgm ON mgm.match_group_id=mg.match_group_id " + ...
    "JOIN detections d ON d.detection_id=mgm.detection_id " + ...
    "WHERE mg.analysis_run_id=" + string(analysisId) + ...
    " AND mg.match_type='one_to_one' AND mgm.member_role='run_a' " + ...
    "AND d.native_event_id='1'");
single = fetch(conn, "SELECT mg.match_group_id FROM match_groups mg " + ...
    "JOIN match_group_members mgm ON mgm.match_group_id=mg.match_group_id " + ...
    "JOIN detections d ON d.detection_id=mgm.detection_id " + ...
    "WHERE mg.analysis_run_id=" + string(analysisId) + ...
    " AND mg.match_type='unmatched' AND mgm.member_role='run_a' " + ...
    "AND d.native_event_id='3'");
execute(conn, "INSERT INTO manual_reviews(analysis_run_id,match_group_id," + ...
    "reviewer_label,review_status) VALUES(" + string(analysisId) + "," + ...
    string(double(supported.match_group_id(1))) + ...
    ",'synthetic_reviewer','adjudicated_positive')");
execute(conn, "INSERT INTO manual_reviews(analysis_run_id,match_group_id," + ...
    "reviewer_label,review_status) VALUES(" + string(analysisId) + "," + ...
    string(double(single.match_group_id(1))) + ...
    ",'synthetic_reviewer','adjudicated_negative')");
end

% --------------------------------------------------------------- fixtures ---

function cells = deepSqueakCells()
headers = {'File', 'ID', 'Label', 'Accepted', 'Score', 'Begin Time (s)', ...
    'End Time (s)', 'Call Length (s)', 'Principle Frequency (kHz)', ...
    'Low Freq (kHz)', 'High Freq (kHz)', 'Delta Freq (kHz)', ...
    'Frequency Standard Deviation (kHz)', 'Slope (kHz/s)', 'Sinuosity', ...
    'Mean Power (dB/Hz)', 'Tonality', 'Peak Freq (kHz)'};
file = 'synthetic/deepsqueak/REC_A_detections.mat';
cells = [headers
    {file,1,'class_a',1,.9134,10,10.05,.05,62,45,80,35,3.2,-120.5,1.12,-71.4,.78,63}
    {file,2,'class_a',1,.8021,20,20.04,.04,61,50,72,22,2.1,15,1.05,-70.1,.81,61.5}
    {file,3,'class_b',1,.7010,30,30.04,.04,59,48,70,22,2.6,4,1.09,-70.8,.74,59.5}
    {file,4,'class_b',0,.2107,40,40.1,.1,63.5,42,84,42,4.4,-8.25,1.4,-69.3,.69,64.2}];
end

function cells = mupetCells()
headers = {'Syllable number','Syllable start time (sec)', ...
    'Syllable end time (sec)','inter-syllable interval (sec)', ...
    'syllable duration (msec)','starting frequency (kHz)', ...
    'final frequency (kHz)','minimum frequency (kHz)', ...
    'maximum frequency (kHz)','mean frequency (kHz)', ...
    'frequency bandwidth (kHz)','total syllable energy (dB)', ...
    'peak syllable amplitude (dB)'};
cells = [headers
    {1,10.004,10.052,9.950,48,45,62,46,79,63,33,12.5,-18}
    {2,20.002,20.042,9.991,40,46,59,47,77,61.5,30,11.5,-19}
    {3,30.033,30.095,9.907,62,47,61,45,75,60,30,10.5,-20}
    {4,40.002,40.045,.007,43,47,61,42.5,84.5,63,42,10.5,-20}
    {5,40.052,40.098,9.902,46,48,62,43,83,62.5,40,9.5,-21}
    {6,50,50.035,'NA',35,46,60,50.5,72.5,61,22,11,-19}];
end

function lines = mupetConfigLines()
lines = ["noise-reduction,5"; "minimum-syllable-duration,008"; ...
    "maximum-syllable-duration,200"; "minimum-syllable-total-energy,-15"; ...
    "minimum-syllable-peak-amplitude,-25"; "minimum-syllable-distance,5"; ...
    "sample-frequency,250000"; "minimum-usv-frequency,30000"; ...
    "maximum-usv-frequency,120000"; "number-filterbank-filters,64"; ...
    "filterbank-type,1"];
end

function path = writeSpecVariant(basePath, workspaceRoot, name, iou)
text = string(fileread(basePath));
old = string(sprintf('"min_temporal_iou": 0.10\n    }'));
new = string(sprintf('"min_temporal_iou": %g\n    }', iou));
assert(count(text, old) == 1);
text = replace(text, old, new);
text = replace(text, '"vawlume.matching.prototype.v1"', ...
    '"vawlume.matching.prototype.' + name + '"');
path = fullfile(workspaceRoot, "matching_" + name + ".json");
writeText(path, text);
end

% -------------------------------------------------------------- utilities ---

function value = derivedInventory(conn)
names = ["candidate_pairs"; "match_groups"; "match_group_members"; ...
    "consensus_events"; "consensus_event_members"; ...
    "agreement_statistics"; "consilience_assessments"];
counts = zeros(numel(names), 1);
for index = 1:numel(names), counts(index) = countOf(conn, names(index)); end
value = table(names, counts, VariableNames=["table_name", "row_count"]);
end

function value = databaseInventory(conn)
names = ["projects"; "recordings"; "extraction_runs"; "artifacts"; ...
    "detections"; "event_measurements"; "manual_reference_events"; ...
    "manual_reviews"; "analysis_runs"; "candidate_pairs"; "match_groups"; ...
    "consensus_events"; "agreement_statistics"; "consilience_assessments"];
counts = zeros(numel(names), 1);
for index = 1:numel(names), counts(index) = countOf(conn, names(index)); end
value = table(names, counts, VariableNames=["table_name", "row_count"]);
end

function value = upstreamFingerprint(conn)
value = fetch(conn, "SELECT d.detection_id,d.extraction_run_id,d.native_event_id," + ...
    "d.start_time_s,d.end_time_s,COUNT(em.event_measurement_id) AS measurements," + ...
    "IFNULL(SUM(em.canonical_value_real),0) AS canonical_total " + ...
    "FROM detections d LEFT JOIN event_measurements em ON em.detection_id=d.detection_id " + ...
    "GROUP BY d.detection_id ORDER BY d.detection_id");
end

function value = countOf(conn, tableName)
rows = fetch(conn, "SELECT COUNT(*) AS n FROM " + tableName);
value = double(rows.n(1));
end

function value = nativeId(conn, detectionId)
rows = fetch(conn, "SELECT native_event_id FROM detections WHERE detection_id=" + ...
    string(detectionId));
value = string(rows.native_event_id(1));
end

function value = joinNativeIds(conn, detectionIds)
value = "";
if isempty(detectionIds), return, end
items = strings(numel(detectionIds), 1);
for index = 1:numel(detectionIds), items(index) = nativeId(conn, detectionIds(index)); end
value = strjoin(items, ", ");
end

function writeCells(path, cells)
makeParent(path);
if isfile(path), delete(path); end
writecell(cells, path);
end

function writeText(path, value)
makeParent(path);
fileId = fopen(path, "w");
if fileId < 0
    error("vawlume:examples:FixtureCreationFailed", ...
        "Could not create demonstration input: %s", path);
end
cleanupFile = onCleanup(@() fclose(fileId));
fprintf(fileId, "%s", value);
clear cleanupFile
end

function makeParent(path)
parent = fileparts(path);
if ~isfolder(parent), mkdir(parent); end
end

function root = normalizedRepoRoot(root)
if strlength(root) == 0, root = fileparts(fileparts(mfilename("fullpath"))); end
try
    root = string(java.io.File(char(root)).getCanonicalPath());
catch
end
end

function value = pathContains(target)
value = any(split(string(path), pathsep) == string(target));
end

function restoreSourcePath(sourcePath, shouldRemove)
if shouldRemove && pathContains(sourcePath), rmpath(sourcePath); end
end

function closeConnection(conn)
try
    if isopen(conn), close(conn); end
catch
end
end

function removeTree(root)
if isfolder(root), rmdir(root, "s"); end
end

function printDemonstration(value)
disp("VAWLUME MATCHING AND CONSENSUS DEMONSTRATION")
disp(value.calibration_boundary)
fprintf("Project intake: %s; DeepSqueak: %s; MUPET: %s\n", ...
    value.project.status, value.deep_squeak.import_status, ...
    value.mupet.import_status);
disp("Candidate evidence (run B minus run A deltas):")
disp(value.candidate_evidence)
disp("Ambiguity-preserving groups and consensus:")
disp(value.match_groups)
disp("Detection agreement (run-specific denominators):")
disp(value.detection_agreement)
disp("Central frequency through registered equivalence class:")
disp(value.central_frequency)
disp("Related but ineligible power/energy/amplitude pairs (not scored):")
disp(value.ineligible_features)
disp("Consilience status counts:")
disp(value.consilience.status_counts)
disp("Independent manual-QC metrics:")
disp(value.manual_qc.per_run)
disp("Threshold sensitivity (no winner selected):")
disp(value.sensitivity.comparison)
fprintf("Rerun reused identities: %d; native detections unchanged: %d\n", ...
    value.rerun.group_ids_stable, value.native_detections_unchanged);
fprintf("Foreign-key violations: %d; temporary artifacts removed: %d\n", ...
    height(value.foreign_key_check), value.temporary_artifacts_removed);
end
