function demonstration = multi_extractor_agreement_demo(options)
%MULTI_EXTRACTOR_AGREEMENT_DEMO Demonstrate three-extractor agreement end to end.
%
% DEMONSTRATION = MULTI_EXTRACTOR_AGREEMENT_DEMO() runs the complete Phase 1
% arbitrary-N workflow over one synthetic recording:
%
%   1. import DeepSqueak, MUPET, and USVSEG through their public importers;
%   2. run all three pairwise comparisons under one versioned matching
%      specification;
%   3. compose those pairwise analyses into arbitrary-N agreement groups;
%   4. query an exact extractor-pair edge pattern;
%   5. query a coarse K-of-possible support count.
%
% Steps 4 and 5 are the point of the demonstration. They are independent
% dimensions: two components can both support two of three possible extractor
% pairs while supporting *different* pairs, and only the coarse query merges
% them. The exact query keeps them apart.
%
% Pairwise matching remains the primitive. Agreement is derived from compatible
% pairwise analyses and preserves their exact supporting edges; it never
% synthesizes a transitive edge to make a component look complete, never
% collapses a split/merge component into one event, and never invents consensus
% timing.
%
% Every artifact and the SQLite database live under the system temporary
% directory and are removed before return. The detections and every threshold
% they meet are illustrative prototype fixtures. Agreement strength is
% methodological evidence, not a calibrated confidence probability and not a
% biological truth label.
%
% Name-value options:
%   Print     print compact developer-facing read-backs (default true)
%   RepoRoot  repository root, inferred from this file by default
%
% See also VAWLUME.AGREEMENT.COMPOSE, VAWLUME.AGREEMENT.SELECTPOPULATION,
% VAWLUME.MATCHING.COMPARE, USVSEG_IMPORT_DEMO, AGREEMENT_FILTER_DEMO.

arguments
    options.Print (1,1) logical = true
    options.RepoRoot (1,1) string = ""
end

repoRoot = normalizedRepoRoot(options.RepoRoot);
sourcePath = fullfile(repoRoot, "src");
removeSourcePath = ~pathContains(sourcePath);
if removeSourcePath, addpath(sourcePath); end
cleanupPath = onCleanup(@() restoreSourcePath(sourcePath, removeSourcePath));

workspaceRoot = fullfile(tempdir, ...
    "VAWLUME multi extractor agreement demo " + string(java.util.UUID.randomUUID));
mkdir(workspaceRoot);
cleanupWorkspace = onCleanup(@() removeTree(workspaceRoot));
databasePath = fullfile(workspaceRoot, "multi_extractor_agreement_demo.sqlite");
conn = sqlite(char(databasePath), "create");
cleanupConnection = onCleanup(@() closeConnection(conn));

vawlume.db.applySchema(conn, fullfile(repoRoot, "schema", "schema.sql"));
vawlume.db.registerBuiltinSemantics(conn, repoRoot);

% 1. One recording, three extractor runs. Separate extraction runs are never
%    implicitly pooled as though they were one biological event set.
[project, recordingRef] = establishProject(conn, workspaceRoot, repoRoot);
imports = importAllThreeExtractors(conn, workspaceRoot, repoRoot, recordingRef);
upstreamBefore = upstreamFingerprint(conn);

% 2. All three pairwise comparisons. Every source analysis must cite the same
%    versioned matching specification, so a missing supporting edge cannot be
%    confused with a pair that was assessed under different thresholds.
matchSpecPath = fullfile(repoRoot, "config", "05_matching_profiles", ...
    "prototype_matching_consilience_spec.json");
pairwise = runPairwiseComparisons(conn, recordingRef, repoRoot, matchSpecPath);

% 3. Compose the arbitrary-N agreement run from those three analyses. Sources
%    are analyses, not a run signature; order carries no meaning.
agreementSources = ["demo-match-ds-mupet"; "demo-match-ds-usvseg"; ...
    "demo-match-mupet-usvseg"];
composed = vawlume.agreement.compose(conn, recordingRef, agreementSources, ...
    struct(run_key="demo-agreement", ...
    run_label="Synthetic three-extractor agreement"), ...
    RepoRoot=repoRoot, Apply=true);
assert(composed.committed, "Agreement composition did not commit: %s", ...
    composed.status);

agreementRef = struct(project_key=project.project_key, run_key="demo-agreement");
allGroups = vawlume.agreement.selectPopulation(conn, agreementRef);

% 4. Exact edge-pattern queries. Both of these components support exactly two
%    of three possible extractor pairs, and they support different pairs.
chainThroughMupet = vawlume.agreement.selectPopulation(conn, agreementRef, ...
    ExactSupportPattern=chainThroughMupetPattern());
chainThroughUsvseg = vawlume.agreement.selectPopulation(conn, agreementRef, ...
    ExactSupportPattern=chainThroughUsvsegPattern());
completeTriplePattern = vawlume.agreement.selectPopulation(conn, agreementRef, ...
    ExactSupportPattern=allPairPattern());

% 5. Coarse K-of-possible queries. ExactSupportedPairCount=2 deliberately
%    returns both open chains as one population; the exact queries above are
%    the only way to keep their shapes apart.
atLeastTwoPairs = vawlume.agreement.selectPopulation(conn, agreementRef, ...
    MinSupportedPairCount=2);
exactlyTwoPairs = vawlume.agreement.selectPopulation(conn, agreementRef, ...
    ExactSupportedPairCount=2);

% Independent shape dimensions over the same run.
triple = "deepsqueak|mupet|usvseg";
cleanCompleteTriple = vawlume.agreement.selectPopulation(conn, agreementRef, ...
    ExtractorSetKey=triple, Completeness="complete", Cleanliness="clean", ...
    Multiplicity="one_per_extractor");
completeAmbiguous = vawlume.agreement.selectPopulation(conn, agreementRef, ...
    ExtractorSetKey=triple, Completeness="complete", ...
    Multiplicity="multiple_per_extractor");
singleExtractorPairOnly = vawlume.agreement.selectPopulation(conn, ...
    agreementRef, ExactPossiblePairCount=1);
extractorUnique = vawlume.agreement.selectPopulation(conn, agreementRef, ...
    Uniqueness="extractor_unique");

populations = struct( ...
    all_groups=allGroups, ...
    exact_all_three_pairs=completeTriplePattern, ...
    exact_chain_through_mupet=chainThroughMupet, ...
    exact_chain_through_usvseg=chainThroughUsvseg, ...
    coarse_at_least_two_pairs=atLeastTwoPairs, ...
    coarse_exactly_two_pairs=exactlyTwoPairs, ...
    clean_complete_triple=cleanCompleteTriple, ...
    complete_ambiguous=completeAmbiguous, ...
    two_extractor_pair_only=singleExtractorPairOnly, ...
    extractor_unique=extractorUnique);

% The exact-versus-coarse claim, stated as a check rather than as prose only.
exactVersusCoarse = struct( ...
    coarse_group_count=exactlyTwoPairs.selected_group_count, ...
    exact_pattern_group_counts=[chainThroughMupet.selected_group_count; ...
        chainThroughUsvseg.selected_group_count], ...
    exact_patterns=[chainThroughMupetPattern(); chainThroughUsvsegPattern()], ...
    exact_patterns_are_disjoint=isempty(intersect( ...
        chainThroughMupet.agreement_group_ids, ...
        chainThroughUsvseg.agreement_group_ids)), ...
    exact_partition_recovers_coarse= ...
        chainThroughMupet.selected_group_count + ...
        chainThroughUsvseg.selected_group_count == ...
        exactlyTwoPairs.selected_group_count);

demonstration = struct( ...
    architecture=["public project intake"; "DeepSqueak import"; ...
        "MUPET import"; "USVSEG import"; "three pairwise matching analyses"; ...
        "arbitrary-N agreement composition"; "exact edge-pattern query"; ...
        "coarse K-of-possible query"], ...
    calibration_boundary="Illustrative synthetic prototype settings. " + ...
        "Agreement strength is methodological evidence, not a calibrated " + ...
        "confidence probability or a biological truth label.", ...
    project=project, imports=imports, pairwise=pairwise, ...
    agreement=struct(run_key=composed.analysis.run_key, ...
        analysis_run_id=composed.analysis.analysis_run_id, ...
        status=composed.status, source_analysis_count=numel(agreementSources), ...
        group_count=allGroups.selected_group_count, ...
        native_member_count=allGroups.selected_member_count), ...
    populations=populations, ...
    population_summary=populationSummary(populations), ...
    group_shapes=groupShapes(allGroups), ...
    exact_versus_coarse=exactVersusCoarse, ...
    denominator_note="Group counts and native-member counts are different " + ...
        "denominators. The split/merge component below is one agreement " + ...
        "group and four native observations; downstream summaries must say " + ...
        "which denominator they used.", ...
    identity=struct( ...
        detections_partitioned=allGroups.selected_member_count == ...
            imports.total_detection_count, ...
        member_detections_unique=numel(unique(allGroups.detection_ids)) == ...
            allGroups.selected_member_count, ...
        native_detections_unchanged=isequal(upstreamBefore, ...
            upstreamFingerprint(conn))), ...
    foreign_key_check=fetch(conn, "PRAGMA foreign_key_check"), ...
    proves=[ ...
        "three extractors reach one relational model and one derived agreement run"; ...
        "arbitrary-N agreement is composed from compatible pairwise analyses, not measured directly"; ...
        "exact extractor-pair patterns stay distinct from coarse K-of-possible counts"; ...
        "split/merge components remain one group with several native observations"; ...
        "an extractor-unique detection survives as a single-member group"], ...
    does_not_prove=[ ...
        "biological truth, caller attribution, or that any extractor is correct"; ...
        "empirical calibration of the matching threshold these edges depend on"; ...
        "that agreement strength is a confidence probability"], ...
    workspace_root=workspaceRoot, database_path=databasePath, ...
    temporary_artifacts_removed=false);

close(conn);
clear cleanupConnection
removeTree(workspaceRoot);
clear cleanupWorkspace
demonstration.temporary_artifacts_removed = ...
    ~isfolder(workspaceRoot) && ~isfile(databasePath);

if options.Print, printDemonstration(demonstration); end
clear cleanupPath
end

% -------------------------------------------------------------- workflow ---

function [project, recordingRef] = establishProject(conn, workspaceRoot, repoRoot)
profilePath = fullfile(repoRoot, "config", "01_mapping_profiles", ...
    "project_inputs", "project_input_source_mapping_examples.json");
sourceRoot = fullfile(workspaceRoot, "project");
audioPath = fullfile(sourceRoot, "control", "mouse_001", "baseline", ...
    "001_baseline_1.wav");
writeText(audioPath, "synthetic audio stand-in; no recorded sound is involved");
ir = vawlume.source_mapping.parse(profilePath, sourceRoot, ...
    ProfileId="example.project.mouse_courtship.folder_driven", RepoRoot=repoRoot);
preview = vawlume.source_mapping.preview(ir);
intake = vawlume.ingest.project(conn, ir, struct( ...
    project_key="demo_multi_extractor_agreement", ...
    project_name="Three-extractor agreement demonstration", ...
    description="Disposable Phase 1 arbitrary-N agreement demonstration."), ...
    Apply=true, RepoRoot=repoRoot);
recording = fetch(conn, "SELECT r.recording_id, p.project_key, " + ...
    "sf.relative_path FROM recordings r " + ...
    "JOIN projects p ON p.project_id=r.project_id " + ...
    "JOIN source_files sf ON sf.source_file_id=r.source_file_id");
recordingId = double(recording.recording_id(1));
recordingRef = struct(recording_id=recordingId);
project = struct(intake_status=intake.status, preview_verdict=preview.verdict, ...
    project_key=string(recording.project_key(1)), recording_id=recordingId, ...
    source_relative_path=string(recording.relative_path(1)));
end

function value = importAllThreeExtractors(conn, workspaceRoot, repoRoot, recordingRef)
dsRoot = fullfile(workspaceRoot, "deepsqueak");
dsPath = fullfile(dsRoot, "exports", "REC_A_Stats.xlsx");
writeCells(dsPath, deepSqueakCells());
ds = vawlume.ingest.deepsqueak(conn, dsPath, recordingRef, ...
    struct(run_key="demo-ds", extractor_version="3.2.1"), ...
    RepoRoot=repoRoot, ArtifactRoot=dsRoot, Apply=true);
assert(ds.committed, "DeepSqueak import did not commit.");

mupetRoot = fullfile(workspaceRoot, "mupet");
mupetPath = fullfile(mupetRoot, "CSV", "REC_A.csv");
configPath = fullfile(mupetRoot, "config.csv");
writeCells(mupetPath, mupetCells());
writeText(configPath, strjoin(mupetConfigLines(), newline) + newline);
mupet = vawlume.ingest.mupet(conn, mupetPath, recordingRef, ...
    struct(run_key="demo-mupet", extractor_version="2.1", ...
    settings=struct(config_path=configPath)), ...
    RepoRoot=repoRoot, ArtifactRoot=mupetRoot, Apply=true);
assert(mupet.committed, "MUPET import did not commit.");

usvsegRoot = fullfile(workspaceRoot, "usvseg");
usvsegPath = fullfile(usvsegRoot, "REC_A_dat.csv");
writeLines(usvsegPath, usvsegLines());
usvseg = vawlume.ingest.usvseg(conn, usvsegPath, recordingRef, ...
    struct(run_key="demo-usvseg", extractor_version="0.9r2"), ...
    RepoRoot=repoRoot, ArtifactRoot=usvsegRoot, Apply=true);
assert(usvseg.committed, "USVSEG import did not commit.");

runKey = ["demo-ds"; "demo-mupet"; "demo-usvseg"];
extractor = ["DeepSqueak"; "MUPET"; "USVSEG"];
detectionCount = [ds.applied_counts.detections; ...
    mupet.applied_counts.detections; usvseg.applied_counts.detections];
value = struct( ...
    runs=table(runKey, extractor, detectionCount, ...
        VariableNames=["run_key", "extractor", "detection_count"]), ...
    total_detection_count=sum(detectionCount));
end

function value = runPairwiseComparisons(conn, recordingRef, repoRoot, specPath)
pairs = { ...
    {"demo-match-ds-mupet", "demo-ds", "demo-mupet"}
    {"demo-match-ds-usvseg", "demo-ds", "demo-usvseg"}
    {"demo-match-mupet-usvseg", "demo-mupet", "demo-usvseg"}};
runKey = strings(numel(pairs), 1);
runA = strings(numel(pairs), 1);
runB = strings(numel(pairs), 1);
candidateCount = zeros(numel(pairs), 1);
groupCount = zeros(numel(pairs), 1);
consensusCount = zeros(numel(pairs), 1);
for index = 1:numel(pairs)
    pair = pairs{index};
    result = vawlume.matching.compare(conn, recordingRef, ...
        struct(run_a=pair{2}, run_b=pair{3}), ...
        struct(run_key=pair{1}, profile_path=specPath), ...
        RepoRoot=repoRoot, Apply=true);
    assert(result.committed, "Matching '%s' did not commit: %s", ...
        pair{1}, result.status);
    runKey(index) = pair{1};
    runA(index) = pair{2};
    runB(index) = pair{3};
    candidateCount(index) = height(result.candidates);
    groupCount(index) = height(result.groups);
    consensusCount(index) = height(result.consensus_events);
end
value = table(runKey, runA, runB, candidateCount, groupCount, consensusCount, ...
    VariableNames=["run_key", "run_a", "run_b", "candidate_pair_count", ...
    "match_group_count", "consensus_event_count"]);
end

% ------------------------------------------------------------ read-backs ---

function rows = populationSummary(populations)
fields = string(fieldnames(populations));
filterKey = fields;
groupCount = zeros(numel(fields), 1);
memberCount = zeros(numel(fields), 1);
for index = 1:numel(fields)
    population = populations.(fields(index));
    groupCount(index) = population.selected_group_count;
    memberCount(index) = population.selected_member_count;
end
rows = table(filterKey, groupCount, memberCount, ...
    VariableNames=["filter_key", "group_count", "native_member_count"]);
end

function rows = groupShapes(population)
groups = population.groups;
rows = table(string(groups.group_key), double(groups.member_count), ...
    double(groups.extractor_count), string(groups.extractor_set_key), ...
    double(groups.supported_extractor_pair_count), ...
    double(groups.possible_extractor_pair_count), ...
    string(groups.supported_extractor_pair_pattern), ...
    string(groups.unsupported_extractor_pair_pattern), ...
    logical(groups.is_extractor_pair_support_complete), ...
    logical(groups.is_one_detection_per_extractor), ...
    logical(groups.is_unambiguous_one_to_one), ...
    logical(groups.is_extractor_unique), ...
    VariableNames=["group_key", "native_member_count", "extractor_count", ...
    "extractor_set_key", "supported_pairs", "possible_pairs", ...
    "supported_pair_pattern", "unsupported_pair_pattern", ...
    "support_complete", "one_detection_per_extractor", ...
    "unambiguous_one_to_one", "extractor_unique"]);
rows = sortrows(rows, "group_key");
end

function value = upstreamFingerprint(conn)
value = fetch(conn, "SELECT d.detection_id, d.extraction_run_id, " + ...
    "d.native_event_id, d.start_time_s, d.end_time_s, " + ...
    "COUNT(em.event_measurement_id) AS measurements " + ...
    "FROM detections d LEFT JOIN event_measurements em " + ...
    "ON em.detection_id=d.detection_id " + ...
    "GROUP BY d.detection_id ORDER BY d.detection_id");
end

% ---------------------------------------------------------------- patterns ---

function value = allPairPattern()
value = "deepsqueak--mupet|deepsqueak--usvseg|mupet--usvseg";
end

function value = chainThroughMupetPattern()
value = "deepsqueak--mupet|mupet--usvseg";
end

function value = chainThroughUsvsegPattern()
value = "deepsqueak--usvseg|mupet--usvseg";
end

% --------------------------------------------------------------- fixtures ---
%
% Six deliberate component shapes over one synthetic recording:
%
%   ~10 s  clean triple            all three extractor pairs supported
%   ~20 s  open chain              DeepSqueak--MUPET and MUPET--USVSEG only
%   ~30 s  complete split/merge    MUPET splits one call into two syllables
%   ~40 s  two-extractor pair      no USVSEG detection nearby
%   ~50 s  extractor-unique        USVSEG alone
%   ~60 s  open chain              DeepSqueak--USVSEG and MUPET--USVSEG only
%
% The two open chains support the same number of extractor pairs and different
% pairs, which is exactly what separates an exact pattern query from a coarse
% K-of-possible query.

function cells = deepSqueakCells()
headers = {'File', 'ID', 'Label', 'Accepted', 'Score', 'Begin Time (s)', ...
    'End Time (s)', 'Call Length (s)', 'Principle Frequency (kHz)', ...
    'Low Freq (kHz)', 'High Freq (kHz)', 'Delta Freq (kHz)', ...
    'Frequency Standard Deviation (kHz)', 'Slope (kHz/s)', 'Sinuosity', ...
    'Mean Power (dB/Hz)', 'Tonality', 'Peak Freq (kHz)'};
file = 'synthetic/deepsqueak/REC_A_detections.mat';
cells = [headers
    {file,1,'class_a',1,.9134,10.000,10.050,.050,62.0,45,80,35,3.2,-120.5,1.12,-71.4,.78,63.0}
    {file,2,'class_a',1,.8021,20.000,20.060,.060,61.0,50,72,22,2.1,15.00,1.05,-70.1,.81,61.5}
    {file,3,'class_b',1,.7010,30.000,30.100,.100,59.0,48,70,22,2.6,4.000,1.09,-70.8,.74,59.5}
    {file,4,'class_b',1,.6604,40.000,40.040,.040,63.5,42,84,42,4.4,-8.25,1.40,-69.3,.69,64.2}
    {file,5,'class_a',1,.7532,60.000,60.060,.060,60.5,46,75,29,2.9,6.500,1.07,-70.5,.76,61.0}];
end

function cells = mupetCells()
headers = {'Syllable number','Syllable start time (sec)', ...
    'Syllable end time (sec)','inter-syllable interval (sec)', ...
    'syllable duration (msec)','starting frequency (kHz)', ...
    'final frequency (kHz)','minimum frequency (kHz)', ...
    'maximum frequency (kHz)','mean frequency (kHz)', ...
    'frequency bandwidth (kHz)','total syllable energy (dB)', ...
    'peak syllable amplitude (dB)'};
cells = [headers
    {1,10.004,10.052,9.978,48,45,62,46.0,79.0,63.0,33,12.5,-18}
    {2,20.030,20.090,9.912,60,46,59,47.0,77.0,61.5,30,11.5,-19}
    {3,30.002,30.045,0.007,43,47,61,45.0,75.0,60.0,30,10.5,-20}
    {4,30.052,30.098,9.904,46,47,61,42.5,84.5,63.0,42,10.5,-20}
    {5,40.002,40.042,20.020,40,48,62,43.0,83.0,62.5,40,9.5,-21}
    {6,60.062,60.120,'NA',58,46,60,50.5,72.5,61.0,22,11.0,-19}];
end

function lines = mupetConfigLines()
lines = ["noise-reduction,5"; "minimum-syllable-duration,008"; ...
    "maximum-syllable-duration,200"; "minimum-syllable-total-energy,-15"; ...
    "minimum-syllable-peak-amplitude,-25"; "minimum-syllable-distance,5"; ...
    "sample-frequency,250000"; "minimum-usv-frequency,30000"; ...
    "maximum-usv-frequency,120000"; "number-filterbank-filters,64"; ...
    "filterbank-type,1"];
end

function lines = usvsegLines()
lines = [ ...
    "#,start,end,duration,maxfreq,maxamp,meanfreq,cvfreq"
    "1,10.0020,10.0490,47.0,72.500,-18.2,61.250,0.1234"
    "2,20.0620,20.1200,58.0,74.000,-19.1,63.125,0.1111"
    "3,30.0010,30.0990,98.0,69.750,-20.4,58.500,0.1502"
    "4,50.0000,50.0450,45.0,71.250,-17.8,60.000,0.0987"
    "5,60.0300,60.0900,60.0,73.125,-18.9,62.375,0.1345"];
end

% -------------------------------------------------------------- utilities ---

function writeCells(path, cells)
makeParent(path);
if isfile(path), delete(path); end
writecell(cells, path);
end

function writeLines(path, lines)
makeParent(path);
fileId = fopen(path, "w");
if fileId < 0
    error("vawlume:examples:FixtureCreationFailed", ...
        "Could not create demonstration input: %s", path);
end
cleanupFile = onCleanup(@() fclose(fileId));
fprintf(fileId, "%s\n", lines);
clear cleanupFile
end

function writeText(path, value)
makeParent(path);
fileId = fopen(path, "w");
if fileId < 0
    error("vawlume:examples:FixtureCreationFailed", ...
        "Could not create demonstration input: %s", path);
end
cleanupFile = onCleanup(@() fclose(fileId));
fprintf(fileId, "%s", value);
clear cleanupFile
end

function makeParent(path)
parent = fileparts(path);
if ~isfolder(parent), mkdir(parent); end
end

function root = normalizedRepoRoot(root)
if strlength(root) == 0, root = fileparts(fileparts(mfilename("fullpath"))); end
try
    root = string(java.io.File(char(root)).getCanonicalPath());
catch
end
end

function value = pathContains(target)
value = any(split(string(path), pathsep) == string(target));
end

function restoreSourcePath(sourcePath, shouldRemove)
if shouldRemove && pathContains(sourcePath), rmpath(sourcePath); end
end

function closeConnection(conn)
try
    if isopen(conn), close(conn); end
catch
end
end

function removeTree(root)
if isfolder(root), rmdir(root, "s"); end
end

function printDemonstration(value)
disp("VAWLUME THREE-EXTRACTOR AGREEMENT DEMONSTRATION")
disp(value.calibration_boundary)
disp("Imported extraction runs (never implicitly pooled):")
disp(value.imports.runs)
disp("Pairwise matching analyses (the primitive):")
disp(value.pairwise)
fprintf("Composed agreement run '%s': %d groups over %d native members\n", ...
    value.agreement.run_key, value.agreement.group_count, ...
    value.agreement.native_member_count);
disp("Agreement group shapes:")
disp(value.group_shapes)
disp("Selected populations:")
disp(value.population_summary)
fprintf(['Exact versus coarse: %d groups support exactly two of three ' ...
    'pairs;\n  the two exact patterns split them %d and %d, disjointly: %d\n'], ...
    value.exact_versus_coarse.coarse_group_count, ...
    value.exact_versus_coarse.exact_pattern_group_counts(1), ...
    value.exact_versus_coarse.exact_pattern_group_counts(2), ...
    value.exact_versus_coarse.exact_patterns_are_disjoint);
disp(value.denominator_note)
fprintf(['Detections partitioned: %d; member detections unique: %d; ' ...
    'native detections unchanged: %d\n'], ...
    value.identity.detections_partitioned, ...
    value.identity.member_detections_unique, ...
    value.identity.native_detections_unchanged);
fprintf("Foreign-key violations: %d; temporary artifacts removed: %d\n", ...
    height(value.foreign_key_check), value.temporary_artifacts_removed);
fprintf("Proves:\n  %s\n", strjoin(value.proves, newline + "  "));
fprintf("Does not prove:\n  %s\n", ...
    strjoin(value.does_not_prove, newline + "  "));
end
