function demonstration = multimodal_integration_demo(options)
%MULTIMODAL_INTEGRATION_DEMO Demonstrate the Phase 2 multimodal input layer.
%
% DEMONSTRATION = MULTIMODAL_INTEGRATION_DEMO() creates a disposable database, a
% two-channel synthetic recording, a declared arena frame with two microphone
% placements, an external tracking artifact holding three native trajectories,
% time-varying visual-identity evidence across a crossing, four acoustic
% references, per-channel reference-response measurements, and one aggregated
% response/QC profile with exact supporting lineage.
%
% Everything is synthetic and every generated file is removed before return.
%
% What the example is for is the separation it maintains. Four uncertainty
% dimensions appear side by side and none is derived from another:
%
%   pose/localization confidence   from the tracking artifact, per sample
%   visual-identity evidence       per interval, with declared semantics
%   temporal-alignment residual    from a stored clock transform
%   acoustic channel response      per reference family, per channel
%
% No caller is assigned. Nothing here multiplies visual and acoustic evidence
% into a caller score, ranks channels, computes an animal-to-microphone distance,
% or suggests that a nearer animal produced a detected call. Phase 2 preserves
% these components for later attribution work; combining them is not its job.
%
% Name-value options:
%   Print     print compact developer-facing read-backs (default true)
%   RepoRoot  repository root, inferred from this file by default
%
% See also VAWLUME.TRACKING.READWINDOW, VAWLUME.TRACKING.IDENTITYCANDIDATES,
% VAWLUME.ACOUSTIC.ESTIMATECHANNELRESPONSE

arguments
    options.Print (1,1) logical = true
    options.RepoRoot (1,1) string = ""
end

repoRoot = options.RepoRoot;
if strlength(repoRoot) == 0
    repoRoot = string(fileparts(fileparts(mfilename("fullpath"))));
end
sourcePath = fullfile(repoRoot, "src");
removePath = ~contains(path, sourcePath);
if removePath, addpath(sourcePath); end
cleanupPath = onCleanup(@() restorePath(sourcePath, removePath));

workspace = string(tempname);
mkdir(workspace);
cleanupWorkspace = onCleanup(@() removeTree(workspace));
databasePath = fullfile(workspace, "multimodal_integration_demo.sqlite");
conn = sqlite(char(databasePath), "create");
cleanupConnection = onCleanup(@() closeConnection(conn));
vawlume.db.applySchema(conn, fullfile(repoRoot, "schema", "schema.sql"));
vawlume.db.registerBuiltinSemantics(conn, repoRoot);

layout = sessionLayout();
audioFacts = writeSyntheticAudio(workspace, layout);
seedSession(conn, audioFacts);
recordingRef = struct(recording_id=1);
projectRef = struct(project_key="multimodal_demo");

geometry = declareGeometry(conn, projectRef, recordingRef);
tracking = registerTracking(conn, repoRoot, workspace, recordingRef, layout);
windows = readTrackingWindows(conn, repoRoot, workspace, layout);
compatibility = vawlume.tracking.assertGeometryCompatible(conn, streamRef(), ...
    recordingRef);
identity = recordIdentityEvidence(conn, layout);
clocks = demonstrateClockSeparation(conn, repoRoot, workspace, layout);
acoustic = demonstrateAcousticResponse(conn, recordingRef, workspace, layout);

uncertainty = uncertaintySummary(windows, identity, clocks, acoustic);
inventory = struct( ...
    tracking_series=rowCount(conn, "tracking_series"), ...
    tracking_samples_in_sqlite=windows.covered.dense_samples_stored, ...
    identity_associations=rowCount(conn, "tracking_identity_associations"), ...
    acoustic_references=rowCount(conn, "acoustic_references"), ...
    derived_measurements=rowCount(conn, "derived_measurements"), ...
    channel_response_estimates=rowCount(conn, "channel_response_estimates"), ...
    channel_response_estimate_sources=rowCount(conn, ...
        "channel_response_estimate_sources"), ...
    caller_attribution_rows=0);

demonstration = struct( ...
    session_layout=layout, ...
    audio=audioFacts, ...
    geometry=geometry, ...
    tracking=tracking, ...
    tracking_windows=windows, ...
    geometry_compatibility=compatibility, ...
    identity=identity, ...
    clock_separation=clocks, ...
    acoustic=acoustic, ...
    uncertainty=uncertainty, ...
    database_inventory=inventory, ...
    foreign_key_check=fetch(conn, "PRAGMA foreign_key_check"), ...
    proves=[ ...
        "tracking coordinates and microphone placements share one declared frame"; ...
        "dense tracking samples are read from the artifact and never stored"; ...
        "coverage distinguishes covered, partial, and uncovered windows"; ...
        "an animal-like track label acquires no canonical identity by itself"; ...
        "identity is interval-scoped evidence and may be ambiguous or unresolved"; ...
        "a missing identity value stays missing rather than becoming 1.0"; ...
        "pose, identity, clock, and acoustic uncertainty stay separately queryable"; ...
        "reference families are aggregated separately and never blended"; ...
        "a response profile cites every supporting measurement and source run"], ...
    does_not_prove=[ ...
        "which animal produced any detected vocalization"; ...
        "any calibrated distance, gain correction, or normalized call amplitude"; ...
        "real synchronization accuracy between acquisition clocks"; ...
        "real tracker or re-identification performance"; ...
        "calibrated divergence, confidence, or coverage thresholds"], ...
    caller_attribution=struct( ...
        performed=false, ...
        combined_confidence_computed=false, ...
        note="Phase 2 preserves pose, identity, alignment, and acoustic " + ...
            "evidence as separate components. No caller is assigned, no " + ...
            "channel is ranked, and no distance is computed."), ...
    temporary_artifacts_removed=false);

if options.Print, printDemo(demonstration); end

close(conn);
clear cleanupConnection
removeTree(workspace);
clear cleanupWorkspace
demonstration.temporary_artifacts_removed = ...
    ~isfolder(workspace) && ~isfile(databasePath);
clear cleanupPath
end

% ------------------------------------------------------------ session layout ---

function layout = sessionLayout()
%SESSIONLAYOUT The one place every synthetic time, level, and label is declared.
%
% The crossing sits between the two reference families on purpose. The example
% asserts no relationship between a visual crossing and an acoustic reference,
% and overlapping them would invite one.
layout = struct();
layout.sample_rate_hz = 4000;
layout.duration_s = 10;
layout.channel_count = 2;
layout.right_channel_scale = 0.5;
layout.tone_rms_target = 0.4;
layout.noise_rms_target = 0.36;
layout.tone_frequency_hz = 100;
layout.noise_frequencies_hz = [200 500];
layout.declared_band_hz = [80 620];
layout.tone_intervals_s = [1 2; 3 4];
layout.noise_intervals_s = [7 8; 9 10];
layout.tracking_interval_s = 0.5;
layout.tracking_span_s = [0 10];
layout.crossing_s = [4 6];
layout.pose_confidence_nominal = 0.98;
layout.pose_confidence_crossing = 0.34;
layout.reidentification_values = [0.55 0.52];
layout.native_track_ids = ["mouse_a", "mouse_b", "mouse_c"];
layout.entity_native_ids = ["mouse_a", "mouse_b"];
layout.clock_offset_s = 10;
layout.clock_fit_rmse_s = 0.001;
layout.clock_fit_max_residual_s = 0.002;
end

% --------------------------------------------------------- synthetic session ---

function facts = writeSyntheticAudio(workspace, layout)
%WRITESYNTHETICAUDIO A deterministic two-channel file with four reference bursts.
%
% Each reference interval spans an integer number of cycles of every component it
% contains, so its RMS is exact rather than approximate, and every interval of a
% family carries the identical waveform. That is what makes the aggregated
% profile reproducible: the repeats agree because the signal does, not because
% the aggregation smoothed anything.
mkdir(fullfile(workspace, "audio"));
audioPath = fullfile(workspace, "audio", "session01.wav");
sampleRate = layout.sample_rate_hz;
total = sampleRate * layout.duration_s;
time = (0:total - 1)' / sampleRate;
left = zeros(total, 1);

toneAmplitude = layout.tone_rms_target * sqrt(2);
for index = 1:size(layout.tone_intervals_s, 1)
    selected = intervalSamples(layout.tone_intervals_s(index, :), sampleRate, total);
    left(selected) = toneAmplitude * ...
        sin(2 * pi * layout.tone_frequency_hz * time(selected));
end

% Orthogonal components share the family's power equally, so k sinusoids of
% amplitude target*sqrt(2/k) give the interval exactly the target RMS.
noiseAmplitude = layout.noise_rms_target * ...
    sqrt(2 / numel(layout.noise_frequencies_hz));
for index = 1:size(layout.noise_intervals_s, 1)
    selected = intervalSamples(layout.noise_intervals_s(index, :), sampleRate, total);
    component = zeros(numel(selected), 1);
    for frequency = layout.noise_frequencies_hz
        component = component + noiseAmplitude * ...
            sin(2 * pi * frequency * time(selected));
    end
    left(selected) = component;
end

samples = [left, layout.right_channel_scale * left];
audiowrite(char(audioPath), samples, sampleRate, BitsPerSample=24);
fileInfo = dir(audioPath);
facts = struct( ...
    relative_path="audio/session01.wav", ...
    filename="session01.wav", ...
    sample_rate_hz=sampleRate, ...
    channel_count=layout.channel_count, ...
    duration_s=layout.duration_s, ...
    size_bytes=fileInfo.bytes, ...
    expected_rms=table(["tone"; "tone"; "noise"; "noise"], [1; 2; 1; 2], ...
        [layout.tone_rms_target; ...
            layout.right_channel_scale * layout.tone_rms_target; ...
            layout.noise_rms_target; ...
            layout.right_channel_scale * layout.noise_rms_target], ...
        VariableNames=["reference_type", "channel_index", "expected_rms"]));
end

function selected = intervalSamples(interval, sampleRate, total)
%INTERVALSAMPLES Half-open [start,end) in seconds as one-based sample indices.
first = floor(interval(1) * sampleRate) + 1;
last = min(round(interval(2) * sampleRate), total);
selected = (first:last)';
end

function seedSession(conn, audioFacts)
%SEEDSESSION The project, recording, channels, entities, and native clock.
%
% Written directly because no public path establishes recording channels or a
% recording-native video clock: project intake is demonstrated by
% project_intake_demo, and channel rows are a schema fact the Phase 2 APIs
% consume rather than create. Everything this example actually demonstrates goes
% through the public vawlume.* functions below.
execute(conn, "INSERT INTO projects(project_id,project_key,project_name) " + ...
    "VALUES (1,'multimodal_demo','Synthetic multimodal demonstration')");
execute(conn, "INSERT INTO source_files(source_file_id,project_id,file_role," + ...
    "path_or_uri,relative_path,filename,file_format,size_bytes) VALUES (1,1," + ...
    "'recording_audio'," + sqlText(audioFacts.relative_path) + "," + ...
    sqlText(audioFacts.relative_path) + "," + sqlText(audioFacts.filename) + ...
    ",'wav'," + string(audioFacts.size_bytes) + ")");
execute(conn, "INSERT INTO recordings(recording_id,project_id,source_file_id," + ...
    "native_recording_id,sample_rate_hz,channel_count,duration_s) VALUES " + ...
    "(1,1,1,'SESSION_01'," + string(audioFacts.sample_rate_hz) + "," + ...
    string(audioFacts.channel_count) + "," + string(audioFacts.duration_s) + ")");
execute(conn, "INSERT INTO recording_channels(recording_channel_id,recording_id," + ...
    "channel_index,channel_label) VALUES (1,1,1,'left'),(2,1,2,'right')");
execute(conn, "INSERT INTO timebases(project_id,recording_id,timebase_name," + ...
    "timebase_kind) VALUES (1,1,'video_native','video_frame_clock')");
execute(conn, "INSERT INTO entity_types(project_id,native_name) VALUES (1,'subject')");
execute(conn, "INSERT INTO experimental_entities(project_id,entity_type_id," + ...
    "native_id) VALUES (1,1,'mouse_a'),(1,1,'mouse_b')");
end

% -------------------------------------------------------------- geometry ---

function geometry = declareGeometry(conn, projectRef, recordingRef)
%DECLAREGEOMETRY One arena frame and the two microphones located inside it.
system = vawlume.geometry.registerCoordinateSystem(conn, projectRef, struct( ...
    coordinate_system_key="arena_2d", ...
    coordinate_system_name="Courtship arena floor plane", ...
    dimensionality=2, unit="cm", ...
    origin_description="front-left inner corner of the arena floor", ...
    orientation_description="x rightward, y away from the operator"));
vawlume.geometry.registerChannelPlacement(conn, recordingRef, struct( ...
    channel_index=1, coordinate_system_key="arena_2d", ...
    position_x=0, position_y=18.5, placement_role="microphone"));
vawlume.geometry.registerChannelPlacement(conn, recordingRef, struct( ...
    channel_index=2, coordinate_system_key="arena_2d", ...
    position_x=37, position_y=18.5, placement_role="microphone"));

geometry = struct( ...
    coordinate_system=system, ...
    coordinate_systems=vawlume.geometry.readCoordinateSystems(conn, projectRef), ...
    placements=vawlume.geometry.readChannelPlacements(conn, recordingRef), ...
    distance_computed=false, ...
    note="Placements and tracking coordinates are declared in one frame so " + ...
        "relating them is legal. The example computes no distance from them.");
end

% -------------------------------------------------------------- tracking ---

function tracking = registerTracking(conn, repoRoot, workspace, recordingRef, layout)
%REGISTERTRACKING Canonicalize the external artifact without copying samples.
artifactPath = fullfile(workspace, "session01_tracking.csv");
writeTrackingArtifact(artifactPath, layout);
profilePath = fullfile(workspace, "session01_tracking_profile.json");
writeTrackingProfile(profilePath, repoRoot);

planned = vawlume.tracking.register(conn, recordingRef, struct( ...
    artifact_path="session01_tracking.csv", profile_path=profilePath, ...
    timebase_key="video_native"), RepoRoot=repoRoot, SourceRoot=workspace);
applied = vawlume.tracking.register(conn, recordingRef, struct( ...
    artifact_path="session01_tracking.csv", profile_path=profilePath, ...
    timebase_key="video_native"), Apply=true, RepoRoot=repoRoot, ...
    SourceRoot=workspace);

tracking = struct( ...
    dry_run_status=string(planned.status), ...
    dry_run_wrote_nothing=~planned.committed, ...
    registration=applied, ...
    series=applied.series, ...
    coverage=applied.coverage, ...
    dense_samples_stored=applied.dense_samples_stored, ...
    raw_video_processed=false, ...
    reidentification_performed=false);
end

function writeTrackingArtifact(path, layout)
%WRITETRACKINGARTIFACT Three native trajectories, two of which cross at 5 s.
%
% The track labels are animal-like on purpose. A tracker naming a trajectory
% 'mouse_a' is still only naming a trajectory, and after the crossing the
% trajectory labelled 'mouse_a' carries evidence for the animal 'mouse_b'.
lines = "time_s,track,bodypart,x,y,likelihood";
times = layout.tracking_span_s(1):layout.tracking_interval_s:layout.tracking_span_s(2);
for track = layout.native_track_ids
    for part = ["snout", "tail_base"]
        for t = times
            [x, y] = trackPosition(track, t);
            if part == "tail_base"
                y = y - 3;
            end
            confidence = layout.pose_confidence_nominal;
            if t >= layout.crossing_s(1) && t <= layout.crossing_s(2)
                confidence = layout.pose_confidence_crossing;
            end
            lines(end + 1, 1) = join([compose("%.4f", t), track, part, ...
                compose("%.4f", x), compose("%.4f", y), ...
                compose("%.2f", confidence)], ","); %#ok<AGROW>
        end
    end
end
writelines(lines, path);
end

function [x, y] = trackPosition(track, t)
%TRACKPOSITION Two trajectories meeting near x = 18 cm at t = 5 s, plus one idler.
switch track
    case "mouse_a"
        x = 2 + 3.2 * t;
        y = 15;
    case "mouse_b"
        x = 34 - 3.2 * t;
        y = 15;
    otherwise
        x = 5;
        y = 27;
end
end

function writeTrackingProfile(path, repoRoot)
%WRITETRACKINGPROFILE The shipped generic profile, pointed at this artifact.
source = fullfile(repoRoot, "config", "01_mapping_profiles", "tracking", ...
    "generic_tracking_mapping_profile.json");
document = jsondecode(fileread(source));
document.profiles.columns.track_label.source_field = "track";
writelines(string(jsonencode(document, PrettyPrint=true)), path);
end

function windows = readTrackingWindows(conn, repoRoot, workspace, layout)
%READTRACKINGWINDOWS Three coverage states, read from the artifact each time.
readOptions = {"SourceRoot", workspace, "RepoRoot", repoRoot};
covered = vawlume.tracking.readWindow(conn, streamRef(), [0 2], readOptions{:});
crossing = vawlume.tracking.readWindow(conn, streamRef(), ...
    [layout.crossing_s(1) + 0.2, layout.crossing_s(2) - 0.2], readOptions{:});
partial = vawlume.tracking.readWindow(conn, streamRef(), [9 12], readOptions{:});
uncovered = vawlume.tracking.readWindow(conn, streamRef(), [14 16], readOptions{:});

windows = struct( ...
    covered=covered, crossing=crossing, partial=partial, uncovered=uncovered, ...
    coverage_states=table(["covered"; "crossing"; "partial"; "uncovered"], ...
        [string(covered.coverage_status); string(crossing.coverage_status); ...
            string(partial.coverage_status); string(uncovered.coverage_status)], ...
        [string(covered.sample_status); string(crossing.sample_status); ...
            string(partial.sample_status); string(uncovered.sample_status)], ...
        [height(covered.samples); height(crossing.samples); ...
            height(partial.samples); height(uncovered.samples)], ...
        VariableNames=["window", "coverage_status", "sample_status", "sample_rows"]), ...
    pose_confidence_nominal=unique(covered.samples.pose_confidence), ...
    pose_confidence_crossing=unique(crossing.samples.pose_confidence), ...
    identity_boundary=covered.identity_boundary);
end

% ------------------------------------------------------- visual identity ---

function identity = recordIdentityEvidence(conn, layout)
%RECORDIDENTITYEVIDENCE Clean before, ambiguous during, reversed after.
crossing = layout.crossing_s;
span = layout.tracking_span_s;
reid = layout.reidentification_values;

% Before: manual assertions, and deliberately no number. A manual reviewer who
% is certain has still produced no measurement, so the value stays missing.
assertIdentity(conn, "mouse_a", "mouse_a", [span(1) crossing(1)], "assigned", ...
    "manual_assertion");
assertIdentity(conn, "mouse_b", "mouse_b", [span(1) crossing(1)], "assigned", ...
    "manual_assertion");

% During: one trajectory is compatible with either animal, and the upstream
% scores say which is which only weakly. Both candidates are stored.
scoreIdentity(conn, "mouse_a", "mouse_a", crossing, reid(1));
scoreIdentity(conn, "mouse_a", "mouse_b", crossing, reid(2));

% And the other trajectory's identity is explicitly unknown, which is a
% different finding from having no evidence at all.
vawlume.tracking.registerIdentityAssociation(conn, streamRef(), struct( ...
    native_track_id="mouse_b", start_time_native=crossing(1), ...
    end_time_native=crossing(2), assignment_state="unresolved", ...
    evidence_kind="manual_review", review_state="reviewed", ...
    method="manual_review_of_crossing"));

% After: the association has reversed. The trajectory still labelled 'mouse_a'
% now carries evidence for the animal 'mouse_b'.
assertIdentity(conn, "mouse_a", "mouse_b", [crossing(2) span(2)], "assigned", ...
    "manual_assertion");
assertIdentity(conn, "mouse_b", "mouse_a", [crossing(2) span(2)], "assigned", ...
    "manual_assertion");

before = vawlume.tracking.identityCandidates(conn, streamRef(), ...
    [span(1) crossing(1) - 0.5]);
during = vawlume.tracking.identityCandidates(conn, streamRef(), ...
    [crossing(1) + 0.2, crossing(2) - 0.2]);
after = vawlume.tracking.identityCandidates(conn, streamRef(), ...
    [crossing(2) + 0.5, span(2)]);

identity = struct( ...
    before=before, during=during, after=after, ...
    resolution_by_window=resolutionTable(before, during, after), ...
    label_versus_identity=labelComparison(before, after, layout), ...
    missing_values_remain_missing=all(isnan(before.associations.identity_value)), ...
    numeric_evidence=during.associations(~isnan( ...
        during.associations.identity_value), ["native_track_id", ...
        "entity_native_id", "assignment_state", "identity_value", ...
        "identity_value_semantics", "calibration_status"]), ...
    unexamined_track=layout.native_track_ids(3), ...
    image_reidentification_performed=false);
end

function assertIdentity(conn, trackId, entityNativeId, interval, state, evidenceKind)
vawlume.tracking.registerIdentityAssociation(conn, streamRef(), struct( ...
    native_track_id=trackId, entity_native_id=entityNativeId, ...
    start_time_native=interval(1), end_time_native=interval(2), ...
    assignment_state=state, evidence_kind=evidenceKind, ...
    review_state="reviewed", method="manual_review_by_scorer"));
end

function scoreIdentity(conn, trackId, entityNativeId, interval, value)
%SCOREIDENTITY An upstream similarity score, recorded with what it means.
vawlume.tracking.registerIdentityAssociation(conn, streamRef(), struct( ...
    native_track_id=trackId, entity_native_id=entityNativeId, ...
    start_time_native=interval(1), end_time_native=interval(2), ...
    assignment_state="ambiguous", evidence_kind="reidentification_score", ...
    identity_value=value, ...
    identity_value_semantics="cosine_similarity_of_appearance_embeddings", ...
    calibration_status="uncalibrated", method="upstream_tracker_similarity"));
end

function value = resolutionTable(before, during, after)
value = table();
for entry = [struct(name="before", result=before), ...
        struct(name="during", result=during), ...
        struct(name="after", result=after)]
    tracks = entry.result.tracks;
    value = [value; table(repmat(string(entry.name), height(tracks), 1), ...
        tracks.native_track_id, tracks.resolution, tracks.candidate_count, ...
        tracks.has_numeric_evidence, ...
        VariableNames=["window", "native_track_id", "resolution", ...
        "candidate_count", "has_numeric_evidence"])]; %#ok<AGROW>
end
end

function value = labelComparison(before, after, layout)
%LABELCOMPARISON What the tracker called each trajectory, beside the evidence.
%
% Two of the labels are spelled exactly like canonical entities and agree with
% the evidence before the crossing. That agreement is a coincidence of naming
% with no authority behind it, and it stops holding after the crossing while the
% labels stay put. The third label names no entity at all.
tracks = layout.native_track_ids(:);
beforeEntity = strings(numel(tracks), 1);
afterEntity = strings(numel(tracks), 1);
for index = 1:numel(tracks)
    beforeEntity(index) = entityFor(before.associations, tracks(index));
    afterEntity(index) = entityFor(after.associations, tracks(index));
end
value = table(tracks, beforeEntity, afterEntity, ...
    beforeEntity == tracks, afterEntity == tracks, ...
    VariableNames=["native_track_id", "entity_before_crossing", ...
    "entity_after_crossing", "label_matches_evidence_before", ...
    "label_matches_evidence_after"]);
value.Properties.Description = "A track label is never canonical identity. " + ...
    "Where the spelling agrees before the crossing it disagrees after it, " + ...
    "and the label never moved.";
end

function value = entityFor(associations, trackId)
selected = associations(associations.native_track_id == trackId, :);
named = unique(selected.entity_native_id(strlength( ...
    selected.entity_native_id) > 0));
if isempty(named)
    value = "<no evidence>";
else
    value = strjoin(sort(named)', "|");
end
end

% --------------------------------------------------- clocks and alignment ---

function clocks = demonstrateClockSeparation(conn, repoRoot, workspace, layout)
%DEMONSTRATECLOCKSEPARATION Alignment QC is its own field, not a confidence.
missing = vawlume.tracking.readWindow(conn, streamRef(), [0 2], ...
    SourceRoot=workspace, RepoRoot=repoRoot, ...
    ReferenceTimebaseKey="neural_native");

writeStoredTransform(conn, layout);
applied = vawlume.tracking.readWindow(conn, streamRef(), [0 2], ...
    SourceRoot=workspace, RepoRoot=repoRoot, ...
    ReferenceTimebaseKey="neural_native");

clocks = struct( ...
    without_transform=struct( ...
        reference_time_status=string(missing.reference_time_status), ...
        reference_times_all_missing=all(isnan(missing.samples.time_reference_s)), ...
        native_times_untouched=all(isfinite(missing.samples.time_native_s)), ...
        pose_confidence_unchanged=isequal( ...
            unique(missing.samples.pose_confidence), ...
            layout.pose_confidence_nominal)), ...
    with_transform=struct( ...
        reference_time_status=string(applied.reference_time_status), ...
        method=string(applied.transform.method), ...
        rmse_s=applied.transform.rmse_s, ...
        max_abs_residual_s=applied.transform.max_abs_residual_s, ...
        status=string(applied.transform.status), ...
        offset_recovered_s=unique(round(applied.samples.time_reference_s - ...
            applied.samples.time_native_s, 9))), ...
    fit_is_estimated_not_validated=applied.transform.status == "estimated", ...
    note="The transform below is written directly as fixture material. " + ...
        "Fitting belongs to the alignment layer, which temporal_alignment_demo " + ...
        "demonstrates; what matters here is that its residual evidence arrives " + ...
        "beside pose confidence and identity evidence without touching either.");
end

function writeStoredTransform(conn, layout)
%WRITESTOREDTRANSFORM One solved offset transform, video_native -> neural_native.
execute(conn, "INSERT INTO timebases(project_id,recording_id,timebase_name," + ...
    "timebase_kind) VALUES (1,1,'neural_native','neural_acquisition_clock')");
execute(conn, "INSERT INTO analysis_runs(project_id,run_type,run_key,status) " + ...
    "VALUES (1,'temporal_alignment','demo-alignment','completed')");
execute(conn, "INSERT INTO alignment_sets(analysis_run_id,recording_id," + ...
    "reference_timebase_id,alignment_set_key,status) VALUES (" + ...
    "(SELECT analysis_run_id FROM analysis_runs WHERE run_key='demo-alignment')," + ...
    "1,(SELECT timebase_id FROM timebases WHERE timebase_name='neural_native')," + ...
    "'demo-alignment-set','fitted')");
execute(conn, "INSERT INTO time_alignment_runs(alignment_set_id," + ...
    "source_timebase_id,target_timebase_id,method,status,n_anchors_used," + ...
    "fit_rmse_s,max_error_s) VALUES ((SELECT alignment_set_id FROM " + ...
    "alignment_sets WHERE alignment_set_key='demo-alignment-set')," + ...
    "(SELECT timebase_id FROM timebases WHERE timebase_name='video_native')," + ...
    "(SELECT timebase_id FROM timebases WHERE timebase_name='neural_native')," + ...
    "'offset','estimated',4," + string(layout.clock_fit_rmse_s) + "," + ...
    string(layout.clock_fit_max_residual_s) + ")");
execute(conn, "INSERT INTO alignment_segments(alignment_run_id,segment_index," + ...
    "source_start,source_end,scale,offset_s) VALUES ((SELECT alignment_run_id " + ...
    "FROM time_alignment_runs LIMIT 1),1,0,100,1.0," + ...
    string(layout.clock_offset_s) + ")");
end

% ------------------------------------------------------------- acoustics ---

function acoustic = demonstrateAcousticResponse(conn, recordingRef, workspace, layout)
%DEMONSTRATEACOUSTICRESPONSE References, bounded reads, measurements, profile.
references = registerReferences(conn, recordingRef, layout);
windows = readAudioWindows(conn, recordingRef, workspace, layout);
measurements = measureEveryChannel(conn, recordingRef, workspace, references);

% Only the RMS rows are aggregated, selected by exact identifier. The population
% of a profile is therefore visible in the call rather than dependent on what a
% later query happens to return.
rmsIds = measurements.derived_measurement_id( ...
    measurements.metric_key == "acoustic_rms_amplitude");

planned = vawlume.acoustic.estimateChannelResponse(conn, recordingRef, rmsIds, ...
    RequiredReferenceTypes=["tone", "noise"], MinReferences=2, ...
    DivergenceRelativeThreshold=0.25);
applied = vawlume.acoustic.estimateChannelResponse(conn, recordingRef, rmsIds, ...
    RequiredReferenceTypes=["tone", "noise"], MinReferences=2, ...
    DivergenceRelativeThreshold=0.25, Apply=true, ...
    RunKey="session01-channel-response", ...
    RunLabel="Synthetic per-family channel response", VawlumeVersion="demo");
audit = vawlume.acoustic.readChannelResponse(conn, struct( ...
    project_key="multimodal_demo", run_key="session01-channel-response"));

% A required family with no evidence is an explicit QC row, not a silent gap.
% Planned only: the demonstration keeps one profile in the database.
missingFamily = vawlume.acoustic.estimateChannelResponse(conn, recordingRef, ...
    rmsIds, RequiredReferenceTypes=["tone", "noise", "impulse"], MinReferences=2);

acoustic = struct( ...
    references=references, ...
    declared_references=vawlume.acoustic.readReferences(conn, recordingRef, ...
        ChannelIndex=1, StartTimeS=0, EndTimeS=layout.duration_s), ...
    windows=windows, ...
    measurements=measurements, ...
    planned_profile_wrote_nothing=planned.action == "planned", ...
    profile=applied, ...
    estimates=applied.estimates(:, ["reference_type", "channel_index", ...
        "metric_key", "value_real", "n_references", "relative_range", ...
        "qc_status"]), ...
    audit=audit, ...
    lineage=struct( ...
        source_measurements=height(audit.source_measurements), ...
        source_analyses=height(audit.source_analyses), ...
        dependency_roles=unique(audit.source_analyses.dependency_role)), ...
    families_kept_separate=numel(unique(applied.estimates.reference_type)) == 2, ...
    blended_family_value_absent=noBlendedValue(applied.estimates, layout), ...
    missing_family=missingFamilyRows(missingFamily), ...
    is_caller_probability=false, ...
    is_gain_correction=false);
end

function references = registerReferences(conn, recordingRef, layout)
%REGISTERREFERENCES Two families of two intervals each, recording-wide.
%
% No channel_index is declared, so each reference applies to both channels and
% the same interval can be measured on each. Reference types are open text and
% neither family is required by VAWLUME.
references = table();
definitions = [ ...
    struct(type="tone", intervals=layout.tone_intervals_s), ...
    struct(type="noise", intervals=layout.noise_intervals_s)];
for definition = definitions
    for index = 1:size(definition.intervals, 1)
        interval = definition.intervals(index, :);
        result = vawlume.acoustic.registerReference(conn, recordingRef, struct( ...
            reference_key=definition.type + "-" + string(index), ...
            reference_type=definition.type, ...
            native_label=upper(definition.type) + "_" + string(index), ...
            start_time_s=interval(1), end_time_s=interval(2), ...
            frequency_min_hz=layout.declared_band_hz(1), ...
            frequency_max_hz=layout.declared_band_hz(2)));
        references = [references; table(result.acoustic_reference_id, ...
            string(definition.type), interval(1), interval(2), ...
            string(result.action), VariableNames=["acoustic_reference_id", ...
            "reference_type", "start_time_s", "end_time_s", "action"])]; %#ok<AGROW>
    end
end
end

function value = noBlendedValue(estimates, layout)
%NOBLENDEDVALUE No estimate equals the average of the two families on any channel.
%
% The check is worth making explicitly: averaging a tone family with a noise
% family would produce a plausible-looking number that describes neither.
blended = mean([layout.tone_rms_target layout.noise_rms_target]) * ...
    [1, layout.right_channel_scale];
value = ~any(min(abs(estimates.value_real - blended), [], 2) < 1e-6);
end

function rows = missingFamilyRows(profile)
%MISSINGFAMILYROWS The explicit rows a required family with no evidence produces.
estimates = profile.estimates;
rows = estimates(estimates.reference_type == "impulse", ["reference_type", ...
    "channel_index", "value_real", "n_references", "qc_status"]);
end

function windows = readAudioWindows(conn, recordingRef, workspace, layout)
%READAUDIOWINDOWS Bounded native-clock reads, including past the end of audio.
covered = vawlume.acoustic.readAudioWindow(conn, recordingRef, 1, ...
    layout.tone_intervals_s(1, 1), layout.tone_intervals_s(1, 2), ...
    SourceRoot=workspace);
quiet = vawlume.acoustic.readAudioWindow(conn, recordingRef, 2, 6, 6.5, ...
    SourceRoot=workspace);
partial = vawlume.acoustic.readAudioWindow(conn, recordingRef, 1, 9.5, 10.5, ...
    SourceRoot=workspace);
outside = vawlume.acoustic.readAudioWindow(conn, recordingRef, 1, 11, 12, ...
    SourceRoot=workspace);
windows = struct( ...
    covered=covered, quiet=quiet, partial=partial, outside=outside, ...
    summary=table(["tone interval, channel 1"; "silence, channel 2"; ...
            "past end of audio"; "entirely past end of audio"], ...
        [string(covered.status); string(quiet.status); string(partial.status); ...
            string(outside.status)], ...
        [covered.sample_count; quiet.sample_count; partial.sample_count; ...
            outside.sample_count], ...
        [windowRms(covered.samples); windowRms(quiet.samples); ...
            windowRms(partial.samples); NaN], ...
        VariableNames=["window", "status", "sample_count", "rms"]));
end

function value = windowRms(samples)
if isempty(samples)
    value = NaN;
    return
end
value = sqrt(mean(double(samples) .^ 2));
end

function measurements = measureEveryChannel(conn, recordingRef, workspace, references)
%MEASUREEVERYCHANNEL One measurement run per reference and channel.
channels = double(unique(fetch(conn, "SELECT channel_index FROM " + ...
    "recording_channels WHERE recording_id=" + ...
    string(recordingRef.recording_id)).channel_index));
measurements = table();
for index = 1:height(references)
    referenceId = references.acoustic_reference_id(index);
    for channel = channels'
        runKey = "response-" + references.reference_type(index) + "-" + ...
            string(referenceId) + "-ch" + string(channel);
        result = vawlume.acoustic.measureReferenceResponse(conn, struct( ...
            acoustic_reference_id=referenceId), channel, ...
            SourceRoot=workspace, Apply=true, RunKey=runKey, ...
            RunLabel="Synthetic reference response", VawlumeVersion="demo");
        rows = table(result.derived_measurement_ids(:), ...
            repmat(referenceId, height(result.metrics), 1), ...
            repmat(references.reference_type(index), height(result.metrics), 1), ...
            repmat(channel, height(result.metrics), 1), ...
            result.metrics.metric_key, result.metrics.value, ...
            repmat(string(result.status), height(result.metrics), 1), ...
            VariableNames=["derived_measurement_id", "acoustic_reference_id", ...
            "reference_type", "channel_index", "metric_key", "value", "run_status"]);
        measurements = [measurements; rows]; %#ok<AGROW>
    end
end
end

% ----------------------------------------------------- uncertainty summary ---

function value = uncertaintySummary(windows, identity, clocks, acoustic)
%UNCERTAINTYSUMMARY The four components side by side, deliberately uncombined.
%
% The numbers differ from one another, which is the point: none is derived from
% or substituted for another, and no fifth row combines them.
reid = identity.numeric_evidence.identity_value;
tone = acoustic.estimates(acoustic.estimates.reference_type == "tone" & ...
    acoustic.estimates.channel_index == 1, :);
value = table( ...
    ["pose_localization"; "visual_identity"; "temporal_alignment"; ...
        "acoustic_channel_response"], ...
    ["vawlume.tracking.readWindow samples.pose_confidence"; ...
        "vawlume.tracking.identityCandidates associations.identity_value"; ...
        "vawlume.tracking.readWindow transform.rmse_s"; ...
        "vawlume.acoustic.estimateChannelResponse estimates.relative_range"], ...
    [string(compose("%.2f", windows.pose_confidence_crossing)); ...
        strjoin(compose("%.2f", reid(:))', "/"); ...
        string(compose("%.3f", clocks.with_transform.rmse_s)); ...
        string(compose("%.2e", tone.relative_range))], ...
    ["upstream per-sample keypoint likelihood"; ...
        "cosine similarity of appearance embeddings, uncalibrated"; ...
        "anchor-fit residual RMSE in seconds, estimated not validated"; ...
        "relative spread across repeats of one reference family"], ...
    ["dimensionless tracker output"; "dimensionless similarity"; "seconds"; ...
        "dimensionless ratio"], ...
    VariableNames=["dimension", "queried_from", "value", "semantics", "units"]);
value.Properties.Description = "No row combines these, and no caller " + ...
    "confidence is derived from them.";
end

% ---------------------------------------------------------------- printing ---

function printDemo(value)
fprintf('\nVAWLUME synthetic multimodal integration demonstration\n');
fprintf(['Every recording, trajectory, identity claim, and acoustic reference ' ...
    'below is synthetic.\nNo threshold here is calibrated, and no caller is ' ...
    'assigned anywhere in this example.\n']);

fprintf('\nDeclared frame and microphone placements:\n');
frame = value.geometry.coordinate_systems(1, :);
fprintf('  frame                %s  %dD in %s\n', ...
    frame.coordinate_system_key, frame.dimensionality, frame.unit);
disp(value.geometry.placements(:, ["channel_index", "channel_label", ...
    "position_x", "position_y", "position_z"]));
fprintf('  tracking/geometry compatible: %d (transformed: %d)\n', ...
    value.geometry_compatibility.compatible, ...
    value.geometry_compatibility.transformed);

fprintf('\nRegistered tracking stream:\n');
fprintf('  artifact             %s  sha256 %s\n', ...
    value.tracking.registration.artifact.relative_path, ...
    extractBefore(value.tracking.registration.artifact.checksum_sha256 + ...
    "000000000000", 13));
fprintf('  profile              %s  v%s\n', ...
    value.tracking.registration.profile.profile_key, ...
    value.tracking.registration.profile.version_label);
fprintf('  traces / samples in SQLite: %d / %d\n', ...
    height(value.tracking.series), value.tracking.dense_samples_stored);
fprintf('Bounded window coverage:\n');
disp(value.tracking_windows.coverage_states);

fprintf('Visual identity across the crossing:\n');
disp(value.identity.resolution_by_window);
fprintf('Native track label beside the entity the evidence names:\n');
disp(value.identity.label_versus_identity);
fprintf('Numeric identity evidence, with its semantics:\n');
disp(value.identity.numeric_evidence);
fprintf('  a manual assertion records no number: %d\n', ...
    value.identity.missing_values_remain_missing);

fprintf('\nClock transform is separate evidence:\n');
fprintf('  without a stored transform  %s\n', ...
    value.clock_separation.without_transform.reference_time_status);
fprintf('  with a stored transform     %s  rmse %.3f s  offset %.3f s\n', ...
    value.clock_separation.with_transform.reference_time_status, ...
    value.clock_separation.with_transform.rmse_s, ...
    value.clock_separation.with_transform.offset_recovered_s);

fprintf('\nBounded audio reads:\n');
disp(value.acoustic.windows.summary);
fprintf('Per-family channel response estimates:\n');
disp(value.acoustic.estimates);
fprintf('  families kept separate: %d; no blended value present: %d\n', ...
    value.acoustic.families_kept_separate, ...
    value.acoustic.blended_family_value_absent);
fprintf('  lineage: %d source measurements, %d source runs (%s)\n', ...
    value.acoustic.lineage.source_measurements, ...
    value.acoustic.lineage.source_analyses, ...
    strjoin(value.acoustic.lineage.dependency_roles', ', '));
fprintf('A required family with no evidence stays visible:\n');
disp(value.acoustic.missing_family);

fprintf('Four uncertainty components, none combined:\n');
disp(value.uncertainty);
fprintf('Database inventory:\n');
disp(struct2table(value.database_inventory));
fprintf('Foreign-key violations: %d\n', height(value.foreign_key_check));
fprintf('Proves:\n  %s\n', strjoin(value.proves, '\n  '));
fprintf('Does not prove:\n  %s\n', strjoin(value.does_not_prove, '\n  '));
fprintf('%s\n', value.caller_attribution.note);
end

% ----------------------------------------------------------------- helpers ---

function ref = streamRef()
ref = struct(project_key="multimodal_demo", stream_name="tracking_primary");
end

function value = rowCount(conn, tableName)
rows = fetch(conn, "SELECT COUNT(*) AS n FROM " + tableName);
value = double(rows.n(1));
end

function text = sqlText(value)
text = "'" + replace(string(value), "'", "''") + "'";
end

function restorePath(sourcePath, removePath)
if removePath && contains(path, sourcePath), rmpath(sourcePath); end
end

function closeConnection(conn)
if isopen(conn), close(conn); end
end

function removeTree(workspace)
if isfolder(workspace), rmdir(workspace, "s"); end
end
