function demonstration = mupet_import_demo(options)
%MUPET_IMPORT_DEMO Demonstrate the MUPET import path end to end.
%
% DEMONSTRATION = MUPET_IMPORT_DEMO() establishes one project recording through
% the real project-intake path, generates a small MUPET per-syllable CSV and its
% native config.csv, maps and previews the CSV, plans and applies the import with
% the public MUPET importer, and returns relational read-back tables covering run
% and artifact provenance, captured settings, syllable detections, native and
% canonical measurements, and the preserved terminal inter-syllable NA. It then
% reruns the identical import, relocates the artifacts under a second absolute
% root, and imports a small DeepSqueak export onto the same recording to show the
% two extractors coexisting.
%
% Every input is generated under the system temporary directory and removed
% before this function returns. No private data is involved and no database edit
% is made by hand.
%
% The flow is:
%
%   synthetic source tree
%       -> project-input JSON profile
%       -> source_mapping.parse + preview
%       -> vawlume.ingest.project(..., Apply=true)
%       -> synthetic MUPET per-syllable .csv + native config.csv
%       -> vawlume.ingest.mupetExport + source_mapping.preview
%       -> vawlume.ingest.mupet (plan)
%       -> vawlume.ingest.mupet (Apply=true)
%       -> relational read-back
%       -> unchanged rerun, artifact relocation, DeepSqueak co-residence
%
% Name-value options:
%   Print     print a concise developer-facing summary (default true)
%   RepoRoot  repository root; inferred from this file's location by default
%
% What this demonstrates is bounded. It covers the MUPET per-syllable CSV for the
% tracked v2.1 output mapping profile, and nothing else: not every MUPET version,
% not dataset summary or repertoire exports, not native .mat parsing, and not
% cross-extractor matching, consensus, or consilience. The co-residence appendix
% shows two populations sharing one recording; it computes no correspondence
% between them, because none is implemented.
%
% Two MUPET behaviours shown here are contract rather than omission. Settings
% provenance is required to apply, and a MUPET import creates zero curation rows
% and zero classification assignments, because the per-syllable CSV exports no
% review state, no class label, and no detector score.
%
% From the repository root:
%
%   addpath("examples")
%   mupet_import_demo
%
% See also VAWLUME.INGEST.MUPET, DEEPSQUEAK_IMPORT_DEMO, PROJECT_INTAKE_DEMO.

arguments
    options.Print (1,1) logical = true
    options.RepoRoot (1,1) string = ""
end

repoRoot = normalizedRepoRoot(options.RepoRoot);
sourcePath = fullfile(repoRoot, "src");
removeSourcePath = ~pathContains(sourcePath);
if removeSourcePath
    addpath(sourcePath);
end
cleanupPath = onCleanup(@() restoreSourcePath(sourcePath, removeSourcePath));

workspaceRoot = fullfile(tempdir, ...
    "VAWLUME mupet import demo " + string(java.util.UUID.randomUUID));
mkdir(workspaceRoot);
cleanupWorkspace = onCleanup(@() removeTree(workspaceRoot));
databasePath = fullfile(workspaceRoot, "mupet_import_demo.sqlite");
conn = sqlite(char(databasePath), "create");
cleanupConnection = onCleanup(@() closeConnection(conn));

vawlume.db.applySchema(conn, fullfile(repoRoot, "schema", "schema.sql"));
vawlume.db.registerBuiltinSemantics(conn, repoRoot);

% --- Phase 3: establish one project recording through the public path --------
projectProfilePath = fullfile(repoRoot, "config", "01_mapping_profiles", ...
    "project_inputs", "project_input_source_mapping_examples.json");
sourceRoot = fullfile(workspaceRoot, "project");
audioPath = fullfile(sourceRoot, "control", "mouse_001", "baseline", ...
    "001_baseline_1.wav");
makeParentFolder(audioPath);
writeText(audioPath, "synthetic audio stand-in; no recorded sound is involved");

projectIR = vawlume.source_mapping.parse(projectProfilePath, sourceRoot, ...
    ProfileId="example.project.mouse_courtship.folder_driven", RepoRoot=repoRoot);
projectPreview = vawlume.source_mapping.preview(projectIR);
intake = vawlume.ingest.project(conn, projectIR, struct( ...
    project_key="demo_mupet_import", ...
    project_name="MUPET import demonstration", ...
    description="Disposable Phase 5 demonstration project."), Apply=true, ...
    ProfileLinkagePath=fullfile(repoRoot, "config", "04_examples", ...
    "profile_linkage_example.json"), RepoRoot=repoRoot);

recording = fetch(conn, ...
    "SELECT r.recording_id, IFNULL(r.native_recording_id,'') AS native_recording_id, " + ...
    "IFNULL(sf.relative_path,'') AS source_relative_path " + ...
    "FROM recordings r JOIN source_files sf ON sf.source_file_id = r.source_file_id");
recordingId = double(recording.recording_id(1));

% --- Phase 5: generate a deterministic per-syllable CSV and its config -------
artifactRoot = fullfile(workspaceRoot, "mupet");
exportPath = fullfile(artifactRoot, "CSV", "MOUSE001_BASELINE.csv");
makeParentFolder(exportPath);
writecell(demonstrationExport(), exportPath);

% Settings are generated as demonstration inputs, not copied from any published
% default. MUPET reprocesses a recording when its configuration changes, so the
% importer refuses to apply without this evidence and substitutes nothing.
configPath = fullfile(artifactRoot, "config.csv");
writeText(configPath, strjoin(demonstrationConfigLines(), newline) + newline);

% The processed .mat is registered and hashed as native provenance. It is never
% parsed, and it is never accepted in place of the settings above.
nativePath = fullfile(artifactRoot, "mat", "MOUSE001_BASELINE.mat");
writeText(nativePath, "synthetic stand-in for MUPET processed state; never parsed");

runSpec = struct( ...
    run_key="demo_mupet_run_1", ...
    extractor_version="2.1", ...
    run_label="Demonstration MUPET segmentation run", ...
    settings=struct(config_path=configPath, relative_path="config.csv"), ...
    native_artifact=struct(artifact_path=nativePath, ...
        relative_path="mat/MOUSE001_BASELINE.mat"), ...
    dataset=struct(workspace_name="demo_workspace", dataset_name="demo_dataset"));

% --- Adapter, IR, and preview before any database write ---------------------
adapter = vawlume.ingest.mupetExport(exportPath, RepoRoot=repoRoot, ...
    ArtifactRoot=artifactRoot, ExtractorVersion="2.1", ...
    SettingsConfigPath=configPath, SettingsArtifactRoot=artifactRoot, ...
    SettingsRelativePath="config.csv");
adapterPreview = vawlume.source_mapping.preview(adapter.ir);

recordingRef = struct(recording_id=recordingId);
plan = vawlume.ingest.mupet(conn, exportPath, recordingRef, runSpec, ...
    RepoRoot=repoRoot, ArtifactRoot=artifactRoot);
imported = vawlume.ingest.mupet(conn, exportPath, recordingRef, runSpec, ...
    RepoRoot=repoRoot, ArtifactRoot=artifactRoot, Apply=true);

% --- Rerun and relocation ---------------------------------------------------
beforeRerun = scientificInventory(conn);
rerun = vawlume.ingest.mupet(conn, exportPath, recordingRef, runSpec, ...
    RepoRoot=repoRoot, ArtifactRoot=artifactRoot, Apply=true);
rerunSummary = struct( ...
    committed=rerun.committed, ...
    extraction_run_action=rerun.extraction_run.action, ...
    extraction_run_id_stable=rerun.extraction_run.extraction_run_id == ...
        imported.extraction_run.extraction_run_id, ...
    detections_created=rerun.applied_counts.detections, ...
    detections_reused=rerun.detections.detections_reuse, ...
    measurements_created=rerun.applied_counts.event_measurements, ...
    measurements_reused=rerun.detections.measurements_reuse, ...
    curation_rows_expected=rerun.detections.curation_rows_expected, ...
    classification_rows_expected=rerun.detections.classification_rows_expected, ...
    scientific_rows_unchanged=isequal(scientificInventory(conn), beforeRerun));

relocatedRoot = fullfile(workspaceRoot, "relocated");
relocatedExport = fullfile(relocatedRoot, "CSV", "MOUSE001_BASELINE.csv");
relocatedConfig = fullfile(relocatedRoot, "config.csv");
relocatedNative = fullfile(relocatedRoot, "mat", "MOUSE001_BASELINE.mat");
copyTo(exportPath, relocatedExport);
copyTo(configPath, relocatedConfig);
copyTo(nativePath, relocatedNative);
relocatedSpec = runSpec;
relocatedSpec.settings.config_path = relocatedConfig;
relocatedSpec.native_artifact.artifact_path = relocatedNative;
relocated = vawlume.ingest.mupet(conn, relocatedExport, recordingRef, ...
    relocatedSpec, RepoRoot=repoRoot, ArtifactRoot=relocatedRoot, Apply=true);
storedArtifactPath = scalarText(conn, ...
    "SELECT path_or_uri FROM artifacts WHERE artifact_type = 'extractor_event_export'");
relocationSummary = struct( ...
    committed=relocated.committed, ...
    extraction_run_action=relocated.extraction_run.action, ...
    artifact_actions=strjoin(sort(string(relocated.artifacts.action)), ", "), ...
    runtime_path_changed=relocated.export.runtime_path ~= imported.export.runtime_path, ...
    stored_portable_path=storedArtifactPath, ...
    scientific_rows_unchanged=isequal(scientificInventory(conn), beforeRerun));

% --- Co-residence appendix: a DeepSqueak run on the same recording ----------
% This shows two extractor populations sharing one recording. It deliberately
% computes no candidate pairs, no overlap, and no consensus: matching is Phase 6
% and does not exist yet.
deepsqueakSummary = importDeepSqueak(conn, workspaceRoot, repoRoot, recordingRef);
coResidence = coResidenceRows(conn, recordingId);
crossExtractorConcepts = broadConceptRows(conn);

inventory = scientificInventory(conn);
foreignKeyViolations = fetch(conn, "PRAGMA foreign_key_check");

demonstration = struct( ...
    architecture=[ ...
        "synthetic project source tree"; ...
        "project intake with tracked device/setup linkage"; ...
        "synthetic MUPET per-syllable CSV and native config.csv"; ...
        "adapter read + source_mapping IR + dry-run preview"; ...
        "extraction run/artifact/settings provenance"; ...
        "syllable detections and native/canonical measurements"; ...
        "explicit terminal interval missingness"; ...
        "idempotent relational read-back"], ...
    boundaries=prototypeBoundaries(), ...
    project_intake=struct( ...
        status=intake.status, committed=intake.committed, ...
        project_id=intake.project_id, ...
        preview_verdict=projectPreview.verdict, ...
        recording_id=recordingId, ...
        native_recording_id=string(recording.native_recording_id(1)), ...
        source_relative_path=string(recording.source_relative_path(1))), ...
    recording_context=recordingContextRows(conn, recordingId), ...
    adapter_summary=struct( ...
        row_count=adapter.artifact.row_count, ...
        column_count=adapter.artifact.column_count, ...
        lexical_columns=joinText(adapter.artifact.lexical_columns), ...
        checksum_sha256=shortHash(adapter.artifact.checksum_sha256), ...
        extractor_version_status=adapter.extractor_version.status, ...
        adapter_errors=adapter.adapter_error_count, ...
        adapter_warnings=adapter.adapter_warning_count, ...
        valid_for_ingest=adapter.valid_for_ingest), ...
    preview_summary=struct( ...
        verdict=adapterPreview.verdict, ...
        ir_value_count=height(adapter.ir.values), ...
        ir_record_count=height(adapter.ir.records), ...
        ir_issue_count=height(adapter.ir.issues), ...
        ir_issue_codes=joinText(unique(string(adapter.ir.issues.code)))), ...
    settings_summary=settingsSummary(imported, adapter), ...
    settings_capture=adapter.settings.entries(:, ["native_name", "raw_value", ...
        "canonical_setting", "native_unit", "status"]), ...
    import_summary=struct( ...
        ir_valid=imported.plan.export.ir.valid_for_ingest, ...
        ir_source_rows=imported.export.row_count, ...
        plan_status=plan.status, ...
        plan_conflicts=numel(plan.conflicts), ...
        planned_detections=plan.detections.planned, ...
        planned_measurements=plan.detections.measurements_create, ...
        apply_status=imported.status, ...
        committed=imported.committed, ...
        provenance_complete=imported.plan.provenance_complete, ...
        validation_valid=imported.validation.is_valid, ...
        validation_warnings=height(imported.validation.warnings)), ...
    planned_events=plan.events, ...
    validation=imported.validation, ...
    extraction_run_provenance=extractionRunRows(conn), ...
    artifact_provenance=artifactRows(conn), ...
    detections=detectionRows(conn), ...
    measurements=measurementRows(conn), ...
    interval_evidence=intervalRows(conn), ...
    capability_absence=capabilityAbsence(conn, imported), ...
    rerun=rerunSummary, ...
    relocation=relocationSummary, ...
    deepsqueak_appendix=deepsqueakSummary, ...
    co_residence=coResidence, ...
    cross_extractor_concepts=crossExtractorConcepts, ...
    database_inventory=inventory, ...
    foreign_key_violations=foreignKeyViolations, ...
    workspace_root=workspaceRoot, database_path=databasePath, ...
    temporary_artifacts_removed=false);

close(conn);
clear cleanupConnection
removeTree(workspaceRoot);
clear cleanupWorkspace
demonstration.temporary_artifacts_removed = ...
    ~isfolder(workspaceRoot) && ~isfile(databasePath);

if options.Print
    printDemonstration(demonstration);
end
clear cleanupPath
end

% ------------------------------------------------------- synthetic input ---

function cells = demonstrationExport()
%DEMONSTRATIONEXPORT Four deterministic syllables in the tracked v2.1 CSV shape.
%
% Values are chosen to be checkable by eye rather than to resemble any organism.
% Syllables 1, 3, and 4 export a duration that agrees with their boundaries;
% syllable 2 exports 38 ms against a 40 ms boundary span, which is what a
% pre-noise-reduction duration legitimately does and is stored as exported.
% Syllable 4 carries the terminal inter-syllable NA. Each bandwidth equals that
% syllable's own maximum minus its own minimum, so the profile's consistency
% check has something real to evaluate.
headers = {'Syllable number', 'Syllable start time (sec)', ...
    'Syllable end time (sec)', 'inter-syllable interval (sec)', ...
    'syllable duration (msec)', 'starting frequency (kHz)', ...
    'final frequency (kHz)', 'minimum frequency (kHz)', ...
    'maximum frequency (kHz)', 'mean frequency (kHz)', ...
    'frequency bandwidth (kHz)', 'total syllable energy (dB)', ...
    'peak syllable amplitude (dB)'};
cells = [
    headers
    {1, 10.000, 10.050, 0.150, 50, 55, 70, 50, 80, 65, 30, 12.0, -18}
    {2, 10.200, 10.240, 0.260, 38, 54, 69, 52, 78, 64, 26, 11.0, -19}
    {3, 10.500, 10.560, 0.240, 60, 56, 71, 48, 82, 66, 34, 10.0, -20}
    {4, 10.800, 10.835, 'NA',  35, 53, 68, 51, 79, 63, 28,  9.0, -21}
];
end

function lines = demonstrationConfigLines()
%DEMONSTRATIONCONFIGLINES The complete supported native key set, synthetic values.
%
% Generated as demonstration input. No publication default is reproduced here,
% and the importer substitutes nothing when a key is absent.
lines = ["noise-reduction,5"; "minimum-syllable-duration,008"; ...
    "maximum-syllable-duration,200"; "minimum-syllable-total-energy,-15"; ...
    "minimum-syllable-peak-amplitude,-25"; "minimum-syllable-distance,5"; ...
    "sample-frequency,250000"; "minimum-usv-frequency,30000"; ...
    "maximum-usv-frequency,120000"; "number-filterbank-filters,64"; ...
    "filterbank-type,1"];
end

function cells = deepsqueakExportCells()
%DEEPSQUEAKEXPORTCELLS Two calls, only enough to show co-residence.
headers = {'File', 'ID', 'Label', 'Accepted', 'Score', 'Begin Time (s)', ...
    'End Time (s)', 'Call Length (s)', 'Principle Frequency (kHz)', ...
    'Low Freq (kHz)', 'High Freq (kHz)', 'Delta Freq (kHz)', ...
    'Frequency Standard Deviation (kHz)', 'Slope (kHz/s)', 'Sinuosity', ...
    'Mean Power (dB/Hz)', 'Tonality', 'Peak Freq (kHz)'};
detectionFile = 'synthetic/deepsqueak/MOUSE001_BASELINE_detections.mat';
cells = [
    headers
    {detectionFile, 1, 'class_a', 1, 0.9134, 10.004, 10.052, 0.048, ...
        62.4, 50.5, 80.5, 30.0, 3.2, -120.5, 1.12, -71.4, 0.78, 63.0}
    {detectionFile, 2, 'class_b', 0, 0.2107, 10.795, 10.840, 0.045, ...
        63.5, 51.0, 79.5, 28.5, 4.4, -8.25, 1.40, -69.3, 0.69, 64.2}
];
end

function value = prototypeBoundaries()
value = [ ...
    "Supported: the MUPET per-syllable CSV for the tracked v2.1 output mapping profile."; ...
    "Not supported: dataset summary, repertoire, or refinement exports."; ...
    "Not supported: native .mat parsing; the processed file is hashed, never read."; ...
    "Not supported: cross-extractor matching, consensus, or consilience."; ...
    "Contract, not omission: settings provenance is required to apply."; ...
    "Contract, not omission: zero curation rows and zero classification assignments."; ...
    "The exported duration is pre-noise-reduction and is never recomputed from the boundaries."; ...
    "The terminal inter-syllable NA is stored as missing and never becomes zero."];
end

% ------------------------------------------------- DeepSqueak co-residence ---

function summary = importDeepSqueak(conn, workspaceRoot, repoRoot, recordingRef)
artifactRoot = fullfile(workspaceRoot, "deepsqueak");
exportPath = fullfile(artifactRoot, "exports", "MOUSE001_BASELINE_Stats.xlsx");
makeParentFolder(exportPath);
writecell(deepsqueakExportCells(), exportPath);

settingsPath = fullfile(artifactRoot, "deepsqueak_detection_settings.json");
writeText(settingsPath, jsonencode(struct( ...
    profile=struct(id="demo.deepsqueak.settings.v1", ...
    name="Demonstration DeepSqueak detection settings", ...
    kind="extractor_settings", profile_version="1.0.0"), ...
    detection=struct(score_threshold=0.15, frequency_range_khz=[15, 115]))));

runSpec = struct(run_key="demo_deepsqueak_run_1", extractor_version="3.2.1", ...
    run_label="Demonstration DeepSqueak detection run", ...
    settings=struct(profile_path=settingsPath));
result = vawlume.ingest.deepsqueak(conn, exportPath, recordingRef, runSpec, ...
    RepoRoot=repoRoot, ArtifactRoot=artifactRoot, Apply=true);
summary = struct(status=result.status, committed=result.committed, ...
    run_key=result.extraction_run.run_key, ...
    detections=result.applied_counts.detections, ...
    measurements=result.applied_counts.event_measurements);
end

function rows = coResidenceRows(conn, recordingId)
rows = fetch(conn, ...
    "SELECT c.extractor_name, c.extractor_version, c.extraction_run_key, " + ...
    "COUNT(*) AS detections, " + ...
    "SUM(CASE WHEN c.detection_score IS NULL THEN 0 ELSE 1 END) AS scored, " + ...
    "(SELECT COUNT(*) FROM curation_events ce JOIN detections d2 " + ...
    "ON d2.detection_id = ce.detection_id " + ...
    "WHERE d2.extraction_run_id = c.extraction_run_id) AS curation_rows, " + ...
    "(SELECT COUNT(*) FROM classification_assignments ca JOIN detections d3 " + ...
    "ON d3.detection_id = ca.detection_id " + ...
    "WHERE d3.extraction_run_id = c.extraction_run_id) AS class_assignments " + ...
    "FROM v_detection_core c WHERE c.recording_id = " + string(recordingId) + " " + ...
    "GROUP BY c.extraction_run_id ORDER BY c.extractor_name");
end

function rows = broadConceptRows(conn)
%BROADCONCEPTROWS Which broad canonical concepts each extractor populates.
%
% Availability, not comparison. No pair, overlap, or agreement is computed
% anywhere in this demonstration. frequency_center is included deliberately: it
% is the one concept in this list that only MUPET populates by canonical name,
% because DeepSqueak's contour median is registered under its own canonical name
% rather than asserted to be the same statistic as a filterbank mean.
concepts = ["call_start_time", "call_end_time", "call_duration", ...
    "frequency_min", "frequency_max", "frequency_bandwidth", "frequency_center"];
rows = fetch(conn, ...
    "SELECT m.canonical_name, c.extractor_name, m.native_name, " + ...
    "m.native_unit, m.canonical_unit, m.transform_key " + ...
    "FROM v_event_measurements_long m " + ...
    "JOIN v_detection_core c ON c.detection_id = m.detection_id " + ...
    "WHERE m.canonical_name IN ('" + strjoin(concepts, "','") + "') " + ...
    "GROUP BY m.canonical_name, c.extractor_name " + ...
    "ORDER BY m.canonical_name, c.extractor_name");
end

% -------------------------------------------------------- read-back rows ---

function rows = recordingContextRows(conn, recordingId)
rows = fetch(conn, ...
    "SELECT project_key, entity_type, IFNULL(canonical_role,'') AS canonical_role, " + ...
    "entity_native_id, link_type, " + ...
    "CASE WHEN role_label IS NULL OR role_label = '' THEN '-' ELSE role_label END AS role_label " + ...
    "FROM v_recording_entity_context WHERE recording_id = " + ...
    string(recordingId) + " ORDER BY entity_type, entity_native_id, link_type");
end

function summary = settingsSummary(imported, adapter)
summary = struct( ...
    mode=imported.settings.mode, ...
    status=imported.settings.status, ...
    capture_status=adapter.settings.status, ...
    capture_complete=adapter.settings.complete, ...
    declared_keys_captured=nnz(adapter.settings.entries.declared), ...
    unrecognized_keys=nnz(adapter.settings.entries.status == "unrecognized"), ...
    missing_required_keys=numel(adapter.settings.missing_required_keys), ...
    source_artifact=adapter.settings.source_artifact.relative_path, ...
    source_checksum=shortHash(adapter.settings.source_checksum_sha256), ...
    structured_capture_checksum=shortHash( ...
        adapter.settings.structured_capture_checksum_sha256), ...
    lineage_derivation=string(adapter.settings.lineage.derivation), ...
    profile_key=imported.settings.profile_key, ...
    profile_version=imported.settings.version_label);
end

function rows = extractionRunRows(conn)
%EXTRACTIONRUNROWS Run identity, exact versions, and where settings actually live.
%
% The settings column distinguishes three genuinely different states rather than
% collapsing two of them. A profile key means a VAWLUME settings profile version
% is linked to the run. `<native settings artifact>` means the exact native
% config.csv is registered, hashed, and faithfully captured, but the schema has
% no clean edge from that source artifact to a synthesized profile version, so
% none is invented. `<not recoverable>` means the settings are genuinely lost,
% which the MUPET contract never permits at apply time.
rows = fetch(conn, ...
    "SELECT er.run_key, sf.filename AS recording_source, e.extractor_name, " + ...
    "ev.version_label AS extractor_version, " + ...
    "ocp.profile_key AS output_mapping_profile, " + ...
    "ocv.version_label AS profile_version, " + ...
    "substr(ocv.checksum_sha256, 1, 12) AS profile_checksum, " + ...
    "CASE WHEN scp.profile_key IS NOT NULL THEN scp.profile_key " + ...
    "WHEN EXISTS (SELECT 1 FROM extraction_run_artifacts ra " + ...
    "JOIN artifacts a ON a.artifact_id = ra.artifact_id " + ...
    "WHERE ra.extraction_run_id = er.extraction_run_id " + ...
    "AND a.artifact_type = 'extractor_settings') " + ...
    "THEN '<native settings artifact>' " + ...
    "ELSE '<not recoverable>' END AS settings_provenance, " + ...
    "substr(IFNULL(scv.checksum_sha256, ''), 1, 12) AS settings_profile_checksum " + ...
    "FROM extraction_runs er " + ...
    "JOIN extraction_run_inputs eri ON eri.extraction_run_id = er.extraction_run_id " + ...
    "JOIN recordings r ON r.recording_id = eri.recording_id " + ...
    "JOIN source_files sf ON sf.source_file_id = r.source_file_id " + ...
    "JOIN extractor_versions ev ON ev.extractor_version_id = er.extractor_version_id " + ...
    "JOIN extractors e ON e.extractor_id = ev.extractor_id " + ...
    "JOIN config_profile_versions ocv ON ocv.profile_version_id = er.output_mapping_profile_version_id " + ...
    "JOIN config_profiles ocp ON ocp.profile_id = ocv.profile_id " + ...
    "LEFT JOIN config_profile_versions scv ON scv.profile_version_id = er.settings_profile_version_id " + ...
    "LEFT JOIN config_profiles scp ON scp.profile_id = scv.profile_id " + ...
    "ORDER BY er.run_key");
end

function rows = artifactRows(conn)
rows = fetch(conn, ...
    "SELECT e.extractor_name, ra.artifact_role, a.artifact_type, a.path_or_uri, " + ...
    "IFNULL(a.file_format,'') AS file_format, a.is_native, " + ...
    "substr(IFNULL(a.checksum_sha256,''), 1, 12) AS checksum " + ...
    "FROM extraction_run_artifacts ra " + ...
    "JOIN artifacts a ON a.artifact_id = ra.artifact_id " + ...
    "JOIN extraction_runs er ON er.extraction_run_id = ra.extraction_run_id " + ...
    "JOIN extractor_versions ev ON ev.extractor_version_id = er.extractor_version_id " + ...
    "JOIN extractors e ON e.extractor_id = ev.extractor_id " + ...
    "ORDER BY e.extractor_name, ra.artifact_role");
end

function rows = detectionRows(conn)
%DETECTIONROWS MUPET syllables with the exported duration beside the boundaries.
%
% The exported pre-noise-reduction duration is shown next to, never in place of,
% the boundary span. They are different quantities and the import keeps both.
rows = fetch(conn, ...
    "SELECT c.detection_id, c.native_event_id, c.start_time_s, c.end_time_s, " + ...
    "c.duration_s AS boundary_span_s, em.canonical_value_real AS exported_duration_s, " + ...
    "IFNULL(em.operational_variant,'') AS duration_variant, " + ...
    "CASE WHEN c.detection_score IS NULL THEN '<none exported>' " + ...
    "ELSE CAST(c.detection_score AS TEXT) END AS detection_score " + ...
    "FROM v_detection_core c " + ...
    "JOIN event_measurements em ON em.detection_id = c.detection_id " + ...
    "JOIN extractor_features xf ON xf.extractor_feature_id = em.extractor_feature_id " + ...
    "WHERE c.extractor_name = 'MUPET' AND xf.native_name = 'syllable duration (msec)' " + ...
    "ORDER BY CAST(c.native_event_id AS INTEGER)");
end

function rows = measurementRows(conn)
% A compact representative set: the unit-transformed duration with its
% operational variant, three frequency features, and one energy and one
% amplitude measure. Missing values are rendered as missing, because printing a
% numeric zero here would display exactly the fabricated value the storage
% contract exists to prevent.
rows = fetch(conn, ...
    "SELECT d.native_event_id, m.native_name, " + ...
    "CASE WHEN m.native_value_real IS NULL THEN '<missing>' " + ...
    "ELSE CAST(m.native_value_real AS TEXT) END AS native_value, " + ...
    "IFNULL(m.native_unit,'') AS native_unit, " + ...
    "IFNULL(m.canonical_name,'') AS canonical_feature, " + ...
    "CASE WHEN m.canonical_value_real IS NULL THEN '<missing>' " + ...
    "ELSE CAST(m.canonical_value_real AS TEXT) END AS canonical_value, " + ...
    "IFNULL(m.canonical_unit,'') AS canonical_unit, " + ...
    "IFNULL(m.transform_key,'') AS transform_key, " + ...
    "IFNULL(m.operational_variant,'') AS operational_variant, " + ...
    "IFNULL(m.derivation_stage,'') AS derivation_stage " + ...
    "FROM v_event_measurements_long m " + ...
    "JOIN detections d ON d.detection_id = m.detection_id " + ...
    "JOIN v_detection_core c ON c.detection_id = d.detection_id " + ...
    "WHERE c.extractor_name = 'MUPET' AND d.native_event_id = '1' " + ...
    "AND m.native_name IN ('syllable duration (msec)', 'minimum frequency (kHz)', " + ...
    "'maximum frequency (kHz)', 'mean frequency (kHz)', " + ...
    "'total syllable energy (dB)', 'peak syllable amplitude (dB)') " + ...
    "ORDER BY m.native_name");
end

function rows = intervalRows(conn)
%INTERVALROWS The exported inter-syllable interval for every syllable.
%
% The terminal syllable has no following syllable. Its exported NA is kept as
% the raw token with no typed value, rather than becoming a zero interval or a
% VAWLUME-computed substitute.
rows = fetch(conn, ...
    "SELECT d.native_event_id, em.native_value_type, " + ...
    "IFNULL(em.native_raw_token,'') AS native_raw_token, " + ...
    "CASE WHEN em.native_value_real IS NULL THEN '<missing>' " + ...
    "ELSE CAST(em.native_value_real AS TEXT) END AS native_value, " + ...
    "CASE WHEN em.canonical_value_real IS NULL THEN '<missing>' " + ...
    "ELSE CAST(em.canonical_value_real AS TEXT) END AS canonical_value, " + ...
    "IFNULL(xf.derivation_stage,'') AS derivation_stage " + ...
    "FROM event_measurements em " + ...
    "JOIN detections d ON d.detection_id = em.detection_id " + ...
    "JOIN extractor_features xf ON xf.extractor_feature_id = em.extractor_feature_id " + ...
    "WHERE xf.native_name = 'inter-syllable interval (sec)' " + ...
    "ORDER BY CAST(d.native_event_id AS INTEGER)");
end

function value = capabilityAbsence(conn, imported)
%CAPABILITYABSENCE State the two zeros positively rather than by omission.
value = struct( ...
    mupet_curation_rows=extractorScopedCount(conn, "curation_events", "MUPET"), ...
    mupet_classification_assignments=extractorScopedCount(conn, ...
        "classification_assignments", "MUPET"), ...
    mupet_detections_with_score=scalar(conn, ...
        "SELECT COUNT(*) AS n FROM v_detection_core " + ...
        "WHERE extractor_name = 'MUPET' AND detection_score IS NOT NULL"), ...
    curation_rows_expected=imported.detections.curation_rows_expected, ...
    classification_rows_expected=imported.detections.classification_rows_expected, ...
    reason=[ ...
        "The per-syllable CSV exports no review state, no class label, and no detector score."; ...
        "Surviving MUPET's duration, energy, and amplitude filtering is not a reviewed state."; ...
        "Those filter thresholds are recorded once as run-level settings provenance."]);
end

function value = extractorScopedCount(conn, tableName, extractorName)
value = scalar(conn, ...
    "SELECT COUNT(*) AS n FROM " + tableName + " t " + ...
    "JOIN v_detection_core c ON c.detection_id = t.detection_id " + ...
    "WHERE c.extractor_name = '" + extractorName + "'");
end

function value = scientificInventory(conn)
tables = ["extraction_runs", "extraction_run_inputs", "extraction_run_artifacts", ...
    "artifacts", "detections", "event_measurements", "curation_events", ...
    "classification_runs", "classification_classes", "classification_assignments", ...
    "candidate_pairs", "match_groups", "consensus_events", "consilience_assessments"];
value = struct();
for name = tables
    value.(name) = scalar(conn, "SELECT COUNT(*) AS n FROM " + name);
end
end

% -------------------------------------------------------------- plumbing ---

function value = scalar(conn, sql)
rows = fetch(conn, sql);
value = double(rows.n(1));
end

function value = scalarText(conn, sql)
rows = fetch(conn, sql);
value = string(rows{1, 1});
end

function value = shortHash(text)
value = string(text);
if strlength(value) > 12
    value = extractBefore(value, 13);
end
end

function value = joinText(items)
value = "";
items = string(items);
if ~isempty(items)
    value = strjoin(items(:)', ", ");
end
end

function printDemonstration(value)
disp("VAWLUME MUPET IMPORT DEMONSTRATION")
disp(strjoin(value.architecture, " -> "))
fprintf("\nProject intake: %s (project %d, recording %d), preview %s\n", ...
    value.project_intake.status, value.project_intake.project_id, ...
    value.project_intake.recording_id, value.project_intake.preview_verdict);
disp("Recording context:")
disp(value.recording_context)
fprintf("Adapter: %d rows x %d columns, lexical column(s) [%s], version %s, " + ...
    "%d error(s)/%d warning(s), valid %d\n", ...
    value.adapter_summary.row_count, value.adapter_summary.column_count, ...
    value.adapter_summary.lexical_columns, ...
    value.adapter_summary.extractor_version_status, ...
    value.adapter_summary.adapter_errors, value.adapter_summary.adapter_warnings, ...
    value.adapter_summary.valid_for_ingest);
fprintf("Preview: %s over %d IR values in %d record(s), %d issue(s) [%s]\n", ...
    value.preview_summary.verdict, value.preview_summary.ir_value_count, ...
    value.preview_summary.ir_record_count, value.preview_summary.ir_issue_count, ...
    value.preview_summary.ir_issue_codes);
fprintf("Settings: mode %s, %s, %d declared key(s) captured, %d missing, " + ...
    "source %s (%s), structured capture %s, lineage %s\n", ...
    value.settings_summary.mode, value.settings_summary.status, ...
    value.settings_summary.declared_keys_captured, ...
    value.settings_summary.missing_required_keys, ...
    value.settings_summary.source_artifact, value.settings_summary.source_checksum, ...
    value.settings_summary.structured_capture_checksum, ...
    value.settings_summary.lineage_derivation);
disp("Captured native settings:")
disp(value.settings_capture)
fprintf("Import: IR valid %d over %d source rows; plan %s with %d conflict(s), " + ...
    "%d syllable(s)/%d measurement(s); apply %s; validation valid %d with " + ...
    "%d warning(s)\n", ...
    value.import_summary.ir_valid, value.import_summary.ir_source_rows, ...
    value.import_summary.plan_status, value.import_summary.plan_conflicts, ...
    value.import_summary.planned_detections, value.import_summary.planned_measurements, ...
    value.import_summary.apply_status, value.import_summary.validation_valid, ...
    value.import_summary.validation_warnings);
% The duration warning below is expected on correct MUPET data, not a defect.
% The exported duration is pre-noise-reduction and the boundaries are not, so
% they legitimately disagree; both are stored exactly as exported.
if ~isempty(value.validation.warnings)
    disp("Profile-declared validation warnings (evidence kept, nothing repaired):")
    disp(value.validation.warnings)
end
if ~isempty(value.validation.unevaluated_checks)
    fprintf("Profile checks declared but not yet evaluated: %s\n", ...
        strjoin(value.validation.unevaluated_checks, ", "));
end
disp("Extraction-run provenance:")
disp(value.extraction_run_provenance)
disp("Artifact provenance:")
disp(value.artifact_provenance)
disp("MUPET syllables (exported duration beside the boundary span):")
disp(value.detections)
disp("Selected measurements (native evidence beside canonical form):")
disp(value.measurements)
disp("Inter-syllable interval, including the terminal NA:")
disp(value.interval_evidence)
fprintf("MUPET curation rows: %d\nMUPET classification assignments: %d\n", ...
    value.capability_absence.mupet_curation_rows, ...
    value.capability_absence.mupet_classification_assignments);
disp(value.capability_absence.reason)
fprintf("Rerun: %d created, %d reused detection(s); scientific rows unchanged: %d\n", ...
    value.rerun.detections_created, value.rerun.detections_reused, ...
    value.rerun.scientific_rows_unchanged);
fprintf("Relocation: run %s, artifacts [%s], stored portable path %s; unchanged: %d\n", ...
    value.relocation.extraction_run_action, value.relocation.artifact_actions, ...
    value.relocation.stored_portable_path, ...
    value.relocation.scientific_rows_unchanged);
disp("Co-residence on one recording (no correspondence is computed):")
disp(value.co_residence)
disp("Broad canonical concepts available by extractor:")
disp(value.cross_extractor_concepts)
fprintf("Matching rows created: %d candidate pair(s), %d match group(s), " + ...
    "%d consensus event(s), %d consilience assessment(s)\n", ...
    value.database_inventory.candidate_pairs, value.database_inventory.match_groups, ...
    value.database_inventory.consensus_events, ...
    value.database_inventory.consilience_assessments);
fprintf("Foreign-key violations: %d; temporary artifacts removed: %d\n", ...
    height(value.foreign_key_violations), value.temporary_artifacts_removed);
disp("Scope:")
disp(value.boundaries)
end

function copyTo(source, destination)
makeParentFolder(destination);
copyfile(source, destination);
end

function makeParentFolder(path)
parent = fileparts(path);
if ~isfolder(parent)
    mkdir(parent);
end
end

function writeText(path, text)
makeParentFolder(path);
fileId = fopen(path, "w");
if fileId < 0
    error("vawlume:examples:FileWriteFailed", ...
        "Could not open %s for writing.", path);
end
cleaner = onCleanup(@() fclose(fileId));
fprintf(fileId, "%s", text);
delete(cleaner);
end

function root = normalizedRepoRoot(root)
if strlength(root) > 0
    root = string(root);
    return
end
root = string(fileparts(fileparts(mfilename("fullpath"))));
end

function value = pathContains(target)
value = any(strcmp(strsplit(string(path), pathsep), target));
end

function restoreSourcePath(sourcePath, shouldRemove)
if shouldRemove && pathContains(sourcePath)
    rmpath(sourcePath);
end
end

function closeConnection(conn)
try
    close(conn);
catch
end
end

function removeTree(root)
%REMOVETREE Best-effort workspace removal.
%
% This also runs while an exception is unwinding, when the SQLite file may still
% be held briefly. Failing loudly here would bury the real error, so removal is
% retried and then reported through the returned struct rather than thrown.
for attempt = 1:5
    if ~isfolder(root)
        return
    end
    try
        rmdir(root, "s");
        return
    catch
        pause(0.2);
    end
end
end
