function demonstration = project_intake_demo(options)
%PROJECT_INTAKE_DEMO Demonstrate source mapping through relational read-back.
%
% DEMONSTRATION = PROJECT_INTAKE_DEMO() builds disposable source trees for
% all three shipped project-input profiles, validates and previews their
% source semantics, applies project intake, and returns compact recording and
% provenance tables. The mouse case also demonstrates exact rerun
% idempotency, root relocation, and tracked device/setup linkage.
%
% All source trees and the SQLite database are created under the system
% temporary directory and removed before this function returns.

arguments
    options.Print (1,1) logical = true
    options.RepoRoot (1,1) string = ""
end

repoRoot = normalizedRepoRoot(options.RepoRoot);
sourcePath = fullfile(repoRoot, "src");
removeSourcePath = ~pathContains(sourcePath);
if removeSourcePath
    addpath(sourcePath);
end
cleanupPath = onCleanup(@() restoreSourcePath(sourcePath, removeSourcePath));

profilePath = fullfile(repoRoot, "config", "01_mapping_profiles", ...
    "project_inputs", "project_input_source_mapping_examples.json");
[loaded, validation] = vawlume.source_mapping.loadProfile( ...
    profilePath, ExpectedKind="project_input", RepoRoot=repoRoot);

workspaceRoot = fullfile(tempdir, ...
    "VAWLUME project intake demo " + string(java.util.UUID.randomUUID));
mkdir(workspaceRoot);
cleanupWorkspace = onCleanup(@() removeTree(workspaceRoot));
databasePath = fullfile(workspaceRoot, "project_intake_demo.sqlite");
conn = sqlite(char(databasePath), "create");
cleanupConnection = onCleanup(@() closeConnection(conn));
vawlume.db.applySchema(conn, fullfile(repoRoot, "schema", "schema.sql"));

cases = demonstrationCases();
count = height(cases);
profileSummary = table( ...
    strings(count, 1), strings(count, 1), false(count, 1), ...
    strings(count, 1), strings(count, 1), NaN(count, 1), NaN(count, 1), ...
    zeros(count, 1), zeros(count, 1), zeros(count, 1), zeros(count, 1), ...
    VariableNames=["profile_key", "project_key", "profile_valid", ...
    "preview_verdict", "intake_status", "project_id", ...
    "ingestion_run_id", "source_count", "recording_count", ...
    "participant_count", "context_count"]);
previews = cell(count, 1);
manifests = cell(count, 1);
recordingContext = table();
intakeProvenance = table();
acquisitionProfiles = table();
mouseIR = struct();
mouseResult = struct();
mouseRoot = "";

for index = 1:count
    sourceRoot = fullfile(workspaceRoot, "source_" + string(index));
    mkdir(sourceRoot);
    touchFile(fullfile(sourceRoot, cases.relative_path(index)));
    ir = vawlume.source_mapping.parse(profilePath, sourceRoot, ...
        ProfileId=cases.profile_key(index), RepoRoot=repoRoot);
    preview = vawlume.source_mapping.preview(ir);
    spec = struct( ...
        project_key=cases.project_key(index), ...
        project_name=cases.project_name(index), ...
        description="Phase 3 project-intake demonstration.");
    if cases.use_linkage(index)
        result = vawlume.ingest.project(conn, ir, spec, Apply=true, ...
            ProfileLinkagePath=linkagePath(repoRoot), RepoRoot=repoRoot);
        mouseIR = ir;
        mouseResult = result;
        mouseRoot = sourceRoot;
    else
        result = vawlume.ingest.project(conn, ir, spec, Apply=true);
    end

    profileSummary.profile_key(index) = cases.profile_key(index);
    profileSummary.project_key(index) = cases.project_key(index);
    profileSummary.profile_valid(index) = validation.is_valid && ...
        ir.valid_for_ingest;
    profileSummary.preview_verdict(index) = preview.verdict;
    profileSummary.intake_status(index) = result.status;
    profileSummary.project_id(index) = result.project_id;
    profileSummary.ingestion_run_id(index) = result.ingestion_run_id;
    profileSummary.source_count(index) = projectCount( ...
        conn, "source_files", result.project_id);
    profileSummary.recording_count(index) = projectCount( ...
        conn, "recordings", result.project_id);
    profileSummary.participant_count(index) = linkCount( ...
        conn, result.project_id, "participant");
    profileSummary.context_count(index) = linkCount( ...
        conn, result.project_id, "context");
    previews{index} = preview;
    manifests{index} = result;

    recordingContext = appendRows(recordingContext, ...
        recordingContextRows(conn, result.project_id));
    intakeProvenance = appendRows(intakeProvenance, ...
        intakeProvenanceRows(conn, result.ingestion_run_id));
    acquisitionProfiles = appendRows(acquisitionProfiles, ...
        acquisitionProfileRows(conn, result.project_id));
end

idempotency = demonstrateIdempotency( ...
    conn, mouseIR, mouseResult, cases(1, :), repoRoot);
relocation = demonstrateRelocation( ...
    conn, mouseIR, mouseResult, mouseRoot, cases(1, :), ...
    profilePath, workspaceRoot, repoRoot);
inventory = databaseInventory(conn);
foreignKeyViolations = fetch(conn, "PRAGMA foreign_key_check");

demonstration = struct( ...
    architecture=[ ...
        "synthetic source tree"; ...
        "project-input JSON profile"; ...
        "source_mapping IR + preview"; ...
        "project intake result/manifest"; ...
        "SQLite project/entity/recording graph"; ...
        "relational read-back tables"], ...
    profile_bundle=struct( ...
        path=loaded.relative_path, profile_count=loaded.profile_count, ...
        validation_valid=validation.is_valid, ...
        validation_error_count=validation.error_count, ...
        checksum_sha256=loaded.checksum_sha256), ...
    profile_summary=profileSummary, previews={previews}, ...
    intake_manifests={manifests}, recording_context=recordingContext, ...
    intake_provenance=intakeProvenance, ...
    acquisition_profiles=acquisitionProfiles, ...
    idempotency=idempotency, relocation=relocation, ...
    database_inventory=inventory, ...
    foreign_key_violations=foreignKeyViolations, ...
    workspace_root=workspaceRoot, database_path=databasePath, ...
    temporary_artifacts_removed=false);

close(conn);
clear cleanupConnection
removeTree(workspaceRoot);
clear cleanupWorkspace
demonstration.temporary_artifacts_removed = ...
    ~isfolder(workspaceRoot) && ~isfile(databasePath);

if options.Print
    printDemonstration(demonstration);
end
clear cleanupPath
end

function value = demonstrationCases()
value = table( ...
    ["example.project.mouse_courtship.folder_driven"; ...
    "example.project.rat_self_admin.filename_driven"; ...
    "example.project.social_dyad.multi_subject"], ...
    ["demo_mouse_folder"; "demo_rat_filename"; "demo_social_dyad"], ...
    ["Folder-driven mouse demo"; "Filename-driven rat demo"; ...
    "Multi-subject dyad demo"], ...
    [string(fullfile("control", "mouse_001", "baseline", ...
    "001_baseline_1.wav")); "OXY_PR_R03_SA07_001.wav"; ...
    string(fullfile("cohort_01", "dyad_004", ...
    "D004_M012_F031_courtship.wav"))], ...
    [true; false; false], ...
    VariableNames=["profile_key", "project_key", "project_name", ...
    "relative_path", "use_linkage"]);
end

function value = demonstrateIdempotency(conn, ir, first, profileCase, repoRoot)
before = semanticSnapshot(conn, first.project_id);
auditBefore = auditCount(conn, first.project_id);
spec = projectSpec(profileCase);
second = vawlume.ingest.project(conn, ir, spec, Apply=true, ...
    ProfileLinkagePath=linkagePath(repoRoot), RepoRoot=repoRoot);
after = semanticSnapshot(conn, first.project_id);
auditAfter = auditCount(conn, first.project_id);
value = struct( ...
    semantic_counts_before=before, semantic_counts_after=after, ...
    semantic_graph_unchanged=isequal(before, after), ...
    source_ids_unchanged=isequal( ...
        first.source_ids(:, ["source_key", "source_file_id"]), ...
        second.source_ids(:, ["source_key", "source_file_id"])), ...
    recording_ids_unchanged=isequal( ...
        first.recording_ids(:, ["record_key", "recording_id"]), ...
        second.recording_ids(:, ["record_key", "recording_id"])), ...
    ingestion_runs_before=auditBefore, ...
    ingestion_runs_after=auditAfter, ...
    ingestion_run_increment=auditAfter - auditBefore, ...
    first_ingestion_run_id=first.ingestion_run_id, ...
    second_ingestion_run_id=second.ingestion_run_id, ...
    second_manifest=second);
end

function value = demonstrateRelocation( ...
        conn, originalIR, first, originalRoot, profileCase, ...
        profilePath, workspaceRoot, repoRoot)
relocatedRoot = fullfile(workspaceRoot, "source_relocated");
mkdir(relocatedRoot);
touchFile(fullfile(relocatedRoot, profileCase.relative_path));
relocatedIR = vawlume.source_mapping.parse(profilePath, relocatedRoot, ...
    ProfileId=profileCase.profile_key, RepoRoot=repoRoot);
originalPreview = vawlume.source_mapping.preview(originalIR);
relocatedPreview = vawlume.source_mapping.preview(relocatedIR);
before = semanticSnapshot(conn, first.project_id);
auditBefore = auditCount(conn, first.project_id);
relocatedResult = vawlume.ingest.project( ...
    conn, relocatedIR, projectSpec(profileCase), Apply=true, ...
    ProfileLinkagePath=linkagePath(repoRoot), RepoRoot=repoRoot);
after = semanticSnapshot(conn, first.project_id);
auditAfter = auditCount(conn, first.project_id);
value = struct( ...
    runtime_roots_differ=originalRoot ~= relocatedRoot, ...
    runtime_paths_differ=~isequal( ...
        originalIR.sources.runtime_path, relocatedIR.sources.runtime_path), ...
    portable_ir_equal=isequaln( ...
        withoutRuntimePaths(originalIR), withoutRuntimePaths(relocatedIR)), ...
    preview_equal=originalPreview.text == relocatedPreview.text, ...
    semantic_counts_before=before, semantic_counts_after=after, ...
    semantic_graph_unchanged=isequal(before, after), ...
    source_ids_unchanged=isequal( ...
        first.source_ids(:, ["source_key", "source_file_id"]), ...
        relocatedResult.source_ids(:, ["source_key", "source_file_id"])), ...
    recording_ids_unchanged=isequal( ...
        first.recording_ids(:, ["record_key", "recording_id"]), ...
        relocatedResult.recording_ids(:, ["record_key", "recording_id"])), ...
    ingestion_run_increment=auditAfter - auditBefore, ...
    relocated_ingestion_run_id=relocatedResult.ingestion_run_id, ...
    relocated_manifest=relocatedResult);
end

function value = projectSpec(profileCase)
value = struct( ...
    project_key=profileCase.project_key, ...
    project_name=profileCase.project_name, ...
    description="Phase 3 project-intake demonstration.");
end

function value = withoutRuntimePaths(value)
value.sources.runtime_path(:) = "";
end

function rows = recordingContextRows(conn, projectId)
rows = fetch(conn, ...
    "SELECT p.project_key, r.recording_id, " + ...
    "CASE WHEN r.native_recording_id IS NULL THEN '<not_authored>' " + ...
    "ELSE r.native_recording_id END AS native_recording_id, " + ...
    "sf.relative_path AS source_relative_path, " + ...
    "et.native_name AS entity_type, ee.native_id AS entity_native_id, " + ...
    "rel.link_type, CASE WHEN rel.role_label IS NULL THEN '<none>' " + ...
    "ELSE rel.role_label END AS role_label " + ...
    "FROM recordings r " + ...
    "JOIN projects p ON p.project_id = r.project_id " + ...
    "JOIN source_files sf ON sf.source_file_id = r.source_file_id " + ...
    "JOIN recording_entity_links rel ON rel.recording_id = r.recording_id " + ...
    "JOIN experimental_entities ee ON ee.entity_id = rel.entity_id " + ...
    "JOIN entity_types et ON et.entity_type_id = ee.entity_type_id " + ...
    "WHERE r.project_id = " + string(projectId) + ...
    " ORDER BY r.recording_id, rel.link_type, role_label, ee.native_id");
end

function rows = intakeProvenanceRows(conn, ingestionRunId)
rows = fetch(conn, ...
    "SELECT ir.ingestion_run_id, p.project_key, ir.status, " + ...
    "cp.profile_key AS mapping_profile_key, " + ...
    "cpv.version_label AS mapping_profile_version, " + ...
    "cpv.content_uri AS mapping_profile_uri, " + ...
    "cpv.checksum_sha256 AS mapping_profile_checksum, " + ...
    "COUNT(inf.source_file_id) AS ingestion_file_count " + ...
    "FROM ingestion_runs ir " + ...
    "JOIN projects p ON p.project_id = ir.project_id " + ...
    "JOIN config_profile_versions cpv ON cpv.profile_version_id = " + ...
    "ir.mapping_profile_version_id " + ...
    "JOIN config_profiles cp ON cp.profile_id = cpv.profile_id " + ...
    "JOIN ingestion_files inf ON inf.ingestion_run_id = ir.ingestion_run_id " + ...
    "WHERE ir.ingestion_run_id = " + string(ingestionRunId) + ...
    " GROUP BY ir.ingestion_run_id, p.project_key, ir.status, " + ...
    "cp.profile_key, cpv.version_label, cpv.content_uri, " + ...
    "cpv.checksum_sha256");
end

function rows = acquisitionProfileRows(conn, projectId)
rows = fetch(conn, ...
    "SELECT p.project_key, r.recording_id, cp.profile_kind, " + ...
    "cp.profile_key, cpv.version_label, cpv.content_uri, " + ...
    "cpv.checksum_sha256, ppa.assignment_role AS project_role, " + ...
    "rpa.assignment_role AS recording_role, rpa.inheritance_source " + ...
    "FROM recording_profile_assignments rpa " + ...
    "JOIN recordings r ON r.recording_id = rpa.recording_id " + ...
    "JOIN projects p ON p.project_id = r.project_id " + ...
    "JOIN config_profile_versions cpv ON cpv.profile_version_id = " + ...
    "rpa.profile_version_id " + ...
    "JOIN config_profiles cp ON cp.profile_id = cpv.profile_id " + ...
    "JOIN project_profile_assignments ppa ON ppa.project_id = p.project_id " + ...
    "AND ppa.profile_version_id = cpv.profile_version_id " + ...
    "WHERE p.project_id = " + string(projectId) + ...
    " ORDER BY cp.profile_kind, cp.profile_key");
end

function value = semanticSnapshot(conn, projectId)
names = ["projects"; "config_profiles"; "config_profile_versions"; ...
    "project_profile_assignments"; "source_files"; "entity_types"; ...
    "experimental_entities"; "entity_relationships"; "recordings"; ...
    "recording_entity_links"; "recording_profile_assignments"];
counts = [ ...
    projectCount(conn, "projects", projectId); ...
    profileCount(conn, projectId, false); ...
    profileCount(conn, projectId, true); ...
    projectCount(conn, "project_profile_assignments", projectId); ...
    projectCount(conn, "source_files", projectId); ...
    projectCount(conn, "entity_types", projectId); ...
    projectCount(conn, "experimental_entities", projectId); ...
    projectCount(conn, "entity_relationships", projectId); ...
    projectCount(conn, "recordings", projectId); ...
    linkedProjectCount(conn, "recording_entity_links", projectId); ...
    linkedProjectCount(conn, "recording_profile_assignments", projectId)];
value = table(names, counts, VariableNames=["table_name", "row_count"]);
end

function value = databaseInventory(conn)
names = ["projects"; "config_profiles"; "config_profile_versions"; ...
    "project_profile_assignments"; "ingestion_runs"; "ingestion_files"; ...
    "source_files"; "entity_types"; "experimental_entities"; ...
    "entity_relationships"; "recordings"; "recording_entity_links"; ...
    "recording_profile_assignments"; "extraction_runs"; "detections"];
counts = zeros(numel(names), 1);
for index = 1:numel(names)
    counts(index) = scalar(conn, ...
        "SELECT COUNT(*) AS n FROM " + names(index));
end
value = table(names, counts, VariableNames=["table_name", "row_count"]);
end

function value = projectCount(conn, tableName, projectId)
if tableName == "projects"
    sql = "SELECT COUNT(*) AS n FROM projects WHERE project_id = " + ...
        string(projectId);
else
    sql = "SELECT COUNT(*) AS n FROM " + tableName + ...
        " WHERE project_id = " + string(projectId);
end
value = scalar(conn, sql);
end

function value = linkedProjectCount(conn, tableName, projectId)
value = scalar(conn, ...
    "SELECT COUNT(*) AS n FROM " + tableName + " item " + ...
    "JOIN recordings r ON r.recording_id = item.recording_id " + ...
    "WHERE r.project_id = " + string(projectId));
end

function value = profileCount(conn, projectId, versions)
if versions
    target = "config_profile_versions cpv JOIN config_profiles cp " + ...
        "ON cp.profile_id = cpv.profile_id";
else
    target = "config_profiles cp";
end
value = scalar(conn, ...
    "SELECT COUNT(*) AS n FROM " + target + ...
    " JOIN project_profile_assignments ppa ON ppa.profile_version_id = " + ...
    conditionalVersionColumn(versions) + ...
    " WHERE ppa.project_id = " + string(projectId));
end

function value = conditionalVersionColumn(versions)
if versions
    value = "cpv.profile_version_id";
else
    value = "(SELECT profile_version_id FROM config_profile_versions " + ...
        "WHERE profile_id = cp.profile_id LIMIT 1)";
end
end

function value = auditCount(conn, projectId)
value = scalar(conn, ...
    "SELECT COUNT(*) AS n FROM ingestion_runs WHERE project_id = " + ...
    string(projectId));
end

function value = linkCount(conn, projectId, linkType)
value = scalar(conn, ...
    "SELECT COUNT(*) AS n FROM recording_entity_links rel " + ...
    "JOIN recordings r ON r.recording_id = rel.recording_id " + ...
    "WHERE r.project_id = " + string(projectId) + ...
    " AND rel.link_type = '" + string(linkType) + "'");
end

function value = scalar(conn, sql)
rows = fetch(conn, sql);
value = double(rows.n(1));
end

function value = appendRows(value, rows)
if isempty(value)
    value = rows;
elseif ~isempty(rows)
    value = [value; rows];
end
end

function touchFile(path)
parent = string(fileparts(path));
if ~isfolder(parent)
    mkdir(parent);
end
fileId = fopen(path, "w");
if fileId < 0
    error("vawlume:examples:FixtureCreationFailed", ...
        "Could not create demonstration source: %s", path);
end
cleanupFile = onCleanup(@() fclose(fileId));
fwrite(fileId, uint8([]));
clear cleanupFile
end

function path = linkagePath(repoRoot)
path = fullfile(repoRoot, "config", "04_examples", ...
    "profile_linkage_example.json");
end

function root = normalizedRepoRoot(root)
if strlength(root) == 0
    root = fileparts(fileparts(mfilename("fullpath")));
end
try
    root = string(java.io.File(char(root)).getCanonicalPath());
catch
    root = string(root);
end
end

function value = pathContains(target)
entries = split(string(path), pathsep);
value = any(entries == string(target));
end

function restoreSourcePath(sourcePath, shouldRemove)
if shouldRemove && pathContains(sourcePath)
    rmpath(sourcePath);
end
end

function closeConnection(conn)
try
    if isopen(conn)
        close(conn);
    end
catch
end
end

function removeTree(root)
if isfolder(root)
    rmdir(root, "s");
end
end

function printDemonstration(value)
disp("VAWLUME PROJECT INTAKE DEMONSTRATION")
disp(strjoin(value.architecture, " -> "))
disp("Profile and intake summary:")
disp(value.profile_summary)
disp("Recording context:")
disp(value.recording_context)
disp("Intake provenance:")
disp(value.intake_provenance)
disp("Tracked acquisition profiles:")
disp(value.acquisition_profiles)
fprintf("Idempotent graph: %d; relocated graph reused: %d; foreign-key violations: %d\n", ...
    value.idempotency.semantic_graph_unchanged, ...
    value.relocation.semantic_graph_unchanged, ...
    height(value.foreign_key_violations));
end
