function demonstration = temporal_alignment_demo(options)
%TEMPORAL_ALIGNMENT_DEMO Demonstrate the integrated Phase 3 alignment layer.
%
% DEMONSTRATION = TEMPORAL_ALIGNMENT_DEMO() creates a disposable synthetic
% audio/video/controller/neural session. It fits continuous piecewise-affine
% transforms from declared breakpoints, leaves one source clock in a named
% failure state, reads alignment QC, transforms points and intervals, projects
% coverage, and lets tracking consume the stored piecewise transform.
%
% The fixture deliberately contains a redundant observation, a held-out anchor,
% anchors clustered toward one end of the source range, one identity-dependent
% anchor, and both recorded and absent anchor uncertainty. All inputs are created
% under the system temporary directory and removed before return.
%
% Four evidence dimensions are displayed side by side and never combined:
% temporal-alignment residual/QC, pose confidence, visual-identity evidence,
% and acoustic/channel evidence. No caller is named or inferred.
%
% Name-value options:
%   Print     print compact developer-facing read-backs (default true)
%   RepoRoot  repository root, inferred from this file by default

arguments
    options.Print (1,1) logical = true
    options.RepoRoot (1,1) string = ""
end

repoRoot = options.RepoRoot;
if strlength(repoRoot) == 0
    repoRoot = string(fileparts(fileparts(mfilename("fullpath"))));
end
sourcePath = fullfile(repoRoot, "src");
removePath = ~contains(path, sourcePath);
if removePath, addpath(sourcePath); end
cleanupPath = onCleanup(@() restorePath(sourcePath, removePath));

workspace = fullfile(tempdir, "VAWLUME phase 3 alignment demo " + ...
    string(java.util.UUID.randomUUID));
mkdir(workspace);
databasePath = fullfile(workspace, "temporal_alignment_demo.sqlite");
conn = sqlite(char(databasePath), "create");
cleanupConnection = onCleanup(@() closeConnection(conn));
cleanupWorkspace = onCleanup(@() removeTree(workspace));
vawlume.db.applySchema(conn, fullfile(repoRoot, "schema", "schema.sql"));
vawlume.db.registerBuiltinSemantics(conn, repoRoot);

seedSession(conn);
[truth, inputs] = writeSyntheticInputs(workspace, repoRoot);
intake = vawlume.ingest.alignment(conn, inputs.manifest_path, ...
    RepoRoot=repoRoot, SourceRoot=workspace, Apply=true);

% Exclusion is a declared decision. The anchor remains available for a residual
% against the transform it did not influence.
withheld = table();
for timebase = ["audio_native", "video_native"]
    observationRef = struct(project_key="synthetic_alignment_session", ...
        run_key="phase3_alignment_demo", anchor_key="sync04", ...
        timebase_key=timebase, observation_role="primary");
    decision = vawlume.alignment.setAnchorInclusion(conn, observationRef, false, ...
        Reason="synthetic held-out check; not automatic outlier rejection");
    withheld = [withheld; struct2table(decision)]; %#ok<AGROW>
end

tracking = registerTrackingAndIdentity(conn, workspace, repoRoot);

% Planning is read-only, so the sharp identity-separation claim can be observed
% directly: the exact same solve is performed before and after evidence is linked.
beforeIdentity = vawlume.alignment.fit(conn, alignmentRef(), ...
    SourceTimebase="audio_native", Breakpoints=truth.audio_breakpoint);
identityLink = vawlume.alignment.linkAnchorIdentityEvidence(conn, ...
    anchorObservationId(conn, "sync03", "audio_native", "primary"), ...
    tracking.identity_association_id, ...
    Notes="Synthetic identity evidence qualifying the biological anchor.");
afterIdentity = vawlume.alignment.fit(conn, alignmentRef(), ...
    SourceTimebase="audio_native", Breakpoints=truth.audio_breakpoint);
identityInvariant = coefficientFingerprint(beforeIdentity, "audio_native") == ...
    coefficientFingerprint(afterIdentity, "audio_native");

audioFit = vawlume.alignment.fit(conn, alignmentRef(), ...
    SourceTimebase="audio_native", Breakpoints=truth.audio_breakpoint, Apply=true);
videoFit = vawlume.alignment.fit(conn, alignmentRef(), ...
    SourceTimebase="video_native", Breakpoints=truth.video_breakpoint, Apply=true);
% This source deliberately has too little declared segmentation information.
% Its named failure is persisted without disturbing the two successful clocks.
controllerFit = vawlume.alignment.fit(conn, alignmentRef(), ...
    SourceTimebase="controller_native", Apply=true);

qc = vawlume.alignment.report(conn, alignmentRef());
audioRunId = runIdFor(qc, "audio_native");
videoRunId = runIdFor(qc, "video_native");

recovered = recoveredParameters(qc, truth);
crossing = vawlume.alignment.applyTransformInterval(conn, audioRunId, 800, 1000);
[supportTimes, support] = vawlume.alignment.applyTransform(conn, audioRunId, ...
    [900; 1600]);
pointSupport = table([900; 1600], supportTimes, support.segment_index, ...
    support.extrapolated, support.uncertainty_s, ...
    VariableNames=["source_time", "reference_time", "segment_index", ...
    "extrapolated", "uncertainty_s"]);

[~, audioUncertainty] = vawlume.alignment.applyTransform(conn, audioRunId, 900);
[~, videoUncertainty] = vawlume.alignment.applyTransform(conn, videoRunId, ...
    truth.video_breakpoint);
uncertaintyPropagation = table(["audio_native"; "video_native"], ...
    [audioUncertainty.uncertainty_s; videoUncertainty.uncertainty_s], ...
    [audioUncertainty.uncertainty_semantics; ...
        videoUncertainty.uncertainty_semantics], ...
    ["recorded anchor uncertainty"; "no anchor uncertainty recorded"], ...
    VariableNames=["source_timebase", "uncertainty_s", "semantics", "case"]);

view = vawlume.alignment.commonTime(conn, alignmentRef(), ...
    VocalizationSource="detections", VocalizationRunId=1, ...
    ErrorOnOutsideCoverage=false);
coverageExample = demonstrateCoverage(conn, view, videoRunId, truth);

trackingWindow = vawlume.tracking.readWindow(conn, tracking.stream_ref, ...
    [800 1000], SourceRoot=workspace, RepoRoot=repoRoot, ...
    ReferenceTimebaseKey="neural_native");

separateEvidence = evidenceSummary(qc, trackingWindow, inputs.acoustic_path);
audioDiagnostics = qc.anchor_diagnostics( ...
    qc.anchor_diagnostics.source_timebase_key == "audio_native", :);
replicateDispersion = qc.anchor_dispersion( ...
    qc.anchor_dispersion.timebase_key == "audio_native" & ...
    qc.anchor_dispersion.anchor_key == "sync01", :);
withheldResidual = qc.residuals( ...
    qc.residuals.source_timebase_key == "audio_native" & ...
    qc.residuals.anchor_key == "sync04", :);

inventory = struct( ...
    aligned_external_events=rowCount(conn, "aligned_external_events"), ...
    sequences=rowCount(conn, "sequences"), ...
    sequence_members=rowCount(conn, "sequence_members"), ...
    caller_attribution_rows=0);
foreignKeyCheck = fetch(conn, "PRAGMA foreign_key_check");

demonstration = struct( ...
    synthetic_truth=truth, inputs=inputs, intake=intake, ...
    fits=struct(audio=audioFit, video=videoFit, controller=controllerFit), ...
    qc=qc, recovered_parameters=recovered, ...
    identity=struct(link=identityLink, coefficients_before= ...
        coefficientFingerprint(beforeIdentity, "audio_native"), ...
        coefficients_after=coefficientFingerprint(afterIdentity, "audio_native"), ...
        coefficients_identical=identityInvariant), ...
    withheld_decisions=withheld, withheld_residual=withheldResidual, ...
    replicate_dispersion=replicateDispersion, ...
    anchor_configuration=audioDiagnostics, ...
    interval_crossing=crossing, point_support=pointSupport, ...
    uncertainty_propagation=uncertaintyPropagation, ...
    common_time_events=view.events, projected_coverage=view.coverage, ...
    coverage_demonstration=coverageExample, ...
    tracking=tracking, tracking_window=trackingWindow, ...
    separate_evidence=separateEvidence, ...
    separation=struct(combined_value_computed=false, caller_named=false, ...
        note="The four evidence values retain distinct sources, semantics, and units."), ...
    database_inventory=inventory, foreign_key_check=foreignKeyCheck, ...
    proves=["declared piecewise drift is recovered through the public fit API"; ...
        "source clocks succeed or fail independently against one reference"; ...
        "replicates, withheld anchors, coverage, and extrapolation remain distinct evidence"; ...
        "tracking consumes the shared stored piecewise transform"; ...
        "identity evidence is visible and coefficient-invariant"], ...
    does_not_prove=["real-device synchronization accuracy"; ...
        "calibrated uncertainty or residual acceptance thresholds"; ...
        "which animal produced any detected vocalization"], ...
    temporary_artifacts_removed=false);

if options.Print, printDemo(demonstration); end
close(conn);
clear cleanupConnection
removeTree(workspace);
clear cleanupWorkspace
demonstration.temporary_artifacts_removed = ...
    ~isfolder(workspace) && ~isfile(databasePath);
clear cleanupPath
end

% -------------------------------------------------------------- synthetic ---

function seedSession(conn)
execute(conn, "INSERT INTO projects(project_id,project_key,project_name) " + ...
    "VALUES (1,'synthetic_alignment_session','Synthetic alignment demo')");
execute(conn, "INSERT INTO source_files(source_file_id,project_id,file_role," + ...
    "path_or_uri,relative_path) VALUES " + ...
    "(1,1,'recording_audio','synthetic/session01.wav','session01.wav')");
execute(conn, "INSERT INTO recordings(recording_id,project_id,source_file_id," + ...
    "native_recording_id,sample_rate_hz,duration_s) " + ...
    "VALUES (1,1,1,'REC_SESSION_01',250000,1600)");
execute(conn, "INSERT INTO extractors(extractor_key,extractor_name) " + ...
    "VALUES ('synthetic_calls','Synthetic call fixture')");
execute(conn, "INSERT INTO extractor_versions(extractor_id,version_label) " + ...
    "VALUES ((SELECT extractor_id FROM extractors " + ...
    "WHERE extractor_key='synthetic_calls'),'0.1-demo')");
execute(conn, "INSERT INTO extraction_runs(extraction_run_id,project_id," + ...
    "extractor_version_id,run_key) VALUES (1,1,(SELECT extractor_version_id " + ...
    "FROM extractor_versions ev JOIN extractors e ON " + ...
    "e.extractor_id=ev.extractor_id WHERE e.extractor_key='synthetic_calls')," + ...
    "'demo_calls')");
execute(conn, "INSERT INTO extraction_run_inputs(extraction_run_id,recording_id) " + ...
    "VALUES (1,1)");
execute(conn, "INSERT INTO detections(extraction_run_id,recording_id," + ...
    "native_event_id,start_time_s,end_time_s,timing_basis) VALUES " + ...
    "(1,1,'call01',60,60.08,'synthetic fixture')," + ...
    "(1,1,'call02',330,330.06,'synthetic fixture')");
execute(conn, "INSERT INTO entity_types(project_id,native_name,is_subject_like) " + ...
    "VALUES (1,'mouse',1)");
execute(conn, "INSERT INTO experimental_entities(project_id,entity_type_id," + ...
    "native_id) VALUES (1,(SELECT entity_type_id FROM entity_types " + ...
    "WHERE project_id=1 AND native_name='mouse'),'mouse_a')," + ...
    "(1,(SELECT entity_type_id FROM entity_types WHERE project_id=1 " + ...
    "AND native_name='mouse'),'mouse_b')");
end

function [truth, inputs] = writeSyntheticInputs(workspace, repoRoot)
truth = struct();
truth.audio_breakpoint = 900;
truth.audio_scale = [1.0015; 0.9990];
truth.audio_offset_s = [117.25; ...
    (truth.audio_scale(1) - truth.audio_scale(2)) * ...
        truth.audio_breakpoint + 117.25];
truth.video_scale = 0.9992;
truth.video_offset_s = 53.40;
truth.audio_times = [10; 20; 30; 900; 1200; 1500];
truth.anchor_keys = "sync" + compose("%02d", (1:numel(truth.audio_times))');
segment = 1 + double(truth.audio_times >= truth.audio_breakpoint);
truth.neural_times = truth.audio_scale(segment) .* truth.audio_times + ...
    truth.audio_offset_s(segment);
% The held-out observation is purposefully displaced. It is QC evidence and
% does not perturb either fitted transform.
truth.neural_times(4) = truth.neural_times(4) + 0.015;
truth.video_times = (truth.neural_times - truth.video_offset_s) / ...
    truth.video_scale;
truth.video_breakpoint = (truth.audio_scale(1) * truth.audio_breakpoint + ...
    truth.audio_offset_s(1) - truth.video_offset_s) / truth.video_scale;

behavior = table(["b1"; "b2"], ["Intruder enters"; "Sniffing"], ...
    ["60"; "330"], ["65"; missing], ["mouse_a"; "mouse_b"], ...
    ["door"; "center"], VariableNames=["event_id", "event", ...
    "start_time_s", "end_time_s", "subject", "zone"]);
writeTable(fullfile(workspace, "video_events.csv"), behavior);

ids = "n" + string(1:numel(truth.neural_times))';
neural = table(ids, repmat("TTL1_HIGH", numel(ids), 1), ...
    compose("%.9f", truth.neural_times * 1000), repmat("5", numel(ids), 1), ...
    repmat("1", numel(ids), 1), ...
    VariableNames=["pulse_id", "marker", "timestamp_ms", "amplitude_v", "channel"]);
writeTable(fullfile(workspace, "neural_events.csv"), neural);

writeTable(fullfile(workspace, "sync_anchors.csv"), anchorTable(truth));

profilePath = fullfile(workspace, "phase3_anchor_profile.json");
writeAnchorProfile(profilePath, repoRoot);
manifestPath = fullfile(workspace, "phase3_alignment_manifest.json");
writeManifest(manifestPath, profilePath, repoRoot);

acousticPath = fullfile(workspace, "acoustic_evidence.csv");
writeTable(acousticPath, table(0.42, "channel_1_to_2_rms_ratio", "ratio", ...
    VariableNames=["value", "semantics", "unit"]));
inputs = struct(manifest_path=string(manifestPath), ...
    anchor_profile_path=string(profilePath), acoustic_path=string(acousticPath));
end

function value = anchorTable(truth)
count = numel(truth.anchor_keys);
rowCount = 3 * count + 3;
markers = strings(rowCount, 1); streams = strings(rowCount, 1);
timestamps = strings(rowCount, 1); roles = strings(rowCount, 1);
included = strings(rowCount, 1); uncertainties = strings(rowCount, 1);
classes = strings(rowCount, 1); eventIds = strings(rowCount, 1);
row = 0;
for index = 1:count
    for item = [struct(stream="audio", time=truth.audio_times(index)), ...
            struct(stream="video", time=truth.video_times(index)), ...
            struct(stream="neural", time=truth.neural_times(index))]
        row = row + 1;
        markers(row) = truth.anchor_keys(index);
        streams(row) = item.stream;
        timestamps(row) = compose("%.9f", item.time);
        roles(row) = "primary";
        included(row) = "true";
        classes(row) = "device_level";
        if item.stream == "audio"
            uncertainties(row) = "0.002";
        elseif item.stream == "neural"
            eventIds(row) = "n" + string(index);
        end
        if index == 3
            classes(row) = "identity_dependent";
        end
    end
end
% A replicate is preserved as dispersion evidence and explicitly excluded.
row = row + 1;
markers(row) = truth.anchor_keys(1);
streams(row) = "audio";
timestamps(row) = compose("%.9f", truth.audio_times(1) + 0.006);
roles(row) = "replicate";
included(row) = "false";
uncertainties(row) = "0.002";
classes(row) = "device_level";
% Two readings establish that a controller clock participated, but no
% breakpoint is declared for its piecewise model, producing a named failure.
for index = 1:2
    row = row + 1;
    markers(row) = truth.anchor_keys(index);
    streams(row) = "controller";
    timestamps(row) = compose("%.9f", 2 * truth.audio_times(index));
    roles(row) = "primary";
    included(row) = "true";
    classes(row) = "device_level";
end
value = table(markers, streams, timestamps, roles, included, uncertainties, ...
    classes, eventIds, VariableNames=["marker", "stream", "timestamp_s", ...
    "role", "include", "uncertainty_s", "evidence_class", "event_id"]);
end

function writeAnchorProfile(pathValue, repoRoot)
document = jsondecode(fileread(fullfile(repoRoot, "config", ...
    "01_mapping_profiles", "alignment_anchors", ...
    "long_anchor_mapping_profile.json")));
document.profile.id = "vawlume.alignment.anchor.long.phase3_demo.v1";
document.profile.name = "Synthetic Phase 3 integrated anchor profile";
declared = cellstr(string(document.context.declared_timebases));
declared{end + 1} = 'controller_native';
document.context.declared_timebases = declared;
mapping = document.context.stream_timebases(1);
mapping.native_value = "controller";
mapping.stream_key = "controller_sync";
mapping.timebase_key = "controller_native";
document.context.stream_timebases(end + 1) = mapping;
pair = document.context.fit_pairs(1);
pair.source_timebase_key = "controller_native";
pair.reference_timebase_key = "neural_native";
document.context.fit_pairs(end + 1) = pair;
writeText(pathValue, string(jsonencode(document, PrettyPrint=true)) + newline);
end

function writeManifest(pathValue, anchorProfilePath, repoRoot)
document = jsondecode(fileread(fullfile(repoRoot, "config", ...
    "06_alignment_manifests", "synthetic_session_alignment_manifest.json")));
document.manifest.alignment_key = "phase3_alignment_demo";
document.manifest.label = "Synthetic integrated Phase 3 alignment";
document.method = "piecewise_affine";
controller = document.timebases{1};
controller.timebase_key = "controller_native";
controller.timebase_kind = "controller_clock";
controller.recording_native = false;
controller.native_unit = "s";
controller.origin_description = "Synthetic controller start.";
document.timebases{end + 1} = controller;
document.anchors.mapping_profile = char(anchorProfilePath);
writeText(pathValue, string(jsonencode(document, PrettyPrint=true)) + newline);
end

% --------------------------------------------------------------- tracking ---

function value = registerTrackingAndIdentity(conn, workspace, repoRoot)
vawlume.geometry.registerCoordinateSystem(conn, ...
    struct(project_key="synthetic_alignment_session"), struct( ...
    coordinate_system_key="arena_2d", coordinate_system_name="Synthetic arena", ...
    dimensionality=2, unit="cm"));

artifactPath = fullfile(workspace, "tracking.csv");
tracking = table([0; 60; 800; 900; 1000; 1500], ...
    repmat("track_a", 6, 1), repmat("snout", 6, 1), ...
    [0; 1; 2; 3; 4; 5], repmat(10, 6, 1), repmat(0.73, 6, 1), ...
    VariableNames=["time_s", "track", "bodypart", "x", "y", "likelihood"]);
writeTable(artifactPath, tracking);
profilePath = fullfile(workspace, "tracking_profile.json");
profile = jsondecode(fileread(fullfile(repoRoot, "config", ...
    "01_mapping_profiles", "tracking", "generic_tracking_mapping_profile.json")));
profile.profiles.columns.track_label.source_field = "track";
writeText(profilePath, string(jsonencode(profile, PrettyPrint=true)) + newline);

streamRef = struct(project_key="synthetic_alignment_session", ...
    stream_name="tracking_primary");
registration = vawlume.tracking.register(conn, struct(recording_id=1), struct( ...
    artifact_path="tracking.csv", profile_path=profilePath, ...
    timebase_key="video_native"), Apply=true, RepoRoot=repoRoot, ...
    SourceRoot=workspace);
association = vawlume.tracking.registerIdentityAssociation(conn, streamRef, struct( ...
    native_track_id="track_a", entity_native_id="mouse_a", ...
    start_time_native=800, end_time_native=1000, ...
    assignment_state="candidate", evidence_kind="reidentification_score", ...
    identity_value=0.55, ...
    identity_value_semantics="cosine_similarity_of_appearance_embeddings", ...
    calibration_status="uncalibrated", review_state="unreviewed"));
value = struct(registration=registration, stream_ref=streamRef, ...
    identity_association_id=association.tracking_identity_association_id, ...
    dense_samples_stored=registration.dense_samples_stored);
end

% ------------------------------------------------------------- read-backs ---

function value = recoveredParameters(qc, truth)
audio = qc.segments(qc.segments.source_timebase_key == "audio_native", :);
video = qc.segments(qc.segments.source_timebase_key == "video_native", :);
expectedScale = [truth.audio_scale; repmat(truth.video_scale, height(video), 1)];
expectedOffset = [truth.audio_offset_s; repmat(truth.video_offset_s, height(video), 1)];
observedScale = [audio.scale; video.scale];
observedOffset = [audio.offset_s; video.offset_s];
value = table([repmat("audio_native", height(audio), 1); ...
    repmat("video_native", height(video), 1)], ...
    [audio.segment_index; video.segment_index], observedScale, expectedScale, ...
    observedOffset, expectedOffset, abs(observedScale - expectedScale), ...
    abs(observedOffset - expectedOffset), ...
    VariableNames=["source_timebase", "segment_index", "scale", ...
    "expected_scale", "offset_s", "expected_offset_s", ...
    "scale_absolute_error", "offset_absolute_error_s"]);
end

function value = demonstrateCoverage(conn, view, videoRunId, truth)
videoKey = unique(view.events.coverage_key( ...
    view.events.source_timebase_key == "video_native"));
assert(isscalar(videoKey), "Expected one video event stream.");
[edges, support] = vawlume.alignment.applyTransform(conn, videoRunId, [0; 30]);
binWidth = edges(2) - edges(1);
channels = struct(name="behavior_event_count", ...
    event_source_kind="external_event", normalized_event_key="female_entry", ...
    coverage_key=videoKey, aggregation="onset_count");
regularized = vawlume.sequence.regularizeTimeline(view, channels, ...
    WindowStart=edges(1), WindowEnd=edges(1) + 12 * binWidth, ...
    BinWidth=binWidth, BinOrigin=edges(1));
value = struct(timeline=regularized.timeline, ...
    specification=regularized.specification, ...
    first_bin_source_interval=[0 30], ...
    first_bin_extrapolated=any(support.extrapolated), ...
    first_bin_covered_empty=regularized.timeline.behavior_event_count(1) == 0, ...
    unavailable_bin_present=any(isnan(regularized.timeline.behavior_event_count)), ...
    projected_coverage=view.coverage( ...
        view.coverage.source_timebase_key == "video_native", :), ...
    note="Zero means covered and empty; NaN means unavailable. Transform support is separate.", ...
    video_breakpoint=truth.video_breakpoint);
end

function value = evidenceSummary(qc, trackingWindow, acousticPath)
withheld = qc.residuals(qc.residuals.source_timebase_key == "audio_native" & ...
    qc.residuals.anchor_key == "sync04", :);
identity = qc.anchor_identity_evidence(1, :);
acoustic = readtable(acousticPath, TextType="string");
value = table(["temporal_alignment"; "pose_localization"; ...
    "visual_identity"; "acoustic_channel_response"], ...
    [abs(withheld.residual_s(1)); trackingWindow.samples.pose_confidence(1); ...
        identity.identity_value(1); acoustic.value(1)], ...
    ["s"; "upstream score"; "similarity"; acoustic.unit(1)], ...
    ["held-out residual; reported, not judged"; ...
        "upstream keypoint localization confidence"; ...
        identity.identity_value_semantics(1); acoustic.semantics(1)], ...
    ["alignment_anchor_residuals"; "tracking artifact"; ...
        "tracking_identity_associations"; "synthetic acoustic evidence file"], ...
    VariableNames=["dimension", "value", "unit", "semantics", "queried_from"]);
end

function value = coefficientFingerprint(fit, sourceKey)
rows = fit.segments(fit.segments.source_timebase_key == sourceKey, :);
parts = compose("%.17g|%.17g|%.17g", rows.scale, rows.offset_s, rows.rmse_s);
value = join(parts, ";");
end

function value = alignmentRef()
value = struct(project_key="synthetic_alignment_session", ...
    run_key="phase3_alignment_demo");
end

function value = runIdFor(qc, sourceKey)
row = qc.transforms(qc.transforms.source_timebase_key == sourceKey, :);
assert(height(row) == 1, "Expected one transform for " + sourceKey);
value = double(row.alignment_run_id(1));
end

function value = anchorObservationId(conn, anchorKey, timebaseKey, role)
rows = fetch(conn, "SELECT o.anchor_observation_id FROM " + ...
    "alignment_anchor_observations o JOIN alignment_anchors a " + ...
    "ON a.alignment_anchor_id=o.alignment_anchor_id JOIN timebases t " + ...
    "ON t.timebase_id=o.timebase_id JOIN alignment_sets s " + ...
    "ON s.alignment_set_id=a.alignment_set_id " + ...
    "WHERE s.alignment_set_key='phase3_alignment_demo' AND a.anchor_key=" + ...
    sqlText(anchorKey) + " AND t.timebase_name=" + sqlText(timebaseKey) + ...
    " AND o.observation_role=" + sqlText(role));
assert(height(rows) == 1, "Anchor observation selector was not unique.");
value = double(rows.anchor_observation_id(1));
end

% ------------------------------------------------------------------ print ---

function printDemo(value)
fprintf('\nVAWLUME synthetic Phase 3 temporal-alignment demonstration\n');
fprintf(['All inputs and thresholds are synthetic. A fitted transform is ' ...
    'estimated, never validated.\n']);
fprintf('Reference clock: %s\n', value.qc.reference_timebase.timebase_key);

fprintf('\nSource-clock outcomes (one failure does not erase the successes):\n');
disp(value.qc.transforms(:, ["source_timebase_key", "method", "status", ...
    "segment_count", "failure_code"]));
fprintf('Recovered declared piecewise parameters:\n');
disp(value.recovered_parameters);

fprintf('Replicate dispersion (one logical anchor, not an extra fit row):\n');
disp(value.replicate_dispersion);
fprintf('Held-out residual (did not influence the coefficients):\n');
disp(value.withheld_residual);
fprintf('Anchor-configuration diagnostics for the deliberately clustered case:\n');
disp(value.anchor_configuration);

fprintf('Interval crossing the declared breakpoint:\n');
disp(value.interval_crossing);
fprintf('Anchored versus extrapolated point:\n');
disp(value.point_support);
fprintf('Propagated uncertainty (explicitly uncalibrated; NaN means absent):\n');
disp(value.uncertainty_propagation);

fprintf('Coverage-aware bins (0 = covered-empty, NaN = unavailable):\n');
disp(value.coverage_demonstration.timeline);
fprintf('  first covered-empty bin extrapolated: %d\n', ...
    value.coverage_demonstration.first_bin_extrapolated);

fprintf('Identity evidence attached; coefficient fingerprints identical: %d\n', ...
    value.identity.coefficients_identical);
fprintf('Tracking readWindow transform method/status: %s / %s\n', ...
    value.tracking_window.transform.method, value.tracking_window.reference_time_status);

fprintf('Four separate evidence dimensions (never combined; no caller named):\n');
disp(value.separate_evidence);
fprintf('Proves:\n  %s\n', strjoin(value.proves, '\n  '));
fprintf('Does not prove:\n  %s\n', strjoin(value.does_not_prove, '\n  '));
end

% ---------------------------------------------------------------- helpers ---

function writeTable(pathValue, value)
writetable(value, pathValue, QuoteStrings="minimal");
end

function writeText(pathValue, value)
fid = fopen(pathValue, "w");
assert(fid >= 0, "Could not create synthetic demonstration input.");
cleanup = onCleanup(@() fclose(fid));
fprintf(fid, "%s", value);
clear cleanup
end

function value = rowCount(conn, tableName)
rows = fetch(conn, "SELECT COUNT(*) AS n FROM " + tableName);
value = double(rows.n(1));
end

function value = sqlText(text)
value = "'" + replace(string(text), "'", "''") + "'";
end

function restorePath(sourcePath, removePath)
if removePath && contains(path, sourcePath), rmpath(sourcePath); end
end

function closeConnection(conn)
if isopen(conn), close(conn); end
end

function removeTree(workspace)
if isfolder(workspace), rmdir(workspace, "s"); end
end
