function demonstration = usvseg_import_demo(options)
%USVSEG_IMPORT_DEMO Demonstrate the USVSEG import path end to end.
%
% DEMONSTRATION = USVSEG_IMPORT_DEMO() creates a disposable project and
% recording through public project intake, generates a small synthetic USVSEG
% `<stem>_dat.csv` event export, inspects it without any database access,
% plans the import, applies it, and reads back extraction-run and artifact
% provenance, syllable detections, and native plus canonical measurements.
%
% It then shows the three behaviours that distinguish USVSEG from the other two
% shipped importers:
%
%   1. settings evidence is optional, and `usvseg_prm.mat` is recorded as
%      application-scoped weak evidence rather than verified run configuration;
%   2. an unexpected source column is preserved in `unmapped_source_values`
%      rather than discarded;
%   3. a header-only export is a valid zero-detection run, not a failure.
%
% Every artifact and the SQLite database live under the system temporary
% directory and are removed before return. The call times, frequencies, and
% amplitudes are purpose-built demonstration values; no recorded sound and no
% real USVSEG output is involved.
%
% Name-value options:
%   Print     print compact developer-facing read-backs (default true)
%   RepoRoot  repository root, inferred from this file by default
%
% See also VAWLUME.INGEST.USVSEG, VAWLUME.INGEST.USVSEGEXPORT,
% MULTI_EXTRACTOR_AGREEMENT_DEMO.

arguments
    options.Print (1,1) logical = true
    options.RepoRoot (1,1) string = ""
end

repoRoot = normalizedRepoRoot(options.RepoRoot);
sourcePath = fullfile(repoRoot, "src");
removeSourcePath = ~pathContains(sourcePath);
if removeSourcePath, addpath(sourcePath); end
cleanupPath = onCleanup(@() restoreSourcePath(sourcePath, removeSourcePath));

workspaceRoot = fullfile(tempdir, ...
    "VAWLUME usvseg import demo " + string(java.util.UUID.randomUUID));
mkdir(workspaceRoot);
cleanupWorkspace = onCleanup(@() removeTree(workspaceRoot));
databasePath = fullfile(workspaceRoot, "usvseg_import_demo.sqlite");
conn = sqlite(char(databasePath), "create");
cleanupConnection = onCleanup(@() closeConnection(conn));

vawlume.db.applySchema(conn, fullfile(repoRoot, "schema", "schema.sql"));
vawlume.db.registerBuiltinSemantics(conn, repoRoot);

% Establish the recording through the real source-mapping/intake path. The
% importer never infers a recording from the CSV basename or its stem.
[project, recordingRef] = establishProject(conn, workspaceRoot, repoRoot);

usvsegRoot = fullfile(workspaceRoot, "usvseg");
exportPath = fullfile(usvsegRoot, "REC_A_dat.csv");
writeLines(exportPath, [standardHeader(); standardRows()]);

% 1. Database-free inspection. USVSEG writes no version string into any output,
%    so the version is caller evidence assessed against the profile's scope.
export = vawlume.ingest.usvsegExport(exportPath, RepoRoot=repoRoot, ...
    ArtifactRoot=usvsegRoot, ExtractorVersion="0.9r2");
preview = vawlume.source_mapping.preview(export.ir);
inspection = struct(preview_verdict=preview.verdict, ...
    valid_for_ingest=export.valid_for_ingest, ...
    identifier_column_preserved=any(export.table.Properties.VariableNames == "#"), ...
    source_row_count=export.artifact.row_count, ...
    declared_version=export.extractor_version.status, ...
    artifact_checksum_sha256=export.artifact.checksum_sha256, ...
    adapter_error_count=export.adapter_error_count, ...
    adapter_warning_count=export.adapter_warning_count);

% 2. Plan, then apply. Planning writes nothing.
runSpec = struct(run_key="demo-usvseg", extractor_version="0.9r2", ...
    run_label="Synthetic USVSEG segmentation pass");
before = databaseInventory(conn);
planned = vawlume.ingest.usvseg(conn, exportPath, recordingRef, runSpec, ...
    RepoRoot=repoRoot, ArtifactRoot=usvsegRoot);
afterPlan = databaseInventory(conn);
applied = vawlume.ingest.usvseg(conn, exportPath, recordingRef, runSpec, ...
    RepoRoot=repoRoot, ArtifactRoot=usvsegRoot, Apply=true);
assert(applied.committed, "USVSEG import did not commit: %s", applied.status);

primaryRun = struct(plan_status=planned.status, ...
    plan_wrote_nothing=isequal(before, afterPlan), ...
    import_status=applied.status, committed=applied.committed, ...
    extraction_run_id=applied.extraction_run.extraction_run_id, ...
    detection_count=applied.applied_counts.detections, ...
    event_measurement_count=applied.applied_counts.event_measurements, ...
    settings_status=applied.settings.status, ...
    settings_verified_run_configuration= ...
        applied.settings.verified_run_configuration, ...
    settings_absence_is_explicit= ...
        any(contains(applied.warnings, "USVSEG_SETTINGS_UNAVAILABLE")));

% 3. What USVSEG does not export is stated positively rather than defaulted.
absentEvidence = struct( ...
    curation_rows=countOf(conn, "curation_events"), ...
    classification_rows=countOf(conn, "classification_assignments"), ...
    detection_score_rows=countOf(conn, ...
        "detections WHERE detection_score IS NOT NULL"), ...
    frequency_bound_measurements=countOf(conn, ...
        "event_measurements em JOIN extractor_features xf " + ...
        "ON xf.extractor_feature_id=em.extractor_feature_id " + ...
        "WHERE xf.equivalence_class IN " + ...
        "('vocalization_frequency_min','vocalization_frequency_max'," + ...
        "'vocalization_frequency_bandwidth')"));

detections = readDetections(conn, applied.extraction_run.extraction_run_id);
measurements = readMeasurements(conn, applied.extraction_run.extraction_run_id);

% 4. An unchanged rerun reuses every identity and adds no scientific row.
inventoryBeforeRerun = databaseInventory(conn);
rerun = vawlume.ingest.usvseg(conn, exportPath, recordingRef, runSpec, ...
    RepoRoot=repoRoot, ArtifactRoot=usvsegRoot, Apply=true);
rerunReadback = struct(status=rerun.status, ...
    extraction_run_id_stable=rerun.extraction_run.extraction_run_id == ...
        applied.extraction_run.extraction_run_id, ...
    new_detections=rerun.applied_counts.detections, ...
    reused_detections=rerun.applied_counts.reused_detections, ...
    rows_unchanged=isequal(inventoryBeforeRerun, databaseInventory(conn)));

% 5. Optional usvseg_prm.mat plus one unexpected source column. The parameter
%    file is application-scoped: USVSEG writes it when the application closes,
%    not beside the CSV it may or may not correspond to.
weak = importWeakEvidenceRun(conn, usvsegRoot, repoRoot, recordingRef);

% 6. A header-only export is a valid zero-detection segmentation pass.
emptyPath = fullfile(usvsegRoot, "REC_A_quiet_dat.csv");
writeLines(emptyPath, standardHeader());
emptyResult = vawlume.ingest.usvseg(conn, emptyPath, recordingRef, ...
    struct(run_key="demo-usvseg-quiet", extractor_version="0.9r2", ...
    run_label="Synthetic zero-detection segmentation pass"), ...
    RepoRoot=repoRoot, ArtifactRoot=usvsegRoot, Apply=true);
zeroDetection = struct(status=emptyResult.status, ...
    committed=emptyResult.committed, ...
    source_row_count=emptyResult.export.row_count, ...
    detection_count=emptyResult.applied_counts.detections, ...
    extraction_run_registered=emptyResult.extraction_run.extraction_run_id > 0, ...
    artifact_count=emptyResult.applied_counts.extraction_run_artifacts);

demonstration = struct( ...
    architecture=["public project intake"; ...
        "database-free USVSEG export inspection"; "read-only import plan"; ...
        "atomic apply"; "provenance and measurement read-back"; ...
        "unchanged rerun"; "optional weak settings evidence"; ...
        "preserved unexpected source column"; "zero-detection run"], ...
    boundary="USVSEG is an integration, not a component. VAWLUME reads an " + ...
        "export USVSEG already produced and never wraps, runs, or " + ...
        "reimplements it.", ...
    project=project, inspection=inspection, primary_run=primaryRun, ...
    detections=detections, measurements=measurements, ...
    absent_evidence=absentEvidence, rerun=rerunReadback, ...
    weak_settings_evidence=weak, zero_detection_run=zeroDetection, ...
    database_inventory=databaseInventory(conn), ...
    foreign_key_check=fetch(conn, "PRAGMA foreign_key_check"), ...
    proves=[ ...
        "a USVSEG export imports through the same relational and semantic model as DeepSqueak and MUPET"; ...
        "native tokens, units, and the literal '#' identifier column survive canonicalization"; ...
        "absent USVSEG evidence is recorded as absent rather than defaulted"; ...
        "usvseg_prm.mat is weak application-scoped evidence, never verified run configuration"; ...
        "a header-only export is a valid zero-detection run"], ...
    does_not_prove=[ ...
        "USVSEG segmentation accuracy or any comparison between extractors"; ...
        "empirical calibration of any threshold"; ...
        "that this synthetic export resembles a real USVSEG artifact"], ...
    workspace_root=workspaceRoot, database_path=databasePath, ...
    temporary_artifacts_removed=false);

close(conn);
clear cleanupConnection
removeTree(workspaceRoot);
clear cleanupWorkspace
demonstration.temporary_artifacts_removed = ...
    ~isfolder(workspaceRoot) && ~isfile(databasePath);

if options.Print, printDemonstration(demonstration); end
clear cleanupPath
end

% -------------------------------------------------------------- workflow ---

function [project, recordingRef] = establishProject(conn, workspaceRoot, repoRoot)
profilePath = fullfile(repoRoot, "config", "01_mapping_profiles", ...
    "project_inputs", "project_input_source_mapping_examples.json");
sourceRoot = fullfile(workspaceRoot, "project");
audioPath = fullfile(sourceRoot, "control", "mouse_001", "baseline", ...
    "001_baseline_1.wav");
writeText(audioPath, "synthetic audio stand-in; no recorded sound is involved");
ir = vawlume.source_mapping.parse(profilePath, sourceRoot, ...
    ProfileId="example.project.mouse_courtship.folder_driven", RepoRoot=repoRoot);
preview = vawlume.source_mapping.preview(ir);
intake = vawlume.ingest.project(conn, ir, struct( ...
    project_key="demo_usvseg_import", ...
    project_name="USVSEG import demonstration", ...
    description="Disposable Phase 1 USVSEG import demonstration."), ...
    Apply=true, RepoRoot=repoRoot);
recording = fetch(conn, "SELECT r.recording_id, p.project_key, " + ...
    "IFNULL(r.native_recording_id,'') AS native_recording_id, " + ...
    "sf.relative_path FROM recordings r " + ...
    "JOIN projects p ON p.project_id=r.project_id " + ...
    "JOIN source_files sf ON sf.source_file_id=r.source_file_id");
recordingId = double(recording.recording_id(1));
recordingRef = struct(recording_id=recordingId);
project = struct(intake_status=intake.status, committed=intake.committed, ...
    preview_verdict=preview.verdict, project_key=string(recording.project_key(1)), ...
    recording_id=recordingId, ...
    native_recording_id=string(recording.native_recording_id(1)), ...
    source_relative_path=string(recording.relative_path(1)));
end

function value = importWeakEvidenceRun(conn, usvsegRoot, repoRoot, recordingRef)
% One export with an extra column the shipped profile does not describe, plus
% the optional application-scoped parameter file.
exportPath = fullfile(usvsegRoot, "REC_A_rerun_dat.csv");
writeLines(exportPath, [standardHeader() + ",snr_db"; ...
    standardRows() + [",11.20"; ",9.80"; ",12.45"; ",10.05"; ",8.60"]]);
settingsPath = fullfile(usvsegRoot, "usvseg_prm.mat");
prm = struct(fftsize=512, timestep=0.0005, freqmin=30, freqmax=120, ...
    threshval=4.5, durmin=5, durmax=300, gapmin=30);
makeParent(settingsPath);
save(char(settingsPath), 'prm');

result = vawlume.ingest.usvseg(conn, exportPath, recordingRef, ...
    struct(run_key="demo-usvseg-prm", extractor_version="0.9r2", ...
    run_label="Synthetic pass with application-scoped parameter evidence", ...
    settings=struct(artifact_path=settingsPath)), ...
    RepoRoot=repoRoot, ArtifactRoot=usvsegRoot, Apply=true);
assert(result.committed, "Weak-evidence USVSEG import did not commit.");

settingsRow = result.artifacts(result.artifacts.role == "extractor_settings", :);
metadata = jsondecode(char(settingsRow.metadata_json(1)));
runRow = fetch(conn, "SELECT IFNULL(settings_profile_version_id,-1) AS " + ...
    "settings_profile_version_id FROM extraction_runs WHERE run_key=" + ...
    "'demo-usvseg-prm'");
unmapped = fetch(conn, "SELECT native_field_name, raw_value_text, " + ...
    "source_locator, reason_unmapped FROM unmapped_source_values " + ...
    "ORDER BY unmapped_value_id");

value = struct(status=result.status, ...
    settings_status=result.settings.status, ...
    settings_evidence_strength=string(metadata.evidence_strength), ...
    settings_evidence_scope=string(metadata.evidence_scope), ...
    verified_run_configuration=result.settings.verified_run_configuration, ...
    run_settings_profile_version_id= ...
        double(runRow.settings_profile_version_id(1)), ...
    unmapped_source_value_count=height(unmapped), ...
    unmapped_source_values=unmapped);
end

% ------------------------------------------------------------ read-backs ---

function value = readDetections(conn, extractionRunId)
value = fetch(conn, "SELECT d.detection_id, d.native_event_id, " + ...
    "d.start_time_s, d.end_time_s, d.timing_basis, d.event_subtype, " + ...
    "(d.detection_score IS NULL) AS detection_score_absent " + ...
    "FROM detections d WHERE d.extraction_run_id=" + ...
    string(extractionRunId) + " ORDER BY d.detection_id");
end

function value = readMeasurements(conn, extractionRunId)
value = fetch(conn, "SELECT d.native_event_id, xf.native_name, " + ...
    "IFNULL(xf.native_unit,'') AS native_unit, " + ...
    "em.native_raw_token, em.native_value_real, " + ...
    "IFNULL(cf.canonical_name,'') AS canonical_name, " + ...
    "em.canonical_value_real, IFNULL(em.canonical_unit,'') AS canonical_unit " + ...
    "FROM event_measurements em " + ...
    "JOIN detections d ON d.detection_id=em.detection_id " + ...
    "JOIN extractor_features xf " + ...
    "ON xf.extractor_feature_id=em.extractor_feature_id " + ...
    "LEFT JOIN feature_mappings fm " + ...
    "ON fm.extractor_feature_id=xf.extractor_feature_id " + ...
    "LEFT JOIN canonical_features cf " + ...
    "ON cf.canonical_feature_id=fm.canonical_feature_id " + ...
    "WHERE d.extraction_run_id=" + string(extractionRunId) + ...
    " ORDER BY d.detection_id, xf.native_name");
end

% --------------------------------------------------------------- fixtures ---

function value = standardHeader()
value = "#,start,end,duration,maxfreq,maxamp,meanfreq,cvfreq";
end

function value = standardRows()
% start/end print four decimal seconds; duration prints one decimal
% millisecond. The two precisions are why the profile's duration-consistency
% check is rounding-aware rather than an equality test.
value = [ ...
    "1,10.0020,10.0490,47.0,72.500,-18.2,61.250,0.1234"
    "2,20.0620,20.1200,58.0,74.000,-19.1,63.125,0.1111"
    "3,30.0010,30.0990,98.0,69.750,-20.4,58.500,0.1502"
    "4,50.0000,50.0450,45.0,71.250,-17.8,60.000,0.0987"
    "5,60.0300,60.0900,60.0,73.125,-18.9,62.375,0.1345"];
end

% -------------------------------------------------------------- utilities ---

function value = databaseInventory(conn)
names = ["projects"; "recordings"; "extraction_runs"; "artifacts"; ...
    "extraction_run_artifacts"; "detections"; "event_measurements"; ...
    "unmapped_source_values"; "curation_events"; "classification_assignments"];
counts = zeros(numel(names), 1);
for index = 1:numel(names), counts(index) = countOf(conn, names(index)); end
value = table(names, counts, VariableNames=["table_name", "row_count"]);
end

function value = countOf(conn, tableExpression)
rows = fetch(conn, "SELECT COUNT(*) AS n FROM " + tableExpression);
value = double(rows.n(1));
end

function writeLines(path, lines)
makeParent(path);
fileId = fopen(path, "w");
if fileId < 0
    error("vawlume:examples:FixtureCreationFailed", ...
        "Could not create demonstration input: %s", path);
end
cleanupFile = onCleanup(@() fclose(fileId));
fprintf(fileId, "%s\n", lines);
clear cleanupFile
end

function writeText(path, value)
makeParent(path);
fileId = fopen(path, "w");
if fileId < 0
    error("vawlume:examples:FixtureCreationFailed", ...
        "Could not create demonstration input: %s", path);
end
cleanupFile = onCleanup(@() fclose(fileId));
fprintf(fileId, "%s", value);
clear cleanupFile
end

function makeParent(path)
parent = fileparts(path);
if ~isfolder(parent), mkdir(parent); end
end

function root = normalizedRepoRoot(root)
if strlength(root) == 0, root = fileparts(fileparts(mfilename("fullpath"))); end
try
    root = string(java.io.File(char(root)).getCanonicalPath());
catch
end
end

function value = pathContains(target)
value = any(split(string(path), pathsep) == string(target));
end

function restoreSourcePath(sourcePath, shouldRemove)
if shouldRemove && pathContains(sourcePath), rmpath(sourcePath); end
end

function closeConnection(conn)
try
    if isopen(conn), close(conn); end
catch
end
end

function removeTree(root)
if isfolder(root), rmdir(root, "s"); end
end

function printDemonstration(value)
disp("VAWLUME USVSEG IMPORT DEMONSTRATION")
disp(value.boundary)
fprintf("Project intake: %s; export verdict: %s; import: %s\n", ...
    value.project.intake_status, value.inspection.preview_verdict, ...
    value.primary_run.import_status);
fprintf("Plan wrote nothing: %d; detections: %d; measurements: %d\n", ...
    value.primary_run.plan_wrote_nothing, value.primary_run.detection_count, ...
    value.primary_run.event_measurement_count);
disp("Syllable detections (native timing, never recomputed):")
disp(value.detections)
disp("Native and canonical measurements:")
disp(value.measurements)
fprintf(['Absent USVSEG evidence recorded as absent - curation %d, ' ...
    'classification %d, detection score %d, frequency bounds %d\n'], ...
    value.absent_evidence.curation_rows, ...
    value.absent_evidence.classification_rows, ...
    value.absent_evidence.detection_score_rows, ...
    value.absent_evidence.frequency_bound_measurements);
fprintf("Settings without usvseg_prm.mat: %s (verified run configuration: %d)\n", ...
    value.primary_run.settings_status, ...
    value.primary_run.settings_verified_run_configuration);
fprintf("Settings with usvseg_prm.mat: %s / %s (verified run configuration: %d)\n", ...
    value.weak_settings_evidence.settings_status, ...
    value.weak_settings_evidence.settings_evidence_strength, ...
    value.weak_settings_evidence.verified_run_configuration);
disp("Unexpected source column preserved rather than discarded:")
disp(value.weak_settings_evidence.unmapped_source_values)
fprintf("Zero-detection pass: %s, %d detections, run registered: %d\n", ...
    value.zero_detection_run.status, ...
    value.zero_detection_run.detection_count, ...
    value.zero_detection_run.extraction_run_registered);
fprintf("Rerun reused the run: %d; scientific rows unchanged: %d\n", ...
    value.rerun.extraction_run_id_stable, value.rerun.rows_unchanged);
fprintf("Foreign-key violations: %d; temporary artifacts removed: %d\n", ...
    height(value.foreign_key_check), value.temporary_artifacts_removed);
fprintf("Proves:\n  %s\n", strjoin(value.proves, newline + "  "));
fprintf("Does not prove:\n  %s\n", ...
    strjoin(value.does_not_prove, newline + "  "));
end
