function [aligned, transform] = applyTransform(conn, alignmentRunId, nativeTimes)
%APPLYTRANSFORM Express native source times on the reference clock.
%
% ALIGNED = vawlume.alignment.applyTransform(CONN, ALIGNMENTRUNID, NATIVETIMES)
% reads the stored segment coefficients for one pairwise transform and returns
%
%   aligned = scale * nativeTimes + offset_s
%
% preserving the shape of NATIVETIMES.
%
% [ALIGNED, TRANSFORM] = ... also returns the coefficients, clocks, method, fit
% summary, and status actually used, so a caller can record what produced a
% number rather than carrying a bare vector around.
%
% **It never refits.** The stored transform is the authority; recomputing here
% could silently disagree with the residuals persisted beside it. It also writes
% nothing: detections, external events, and anchor observations keep their native
% timestamps, and an aligned value is derived on demand.
%
% A run that has not been fitted, or whose fit was rejected or failed, raises
% rather than returning a plausible-looking number.

arguments
    conn
    alignmentRunId (1,1) double {mustBePositive, mustBeInteger}
    nativeTimes double
end

rows = fetch(conn, "SELECT r.alignment_run_id, r.method, r.status, " + ...
    "IFNULL(r.n_anchors_used,-1) AS n_anchors_used, " + ...
    "IFNULL(r.fit_rmse_s,-1) AS fit_rmse_s, " + ...
    "IFNULL(r.max_error_s,-1) AS max_error_s, " + ...
    "src.timebase_name AS source_timebase_key, " + ...
    "ref.timebase_name AS reference_timebase_key " + ...
    "FROM time_alignment_runs r " + ...
    "JOIN timebases src ON src.timebase_id=r.source_timebase_id " + ...
    "JOIN timebases ref ON ref.timebase_id=r.target_timebase_id " + ...
    "WHERE r.alignment_run_id=" + string(alignmentRunId));
if isempty(rows) || height(rows) == 0
    error("vawlume:alignment:TransformRunNotFound", ...
        "No pairwise transform run has id %d.", alignmentRunId);
end

status = presentText(rows.status(1));
if ismember(status, ["rejected", "failed"])
    error("vawlume:alignment:TransformNotUsable", ...
        ['Transform run %d has status ''%s''. A rejected or failed fit must not ' ...
        'be used to place events on another clock.'], alignmentRunId, status);
end
if status == "registered"
    error("vawlume:alignment:TransformNotFitted", ...
        ['Transform run %d is registered but not fitted. Fit it with ' ...
        'vawlume.alignment.fit before applying it.'], alignmentRunId);
end

segments = fetch(conn, "SELECT segment_index, scale, offset_s, " + ...
    "IFNULL(rmse_s,-1) AS rmse_s FROM alignment_segments " + ...
    "WHERE alignment_run_id=" + string(alignmentRunId) + " ORDER BY segment_index");
if isempty(segments) || height(segments) == 0
    error("vawlume:alignment:TransformSegmentMissing", ...
        "Transform run %d has status '%s' but stores no segment coefficients.", ...
        alignmentRunId, status);
end
if height(segments) > 1
    % Representable in the schema, not implemented here. Applying the first
    % segment to every time would silently produce wrong answers outside it.
    error("vawlume:alignment:PiecewiseNotImplemented", ...
        ['Transform run %d stores %d segments. Piecewise segment selection is ' ...
        'not implemented, and applying one segment across the whole clock would ' ...
        'be wrong outside its range.'], alignmentRunId, height(segments));
end

scale = double(segments.scale(1));
offset = double(segments.offset_s(1));
aligned = scale * nativeTimes + offset;

transform = struct( ...
    alignment_run_id=double(rows.alignment_run_id(1)), ...
    source_timebase_key=presentText(rows.source_timebase_key(1)), ...
    reference_timebase_key=presentText(rows.reference_timebase_key(1)), ...
    method=presentText(rows.method(1)), ...
    scale=scale, ...
    offset_s=offset, ...
    n_anchors_used=optionalNumber(rows.n_anchors_used(1)), ...
    rmse_s=optionalNumber(rows.fit_rmse_s(1)), ...
    max_abs_residual_s=optionalNumber(rows.max_error_s(1)), ...
    status=status, ...
    source="stored alignment_segments coefficients; not refitted");
end

function value = optionalNumber(raw)
value = double(raw);
if value < 0
    value = NaN;
end
end

function value = presentText(value)
value = string(value);
value(ismissing(value)) = "";
end
