function value = commonTime(conn, alignmentRef, options)
%COMMONTIME Read calls and external events on one stored reference clock.
%
% VALUE = vawlume.alignment.commonTime(CONN, ALIGNMENTREF, ...) returns a
% normalized derived event table plus observed coverage intervals. Native
% timestamps remain beside aligned timestamps and are never updated.
%
% Name-value options:
%   VocalizationSource  "none", "detections", or "consensus_events"
%   VocalizationRunId   extraction_run_id or analysis_run_id for that source
%   IncludeExternal     include external_events for the aligned recording
%   ErrorOnOutsideCoverage  reject events outside declared stream coverage

% Detections and consensus events inherit the recording-native timebase. A
% caller must select their population explicitly; consensus is never silently
% substituted for unmatched or ambiguous detections.

% aligned_external_events is an optional cache only. This function derives all
% aligned values from native evidence plus stored alignment_segments.

arguments
    conn
    alignmentRef (1,1) struct
    options.VocalizationSource (1,1) string {mustBeMember(options.VocalizationSource, ...
        ["none", "detections", "consensus_events"])} = "none"
    options.VocalizationRunId (1,1) double = NaN
    options.IncludeExternal (1,1) logical = true
    options.ErrorOnOutsideCoverage (1,1) logical = true
end

context = resolveContext(conn, alignmentRef);
events = emptyEvents();
coverage = emptyCoverage();

if options.VocalizationSource ~= "none"
    validateattributes(options.VocalizationRunId, {'double'}, ...
        {'scalar', 'finite', 'positive', 'integer'}, mfilename, ...
        'VocalizationRunId');
    [callEvents, callCoverage] = readCalls(conn, context, ...
        options.VocalizationSource, options.VocalizationRunId);
    events = [events; callEvents];
    coverage = [coverage; callCoverage];
end

if options.IncludeExternal
    [externalEvents, externalCoverage] = readExternal(conn, context);
    events = [events; externalEvents];
    coverage = [coverage; externalCoverage];
end

if ~isempty(events)
    [~, order] = sortrows([events.aligned_start, events.event_id], [1 2]);
    events = events(order, :);
end
if ~isempty(coverage)
    [~, order] = sortrows([double(categorical(coverage.coverage_key)), ...
        coverage.aligned_start], [1 2]);
    coverage = coverage(order, :);
end

outside = eventsOutsideCoverage(events, coverage);
if ~isempty(outside)
    message = sprintf('%d event(s) fall outside declared observed coverage; first: %s id %g.', ...
        height(outside), outside.event_source_kind(1), outside.event_id(1));
    if options.ErrorOnOutsideCoverage
        error("vawlume:alignment:EventOutsideCoverage", "%s", message);
    else
        warning("vawlume:alignment:EventOutsideCoverage", "%s", message);
    end
end

value = struct( ...
    events=events, coverage=coverage, ...
    specification=struct( ...
        alignment_set_id=context.alignment_set_id, ...
        recording_id=context.recording_id, ...
        reference_timebase_id=context.reference_timebase_id, ...
        reference_timebase_key=context.reference_timebase_key, ...
        vocalization_source=options.VocalizationSource, ...
        vocalization_run_id=options.VocalizationRunId, ...
        include_external=options.IncludeExternal, ...
        outside_coverage_policy=conditional(options.ErrorOnOutsideCoverage, ...
            "error", "warning"), ...
        authority="native timestamp + source timebase + stored transform", ...
        materialization="aligned_external_events is an optional cache; not read"), ...
    alignment=vawlume.alignment.report(conn, ...
        struct(alignment_set_id=context.alignment_set_id)));
end

function value = resolveContext(conn, alignmentRef)
hasId = isfield(alignmentRef, "alignment_set_id");
hasKey = isfield(alignmentRef, "run_key");
if hasId == hasKey
    error("vawlume:alignment:AlignmentRefInvalid", ...
        "alignmentRef must contain exactly one of alignment_set_id or run_key.");
end
if hasId
    predicate = "aset.alignment_set_id=" + string(scalarId( ...
        alignmentRef.alignment_set_id, "alignment_set_id"));
else
    predicate = "ar.run_key=" + sqlText(alignmentRef.run_key);
    if isfield(alignmentRef, "project_key")
        predicate = predicate + " AND p.project_key=" + ...
            sqlText(alignmentRef.project_key);
    end
end
rows = fetch(conn, "SELECT aset.alignment_set_id, aset.recording_id, " + ...
    "aset.reference_timebase_id, ref.timebase_name AS reference_timebase_key " + ...
    "FROM alignment_sets aset " + ...
    "JOIN analysis_runs ar ON ar.analysis_run_id=aset.analysis_run_id " + ...
    "JOIN projects p ON p.project_id=ar.project_id " + ...
    "JOIN timebases ref ON ref.timebase_id=aset.reference_timebase_id " + ...
    "WHERE " + predicate);
if isempty(rows) || height(rows) == 0
    error("vawlume:alignment:AlignmentSetNotFound", ...
        "No alignment set matches alignmentRef.");
end
if height(rows) ~= 1
    error("vawlume:alignment:AlignmentSetAmbiguous", ...
        "alignmentRef matched %d alignment sets.", height(rows));
end
recordingId = double(rows.recording_id(1));
if isnan(recordingId)
    error("vawlume:alignment:RecordingRequired", ...
        "Common-time event projection requires an alignment set recording_id.");
end
native = fetch(conn, "SELECT timebase_id, timebase_name FROM timebases " + ...
    "WHERE recording_id=" + string(recordingId) + " AND is_recording_native=1");
if isempty(native) || height(native) ~= 1
    error("vawlume:alignment:RecordingTimebaseMissing", ...
        "Recording %d must have exactly one native timebase.", recordingId);
end
value = struct(alignment_set_id=double(rows.alignment_set_id(1)), ...
    recording_id=recordingId, ...
    reference_timebase_id=double(rows.reference_timebase_id(1)), ...
    reference_timebase_key=presentText(rows.reference_timebase_key(1)), ...
    recording_timebase_id=double(native.timebase_id(1)), ...
    recording_timebase_key=presentText(native.timebase_name(1)));
end

function [events, coverage] = readCalls(conn, context, sourceKind, runId)
if sourceKind == "detections"
    rows = fetch(conn, "SELECT detection_id AS event_id, recording_id, " + ...
        "start_time_s AS native_start, end_time_s AS native_end, " + ...
        "event_subtype AS event_key FROM detections WHERE recording_id=" + ...
        string(context.recording_id) + " AND extraction_run_id=" + string(runId) + ...
        " ORDER BY detection_id");
    label = "detection";
else
    rows = fetch(conn, "SELECT consensus_event_id AS event_id, recording_id, " + ...
        "start_time_s AS native_start, end_time_s AS native_end, " + ...
        "derivation_method AS event_key FROM consensus_events WHERE recording_id=" + ...
        string(context.recording_id) + " AND analysis_run_id=" + string(runId) + ...
        " ORDER BY consensus_event_id");
    label = "consensus_event";
end
events = rowsToEvents(conn, rows, context, label, NaN, ...
    context.recording_timebase_id, context.recording_timebase_key, ...
    "vocalization", "recording:" + string(context.recording_id));

duration = fetch(conn, "SELECT IFNULL(duration_s,-1) AS duration_s " + ...
    "FROM recordings WHERE recording_id=" + string(context.recording_id));
coverage = emptyCoverage();
if ~isempty(duration) && double(duration.duration_s(1)) >= 0
    coverage = coverageRow(conn, context, NaN, context.recording_timebase_id, ...
        context.recording_timebase_key, 1, 0, double(duration.duration_s(1)), ...
        "recording:" + string(context.recording_id), ...
        "recordings.duration_s");
end
end

function [events, coverage] = readExternal(conn, context)
rows = fetch(conn, "SELECT ee.external_event_id AS event_id, " + ...
    "es.recording_id, es.external_stream_id, es.timebase_id, " + ...
    "tb.timebase_name AS timebase_key, ee.start_time_native AS native_start, " + ...
    "IFNULL(ee.end_time_native,1e308) AS native_end, ee.event_type AS event_key, " + ...
    "IFNULL(ee.native_event_label,'') AS native_label, " + ...
    "IFNULL(ee.entity_id,-1) AS entity_id " + ...
    "FROM external_events ee JOIN external_streams es " + ...
    "ON es.external_stream_id=ee.external_stream_id " + ...
    "JOIN timebases tb ON tb.timebase_id=es.timebase_id " + ...
    "WHERE es.recording_id=" + string(context.recording_id) + ...
    " ORDER BY ee.external_event_id");
events = emptyEvents();
for index = 1:height(rows)
    row = rows(index, :);
    nativeEnd = double(row.native_end(1));
    if nativeEnd >= 1e307, nativeEnd = NaN; end
    one = table(double(row.event_id(1)), double(row.recording_id(1)), ...
        double(row.native_start(1)), nativeEnd, presentText(row.event_key(1)), ...
        VariableNames=["event_id", "recording_id", "native_start", ...
        "native_end", "event_key"]);
    projected = rowsToEvents(conn, one, context, "external_event", ...
        double(row.external_stream_id(1)), double(row.timebase_id(1)), ...
        presentText(row.timebase_key(1)), presentText(row.event_key(1)), ...
        "external_stream:" + string(double(row.external_stream_id(1))));
    projected.native_event_label(1) = presentText(row.native_label(1));
    entityId = double(row.entity_id(1));
    if entityId >= 0, projected.entity_id(1) = entityId; end
    events = [events; projected]; %#ok<AGROW>
end

segments = fetch(conn, "SELECT c.external_stream_coverage_id, " + ...
    "c.external_stream_id, es.timebase_id, tb.timebase_name AS timebase_key, " + ...
    "c.segment_index, c.start_time_native, c.end_time_native " + ...
    "FROM external_stream_coverage c JOIN external_streams es " + ...
    "ON es.external_stream_id=c.external_stream_id " + ...
    "JOIN timebases tb ON tb.timebase_id=es.timebase_id " + ...
    "WHERE es.recording_id=" + string(context.recording_id) + ...
    " ORDER BY c.external_stream_id, c.segment_index");
coverage = emptyCoverage();
for index = 1:height(segments)
    row = segments(index, :);
    coverage = [coverage; coverageRow(conn, context, ...
        double(row.external_stream_id(1)), double(row.timebase_id(1)), ...
        presentText(row.timebase_key(1)), double(row.segment_index(1)), ...
        double(row.start_time_native(1)), double(row.end_time_native(1)), ...
        "external_stream:" + string(double(row.external_stream_id(1))), ...
        "external_stream_coverage")]; %#ok<AGROW>
end
end

function value = rowsToEvents(conn, rows, context, sourceKind, streamId, ...
        timebaseId, timebaseKey, normalizedKey, coverageKey)
value = emptyEvents();
if isempty(rows), return; end
[alignedStart, alignedEnd, runId, alignmentKind] = projectInterval( ...
    conn, context, timebaseId, double(rows.native_start), ...
    double(rows.native_end));
for index = 1:height(rows)
    key = normalizedKey;
    if sourceKind == "external_event"
        key = presentText(rows.event_key(index));
    end
    nativeLabel = "";
    value(end + 1, :) = {sourceKind, double(rows.event_id(index)), ...
        double(rows.recording_id(index)), streamId, timebaseId, timebaseKey, ...
        context.reference_timebase_id, context.reference_timebase_key, ...
        double(rows.native_start(index)), double(rows.native_end(index)), ...
        alignedStart(index), alignedEnd(index), key, nativeLabel, NaN, ...
        context.alignment_set_id, runId, alignmentKind, coverageKey, ...
        "derived from native row; source population selected explicitly"}; %#ok<AGROW>
end
end

function value = coverageRow(conn, context, streamId, timebaseId, timebaseKey, ...
        segmentIndex, nativeStart, nativeEnd, coverageKey, provenance)
[alignedStart, alignedEnd, runId, alignmentKind] = projectInterval( ...
    conn, context, timebaseId, nativeStart, nativeEnd);
value = table(coverageKey, streamId, timebaseId, timebaseKey, ...
    context.reference_timebase_id, context.reference_timebase_key, ...
    segmentIndex, nativeStart, nativeEnd, alignedStart, alignedEnd, ...
    runId, alignmentKind, "observed", provenance, ...
    VariableNames=["coverage_key", "source_stream_id", ...
    "source_timebase_id", "source_timebase_key", ...
    "reference_timebase_id", "reference_timebase_key", "segment_index", ...
    "native_start", "native_end", "aligned_start", "aligned_end", ...
    "alignment_run_id", "alignment_kind", "observation_status", "provenance"]);
end

function [alignedStart, alignedEnd, runId, kind] = projectInterval( ...
        conn, context, timebaseId, nativeStart, nativeEnd)
if timebaseId == context.reference_timebase_id
    alignedStart = nativeStart;
    alignedEnd = nativeEnd;
    runId = NaN;
    kind = "identity";
else
    runs = fetch(conn, "SELECT alignment_run_id FROM time_alignment_runs " + ...
        "WHERE alignment_set_id=" + string(context.alignment_set_id) + ...
        " AND source_timebase_id=" + string(timebaseId));
    if isempty(runs) || height(runs) == 0
        error("vawlume:alignment:TransformRunNotFound", ...
            "Alignment set %d has no transform for timebase %d.", ...
            context.alignment_set_id, timebaseId);
    end
    if height(runs) ~= 1
        error("vawlume:alignment:TransformRunAmbiguous", ...
            "Alignment set %d has multiple transforms for timebase %d.", ...
            context.alignment_set_id, timebaseId);
    end
    runId = double(runs.alignment_run_id(1));
    [alignedStart, transform] = vawlume.alignment.applyTransform( ...
        conn, runId, nativeStart);
    alignedEnd = nativeEnd;
    finiteEnd = isfinite(nativeEnd);
    if any(finiteEnd)
        alignedEnd(finiteEnd) = vawlume.alignment.applyTransform( ...
            conn, runId, nativeEnd(finiteEnd));
    end
    if transform.scale <= 0
        error("vawlume:alignment:NonPositiveTransformScale", ...
            "Transform run %d has non-positive scale %g.", runId, transform.scale);
    end
    kind = "stored_transform";
end
finiteIntervals = isfinite(nativeEnd);
if any(alignedEnd(finiteIntervals) < alignedStart(finiteIntervals))
    error("vawlume:alignment:AlignedIntervalInvalid", ...
        "A projected event or coverage interval ends before it starts.");
end
end

function value = eventsOutsideCoverage(events, coverage)
outside = false(height(events), 1);
for index = 1:height(events)
    candidates = coverage(coverage.coverage_key == events.coverage_key(index), :);
    if isempty(candidates)
        continue
    end
    eventEnd = events.aligned_end(index);
    if ~isfinite(eventEnd), eventEnd = events.aligned_start(index); end
    inside = candidates.aligned_start <= events.aligned_start(index) & ...
        candidates.aligned_end >= eventEnd;
    outside(index) = ~any(inside);
end
value = events(outside, :);
end

function value = emptyEvents()
value = table(strings(0, 1), zeros(0, 1), zeros(0, 1), zeros(0, 1), ...
    zeros(0, 1), strings(0, 1), zeros(0, 1), strings(0, 1), ...
    zeros(0, 1), zeros(0, 1), zeros(0, 1), zeros(0, 1), ...
    strings(0, 1), strings(0, 1), zeros(0, 1), zeros(0, 1), ...
    zeros(0, 1), strings(0, 1), strings(0, 1), strings(0, 1), ...
    VariableNames=["event_source_kind", "event_id", "recording_id", ...
    "source_stream_id", "source_timebase_id", "source_timebase_key", ...
    "reference_timebase_id", "reference_timebase_key", "native_start", ...
    "native_end", "aligned_start", "aligned_end", "normalized_event_key", ...
    "native_event_label", "entity_id", "alignment_set_id", ...
    "alignment_run_id", "alignment_kind", "coverage_key", "provenance"]);
end

function value = emptyCoverage()
value = table(strings(0, 1), zeros(0, 1), zeros(0, 1), strings(0, 1), ...
    zeros(0, 1), strings(0, 1), zeros(0, 1), zeros(0, 1), zeros(0, 1), ...
    zeros(0, 1), zeros(0, 1), zeros(0, 1), strings(0, 1), strings(0, 1), ...
    strings(0, 1), VariableNames=["coverage_key", "source_stream_id", ...
    "source_timebase_id", "source_timebase_key", ...
    "reference_timebase_id", "reference_timebase_key", "segment_index", ...
    "native_start", "native_end", "aligned_start", "aligned_end", ...
    "alignment_run_id", "alignment_kind", "observation_status", "provenance"]);
end

function value = scalarId(raw, label)
validateattributes(raw, {'numeric'}, {'scalar', 'finite', 'positive', 'integer'}, ...
    mfilename, label);
value = double(raw);
end

function value = sqlText(raw)
raw = string(raw);
if ~isscalar(raw) || ismissing(raw) || strlength(raw) == 0
    error("vawlume:alignment:AlignmentRefInvalid", ...
        "Alignment reference text must be a nonempty scalar.");
end
value = "'" + replace(raw, "'", "''") + "'";
end

function value = presentText(raw)
value = string(raw);
value(ismissing(value)) = "";
end

function value = conditional(condition, whenTrue, whenFalse)
if condition, value = whenTrue; else, value = whenFalse; end
end
