function value = report(conn, alignmentRef)
%REPORT Read back the stored transforms and residual evidence for an alignment.
%
% VALUE = vawlume.alignment.report(CONN, ALIGNMENTREF) returns what is actually
% persisted: the alignment set, one row per pairwise transform with its
% coefficients and fit summary, and one row per stored anchor residual naming both
% observations it was computed from.
%
% This is read-only and refits nothing. It differs from the planning mode of
% VAWLUME.ALIGNMENT.FIT, which recomputes coefficients from anchors: this reports
% the fit of record, which is what downstream work must use.
%
% ALIGNMENTREF accepts the same selectors as VAWLUME.ALIGNMENT.FIT.
%
% The reference timebase is a **coordinate choice** for this alignment, not an
% assertion that one device's clock is correct. Every transform in a set
% expresses one source clock in that chosen frame; nothing here ranks the clocks
% or treats the reference as ground truth.
%
% VALUE fields:
%
%   alignment_set_id, analysis_run_id, run_key, project_key, set_status
%   reference_timebase
%   transforms       one row per source clock, with its status and failure code
%   segments         one row per stored segment, with bounds and per-segment QC
%   breakpoints      the declared segmentation of each piecewise transform
%   residuals        per-anchor fit evidence, including withheld anchors
%   anchor_dispersion  replicate spread per anchor and clock, derived on read
%   anchor_diagnostics whether the anchors could support the model asked of
%                      them: counts, the span they covered, and the largest gap
%                      within it, derived on read
%   clocks_without_transform  clocks carrying anchor readings that no transform
%                      in this set can use
%   failures         every transform that was attempted and could not be fitted
%   uncertainty_note, dispersion_note
%
% Dispersion is derived here rather than stored, for the reason given in the
% temporal-alignment contract: it is a pure function of the observations, and a
% stored copy would be a second thing to keep current.

arguments
    conn
    alignmentRef (1,1) struct
end

set = resolveSet(conn, alignmentRef);

transforms = fetch(conn, "SELECT r.alignment_run_id, " + ...
    "src.timebase_name AS source_timebase_key, " + ...
    "ref.timebase_name AS reference_timebase_key, r.method, r.status, " + ...
    "IFNULL(r.n_anchors_used,-1) AS n_anchors_used, " + ...
    "IFNULL(r.fit_rmse_s,-1) AS fit_rmse_s, " + ...
    "IFNULL(r.max_error_s,-1) AS max_error_s, " + ...
    "IFNULL(seg.scale, 1e308) AS scale, " + ...
    "IFNULL(seg.offset_s, 1e308) AS offset_s, " + ...
    "IFNULL(seg.segment_count, 0) AS segment_count, " + ...
    "IFNULL(r.failure_code,'') AS failure_code, " + ...
    "IFNULL(r.failure_reason,'') AS failure_reason " + ...
    "FROM time_alignment_runs r " + ...
    "JOIN timebases src ON src.timebase_id=r.source_timebase_id " + ...
    "JOIN timebases ref ON ref.timebase_id=r.target_timebase_id " + ...
    "LEFT JOIN (SELECT alignment_run_id, MIN(scale) AS scale, " + ...
    "MIN(offset_s) AS offset_s, COUNT(*) AS segment_count " + ...
    "FROM alignment_segments GROUP BY alignment_run_id) seg " + ...
    "ON seg.alignment_run_id=r.alignment_run_id " + ...
    "WHERE r.alignment_set_id=" + string(set.alignment_set_id) + ...
    " ORDER BY src.timebase_name");

segments = fetch(conn, "SELECT s.alignment_run_id, " + ...
    "src.timebase_name AS source_timebase_key, s.segment_index, " + ...
    "IFNULL(s.source_start, 1e308) AS source_start, " + ...
    "IFNULL(s.source_end, 1e308) AS source_end, s.scale, s.offset_s, " + ...
    "IFNULL(s.rmse_s,-1) AS rmse_s, " + ...
    "IFNULL(s.uncertainty_s,-1) AS uncertainty_s, " + ...
    "IFNULL(s.uncertainty_semantics,'') AS uncertainty_semantics " + ...
    "FROM alignment_segments s " + ...
    "JOIN time_alignment_runs r ON r.alignment_run_id=s.alignment_run_id " + ...
    "JOIN timebases src ON src.timebase_id=r.source_timebase_id " + ...
    "WHERE r.alignment_set_id=" + string(set.alignment_set_id) + ...
    " ORDER BY src.timebase_name, s.segment_index");

breakpoints = fetch(conn, "SELECT b.alignment_run_id, " + ...
    "src.timebase_name AS source_timebase_key, b.breakpoint_index, " + ...
    "b.source_time, IFNULL(b.declared_by,'') AS declared_by " + ...
    "FROM alignment_run_breakpoints b " + ...
    "JOIN time_alignment_runs r ON r.alignment_run_id=b.alignment_run_id " + ...
    "JOIN timebases src ON src.timebase_id=r.source_timebase_id " + ...
    "WHERE r.alignment_set_id=" + string(set.alignment_set_id) + ...
    " ORDER BY src.timebase_name, b.breakpoint_index");

% Replicate spread, computed from the observations rather than read from a
% stored copy. One row per anchor and clock that carries more than one reading.
dispersion = fetch(conn, "SELECT a.anchor_key, o.timebase_id, " + ...
    "tb.timebase_name AS timebase_key, COUNT(*) AS observation_count, " + ...
    "MAX(o.observed_time_native) - MIN(o.observed_time_native) AS spread_s " + ...
    "FROM alignment_anchor_observations o " + ...
    "JOIN alignment_anchors a ON a.alignment_anchor_id=o.alignment_anchor_id " + ...
    "JOIN timebases tb ON tb.timebase_id=o.timebase_id " + ...
    "WHERE a.alignment_set_id=" + string(set.alignment_set_id) + ...
    " GROUP BY a.anchor_key, o.timebase_id, tb.timebase_name " + ...
    "HAVING COUNT(*) > 1 ORDER BY a.anchor_key, tb.timebase_name");

% Clocks that carry readings no transform in this set can use. Legal - a clock
% may be registered before its transform is - and equally often a manifest that
% named a stream and forgot its transform. The reference clock is excluded:
% every anchor is read on it by definition, and it needs no transform of its own.
stray = fetch(conn, "SELECT o.timebase_id, tb.timebase_name AS timebase_key, " + ...
    "COUNT(*) AS observation_count " + ...
    "FROM alignment_anchor_observations o " + ...
    "JOIN alignment_anchors a ON a.alignment_anchor_id=o.alignment_anchor_id " + ...
    "JOIN timebases tb ON tb.timebase_id=o.timebase_id " + ...
    "WHERE a.alignment_set_id=" + string(set.alignment_set_id) + ...
    " AND o.timebase_id <> " + string(set.reference_timebase_id) + ...
    " AND o.timebase_id NOT IN (SELECT source_timebase_id " + ...
    "FROM time_alignment_runs WHERE alignment_set_id=" + ...
    string(set.alignment_set_id) + ") " + ...
    "GROUP BY o.timebase_id, tb.timebase_name ORDER BY tb.timebase_name");

residuals = fetch(conn, "SELECT res.alignment_run_id, " + ...
    "src.timebase_name AS source_timebase_key, a.anchor_key, " + ...
    "res.source_observation_id, res.reference_observation_id, " + ...
    "res.observed_source_time, res.observed_reference_time, " + ...
    "res.predicted_reference_time, res.residual_s, res.included_in_fit, " + ...
    "IFNULL(res.exclusion_reason,'') AS exclusion_reason " + ...
    "FROM alignment_anchor_residuals res " + ...
    "JOIN alignment_anchors a ON a.alignment_anchor_id=res.alignment_anchor_id " + ...
    "JOIN time_alignment_runs r ON r.alignment_run_id=res.alignment_run_id " + ...
    "JOIN timebases src ON src.timebase_id=r.source_timebase_id " + ...
    "WHERE r.alignment_set_id=" + string(set.alignment_set_id) + ...
    " ORDER BY src.timebase_name, a.anchor_key");

value = struct( ...
    alignment_set_id=set.alignment_set_id, ...
    analysis_run_id=set.analysis_run_id, ...
    run_key=set.run_key, ...
    project_key=set.project_key, ...
    set_status=set.status, ...
    reference_timebase=struct(timebase_id=set.reference_timebase_id, ...
        timebase_key=set.reference_timebase_key), ...
    transforms=normalizeTransforms(transforms), ...
    segments=normalizeSegments(segments), ...
    breakpoints=normalizeBreakpoints(breakpoints), ...
    anchor_dispersion=normalizeDispersion(dispersion), ...
    clocks_without_transform=normalizeStray(stray), ...
    residuals=normalizeResiduals(residuals), ...
    uncertainty_note=uncertaintyNote(), ...
    dispersion_note=dispersionNote(), ...
    source="stored alignment_segments and alignment_anchor_residuals");
value.failures = value.transforms(value.transforms.status == "failed", ...
    ["alignment_run_id", "source_timebase_key", "method", ...
    "failure_code", "failure_reason"]);
value.anchor_diagnostics = diagnosticsFromResiduals(value.residuals, ...
    value.transforms);
end

function value = resolveSet(conn, alignmentRef)
hasId = isfield(alignmentRef, "alignment_set_id");
hasKey = isfield(alignmentRef, "run_key");
if hasId == hasKey
    error("vawlume:alignment:AlignmentRefInvalid", ...
        "alignmentRef must contain exactly one of alignment_set_id or run_key.");
end
if hasId
    predicate = "aset.alignment_set_id=" + string(double(alignmentRef.alignment_set_id));
else
    predicate = "ar.run_key='" + replace(string(alignmentRef.run_key), "'", "''") + "'";
    if isfield(alignmentRef, "project_key")
        predicate = predicate + " AND p.project_key='" + ...
            replace(string(alignmentRef.project_key), "'", "''") + "'";
    end
end
rows = fetch(conn, "SELECT aset.alignment_set_id, aset.analysis_run_id, " + ...
    "aset.reference_timebase_id, aset.status, ar.run_key, p.project_key, " + ...
    "tb.timebase_name AS reference_timebase_key " + ...
    "FROM alignment_sets aset " + ...
    "JOIN analysis_runs ar ON ar.analysis_run_id=aset.analysis_run_id " + ...
    "JOIN projects p ON p.project_id=ar.project_id " + ...
    "JOIN timebases tb ON tb.timebase_id=aset.reference_timebase_id " + ...
    "WHERE " + predicate);
if isempty(rows) || height(rows) == 0
    error("vawlume:alignment:AlignmentSetNotFound", ...
        "No alignment set matches alignmentRef.");
end
if height(rows) ~= 1
    error("vawlume:alignment:AlignmentSetAmbiguous", ...
        "alignmentRef matched %d alignment sets.", height(rows));
end
value = struct( ...
    alignment_set_id=double(rows.alignment_set_id(1)), ...
    analysis_run_id=double(rows.analysis_run_id(1)), ...
    reference_timebase_id=double(rows.reference_timebase_id(1)), ...
    reference_timebase_key=presentText(rows.reference_timebase_key(1)), ...
    status=presentText(rows.status(1)), ...
    run_key=presentText(rows.run_key(1)), ...
    project_key=presentText(rows.project_key(1)));
end

function value = normalizeTransforms(rows)
value = table(zeros(0, 1), strings(0, 1), strings(0, 1), strings(0, 1), ...
    strings(0, 1), zeros(0, 1), zeros(0, 1), zeros(0, 1), zeros(0, 1), ...
    zeros(0, 1), zeros(0, 1), strings(0, 1), strings(0, 1), ...
    VariableNames=["alignment_run_id", "source_timebase_key", ...
    "reference_timebase_key", "method", "status", "scale", "offset_s", ...
    "n_anchors_used", "rmse_s", "max_abs_residual_s", "segment_count", ...
    "failure_code", "failure_reason"]);
for index = 1:height(rows)
    segmentCount = double(rows.segment_count(index));
    scale = sentinelNumber(rows.scale(index));
    offset = sentinelNumber(rows.offset_s(index));
    if segmentCount > 1
        % A segmented transform has no single slope. The query aggregates the
        % segment rows, and reporting that aggregate would be a number belonging
        % to no part of the clock. The segments table carries the real ones.
        scale = NaN;
        offset = NaN;
    end
    value(end + 1, :) = {double(rows.alignment_run_id(index)), ...
        presentText(rows.source_timebase_key(index)), ...
        presentText(rows.reference_timebase_key(index)), ...
        presentText(rows.method(index)), presentText(rows.status(index)), ...
        scale, offset, ...
        negativeSentinel(rows.n_anchors_used(index)), ...
        negativeSentinel(rows.fit_rmse_s(index)), ...
        negativeSentinel(rows.max_error_s(index)), ...
        segmentCount, presentText(rows.failure_code(index)), ...
        presentText(rows.failure_reason(index))}; %#ok<AGROW>
end
end

function value = normalizeSegments(rows)
value = table(zeros(0, 1), strings(0, 1), zeros(0, 1), zeros(0, 1), ...
    zeros(0, 1), zeros(0, 1), zeros(0, 1), zeros(0, 1), zeros(0, 1), ...
    strings(0, 1), ...
    VariableNames=["alignment_run_id", "source_timebase_key", ...
    "segment_index", "source_start", "source_end", "scale", "offset_s", ...
    "rmse_s", "uncertainty_s", "uncertainty_semantics"]);
for index = 1:height(rows)
    value(end + 1, :) = {double(rows.alignment_run_id(index)), ...
        presentText(rows.source_timebase_key(index)), ...
        double(rows.segment_index(index)), ...
        sentinelNumber(rows.source_start(index)), ...
        sentinelNumber(rows.source_end(index)), ...
        double(rows.scale(index)), double(rows.offset_s(index)), ...
        negativeSentinel(rows.rmse_s(index)), ...
        negativeSentinel(rows.uncertainty_s(index)), ...
        presentText(rows.uncertainty_semantics(index))}; %#ok<AGROW>
end
end

function value = normalizeBreakpoints(rows)
value = table(zeros(0, 1), strings(0, 1), zeros(0, 1), zeros(0, 1), ...
    strings(0, 1), ...
    VariableNames=["alignment_run_id", "source_timebase_key", ...
    "breakpoint_index", "source_time", "declared_by"]);
for index = 1:height(rows)
    value(end + 1, :) = {double(rows.alignment_run_id(index)), ...
        presentText(rows.source_timebase_key(index)), ...
        double(rows.breakpoint_index(index)), ...
        double(rows.source_time(index)), ...
        presentText(rows.declared_by(index))}; %#ok<AGROW>
end
end

function value = normalizeDispersion(rows)
value = table(strings(0, 1), zeros(0, 1), strings(0, 1), zeros(0, 1), ...
    zeros(0, 1), ...
    VariableNames=["anchor_key", "timebase_id", "timebase_key", ...
    "observation_count", "spread_s"]);
for index = 1:height(rows)
    value(end + 1, :) = {presentText(rows.anchor_key(index)), ...
        double(rows.timebase_id(index)), ...
        presentText(rows.timebase_key(index)), ...
        double(rows.observation_count(index)), ...
        double(rows.spread_s(index))}; %#ok<AGROW>
end
end

function value = normalizeStray(rows)
value = table(zeros(0, 1), strings(0, 1), zeros(0, 1), ...
    VariableNames=["timebase_id", "timebase_key", "observation_count"]);
for index = 1:height(rows)
    value(end + 1, :) = {double(rows.timebase_id(index)), ...
        presentText(rows.timebase_key(index)), ...
        double(rows.observation_count(index))}; %#ok<AGROW>
end
end

function value = diagnosticsFromResiduals(residuals, transforms)
%DIAGNOSTICSFROMRESIDUALS Whether the anchors could support the model.
%
% Derived from the stored residuals, which is the same evidence the fitter used,
% so the read side and the plan side agree without a second stored copy.
%
% Every number here is reported for a reader to judge. None is a threshold, a
% grade, or a verdict: this prototype ships no calibrated acceptance criterion.
% The span and gap matter because anchors clustered at one end of a session
% support an offset far better than a slope, and a fit summary cannot show that.
value = table(zeros(0, 1), strings(0, 1), zeros(0, 1), zeros(0, 1), ...
    zeros(0, 1), zeros(0, 1), zeros(0, 1), zeros(0, 1), zeros(0, 1), ...
    VariableNames=["alignment_run_id", "source_timebase_key", ...
    "paired_anchor_count", "included_anchor_count", "withheld_anchor_count", ...
    "source_range_start", "source_range_end", "source_span_s", ...
    "largest_gap_fraction"]);
for index = 1:height(transforms)
    runId = transforms.alignment_run_id(index);
    rows = residuals(residuals.alignment_run_id == runId, :);
    included = sort(rows.observed_source_time(rows.included_in_fit == 1));
    rangeStart = NaN;
    rangeEnd = NaN;
    span = NaN;
    gap = NaN;
    if ~isempty(included)
        rangeStart = included(1);
        rangeEnd = included(end);
        span = rangeEnd - rangeStart;
        if numel(included) > 1 && span > 0
            gap = max(diff(included)) / span;
        end
    end
    value(end + 1, :) = {runId, transforms.source_timebase_key(index), ...
        height(rows), numel(included), nnz(rows.included_in_fit == 0), ...
        rangeStart, rangeEnd, span, gap}; %#ok<AGROW>
end
end

function value = uncertaintyNote()
value = "A segment's uncertainty_s is the largest recorded anchor " + ...
    "uncertainty among the anchors that determined it, on the reference " + ...
    "clock. It is uncalibrated: not a confidence interval, a standard error, " + ...
    "or a probability, and it is never combined with rmse_s.";
end

function value = dispersionNote()
value = "Replicate spread is derived from alignment_anchor_observations on " + ...
    "read and is never stored. A replicate is evidence about how consistently " + ...
    "a marker was read, never an extra statistical anchor. An anchor read " + ...
    "once has no dispersion and appears in no row here.";
end

function value = normalizeResiduals(rows)
value = table(zeros(0, 1), strings(0, 1), strings(0, 1), zeros(0, 1), ...
    zeros(0, 1), zeros(0, 1), zeros(0, 1), zeros(0, 1), zeros(0, 1), ...
    zeros(0, 1), strings(0, 1), ...
    VariableNames=["alignment_run_id", "source_timebase_key", "anchor_key", ...
    "source_observation_id", "reference_observation_id", ...
    "observed_source_time", "observed_reference_time", ...
    "predicted_reference_time", "residual_s", "included_in_fit", ...
    "exclusion_reason"]);
for index = 1:height(rows)
    value(end + 1, :) = {double(rows.alignment_run_id(index)), ...
        presentText(rows.source_timebase_key(index)), ...
        presentText(rows.anchor_key(index)), ...
        double(rows.source_observation_id(index)), ...
        double(rows.reference_observation_id(index)), ...
        double(rows.observed_source_time(index)), ...
        double(rows.observed_reference_time(index)), ...
        double(rows.predicted_reference_time(index)), ...
        double(rows.residual_s(index)), ...
        double(rows.included_in_fit(index)), ...
        presentText(rows.exclusion_reason(index))}; %#ok<AGROW>
end
end

function value = sentinelNumber(raw)
value = double(raw);
if value >= 1e307
    value = NaN;
end
end

function value = negativeSentinel(raw)
value = double(raw);
if value < 0
    value = NaN;
end
end

function value = presentText(value)
value = string(value);
value(ismissing(value)) = "";
end
