function value = report(conn, alignmentRef)
%REPORT Read back the stored transforms and residual evidence for an alignment.
%
% VALUE = vawlume.alignment.report(CONN, ALIGNMENTREF) returns what is actually
% persisted: the alignment set, one row per pairwise transform with its
% coefficients and fit summary, and one row per stored anchor residual naming both
% observations it was computed from.
%
% This is read-only and refits nothing. It differs from the planning mode of
% VAWLUME.ALIGNMENT.FIT, which recomputes coefficients from anchors: this reports
% the fit of record, which is what downstream work must use.
%
% ALIGNMENTREF accepts the same selectors as VAWLUME.ALIGNMENT.FIT.

arguments
    conn
    alignmentRef (1,1) struct
end

set = resolveSet(conn, alignmentRef);

transforms = fetch(conn, "SELECT r.alignment_run_id, " + ...
    "src.timebase_name AS source_timebase_key, " + ...
    "ref.timebase_name AS reference_timebase_key, r.method, r.status, " + ...
    "IFNULL(r.n_anchors_used,-1) AS n_anchors_used, " + ...
    "IFNULL(r.fit_rmse_s,-1) AS fit_rmse_s, " + ...
    "IFNULL(r.max_error_s,-1) AS max_error_s, " + ...
    "IFNULL(seg.scale, 1e308) AS scale, " + ...
    "IFNULL(seg.offset_s, 1e308) AS offset_s, " + ...
    "IFNULL(seg.segment_count, 0) AS segment_count " + ...
    "FROM time_alignment_runs r " + ...
    "JOIN timebases src ON src.timebase_id=r.source_timebase_id " + ...
    "JOIN timebases ref ON ref.timebase_id=r.target_timebase_id " + ...
    "LEFT JOIN (SELECT alignment_run_id, MIN(scale) AS scale, " + ...
    "MIN(offset_s) AS offset_s, COUNT(*) AS segment_count " + ...
    "FROM alignment_segments GROUP BY alignment_run_id) seg " + ...
    "ON seg.alignment_run_id=r.alignment_run_id " + ...
    "WHERE r.alignment_set_id=" + string(set.alignment_set_id) + ...
    " ORDER BY src.timebase_name");

residuals = fetch(conn, "SELECT res.alignment_run_id, " + ...
    "src.timebase_name AS source_timebase_key, a.anchor_key, " + ...
    "res.source_observation_id, res.reference_observation_id, " + ...
    "res.observed_source_time, res.observed_reference_time, " + ...
    "res.predicted_reference_time, res.residual_s, res.included_in_fit, " + ...
    "IFNULL(res.exclusion_reason,'') AS exclusion_reason " + ...
    "FROM alignment_anchor_residuals res " + ...
    "JOIN alignment_anchors a ON a.alignment_anchor_id=res.alignment_anchor_id " + ...
    "JOIN time_alignment_runs r ON r.alignment_run_id=res.alignment_run_id " + ...
    "JOIN timebases src ON src.timebase_id=r.source_timebase_id " + ...
    "WHERE r.alignment_set_id=" + string(set.alignment_set_id) + ...
    " ORDER BY src.timebase_name, a.anchor_key");

value = struct( ...
    alignment_set_id=set.alignment_set_id, ...
    analysis_run_id=set.analysis_run_id, ...
    run_key=set.run_key, ...
    project_key=set.project_key, ...
    set_status=set.status, ...
    reference_timebase=struct(timebase_id=set.reference_timebase_id, ...
        timebase_key=set.reference_timebase_key), ...
    transforms=normalizeTransforms(transforms), ...
    residuals=normalizeResiduals(residuals), ...
    source="stored alignment_segments and alignment_anchor_residuals");
end

function value = resolveSet(conn, alignmentRef)
hasId = isfield(alignmentRef, "alignment_set_id");
hasKey = isfield(alignmentRef, "run_key");
if hasId == hasKey
    error("vawlume:alignment:AlignmentRefInvalid", ...
        "alignmentRef must contain exactly one of alignment_set_id or run_key.");
end
if hasId
    predicate = "aset.alignment_set_id=" + string(double(alignmentRef.alignment_set_id));
else
    predicate = "ar.run_key='" + replace(string(alignmentRef.run_key), "'", "''") + "'";
    if isfield(alignmentRef, "project_key")
        predicate = predicate + " AND p.project_key='" + ...
            replace(string(alignmentRef.project_key), "'", "''") + "'";
    end
end
rows = fetch(conn, "SELECT aset.alignment_set_id, aset.analysis_run_id, " + ...
    "aset.reference_timebase_id, aset.status, ar.run_key, p.project_key, " + ...
    "tb.timebase_name AS reference_timebase_key " + ...
    "FROM alignment_sets aset " + ...
    "JOIN analysis_runs ar ON ar.analysis_run_id=aset.analysis_run_id " + ...
    "JOIN projects p ON p.project_id=ar.project_id " + ...
    "JOIN timebases tb ON tb.timebase_id=aset.reference_timebase_id " + ...
    "WHERE " + predicate);
if isempty(rows) || height(rows) == 0
    error("vawlume:alignment:AlignmentSetNotFound", ...
        "No alignment set matches alignmentRef.");
end
if height(rows) ~= 1
    error("vawlume:alignment:AlignmentSetAmbiguous", ...
        "alignmentRef matched %d alignment sets.", height(rows));
end
value = struct( ...
    alignment_set_id=double(rows.alignment_set_id(1)), ...
    analysis_run_id=double(rows.analysis_run_id(1)), ...
    reference_timebase_id=double(rows.reference_timebase_id(1)), ...
    reference_timebase_key=presentText(rows.reference_timebase_key(1)), ...
    status=presentText(rows.status(1)), ...
    run_key=presentText(rows.run_key(1)), ...
    project_key=presentText(rows.project_key(1)));
end

function value = normalizeTransforms(rows)
value = table(zeros(0, 1), strings(0, 1), strings(0, 1), strings(0, 1), ...
    strings(0, 1), zeros(0, 1), zeros(0, 1), zeros(0, 1), zeros(0, 1), ...
    zeros(0, 1), zeros(0, 1), ...
    VariableNames=["alignment_run_id", "source_timebase_key", ...
    "reference_timebase_key", "method", "status", "scale", "offset_s", ...
    "n_anchors_used", "rmse_s", "max_abs_residual_s", "segment_count"]);
for index = 1:height(rows)
    value(end + 1, :) = {double(rows.alignment_run_id(index)), ...
        presentText(rows.source_timebase_key(index)), ...
        presentText(rows.reference_timebase_key(index)), ...
        presentText(rows.method(index)), presentText(rows.status(index)), ...
        sentinelNumber(rows.scale(index)), sentinelNumber(rows.offset_s(index)), ...
        negativeSentinel(rows.n_anchors_used(index)), ...
        negativeSentinel(rows.fit_rmse_s(index)), ...
        negativeSentinel(rows.max_error_s(index)), ...
        double(rows.segment_count(index))}; %#ok<AGROW>
end
end

function value = normalizeResiduals(rows)
value = table(zeros(0, 1), strings(0, 1), strings(0, 1), zeros(0, 1), ...
    zeros(0, 1), zeros(0, 1), zeros(0, 1), zeros(0, 1), zeros(0, 1), ...
    zeros(0, 1), strings(0, 1), ...
    VariableNames=["alignment_run_id", "source_timebase_key", "anchor_key", ...
    "source_observation_id", "reference_observation_id", ...
    "observed_source_time", "observed_reference_time", ...
    "predicted_reference_time", "residual_s", "included_in_fit", ...
    "exclusion_reason"]);
for index = 1:height(rows)
    value(end + 1, :) = {double(rows.alignment_run_id(index)), ...
        presentText(rows.source_timebase_key(index)), ...
        presentText(rows.anchor_key(index)), ...
        double(rows.source_observation_id(index)), ...
        double(rows.reference_observation_id(index)), ...
        double(rows.observed_source_time(index)), ...
        double(rows.observed_reference_time(index)), ...
        double(rows.predicted_reference_time(index)), ...
        double(rows.residual_s(index)), ...
        double(rows.included_in_fit(index)), ...
        presentText(rows.exclusion_reason(index))}; %#ok<AGROW>
end
end

function value = sentinelNumber(raw)
value = double(raw);
if value >= 1e307
    value = NaN;
end
end

function value = negativeSentinel(raw)
value = double(raw);
if value < 0
    value = NaN;
end
end

function value = presentText(value)
value = string(value);
value(ismissing(value)) = "";
end
