function result = alignmentFitResult(plan)
%ALIGNMENTFITRESULT Structured, auditable QC read-back for one alignment set.
%
% The point of this shape is that a researcher can check the arithmetic. Observed
% source and reference times, the predicted reference time, and the residual all
% appear beside the coefficients, so a fit can be verified by hand rather than
% trusted because a summary number looked small.

if plan.has_conflicts
    status = "conflict";
else
    status = "planned";
end

result = struct( ...
    status=status, ...
    committed=false, ...
    has_conflicts=plan.has_conflicts, ...
    conflicts=plan.conflicts, ...
    alignment_set_id=plan.set.alignment_set_id, ...
    analysis_run_id=plan.set.analysis_run_id, ...
    run_key=plan.set.run_key, ...
    project_key=plan.set.project_key, ...
    reference_timebase=struct(timebase_id=plan.set.reference_timebase_id, ...
        timebase_key=plan.set.reference_timebase_key), ...
    transforms=transformTable(plan), ...
    anchors=anchorTable(plan), ...
    uncertainty_note=uncertaintyNote(), ...
    validation_note=validationNote(), ...
    applied_counts=struct());
end

function value = transformTable(plan)
value = table(zeros(0, 1), strings(0, 1), strings(0, 1), strings(0, 1), ...
    zeros(0, 1), zeros(0, 1), zeros(0, 1), zeros(0, 1), zeros(0, 1), ...
    strings(0, 1), strings(0, 1), ...
    VariableNames=["alignment_run_id", "source_timebase_key", ...
    "reference_timebase_key", "method", "scale", "offset_s", ...
    "n_anchors_used", "rmse_s", "max_abs_residual_s", "action", "status"]);
for index = 1:numel(plan.runs)
    run = plan.runs(index);
    value(end + 1, :) = {run.alignment_run_id, run.source_timebase_key, ...
        run.reference_timebase_key, run.method, run.scale, run.offset_s, ...
        run.fit_anchor_count, run.rmse_s, run.max_abs_residual_s, ...
        run.action, statusFor(run)}; %#ok<AGROW>
end
end

function value = statusFor(run)
switch run.action
    case "create"
        value = "estimated";
    case "reuse"
        value = run.stored_status;
    otherwise
        value = run.stored_status;
end
end

function value = anchorTable(plan)
% The observation counts are reported so a reader can see that redundant readings
% existed and that exactly one of them was selected, rather than having to infer
% from a single row that nothing was averaged away.
value = table(strings(0, 1), zeros(0, 1), strings(0, 1), zeros(0, 1), ...
    zeros(0, 1), zeros(0, 1), zeros(0, 1), zeros(0, 1), zeros(0, 1), ...
    zeros(0, 1), strings(0, 1), strings(0, 1), strings(0, 1), ...
    zeros(0, 1), zeros(0, 1), zeros(0, 1), zeros(0, 1), ...
    VariableNames=["source_timebase_key", "alignment_run_id", "anchor_key", ...
    "source_observation_id", "reference_observation_id", ...
    "observed_source_time", "observed_reference_time", ...
    "predicted_reference_time", "residual_s", "included_in_fit", ...
    "source_role", "reference_role", "exclusion_reason", ...
    "source_uncertainty_s", "reference_uncertainty_s", ...
    "source_observation_count", "reference_observation_count"]);
for index = 1:numel(plan.runs)
    run = plan.runs(index);
    for row = 1:height(run.anchors)
        anchor = run.anchors(row, :);
        value(end + 1, :) = {run.source_timebase_key, run.alignment_run_id, ...
            anchor.anchor_key, anchor.source_observation_id, ...
            anchor.reference_observation_id, anchor.observed_source_time, ...
            anchor.observed_reference_time, anchor.predicted_reference_time, ...
            anchor.residual_s, anchor.included_in_fit, anchor.source_role, ...
            anchor.reference_role, anchor.exclusion_reason, ...
            anchor.source_uncertainty_s, anchor.reference_uncertainty_s, ...
            anchor.source_observation_count, ...
            anchor.reference_observation_count}; %#ok<AGROW>
    end
end
end

function value = uncertaintyNote()
value = "Anchor uncertainty_s is preserved and reported but is not used as a " + ...
    "fit weight. This is unweighted ordinary least squares.";
end

function value = validationNote()
value = "A solved fit is recorded as estimated, never validated. No calibrated " + ...
    "acceptance threshold exists, and residual size alone is not validation.";
end
