function result = alignmentFitResult(plan)
%ALIGNMENTFITRESULT Structured, auditable QC read-back for one alignment set.
%
% The point of this shape is that a researcher can check the arithmetic. Observed
% source and reference times, the predicted reference time, and the residual all
% appear beside the coefficients, so a fit can be verified by hand rather than
% trusted because a summary number looked small.

if plan.has_conflicts
    status = "conflict";
else
    status = "planned";
end

result = struct( ...
    status=status, ...
    committed=false, ...
    has_conflicts=plan.has_conflicts, ...
    conflicts=plan.conflicts, ...
    alignment_set_id=plan.set.alignment_set_id, ...
    analysis_run_id=plan.set.analysis_run_id, ...
    run_key=plan.set.run_key, ...
    project_key=plan.set.project_key, ...
    reference_timebase=struct(timebase_id=plan.set.reference_timebase_id, ...
        timebase_key=plan.set.reference_timebase_key), ...
    transforms=transformTable(plan), ...
    anchors=anchorTable(plan), ...
    anchor_diagnostics=diagnosticsTable(plan), ...
    unpaired_anchors=unpairedTable(plan), ...
    anchors_without_transform=plan.anchors_without_transform, ...
    uncertainty_note=uncertaintyNote(), ...
    dispersion_note=dispersionNote(), ...
    influence_note=influenceNote(), ...
    validation_note=validationNote(), ...
    applied_counts=struct());
end

function value = transformTable(plan)
value = table(zeros(0, 1), strings(0, 1), strings(0, 1), strings(0, 1), ...
    zeros(0, 1), zeros(0, 1), zeros(0, 1), zeros(0, 1), zeros(0, 1), ...
    strings(0, 1), strings(0, 1), ...
    VariableNames=["alignment_run_id", "source_timebase_key", ...
    "reference_timebase_key", "method", "scale", "offset_s", ...
    "n_anchors_used", "rmse_s", "max_abs_residual_s", "action", "status"]);
for index = 1:numel(plan.runs)
    run = plan.runs(index);
    value(end + 1, :) = {run.alignment_run_id, run.source_timebase_key, ...
        run.reference_timebase_key, run.method, run.scale, run.offset_s, ...
        run.fit_anchor_count, run.rmse_s, run.max_abs_residual_s, ...
        run.action, statusFor(run)}; %#ok<AGROW>
end
end

function value = statusFor(run)
switch run.action
    case "create"
        value = "estimated";
    case "reuse"
        value = run.stored_status;
    otherwise
        value = run.stored_status;
end
end

function value = anchorTable(plan)
% The observation counts are reported so a reader can see that redundant readings
% existed and that exactly one of them was selected, rather than having to infer
% from a single row that nothing was averaged away.
value = table(strings(0, 1), zeros(0, 1), strings(0, 1), zeros(0, 1), ...
    zeros(0, 1), zeros(0, 1), zeros(0, 1), zeros(0, 1), zeros(0, 1), ...
    zeros(0, 1), strings(0, 1), strings(0, 1), strings(0, 1), ...
    zeros(0, 1), zeros(0, 1), zeros(0, 1), zeros(0, 1), ...
    zeros(0, 1), zeros(0, 1), zeros(0, 1), zeros(0, 1), ...
    zeros(0, 1), zeros(0, 1), ...
    VariableNames=["source_timebase_key", "alignment_run_id", "anchor_key", ...
    "source_observation_id", "reference_observation_id", ...
    "observed_source_time", "observed_reference_time", ...
    "predicted_reference_time", "residual_s", "included_in_fit", ...
    "source_role", "reference_role", "exclusion_reason", ...
    "source_uncertainty_s", "reference_uncertainty_s", ...
    "source_observation_count", "reference_observation_count", ...
    "source_spread_s", "reference_spread_s", ...
    "source_max_deviation_s", "reference_max_deviation_s", ...
    "loo_scale_delta", "loo_offset_delta_s"]);
for index = 1:numel(plan.runs)
    run = plan.runs(index);
    for row = 1:height(run.anchors)
        anchor = run.anchors(row, :);
        value(end + 1, :) = {run.source_timebase_key, run.alignment_run_id, ...
            anchor.anchor_key, anchor.source_observation_id, ...
            anchor.reference_observation_id, anchor.observed_source_time, ...
            anchor.observed_reference_time, anchor.predicted_reference_time, ...
            anchor.residual_s, anchor.included_in_fit, anchor.source_role, ...
            anchor.reference_role, anchor.exclusion_reason, ...
            anchor.source_uncertainty_s, anchor.reference_uncertainty_s, ...
            anchor.source_observation_count, ...
            anchor.reference_observation_count, ...
            anchor.source_spread_s, anchor.reference_spread_s, ...
            anchor.source_max_deviation_s, anchor.reference_max_deviation_s, ...
            anchor.loo_scale_delta, anchor.loo_offset_delta_s}; %#ok<AGROW>
    end
end
end

function value = diagnosticsTable(plan)
% Whether the anchors could support the model asked of them. Every number is
% reported for a reader to judge; none is a threshold, a grade, or a verdict.
value = table(zeros(0, 1), strings(0, 1), zeros(0, 1), zeros(0, 1), ...
    zeros(0, 1), zeros(0, 1), zeros(0, 1), zeros(0, 1), zeros(0, 1), ...
    zeros(0, 1), ...
    VariableNames=["alignment_run_id", "source_timebase_key", ...
    "paired_anchor_count", "included_anchor_count", "withheld_anchor_count", ...
    "unpaired_anchor_count", "source_range_start", "source_range_end", ...
    "source_span_s", "largest_gap_fraction"]);
for index = 1:numel(plan.runs)
    run = plan.runs(index);
    value(end + 1, :) = {run.alignment_run_id, run.source_timebase_key, ...
        height(run.anchors), run.diagnostics.included_anchor_count, ...
        run.withheld_anchor_count, height(run.unpaired_anchors), ...
        run.diagnostics.source_range_start, run.diagnostics.source_range_end, ...
        run.diagnostics.source_span_s, ...
        run.diagnostics.largest_gap_fraction}; %#ok<AGROW>
end
end

function value = unpairedTable(plan)
% Anchors the fitter never saw, and why. Previously these were skipped in
% silence, which made missing evidence indistinguishable from absent evidence.
value = table(zeros(0, 1), strings(0, 1), strings(0, 1), zeros(0, 1), ...
    zeros(0, 1), strings(0, 1), ...
    VariableNames=["alignment_run_id", "source_timebase_key", "anchor_key", ...
    "source_observation_count", "reference_observation_count", "reason"]);
for index = 1:numel(plan.runs)
    run = plan.runs(index);
    for row = 1:height(run.unpaired_anchors)
        entry = run.unpaired_anchors(row, :);
        value(end + 1, :) = {run.alignment_run_id, run.source_timebase_key, ...
            entry.anchor_key, entry.source_observation_count, ...
            entry.reference_observation_count, entry.reason}; %#ok<AGROW>
    end
end
end

function value = dispersionNote()
value = "Replicate spread is derived from alignment_anchor_observations on " + ...
    "read and is never stored. A replicate is evidence about how consistently " + ...
    "a marker was read, never an extra statistical anchor: nothing is averaged " + ...
    "and nothing extra enters the design matrix. An anchor read once has no " + ...
    "dispersion, reported as NaN rather than as zero.";
end

function value = influenceNote()
value = "Leave-one-out deltas say how far the coefficients move when one " + ...
    "anchor is dropped. They mix residual with leverage, so a large delta " + ...
    "means the reading matters to the answer, not that it is wrong. They are " + ...
    "reported, never acted on: no anchor is excluded automatically, and " + ...
    "exclusion remains a declared decision recorded on the observation.";
end

function value = uncertaintyNote()
value = "Anchor uncertainty_s is preserved and reported but is not used as a " + ...
    "fit weight. This is unweighted ordinary least squares.";
end

function value = validationNote()
value = "A solved fit is recorded as estimated, never validated. No calibrated " + ...
    "acceptance threshold exists, and residual size alone is not validation.";
end
