function result = agreementPlanResult(plan)
%AGREEMENTPLANRESULT Project internal planning state into the public result.
%
% The result reports what was validated, what identity was resolved, and what
% was composed. The per-group dimensions it carries - member and extractor
% counts, supported and unsupported extractor-pair labels, contributing
% ambiguous topologies, singleton status - are computed here and deliberately
% not stored. They are views over the members and exact edges, recomputable at
% any time, and they are reported as separate fields rather than collapsed into
% one score or flag.

if plan.has_conflicts
    status = "conflict";
else
    status = "planned";
end
result = struct( ...
    status=status, ...
    committed=false, ...
    has_conflicts=plan.has_conflicts, ...
    conflicts=plan.conflicts, ...
    recording=plan.recording, ...
    sources=plan.sources, ...
    source_count=height(plan.sources), ...
    extractor_runs=plan.extractor_runs, ...
    coverage=plan.coverage, ...
    specification=struct( ...
        profile_key=plan.specification.profile_key, ...
        version_label=plan.specification.version_label, ...
        checksum_sha256=plan.specification.checksum_sha256, ...
        content_uri=plan.specification.content_uri, ...
        assignment_role=agreementRoles().specification, ...
        required_run_type=plan.specification.required_run_type, ...
        required_status=plan.specification.required_status, ...
        pairwise_coverage=plan.specification.pairwise_coverage, ...
        component_rule=plan.specification.component_rule, ...
        clique_completeness=plan.specification.clique_completeness, ...
        singleton_inclusion=plan.specification.singleton_inclusion, ...
        ambiguity_propagation=plan.specification.ambiguity_propagation, ...
        feature_support_is_admission_criterion=...
            plan.specification.feature_support_is_admission_criterion), ...
    algorithm=struct(key=plan.specification.algorithm_key, ...
        version=plan.specification.algorithm_version), ...
    configuration=plan.configuration, ...
    analysis=plan.analysis, ...
    eligibility=plan.graph.eligibility, ...
    nodes=plan.graph.nodes, ...
    node_count=height(plan.graph.nodes), ...
    edges=plan.graph.edges, ...
    edge_count=height(plan.graph.edges), ...
    groups=plan.groups, ...
    group_count=height(plan.groups), ...
    members=plan.members, ...
    support_edges=plan.support_edges, ...
    singleton_count=nnz(plan.groups.is_singleton), ...
    composition_pending=plan.analysis.graph_action ~= "reuse", ...
    applied_counts=struct());
end
