function [plan, counts] = agreementApplyPlan(conn, plan)
%AGREEMENTAPPLYPLAN Atomically persist the agreement run's provenance skeleton.
%
% This writes the analysis boundary and nothing else: the policy profile version,
% the derived analysis run, its participating extraction inputs, its many-parent
% lineage, and its policy linkage. No agreement group, member, or supporting edge
% is created, so the run is deliberately left with status 'started'. Claiming
% 'completed' would assert a composition that has not been performed.

if plan.has_conflicts
    error("vawlume:agreement:PlanConflict", ...
        "An agreement plan with identity conflicts cannot be applied.");
end
counts = emptyCounts();
if plan.analysis.action == "reuse"
    counts = reuseCounts(plan, counts);
    return
end

oldAutoCommit = string(conn.AutoCommit);
if oldAutoCommit ~= "on"
    error("vawlume:agreement:TransactionState", ...
        "Agreement apply requires a connection with AutoCommit enabled.");
end
conn.AutoCommit = "off";
try
    [plan, counts] = applyConfiguration(conn, plan, counts);
    [plan, counts] = applyAnalysis(conn, plan, counts);
    commit(conn);
catch exception
    try
        rollback(conn);
    catch
    end
    conn.AutoCommit = oldAutoCommit;
    rethrow(exception);
end
conn.AutoCommit = oldAutoCommit;
end

function [plan, counts] = applyConfiguration(conn, plan, counts)
configuration = plan.configuration;
if configuration.profile_action == "create"
    configuration.profile_id = agreementInsertRow(conn, "config_profiles", struct( ...
        project_id=plan.recording.project_id, ...
        profile_key=configuration.profile_key, ...
        profile_name=configuration.profile_name, ...
        profile_kind=configuration.profile_kind, is_builtin=0, ...
        description="Versioned arbitrary-N extractor-agreement composition policy."), ...
        "profile_id");
    counts.config_profiles = 1;
else
    counts.reused_config_profiles = 1;
end
if configuration.version_action == "create"
    configuration.profile_version_id = agreementInsertRow(conn, ...
        "config_profile_versions", struct(profile_id=configuration.profile_id, ...
        version_label=configuration.version_label, ...
        profile_schema_version=configuration.profile_schema_version, ...
        content_format=configuration.content_format, ...
        content_uri=configuration.content_uri, ...
        checksum_sha256=configuration.checksum_sha256, is_snapshot=1, ...
        notes="Exact agreement policy used by a derived arbitrary-N analysis."), ...
        "profile_version_id");
    counts.config_profile_versions = 1;
else
    counts.reused_config_profile_versions = 1;
end
plan.configuration = configuration;
end

function [plan, counts] = applyAnalysis(conn, plan, counts)
roles = agreementRoles();
plan.analysis.analysis_run_id = agreementInsertRow(conn, "analysis_runs", struct( ...
    project_id=plan.recording.project_id, ...
    run_type=plan.analysis.run_type, run_key=plan.context.run_key, ...
    run_label=plan.context.run_label, ...
    vawlume_version=plan.context.vawlume_version, ...
    source_commit=plan.context.source_commit, ...
    status="started", notes=analysisNotes(plan)), "analysis_run_id");
plan.analysis.status = "started";
counts.analysis_runs = 1;

agreementInsertRow(conn, "analysis_run_profiles", struct( ...
    analysis_run_id=plan.analysis.analysis_run_id, ...
    profile_version_id=plan.configuration.profile_version_id, ...
    assignment_role=roles.specification));
counts.analysis_run_profiles = 1;

for index = 1:height(plan.extractor_runs)
    agreementInsertRow(conn, "analysis_run_extraction_inputs", struct( ...
        analysis_run_id=plan.analysis.analysis_run_id, ...
        extraction_run_id=plan.extractor_runs.extraction_run_id(index), ...
        input_role=roles.extraction_input));
end
counts.analysis_run_extraction_inputs = height(plan.extractor_runs);

% Every pairwise parent, in canonical order. This is the claim
% parent_analysis_run_id cannot make.
for index = 1:height(plan.sources)
    agreementInsertRow(conn, "analysis_run_sources", struct( ...
        analysis_run_id=plan.analysis.analysis_run_id, ...
        source_analysis_run_id=plan.sources.analysis_run_id(index), ...
        dependency_role=roles.source_analysis, ...
        notes="Pairwise analysis '" + plan.sources.run_key(index) + ...
            "' covering extractor pair " + plan.sources.pair_label(index) + "."));
end
counts.analysis_run_sources = height(plan.sources);
plan.analysis.action = "create";
end

function value = analysisNotes(plan)
value = "algorithm=" + plan.specification.algorithm_key + "@" + ...
    plan.specification.algorithm_version + ...
    "; composition_pending=true; sources=" + ...
    strjoin(plan.sources.run_key', ",");
if strlength(plan.context.notes) > 0
    value = plan.context.notes + " [" + value + "]";
end
end

function counts = reuseCounts(plan, counts)
counts.reused_config_profiles = 1;
counts.reused_config_profile_versions = 1;
counts.reused_analysis_runs = 1;
counts.reused_analysis_run_profiles = 1;
counts.reused_analysis_run_extraction_inputs = height(plan.extractor_runs);
counts.reused_analysis_run_sources = height(plan.sources);
end

function counts = emptyCounts()
counts = struct(config_profiles=0, config_profile_versions=0, ...
    analysis_runs=0, analysis_run_profiles=0, ...
    analysis_run_extraction_inputs=0, analysis_run_sources=0, ...
    agreement_groups=0, agreement_group_members=0, ...
    agreement_supporting_edges=0, ...
    reused_config_profiles=0, reused_config_profile_versions=0, ...
    reused_analysis_runs=0, reused_analysis_run_profiles=0, ...
    reused_analysis_run_extraction_inputs=0, reused_analysis_run_sources=0);
end
