function detection = consilienceDetectionAgreement(conn, analysis)
%CONSILIENCEDETECTIONAGREEMENT Counts, denominators, topology, and temporal deltas.
%
% Every proportion is computed against that run's own detection count, and the
% denominator is carried in the result rather than left to be inferred. A split
% group counts once as one ambiguous component, never as several one-to-one
% matches, which is why participation is counted per detection and per component
% separately.

groups = fetch(conn, "SELECT mg.match_group_id, mg.match_type, " + ...
    "IFNULL(mg.ambiguity_status,'') AS ambiguity_status " + ...
    "FROM match_groups mg WHERE mg.analysis_run_id=" + ...
    string(analysis.analysis_run_id) + " ORDER BY mg.match_group_id");
members = fetch(conn, "SELECT mgm.match_group_id, mgm.detection_id, " + ...
    "IFNULL(mgm.member_role,'') AS member_role, mg.match_type " + ...
    "FROM match_group_members mgm " + ...
    "JOIN match_groups mg ON mg.match_group_id=mgm.match_group_id " + ...
    "WHERE mg.analysis_run_id=" + string(analysis.analysis_run_id));
if height(groups) == 0
    error("vawlume:consilience:NoMatchGroups", ...
        "Matching analysis '%s' has no match groups to summarize.", ...
        analysis.run_key);
end

matchTypes = presentText(groups.match_type);
memberTypes = presentText(members.match_type);
memberRoles = presentText(members.member_role);

ambiguousTypes = ["one_to_many", "many_to_one", "many_to_many"];
perRun = emptyPerRun();
for role = ["run_a", "run_b"]
    run = analysis.(role);
    total = countOf(conn, "SELECT COUNT(*) AS n FROM detections " + ...
        "WHERE extraction_run_id=" + string(run.extraction_run_id) + ...
        " AND recording_id=" + string(analysis.recording_id));
    selected = memberRoles == role;
    inGroups = nnz(selected & memberTypes ~= "unmatched");
    inOneToOne = nnz(selected & memberTypes == "one_to_one");
    inAmbiguous = nnz(selected & ismember(memberTypes, ambiguousTypes));
    unmatched = nnz(selected & memberTypes == "unmatched");
    if inGroups + unmatched ~= total
        error("vawlume:consilience:PartitionIncomplete", ...
            ['Matching analysis ''%s'' places %d of %s''s %d detections in ' ...
            'groups. Agreement denominators require the complete partition.'], ...
            analysis.run_key, inGroups + unmatched, run.extractor_name, total);
    end
    perRun(end + 1, :) = {role, run.extractor_name, run.extractor_version, ...
        run.run_key, total, inGroups, inOneToOne, inAmbiguous, unmatched, ...
        ratio(inGroups, total), ratio(inOneToOne, total), ...
        ratio(inAmbiguous, total), ratio(unmatched, total)}; %#ok<AGROW>
end

topology = emptyTopology();
participation = emptyParticipation();
for name = ["one_to_one", "one_to_many", "many_to_one", "many_to_many", "unmatched"]
    groupCount = nnz(matchTypes == name);
    selected = memberTypes == name;
    topology(end + 1, :) = {name, groupCount, nnz(selected), ...
        nnz(selected & memberRoles == "run_a"), ...
        nnz(selected & memberRoles == "run_b")}; %#ok<AGROW>
end
for role = ["run_a", "run_b"]
    for name = ["one_to_one", "one_to_many", "many_to_one", "many_to_many", "unmatched"]
        participation(end + 1, :) = {role, analysis.(role).extractor_name, ...
            name, nnz(memberTypes == name & memberRoles == role)}; %#ok<AGROW>
    end
end

detection = struct( ...
    per_run=perRun, ...
    topology=topology, ...
    participation=participation, ...
    symmetric=symmetricCoverage(perRun), ...
    temporal=temporalAgreement(conn, analysis, groups, members), ...
    denominator_note=denominatorNote());
end

function value = symmetricCoverage(perRun)
%SYMMETRICCOVERAGE One pooled figure, with its definition attached.
%
% Neither extractor is ground truth, so a single "percent agreement" would have
% no defensible denominator. This is deliberately labelled pooled coverage: the
% share of all detections from both runs that sit in a cross-extractor component.
matchedTotal = sum(perRun.in_cross_extractor_groups);
allTotal = sum(perRun.total_detections);
value = struct( ...
    definition="pooled share of both runs' detections that belong to a " + ...
        "cross-extractor correspondence component", ...
    numerator=matchedTotal, ...
    denominator=allTotal, ...
    pooled_matched_coverage=ratio(matchedTotal, allTotal), ...
    caution="This is coverage, not an agreement rate, and it is not a " + ...
        "measure of either extractor's accuracy.");
end

function value = denominatorNote()
value = [ ...
    "Every proportion uses that run's own detection count on this recording."; ...
    "in_cross_extractor_groups counts detections in any component with " + ...
        "members from both runs; unmatched single-member groups are excluded."; ...
    "in_ambiguous_groups counts detections in one_to_many, many_to_one, and " + ...
        "many_to_many components."; ...
    "The four count columns partition each run's detections exactly once, " + ...
        "because in_one_to_one plus in_ambiguous plus unmatched equals total."];
end

function temporal = temporalAgreement(conn, analysis, groups, members)
%TEMPORALAGREEMENT Read stored candidate evidence; never recompute it.
%
% The candidate row already holds the overlap, IoU, and signed onset, offset,
% and duration differences computed at generation time under the versioned
% specification. Recomputing them here from detection geometry would risk a
% subtly different formula reporting a different answer than the stored evidence.
oneToOne = groups.match_group_id(presentText(groups.match_type) == "one_to_one");
temporal = struct( ...
    source="stored candidate_pairs evidence for one_to_one components", ...
    group_count=numel(oneToOne), ...
    rows=emptyTemporalRows(), ...
    summary=emptyTemporalSummary());
if isempty(oneToOne)
    return
end

for index = 1:numel(oneToOne)
    groupId = oneToOne(index);
    detectionIds = members.detection_id(members.match_group_id == groupId);
    rows = fetch(conn, "SELECT cp.temporal_overlap_s, cp.temporal_iou, " + ...
        "cp.onset_difference_s, cp.offset_difference_s, cp.duration_difference_s " + ...
        "FROM candidate_pairs cp WHERE cp.analysis_run_id=" + ...
        string(analysis.analysis_run_id) + " AND cp.detection_a_id=" + ...
        string(min(detectionIds)) + " AND cp.detection_b_id=" + ...
        string(max(detectionIds)));
    if height(rows) ~= 1
        error("vawlume:consilience:CandidateEvidenceMissing", ...
            ['One-to-one group %d has no single stored candidate row. ' ...
            'Temporal agreement reads stored evidence and does not recompute it.'], ...
            groupId);
    end
    temporal.rows(end + 1, :) = {groupId, ...
        double(rows.temporal_overlap_s(1)), double(rows.temporal_iou(1)), ...
        double(rows.onset_difference_s(1)), double(rows.offset_difference_s(1)), ...
        double(rows.duration_difference_s(1))};
end

for name = ["temporal_overlap_s", "temporal_iou", "onset_difference_s", ...
        "offset_difference_s", "duration_difference_s"]
    values = temporal.rows.(name);
    temporal.summary(end + 1, :) = {name, numel(values), mean(values), ...
        median(values), mean(abs(values)), median(abs(values)), ...
        standardDeviation(values), min(values), max(values)};
end
end

function value = standardDeviation(values)
if numel(values) < 2
    value = NaN;
    return
end
value = std(values);
end

function value = ratio(numerator, denominator)
if denominator == 0
    value = NaN;
    return
end
value = numerator / denominator;
end

function value = countOf(conn, sql)
rows = fetch(conn, sql);
value = double(rows.n(1));
end

function value = emptyPerRun()
value = table(strings(0, 1), strings(0, 1), strings(0, 1), strings(0, 1), ...
    zeros(0, 1), zeros(0, 1), zeros(0, 1), zeros(0, 1), zeros(0, 1), ...
    zeros(0, 1), zeros(0, 1), zeros(0, 1), zeros(0, 1), ...
    VariableNames=["run_role", "extractor_name", "extractor_version", ...
    "run_key", "total_detections", "in_cross_extractor_groups", ...
    "in_one_to_one_groups", "in_ambiguous_groups", "unmatched_detections", ...
    "proportion_in_groups", "proportion_one_to_one", ...
    "proportion_ambiguous", "proportion_unmatched"]);
end

function value = emptyTopology()
value = table(strings(0, 1), zeros(0, 1), zeros(0, 1), zeros(0, 1), zeros(0, 1), ...
    VariableNames=["match_type", "group_count", "detection_count", ...
    "run_a_detections", "run_b_detections"]);
end

function value = emptyParticipation()
value = table(strings(0, 1), strings(0, 1), strings(0, 1), zeros(0, 1), ...
    VariableNames=["run_role", "extractor_name", "match_type", "detection_count"]);
end

function value = emptyTemporalRows()
value = table(zeros(0, 1), zeros(0, 1), zeros(0, 1), zeros(0, 1), ...
    zeros(0, 1), zeros(0, 1), ...
    VariableNames=["match_group_id", "temporal_overlap_s", "temporal_iou", ...
    "onset_difference_s", "offset_difference_s", "duration_difference_s"]);
end

function value = emptyTemporalSummary()
value = table(strings(0, 1), zeros(0, 1), zeros(0, 1), zeros(0, 1), ...
    zeros(0, 1), zeros(0, 1), zeros(0, 1), zeros(0, 1), zeros(0, 1), ...
    VariableNames=["statistic", "n", "mean_signed", "median_signed", ...
    "mean_absolute", "median_absolute", "std_signed", "minimum", "maximum"]);
end

function value = presentText(value)
value = string(value);
value(ismissing(value)) = "";
end
