function analysis = consilienceResolveAnalysis(conn, analysisRef)
%CONSILIENCERESOLVEANALYSIS Resolve exactly one completed matching analysis.
%
% The ordered run pair comes from analysis_run_extraction_inputs.input_role,
% which is the only place run direction is recorded. Signed differences
% everywhere downstream are run_b minus run_a, matching the stored candidate
% evidence direction.

hasId = isfield(analysisRef, "analysis_run_id");
hasKey = isfield(analysisRef, "run_key");
if hasId == hasKey
    error("vawlume:consilience:AnalysisRefInvalid", ...
        "analysisRef must contain exactly one of analysis_run_id or run_key.");
end
if hasId
    predicate = "ar.analysis_run_id=" + string(scalarPositiveInteger( ...
        analysisRef.analysis_run_id, "analysis_run_id"));
else
    predicate = "ar.run_key=" + sqlText(scalarText(analysisRef.run_key, "run_key"));
    if isfield(analysisRef, "project_key")
        predicate = predicate + " AND p.project_key=" + ...
            sqlText(scalarText(analysisRef.project_key, "project_key"));
    end
end

rows = fetch(conn, "SELECT ar.analysis_run_id, ar.project_id, p.project_key, " + ...
    "ar.run_key, IFNULL(ar.run_label,'') AS run_label, ar.run_type, ar.status " + ...
    "FROM analysis_runs ar JOIN projects p ON p.project_id=ar.project_id " + ...
    "WHERE " + predicate);
if isempty(rows) || height(rows) == 0
    error("vawlume:consilience:AnalysisNotFound", ...
        "No analysis run matches analysisRef.");
end
if height(rows) ~= 1
    error("vawlume:consilience:AnalysisAmbiguous", ...
        "analysisRef matched %d analysis runs; exactly one is required. " + ...
        "Supply project_key or analysis_run_id.", height(rows));
end
if presentText(rows.run_type(1)) ~= "cross_extractor_matching"
    error("vawlume:consilience:AnalysisNotMatching", ...
        "Agreement requires a cross_extractor_matching analysis, not '%s'.", ...
        presentText(rows.run_type(1)));
end
if presentText(rows.status(1)) ~= "completed"
    error("vawlume:consilience:AnalysisIncomplete", ...
        "Agreement requires a completed matching analysis; '%s' is '%s'.", ...
        presentText(rows.run_key(1)), presentText(rows.status(1)));
end

analysis = struct( ...
    analysis_run_id=double(rows.analysis_run_id(1)), ...
    project_id=double(rows.project_id(1)), ...
    project_key=presentText(rows.project_key(1)), ...
    run_key=presentText(rows.run_key(1)), ...
    run_label=presentText(rows.run_label(1)));

inputs = fetch(conn, "SELECT ari.input_role, ari.extraction_run_id, " + ...
    "er.run_key, e.extractor_name, ev.version_label AS extractor_version, " + ...
    "e.extractor_id FROM analysis_run_extraction_inputs ari " + ...
    "JOIN extraction_runs er ON er.extraction_run_id=ari.extraction_run_id " + ...
    "JOIN extractor_versions ev ON ev.extractor_version_id=er.extractor_version_id " + ...
    "JOIN extractors e ON e.extractor_id=ev.extractor_id " + ...
    "WHERE ari.analysis_run_id=" + string(analysis.analysis_run_id) + ...
    " ORDER BY ari.input_role");
roles = presentText(inputs.input_role);
if ~isequal(sort(roles), ["run_a"; "run_b"])
    error("vawlume:consilience:AnalysisInputsInvalid", ...
        "A matching analysis must declare exactly one run_a and one run_b input.");
end
for role = ["run_a", "run_b"]
    index = find(roles == role, 1);
    analysis.(role) = struct( ...
        extraction_run_id=double(inputs.extraction_run_id(index)), ...
        run_key=presentText(inputs.run_key(index)), ...
        extractor_id=double(inputs.extractor_id(index)), ...
        extractor_name=presentText(inputs.extractor_name(index)), ...
        extractor_version=presentText(inputs.extractor_version(index)));
end
if analysis.run_a.extractor_id == analysis.run_b.extractor_id
    error("vawlume:consilience:SameExtractor", ...
        "Cross-extractor agreement requires two different extractors.");
end

recordings = fetch(conn, "SELECT DISTINCT d.recording_id FROM detections d " + ...
    "WHERE d.extraction_run_id IN (" + ...
    string(analysis.run_a.extraction_run_id) + "," + ...
    string(analysis.run_b.extraction_run_id) + ")");
if height(recordings) ~= 1
    error("vawlume:consilience:RecordingAmbiguous", ...
        "The analysis inputs span %d recordings; exactly one is required.", ...
        height(recordings));
end
analysis.recording_id = double(recordings.recording_id(1));
analysis.direction = "signed differences are run_b minus run_a";
end

function value = scalarPositiveInteger(value, name)
if ~isnumeric(value) || ~isscalar(value) || ~isfinite(value) || ...
        fix(value) ~= value || value <= 0
    error("vawlume:consilience:AnalysisRefInvalid", ...
        "%s must be a positive scalar integer.", name);
end
value = double(value);
end

function value = scalarText(value, name)
try
    value = string(value);
catch
    value = strings(0, 1);
end
if ~isscalar(value) || ismissing(value) || strlength(strtrim(value)) == 0
    error("vawlume:consilience:AnalysisRefInvalid", ...
        "%s must be a nonempty scalar text value.", name);
end
value = strtrim(value);
end

function value = presentText(value)
value = string(value);
value(ismissing(value)) = "";
end

function value = sqlText(text)
value = "'" + replace(string(text), "'", "''") + "'";
end
