function classification = consilienceClassify(conn, analysis, specification, detection, feature)
%CONSILIENCECLASSIFY Assign one automated consilience status per match group.
%
% A status is a categorical evidence summary under one versioned rule set. It is
% not a probability that a vocalization occurred, and no score is stored: the
% schema's score column stays NULL because nothing here is calibrated.
%
% Manual adjudication never overwrites the automated status. The automated status
% is what gets persisted; the manual verdict lives in its own manual_reviews row
% and is reported beside it, with the precedence-resolved effective status
% computed for the reader rather than stored as the group's status.

groups = fetch(conn, "SELECT mg.match_group_id, mg.match_type, " + ...
    "IFNULL(mg.ambiguity_status,'') AS ambiguity_status " + ...
    "FROM match_groups mg WHERE mg.analysis_run_id=" + ...
    string(analysis.analysis_run_id) + " ORDER BY mg.match_group_id");
manual = manualAdjudications(conn, analysis);

rows = emptyRows();
for index = 1:height(groups)
    groupId = double(groups.match_group_id(index));
    matchType = presentText(groups.match_type(index));
    evidence = groupEvidence(analysis, detection, feature, groupId, matchType, ...
        specification);
    [status, rule] = automatedStatus(matchType, evidence, specification);
    manualRow = manual(manual.match_group_id == groupId, :);
    [manualStatus, manualReviewId, reviewerLabel] = manualVerdict(manualRow);
    effective = effectiveStatus(status, manualStatus);
    rationale = string(jsonencode(rationaleFor(analysis, specification, ...
        matchType, status, rule, evidence, manualStatus, manualReviewId, ...
        reviewerLabel)));
    rows(end + 1, :) = {groupId, matchType, status, rule, manualStatus, ...
        manualReviewId, reviewerLabel, effective, ...
        evidence.supporting_available, evidence.supporting_within, ...
        evidence.supporting_outside, evidence.supporting_missing, ...
        strjoin(evidence.discrepant_classes, ", "), rationale}; %#ok<AGROW>
end

classification = struct( ...
    assessments=rows, ...
    status_counts=statusCounts(rows), ...
    precedence=specification.precedence_order, ...
    vocabulary=specification.status_vocabulary);
end

% ------------------------------------------------------------------ rules ---

function [status, rule] = automatedStatus(matchType, evidence, specification)
%AUTOMATEDSTATUS The frozen rule set, evaluated in precedence order.
%
% Ambiguous topology outranks feature evidence deliberately: averaging the two
% MUPET syllables of a split component to produce something comparable against
% one DeepSqueak call would require an aggregation model that does not exist, so
% an ambiguous component never earns a feature-supported status.
if matchType == "unmatched"
    status = "single_extractor";
    rule = "no eligible cross-extractor correspondence under this " + ...
        "specification; this is not a false positive and not a judgement " + ...
        "about the detection's validity";
    return
end
if matchType ~= "one_to_one"
    status = "ambiguous_split_merge";
    rule = "topology " + matchType + "; feature support is not evaluated " + ...
        "because no aggregation model for ambiguous components exists";
    return
end
if evidence.supporting_outside > 0
    status = "matched_feature_discrepant";
    rule = "one_to_one with " + string(evidence.supporting_outside) + ...
        " eligible supporting comparison(s) outside the declared tolerance";
    return
end
minimum = specification.minimum_supporting_comparisons;
if evidence.supporting_within >= minimum
    status = "matched_feature_supported";
    rule = "one_to_one with " + string(evidence.supporting_within) + ...
        " eligible supporting comparison(s) within tolerance, meeting the " + ...
        "configured minimum of " + string(minimum);
    return
end
status = "temporally_matched";
rule = "one_to_one temporal correspondence with " + ...
    string(evidence.supporting_within) + " supporting comparison(s), below " + ...
    "the configured minimum of " + string(minimum) + "; a missing comparison " + ...
    "is not a discrepancy";
end

function value = effectiveStatus(automated, manualStatus)
%EFFECTIVESTATUS Precedence applied for the reader, never for storage.
if manualStatus == "not_reviewed"
    value = automated;
    return
end
value = manualStatus;
end

% --------------------------------------------------------------- evidence ---

function evidence = groupEvidence(analysis, detection, feature, groupId, ...
        matchType, specification)
evidence = struct(supporting_available=0, supporting_within=0, ...
    supporting_outside=0, supporting_missing=0, ...
    discrepant_classes=strings(0, 1), temporal=struct(), ...
    run_a_members=0, run_b_members=0);

participation = detection.topology(string(detection.topology.match_type) == ...
    matchType, :);
if height(participation) == 1
    evidence.topology_group_count = double(participation.group_count(1));
end

comparisons = feature.comparisons;
if height(comparisons) > 0
    selected = comparisons(comparisons.match_group_id == groupId, :);
    % Supporting comparisons are exactly the eligible pairs that carry a
    % declared tolerance. Timing classes are already primary temporal evidence
    % and are excluded here so one piece of evidence is never counted twice.
    supporting = selected(~selected.primary_temporal_evidence, :);
    evidence.supporting_available = height(supporting);
    if height(supporting) > 0
        computed = supporting(supporting.status == "computed", :);
        evidence.supporting_missing = height(supporting) - height(computed);
        evidence.supporting_within = nnz(computed.within_tolerance == 1);
        evidence.supporting_outside = nnz(computed.within_tolerance == 0);
        evidence.discrepant_classes = string( ...
            computed.equivalence_class(computed.within_tolerance == 0));
    end
end

temporalRows = detection.temporal.rows;
if height(temporalRows) > 0
    row = temporalRows(temporalRows.match_group_id == groupId, :);
    if height(row) == 1
        evidence.temporal = struct( ...
            temporal_overlap_s=row.temporal_overlap_s(1), ...
            temporal_iou=row.temporal_iou(1), ...
            onset_difference_s=row.onset_difference_s(1), ...
            offset_difference_s=row.offset_difference_s(1), ...
            duration_difference_s=row.duration_difference_s(1), ...
            direction="run_b minus run_a", ...
            source="stored candidate_pairs evidence");
    end
end

evidence.run_a_extractor = analysis.run_a.extractor_name;
evidence.run_b_extractor = analysis.run_b.extractor_name;
evidence.minimum_supporting_comparisons = ...
    specification.minimum_supporting_comparisons;
evidence.missing_feature_policy = specification.missing_feature_policy;
end

function value = rationaleFor(analysis, specification, matchType, status, ...
        rule, evidence, manualStatus, manualReviewId, reviewerLabel)
value = struct( ...
    rule_set=struct( ...
        profile_key=specification.profile_key, ...
        version_label=specification.version_label, ...
        checksum_sha256=specification.checksum_sha256, ...
        algorithm_key=consilienceAlgorithm().key, ...
        algorithm_version=consilienceAlgorithm().version), ...
    matching_analysis=struct(run_key=analysis.run_key, ...
        analysis_run_id=analysis.analysis_run_id), ...
    topology=matchType, ...
    automated_status=status, ...
    automated_rule=rule, ...
    feature_evidence=struct( ...
        supporting_available=evidence.supporting_available, ...
        supporting_within_tolerance=evidence.supporting_within, ...
        supporting_outside_tolerance=evidence.supporting_outside, ...
        supporting_not_computed=evidence.supporting_missing, ...
        discrepant_equivalence_classes=evidence.discrepant_classes, ...
        minimum_required=evidence.minimum_supporting_comparisons, ...
        missing_feature_policy=evidence.missing_feature_policy, ...
        ineligible_relationships_excluded=true), ...
    temporal_evidence=evidence.temporal, ...
    manual=struct(status=manualStatus, manual_review_id=manualReviewId, ...
        reviewer_label=reviewerLabel, ...
        precedence="manual adjudication is reported beside the automated " + ...
            "status and never overwrites it"), ...
    score_omitted_reason="a consilience status is a categorical evidence " + ...
        "summary, not a calibrated probability");
end

% ----------------------------------------------------------------- manual ---

function manual = manualAdjudications(conn, analysis)
%MANUALADJUDICATIONS Independent adjudication targeting this analysis's groups.
%
% Read from manual_reviews only. Extractor curation, native labels, and detector
% scores are never consulted: a manual verdict derived from an extractor's own
% accept flag would not be independent evidence.
manual = fetch(conn, "SELECT mr.manual_review_id, mr.match_group_id, " + ...
    "mr.review_status, IFNULL(mr.reviewer_label,'') AS reviewer_label " + ...
    "FROM manual_reviews mr " + ...
    "JOIN match_groups mg ON mg.match_group_id=mr.match_group_id " + ...
    "WHERE mg.analysis_run_id=" + string(analysis.analysis_run_id) + ...
    " ORDER BY mr.manual_review_id");
if height(manual) == 0
    manual = table(zeros(0, 1), zeros(0, 1), strings(0, 1), strings(0, 1), ...
        VariableNames=["manual_review_id", "match_group_id", ...
        "review_status", "reviewer_label"]);
end
end

function [status, reviewId, reviewerLabel] = manualVerdict(manualRow)
status = "not_reviewed";
reviewId = NaN;
reviewerLabel = "";
if height(manualRow) == 0
    return
end
if height(manualRow) > 1
    error("vawlume:consilience:ManualReviewAmbiguous", ...
        "Match group %d carries %d manual reviews; exactly one is expected.", ...
        double(manualRow.match_group_id(1)), height(manualRow));
end
reviewId = double(manualRow.manual_review_id(1));
reviewerLabel = presentText(manualRow.reviewer_label(1));
declared = presentText(manualRow.review_status(1));
allowed = ["adjudicated_positive", "adjudicated_negative", "manually_reviewed"];
if ~ismember(declared, allowed)
    error("vawlume:consilience:ManualStatusUnsupported", ...
        ['Manual review %d declares status ''%s'', which is outside the frozen ' ...
        'adjudication vocabulary (%s).'], reviewId, declared, ...
        strjoin(allowed, ", "));
end
status = declared;
end

% ---------------------------------------------------------------- shaping ---

function counts = statusCounts(rows)
counts = table(strings(0, 1), zeros(0, 1), zeros(0, 1), ...
    VariableNames=["status", "group_count", "manually_reviewed_count"]);
if height(rows) == 0
    return
end
for status = ["single_extractor", "temporally_matched", ...
        "matched_feature_supported", "matched_feature_discrepant", ...
        "ambiguous_split_merge"]
    selected = rows.automated_status == status;
    counts(end + 1, :) = {status, nnz(selected), ...
        nnz(selected & rows.manual_status ~= "not_reviewed")}; %#ok<AGROW>
end
end

function value = emptyRows()
value = table(zeros(0, 1), strings(0, 1), strings(0, 1), strings(0, 1), ...
    strings(0, 1), zeros(0, 1), strings(0, 1), strings(0, 1), ...
    zeros(0, 1), zeros(0, 1), zeros(0, 1), zeros(0, 1), strings(0, 1), ...
    strings(0, 1), ...
    VariableNames=["match_group_id", "match_type", "automated_status", ...
    "automated_rule", "manual_status", "manual_review_id", "reviewer_label", ...
    "effective_status", "supporting_available", "supporting_within", ...
    "supporting_outside", "supporting_missing", "discrepant_classes", ...
    "rationale_json"]);
end

function value = presentText(value)
value = string(value);
value(ismissing(value)) = "";
end
