function [counts, agreementAnalysis] = consilienceApplyStatistics( ...
        conn, analysis, specification, detection, feature)
%CONSILIENCEAPPLYSTATISTICS Persist aggregate agreement under a child analysis run.
%
% Only aggregates are stored, in agreement_statistics, which the schema provides
% for exactly this with a statistic_kind vocabulary and optional feature_a_id /
% feature_b_id. Per-pair comparison rows are not persisted: no schema row can
% hold a match group, two detections, and two features with explicit lineage, and
% every per-pair value is exactly recomputable from stored candidates,
% measurements, and the registry. Caching them would create a second copy that
% could drift from the evidence.
%
% The results live under their own analysis_runs row whose parent is the matching
% analysis, so a changed agreement algorithm produces a new child rather than
% mutating an earlier summary.

runKey = agreementRunKey(analysis.run_key);
existing = fetch(conn, "SELECT analysis_run_id, status, IFNULL(notes,'') AS notes " + ...
    "FROM analysis_runs WHERE project_id=" + string(analysis.project_id) + ...
    " AND run_key=" + sqlText(runKey));
rows = statisticRows(detection, feature);

if height(existing) > 0
    agreementAnalysis = reuseOrConflict(conn, analysis, existing, runKey, rows);
    counts = emptyCounts();
    counts.reused_analysis_runs = 1;
    counts.reused_agreement_statistics = height(rows);
    return
end

oldAutoCommit = string(conn.AutoCommit);
if oldAutoCommit ~= "on"
    error("vawlume:consilience:TransactionState", ...
        "Agreement apply requires a connection with AutoCommit enabled.");
end
counts = emptyCounts();
conn.AutoCommit = "off";
try
    analysisRunId = consilienceInsertRow(conn, "analysis_runs", struct( ...
        project_id=analysis.project_id, ...
        parent_analysis_run_id=analysis.analysis_run_id, ...
        run_type="cross_extractor_agreement", run_key=runKey, ...
        run_label="Detection and feature agreement for " + analysis.run_key, ...
        status="started", notes=analysisNotes(analysis, specification)), ...
        "analysis_run_id");
    counts.analysis_runs = 1;
    consilienceInsertRow(conn, "analysis_run_profiles", struct( ...
        analysis_run_id=analysisRunId, ...
        profile_version_id=specification.profile_version_id, ...
        assignment_role="agreement_spec"));
    counts.analysis_run_profiles = 1;
    for role = ["run_a", "run_b"]
        consilienceInsertRow(conn, "analysis_run_extraction_inputs", struct( ...
            analysis_run_id=analysisRunId, ...
            extraction_run_id=analysis.(role).extraction_run_id, input_role=role));
    end
    counts.analysis_run_extraction_inputs = 2;
    for index = 1:height(rows)
        row = rows(index, :);
        values = struct(analysis_run_id=analysisRunId, ...
            statistic_kind=row.statistic_kind, statistic_name=row.statistic_name, ...
            statistic_value=row.statistic_value, notes=row.notes);
        if ~isnan(row.feature_a_id)
            values.feature_a_id = row.feature_a_id;
            values.feature_b_id = row.feature_b_id;
        end
        if ~isnan(row.n_observations)
            values.n_observations = row.n_observations;
        end
        consilienceInsertRow(conn, "agreement_statistics", values, ...
            "agreement_statistic_id");
    end
    counts.agreement_statistics = height(rows);
    execute(conn, "UPDATE analysis_runs SET status='completed', " + ...
        "completed_at_utc=strftime('%Y-%m-%dT%H:%M:%fZ','now') " + ...
        "WHERE analysis_run_id=" + string(analysisRunId));
    commit(conn);
catch exception
    try
        rollback(conn);
    catch
    end
    conn.AutoCommit = oldAutoCommit;
    rethrow(exception);
end
conn.AutoCommit = oldAutoCommit;
agreementAnalysis = struct(analysis_run_id=analysisRunId, run_key=runKey, ...
    parent_analysis_run_id=analysis.analysis_run_id, status="committed", ...
    action="create", statistic_count=height(rows));
end

function agreementAnalysis = reuseOrConflict(conn, analysis, existing, runKey, rows)
%REUSEORCONFLICT An existing summary is reused only if it is identical.
%
% Nothing is updated in place. A different result under the same key means the
% inputs or the algorithm changed, which is a new analysis, not a correction.
analysisRunId = double(existing.analysis_run_id(1));
stored = fetch(conn, "SELECT statistic_kind, statistic_name, " + ...
    "IFNULL(statistic_value, 1e308) AS statistic_value, " + ...
    "IFNULL(n_observations, -1) AS n_observations " + ...
    "FROM agreement_statistics WHERE analysis_run_id=" + string(analysisRunId) + ...
    " ORDER BY statistic_kind, statistic_name");
expected = sortrows(rows, ["statistic_kind", "statistic_name"]);
mismatch = height(stored) ~= height(expected);
if ~mismatch
    for index = 1:height(expected)
        if presentText(stored.statistic_kind(index)) ~= expected.statistic_kind(index) || ...
                presentText(stored.statistic_name(index)) ~= expected.statistic_name(index) || ...
                ~valuesAgree(double(stored.statistic_value(index)), ...
                    expected.statistic_value(index))
            mismatch = true;
            break
        end
    end
end
if mismatch
    error("vawlume:consilience:AgreementConflict", ...
        ['Agreement analysis ''%s'' already exists with different statistics. ' ...
        'A changed algorithm or changed inputs require a new analysis key ' ...
        'rather than rewriting a stored summary.'], runKey);
end
agreementAnalysis = struct(analysis_run_id=analysisRunId, run_key=runKey, ...
    parent_analysis_run_id=analysis.analysis_run_id, status="reused", ...
    action="reuse", statistic_count=height(rows));
end

function value = valuesAgree(stored, expected)
if isnan(expected)
    value = stored >= 1e307;
    return
end
if stored >= 1e307
    value = false;
    return
end
value = abs(stored - expected) <= 1e-9 * max(1, abs(expected));
end

function rows = statisticRows(detection, feature)
rows = emptyRows();
for index = 1:height(detection.per_run)
    run = detection.per_run(index, :);
    context = string(jsonencode(struct( ...
        run_role=run.run_role, extractor_name=run.extractor_name, ...
        extraction_run_key=run.run_key, ...
        denominator="that run's own detection count on this recording")));
    prefix = run.run_role + ".";
    rows = append(rows, "detection_agreement", prefix + "total_detections", ...
        run.total_detections, run.total_detections, context);
    rows = append(rows, "detection_agreement", prefix + "in_cross_extractor_groups", ...
        run.in_cross_extractor_groups, run.total_detections, context);
    rows = append(rows, "detection_agreement", prefix + "in_one_to_one_groups", ...
        run.in_one_to_one_groups, run.total_detections, context);
    rows = append(rows, "detection_agreement", prefix + "in_ambiguous_groups", ...
        run.in_ambiguous_groups, run.total_detections, context);
    rows = append(rows, "detection_agreement", prefix + "unmatched_detections", ...
        run.unmatched_detections, run.total_detections, context);
    rows = append(rows, "detection_agreement", prefix + "proportion_in_groups", ...
        run.proportion_in_groups, run.total_detections, context);
    rows = append(rows, "detection_agreement", prefix + "proportion_one_to_one", ...
        run.proportion_one_to_one, run.total_detections, context);
    rows = append(rows, "detection_agreement", prefix + "proportion_ambiguous", ...
        run.proportion_ambiguous, run.total_detections, context);
    rows = append(rows, "detection_agreement", prefix + "proportion_unmatched", ...
        run.proportion_unmatched, run.total_detections, context);
end
symmetricContext = string(jsonencode(struct( ...
    definition=detection.symmetric.definition, ...
    caution=detection.symmetric.caution)));
rows = append(rows, "detection_agreement", "pooled_matched_coverage", ...
    detection.symmetric.pooled_matched_coverage, ...
    detection.symmetric.denominator, symmetricContext);

for index = 1:height(detection.topology)
    row = detection.topology(index, :);
    context = string(jsonencode(struct(match_type=row.match_type, ...
        run_a_detections=row.run_a_detections, ...
        run_b_detections=row.run_b_detections)));
    rows = append(rows, "matching_diagnostic", ...
        "topology.groups." + row.match_type, row.group_count, NaN, context);
    rows = append(rows, "matching_diagnostic", ...
        "topology.detections." + row.match_type, row.detection_count, NaN, context);
end
for index = 1:height(detection.temporal.summary)
    row = detection.temporal.summary(index, :);
    context = string(jsonencode(struct( ...
        source=detection.temporal.source, ...
        direction="run_b minus run_a")));
    rows = append(rows, "matching_diagnostic", ...
        "temporal.mean_signed." + row.statistic, row.mean_signed, row.n, context);
    rows = append(rows, "matching_diagnostic", ...
        "temporal.median_absolute." + row.statistic, row.median_absolute, ...
        row.n, context);
end

for index = 1:height(feature.summary)
    row = feature.summary(index, :);
    context = string(jsonencode(struct( ...
        equivalence_class=row.equivalence_class, ...
        relationship_type=row.relationship_type, ...
        canonical_unit=row.canonical_unit, ...
        direction="run_b minus run_a", ...
        scope="one_to_one groups only", ...
        primary_temporal_evidence=row.primary_temporal_evidence)));
    prefix = "feature." + row.equivalence_class + ".";
    rows = appendFeature(rows, prefix + "mean_signed_bias", ...
        row.mean_signed_bias, row.n_pairs, row.feature_a_id, row.feature_b_id, context);
    rows = appendFeature(rows, prefix + "median_signed_bias", ...
        row.median_signed_bias, row.n_pairs, row.feature_a_id, row.feature_b_id, context);
    rows = appendFeature(rows, prefix + "mean_absolute_difference", ...
        row.mean_absolute_difference, row.n_pairs, row.feature_a_id, row.feature_b_id, context);
    rows = appendFeature(rows, prefix + "median_absolute_difference", ...
        row.median_absolute_difference, row.n_pairs, row.feature_a_id, row.feature_b_id, context);
    rows = appendFeature(rows, prefix + "outside_tolerance_count", ...
        row.outside_tolerance_count, row.n_pairs, row.feature_a_id, row.feature_b_id, context);
end
rows = sortrows(rows, ["statistic_kind", "statistic_name"]);
end

function rows = append(rows, kind, name, value, n, context)
rows(end + 1, :) = {string(kind), string(name), double(value), NaN, NaN, ...
    double(n), string(context)};
end

function rows = appendFeature(rows, name, value, n, featureA, featureB, context)
rows(end + 1, :) = {"feature_agreement", string(name), double(value), ...
    double(featureA), double(featureB), double(n), string(context)};
end

function value = agreementRunKey(matchingRunKey)
value = matchingRunKey + ":agreement:" + consilienceAlgorithm().key + ...
    "@" + consilienceAlgorithm().version;
end

function value = analysisNotes(analysis, specification)
value = string(jsonencode(struct( ...
    algorithm_key=consilienceAlgorithm().key, ...
    algorithm_version=consilienceAlgorithm().version, ...
    matching_run_key=analysis.run_key, ...
    specification_profile_key=specification.profile_key, ...
    specification_version_label=specification.version_label, ...
    specification_checksum_sha256=specification.checksum_sha256, ...
    per_pair_rows_persisted=false, ...
    per_pair_rows_reason="recomputable from candidates, measurements, and registry")));
end

function rows = emptyRows()
rows = table(strings(0, 1), strings(0, 1), zeros(0, 1), zeros(0, 1), ...
    zeros(0, 1), zeros(0, 1), strings(0, 1), ...
    VariableNames=["statistic_kind", "statistic_name", "statistic_value", ...
    "feature_a_id", "feature_b_id", "n_observations", "notes"]);
end

function counts = emptyCounts()
counts = struct(analysis_runs=0, analysis_run_profiles=0, ...
    analysis_run_extraction_inputs=0, agreement_statistics=0, ...
    reused_analysis_runs=0, reused_agreement_statistics=0);
end

function value = presentText(value)
value = string(value);
value(ismissing(value)) = "";
end

function value = sqlText(text)
value = "'" + replace(string(text), "'", "''") + "'";
end
