function manualQc = consilienceManualQc(conn, analysis, specification, classification)
%CONSILIENCEMANUALQC Evaluate both runs against an independent manual reference.
%
% The reference is reviewer-authored, lives in manual_reference_events, is scoped
% to the recording rather than to any analysis, and is never derived from an
% extractor. That independence is the whole point: an extractor evaluated against
% its own accept flag would agree with itself.
%
% The detection-to-reference rule is deliberately separate from the
% extractor-to-extractor rule, so neither can be tuned through the other.
%
% Recall and false negatives are only computed when the specification declares
% the reference set exhaustive over the recording. Without that claim, a
% detection with no overlapping reference event might simply lie in a region
% nobody reviewed, and precision would be the only defensible figure.

reference = fetch(conn, "SELECT manual_reference_event_id, " + ...
    "IFNULL(native_reference_id,'') AS native_reference_id, " + ...
    "IFNULL(reviewer_label,'') AS reviewer_label, " + ...
    "start_time_s, end_time_s, event_status FROM manual_reference_events " + ...
    "WHERE recording_id=" + string(analysis.recording_id) + ...
    " AND reference_set_key=" + sqlText(specification.reference_set_key) + ...
    " ORDER BY start_time_s, manual_reference_event_id");

manualQc = struct( ...
    reference_set_key=specification.reference_set_key, ...
    reference_available=height(reference) > 0, ...
    reference_event_count=height(reference), ...
    coverage=specification.reference_coverage, ...
    recall_reportable=specification.reference_coverage == "exhaustive_over_recording", ...
    matching_rule=struct( ...
        purpose="detection to manual reference, separate from the " + ...
            "extractor-to-extractor rule", ...
        require_positive_overlap=true, ...
        min_temporal_iou=specification.manual_min_temporal_iou, ...
        assignment="greatest temporal IoU, each side used at most once"), ...
    per_run=emptyPerRun(), ...
    links=emptyLinks(), ...
    unmatched_reference_events=emptyUnmatchedReference(), ...
    contingency=emptyContingency(), ...
    curation_cross_reference=emptyCuration(), ...
    caution=cautionNote());
if ~manualQc.reference_available
    return
end

for role = ["run_a", "run_b"]
    run = analysis.(role);
    detections = fetch(conn, "SELECT detection_id, " + ...
        "IFNULL(native_event_id,'') AS native_event_id, " + ...
        "start_time_s, end_time_s FROM detections WHERE extraction_run_id=" + ...
        string(run.extraction_run_id) + " AND recording_id=" + ...
        string(analysis.recording_id) + " ORDER BY start_time_s, detection_id");
    [links, unmatchedReference] = linkToReference(detections, reference, ...
        specification.manual_min_temporal_iou);
    truePositives = height(links);
    falsePositives = height(detections) - truePositives;
    falseNegatives = height(unmatchedReference);

    for index = 1:height(links)
        manualQc.links(end + 1, :) = {role, run.extractor_name, ...
            links.detection_id(index), links.native_event_id(index), ...
            links.manual_reference_event_id(index), ...
            links.native_reference_id(index), links.temporal_iou(index), ...
            links.onset_error_s(index), links.offset_error_s(index)};
    end
    for index = 1:height(unmatchedReference)
        manualQc.unmatched_reference_events(end + 1, :) = {role, ...
            run.extractor_name, ...
            unmatchedReference.manual_reference_event_id(index), ...
            unmatchedReference.native_reference_id(index), ...
            unmatchedReference.start_time_s(index), ...
            unmatchedReference.end_time_s(index)};
    end

    if manualQc.recall_reportable
        recall = ratio(truePositives, truePositives + falseNegatives);
        reportedFalseNegatives = falseNegatives;
    else
        recall = NaN;
        reportedFalseNegatives = NaN;
    end
    manualQc.per_run(end + 1, :) = {role, run.extractor_name, ...
        height(detections), height(reference), truePositives, falsePositives, ...
        reportedFalseNegatives, ratio(truePositives, truePositives + falsePositives), ...
        recall, meanOrNaN(abs(links.onset_error_s)), ...
        meanOrNaN(abs(links.offset_error_s))};
end

manualQc.contingency = contingencyTable(conn, analysis, classification, ...
    manualQc.links);
manualQc.curation_cross_reference = curationCrossReference(conn, analysis, ...
    manualQc.links);
end

% -------------------------------------------------------------- reference ---

function [links, unmatchedReference] = linkToReference(detections, reference, minIou)
%LINKTOREFERENCE Greedy highest-IoU assignment, each side used at most once.
%
% One-to-one by construction: a reference event cannot count as a true positive
% for two detections, and a detection cannot be excused by two reference events.
links = emptyLinkRows();
usedReference = false(height(reference), 1);
usedDetection = false(height(detections), 1);

candidates = zeros(0, 3);
for d = 1:height(detections)
    for r = 1:height(reference)
        iou = temporalIou(detections.start_time_s(d), detections.end_time_s(d), ...
            reference.start_time_s(r), reference.end_time_s(r));
        if iou >= minIou && iou > 0
            candidates(end + 1, :) = [iou, d, r]; %#ok<AGROW>
        end
    end
end
if ~isempty(candidates)
    candidates = sortrows(candidates, [-1, 2, 3]);
    for index = 1:height(candidates)
        d = candidates(index, 2);
        r = candidates(index, 3);
        if usedDetection(d) || usedReference(r)
            continue
        end
        usedDetection(d) = true;
        usedReference(r) = true;
        links(end + 1, :) = {double(detections.detection_id(d)), ...
            presentText(detections.native_event_id(d)), ...
            double(reference.manual_reference_event_id(r)), ...
            presentText(reference.native_reference_id(r)), ...
            candidates(index, 1), ...
            double(detections.start_time_s(d)) - double(reference.start_time_s(r)), ...
            double(detections.end_time_s(d)) - double(reference.end_time_s(r))}; %#ok<AGROW>
    end
end
if height(links) > 0
    links = sortrows(links, "detection_id");
end

unmatchedReference = table(zeros(0, 1), strings(0, 1), zeros(0, 1), zeros(0, 1), ...
    VariableNames=["manual_reference_event_id", "native_reference_id", ...
    "start_time_s", "end_time_s"]);
for r = 1:height(reference)
    if usedReference(r)
        continue
    end
    unmatchedReference(end + 1, :) = { ...
        double(reference.manual_reference_event_id(r)), ...
        presentText(reference.native_reference_id(r)), ...
        double(reference.start_time_s(r)), double(reference.end_time_s(r))}; %#ok<AGROW>
end
end

function value = temporalIou(startA, endA, startB, endB)
intersection = max(0, min(endA, endB) - max(startA, startB));
union = max(endA, endB) - min(startA, startB);
if union <= 0
    value = 0;
    return
end
value = intersection / union;
end

% ------------------------------------------------------------ contingency ---

function contingency = contingencyTable(conn, analysis, classification, links)
%CONTINGENCYTABLE Automated status against independent manual evidence.
%
% Counts only. Turning this into a predictive claim would require calibration
% against real annotated data, which does not exist.
contingency = emptyContingency();
if isempty(classification) || height(classification.assessments) == 0
    return
end
members = fetch(conn, "SELECT mgm.match_group_id, mgm.detection_id " + ...
    "FROM match_group_members mgm " + ...
    "JOIN match_groups mg ON mg.match_group_id=mgm.match_group_id " + ...
    "WHERE mg.analysis_run_id=" + string(analysis.analysis_run_id));
supportedDetections = [];
if height(links) > 0
    supportedDetections = links.detection_id;
end

assessments = classification.assessments;
verdicts = strings(height(assessments), 1);
for index = 1:height(assessments)
    groupId = assessments.match_group_id(index);
    detectionIds = members.detection_id(members.match_group_id == groupId);
    if any(ismember(double(detectionIds), supportedDetections))
        verdicts(index) = "reference_supported";
    else
        verdicts(index) = "reference_absent";
    end
end

for status = ["single_extractor", "temporally_matched", ...
        "matched_feature_supported", "matched_feature_discrepant", ...
        "ambiguous_split_merge"]
    selected = assessments.automated_status == status;
    if ~any(selected)
        continue
    end
    contingency(end + 1, :) = {status, nnz(selected), ...
        nnz(selected & verdicts == "reference_supported"), ...
        nnz(selected & verdicts == "reference_absent"), ...
        nnz(selected & assessments.manual_status == "adjudicated_positive"), ...
        nnz(selected & assessments.manual_status == "adjudicated_negative")}; %#ok<AGROW>
end
end

function crossReference = curationCrossReference(conn, analysis, links)
%CURATIONCROSSREFERENCE DeepSqueak's own accept flag against the reference.
%
% Reported as secondary evidence only. It generates no manual label and enters no
% consilience status rule; it is extractor curation, and comparing it with an
% independent reference is a question about the extractor, not an input to
% validation.
crossReference = emptyCuration();
rows = fetch(conn, "SELECT e.extractor_name, ce.status_after, " + ...
    "ce.detection_id FROM curation_events ce " + ...
    "JOIN detections d ON d.detection_id=ce.detection_id " + ...
    "JOIN extraction_runs er ON er.extraction_run_id=d.extraction_run_id " + ...
    "JOIN extractor_versions ev ON ev.extractor_version_id=er.extractor_version_id " + ...
    "JOIN extractors e ON e.extractor_id=ev.extractor_id " + ...
    "WHERE d.extraction_run_id IN (" + ...
    string(analysis.run_a.extraction_run_id) + "," + ...
    string(analysis.run_b.extraction_run_id) + ")");
if height(rows) == 0
    return
end
supportedDetections = [];
if height(links) > 0
    supportedDetections = links.detection_id;
end
states = presentText(rows.status_after);
supported = ismember(double(rows.detection_id), supportedDetections);
for extractor = unique(presentText(rows.extractor_name))'
    for state = unique(states)'
        selected = presentText(rows.extractor_name) == extractor & states == state;
        if ~any(selected)
            continue
        end
        crossReference(end + 1, :) = {extractor, state, nnz(selected), ...
            nnz(selected & supported), nnz(selected & ~supported)}; %#ok<AGROW>
    end
end
end

% ---------------------------------------------------------------- shaping ---

function value = cautionNote()
value = [ ...
    "The reference subset demonstrates evaluation logic. It is synthetic and " + ...
        "small, and is not scientific performance evidence."; ...
    "Precision and recall are computed against one reviewer-authored set " + ...
        "under one declared matching rule, both of which are configuration."; ...
    "DeepSqueak's accept flag is reported beside the reference as extractor " + ...
        "curation. It generates no manual label and enters no status rule."];
end

function value = ratio(numerator, denominator)
if denominator == 0
    value = NaN;
    return
end
value = numerator / denominator;
end

function value = meanOrNaN(values)
if isempty(values)
    value = NaN;
    return
end
value = mean(values);
end

function value = emptyPerRun()
value = table(strings(0, 1), strings(0, 1), zeros(0, 1), zeros(0, 1), ...
    zeros(0, 1), zeros(0, 1), zeros(0, 1), zeros(0, 1), zeros(0, 1), ...
    zeros(0, 1), zeros(0, 1), ...
    VariableNames=["run_role", "extractor_name", "detection_count", ...
    "reference_event_count", "true_positives", "false_positives", ...
    "false_negatives", "precision", "recall", "mean_absolute_onset_error_s", ...
    "mean_absolute_offset_error_s"]);
end

function value = emptyLinks()
value = table(strings(0, 1), strings(0, 1), zeros(0, 1), strings(0, 1), ...
    zeros(0, 1), strings(0, 1), zeros(0, 1), zeros(0, 1), zeros(0, 1), ...
    VariableNames=["run_role", "extractor_name", "detection_id", ...
    "native_event_id", "manual_reference_event_id", "native_reference_id", ...
    "temporal_iou", "onset_error_s", "offset_error_s"]);
end

function value = emptyLinkRows()
value = table(zeros(0, 1), strings(0, 1), zeros(0, 1), strings(0, 1), ...
    zeros(0, 1), zeros(0, 1), zeros(0, 1), ...
    VariableNames=["detection_id", "native_event_id", ...
    "manual_reference_event_id", "native_reference_id", "temporal_iou", ...
    "onset_error_s", "offset_error_s"]);
end

function value = emptyUnmatchedReference()
value = table(strings(0, 1), strings(0, 1), zeros(0, 1), strings(0, 1), ...
    zeros(0, 1), zeros(0, 1), ...
    VariableNames=["run_role", "extractor_name", "manual_reference_event_id", ...
    "native_reference_id", "start_time_s", "end_time_s"]);
end

function value = emptyContingency()
value = table(strings(0, 1), zeros(0, 1), zeros(0, 1), zeros(0, 1), ...
    zeros(0, 1), zeros(0, 1), ...
    VariableNames=["automated_status", "group_count", ...
    "reference_supported", "reference_absent", ...
    "adjudicated_positive", "adjudicated_negative"]);
end

function value = emptyCuration()
value = table(strings(0, 1), strings(0, 1), zeros(0, 1), zeros(0, 1), zeros(0, 1), ...
    VariableNames=["extractor_name", "curation_status", "detection_count", ...
    "reference_supported", "reference_absent"]);
end

function value = presentText(value)
value = string(value);
value(ismissing(value)) = "";
end

function value = sqlText(text)
value = "'" + replace(string(text), "'", "''") + "'";
end
