function [rows, gate] = edaCandidateRows(conn, analysis)
%EDACANDIDATEROWS Read one analysis's stored candidate evidence and its gate.
%
% Every temporal metric is read from the stored candidate_pairs row. None is
% recomputed from detection boundaries. vawlume.consilience.summarize makes the
% same choice explicitly, describing its temporal agreement as read from the
% stored candidate evidence rather than recomputed, and following it keeps one
% definition of each quantity in the repository.
%
% Two things are resolved here that the stored row cannot supply on its own.
%
% Direction. The signed differences were computed as the caller's run_b minus
% the caller's run_a, but detection_a_id and detection_b_id are ordered by
% detection id to satisfy a schema CHECK and carry no run meaning. Pooling
% signed differences across analyses without resolving direction produces a
% bimodal distribution for a reason that is not biological. The caller's order
% comes from analysis_run_extraction_inputs.input_role, and every row's
% details_json is checked against it rather than trusted.
%
% The active gate. details_json records which plausibility gates admitted the
% row and at what values. A temporal_iou distribution with a hard left edge at
% 0.1 is a property of the threshold that generated the rows, not of the data,
% and a reader who cannot see the gate will misread the figure.

raw = fetch(conn, candidateQuery() + string(analysis.analysis_run_id) + ...
    " ORDER BY cp.detection_a_id, cp.detection_b_id");
gate = emptyGate(analysis.analysis_run_id);
if isempty(raw) || height(raw) == 0
    rows = emptyRows();
    return
end

detectionARunId = double(raw.detection_a_run_id);
detectionBRunId = double(raw.detection_b_run_id);
foreign = ~ismember(detectionARunId, [analysis.run_a_extraction_run_id, ...
    analysis.run_b_extraction_run_id]) | ...
    ~ismember(detectionBRunId, [analysis.run_a_extraction_run_id, ...
    analysis.run_b_extraction_run_id]);
if any(foreign)
    error("vawlume:eda:CandidateOutsideDeclaredInputs", ...
        "Matching analysis '%s' stores candidate rows whose detections lie " + ...
        "outside its two declared extraction runs.", analysis.matching_run_key);
end

lowerIsA = detectionARunId == analysis.lower_extraction_run_id;
lowerDetectionId = double(raw.detection_a_id);
higherDetectionId = double(raw.detection_b_id);
lowerDetectionId(~lowerIsA) = double(raw.detection_b_id(~lowerIsA));
higherDetectionId(~lowerIsA) = double(raw.detection_a_id(~lowerIsA));

% as_stored means the caller's run_a already held the lower extractor key, so
% the stored "run_b minus run_a" is already "higher key minus lower key".
if analysis.sign_normalization == "as_stored"
    signFactor = 1;
else
    signFactor = -1;
end

details = decodeDetails(raw, analysis);
gate = details.gate;

n = height(raw);
rows = table( ...
    repmat(analysis.analysis_run_id, n, 1), ...
    double(raw.candidate_pair_id), ...
    double(raw.recording_id), ...
    repmat(analysis.project_key, n, 1), ...
    repmat(analysis.matching_run_key, n, 1), ...
    repmat(analysis.configuration_id, n, 1), ...
    repmat(analysis.extractor_pair_key, n, 1), ...
    repmat(analysis.extractor_key_a, n, 1), ...
    repmat(analysis.extractor_key_b, n, 1), ...
    double(raw.detection_a_id), ...
    double(raw.detection_b_id), ...
    lowerDetectionId, ...
    higherDetectionId, ...
    edaSentinelToNaN(raw.temporal_overlap_s), ...
    edaSentinelToNaN(raw.temporal_iou), ...
    signFactor * edaSentinelToNaN(raw.onset_difference_s), ...
    signFactor * edaSentinelToNaN(raw.offset_difference_s), ...
    signFactor * edaSentinelToNaN(raw.duration_difference_s), ...
    abs(edaSentinelToNaN(raw.onset_difference_s)), ...
    abs(edaSentinelToNaN(raw.offset_difference_s)), ...
    abs(edaSentinelToNaN(raw.duration_difference_s)), ...
    edaSentinelToNaN(raw.candidate_score), ...
    edaPresentText(raw.candidate_status), ...
    repmat(gate.eligibility_rule, n, 1), ...
    VariableNames=edaMetricSurfaceColumns());
end

function value = candidateQuery()
% Nullable numeric columns go through the 1e308 sentinel because MATLAB's
% Database Toolbox raises while building a result set containing a SQL NULL,
% before any MATLAB-side normalization could run. See edaSentinelToNaN.
value = "SELECT cp.candidate_pair_id, cp.recording_id, " + ...
    "cp.detection_a_id, cp.detection_b_id, " + ...
    "IFNULL(cp.temporal_overlap_s,1e308) AS temporal_overlap_s, " + ...
    "IFNULL(cp.temporal_iou,1e308) AS temporal_iou, " + ...
    "IFNULL(cp.onset_difference_s,1e308) AS onset_difference_s, " + ...
    "IFNULL(cp.offset_difference_s,1e308) AS offset_difference_s, " + ...
    "IFNULL(cp.duration_difference_s,1e308) AS duration_difference_s, " + ...
    "IFNULL(cp.candidate_score,1e308) AS candidate_score, " + ...
    "IFNULL(cp.candidate_status,'') AS candidate_status, " + ...
    "IFNULL(cp.details_json,'') AS details_json, " + ...
    "da.extraction_run_id AS detection_a_run_id, " + ...
    "db.extraction_run_id AS detection_b_run_id " + ...
    "FROM candidate_pairs cp " + ...
    "JOIN detections da ON da.detection_id=cp.detection_a_id " + ...
    "JOIN detections db ON db.detection_id=cp.detection_b_id " + ...
    "WHERE cp.analysis_run_id=";
end

function details = decodeDetails(raw, analysis)
%DECODEDETAILS Read the gate record and verify the direction it asserts.
texts = edaPresentText(raw.details_json);
gate = emptyGate(analysis.analysis_run_id);
seen = false;
for index = 1:numel(texts)
    if strlength(texts(index)) == 0
        continue
    end
    try
        record = jsondecode(texts(index));
    catch exception
        error("vawlume:eda:CandidateDetailsInvalid", ...
            "Matching analysis '%s' stores an undecodable candidate " + ...
            "details_json: %s", analysis.matching_run_key, exception.message);
    end
    verifyDirection(record, raw, index, analysis);
    current = gateOf(record, analysis.analysis_run_id);
    if ~seen
        gate = current;
        seen = true;
    elseif ~isequaln(rmfield(current, "candidate_rows"), ...
            rmfield(gate, "candidate_rows"))
        error("vawlume:eda:GateRecordInconsistent", ...
            "Matching analysis '%s' stores candidate rows admitted under " + ...
            "different plausibility rules. One analysis is one " + ...
            "configuration, so its rows cannot disagree about the gate.", ...
            analysis.matching_run_key);
    end
end
gate.candidate_rows = height(raw);
details = struct(gate=gate);
end

function verifyDirection(record, raw, index, analysis)
%VERIFYDIRECTION Check the row's own account of direction against input_role.
%
% Two independent records of run direction exist. They must agree, or neither
% can be trusted and every signed metric on this analysis is suspect.
if ~isfield(record, "evidence_direction") || ...
        string(record.evidence_direction) ~= "run_a_to_run_b"
    error("vawlume:eda:DirectionUnverifiable", ...
        "A candidate row of '%s' does not declare the run_a_to_run_b " + ...
        "evidence direction the signed metrics assume.", ...
        analysis.matching_run_key);
end
if isfield(record, "run_a_detection_id") && isfield(record, "run_b_detection_id")
    stored = sort([double(record.run_a_detection_id), ...
        double(record.run_b_detection_id)]);
    actual = sort([double(raw.detection_a_id(index)), ...
        double(raw.detection_b_id(index))]);
    if ~isequal(stored, actual)
        error("vawlume:eda:DirectionInconsistent", ...
            "A candidate row of '%s' names detections in details_json that " + ...
            "differ from its stored pair.", analysis.matching_run_key);
    end
end
if ~isfield(record, "run_a_extraction_run_id")
    return
end
callerRunA = double(record.run_a_extraction_run_id);
if callerRunA ~= analysis.run_a_extraction_run_id
    error("vawlume:eda:DirectionInconsistent", ...
        "Candidate details_json of '%s' records run_a as extraction run " + ...
        "%d while analysis_run_extraction_inputs records %d. The two " + ...
        "records of run direction disagree.", ...
        analysis.matching_run_key, callerRunA, ...
        analysis.run_a_extraction_run_id);
end
end

function gate = gateOf(record, analysisRunId)
gate = emptyGate(analysisRunId);
if isfield(record, "eligibility_rule")
    gate.eligibility_rule = string(record.eligibility_rule);
end
for name = ["min_temporal_iou", edaGateBoundNames()]
    if isfield(record, name)
        gate.(name) = double(record.(name));
    end
end
end

function gate = emptyGate(analysisRunId)
gate = struct();
gate.analysis_run_id = analysisRunId;
gate.eligibility_rule = "";
gate.min_temporal_iou = NaN;
for name = edaGateBoundNames()
    gate.(name) = NaN;
end
gate.candidate_rows = 0;
end

function rows = emptyRows()
rows = table(zeros(0, 1), zeros(0, 1), zeros(0, 1), strings(0, 1), ...
    strings(0, 1), strings(0, 1), strings(0, 1), strings(0, 1), ...
    strings(0, 1), zeros(0, 1), zeros(0, 1), zeros(0, 1), zeros(0, 1), ...
    zeros(0, 1), zeros(0, 1), zeros(0, 1), zeros(0, 1), zeros(0, 1), ...
    zeros(0, 1), zeros(0, 1), zeros(0, 1), zeros(0, 1), strings(0, 1), ...
    strings(0, 1), VariableNames=edaMetricSurfaceColumns());
end
