function value = edaCautionNote()
%EDACAUTIONNOTE The canonical exploratory caution text, carried not paraphrased.
%
% Fixed by the governing contract so the repository speaks in one voice, and
% adapted there from vawlume.consilience.sensitivity's own note. Every
% exploratory artifact carries this text, because a figure or table travels
% without the code that produced it and a docstring therefore cannot reach its
% reader.
value = [ ...
    "Agreement among extractors is methodological evidence, not ground " + ...
        "truth. Extractors can share biases, and a detection reported by " + ...
        "only one extractor may still be a real vocalization."; ...
    "The evidential relationship is not symmetric. Multiple independent " + ...
        "detections may increase confidence; the failure of one or more " + ...
        "extractors to report the same event does not, by itself, establish " + ...
        "that the event is false."; ...
    "Agreement also identifies calls that are simultaneously amenable to " + ...
        "the detection strategies of the participating extractors. That is " + ...
        "related to, but not the same as, evidence that a call is real."; ...
    "These summaries describe how correspondence responds to matching " + ...
        "assumptions in this dataset. No configuration here is optimal, " + ...
        "validated, or calibrated, and none should be described that way. " + ...
        "Agreement between the two sensitivity probes is informative, but " + ...
        "it does not establish that manual calibration is unnecessary."];
end
