function names = edaExampleIndexColumns()
%EDAEXAMPLEINDEXCOLUMNS Contract section L's fixed version-1.0 column order.
names = [ ...
    "index_version", "example_id", "exploration_run_key", ...
    "reference_configuration_id", "reference_profile_version", ...
    "project_key", "recording_id", "native_recording_id", ...
    "supported_extractor_pair_pattern", "member_detection_ids", ...
    "member_extractor_keys", "member_native_event_ids", ...
    "frequency_extent_sources", "group_start_time_s", "group_end_time_s", ...
    "snippet_window_start_s", "snippet_window_end_s", ...
    "snippet_channel_index", "spectrogram_settings_json", "image_path", ...
    "render_status", "render_failure_reason"];
end
