function [generators, source] = edaGeneratorCatalog(k, p)
%EDAGENERATORCATALOG Maximum-resolution generators for a 2^(k-p) fractional factorial.
%
% A small documented lookup rather than a search. The standard generator sets are
% published, well studied, and known to be maximum resolution; a search would
% have to rediscover them and would need its own correctness argument. A lookup
% also guarantees what the design contract requires: the generator choice is
% DETERMINISTIC for a given (k, p), so two runs of the same design assign factors
% identically and their configuration identifiers line up. Without that, the two
% probes cannot be compared at all.
%
% Each entry reads "<added factor> = <product of base factors>". The first k-p
% factors are the base; each remaining factor is defined by its generator.
%
% Returns an empty array when no standard set is tabulated for that (k, p), which
% the caller must treat as "this fraction is unavailable" rather than inventing
% one.
source = "Box, Hunter & Hunter, Statistics for Experimenters, standard " + ...
    "2^(k-p) generator tables; equivalently the NIST/SEMATECH e-Handbook " + ...
    "section 5.3.3.4.7 catalogue of fractional factorial designs.";
catalogue = struct( ...
    k3_p1={"C=AB"}, ...
    k4_p1={"D=ABC"}, ...
    k5_p1={"E=ABCD"}, ...
    k5_p2={["D=AB", "E=AC"]}, ...
    k6_p1={"F=ABCDE"}, ...
    k6_p2={["E=ABC", "F=BCD"]}, ...
    k6_p3={["D=AB", "E=AC", "F=BC"]}, ...
    k7_p1={"G=ABCDEF"}, ...
    k7_p2={["F=ABCD", "G=ABDE"]}, ...
    k7_p3={["E=ABC", "F=BCD", "G=ACD"]}, ...
    k7_p4={["D=AB", "E=AC", "F=BC", "G=ABC"]});
key = "k" + string(k) + "_p" + string(p);
if ~isfield(catalogue, key)
    generators = strings(1, 0);
    return
end
generators = string(catalogue.(key));
end
