function value = edaMetricSurfaceColumns()
%EDAMETRICSURFACECOLUMNS Column order of the candidate-metric table, identifiers first.
%
% Two different "a/b" conventions meet in this table and must not be confused.
%
%   detection_a_id / detection_b_id     ascending DETECTION ID, as the schema
%                                       CHECK stores them; no run meaning
%   extractor_key_a / extractor_key_b   ascending EXTRACTOR KEY, the ordering
%                                       every signed metric here is expressed in
%
% They are not aligned: detection_a_id is not necessarily the detection produced
% by extractor_key_a. lower_extractor_detection_id and
% higher_extractor_detection_id state that mapping explicitly, and exist so no
% caller has to infer it.
value = ["analysis_run_id", "candidate_pair_id", "recording_id", ...
    "project_key", "matching_run_key", "configuration_id", ...
    "extractor_pair_key", "extractor_key_a", "extractor_key_b", ...
    "detection_a_id", "detection_b_id", ...
    "lower_extractor_detection_id", "higher_extractor_detection_id", ...
    "temporal_overlap_s", "temporal_iou", ...
    "onset_difference_s", "offset_difference_s", "duration_difference_s", ...
    "abs_onset_difference_s", "abs_offset_difference_s", ...
    "abs_duration_difference_s", "candidate_score", ...
    "candidate_status", "eligibility_rule"];
end
