function value = report(conn, runRef)
%REPORT Read back one caller-attribution run: what was stored, and what was not.
%
% VALUE = vawlume.attribution.report(CONN, RUNREF) returns what is actually
% persisted for one attribution run — its provenance, targets, candidate callers,
% long-form evidence, imported claims, window correspondences and decisions —
% together with QC that reports facts and judges nothing.
%
% This is read-only. It writes no row, recomputes no score, and re-derives no
% decision. RUNREF accepts attribution_run_id, or project_key plus run_key.
%
% WHAT THIS DOES NOT DO, and the reasons are the phase's:
%
% **It does not rank or choose a caller.** Several candidates per target is the
% ordinary case, not a degenerate one. Every candidate is returned; nothing
% privileges the top-ranked one, because a read surface that showed one and hid
% the rest would reintroduce the single caller_id this representation exists to
% avoid.
%
% **It combines no evidence dimension with any other.** Temporal-alignment,
% pose/localization, visual-identity and acoustic evidence are returned as rows
% carrying their own dimension, units and semantics. No field here is a function
% of more than one of them, and none is named as though it were. Combination is
% Phase 6's business and requires an explicit, versioned method.
%
% **It judges nothing.** No quality score for a run, no threshold that calls a
% run acceptable, no aggregate that reads as a verdict. A count of scoreless
% claims is a fact; "this run has poor score coverage" is a verdict, and only the
% first appears here.
%
% **It does not promote an imported claim into a candidate.** A claim belongs to
% (window, entity) and a candidate to (target, entity). Deciding which
% correspondence is good enough to carry a claim onto a target is a policy
% question, so this function reads across that boundary by joining and never
% closes it by writing. Where one window corresponds to two targets, its claim
% appears against both and neither is marked as chosen.
%
% THE GRAIN OF EACH TABLE, because confusing them is the easiest way to
% miscount:
%
%   targets              one row per attribution target
%   candidates           one row per (target, candidate entity)
%   evidence             one row per stored evidence record
%   imported_claims      one row per (imported window, claimed caller)
%   correspondences      one row per stored correspondence
%   claim_correspondences one row per (claim, correspondence) — the joined story,
%                        so a correspondence whose window carries two claims
%                        appears TWICE here and ONCE in correspondences
%   decisions            one row per (target, policy version)
%   decision_selections  one row per candidate a decision selected
%
% QC counts correspondences from `correspondences`, never from the joined table.
%
% TWO BASES THAT ARE NOT THE SAME FACT, both present on a correspondence:
%
%   iou_basis            'native' or 'aligned' — which intervals the IoU was
%                        computed on
%   target_extent_basis  which of the five derivations gave an agreement group
%                        its interval at all; empty for a detection or consensus
%                        event, which carry their own
%
% Reading one as the other would attribute a clock-drift artefact to a choice
% about group boundaries. Correspondence scores are summarized **per basis pair**
% and never pooled across them, because results on different extent bases rest on
% different intervals and were never comparable.
%
% ABSENCE READS AS ABSENCE. A missing number is NaN, not 0; missing text is "".
% A candidate with no acoustic evidence has no acoustic row, not a zero-valued
% one — a zero would claim a measurement was made. A claim whose source carried
% no score reads as NaN, never as 1.0.
%
% See also VAWLUME.ATTRIBUTION.CORRESPONDWINDOWS, VAWLUME.ATTRIBUTION.DECIDE,
% VAWLUME.ALIGNMENT.REPORT

arguments
    conn
    runRef (1,1) struct
end

run = attributionResolveRun(conn, runRef);
runId = run.attribution_run_id;

targets = attributionReadTargetGeometry(conn, runId);
candidates = readCandidates(conn, runId);
evidence = readEvidence(conn, runId);
claims = readClaims(conn, runId);
correspondences = readCorrespondences(conn, runId);
claimCorrespondences = readClaimCorrespondences(conn, runId);
decisions = readDecisions(conn, runId);
selections = readSelections(conn, runId);
windowCount = countWindows(conn, runId);

value = struct( ...
    attribution_run_id=runId, ...
    run_key=run.run_key, ...
    project_key=run.project_key, ...
    recording_id=run.recording_id, ...
    native_recording_id=run.native_recording_id, ...
    attribution_path=run.attribution_path, ...
    method=run.method, ...
    status=run.status, ...
    analysis_status=run.analysis_status, ...
    settings_profile_version_id=run.settings_profile_version_id, ...
    participating_entity_ids=run.participating_entity_ids, ...
    provenance=run.provenance, ...
    targets=targets, ...
    candidates=candidates, ...
    evidence=evidence, ...
    imported_claims=claims, ...
    correspondences=correspondences, ...
    claim_correspondences=claimCorrespondences, ...
    decisions=decisions, ...
    decision_selections=selections, ...
    qc=qualityControl(targets, candidates, evidence, claims, ...
        correspondences, decisions, windowCount), ...
    dimension_separation_note=dimensionSeparationNote(), ...
    absence_note=absenceNote(), ...
    basis_note=basisNote(), ...
    qc_note=qcNote(), ...
    source="stored attribution_* rows and v_attribution_window_correspondences");
end

% ------------------------------------------------------------------ reads ---

function value = readCandidates(conn, runId)
%READCANDIDATES Every candidate, in stored rank order. None is privileged.
rows = fetch(conn, "SELECT c.attribution_candidate_id, c.attribution_target_id, " + ...
    "c.entity_id, IFNULL(e.native_id,'') AS entity_native_id, " + ...
    "c.candidate_status, IFNULL(c.candidate_rank,-1) AS candidate_rank, " + ...
    "IFNULL(c.score, 1e308) AS score, " + ...
    "IFNULL(c.score_semantics,'') AS score_semantics, " + ...
    "IFNULL(c.probability, 1e308) AS probability, " + ...
    "IFNULL(c.probability_semantics,'') AS probability_semantics, " + ...
    "IFNULL(c.source_label,'') AS source_label " + ...
    "FROM attribution_candidates c " + ...
    "JOIN attribution_targets t " + ...
    "  ON t.attribution_target_id = c.attribution_target_id " + ...
    "LEFT JOIN experimental_entities e ON e.entity_id = c.entity_id " + ...
    "WHERE t.attribution_run_id=" + string(runId) + ...
    " ORDER BY c.attribution_target_id, " + ...
    "IFNULL(c.candidate_rank, 1e9), c.attribution_candidate_id");

value = table(zeros(0, 1), zeros(0, 1), zeros(0, 1), strings(0, 1), ...
    strings(0, 1), zeros(0, 1), zeros(0, 1), strings(0, 1), zeros(0, 1), ...
    strings(0, 1), strings(0, 1), ...
    VariableNames=["attribution_candidate_id", "attribution_target_id", ...
    "entity_id", "entity_native_id", "candidate_status", "candidate_rank", ...
    "score", "score_semantics", "probability", "probability_semantics", ...
    "source_label"]);
for index = 1:height(rows)
    value(end + 1, :) = {double(rows.attribution_candidate_id(index)), ...
        double(rows.attribution_target_id(index)), ...
        double(rows.entity_id(index)), ...
        presentText(rows.entity_native_id(index)), ...
        presentText(rows.candidate_status(index)), ...
        negativeSentinel(rows.candidate_rank(index)), ...
        sentinelNumber(rows.score(index)), ...
        presentText(rows.score_semantics(index)), ...
        sentinelNumber(rows.probability(index)), ...
        presentText(rows.probability_semantics(index)), ...
        presentText(rows.source_label(index))}; %#ok<AGROW>
end
end

function value = readEvidence(conn, runId)
%READEVIDENCE One row per stored evidence record, carrying its own dimension.
%
% Each row states which of the evidence dimensions it belongs to, in its own
% units and with its own semantics. Nothing here merges two rows, and no derived
% column spans dimensions.
rows = fetch(conn, "SELECT ev.attribution_evidence_id, " + ...
    "ev.attribution_target_id, " + ...
    "IFNULL(ev.attribution_candidate_id,-1) AS attribution_candidate_id, " + ...
    "ev.evidence_dimension, ev.evidence_kind, " + ...
    "IFNULL(ev.value_real, 1e308) AS value_real, " + ...
    "IFNULL(ev.value_text,'') AS value_text, " + ...
    "IFNULL(ev.value_units,'') AS value_units, " + ...
    "IFNULL(ev.value_semantics,'') AS value_semantics, " + ...
    "IFNULL(ev.identity_statement_kind,'') AS identity_statement_kind, " + ...
    "IFNULL(ev.tracking_identity_association_id,-1) AS tracking_identity_association_id, " + ...
    "IFNULL(ev.external_event_id,-1) AS external_event_id, " + ...
    "IFNULL(ev.alignment_run_id,-1) AS alignment_run_id, " + ...
    "IFNULL(ev.source_file_id,-1) AS source_file_id, " + ...
    "IFNULL(ev.mapping_profile_version_id,-1) AS mapping_profile_version_id, " + ...
    "IFNULL(ev.source_locator,'') AS source_locator " + ...
    "FROM attribution_evidence ev " + ...
    "JOIN attribution_targets t " + ...
    "  ON t.attribution_target_id = ev.attribution_target_id " + ...
    "WHERE t.attribution_run_id=" + string(runId) + ...
    " ORDER BY ev.attribution_target_id, ev.attribution_evidence_id");

value = table(zeros(0, 1), zeros(0, 1), zeros(0, 1), strings(0, 1), ...
    strings(0, 1), zeros(0, 1), strings(0, 1), strings(0, 1), strings(0, 1), ...
    strings(0, 1), zeros(0, 1), zeros(0, 1), zeros(0, 1), zeros(0, 1), ...
    zeros(0, 1), strings(0, 1), ...
    VariableNames=["attribution_evidence_id", "attribution_target_id", ...
    "attribution_candidate_id", "evidence_dimension", "evidence_kind", ...
    "value_real", "value_text", "value_units", "value_semantics", ...
    "identity_statement_kind", "tracking_identity_association_id", ...
    "external_event_id", "alignment_run_id", "source_file_id", ...
    "mapping_profile_version_id", "source_locator"]);
for index = 1:height(rows)
    value(end + 1, :) = {double(rows.attribution_evidence_id(index)), ...
        double(rows.attribution_target_id(index)), ...
        negativeSentinel(rows.attribution_candidate_id(index)), ...
        presentText(rows.evidence_dimension(index)), ...
        presentText(rows.evidence_kind(index)), ...
        sentinelNumber(rows.value_real(index)), ...
        presentText(rows.value_text(index)), ...
        presentText(rows.value_units(index)), ...
        presentText(rows.value_semantics(index)), ...
        presentText(rows.identity_statement_kind(index)), ...
        negativeSentinel(rows.tracking_identity_association_id(index)), ...
        negativeSentinel(rows.external_event_id(index)), ...
        negativeSentinel(rows.alignment_run_id(index)), ...
        negativeSentinel(rows.source_file_id(index)), ...
        negativeSentinel(rows.mapping_profile_version_id(index)), ...
        presentText(rows.source_locator(index))}; %#ok<AGROW>
end
end

function value = readClaims(conn, runId)
%READCLAIMS The exporting system's caller claims, with their own numbers.
%
% A NULL score reads as NaN. It means the source supplied no number, not that it
% supplied zero, and certainly not that the named caller is certain.
%
% entity_id may be NaN. Under the shipped resolution policy intake resolves every
% label or refuses the import by name, so nothing writes NULL there today; a NaN
% therefore means only that no shipped policy produced this row, and nothing more
% may be inferred from it.
rows = fetch(conn, "SELECT cl.imported_attribution_claim_id, " + ...
    "cl.imported_attribution_window_id, " + ...
    "IFNULL(iw.native_window_id,'') AS native_window_id, " + ...
    "iw.start_time_native, iw.end_time_native, " + ...
    "cl.claim_ordinal, cl.source_caller_label, " + ...
    "IFNULL(cl.entity_id,-1) AS entity_id, " + ...
    "IFNULL(e.native_id,'') AS entity_native_id, " + ...
    "IFNULL(cl.score, 1e308) AS score, " + ...
    "IFNULL(cl.score_semantics,'') AS score_semantics, " + ...
    "IFNULL(cl.probability, 1e308) AS probability, " + ...
    "IFNULL(cl.probability_semantics,'') AS probability_semantics, " + ...
    "IFNULL(cl.source_locator,'') AS source_locator " + ...
    "FROM imported_attribution_claims cl " + ...
    "JOIN imported_attribution_windows iw " + ...
    "  ON iw.imported_attribution_window_id = cl.imported_attribution_window_id " + ...
    "LEFT JOIN experimental_entities e ON e.entity_id = cl.entity_id " + ...
    "WHERE iw.attribution_run_id=" + string(runId) + ...
    " ORDER BY cl.imported_attribution_window_id, cl.claim_ordinal");

value = table(zeros(0, 1), zeros(0, 1), strings(0, 1), zeros(0, 1), ...
    zeros(0, 1), zeros(0, 1), strings(0, 1), zeros(0, 1), strings(0, 1), ...
    zeros(0, 1), strings(0, 1), zeros(0, 1), strings(0, 1), strings(0, 1), ...
    VariableNames=["imported_attribution_claim_id", ...
    "imported_attribution_window_id", "native_window_id", ...
    "start_time_native", "end_time_native", "claim_ordinal", ...
    "source_caller_label", "entity_id", "entity_native_id", "score", ...
    "score_semantics", "probability", "probability_semantics", ...
    "source_locator"]);
for index = 1:height(rows)
    value(end + 1, :) = {double(rows.imported_attribution_claim_id(index)), ...
        double(rows.imported_attribution_window_id(index)), ...
        presentText(rows.native_window_id(index)), ...
        double(rows.start_time_native(index)), ...
        double(rows.end_time_native(index)), ...
        double(rows.claim_ordinal(index)), ...
        presentText(rows.source_caller_label(index)), ...
        negativeSentinel(rows.entity_id(index)), ...
        presentText(rows.entity_native_id(index)), ...
        sentinelNumber(rows.score(index)), ...
        presentText(rows.score_semantics(index)), ...
        sentinelNumber(rows.probability(index)), ...
        presentText(rows.probability_semantics(index)), ...
        presentText(rows.source_locator(index))}; %#ok<AGROW>
end
end

function value = readCorrespondences(conn, runId)
%READCORRESPONDENCES One row per stored correspondence. The counting grain.
rows = fetch(conn, "SELECT DISTINCT c.attribution_window_correspondence_id, " + ...
    "c.imported_attribution_window_id, " + ...
    "IFNULL(c.native_window_id,'') AS native_window_id, " + ...
    "c.attribution_target_id, IFNULL(c.target_kind,'') AS target_kind, " + ...
    "IFNULL(c.target_extent_basis,'') AS target_extent_basis, " + ...
    "c.iou_basis, " + ...
    "IFNULL(c.temporal_overlap_s, 1e308) AS temporal_overlap_s, " + ...
    "IFNULL(c.temporal_iou, 1e308) AS temporal_iou, " + ...
    "IFNULL(c.onset_difference_s, 1e308) AS onset_difference_s, " + ...
    "IFNULL(c.offset_difference_s, 1e308) AS offset_difference_s, " + ...
    "IFNULL(c.alignment_run_id,-1) AS alignment_run_id, " + ...
    "IFNULL(c.aligned_start_s, 1e308) AS aligned_start_s, " + ...
    "IFNULL(c.aligned_end_s, 1e308) AS aligned_end_s, " + ...
    "IFNULL(c.start_extrapolated,-1) AS start_extrapolated, " + ...
    "IFNULL(c.end_extrapolated,-1) AS end_extrapolated, " + ...
    "c.eligibility_rule, " + ...
    "IFNULL(c.min_temporal_iou, 1e308) AS min_temporal_iou " + ...
    "FROM v_attribution_window_correspondences c " + ...
    "WHERE c.attribution_run_id=" + string(runId) + ...
    " ORDER BY c.attribution_window_correspondence_id");

value = table(zeros(0, 1), zeros(0, 1), strings(0, 1), zeros(0, 1), ...
    strings(0, 1), strings(0, 1), strings(0, 1), zeros(0, 1), zeros(0, 1), ...
    zeros(0, 1), zeros(0, 1), zeros(0, 1), zeros(0, 1), zeros(0, 1), ...
    zeros(0, 1), zeros(0, 1), strings(0, 1), zeros(0, 1), ...
    VariableNames=["attribution_window_correspondence_id", ...
    "imported_attribution_window_id", "native_window_id", ...
    "attribution_target_id", "target_kind", "target_extent_basis", ...
    "iou_basis", "temporal_overlap_s", "temporal_iou", "onset_difference_s", ...
    "offset_difference_s", "alignment_run_id", "aligned_start_s", ...
    "aligned_end_s", "start_extrapolated", "end_extrapolated", ...
    "eligibility_rule", "min_temporal_iou"]);
for index = 1:height(rows)
    value(end + 1, :) = { ...
        double(rows.attribution_window_correspondence_id(index)), ...
        double(rows.imported_attribution_window_id(index)), ...
        presentText(rows.native_window_id(index)), ...
        double(rows.attribution_target_id(index)), ...
        presentText(rows.target_kind(index)), ...
        presentText(rows.target_extent_basis(index)), ...
        presentText(rows.iou_basis(index)), ...
        sentinelNumber(rows.temporal_overlap_s(index)), ...
        sentinelNumber(rows.temporal_iou(index)), ...
        sentinelNumber(rows.onset_difference_s(index)), ...
        sentinelNumber(rows.offset_difference_s(index)), ...
        negativeSentinel(rows.alignment_run_id(index)), ...
        sentinelNumber(rows.aligned_start_s(index)), ...
        sentinelNumber(rows.aligned_end_s(index)), ...
        negativeSentinel(rows.start_extrapolated(index)), ...
        negativeSentinel(rows.end_extrapolated(index)), ...
        presentText(rows.eligibility_rule(index)), ...
        sentinelNumber(rows.min_temporal_iou(index))}; %#ok<AGROW>
end
end

function value = readClaimCorrespondences(conn, runId)
%READCLAIMCORRESPONDENCES The joined story: claim, window, event, metrics, bases.
%
% One row per (claim, correspondence). A window carrying two claims produces two
% rows for one correspondence, and a claim whose window corresponds to two
% targets produces two rows for one claim — both are real multiplicities and
% neither is collapsed. Do not count correspondences here; use `correspondences`.
%
% A claim appearing against two targets is the ambiguous case. Nothing in this
% table marks either as chosen, because nothing chose.
rows = fetch(conn, "SELECT c.attribution_window_correspondence_id, " + ...
    "IFNULL(c.imported_attribution_claim_id,-1) AS imported_attribution_claim_id, " + ...
    "IFNULL(c.source_caller_label,'') AS source_caller_label, " + ...
    "IFNULL(c.claimed_entity_id,-1) AS claimed_entity_id, " + ...
    "IFNULL(e.native_id,'') AS claimed_entity_native_id, " + ...
    "IFNULL(c.claim_score, 1e308) AS claim_score, " + ...
    "IFNULL(c.claim_score_semantics,'') AS claim_score_semantics, " + ...
    "IFNULL(c.claim_probability, 1e308) AS claim_probability, " + ...
    "IFNULL(c.claim_probability_semantics,'') AS claim_probability_semantics, " + ...
    "IFNULL(c.native_window_id,'') AS native_window_id, " + ...
    "c.start_time_native, c.end_time_native, " + ...
    "c.attribution_target_id, IFNULL(c.target_kind,'') AS target_kind, " + ...
    "IFNULL(c.detection_id,-1) AS detection_id, " + ...
    "IFNULL(c.consensus_event_id,-1) AS consensus_event_id, " + ...
    "IFNULL(c.agreement_group_id,-1) AS agreement_group_id, " + ...
    "IFNULL(c.target_extent_basis,'') AS target_extent_basis, " + ...
    "c.iou_basis, " + ...
    "IFNULL(c.temporal_iou, 1e308) AS temporal_iou, " + ...
    "IFNULL(c.temporal_overlap_s, 1e308) AS temporal_overlap_s, " + ...
    "IFNULL(c.alignment_run_id,-1) AS alignment_run_id, " + ...
    "IFNULL(c.start_extrapolated,-1) AS start_extrapolated, " + ...
    "IFNULL(c.end_extrapolated,-1) AS end_extrapolated " + ...
    "FROM v_attribution_window_correspondences c " + ...
    "LEFT JOIN experimental_entities e ON e.entity_id = c.claimed_entity_id " + ...
    "WHERE c.attribution_run_id=" + string(runId) + ...
    " ORDER BY c.imported_attribution_window_id, " + ...
    "IFNULL(c.imported_attribution_claim_id,-1), " + ...
    "c.attribution_window_correspondence_id");

value = table(zeros(0, 1), zeros(0, 1), strings(0, 1), zeros(0, 1), ...
    strings(0, 1), zeros(0, 1), strings(0, 1), zeros(0, 1), strings(0, 1), ...
    strings(0, 1), zeros(0, 1), zeros(0, 1), zeros(0, 1), strings(0, 1), ...
    zeros(0, 1), zeros(0, 1), zeros(0, 1), strings(0, 1), strings(0, 1), ...
    zeros(0, 1), zeros(0, 1), zeros(0, 1), zeros(0, 1), zeros(0, 1), ...
    VariableNames=["attribution_window_correspondence_id", ...
    "imported_attribution_claim_id", "source_caller_label", ...
    "claimed_entity_id", "claimed_entity_native_id", "claim_score", ...
    "claim_score_semantics", "claim_probability", ...
    "claim_probability_semantics", "native_window_id", "start_time_native", ...
    "end_time_native", "attribution_target_id", "target_kind", ...
    "detection_id", "consensus_event_id", "agreement_group_id", ...
    "target_extent_basis", "iou_basis", "temporal_iou", "temporal_overlap_s", ...
    "alignment_run_id", "start_extrapolated", "end_extrapolated"]);
for index = 1:height(rows)
    value(end + 1, :) = { ...
        double(rows.attribution_window_correspondence_id(index)), ...
        negativeSentinel(rows.imported_attribution_claim_id(index)), ...
        presentText(rows.source_caller_label(index)), ...
        negativeSentinel(rows.claimed_entity_id(index)), ...
        presentText(rows.claimed_entity_native_id(index)), ...
        sentinelNumber(rows.claim_score(index)), ...
        presentText(rows.claim_score_semantics(index)), ...
        sentinelNumber(rows.claim_probability(index)), ...
        presentText(rows.claim_probability_semantics(index)), ...
        presentText(rows.native_window_id(index)), ...
        double(rows.start_time_native(index)), ...
        double(rows.end_time_native(index)), ...
        double(rows.attribution_target_id(index)), ...
        presentText(rows.target_kind(index)), ...
        negativeSentinel(rows.detection_id(index)), ...
        negativeSentinel(rows.consensus_event_id(index)), ...
        negativeSentinel(rows.agreement_group_id(index)), ...
        presentText(rows.target_extent_basis(index)), ...
        presentText(rows.iou_basis(index)), ...
        sentinelNumber(rows.temporal_iou(index)), ...
        sentinelNumber(rows.temporal_overlap_s(index)), ...
        negativeSentinel(rows.alignment_run_id(index)), ...
        negativeSentinel(rows.start_extrapolated(index)), ...
        negativeSentinel(rows.end_extrapolated(index))}; %#ok<AGROW>
end
end

function value = readDecisions(conn, runId)
%READDECISIONS Each decision with the policy that produced it.
%
% A decision without its policy is not a decision, so the policy version and the
% applied threshold travel with every row. The threshold is uncalibrated: this
% prototype ships no acceptance criterion, and no status here means validated.
rows = fetch(conn, "SELECT d.attribution_decision_id, " + ...
    "d.attribution_target_id, d.decision_status, " + ...
    "d.policy_profile_version_id, " + ...
    "IFNULL(pv.version_label,'') AS policy_version_label, " + ...
    "IFNULL(p.profile_key,'') AS policy_profile_key, " + ...
    "IFNULL(d.applied_threshold, 1e308) AS applied_threshold, " + ...
    "IFNULL(d.applied_threshold_semantics,'') AS applied_threshold_semantics, " + ...
    "IFNULL(d.exclusion_reason,'') AS exclusion_reason, " + ...
    "d.decided_at_utc " + ...
    "FROM attribution_decisions d " + ...
    "JOIN attribution_targets t " + ...
    "  ON t.attribution_target_id = d.attribution_target_id " + ...
    "LEFT JOIN config_profile_versions pv " + ...
    "  ON pv.profile_version_id = d.policy_profile_version_id " + ...
    "LEFT JOIN config_profiles p ON p.profile_id = pv.profile_id " + ...
    "WHERE t.attribution_run_id=" + string(runId) + ...
    " ORDER BY d.attribution_target_id, d.attribution_decision_id");

value = table(zeros(0, 1), zeros(0, 1), strings(0, 1), zeros(0, 1), ...
    strings(0, 1), strings(0, 1), zeros(0, 1), strings(0, 1), strings(0, 1), ...
    strings(0, 1), ...
    VariableNames=["attribution_decision_id", "attribution_target_id", ...
    "decision_status", "policy_profile_version_id", "policy_version_label", ...
    "policy_profile_key", "applied_threshold", "applied_threshold_semantics", ...
    "exclusion_reason", "decided_at_utc"]);
for index = 1:height(rows)
    value(end + 1, :) = {double(rows.attribution_decision_id(index)), ...
        double(rows.attribution_target_id(index)), ...
        presentText(rows.decision_status(index)), ...
        double(rows.policy_profile_version_id(index)), ...
        presentText(rows.policy_version_label(index)), ...
        presentText(rows.policy_profile_key(index)), ...
        sentinelNumber(rows.applied_threshold(index)), ...
        presentText(rows.applied_threshold_semantics(index)), ...
        presentText(rows.exclusion_reason(index)), ...
        presentText(rows.decided_at_utc(index))}; %#ok<AGROW>
end
end

function value = readSelections(conn, runId)
%READSELECTIONS Which candidates a decision selected. A set, never a winner.
rows = fetch(conn, "SELECT dc.attribution_decision_id, " + ...
    "dc.attribution_candidate_id, d.attribution_target_id, " + ...
    "d.decision_status, c.entity_id, " + ...
    "IFNULL(e.native_id,'') AS entity_native_id, " + ...
    "IFNULL(dc.selection_role,'') AS selection_role " + ...
    "FROM attribution_decision_candidates dc " + ...
    "JOIN attribution_decisions d " + ...
    "  ON d.attribution_decision_id = dc.attribution_decision_id " + ...
    "JOIN attribution_candidates c " + ...
    "  ON c.attribution_candidate_id = dc.attribution_candidate_id " + ...
    "JOIN attribution_targets t " + ...
    "  ON t.attribution_target_id = d.attribution_target_id " + ...
    "LEFT JOIN experimental_entities e ON e.entity_id = c.entity_id " + ...
    "WHERE t.attribution_run_id=" + string(runId) + ...
    " ORDER BY dc.attribution_decision_id, dc.attribution_candidate_id");

value = table(zeros(0, 1), zeros(0, 1), zeros(0, 1), strings(0, 1), ...
    zeros(0, 1), strings(0, 1), strings(0, 1), ...
    VariableNames=["attribution_decision_id", "attribution_candidate_id", ...
    "attribution_target_id", "decision_status", "entity_id", ...
    "entity_native_id", "selection_role"]);
for index = 1:height(rows)
    value(end + 1, :) = {double(rows.attribution_decision_id(index)), ...
        double(rows.attribution_candidate_id(index)), ...
        double(rows.attribution_target_id(index)), ...
        presentText(rows.decision_status(index)), ...
        double(rows.entity_id(index)), ...
        presentText(rows.entity_native_id(index)), ...
        presentText(rows.selection_role(index))}; %#ok<AGROW>
end
end

function value = countWindows(conn, runId)
rows = fetch(conn, "SELECT COUNT(*) AS n FROM imported_attribution_windows " + ...
    "WHERE attribution_run_id=" + string(runId));
value = double(rows.n(1));
end

% --------------------------------------------------------------------- QC ---

function value = qualityControl(targets, candidates, evidence, claims, ...
        correspondences, decisions, windowCount)
%QUALITYCONTROL Facts about the run. No verdict, no threshold, no quality score.
%
% Every field is a count, a membership, or an observed range. None is a grade.
% "17 targets received no candidate" is a fact a reader can act on; "this run
% scored 0.62" would be an opinion dressed as a measurement, and this prototype
% has no calibrated basis for one.
value = struct( ...
    target_count=height(targets), ...
    candidate_count=height(candidates), ...
    evidence_count=height(evidence), ...
    imported_window_count=windowCount, ...
    imported_claim_count=height(claims), ...
    correspondence_count=height(correspondences), ...
    decision_count=height(decisions), ...
    targets_without_candidate=targetsWithoutCandidate(targets, candidates), ...
    targets_with_empty_extent=targetsWithEmptyExtent(targets), ...
    candidates_per_target=candidatesPerTarget(targets, candidates), ...
    candidate_status_counts=countByText(candidates, "candidate_status"), ...
    decision_status_counts=countByText(decisions, "decision_status"), ...
    evidence_by_dimension=evidenceByDimension(evidence), ...
    claims_without_score=nnz(isnan(claims.score)), ...
    claims_without_probability=nnz(isnan(claims.probability)), ...
    claims_without_resolved_entity=nnz(isnan(claims.entity_id)), ...
    imported_label_resolution=labelResolution(claims), ...
    windows_without_correspondence=windowsWithout(correspondences, ...
        windowCount), ...
    windows_with_multiple_correspondences=windowsWithMultiple(correspondences), ...
    correspondence_by_basis=correspondenceByBasis(correspondences));
end

function value = targetsWithoutCandidate(targets, candidates)
%TARGETSWITHOUTCANDIDATE A fact, not a failure. Reported with enough identity to
% act on: which target, of which kind, and on which extent basis where that
% applies, since a group may have received candidates under one basis and not
% another.
value = targets(~ismember(targets.attribution_target_id, ...
    candidates.attribution_target_id), ...
    ["attribution_target_id", "target_kind", "target_extent_basis", ...
    "start_time_s", "end_time_s", "extent_is_empty"]);
end

function value = targetsWithEmptyExtent(targets)
%TARGETSWITHEMPTYEXTENT An agreement group whose declared extent is empty has no
% interval, so nothing could correspond to it. Surfaced rather than left to be
% inferred from an absent correspondence.
value = targets(targets.extent_is_empty, ...
    ["attribution_target_id", "target_kind", "target_extent_basis"]);
end

function value = candidatesPerTarget(targets, candidates)
value = table(zeros(0, 1), strings(0, 1), strings(0, 1), zeros(0, 1), ...
    VariableNames=["attribution_target_id", "target_kind", ...
    "target_extent_basis", "candidate_count"]);
for index = 1:height(targets)
    targetId = targets.attribution_target_id(index);
    value(end + 1, :) = {targetId, targets.target_kind(index), ...
        targets.target_extent_basis(index), ...
        nnz(candidates.attribution_target_id == targetId)}; %#ok<AGROW>
end
end

function value = countByText(rows, column)
value = table(strings(0, 1), zeros(0, 1), VariableNames=[column, "count"]);
if height(rows) == 0
    return
end
observed = unique(rows.(column));
for index = 1:numel(observed)
    value(end + 1, :) = {observed(index), ...
        nnz(rows.(column) == observed(index))}; %#ok<AGROW>
end
end

function value = evidenceByDimension(evidence)
%EVIDENCEBYDIMENSION Which dimensions this run carries, counted separately.
%
% One row per dimension present. There is deliberately no total, no coverage
% fraction, and no field spanning two dimensions: a number combining them would
% be the combination Phase 4 does not perform, arrived at by arithmetic instead
% of by method.
value = table(strings(0, 1), zeros(0, 1), zeros(0, 1), zeros(0, 1), ...
    VariableNames=["evidence_dimension", "row_count", ...
    "candidate_level_count", "target_level_count"]);
if height(evidence) == 0
    return
end
observed = unique(evidence.evidence_dimension);
for index = 1:numel(observed)
    rows = evidence(evidence.evidence_dimension == observed(index), :);
    value(end + 1, :) = {observed(index), height(rows), ...
        nnz(~isnan(rows.attribution_candidate_id)), ...
        nnz(isnan(rows.attribution_candidate_id))}; %#ok<AGROW>
end
end

function value = labelResolution(claims)
%LABELRESOLUTION Which imported label resolved to which entity, and how often.
value = table(strings(0, 1), zeros(0, 1), strings(0, 1), zeros(0, 1), ...
    VariableNames=["source_caller_label", "entity_id", "entity_native_id", ...
    "claim_count"]);
if height(claims) == 0
    return
end
labels = unique(claims.source_caller_label);
for index = 1:numel(labels)
    rows = claims(claims.source_caller_label == labels(index), :);
    value(end + 1, :) = {labels(index), rows.entity_id(1), ...
        rows.entity_native_id(1), height(rows)}; %#ok<AGROW>
end
end

function value = windowsWithout(correspondences, windowCount)
%WINDOWSWITHOUT A window matching nothing is a finding, not a failure: an
% attribution system may have emitted a window for a call no extractor found.
%
% Counted from `correspondences`, whose grain is one row per correspondence. The
% joined claim table would overcount a window carrying several claims.
if windowCount == 0
    value = 0;
    return
end
value = windowCount - numel(unique(correspondences.imported_attribution_window_id));
end

function value = windowsWithMultiple(correspondences)
%WINDOWSWITHMULTIPLE The ambiguous case, counted. Nothing resolves it.
value = 0;
if height(correspondences) == 0
    return
end
ids = correspondences.imported_attribution_window_id;
observed = unique(ids);
for index = 1:numel(observed)
    if nnz(ids == observed(index)) > 1
        value = value + 1;
    end
end
end

function value = correspondenceByBasis(correspondences)
%CORRESPONDENCEBYBASIS Score distribution, summarized WITHIN a basis pair.
%
% Never pooled across bases. An IoU computed on aligned intervals is not the IoU
% of the native ones under a piecewise clock, and an IoU against a group's union
% extent is not the IoU against its intersection extent — the intervals differ,
% so the numbers were never comparable. A single run-wide distribution would
% average quantities that measure different things, which is why none is
% offered.
%
% Min, median and max describe what was observed. None is a threshold and none
% grades the run.
value = table(strings(0, 1), strings(0, 1), zeros(0, 1), zeros(0, 1), ...
    zeros(0, 1), zeros(0, 1), zeros(0, 1), ...
    VariableNames=["iou_basis", "target_extent_basis", ...
    "correspondence_count", "window_count", "temporal_iou_min", ...
    "temporal_iou_median", "temporal_iou_max"]);
if height(correspondences) == 0
    return
end
keys = unique(strcat(correspondences.iou_basis, "|", ...
    correspondences.target_extent_basis));
for index = 1:numel(keys)
    parts = split(keys(index), "|");
    rows = correspondences(correspondences.iou_basis == parts(1) & ...
        correspondences.target_extent_basis == parts(2), :);
    ious = rows.temporal_iou(~isnan(rows.temporal_iou));
    if isempty(ious)
        minimum = NaN;
        middle = NaN;
        maximum = NaN;
    else
        minimum = min(ious);
        middle = median(ious);
        maximum = max(ious);
    end
    value(end + 1, :) = {parts(1), parts(2), height(rows), ...
        numel(unique(rows.imported_attribution_window_id)), ...
        minimum, middle, maximum}; %#ok<AGROW>
end
end

% ------------------------------------------------------------------ notes ---

function value = dimensionSeparationNote()
value = "Temporal-alignment, pose/localization, visual-identity and acoustic " + ...
    "evidence are returned as separate rows with their own units and " + ...
    "semantics. No field here combines them, and evidence_by_dimension counts " + ...
    "each separately rather than summing them into a coverage score. An " + ...
    "'imported_composite' row is somebody else's already-combined number, " + ...
    "stored with its producer named; VAWLUME did not compute it and does not " + ...
    "decompose it.";
end

function value = absenceNote()
value = "Absence reads as absence. A missing number is NaN and missing text " + ...
    "is empty, never 0 and never a default. A candidate with no acoustic " + ...
    "evidence has no acoustic row rather than a zero-valued one, because a " + ...
    "zero would claim a measurement was made. A claim with NaN score means the " + ...
    "exporting system supplied no number. A claim with NaN entity_id means no " + ...
    "shipped resolution policy produced that row, and nothing further may be " + ...
    "inferred from it.";
end

function value = basisNote()
value = "iou_basis and target_extent_basis are different facts. iou_basis " + ...
    "says whether the IoU was computed on native or aligned intervals; " + ...
    "target_extent_basis says which of the five derivations gave an agreement " + ...
    "group its interval at all, and is empty for a detection or consensus " + ...
    "event. Correspondence scores are summarized within a basis pair and never " + ...
    "pooled across them.";
end

function value = qcNote()
value = "QC reports facts and judges nothing. There is no quality score for a " + ...
    "run, no threshold that calls one acceptable, and no aggregate that reads " + ...
    "as a verdict. What QC cannot tell you: whether any claimed caller called, " + ...
    "whether the exporting system's numbers are calibrated, whether a window " + ...
    "that corresponded to nothing refers to a real call VAWLUME missed, or " + ...
    "which extent basis is right for your question. Counts of missing evidence " + ...
    "describe this run's inputs, not its quality.";
end

% --------------------------------------------------------------- helpers ---

function value = sentinelNumber(raw)
value = double(raw);
if value >= 1e307
    value = NaN;
end
end

function value = negativeSentinel(raw)
value = double(raw);
if value < 0
    value = NaN;
end
end

function value = presentText(raw)
value = string(raw);
value(ismissing(value)) = "";
end
