function result = emptyIntermediateRepresentation(profile)
%EMPTYINTERMEDIATERESULT Construct the transparent source-mapping IR shape.

result = struct();
result.ir_schema_version = "0.1-draft";
result.profile = profile;
result.sources = emptySourcesTable();
result.records = emptyRecordsTable();
result.values = emptyValuesTable();
result.relationships = emptyRelationshipsTable();
result.issues = emptyIssuesTable();
result.summary = struct();
result.valid_for_ingest = false;
end

function value = emptySourcesTable()
value = table( ...
    strings(0, 1), strings(0, 1), strings(0, 1), strings(0, 1), ...
    strings(0, 1), strings(0, 1), strings(0, 1), strings(0, 1), ...
    NaN(0, 1), strings(0, 1), ...
    VariableNames=["source_key", "runtime_path", "relative_path", "filename", ...
    "source_type", "discovery_rule", "artifact_type", "status", ...
    "source_row_count", "checksum_sha256"]);
end

function value = emptyRecordsTable()
value = table( ...
    strings(0, 1), strings(0, 1), strings(0, 1), strings(0, 1), ...
    strings(0, 1), strings(0, 1), NaN(0, 1), strings(0, 1), ...
    strings(0, 1), strings(0, 1), ...
    VariableNames=["record_key", "source_key", "native_level", "canonical_level", ...
    "native_identifier", "record_scope", "source_row", "role_label", ...
    "mapping_rule", "status"]);
end

function value = emptyValuesTable()
value = table( ...
    strings(0, 1), strings(0, 1), strings(0, 1), strings(0, 1), ...
    strings(0, 1), strings(0, 1), strings(0, 1), strings(0, 1), ...
    NaN(0, 1), NaN(0, 1), strings(0, 1), NaN(0, 1), strings(0, 1), ...
    strings(0, 1), NaN(0, 1), NaN(0, 1), strings(0, 1), NaN(0, 1), ...
    strings(0, 1), strings(0, 1), strings(0, 1), strings(0, 1), ...
    strings(0, 1), ...
    NaN(0, 1), strings(0, 1), strings(0, 1), strings(0, 1), ...
    strings(0, 1), strings(0, 1), strings(0, 1), strings(0, 1), ...
    strings(0, 1), NaN(0, 1), strings(0, 1), ...
    VariableNames=["value_key", "evidence_group_key", "record_key", "source_key", ...
    "native_field", "actual_source_field", "raw_value", "native_value_type", ...
    "native_value_real", "native_value_integer", "native_value_text", ...
    "native_value_boolean", "native_unit", "canonical_field", ...
    "normalized_value_real", "normalized_value_integer", "normalized_value_text", ...
    "normalized_value_boolean", "normalized_value_type", "canonical_unit", ...
    "transform_key", "mapping_rule", "profile_location", "source_row", ...
    "derivation_stage", "operational_variant", "operational_definition", ...
    "equivalence_class", "cross_extractor_relationship", "consilience_role", ...
    "semantic_role", "consolidation_status", "evidence_count", "status"]);
end

function value = emptyRelationshipsTable()
value = table( ...
    strings(0, 1), strings(0, 1), strings(0, 1), strings(0, 1), ...
    strings(0, 1), strings(0, 1), strings(0, 1), strings(0, 1), ...
    strings(0, 1), ...
    VariableNames=["relationship_key", "source_key", "from_record_key", ...
    "to_record_key", "native_relationship", "canonical_relationship", ...
    "role_label", "mapping_rule", "status"]);
end

function value = emptyIssuesTable()
value = table( ...
    strings(0, 1), strings(0, 1), strings(0, 1), strings(0, 1), ...
    strings(0, 1), strings(0, 1), strings(0, 1), strings(0, 1), ...
    false(0, 1), ...
    VariableNames=["issue_key", "severity", "code", "source_key", ...
    "record_key", "location", "field_or_rule", "message", ...
    "affects_validity"]);
end
