function result = emptyIntermediateRepresentation(profile)
%EMPTYINTERMEDIATERESULT Construct the transparent source-mapping IR shape.

result = struct();
result.ir_schema_version = "0.2-draft";
result.profile = profile;
result.sources = emptySourcesTable();
result.records = emptyRecordsTable();
result.values = emptyValuesTable();
result.relationships = emptyRelationshipsTable();
result.streams = emptyStreamsTable();
result.events = emptyEventsTable();
result.event_attributes = emptyEventAttributesTable();
result.coverage = emptyCoverageTable();
result.anchors = emptyAnchorsTable();
result.anchor_observations = emptyAnchorObservationsTable();
result.anchor_fit_pairs = emptyAnchorFitPairsTable();
result.tracking_streams = emptyTrackingStreamsTable();
result.tracking_series = emptyTrackingSeriesTable();
result.tracking_columns = emptyTrackingColumnsTable();
result.attribution_windows = emptyAttributionWindowsTable();
result.attribution_claims = emptyAttributionClaimsTable();
result.attribution_localization_estimates = emptyLocalizationEstimatesTable();
result.attribution_channel_evidence = emptyChannelEvidenceTable();
result.attribution_track_references = emptyTrackReferencesTable();
result.attribution_native_attributes = emptyNativeAttributesTable();
result.attribution_declared_inputs = emptyDeclaredInputsTable();
result.issues = emptyIssuesTable();
result.summary = struct();
result.valid_for_ingest = false;
end

function value = emptyStreamsTable()
names = ["stream_key", "source_key", "timebase_key", "stream_kind", ...
    "modality", "native_time_unit", "normalized_time_unit", "status"];
value = typedEmptyTable(names, repmat("string", 1, numel(names)));
end

function value = emptyEventsTable()
names = ["event_key", "source_key", "stream_key", "timebase_key", ...
    "source_row", "source_locator", "native_event_id", "native_event_label", ...
    "normalized_event_key", "start_time_native", "end_time_native", ...
    "start_time_s", "end_time_s", "native_time_unit", "time_transform", ...
    "start_source_field", "end_source_field", "start_column_resolution", ...
    "end_column_resolution", "entity_key", "scalar_raw_value", ...
    "scalar_value_real", "scalar_value_integer", "scalar_value_text", ...
    "scalar_value_boolean", "scalar_value_type", "scalar_native_unit", ...
    "scalar_unit", ...
    "mapping_rule", "status"];
types = repmat("string", 1, numel(names));
types(ismember(names, ["source_row", "start_time_native", "end_time_native", ...
    "start_time_s", "end_time_s", "scalar_value_real", "scalar_value_integer", ...
    "scalar_value_boolean"])) = "double";
value = typedEmptyTable(names, types);
end

function value = emptyEventAttributesTable()
names = ["attribute_key", "event_key", "source_key", "source_row", ...
    "source_locator", "native_field", "actual_source_field", "attribute_name", ...
    "raw_value", "value_type", "value_real", "value_integer", "value_text", ...
    "value_boolean", "native_unit", "normalized_unit", "transform_key", ...
    "mapping_rule", "status"];
types = repmat("string", 1, numel(names));
types(ismember(names, ["source_row", "value_real", "value_integer", ...
    "value_boolean"])) = "double";
value = typedEmptyTable(names, types);
end

function value = emptyCoverageTable()
names = ["coverage_key", "source_key", "stream_key", "timebase_key", ...
    "segment_index", "start_time_native", "end_time_native", "start_time_s", ...
    "end_time_s", "native_time_unit", "time_transform", "source_locator", ...
    "mapping_rule", "observation_status", "status"];
types = repmat("string", 1, numel(names));
types(ismember(names, ["segment_index", "start_time_native", "end_time_native", ...
    "start_time_s", "end_time_s"])) = "double";
value = typedEmptyTable(names, types);
end

function value = emptyAnchorsTable()
names = ["anchor_key", "source_key", "source_row", "source_locator", ...
    "anchor_type", "expected_order", "mapping_rule", "status"];
types = repmat("string", 1, numel(names));
types(ismember(names, ["source_row", "expected_order"])) = "double";
value = typedEmptyTable(names, types);
end

function value = emptyAnchorObservationsTable()
names = ["observation_key", "anchor_key", "source_key", "source_row", ...
    "source_locator", "stream_key", "timebase_key", "observed_time_native", ...
    "observed_time_s", "native_time_unit", "time_transform", ...
    "timestamp_source_field", "timestamp_column_resolution", "observation_role", ...
    "included_in_fit", "uncertainty_s", "evidence_class", ...
    "event_source_key", "event_stream_key", ...
    "event_native_event_id", "mapping_rule", "status"];
types = repmat("string", 1, numel(names));
types(ismember(names, ["source_row", "observed_time_native", "observed_time_s", ...
    "included_in_fit", "uncertainty_s"])) = "double";
value = typedEmptyTable(names, types);
end

function value = emptyAnchorFitPairsTable()
names = ["source_timebase_key", "reference_timebase_key", ...
    "fit_eligible_anchor_count", "status"];
value = typedEmptyTable(names, ["string", "string", "double", "string"]);
end

% Tracking is deliberately metadata-only in the IR. These three tables describe
% the stream, the traces it contains, and the column contract that resolves its
% artifact - never a tracking sample. A stream with a million rows produces one
% tracking_streams row, a handful of tracking_series rows, and one
% tracking_columns row per mapped role.

function value = emptyTrackingStreamsTable()
names = ["stream_key", "source_key", "timebase_key", "coordinate_system_key", ...
    "native_time_basis", "nominal_frame_rate_hz", "has_confidence", ...
    "declared_sample_count", "native_time_unit", "time_transform", "status"];
types = repmat("string", 1, numel(names));
types(ismember(names, ["nominal_frame_rate_hz", "has_confidence", ...
    "declared_sample_count"])) = "double";
value = typedEmptyTable(names, types);
end

function value = emptyTrackingSeriesTable()
% native_track_id is the upstream trajectory label, never a canonical entity.
% No entity key appears here: track-to-entity association is time-varying
% evidence with its own semantics and provenance, not a property of a trace.
names = ["series_key", "stream_key", "source_key", "native_track_id", ...
    "native_bodypart_label", "canonical_bodypart_role", "sample_count", "status"];
types = repmat("string", 1, numel(names));
types(ismember(names, "sample_count")) = "double";
value = typedEmptyTable(names, types);
end

function value = emptyTrackingColumnsTable()
names = ["column_key", "stream_key", "source_key", "role", "source_field", ...
    "actual_source_field", "column_resolution", "native_unit", "is_required", ...
    "status"];
types = repmat("string", 1, numel(names));
types(ismember(names, "is_required")) = "double";
value = typedEmptyTable(names, types);
end


% Imported attribution is deliberately two tables: the window an exporting system
% claimed a vocalization occupied, and the caller claims made about it. They are
% separate because one window may carry several claims, and because a window is a
% statement about time while a claim is a statement about an animal.
%
% No VAWLUME event key appears here. Relating an imported window to a detection or
% consensus event is correspondence work with its own eligibility rule, and doing
% it during mapping would make every import quietly assert a match.

function value = emptyAttributionWindowsTable()
names = ["window_key", "source_key", "source_row", "source_locator", ...
    "native_window_id", "timebase_key", "start_time_native", "end_time_native", ...
    "native_time_unit", "mapping_rule", "status"];
types = repmat("string", 1, numel(names));
types(ismember(names, ["source_row", "start_time_native", "end_time_native"])) = "double";
value = typedEmptyTable(names, types);
end

% caller_label is the exporting system's own string and is preserved verbatim.
% entity_native_id is what the profile DECLARED it denotes -- never inferred, and
% resolved against the database only at intake, where an unknown one is refused.
function value = emptyAttributionClaimsTable()
names = ["claim_key", "window_key", "source_key", "source_row", ...
    "source_locator", "caller_label", "entity_native_id", ...
    "score", "score_semantics", "probability", "probability_semantics", ...
    "exporting_system", "exporting_system_version", "mapping_rule", "status"];
types = repmat("string", 1, numel(names));
types(ismember(names, ["source_row", "score", "probability"])) = "double";
value = typedEmptyTable(names, types);
end

% Backend attribution adds window-grain material the imported path has no use
% for. Every table here is keyed to a window or a claim in the two tables above,
% never to a VAWLUME event: relating a backend window to an event is
% correspondence, which happens after intake.
%
% NOTHING HERE IS RESOLVED AGAINST A DATABASE. coordinate_system_key,
% channel_index, tracking_stream_key/native_track_id and the claim's
% entity_native_id are declared keys; intake resolves each to an id or refuses.

% One localization estimate. coordinate_system_key is required by the mapper
% before a row is accepted: a coordinate without a frame is not a coordinate.
% position_z and confidence are NaN when absent, never 0. ordinal_source says
% whether estimate_ordinal came from the source ("declared") or from the order
% the estimates first appeared in the file ("source_order").
function value = emptyLocalizationEstimatesTable()
names = ["estimate_key", "window_key", "claim_key", "source_key", "source_row", ...
    "source_locator", "estimate_ordinal", "ordinal_source", "native_estimate_id", ...
    "coordinate_system_key", "position_x", "position_y", "position_z", ...
    "position_semantics", "confidence", "confidence_semantics", "mapping_rule", ...
    "status"];
types = repmat("string", 1, numel(names));
types(ismember(names, ["source_row", "estimate_ordinal", "position_x", ...
    "position_y", "position_z", "confidence"])) = "double";
value = typedEmptyTable(names, types);
end

% Per-channel evidence a backend reported for a window. channel_index is the
% backend's assertion and is resolved to a recording channel at intake.
function value = emptyChannelEvidenceTable()
names = ["channel_evidence_key", "window_key", "source_key", "source_row", ...
    "source_locator", "channel_index", "evidence_kind", "native_field_name", ...
    "value_real", "native_raw_token", "value_units", "value_semantics", ...
    "mapping_rule", "status"];
types = repmat("string", 1, numel(names));
types(ismember(names, ["source_row", "channel_index", "value_real"])) = "double";
value = typedEmptyTable(names, types);
end

% A backend's video-derived association for a claimed caller: a REFERENCE to an
% identity association that must already exist, never a new one.
function value = emptyTrackReferencesTable()
names = ["track_reference_key", "claim_key", "source_key", "source_row", ...
    "source_locator", "tracking_stream_key", "native_track_id", "mapping_rule", ...
    "status"];
types = repmat("string", 1, numel(names));
types(ismember(names, "source_row")) = "double";
value = typedEmptyTable(names, types);
end

% A producer-native field, owned by exactly one window, claim or estimate. No
% json value type. value_boolean is 0/1, or NaN when another type holds the value.
function value = emptyNativeAttributesTable()
names = ["attribute_key", "owner_kind", "owner_key", "source_key", "source_row", ...
    "source_locator", "attribute_name", "native_field_name", "value_type", ...
    "value_text", "value_real", "value_integer", "value_boolean", ...
    "native_raw_token", "unit", "mapping_rule_key", "status"];
types = repmat("string", 1, numel(names));
types(ismember(names, ["source_row", "value_real", "value_integer", ...
    "value_boolean"])) = "double";
value = typedEmptyTable(names, types);
end

% What the profile declared the producer consumed. Absence of a row means
% undeclared, never not_used.
function value = emptyDeclaredInputsTable()
names = ["input_dimension", "declaration", "mapping_rule"];
value = typedEmptyTable(names, repmat("string", 1, numel(names)));
end
function value = typedEmptyTable(names, types)
value = table(Size=[0, numel(names)], VariableTypes=cellstr(types), ...
    VariableNames=cellstr(names));
end

function value = emptySourcesTable()
value = table( ...
    strings(0, 1), strings(0, 1), strings(0, 1), strings(0, 1), ...
    strings(0, 1), strings(0, 1), strings(0, 1), strings(0, 1), ...
    NaN(0, 1), strings(0, 1), ...
    VariableNames=["source_key", "runtime_path", "relative_path", "filename", ...
    "source_type", "discovery_rule", "artifact_type", "status", ...
    "source_row_count", "checksum_sha256"]);
end

function value = emptyRecordsTable()
value = table( ...
    strings(0, 1), strings(0, 1), strings(0, 1), strings(0, 1), ...
    strings(0, 1), strings(0, 1), NaN(0, 1), strings(0, 1), ...
    strings(0, 1), strings(0, 1), ...
    VariableNames=["record_key", "source_key", "native_level", "canonical_level", ...
    "native_identifier", "record_scope", "source_row", "role_label", ...
    "mapping_rule", "status"]);
end

function value = emptyValuesTable()
value = table( ...
    strings(0, 1), strings(0, 1), strings(0, 1), strings(0, 1), ...
    strings(0, 1), strings(0, 1), strings(0, 1), strings(0, 1), ...
    NaN(0, 1), NaN(0, 1), strings(0, 1), NaN(0, 1), strings(0, 1), ...
    strings(0, 1), NaN(0, 1), NaN(0, 1), strings(0, 1), NaN(0, 1), ...
    strings(0, 1), strings(0, 1), strings(0, 1), strings(0, 1), ...
    strings(0, 1), ...
    NaN(0, 1), strings(0, 1), strings(0, 1), strings(0, 1), ...
    strings(0, 1), strings(0, 1), strings(0, 1), strings(0, 1), ...
    strings(0, 1), NaN(0, 1), strings(0, 1), ...
    VariableNames=["value_key", "evidence_group_key", "record_key", "source_key", ...
    "native_field", "actual_source_field", "raw_value", "native_value_type", ...
    "native_value_real", "native_value_integer", "native_value_text", ...
    "native_value_boolean", "native_unit", "canonical_field", ...
    "normalized_value_real", "normalized_value_integer", "normalized_value_text", ...
    "normalized_value_boolean", "normalized_value_type", "canonical_unit", ...
    "transform_key", "mapping_rule", "profile_location", "source_row", ...
    "derivation_stage", "operational_variant", "operational_definition", ...
    "equivalence_class", "cross_extractor_relationship", "consilience_role", ...
    "semantic_role", "consolidation_status", "evidence_count", "status"]);
end

function value = emptyRelationshipsTable()
value = table( ...
    strings(0, 1), strings(0, 1), strings(0, 1), strings(0, 1), ...
    strings(0, 1), strings(0, 1), strings(0, 1), strings(0, 1), ...
    strings(0, 1), ...
    VariableNames=["relationship_key", "source_key", "from_record_key", ...
    "to_record_key", "native_relationship", "canonical_relationship", ...
    "role_label", "mapping_rule", "status"]);
end

function value = emptyIssuesTable()
value = table( ...
    strings(0, 1), strings(0, 1), strings(0, 1), strings(0, 1), ...
    strings(0, 1), strings(0, 1), strings(0, 1), strings(0, 1), ...
    false(0, 1), ...
    VariableNames=["issue_key", "severity", "code", "source_key", ...
    "record_key", "location", "field_or_rule", "message", ...
    "affects_validity"]);
end
