function issue = makeIssue(severity, code, profileLocation, message)
%MAKEISSUE Construct a source_mapping issue record.
issue = struct( ...
    severity=string(severity), ...
    code=string(code), ...
    profile_location=string(profileLocation), ...
    message=string(message));
end
