function tests = test_eda_example_rendering
%TEST_EDA_EXAMPLE_RENDERING Pure display planning, styles, names and CSV.
tests = functiontests({ ...
    @setupOnce, ...
    @teardownOnce, ...
    @testStyleAssignmentIsStableAndPrintConscious, ...
    @testStyleCapacityFailsRatherThanReusingAStyle, ...
    @testFilenamesAreStableSortableAndSafe, ...
    @testDisplayPlanIsPureAndCarriesAllGeometry, ...
    @testMixedExtentsRenderAsDifferentGraphics, ...
    @testNoBandIsDrawnWhenTheSpecificationHasNone, ...
    @testIdentifyingAndCautionTextTravelWithTheFigure, ...
    @testIndexRoundTripsHostileTextInTheFixedOrder, ...
    @testIndexRejectsReviewColumns});
end

function setupOnce(testCase)
repoRoot = fileparts(fileparts(fileparts(mfilename("fullpath"))));
sourcePath = fullfile(repoRoot, "src");
testCase.TestData.repo_root = repoRoot;
testCase.TestData.source_path = sourcePath;
testCase.TestData.added_path = ~contains(path, sourcePath);
if testCase.TestData.added_path
    addpath(sourcePath);
end
end

function teardownOnce(testCase)
if testCase.TestData.added_path && contains(path, testCase.TestData.source_path)
    rmpath(testCase.TestData.source_path);
end
end

function testDisplayPlanIsPureAndCarriesAllGeometry(testCase)
prepared = syntheticPrepared();
before = findall(groot, Type="figure");
plan = vawlume.eda.exampleDisplayPlan(prepared);
after = findall(groot, Type="figure");

verifyEqual(testCase, after, before);
verifyEqual(testCase, height(plan.annotations), height(prepared.annotations));
verifyTrue(testCase, all(isfinite(plan.annotations.rectangle_width(1:2))));
verifyTrue(testCase, isnan(plan.annotations.rectangle_width(3)));
verifyEqual(testCase, numel(plan.annotations.marker_frequencies_hz{3}), 2);
verifyEqual(testCase, plan.spectrogram_time_s, ...
    prepared.window.actual_start_s + prepared.spectrogram.time_s);
verifyTrue(testCase, contains(plan.geometry_rule, ...
    "has_measured_band is true"));
end

function testStyleAssignmentIsStableAndPrintConscious(testCase)
first = vawlume.eda.exampleStyles(["deepsqueak", "mupet", "usvseg"]);
second = vawlume.eda.exampleStyles(["usvseg", "deepsqueak", "mupet"]);
verifyEqual(testCase, first, second);

single = vawlume.eda.exampleStyles("usvseg");
expected = first(first.extractor_key == "usvseg", :);
verifyEqual(testCase, single(:, expected.Properties.VariableNames), expected);
verifyEqual(testCase, numel(unique(first.line_style)), 3, ...
    "The three pilot extractors are not dash-distinct in greyscale.");
verifyEqual(testCase, height(unique(first(:, ["color_index", ...
    "line_style_index"]))), 3);
end

function testStyleCapacityFailsRatherThanReusingAStyle(testCase)
keys = "extractor_" + string(1:9);
verifyError(testCase, @() vawlume.eda.exampleStyles(keys), ...
    "vawlume:eda:ExtractorStyleCapacityExceeded");
end

function testFilenamesAreStableSortableAndSafe(testCase)
first = vawlume.eda.exampleFilename("CON:/a call? * ", 7);
second = vawlume.eda.exampleFilename("CON:/a call? * ", 7);
neighbour = vawlume.eda.exampleFilename("CON:/a call? quoted", 8);
verifyEqual(testCase, first, second);
verifyNotEqual(testCase, first, neighbour);
verifyTrue(testCase, startsWith(first, "0007_"));
verifyTrue(testCase, endsWith(first, ".png"));
verifyEmpty(testCase, regexp(first, '[<>:"/\\|?*]', 'once'));
end

function testMixedExtentsRenderAsDifferentGraphics(testCase)
prepared = syntheticPrepared();
rendered = vawlume.eda.renderExample(prepared, Visible=false);
cleanup = onCleanup(@() closeIfOpen(rendered.figure));

groups = findall(rendered.axes, Tag="vawlume-example-annotation");
bands = findall(rendered.axes, Tag="vawlume-measured-band");
boundaries = findall(rendered.axes, Tag="vawlume-time-boundary");
markers = findall(rendered.axes, Tag="vawlume-frequency-marker");
verifyEqual(testCase, numel(groups), 3);
verifyEqual(testCase, numel(bands), 2);
verifyEqual(testCase, numel(boundaries), 2);
verifyEqual(testCase, numel(markers), 2);

legendText = string(rendered.legend.String);
verifyTrue(testCase, any(contains(legendText, ...
    "deepsqueak — measured band edges")));
verifyTrue(testCase, any(contains(legendText, ...
    "usvseg — no measured band")));
end

function testNoBandIsDrawnWhenTheSpecificationHasNone(testCase)
% Verified as an absence at the graphics boundary: the centre-only member owns
% no rectangle child even though it has two finite frequency measurements.
prepared = syntheticPrepared();
rendered = vawlume.eda.renderExample(prepared, Visible=false);
cleanup = onCleanup(@() closeIfOpen(rendered.figure));

groups = findall(rendered.axes, Tag="vawlume-example-annotation");
target = gobjects(0);
for group = groups'
    if string(group.UserData.extractor_key) == "usvseg"
        target = group;
    end
end
verifyEqual(testCase, numel(target), 1);
verifyEmpty(testCase, findall(target, Type="rectangle"), ...
    "A rectangle was synthesized for a no-band annotation.");
verifyEqual(testCase, numel(findall(target, ...
    Tag="vawlume-frequency-marker")), 2);
end

function testIdentifyingAndCautionTextTravelWithTheFigure(testCase)
prepared = syntheticPrepared();
rendered = vawlume.eda.renderExample(prepared, ...
    ReferenceConfigurationId="ref-test", Visible=false);
cleanup = onCleanup(@() closeIfOpen(rendered.figure));

identity = strjoin(string(rendered.identity_textbox.String), string(newline));
note = strjoin(string(rendered.caution_textbox.String), string(newline));
for token = ["example-one", "recording 17", ...
        "deepsqueak|mupet|usvseg", "deep--mupet|deep--usv", ...
        "deep-1", "mupet-1", "usv-1", "ref-test", ...
        "Window requested", "clamped start=false"]
    verifyTrue(testCase, contains(identity, token), ...
        "The identifying text omits " + token + ".");
end
verifyTrue(testCase, contains(note, "APPROXIMATE EXTENT"));
verifyTrue(testCase, contains(note, ...
    "methodological evidence, not ground truth"));
verifyTrue(testCase, contains(note, "not symmetric"));

% Geometry arithmetic belongs in the pure display plan, not in the renderer.
source = fileread(fullfile(repoRootPath(), "src", "+vawlume", "+eda", ...
    "renderExample.m"));
verifyFalse(testCase, contains(source, "end_time_s -"));
verifyFalse(testCase, contains(source, "frequency_max_hz -"));
end

function testIndexRoundTripsHostileTextInTheFixedOrder(testCase)
path = string(tempname) + ".csv";
cleanup = onCleanup(@() deleteIfPresent(path));
index = nominalIndex();
index.render_failure_reason = "failed, because ""quoted"" text survived";

result = vawlume.eda.writeExampleIndex(index, path);
verifyTrue(testCase, result.round_trip_verified);
verifyEqual(testCase, result.row_count, 1);
verifyEqual(testCase, result.columns, expectedColumns());
verifyFalse(testCase, any(contains(lower(result.columns), "review")));
text = string(fileread(path));
verifyTrue(testCase, contains(text, ...
    """failed, because """"quoted"""" text survived"""));
end

function testIndexRejectsReviewColumns(testCase)
path = string(tempname) + ".csv";
index = nominalIndex();
index.review_notes = "";
verifyError(testCase, @() vawlume.eda.writeExampleIndex(index, path), ...
    "vawlume:eda:ExampleIndexColumnsInvalid");
verifyFalse(testCase, isfile(path));
end

function prepared = syntheticPrepared()
annotations = table( ...
    [101; 102; 103], [1; 1; 1], ...
    ["deepsqueak"; "mupet"; "usvseg"], ...
    ["DeepSqueak"; "MUPET"; "USVSEG"], ...
    ["deep-1"; "mupet-1"; "usv-1"], ...
    [10.020; 10.024; 10.018], [10.060; 10.064; 10.058], ...
    [0.040; 0.040; 0.040], ...
    ["band_edges"; "band_edges"; "center_and_peak"], ...
    [true; true; false], [45000; 44000; NaN], [80000; 79000; NaN], ...
    [62000; 61000; 62100], [NaN; NaN; 71200], ...
    ["rectangle"; "rectangle"; "time extent with two markers"], ...
    [false; false; false], [0; 0; 0], ["Hz"; "Hz"; "Hz"], ...
    VariableNames=["detection_id", "agreement_group_id", "extractor_key", ...
    "extractor_name", "native_event_id", "start_time_s", "end_time_s", ...
    "duration_s", "frequency_extent_source", "has_measured_band", ...
    "frequency_min_hz", "frequency_max_hz", "frequency_center_hz", ...
    "frequency_peak_hz", "rendering", "is_clipped_by_window", ...
    "outside_window_s", "frequency_unit"]);

settings = struct(method_key="vawlume.eda.spectrogram", ...
    method_version="1.0.0", window_type="periodic_hann", ...
    window_length_samples=64, hop_samples=32, overlap_samples=32, ...
    fft_length=64, sample_rate_hz=192000, scaling="power_db", ...
    floor_db=-120, frequency_limits_hz=[30000 90000], ...
    padding_pre_s=0.05, padding_post_s=0.05, channel_index=1);
prepared = struct(example_id="example-one", ...
    recording=struct(recording_id=17, native_recording_id="native-rec"), ...
    extractor_set_key="deepsqueak|mupet|usvseg", ...
    window=struct(requested_start_s=10, requested_end_s=10.1, ...
        actual_start_s=10, actual_end_s=10.1, ...
        is_clamped_at_start=false, is_clamped_at_end=false), ...
    frequency_bounds=struct(low_hz=30000, high_hz=90000), ...
    annotations=annotations, ...
    spectrogram=struct(status="computed", time_s=[0.01 0.04 0.07 0.09], ...
        frequency_hz=[30000; 60000; 90000], ...
        matrix=[-90 -80 -70 -85; -60 -30 -25 -55; -100 -90 -80 -95], ...
        settings=settings), ...
    supported_extractor_pair_pattern="deep--mupet|deep--usv", ...
    reference_configuration=struct(profile_key="profile", ...
        version_label="1.0"), ...
    approximate_extent_note="APPROXIMATE EXTENT derived from extractor " + ...
        "output, not the extractor's native segmentation contour.", ...
    caution=["Agreement among extractors is methodological evidence, not " + ...
        "ground truth."; "The evidential relationship is not symmetric."; ...
        "Agreement identifies calls amenable to participating strategies."; ...
        "No configuration is optimal, validated, or calibrated."]);
end

function value = nominalIndex()
value = table("1.0", "example", "exploration", "ref-id", "1.0", ...
    "project", 17, "native", "a--b", "1|2", "a|b", ...
    "native,one|native""two", "band_edges|center_only", 1.0, 1.1, ...
    0.95, 1.15, 1, "{""method_key"":""fft"",""x"":1}", ...
    "images/0001.png", "failed", "placeholder", ...
    VariableNames=expectedColumns());
end

function value = expectedColumns()
value = ["index_version", "example_id", "exploration_run_key", ...
    "reference_configuration_id", "reference_profile_version", ...
    "project_key", "recording_id", "native_recording_id", ...
    "supported_extractor_pair_pattern", "member_detection_ids", ...
    "member_extractor_keys", "member_native_event_ids", ...
    "frequency_extent_sources", "group_start_time_s", "group_end_time_s", ...
    "snippet_window_start_s", "snippet_window_end_s", ...
    "snippet_channel_index", "spectrogram_settings_json", "image_path", ...
    "render_status", "render_failure_reason"];
end

function closeIfOpen(handle)
if isgraphics(handle)
    close(handle);
end
end

function deleteIfPresent(path)
if isfile(path)
    delete(path);
end
end

function root = repoRootPath()
root = string(fileparts(fileparts(fileparts(mfilename("fullpath")))));
end
