function tests = test_regularized_timeline
%TEST_REGULARIZED_TIMELINE Half-open binning and coverage semantics.
tests = functiontests(localfunctions);
end

function setupOnce(testCase)
repoRoot = string(fileparts(fileparts(fileparts(mfilename("fullpath")))));
testCase.TestData.sourcePath = fullfile(repoRoot, "src");
addpath(testCase.TestData.sourcePath);
end

function teardownOnce(testCase)
rmpath(testCase.TestData.sourcePath);
end

function testCountsEdgesOverlapAndUnavailableRemainDistinct(testCase)
[view, channels] = fixture();
result = vawlume.sequence.regularizeTimeline(view, channels, ...
    WindowStart=0, WindowEnd=4, BinWidth=1, BinOrigin=0);
t = result.timeline;

% The onset exactly at 1 belongs to [1,2), not [0,1).
verifyEqual(testCase, t.call_count, [1; 2; 0; 0]);
verifyEqual(testCase, t.call_count_covered, true(4, 1));

% The behavior interval [0.5,1.5] overlaps two bins. Its coverage has a gap,
% so [2,3) is unavailable (NaN), while [3,4) is covered-empty (0).
verifyEqual(testCase, t.behavior_present([1 2 4]), [1; 1; 0]);
verifyTrue(testCase, isnan(t.behavior_present(3)));
verifyEqual(testCase, t.behavior_present_covered, [true; true; false; true]);
verifyEqual(testCase, result.specification.edge_convention, ...
    "half-open [start,end); WindowEnd excluded");
verifyEqual(testCase, result.specification.persistence, ...
    "derived MATLAB table; no SQLite rows");
end

function testDifferentBinWidthsAreDeterministic(testCase)
[view, channels] = fixture();
one = vawlume.sequence.regularizeTimeline(view, channels(1), ...
    WindowStart=0, WindowEnd=4, BinWidth=1);
two = vawlume.sequence.regularizeTimeline(view, channels(1), ...
    WindowStart=0, WindowEnd=4, BinWidth=2);
again = vawlume.sequence.regularizeTimeline(view, channels(1), ...
    WindowStart=0, WindowEnd=4, BinWidth=2);
verifyEqual(testCase, one.timeline.call_count, [1; 2; 0; 0]);
verifyEqual(testCase, two.timeline.call_count, [3; 0]);
verifyEqual(testCase, two, again);
end

function testFinalEndpointExcludedAndInvalidGridRejected(testCase)
[view, channels] = fixture();
view.events(end + 1, :) = {"detection", "vocalization", "recording:1", ...
    4, NaN};
result = vawlume.sequence.regularizeTimeline(view, channels(1), ...
    WindowStart=0, WindowEnd=4, BinWidth=1);
verifyEqual(testCase, result.timeline.call_count, [1; 2; 0; 0]);
verifyError(testCase, @() vawlume.sequence.regularizeTimeline( ...
    view, channels(1), WindowStart=0, WindowEnd=4.1, BinWidth=1), ...
    "vawlume:sequence:WindowNotDivisible");
end

function [view, channels] = fixture()
events = table( ...
    ["detection"; "detection"; "detection"; "external_event"], ...
    ["vocalization"; "vocalization"; "vocalization"; "female_entry"], ...
    ["recording:1"; "recording:1"; "recording:1"; "external_stream:2"], ...
    [0.2; 1.0; 1.8; 0.5], [0.3; 1.1; 1.9; 1.5], ...
    VariableNames=["event_source_kind", "normalized_event_key", ...
    "coverage_key", "aligned_start", "aligned_end"]);
coverage = table( ...
    ["recording:1"; "external_stream:2"; "external_stream:2"], ...
    repmat("observed", 3, 1), [0; 0; 3], [4; 2; 4], ...
    VariableNames=["coverage_key", "observation_status", ...
    "aligned_start", "aligned_end"]);
view = struct(events=events, coverage=coverage, ...
    specification=struct(reference_timebase_id=3, ...
    reference_timebase_key="neural"));
channels = [struct(name="call_count", event_source_kind="detection", ...
    normalized_event_key="vocalization", coverage_key="recording:1", ...
    aggregation="onset_count"), ...
    struct(name="behavior_present", event_source_kind="external_event", ...
    normalized_event_key="female_entry", coverage_key="external_stream:2", ...
    aggregation="any_overlap")];
end
