function tests = test_project_recording_ingest
tests = functiontests({ ...
    @testPlanUsesExplicitRecordingScopeAndMinimalLinks, ...
    @testRecordingGraphApplyIsIdempotent, ...
    @testExplicitNativeRecordingCollisionIsConflict, ...
    @testRecordingRoleCollisionIsConflict, ...
    @testRecordingLinkFailureRollsBackWholeGraph});
end

function testPlanUsesExplicitRecordingScopeAndMinimalLinks(testCase)
[conn, dbFile, repoRoot] = createDisposableDatabase();
cleanupDb = onCleanup(@() cleanupDatabase(conn, dbFile));

result = vawlume.ingest.project(conn, recordingIR(), projectSpec());

verifyEqual(testCase, height(result.plan.recordings), 1);
verifyEqual(testCase, result.plan.recordings.record_key, ...
    "source:audio/session_01/call.wav|record:recording");
verifyEqual(testCase, result.plan.recordings.native_recording_id, "");
verifyEqual(testCase, result.plan.sources.path_or_uri, ...
    "audio/session_01/call.wav");
verifyEqual(testCase, sort(result.plan.recording_links.link_type), ...
    ["context"; "participant"]);
participant = result.plan.recording_links( ...
    result.plan.recording_links.link_type == "participant", :);
context = result.plan.recording_links( ...
    result.plan.recording_links.link_type == "context", :);
verifyTrue(testCase, contains(participant.entity_key, ...
    "entity_type:animal|native_id:A01"));
verifyTrue(testCase, contains(context.entity_key, ...
    "entity_type:session|native_id:S01"));
verifyEqual(testCase, result.plan.ingestion_files.action, "create");
verifyEqual(testCase, result.plan.ingestion_files.parse_status, "parsed");
verifyTrue(testCase, isnan(result.plan.ingestion_files.ingestion_run_id));
verifyEqual(testCase, scalar(conn, "SELECT COUNT(*) AS n FROM projects"), 0);

clear cleanupDb
rmpath(fullfile(repoRoot, "src"));
end

function testRecordingGraphApplyIsIdempotent(testCase)
[conn, dbFile, repoRoot] = createDisposableDatabase();
cleanupDb = onCleanup(@() cleanupDatabase(conn, dbFile));
ir = recordingIR();

first = vawlume.ingest.project(conn, ir, projectSpec(), Apply=true);
countsAfterFirst = graphCounts(conn);
second = vawlume.ingest.project(conn, ir, projectSpec(), Apply=true);
countsAfterSecond = graphCounts(conn);

verifyEqual(testCase, first.status, "completed");
verifyTrue(testCase, first.committed);
verifyEqual(testCase, first.applied_counts.source_files, 1);
verifyEqual(testCase, first.applied_counts.recordings, 1);
verifyEqual(testCase, first.applied_counts.recording_entity_links, 2);
verifyTrue(testCase, all(~isnan(first.source_ids.source_file_id)));
verifyTrue(testCase, all(~isnan(first.recording_ids.recording_id)));
verifyEqual(testCase, second.status, "completed");
verifyNotEqual(testCase, second.ingestion_run_id, first.ingestion_run_id);
verifyEqual(testCase, second.applied_counts.reused_source_files, 1);
verifyEqual(testCase, second.applied_counts.reused_recordings, 1);
verifyEqual(testCase, ...
    second.applied_counts.reused_recording_entity_links, 2);
verifyEqual(testCase, countsAfterFirst, struct( ...
    projects=1, source_files=1, entity_types=3, entities=3, ...
    entity_relationships=2, recordings=1, recording_entity_links=2, ...
    ingestion_runs=1, ingestion_files=1, extraction_runs=0, detections=0));
verifyEqual(testCase, countsAfterSecond, struct( ...
    projects=1, source_files=1, entity_types=3, entities=3, ...
    entity_relationships=2, recordings=1, recording_entity_links=2, ...
    ingestion_runs=2, ingestion_files=2, extraction_runs=0, detections=0));
verifyEqual(testCase, height(fetch(conn, "PRAGMA foreign_key_check")), 0);

clear cleanupDb
rmpath(fullfile(repoRoot, "src"));
end

function testExplicitNativeRecordingCollisionIsConflict(testCase)
[conn, dbFile, repoRoot] = createDisposableDatabase();
cleanupDb = onCleanup(@() cleanupDatabase(conn, dbFile));
firstIr = recordingIR();
recordingRow = firstIr.records.record_scope == "source_recording";
firstIr.records.native_identifier(recordingRow) = "REC-A";
firstIr.records.mapping_rule(recordingRow) = "rule.native_recording_id";
vawlume.ingest.project(conn, firstIr, projectSpec(), Apply=true);

secondIr = firstIr;
secondIr.records.native_identifier(recordingRow) = "REC-B";
result = vawlume.ingest.project(conn, secondIr, projectSpec(), Apply=true);

verifyEqual(testCase, result.status, "conflict");
verifyFalse(testCase, result.committed);
verifyEqual(testCase, result.plan.recordings.action, "conflict");
verifyTrue(testCase, any(result.issues.code == "RECORDING_CONFLICT"));
verifyEqual(testCase, scalar(conn, "SELECT COUNT(*) AS n FROM recordings"), 1);

clear cleanupDb
rmpath(fullfile(repoRoot, "src"));
end

function testRecordingRoleCollisionIsConflict(testCase)
[conn, dbFile, repoRoot] = createDisposableDatabase();
cleanupDb = onCleanup(@() cleanupDatabase(conn, dbFile));
firstIr = recordingIR();
vawlume.ingest.project(conn, firstIr, projectSpec(), Apply=true);

secondIr = firstIr;
subjectRow = secondIr.records.canonical_level == "subject";
secondIr.records.role_label(subjectRow) = "speaker";
result = vawlume.ingest.project(conn, secondIr, projectSpec(), Apply=true);

verifyEqual(testCase, result.status, "conflict");
verifyFalse(testCase, result.committed);
verifyTrue(testCase, any(result.issues.code == "RECORDING_LINK_CONFLICT"));
verifyEqual(testCase, scalar(conn, ...
    "SELECT COUNT(*) AS n FROM recording_entity_links"), 2);

clear cleanupDb
rmpath(fullfile(repoRoot, "src"));
end

function testRecordingLinkFailureRollsBackWholeGraph(testCase)
[conn, dbFile, repoRoot] = createDisposableDatabase();
cleanupDb = onCleanup(@() cleanupDatabase(conn, dbFile));
execute(conn, "CREATE TRIGGER force_recording_link_failure " + ...
    "BEFORE INSERT ON recording_entity_links BEGIN " + ...
    "SELECT RAISE(ABORT, 'forced recording link failure'); END");

didThrow = false;
try
    vawlume.ingest.project(conn, recordingIR(), projectSpec(), Apply=true);
catch exception
    didThrow = true;
    verifyTrue(testCase, contains(string(exception.message), ...
        "forced recording link failure"));
end

verifyTrue(testCase, didThrow);
verifyEqual(testCase, string(conn.AutoCommit), "on");
verifyEqual(testCase, graphCounts(conn), zeroGraphCounts());
verifyEqual(testCase, height(fetch(conn, "PRAGMA foreign_key_check")), 0);

clear cleanupDb
rmpath(fullfile(repoRoot, "src"));
end

function ir = recordingIR(runtimePath)
arguments
    runtimePath (1,1) string = "C:/runtime/project/audio/session_01/call.wav"
end
sourceKey = "source:audio/session_01/call.wav";
checksum = string(repmat('a', 1, 64));
ir = struct();
ir.profile = struct( ...
    profile_key="example.project.recording.test", ...
    profile_name="Project recording test profile", ...
    profile_kind="project_input", ...
    profile_version="0.1.0", ...
    profile_schema_version="0.2-draft", ...
    profile_content_format="json", ...
    profile_path="config/project_recording_test.json", ...
    profile_runtime_path="C:/repo/config/project_recording_test.json", ...
    profile_checksum=checksum);
ir.sources = table( ...
    sourceKey, runtimePath, "audio/session_01/call.wav", ...
    "call.wav", "project_file", "rule.audio", "source_audio", ...
    "mapped", "", ...
    VariableNames=["source_key", "runtime_path", "relative_path", ...
    "filename", "source_type", "discovery_rule", "artifact_type", ...
    "status", "checksum_sha256"]);
ir.records = table( ...
    [sourceKey + "|record:study"; sourceKey + "|record:animal"; ...
    sourceKey + "|record:session"; sourceKey + "|record:recording"], ...
    repmat(sourceKey, 4, 1), ...
    ["study"; "animal"; "session"; "recording"], ...
    ["study"; "subject"; "session"; "recording"], ...
    ["study_01"; "A01"; "S01"; "audio/session_01/call.wav"], ...
    ["entity"; "entity"; "entity"; "source_recording"], ...
    strings(4, 1), ...
    ["rule.study"; "rule.animal"; "rule.session"; "source.relative_path"], ...
    repmat("mapped", 4, 1), ...
    VariableNames=["record_key", "source_key", "native_level", ...
    "canonical_level", "native_identifier", "record_scope", "role_label", ...
    "mapping_rule", "status"]);
ir.relationships = table( ...
    [sourceKey + "|relationship:study_animal"; ...
    sourceKey + "|relationship:animal_session"; ...
    sourceKey + "|relationship:session_recording"], ...
    repmat(sourceKey, 3, 1), ...
    [sourceKey + "|record:study"; sourceKey + "|record:animal"; ...
    sourceKey + "|record:session"], ...
    [sourceKey + "|record:animal"; sourceKey + "|record:session"; ...
    sourceKey + "|record:recording"], ...
    repmat("parent", 3, 1), repmat("contains", 3, 1), ...
    strings(3, 1), ["rule.rel.1"; "rule.rel.2"; "rule.rel.3"], ...
    repmat("mapped", 3, 1), ...
    VariableNames=["relationship_key", "source_key", "from_record_key", ...
    "to_record_key", "native_relationship", "canonical_relationship", ...
    "role_label", "mapping_rule", "status"]);
ir.valid_for_ingest = true;
end

function value = projectSpec()
value = struct(project_key="recording_test_project", ...
    project_name="Recording test project", description="Recording graph test.");
end

function [conn, dbFile, repoRoot] = createDisposableDatabase()
repoRoot = repoRootForTest();
addpath(fullfile(repoRoot, "src"));
dbFile = string(tempname) + ".sqlite";
conn = sqlite(char(dbFile), "create");
vawlume.db.applySchema(conn, fullfile(repoRoot, "schema", "schema.sql"));
end

function counts = graphCounts(conn)
counts = struct( ...
    projects=scalar(conn, "SELECT COUNT(*) AS n FROM projects"), ...
    source_files=scalar(conn, "SELECT COUNT(*) AS n FROM source_files"), ...
    entity_types=scalar(conn, "SELECT COUNT(*) AS n FROM entity_types"), ...
    entities=scalar(conn, "SELECT COUNT(*) AS n FROM experimental_entities"), ...
    entity_relationships=scalar(conn, ...
    "SELECT COUNT(*) AS n FROM entity_relationships"), ...
    recordings=scalar(conn, "SELECT COUNT(*) AS n FROM recordings"), ...
    recording_entity_links=scalar(conn, ...
    "SELECT COUNT(*) AS n FROM recording_entity_links"), ...
    ingestion_runs=scalar(conn, "SELECT COUNT(*) AS n FROM ingestion_runs"), ...
    ingestion_files=scalar(conn, "SELECT COUNT(*) AS n FROM ingestion_files"), ...
    extraction_runs=scalar(conn, "SELECT COUNT(*) AS n FROM extraction_runs"), ...
    detections=scalar(conn, "SELECT COUNT(*) AS n FROM detections"));
end

function counts = zeroGraphCounts()
counts = struct(projects=0, source_files=0, entity_types=0, entities=0, ...
    entity_relationships=0, recordings=0, recording_entity_links=0, ...
    ingestion_runs=0, ingestion_files=0, extraction_runs=0, detections=0);
end

function value = scalar(conn, sql)
rows = fetch(conn, sql);
value = double(rows.n(1));
end

function cleanupDatabase(conn, dbFile)
if isopen(conn)
    close(conn);
end
deleteIfExists(dbFile);
deleteIfExists(dbFile + "-journal");
deleteIfExists(dbFile + "-wal");
deleteIfExists(dbFile + "-shm");
end

function deleteIfExists(path)
if isfile(path)
    delete(path);
end
end

function repoRoot = repoRootForTest()
repoRoot = fileparts(fileparts(fileparts(mfilename("fullpath"))));
end
