function tests = test_project_profile_linkage
tests = functiontests({ ...
    @testPlanResolvesTrackedProjectDefaultsReadOnly, ...
    @testTrackedLinkageApplyTwiceReusesSemanticGraphAndAuditsAttempts, ...
    @testLinkedProfileChecksumConflictPreventsAuditWrite, ...
    @testSingularRecordingAssignmentConflictPreventsAuditWrite, ...
    @testMismatchedLinkageIsRejectedBeforeMutation});
end

function testPlanResolvesTrackedProjectDefaultsReadOnly(testCase)
[conn, dbFile, repoRoot] = createDisposableDatabase();
cleanupDb = onCleanup(@() cleanupDatabase(conn, dbFile));
[ir, sourceRoot] = parsedIR(repoRoot, ...
    "example.project.mouse_courtship.folder_driven", ...
    fullfile("control", "mouse_001", "baseline", ...
    "001_baseline_1.wav"));
cleanupRoot = onCleanup(@() removeTree(sourceRoot));

result = vawlume.ingest.project(conn, ir, projectSpec(), ...
    ProfileLinkagePath=linkagePath(repoRoot), RepoRoot=repoRoot);

verifyEqual(testCase, result.status, "planned");
verifyFalse(testCase, result.committed);
verifyTrue(testCase, result.plan.profile_linkage.enabled);
verifyEqual(testCase, result.plan.profile_linkage.content_uri, ...
    "config/04_examples/profile_linkage_example.json");
verifyEqual(testCase, result.plan.profile_linkage.checksum_sha256, ...
    "54a1757aaf8c8667a9adf5312b4924fc600a867aad256e7c937c2add6777ff50");
profiles = result.plan.profile_linkage.profiles;
verifyEqual(testCase, profiles.profile_key, [ ...
    "example.device.ultrasonic_usb_primary"; ...
    "example.setup.mouse_courtship_chamber"]);
verifyEqual(testCase, profiles.profile_kind, ...
    ["recording_device"; "experimental_setup"]);
verifyEqual(testCase, profiles.version_label, ["1"; "1"]);
verifyEqual(testCase, profiles.profile_schema_version, ...
    ["0.1-draft"; "0.1-draft"]);
verifyEqual(testCase, profiles.content_uri, [ ...
    "config/02_device_profiles/recording_device_profile_examples.json"; ...
    "config/03_setup_profiles/experimental_setup_profile_examples.json"]);
verifyEqual(testCase, profiles.checksum_sha256, [ ...
    "6bcb1ca9c07596619b56ee50fdce1ed6349100327a53622e7322c01d3c009ede"; ...
    "21b0b0a915078e437998232dda9683784744876632bedbb4b499bc3359adcd8e"]);
verifyEqual(testCase, ...
    sort(result.project_profile_assignments.assignment_role), ...
    sort(["source_mapping_profile"; "default_recording_device"; ...
    "default_experimental_setup"]));
mappingAssignment = result.project_profile_assignments( ...
    result.project_profile_assignments.assignment_role == ...
    "source_mapping_profile", :);
verifyFalse(testCase, mappingAssignment.is_default);
verifyEqual(testCase, ...
    sort(result.recording_profile_assignments.assignment_role), ...
    ["experimental_setup"; "recording_device"]);
verifyEqual(testCase, ...
    unique(result.recording_profile_assignments.inheritance_source), ...
    "project_default");
verifyEqual(testCase, result.created_counts.config_profiles, 3);
verifyEqual(testCase, result.created_counts.config_profile_versions, 3);
verifyEqual(testCase, result.created_counts.project_profile_assignments, 3);
verifyEqual(testCase, result.created_counts.recording_profile_assignments, 2);
verifyEqual(testCase, result.created_counts.ingestion_runs, 1);
verifyEqual(testCase, result.created_counts.ingestion_files, 1);
verifyEqual(testCase, scalar(conn, "SELECT COUNT(*) AS n FROM projects"), 0);
verifyEqual(testCase, scalar(conn, ...
    "SELECT COUNT(*) AS n FROM config_profiles"), 0);

clear cleanupRoot cleanupDb
rmpath(fullfile(repoRoot, "src"));
end

function testTrackedLinkageApplyTwiceReusesSemanticGraphAndAuditsAttempts(testCase)
[conn, dbFile, repoRoot] = createDisposableDatabase();
cleanupDb = onCleanup(@() cleanupDatabase(conn, dbFile));
[ir, sourceRoot] = parsedIR(repoRoot, ...
    "example.project.mouse_courtship.folder_driven", ...
    fullfile("control", "mouse_001", "baseline", ...
    "001_baseline_1.wav"));
cleanupRoot = onCleanup(@() removeTree(sourceRoot));
options = namedargs2cell(struct( ...
    Apply=true, ProfileLinkagePath=linkagePath(repoRoot), ...
    RepoRoot=repoRoot));

first = vawlume.ingest.project(conn, ir, projectSpec(), options{:});
countsAfterFirst = semanticCounts(conn);
second = vawlume.ingest.project(conn, ir, projectSpec(), options{:});
countsAfterSecond = semanticCounts(conn);

verifyEqual(testCase, first.status, "completed");
verifyEqual(testCase, second.status, "completed");
verifyTrue(testCase, first.committed);
verifyTrue(testCase, second.committed);
verifyNotEqual(testCase, first.ingestion_run_id, second.ingestion_run_id);
verifyEqual(testCase, first.applied_counts.config_profiles, 3);
verifyEqual(testCase, first.applied_counts.config_profile_versions, 3);
verifyEqual(testCase, first.applied_counts.project_profile_assignments, 3);
verifyEqual(testCase, first.applied_counts.recording_profile_assignments, 2);
verifyEqual(testCase, second.applied_counts.reused_config_profiles, 3);
verifyEqual(testCase, ...
    second.applied_counts.reused_config_profile_versions, 3);
verifyEqual(testCase, ...
    second.applied_counts.reused_project_profile_assignments, 3);
verifyEqual(testCase, ...
    second.applied_counts.reused_recording_profile_assignments, 2);
verifyEqual(testCase, countsAfterFirst, countsAfterSecond);
verifyEqual(testCase, countsAfterSecond, struct( ...
    projects=1, config_profiles=3, config_profile_versions=3, ...
    project_profile_assignments=3, source_files=1, entity_types=4, ...
    entities=4, entity_relationships=3, recordings=1, ...
    recording_entity_links=2, recording_profile_assignments=2));
verifyEqual(testCase, scalar(conn, ...
    "SELECT COUNT(*) AS n FROM ingestion_runs"), 2);
verifyEqual(testCase, scalar(conn, ...
    "SELECT COUNT(*) AS n FROM ingestion_files"), 2);
verifyEqual(testCase, string(fetch(conn, ...
    "SELECT status FROM ingestion_runs ORDER BY ingestion_run_id").status), ...
    ["completed"; "completed"]);
verifyEqual(testCase, first.profile_version_ids.profile_version_id, ...
    second.profile_version_ids.profile_version_id);
verifyTrue(testCase, all(second.project_profile_assignments.action == "reuse"));
verifyTrue(testCase, all(second.recording_profile_assignments.action == "reuse"));
verifyEqual(testCase, height(fetch(conn, "PRAGMA foreign_key_check")), 0);

clear cleanupRoot cleanupDb
rmpath(fullfile(repoRoot, "src"));
end

function testLinkedProfileChecksumConflictPreventsAuditWrite(testCase)
[conn, dbFile, repoRoot] = createDisposableDatabase();
cleanupDb = onCleanup(@() cleanupDatabase(conn, dbFile));
[ir, sourceRoot] = parsedIR(repoRoot, ...
    "example.project.mouse_courtship.folder_driven", ...
    fullfile("control", "mouse_001", "baseline", ...
    "001_baseline_1.wav"));
cleanupRoot = onCleanup(@() removeTree(sourceRoot));
options = namedargs2cell(struct( ...
    Apply=true, ProfileLinkagePath=linkagePath(repoRoot), ...
    RepoRoot=repoRoot));
vawlume.ingest.project(conn, ir, projectSpec(), options{:});
deviceVersionId = scalar(conn, ...
    "SELECT cpv.profile_version_id AS n FROM config_profile_versions cpv " + ...
    "JOIN config_profiles cp ON cp.profile_id = cpv.profile_id " + ...
    "WHERE cp.profile_key = 'example.device.ultrasonic_usb_primary'");
execute(conn, ...
    "UPDATE config_profile_versions SET checksum_sha256 = '" + ...
    string(repmat('b', 1, 64)) + "' WHERE profile_version_id = " + ...
    string(deviceVersionId));

result = vawlume.ingest.project(conn, ir, projectSpec(), options{:});

verifyEqual(testCase, result.status, "conflict");
verifyFalse(testCase, result.committed);
verifyTrue(testCase, any(result.issues.code == ...
    "LINKED_PROFILE_VERSION_CONFLICT"));
verifyEqual(testCase, scalar(conn, ...
    "SELECT COUNT(*) AS n FROM ingestion_runs"), 1);
verifyEqual(testCase, semanticCounts(conn).config_profile_versions, 3);

clear cleanupRoot cleanupDb
rmpath(fullfile(repoRoot, "src"));
end

function testSingularRecordingAssignmentConflictPreventsAuditWrite(testCase)
[conn, dbFile, repoRoot] = createDisposableDatabase();
cleanupDb = onCleanup(@() cleanupDatabase(conn, dbFile));
[ir, sourceRoot] = parsedIR(repoRoot, ...
    "example.project.mouse_courtship.folder_driven", ...
    fullfile("control", "mouse_001", "baseline", ...
    "001_baseline_1.wav"));
cleanupRoot = onCleanup(@() removeTree(sourceRoot));
options = namedargs2cell(struct( ...
    Apply=true, ProfileLinkagePath=linkagePath(repoRoot), ...
    RepoRoot=repoRoot));
vawlume.ingest.project(conn, ir, projectSpec(), options{:});
execute(conn, ...
    "INSERT INTO config_profiles " + ...
    "(profile_key, profile_name, profile_kind, is_builtin) VALUES " + ...
    "('test.device.alternate', 'Alternate device', 'recording_device', 1)");
alternateProfileId = scalar(conn, ...
    "SELECT profile_id AS n FROM config_profiles " + ...
    "WHERE profile_key = 'test.device.alternate'");
execute(conn, ...
    "INSERT INTO config_profile_versions " + ...
    "(profile_id, version_label, profile_schema_version, content_format, " + ...
    "content_uri, checksum_sha256, is_snapshot) VALUES (" + ...
    string(alternateProfileId) + ...
    ", '1', '0.1-draft', 'json', 'config/test_device.json', '" + ...
    string(repmat('c', 1, 64)) + "', 1)");
alternateVersionId = scalar(conn, ...
    "SELECT profile_version_id AS n FROM config_profile_versions " + ...
    "WHERE profile_id = " + string(alternateProfileId));
recordingId = scalar(conn, "SELECT recording_id AS n FROM recordings");
execute(conn, ...
    "INSERT INTO recording_profile_assignments " + ...
    "(recording_id, profile_version_id, assignment_role, " + ...
    "inheritance_source) VALUES (" + string(recordingId) + ", " + ...
    string(alternateVersionId) + ", 'recording_device', 'direct')");

result = vawlume.ingest.project(conn, ir, projectSpec(), options{:});

verifyEqual(testCase, result.status, "conflict");
verifyFalse(testCase, result.committed);
verifyTrue(testCase, any(result.issues.code == ...
    "RECORDING_PROFILE_ASSIGNMENT_CONFLICT"));
verifyEqual(testCase, scalar(conn, ...
    "SELECT COUNT(*) AS n FROM ingestion_runs"), 1);
verifyEqual(testCase, scalar(conn, ...
    "SELECT COUNT(*) AS n FROM recording_profile_assignments"), 3);

clear cleanupRoot cleanupDb
rmpath(fullfile(repoRoot, "src"));
end

function testMismatchedLinkageIsRejectedBeforeMutation(testCase)
[conn, dbFile, repoRoot] = createDisposableDatabase();
cleanupDb = onCleanup(@() cleanupDatabase(conn, dbFile));
[ir, sourceRoot] = parsedIR(repoRoot, ...
    "example.project.social_dyad.multi_subject", ...
    fullfile("cohort_01", "dyad_004", ...
    "D004_M012_F031_courtship.wav"));
cleanupRoot = onCleanup(@() removeTree(sourceRoot));

verifyError(testCase, @() vawlume.ingest.project( ...
    conn, ir, projectSpec(), Apply=true, ...
    ProfileLinkagePath=linkagePath(repoRoot), RepoRoot=repoRoot), ...
    "vawlume:ingest:ProfileLinkageMismatch");
verifyEqual(testCase, scalar(conn, "SELECT COUNT(*) AS n FROM projects"), 0);
verifyEqual(testCase, scalar(conn, ...
    "SELECT COUNT(*) AS n FROM ingestion_runs"), 0);

clear cleanupRoot cleanupDb
rmpath(fullfile(repoRoot, "src"));
end

function [ir, root] = parsedIR(repoRoot, profileId, relativePath)
root = string(tempname);
mkdir(root);
touchFile(fullfile(root, relativePath));
ir = vawlume.source_mapping.parse(projectProfilePath(repoRoot), root, ...
    ProfileId=profileId, RepoRoot=repoRoot);
end

function value = projectSpec()
value = struct(project_key="profile_linkage_test", ...
    project_name="Profile linkage test", ...
    description="Pass 5 tracked profile-linkage case.");
end

function value = semanticCounts(conn)
value = struct( ...
    projects=scalar(conn, "SELECT COUNT(*) AS n FROM projects"), ...
    config_profiles=scalar(conn, ...
    "SELECT COUNT(*) AS n FROM config_profiles"), ...
    config_profile_versions=scalar(conn, ...
    "SELECT COUNT(*) AS n FROM config_profile_versions"), ...
    project_profile_assignments=scalar(conn, ...
    "SELECT COUNT(*) AS n FROM project_profile_assignments"), ...
    source_files=scalar(conn, "SELECT COUNT(*) AS n FROM source_files"), ...
    entity_types=scalar(conn, "SELECT COUNT(*) AS n FROM entity_types"), ...
    entities=scalar(conn, ...
    "SELECT COUNT(*) AS n FROM experimental_entities"), ...
    entity_relationships=scalar(conn, ...
    "SELECT COUNT(*) AS n FROM entity_relationships"), ...
    recordings=scalar(conn, "SELECT COUNT(*) AS n FROM recordings"), ...
    recording_entity_links=scalar(conn, ...
    "SELECT COUNT(*) AS n FROM recording_entity_links"), ...
    recording_profile_assignments=scalar(conn, ...
    "SELECT COUNT(*) AS n FROM recording_profile_assignments"));
end

function [conn, dbFile, repoRoot] = createDisposableDatabase()
repoRoot = repoRootForTest();
addpath(fullfile(repoRoot, "src"));
dbFile = string(tempname) + ".sqlite";
conn = sqlite(char(dbFile), "create");
vawlume.db.applySchema(conn, fullfile(repoRoot, "schema", "schema.sql"));
end

function value = scalar(conn, sql)
rows = fetch(conn, sql);
value = double(rows.n(1));
end

function cleanupDatabase(conn, dbFile)
if isopen(conn)
    close(conn);
end
deleteIfExists(dbFile);
deleteIfExists(dbFile + "-journal");
deleteIfExists(dbFile + "-wal");
deleteIfExists(dbFile + "-shm");
end

function touchFile(path)
parent = string(fileparts(path));
if ~isfolder(parent)
    mkdir(parent);
end
fileId = fopen(path, "w");
assert(fileId ~= -1, "Test fixture file could not be created.");
cleanupFile = onCleanup(@() fclose(fileId));
fwrite(fileId, uint8([]));
clear cleanupFile
end

function removeTree(root)
if isfolder(root)
    rmdir(root, "s");
end
end

function deleteIfExists(path)
if isfile(path)
    delete(path);
end
end

function path = linkagePath(repoRoot)
path = fullfile(repoRoot, "config", "04_examples", ...
    "profile_linkage_example.json");
end

function path = projectProfilePath(repoRoot)
path = fullfile(repoRoot, "config", "01_mapping_profiles", ...
    "project_inputs", "project_input_source_mapping_examples.json");
end

function repoRoot = repoRootForTest()
repoRoot = fileparts(fileparts(fileparts(mfilename("fullpath"))));
end
