function result = matchingPlanResult(plan)
%MATCHINGPLANRESULT Project internal planning state into the public result.

if plan.has_conflicts
    status = "conflict";
else
    status = "planned";
end
result = struct( ...
    status=status, ...
    committed=false, ...
    has_conflicts=plan.has_conflicts, ...
    conflicts=plan.conflicts, ...
    recording=plan.recording, ...
    run_pair=plan.run_pair, ...
    configuration=plan.configuration, ...
    analysis=plan.analysis, ...
    algorithm=struct(key=plan.specification.algorithm_key, ...
        version=plan.specification.algorithm_version), ...
    min_temporal_iou=plan.specification.min_temporal_iou, ...
    detection_counts=struct(run_a=height(plan.detections.run_a), ...
        run_b=height(plan.detections.run_b)), ...
    candidate_count=height(plan.candidates), ...
    candidates=plan.candidates, ...
    unmatched_counts=struct( ...
        run_a=numel(plan.unmatched.run_a_detection_ids), ...
        run_b=numel(plan.unmatched.run_b_detection_ids)), ...
    unmatched_detection_ids=plan.unmatched);
end
