function [plan, counts] = matchingApplyPlan(conn, plan)
%MATCHINGAPPLYPLAN Atomically persist specification, parent, inputs, and edges.

if plan.has_conflicts
    error("vawlume:matching:PlanConflict", ...
        "A matching plan with identity conflicts cannot be applied.");
end
counts = emptyCounts();
if plan.analysis.action == "reuse"
    counts.reused_analysis_runs = 1;
    counts.reused_candidate_pairs = height(plan.candidates);
    return
end

oldAutoCommit = string(conn.AutoCommit);
if oldAutoCommit ~= "on"
    error("vawlume:matching:TransactionState", ...
        "Matching apply requires a connection with AutoCommit enabled.");
end
conn.AutoCommit = "off";
try
    [plan, counts] = applyConfiguration(conn, plan, counts);
    [plan, counts] = applyAnalysis(conn, plan, counts);
    commit(conn);
catch exception
    try
        rollback(conn);
    catch
    end
    conn.AutoCommit = oldAutoCommit;
    rethrow(exception);
end
conn.AutoCommit = oldAutoCommit;
end

function [plan, counts] = applyConfiguration(conn, plan, counts)
configuration = plan.configuration;
if configuration.profile_action == "create"
    configuration.profile_id = matchingInsertRow(conn, "config_profiles", struct( ...
        project_id=plan.recording.project_id, ...
        profile_key=configuration.profile_key, ...
        profile_name=configuration.profile_name, ...
        profile_kind=configuration.profile_kind, ...
        is_builtin=0, ...
        description="Versioned matching and consilience policy for one project."), ...
        "profile_id");
    counts.config_profiles = 1;
else
    counts.reused_config_profiles = 1;
end
if configuration.version_action == "create"
    configuration.profile_version_id = matchingInsertRow(conn, ...
        "config_profile_versions", struct( ...
        profile_id=configuration.profile_id, ...
        version_label=configuration.version_label, ...
        profile_schema_version=configuration.profile_schema_version, ...
        content_format=configuration.content_format, ...
        content_uri=configuration.content_uri, ...
        checksum_sha256=configuration.checksum_sha256, ...
        is_snapshot=1, ...
        notes="Exact matching specification used by a derived analysis."), ...
        "profile_version_id");
    counts.config_profile_versions = 1;
else
    counts.reused_config_profile_versions = 1;
end
plan.configuration = configuration;
end

function [plan, counts] = applyAnalysis(conn, plan, counts)
notes = "algorithm=" + plan.specification.algorithm_key + ...
    "@" + plan.specification.algorithm_version;
if strlength(plan.context.notes) > 0
    notes = plan.context.notes + " [" + notes + "]";
end
values = struct( ...
    project_id=plan.recording.project_id, ...
    run_type="cross_extractor_matching", ...
    run_key=plan.context.run_key, ...
    run_label=plan.context.run_label, ...
    vawlume_version=plan.context.vawlume_version, ...
    source_commit=plan.context.source_commit, ...
    status="started", ...
    notes=notes);
plan.analysis.analysis_run_id = matchingInsertRow(conn, "analysis_runs", ...
    values, "analysis_run_id");
counts.analysis_runs = 1;
matchingInsertRow(conn, "analysis_run_profiles", struct( ...
    analysis_run_id=plan.analysis.analysis_run_id, ...
    profile_version_id=plan.configuration.profile_version_id, ...
    assignment_role="matching_spec"));
counts.analysis_run_profiles = 1;
matchingInsertRow(conn, "analysis_run_extraction_inputs", struct( ...
    analysis_run_id=plan.analysis.analysis_run_id, ...
    extraction_run_id=plan.run_pair.run_a.extraction_run_id, ...
    input_role="run_a"));
matchingInsertRow(conn, "analysis_run_extraction_inputs", struct( ...
    analysis_run_id=plan.analysis.analysis_run_id, ...
    extraction_run_id=plan.run_pair.run_b.extraction_run_id, ...
    input_role="run_b"));
counts.analysis_run_extraction_inputs = 2;

for index = 1:height(plan.candidates)
    row = plan.candidates(index, :);
    matchingInsertRow(conn, "candidate_pairs", struct( ...
        analysis_run_id=plan.analysis.analysis_run_id, ...
        recording_id=plan.recording.recording_id, ...
        detection_a_id=row.detection_a_id, ...
        detection_b_id=row.detection_b_id, ...
        temporal_overlap_s=row.temporal_overlap_s, ...
        temporal_iou=row.temporal_iou, ...
        onset_difference_s=row.onset_difference_s, ...
        offset_difference_s=row.offset_difference_s, ...
        duration_difference_s=row.duration_difference_s, ...
        candidate_score=row.candidate_score, ...
        candidate_status=row.candidate_status, ...
        details_json=row.details_json), "candidate_pair_id");
end
counts.candidate_pairs = height(plan.candidates);
execute(conn, "UPDATE analysis_runs SET status='completed', " + ...
    "completed_at_utc=strftime('%Y-%m-%dT%H:%M:%fZ','now') " + ...
    "WHERE analysis_run_id=" + string(plan.analysis.analysis_run_id));
plan.analysis.action = "create";
end

function counts = emptyCounts()
counts = struct( ...
    config_profiles=0, config_profile_versions=0, analysis_runs=0, ...
    analysis_run_profiles=0, analysis_run_extraction_inputs=0, ...
    candidate_pairs=0, reused_config_profiles=0, ...
    reused_config_profile_versions=0, reused_analysis_runs=0, ...
    reused_candidate_pairs=0);
end
