function [candidates, unmatched] = matchingGenerateCandidates(runA, runB, pair, minIou)
%MATCHINGGENERATECANDIDATES Compute exhaustive transparent temporal evidence.
%
% Duration is the boundary-derived v_detection_core.duration_s surface. A
% start-ordered interval sweep compares only pairs with positive temporal
% overlap. Every qualifying edge survives; no best-candidate reduction occurs.

runA = sortrows(runA, ["start_time_s", "detection_id"]);
runB = sortrows(runB, ["start_time_s", "detection_id"]);
records = emptyRecords();
activeA = zeros(0, 1);
activeB = zeros(0, 1);
aIndex = 1;
bIndex = 1;

while aIndex <= height(runA) || bIndex <= height(runB)
    nextA = Inf;
    nextB = Inf;
    if aIndex <= height(runA), nextA = runA.start_time_s(aIndex); end
    if bIndex <= height(runB), nextB = runB.start_time_s(bIndex); end

    if nextA <= nextB
        activeB = activeB(runB.end_time_s(activeB) > nextA);
        for activeIndex = activeB'
            record = candidateRecord(runA(aIndex, :), runB(activeIndex, :), ...
                pair, minIou);
            if ~isempty(record)
                records(end + 1, 1) = record; %#ok<AGROW>
            end
        end
        activeA(end + 1, 1) = aIndex; %#ok<AGROW>
        aIndex = aIndex + 1;
    else
        activeA = activeA(runA.end_time_s(activeA) > nextB);
        for activeIndex = activeA'
            record = candidateRecord(runA(activeIndex, :), runB(bIndex, :), ...
                pair, minIou);
            if ~isempty(record)
                records(end + 1, 1) = record; %#ok<AGROW>
            end
        end
        activeB(end + 1, 1) = bIndex; %#ok<AGROW>
        bIndex = bIndex + 1;
    end
end

if isempty(records)
    candidates = emptyCandidateTable();
else
    candidates = struct2table(records, "AsArray", true);
    candidates.candidate_status = string(candidates.candidate_status);
    candidates.details_json = string(candidates.details_json);
    candidates = sortrows(candidates, ["run_a_detection_id", ...
        "run_b_detection_id"]);
end

matchedA = unique(candidates.run_a_detection_id);
matchedB = unique(candidates.run_b_detection_id);
unmatched = struct( ...
    run_a_detection_ids=runA.detection_id(~ismember(runA.detection_id, matchedA)), ...
    run_b_detection_ids=runB.detection_id(~ismember(runB.detection_id, matchedB)));
end

function record = candidateRecord(runA, runB, pair, minIou)
intersection = max(0, min(runA.end_time_s, runB.end_time_s) - ...
    max(runA.start_time_s, runB.start_time_s));
union = max(runA.end_time_s, runB.end_time_s) - ...
    min(runA.start_time_s, runB.start_time_s);
temporalIou = intersection / union;
if intersection <= 0 || temporalIou < minIou
    record = [];
    return
end
runAId = runA.detection_id;
runBId = runB.detection_id;
record = struct( ...
    run_a_detection_id=runAId, ...
    run_b_detection_id=runBId, ...
    detection_a_id=min(runAId, runBId), ...
    detection_b_id=max(runAId, runBId), ...
    temporal_overlap_s=intersection, ...
    temporal_iou=temporalIou, ...
    onset_difference_s=runB.start_time_s - runA.start_time_s, ...
    offset_difference_s=runB.end_time_s - runA.end_time_s, ...
    duration_difference_s=runB.duration_s - runA.duration_s, ...
    candidate_score=temporalIou, ...
    candidate_status="eligible", ...
    details_json=jsonencode(struct( ...
        evidence_direction="run_a_to_run_b", ...
        run_a_extraction_run_id=pair.run_a.extraction_run_id, ...
        run_b_extraction_run_id=pair.run_b.extraction_run_id, ...
        run_a_detection_id=runAId, ...
        run_b_detection_id=runBId, ...
        schema_detection_order="ascending_detection_id", ...
        eligibility_rule="positive_overlap_and_min_temporal_iou", ...
        min_temporal_iou=minIou)));
end

function records = emptyRecords()
records = struct( ...
    run_a_detection_id={}, run_b_detection_id={}, ...
    detection_a_id={}, detection_b_id={}, temporal_overlap_s={}, ...
    temporal_iou={}, onset_difference_s={}, offset_difference_s={}, ...
    duration_difference_s={}, candidate_score={}, candidate_status={}, ...
    details_json={});
end

function candidates = emptyCandidateTable()
candidates = table(zeros(0, 1), zeros(0, 1), zeros(0, 1), zeros(0, 1), ...
    zeros(0, 1), zeros(0, 1), zeros(0, 1), zeros(0, 1), zeros(0, 1), ...
    zeros(0, 1), strings(0, 1), strings(0, 1), ...
    VariableNames=["run_a_detection_id", "run_b_detection_id", ...
    "detection_a_id", "detection_b_id", "temporal_overlap_s", ...
    "temporal_iou", "onset_difference_s", "offset_difference_s", ...
    "duration_difference_s", "candidate_score", "candidate_status", ...
    "details_json"]);
end
